<style>
    .panel-body{padding: 15px 10px 0 10px;}
    .form-control{width:95%;}
    textarea{resize:none;}

    .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
        padding: 4px;
        vertical-align: top;
    }

    [id^="feeheads_total"],[bgcolor*="#ccf5ff"]>span{font-weight:bolder;font-size:1.1em;
     /* border:1px inset #ddd;*/
     /*padding: 4px;*/
 }
 [id^="cat_total"],[bgcolor*="#b3ecff"]{
    font-weight:bolder;font-size:1.3em;
    /*border:1px inset #ddd;*/
    /*padding: 4px;*/

}


</style>
<script src="<?php echo $this->mainconfig['publicpath']; ?>js/jquery-ui.min.js"></script>


<?php
//error_reporting(0);
$date = new Zend_Date();
$col_span = 2 + count($this->term_data);
?>
<tr class="purchase-quatation-items-close ">
    <td colspan="6">
        <div class="purchase-quatation-items" style="display: block;"><div class="col-sm-12 " >
            <div id="log1">  
                <div class="panel panel-default bor" >
                    <div class="panel-body" style="">
                        <div>
                            <div class="col-sm-12" width="99%"><center>
                                <div class="form-group bor">

                                    <label class="control-label"><strong><h4><u>Tuition Fee Collection</u></h4></strong></label>
                                </div></center>
                            </div>

                        </div>
                    </div>
                    <div class="row" style="margin-bottom:5px;" >
                        <div class="col-sm-12">
                            <div class="form-group bor" >
							 <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
                                <?php if (count($this->term_data) != 0) { ?>
								
								<center>
								<?php $this->studetails;
			                          $this->acad_details;  
									
								 ?>
								
								<label class="control-label"><strong><h4><u><?=$this->term_data['term_name']?></u></h4></strong></label>
								            <h5><?php echo ($this->studetails['stu_fname']); ?>, Department -<?php echo ($this->acad_details['batch_code']); ?></h5></center>
                                    <table class="table table-striped table-bordered mb30 table bulk_action" id="dataTable" border="0" >
                                        <thead>
                                            <tr align="center" style="background-color:#1b4965;color:#f0f8ff	">
                                                <th rowspan="2" style="text-align:center;">S.No.</th>
                                                <th rowspan="2" style="text-align:center;">Particulars</th> 
                                                <th rowspan="2" style="text-align:center;">Total Fees</th> 
												<th rowspan="2" style="text-align:center;">Total Paid</th> 
                                                <th rowspan="2" style="text-align:center;">Total Dues</th> 
												<th style="text-align:center;">Payment Amount</th>
                                            </tr>
                                            <tr>
                                                <?php 
												
												

												if (($this->term_data) > 0) { 
												$term_details=$this->term_data;
												?>
                                                    <?php //foreach ($this->term_data as $term_details) { ?>
                                                        <?php $inc = $key + 1; ?>
                                                        <input type ="text" style="display:none;" value="<?= $term_details['term_id']; ?>" name='term_id' > 
                                                       <input type ="hidden" value="<?= $this->studetails['student_id']; ?>" name='student_id' > 
													    <input type ="hidden" value="<?= $this->acad_details['academic_year_id']; ?>" name='academic_year_id' >


														
                                                    <?php  //}  ?>

                                                <?php } ?>
                                                <!-- <th rowspan="3" bgcolor="#f7ffe6" style="text-align:center;">Total (Rs.)</th> -->
                                            </tr>
                                            <tr>
                                                <!-- <td colspan="2" bgcolor="#ffffcc">Due Date for Payment</td> -->
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
											$account =  new Application_Model_Account();
											 //echo "<pre>"; print_r($term_details); die();
                                                // print_r($this->academics_data);
                                                // $i=1;
                                            $letters = array('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z');
                                            $i = 0;
                                            if (!empty($this->academics_data)) {
                                                ?>





                                                <?php
                                                //print_r($this->academics_data);
                                            } else {

                                                  			
                                                if (($this->Category_data) > 0) {
                                                    $fee_head = $this->Feeheads_data;
                                                        //echo '<pre>'; print_r($this->Category_data['feecategory_id']); 
                                                    foreach ($this->Category_data as $key => $categories) {
                                                            //  print_r($fee_head[$key]['feecategory_id']);
                                                        ?>

                                                        <tr>
                                                           <!-- <td align="center"><?php //echo $letters[$i]; ?></td> -->

                                                           <!-- <td bgcolor="#f7ffe6" ></td> -->

                                                       </tr>
                                                       <?php
                                                       $j = 1;
                                                       $term1_cat_tot = 0;
                                                       $term2_cat_tot = 0;
                                                       $term3_cat_tot = 0;
                                                       $term4_cat_tot = 0;
                                                       $term6_cat_tot = 0;
													    
                                                       foreach ($this->Feeheads_data as $keys => $vals) {
                                                                //print_r($);die()
                                                        if ($categories['category_id'] == $vals['feecategory_id']) {
                                                            ?>
                                                            <tr>
                                                                <td align="center"><?php echo $j; ?><input type="hidden" name="terms[count][]" value="<?php echo $j; ?>"/></td>
                                                                <td><?php echo $vals['feehead_name']; ?><input type="hidden" name="feehead_id[]" id="feehead_id<?php echo $j; ?>" value="<?php echo $vals['feehead_id']; ?>" /></td>



                                                                <?php
                                                                $TermItems_model = new Application_Model_FeeStructureTermItems();
                                                                $cat_ids = $categories['category_id'];
                                                                $fhead_ids = $vals['feehead_id'];

                                                              //  foreach ($this->term_data as $key => $term_details) {
																  
																 $term_details=$this->term_data;
																  //print_r($this->fee_acad_details);die();
                                                                    ?>
                                                                    <?php $inc =  1; ?> 
                                                                    <?php $term1_result = $TermItems_model->getFeesRecords($this->structure_id, $cat_ids, $fhead_ids, $term_details['term_id']); ?>
                                                                    

																	<td> <input type="hidden" name="terms_amt_head[]" id="terms_amt_head" value="<?php echo $term1_result['fees'] ?>" /><?php echo $term1_result['fees']; ?></td>
																	<td><?php echo $this->fee_acad_details[$keys]['paidamt']; ?></td>	
																	<td><input type="hidden" name="terms_dues_head[]" id="terms_amt_head" value="<?php echo $term1_result['fees']-$this->fee_acad_details[$keys]['paidamt']; ?>" /><?php echo $term1_result['fees']-$this->fee_acad_details[$keys]['paidamt']; ?></td>	
                                                                    <td>  <input type="text" name="pay_amt[]" id ="term<?php echo $j; ?>_<?= $inc; ?>"  class="form-control-sm term<?= $inc; ?><?php echo $categories['category_id']; ?> term payamt" style="text-align:right;"/></td>
                                                                    <?php //} ?>

                                                                </tr>

                                                                <?php
                                                            }
                                                            $j++;
															$term1_cat_tot += $term1_result['fees'];
															 $ttotalduesamt +=    $term1_result['fees']-$this->fee_acad_details[$keys]['paidamt'];   
															 $ttotalpaysamt +=	$this->fee_acad_details[$keys]['paidamt'];
															 
                                                        }
                                                        ?>
                                                         <input type="hidden" name="terms_amt" id="count_i" value="<?php echo $term1_cat_tot ?>" />
                                                        <input type="hidden" name="terms[count_i][]" id="count_i" value="<?php echo $i; ?>" />
                                                        <?php $i++;
                                                    }
                                                    ?>

                                                    
                                                <?php }
                                            } //else { 
                                                ?>
												<tr style="background-color: #aaa9e3";>
												
												<? //print_r($this->accounts);?>
                                                    <td colspan="1"></td>
													<td colspan="1"> Discount : </td>
													<td><?php //echo $term1_cat_tot ?></td>
													<td><?php echo $this->discount ?></td>
													<td colspan="1"><?php //echo $this->discount ?></td>
													<td colspan="1"><input type="text" name="discount" id="discount"  value="<?php //echo $ttotalduesamt ?>"></td>
                                                    
                                                </tr> 
												
                                                <tr style="background-color: #a9e3e3";>
												
												<? //print_r($this->accounts);?>
                                                    <td colspan="1"></td>
													<td colspan="1"> Total Amount : </td>
													<td><?php echo $term1_cat_tot ?></td>
													<td><?php echo $ttotalpaysamt+$this->discount ?></td>
													<td colspan="1"><?php echo $ttotalduesamt-$this->discount ?></td>
													<td colspan="1"><input type="text" name="sumtotal" id="sumtotal"  value="" readonly></td>
                                                    
                                                </tr> 
												 <tr>
												
												<? //print_r($this->accounts);?>
                                                    <td colspan="1" class="td_2">Payment Mode</td>
                                                    <td colspan="1" class="td_2"><?php echo $this->form->payment_mode?></td>
													<td colspan="1" class="td_4">Account</td>
                                                    <td colspan="1" class="td_4"><?php echo $this->form->account_id?></td>
													<td class="td_1">Transactio ID : <input type="text" name="transaction_id"></td>
													<td class="td_3">Check/DD No : <input type="text" name="check_dd"></td>
													<td class="td_3">Remarks : <input type="text" name="remarks"></td>
                                                    <td>Date :<input type="date" name="paid_date" value="<?=date('Y-m-d')?>"><input name="userid" type="hidden" value="<?=$this->userid?>"></td>
                                                </tr>
                                                 <tr><td colspan="6"><center><strong><input type="submit" class ="btn btn-success"id="pay_collect" value="Pay Now"></strong></center></td></tr> 
												
                                                <?php //}  ?>	
                                            </tbody>
                                        </table>
                                    <?php } else { ?>
                                        <table width="99%" class="table table-striped table-bordered mb30 table bulk_action" border="0" >
                                            <thead>
                                                <tr>
                                                    <th class="text-center">No Terms</th>
                                                </tr>
                                            </thead>
                                        </table>
                                    <?php } ?>
									</form>
                                </div>
                            </div>
                        </div>
                       

                    </div>
					<div class="col-sm-12">
					  <center> <label> Transaction Details </label></center>
					  
					  <table width="99%" class="table table-striped table-bordered mb30 table bulk_action" border="0">
					    <thead><tr><th>ID</th><th>Transaction date</th><th>Bank Name</th><th>Amount</th><th>Action</th></tr></thead>
					     <tbody>
						 <?php  foreach($this->allrecords as $record) { ?>
						 <tr>
						<td>#<?=$record['id']?></td>
						<td><?=date('d-m-Y',strtotime($record['paid_date']))?></td>
						<td><? if($record['bank_id']==0) { echo 'Cash'; } else { echo $account->getRecord($record['bank_id'])['acc_name']; }?></td>
						<td><?=$record['paid']?></td>
					    <td><a target="_blank" href="<?php echo $this->mainconfig['host']; ?>fee-collection/printslip/stuid/<?=$record['s_id']?>/collect/<?=$record['collect_id']?>/hid/<?=$record['id']?>">Print</a></td>
						 </tr>
						 
						 <?php } ?>
						 </tbody>
					  </table>
					   
					   </div>
                </div>
            </div>

        </div>
    </div>
</td>
</tr>

<style type="text/css">
    /*  .bor {border:1px solid #ccc; } */
    .table { margin-bottom: 0px !important;width: 100%;}
    .employee_class {margin-left: 4% !important;margin-right: 4% !important;}
    .panel-footer {padding: 5px;}
    .panel {margin-bottom: 10px !important;}
    a:hover{cursor:pointer;}
</style>

<script>

function sumOfIncome() {
  var sum = 0;
  $('.payamt').each(function() {
    sum += parseInt(this.value) || 0;
    console.log(sum)
  });
  $('#sumtotal').val(sum);
}
$('.payamt').blur(function() {
  sumOfIncome();
})


 setDatatables();
	
	
 
	
    function payNow() {
		alert('1');
		
		
       /*  let total = 0;
        let total_amt = <?php echo $this->total ?>;
        $('.term').each( function () {
            if (!$(this).val()) {
                $(this).val(0);
            }
            total += parseFloat($(this).val());
            console.log(total);
        });
        $('.term').each( function () {
            let term = $(this).attr('id').split('term')[1];

            $.ajax({
                type: "POST",
                url: "<?php echo $this->mainconfig['host'] . 'fee-collection/ajax-pay-fee-structure'; ?>",
                data: {
                    head_id: term, 
                    student_id: <?php echo $this->stid; ?>,
                    paid_amount: $(this).val(),
                    account: $('#account_num').val(),
                    total_paid: total,
                    total_due: total_amt - total,
                }

            }).done(function (data) {
                console.log(data);

                // $("#structure_data").empty('');

                // $("#structure_data").html(data);
            // $(".load-box").hide();

            });
        }); */
    }
$(document).ready(function() {
    $(".td_1").hide();
	$(".td_3").hide();
	$(".td_4").hide();
	
	
	$('#payment_mode').change(function(){

      var pay = $('#payment_mode').val();
	  
	  if(pay==='2') {
		  
		  $(".td_1").show();
		  $(".td_4").show();
		  $(".td_3").hide();
	  } 
	  else if(pay==='3') {
		  $(".td_3").show();
		   $(".td_4").show();
		   $(".td_1").hide(); 
	  }
	  else {
		  $(".td_1").hide(); 
		   $(".td_3").hide();
		   $(".td_4").hide();
	  }

		});
		
		
 
			
			
	
});



</script>
