<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

	<thead>

		<tr>

			<th style="text-align:center;" >S.  No.</th>												

			<!-- <th style="text-align:center;" >Course Category Name</th>-->
			<th style="text-align:center;" >Student Name</th>
			<th style="text-align:center;" >Cast Category</th>
			<th style="text-align:center;" >Total Amount</th>
            <th style="text-align:center;" >Total Paid</th>
			<th style="text-align:center;" >Discount</th>
			<th style="text-align:center;" >Total Due</th>
			<th style="text-align:center;" >Extra Charges</th>
			<th style="text-align:center;" >Default Due Date</th>
			<th style="text-align:center;" >Student Due Date</th>

			<th class="no_print"  style="text-align:center;" >Action</th>

		</tr>

	</thead>

	<tbody style="text-align:center;" >

		<?php
		$i = 1;
 $fee_collector_model = new Application_Model_FeeCollector();
 $fee_schedule = new Application_Model_Tuitionfees();
$duesdate_model= new Application_Model_DuesDate();
     	//print_r($this->termdata['year_id']); die();      
		$pagination_tr = '';

		if (count($this->paginator) != 0) {

                   
	foreach ($this->paginator as $results) {
		
   // $total_fees=$this->semFee[$results['academic_id']];
  $dedate=  $fee_schedule->getENDdate($this->termdata['year_id'],$this->termdata['session'],$results['academic_id']);
   
 $dedatedue=  $duesdate_model->getTotalfee($results['student_id']);
 
  $total_fees= $results['totfeess'];
	  $result1 = $fee_collector_model->get_student_paid($results['student_id'],$this->termdata['term_id']);
	  $records= $duesdate_model->getTotalpaidfeebystu($results['student_id'],$this->termdata['term_id'],$results['academic_id'],$this->termdata['session']);
	  // echo "<pre>"; print_r($dedate); 
	 
    $due_fees = round($total_fees-$result1['totalpaid']-$result1['discount']);
              
				?>

				<tr>

					<td><?php
					echo $i;



					$i++;
					?>

				</td>						





		
				<td><?php echo $results['stu_fname']; ?></td>
				 <td><?php echo $results['castname']; ?></td>
				 <td><?php echo $results['totfeess']; ?></td>
		       
				<!--<td><?php 
				/*  if($this->termdata['cmn_terms']!='') {
				     switch ($this->termdata['cmn_terms']) {
                        case "t1":
                        echo "Sem-1";
                        break;
                        case "t2":
                        echo "Sem-2";
                        break;
                        case "t3":
                        echo "Sem-3";
                        break;
                        case "t4":
                        echo "Sem-4";
                        break;
                        case "t5":
                        echo "Sem-5";
                        break;
                        case "t6":
                        echo "Sem-6";
                        break;
                        default:
                        echo "n/a";
                         }
				
				 }
				 else {
					 
					 switch ($this->termdata['year_id']) {
                        case "1":
                        echo "First Year";
                        break;
                        case "2":
                        echo "Second Year";
                        break;
                        case "3":
                        echo "Third Year";
                        break;
                        case "4":
                        echo "Forth Yeat";
                        
                        break;
                        default:
                        echo "n/a";
                         } 
					 
				 } */
				
				?></td> -->
				<td><?php echo $result1['totalpaid'];  ?></td>
				<td><?php echo $result1['discount'];  ?></td>
				 <td><?php echo $due_fees; ?></td>
				 <td><?php echo $result1['extra_charges'];  ?></td>
				 <td><?php echo date('d-m-Y',strtotime($dedate['end_date'])); ?></td>
				 <td id="defaultdate<?=$i?>">
				 <input type="hidden" name="studentid" id="studentid<?=$i?>" value="<?=$results['student_id']?>">
				 <input type="hidden" name="termid" id="termid<?=$i?>" value="<?=$this->termdata['term_id']?>">
				 <input type="hidden" name="acadid" id="acadid<?=$i?>" value="<?=$results['academic_id']?>">
				 <input type="hidden" name="sessionid" id="sessionid<?=$i?>" value="<?=$this->termdata['session']?>">
				 <?php 
				 
				 if($records['dues_date'] && $records['dues_date']!='0000-00-00') { echo date('d-m-Y',strtotime($records['dues_date'])); }
				 
				 else {
						echo  date('d-m-Y',strtotime($dedate['end_date']));

				 }					 
				  ?>   </td>
				  <td id="duesdate<?=$i?>"><input type="date" name="dues_date" id="chgduedate<?=$i?>" value="<?=$dedate['end_date']?>"></td>
				  <td> <a href="#" id="onduesdate<?=$i?>" title="Change Due Date"><span class="fa fa-calendar"><span></a> <a href="<?php echo $this->mainconfig['host']; ?>fee-collection/paycast?stid=<?php echo $results['student_id'] ?>&academic=<?php echo $results['academic_id'] ?>&term=<?=$this->semester?>&collection_id=<?php echo $result1['id'] ?>&cast=<? echo $results['castid'] ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>



			</tr>            
            <script>
			$('#duesdate<?=$i?>').hide();
			
			$('#onduesdate<?=$i?>').click(function () {
				
				$('#duesdate<?=$i?>').show();
				$('#defaultdate<?=$i?>').hide();
				
				
				
			})
	$('#chgduedate<?=$i?>').change(function () {
				var duessdate = $(this).val();
				var stuid = $('#studentid<?=$i?>').val();
				var termid = $('#termid<?=$i?>').val();
				var acadid = $('#acadid<?=$i?>').val();
				var sessionid = $('#sessionid<?=$i?>').val();
				if (duessdate) {
             $.ajax({
				type: "POST",
				url: '<?php echo $this->mainconfig['host'] . 'fee-collection/ajax-update-dues-date'; ?>',
				data: {duessdate: duessdate,stuid:stuid,termid:termid,acadid:acadid,sessionid:sessionid}
			}).done(function (data) {
                 
				 if(data==='1') {
					location.reload();
				 }
        })
			}
    });
			
			</script>


			<?php
		}

		$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
	}
	?>



</tbody>

</table>
<script>


	setDatatables();
</script>