<div class="right_col">
	<div class="padding-md">
		<div class="row">
			<div class="col-md-12 " >
				<h3 class="page-title txt-color-blueDark" >
					<div><i class="fa fa-eye"> Fee Collection</i></div>
				</h3>
				<div class="panel panel-default">
					<!-- <form class="no-margin" id="formValidate1" action="<?php // echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
						<div class="panel-body">
							<div class="row">
								<div class="col-sm-12 col-md-3">
									<div class="form-group">
										<label class="control-label"> Session <span class="asterisk">*</span></label>
										<?php // echo $this->form->session_id; ?>
									</div>
								</div>
							</div>
						</div>
					</form> -->
				</div>
			</div>
		</div>
		<!-- <div id="ajaxData"></div> -->
	</div>
</div>
<div class="load-box" style="top:0px;">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>

<script>
	// $('#session_id').change( function() {
	// 	let session_id = $('#session_id').val();
	// 	if (session_id) {
	// 		$('.load-box').show();
	// 		$.ajax({
    //             type: "POST",
    //             url: '<?php echo $this->mainconfig['host'] . 'fee-collection/ajax-get-students'; ?>',
    //             data: {session_id: session_id}
    //         }).done(function (data) {
    //             $('#ajaxData').empty('');
    //             $('#ajaxData').html(data);
    //             $('.load-box').css('display','none');
    //         });
	// 	}
	// });
</script>
