<div class="right_col">
    <div class="panel panel-default"> 
               
            <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Get Document Upload  Status by Application Number </i>

                    </h3>
                </div>
            </div>
                <div class="panel-body cont">
                </div>
                <div class="col-md-12">
                   
                    <span id="updatemsg" style="color:green;"></span>
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label" style="float:left;">Enter Your Application Number:<span class="asterisk">*</span></label>
                            <input type="text" name="a_id" id="a_id" value="" class="form-control" placeholder="A-2020-XXXX" pattern="\d+" title="xxx.." autocomplete="off">
                        </div>
                   </div><hr>
                <div style="float:left;padding-left:10%;">
                    <button class="btn btn-primary submit" id="app_id_submit">Submit</button>
                </div>
                </div>
                 <div class="col-md-12">
                   <div class="table-responsive" id="studentData"> 
                       
                    </div>
                </div>
                
            </div>    
           

        </div>
</div>
<script>
$("#app_id_submit").click(function(){
    //alert('kk');
    var a_id= $('#a_id').val().trim();
        if (a_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'global-settings/ajax-get-student-info-for-document-unlock'; ?>',
                data: {a_id: a_id}
            }).done(function (data) {
                $('#studentData').empty('');
                $('#studentData').html(data);
            });
        }else{
        alert('Please enter application number.');
        }
});


</script>