 <div class="col-md-12">
                   
    <?php 
         if(!empty($this->resultData)) { 
            // echo '<pre>'; print_r($this->resultData);exit;

     ?>
                         <div class="table-responsive" id="studentData"> 
                         <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">
                             <thead>
                                 <tr>
                                    <th class="no-sort">S.No.</th>
                                    <th>Applicant Name</th>
                                    <th>Application No</th>
                                    <th>Form Id</th>
                                    <th>Department</th>
                                    <th>Action</th>

                                 </tr>
                             </thead>
                             <tbody>
                         <tr>

                             <td><?php echo '1'; ?></td>						
                             <td><?php echo $this->resultData['applicant_name']; ?></td>
                             <td><?php echo $this->resultData['application_no']; ?></td>
                             <td><?php echo $this->resultData['form_id']; ?></td>
                             <td><?php echo $this->resultData['department_type']; ?></td>
                             
                             
                             <td id="unlockBtn">
                                 <input type="hidden" name="a_id" id="a_id" value="<?= $this->resultData['application_no'] ?>" />
                                  <?php if($this->resultData['status'] == 2){
                                      echo '<span style="color:red" class="fa fa-lock fa-lg"></span>';}else{
                                          echo '<span style="color:green" class="fa fa-unlock fa-lg"></span>'; 
                                        }?>
                              </td>
                         </tr>            

                     <?php

                     }else{?>
                         <td colspan="7"><b style="text-align: center;">Oop's..! Form id not exists. </b></td>
                     <?php }

                 ?>

             </tbody>
         </table>
     </div>
 </div>
    
    
    <script>
   $("#unlockBtn").click(function(){
    //alert('kk');
    var a_id= $('#a_id').val().trim();
  
        if (a_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'global-settings/ajax-document-unlock'; ?>',
                data: {a_id: a_id}
            }).done(function (data) {
                $('#unlockBtn').empty('');
                $("#unlockBtn").append("<span style='color:green' class='fa fa-unlock fa-lg'></span>");
                
            });
        }
});
    
    </script>