<?php 

$term_result = $this->term_result;

for($i=0;$i<count($term_result);$i++) {   ?>
 <div class="box-body">
	<h4 style="background-color:#3c8dbc;padding:8px 8px;color:white;"><?php echo $term_result[$i]['term_name'];?></h4>
	<div style="overflow-x:scroll">
	<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
<thead>
					<tr>
						<th rowspan="2">S. No.</th>
						<th rowspan="2">Name of Participants</th>
						<th rowspan="2">ID Number</th>
						<th>Course</th>
						<?php 
						
						$Corecourselearning_model =  new Application_Model_Corecourselearning();
							$result = $Corecourselearning_model->getcorecourses($term_result[$i]['academic_year_id'],$term_result[$i]['term_id']);
							
							foreach($result as $k => $val) {
							?>
							<th><?php echo 	$val['course_name']; ?></th>
							<?php } ?>
						<th>Grade Point Average</th>
					</tr>
					<tr>	
						<th>Credits</th>
						<?php foreach($result as $k => $val) {
							?>
						<th><?php echo $val['credit_value']; ?></th>
						<?php } ?>
						<th></th>
					</tr>
				</thead>
				<tbody>
				<?php $StudentPortal_model = new Application_Model_StudentPortal(); 
				 $category_data=$StudentPortal_model->getstudentsdetails($term_result[$i]['academic_year_id']);
				 $m = 1;
				 $total = 0;
				
				 foreach($category_data as $stu_data) { ?>
					
							<tr>
								<td><?php echo $m; ?></td>						
								
								<td><?php echo $stu_data['students']; ?></td>
								
							<input type="hidden" name="course[student_id_<?php echo $term_result[$i]['term_id'];?>][]" id="student_id" value="<?php echo $stu_data['student_id']; ?>" />
								<td><?php echo $stu_data['stu_id']; ?></td>
								<td></td>	
								<?php $total_credit_value = 0;
										$tot_grade = 0;
										 $total_grade = 0;
										$academic_courses = '';
										$academic_credits = '';
										$academic_grades = '';
									foreach($result as $k => $val) {
									$GradeAllocationReport_model = new Application_Model_GradeAllocationReport(); 
									$grade_point = $GradeAllocationReport_model->getGradePointValue($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$val['course_id'],$stu_data['student_id']);
									$academic_courses = $academic_courses.$val['course_id'].",";
									$academic_credits = $academic_credits.$val['credit_value'].",";
									$academic_grades = $academic_grades.$grade_point['grade_point'].",";
									?>
									<td><?php if($grade_point['grade_point'] == '')
{ $grade = '0'; } else { $grade = $grade_point['grade_point'];  } echo $grade; 
										$total_grade += $grade*$val['credit_value']; 
									
							?></td>
								<?php  $total_credit_value  += $val['credit_value']; 
									
										} $tot_grade += ($total_grade)/($total_credit_value ); ?>

								<td><?php echo number_format($tot_grade,3); ?></td>
<input type="hidden" name="course[academic_courses_<?php echo $term_result[$i]['term_id']; ?>][]" id="academic_courses" value="<?php echo  $academic_courses; ?>" />
<input type="hidden"  name="course[academic_credits_<?php echo $term_result[$i]['term_id'];?>][]"  id="academic_credits" value="<?php echo $academic_credits; ?>" />
<input type="hidden" name="course[academic_grades_<?php echo $term_result[$i]['term_id'];?>][]" id="academic_grades" value="<?php echo $academic_grades; ?>" />
<input type="hidden" name="course[total_academic_grade_<?php echo $term_result[$i]['term_id'];?>][]" id="total_academic_grade" value="<?php $tot = number_format($tot_grade,3); echo $tot; ?>" />

							</tr>  
				 <?php $m++; } ?>	
				</tbody>
	</table>

</div>
</div>

<?php } ?>