<tr class="sub">
<td colspan="3">
         <div class="col-sm-2" style="float:right;"><button class="close_tr btn btn-primary">Close</button></div>
<br></br>
    <?php
$item_result = $this->result1;

$i = 1;

	$EvaluationComponents_model = '';
	
 for($i=0;$i<count($item_result);$i++) {   ?>

 <div class="box-body">
	<h4 style="background-color:#3c8dbc;padding:8px 8px;color:white;"><?php echo $item_result[$i]['term_id'].'-'.$item_result[$i]['course_name']; ?></h4>
	<div style="overflow-x:scroll">
	<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th rowspan="2">S. No.</th>
						<th rowspan="2">Name of Participants</th>
						<th rowspan="2">ID Number</th>
						<th>Component</th>
						<?php 
						
						$item_result = $this->result1;
							
							foreach($item_result as $k => $val) {
							?>
							<th><?php echo 	$val['component_name']; ?></th>
							<?php } ?>
						<th>Course Grade Point</th>
					</tr>
					<tr>
						
						
						<th>Weightage</th>
						<?php foreach($item_result as $k => $val) {
							?>
						<th><?php echo $val['weightage']; ?></th>
						<?php } ?>
						<th></th>
					</tr>
				</thead>
				<tbody>
				
					
							<tr>
								<td><?php echo $m; ?></td>						
								
								<td><?php echo $stu_data['students']; ?></td>
								
								<td><?php echo $stu_data['stu_id']; ?></td>
								<td></td>
								
								<td><?php echo $grade_value;?></td>
								
							</tr>  
				 <?php  }  ?>							

				</tbody>
			</table>
			</div>
	</div>
	<div id="addmore_items_<?php echo $i;?>"></div>
				<br>
<?php  // }  ?>

</td>
</tr>
<script>
    $(".close_tr").click(function() {
            $( ".sub" ).hide();
     });
</script>