<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
                    <?php
                    if($this->type == 'edit'){
                        ?>
                        <h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Courses Wise Penalties</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					<div class="row">
						<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch:</label>
                                <?php echo $this->academic_batch['short_code']; ?>
                            </div>
							</div>
							<?php /* <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->year; ?>
                            </div>
							</div>	 */ ?>
						<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year:</label>
                              <?php if($this->year_id == 1){ echo 'First Year'; } else if($this->year_id == 2){ echo 'Second Year'; } ?>                              
                            </div>
						</div>
												
					</div>
					<div class="row">
							<div class="col-sm-3">
							<div class="form-group">
							<input type="text" id="batch" class="form-control"  style="background-color:#fdf59a;" readonly /></div>
							</div>
							</div>
					<div class="row">
                                            <div id="course_grade_details">
                                                <table>
                                               <tr class="sub">
<td colspan="5">


<?php 

$term_result = $this->term_result;

for($i=0;$i<count($term_result);$i++) {   ?>
 <div class="box-body">
	<h4 style="background-color:#3c8dbc;padding:8px 8px;color:white;"><?php echo $term_result[$i]['term_name'];?></h4>
	<div style="overflow-x:scroll;width:1043px;">
	<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
<thead>
					<tr>
						<th rowspan="2">S. No.</th>
						<th rowspan="2">Name of Participants</th>
						<th rowspan="2">ID Number</th>
						<th>Course</th>
						<?php 
						
						 $Corecourselearning_model =  new Application_Model_Corecourselearning();
							$result = $Corecourselearning_model->getcorecourses($term_result[$i]['academic_year_id'],$term_result[$i]['term_id']);	//print_r($result);exit;
                                                        //echo $term_result[$i]['academic_year_id'].$term_result[$i]['term_id'];exit;
							foreach($result as $k => $val) {
							?>
							<th><?php echo 	$val['course_name']; ?></th>
							<?php } ?>
						
					</tr>
					<tr>
	
						<th>Credits</th>
						<?php foreach($result as $k => $val) {
							?>
						<th><?php echo $val['credit_value']; ?></th>
						<?php } ?>
						
					</tr>
				</thead>
				<tbody>
					<?php $StudentPortal_model = new Application_Model_StudentPortal(); 
				 $category_data=$StudentPortal_model->getstudentsdetails($term_result[$i]['academic_year_id']);
				 $m = 1;
				 $total = 0;
				 foreach($category_data as $stu_data) { ?>
					
							<tr>
								<td><?php echo $m; ?></td>						
								
								<td><?php echo $stu_data['students']; ?></td>
								
								<input type="hidden" name="student[student_id_<?php echo $term_result[$i]['term_id'];?>][]" id="student_id" value="<?php echo $stu_data['student_id']; ?>" />
								<td><?php echo $stu_data['stu_id']; ?></td>
								<td></td>	
								<?php $total_credit_value = 0;
										$tot_grade = 0;
										$academic_courses = '';
										$academic_credits = '';
										$academic_grades = '';
									foreach($result as $k => $val) {
									$GradeAllocationReport_model = new Application_Model_GradeAllocationReport(); 
									$grade_point = $GradeAllocationReport_model->getGradePointValue($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$val['course_id'],$stu_data['student_id']);
									$academic_courses = $academic_courses.$val['course_id'].",";
									$academic_credits = $academic_credits.$val['credit_value'].",";
									$academic_grades = $academic_grades.$grade_point['grade_point'].",";
									$Coursewisepenalties_model = new Application_Model_Coursewisepenalties();
									$absence_value = $Coursewisepenalties_model->getAbsenceValues($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$stu_data['student_id']);
									$tot_absence = explode(',',$absence_value['absence']);
									?>
                                                                        <td><input type="text" name="student[absence_<?php echo $term_result[$i]['term_id'];?>_<?php echo $stu_data['student_id'];?>][]" value="<?php if($tot_absence[$k] != ''){echo $tot_absence[$k]; } else{ echo '0'; }?>"/></td>
							<?php 
										$total_grade = $grade_point['grade_point']*$val['credit_value']; 
							?>
								<?php  $total_credit_value  += $val['credit_value']; 
										} ?>
								
								<?php $tot_grade = ($total_grade)/($total_credit_value ) ?>			
<input type="hidden" name="student[academic_courses_<?php echo $term_result[$i]['term_id']; ?>][]" id="academic_courses" value="<?php echo  $academic_courses; ?>" />
<input type="hidden"  name="student[academic_credits_<?php echo $term_result[$i]['term_id'];?>][]"  id="academic_credits" value="<?php echo $academic_credits; ?>" />
<input type="hidden" name="student[academic_grades_<?php echo $term_result[$i]['term_id'];?>][]" id="academic_grades" value="<?php echo $academic_grades; ?>" />
<input type="hidden" name="absence_penalty_id_<?php echo $term_result[$i]['term_id']; ?>[]" value="<?php echo $absence_value['item_id']; ?>" />
							</tr>  
				 <?php 
                                 unset($absence_value);
                                 $m++; } ?>	
				</tbody>
	</table>


</div>
</div>
<?php } ?>
         
</td>
</tr>
                                            </table>
<script>
    $(".close_tr").click(function() {
            $( ".sub" ).hide();
     });
</script>
                                            </div>
					</div>
				
				
 			</div>
			
			<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
                                                                                <input type="hidden" name="edit_form_submitted" value="1"/>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
                                    </form>
					</div>
                        <?php
                    }
                    else{
                    ?>
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Courses Wise Penalties</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					<div class="row">
						<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_id; ?>
                            </div>
							</div>
							<?php /* <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->year; ?>
                            </div>
							</div>	 */ ?>
						<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->year_id; ?>
                            </div>
						</div>
												
					</div>
					<div class="row">
							<div class="col-sm-3">
							<div class="form-group">
							<input type="text" id="batch" class="form-control"  style="background-color:#fdf59a;" readonly /></div>
							</div>
							</div>
					<div class="row">
                                            <div id="course_grade_details">
                                               <tr class="sub">
<td colspan="5">

         <div class="col-sm-2" style="float:right;"><button class="close_tr btn btn-primary">Close</button></div>
<br></br>
<?php 

$term_result = $this->term_result;

for($i=0;$i<count($term_result);$i++) {   ?>
 <div class="box-body">
	<h4 style="background-color:#3c8dbc;padding:8px 8px;color:white;"><?php echo $term_result[$i]['term_name'];?></h4>
	<div style="overflow-x:scroll;width:1043px;">
	<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
<thead>
					<tr>
						<th rowspan="2">S. No.</th>
						<th rowspan="2">Name of Participants</th>
						<th rowspan="2">ID Number</th>
						<th>Course</th>
						<?php 
						
						 $Corecourselearning_model =  new Application_Model_Corecourselearning();
							$result = $Corecourselearning_model->getcorecourses($term_result[$i]['academic_year_id'],$term_result[$i]['term_id']);	
							foreach($result as $k => $val) {
							?>
							<th><?php echo 	$val['course_name']; ?></th>
							<?php } ?>
						
					</tr>
					<tr>
	
						<th>Credits</th>
						<?php foreach($result as $k => $val) {
							?>
						<th><?php echo $val['credit_value']; ?></th>
						<?php } ?>
						
					</tr>
				</thead>
				<tbody>
					<?php $StudentPortal_model = new Application_Model_StudentPortal(); 
				 $category_data=$StudentPortal_model->getstudentsdetails($term_result[$i]['academic_year_id']);
				 $m = 1;
				 $total = 0;
				 foreach($category_data as $stu_data) { ?>
					
							<tr>
								<td><?php echo $m; ?></td>						
								
								<td><?php echo $stu_data['students']; ?></td>
								
								<input type="hidden" name="student[student_id_<?php echo $term_result[$i]['term_id'];?>][]" id="student_id" value="<?php echo $stu_data['student_id']; ?>" />
								<td><?php echo $stu_data['stu_id']; ?></td>
								<td></td>	
								<?php $total_credit_value = 0;
										$tot_grade = 0;
										$academic_courses = '';
										$academic_credits = '';
										$academic_grades = '';
									foreach($result as $k => $val) {
									$GradeAllocationReport_model = new Application_Model_GradeAllocationReport(); 
									$grade_point = $GradeAllocationReport_model->getGradePointValue($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$val['course_id'],$stu_data['student_id']);
									$academic_courses = $academic_courses.$val['course_id'].",";
									$academic_credits = $academic_credits.$val['credit_value'].",";
									$academic_grades = $academic_grades.$grade_point['grade_point'].",";
									$Coursewisepenalties_model = new Application_Model_Coursewisepenalties();
									$absence_value = $Coursewisepenalties_model->getAbsenceValues($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$stu_data['student_id']);
									$tot_absence = explode(',',$absence_value['absence']);
									?>
									<td><input type="text" name="student[absence_<?php echo $term_result[$i]['term_id'];?>_<?php echo $stu_data['student_id'];?>][]" value="<?php echo $tot_absence[$k];?>"readonly /></td>
							<?php 
										$total_grade = $grade_point['grade_point']*$val['credit_value']; 
							?>
								<?php  $total_credit_value  += $val['credit_value']; 
										} ?>
								
								<?php $tot_grade = ($total_grade)/($total_credit_value ) ?>			
<input type="hidden" name="student[academic_courses_<?php echo $term_result[$i]['term_id']; ?>][]" id="academic_courses" value="<?php echo  $academic_courses; ?>" />
<input type="hidden"  name="student[academic_credits_<?php echo $term_result[$i]['term_id'];?>][]"  id="academic_credits" value="<?php echo $academic_credits; ?>" />
<input type="hidden" name="student[academic_grades_<?php echo $term_result[$i]['term_id'];?>][]" id="academic_grades" value="<?php echo $academic_grades; ?>" />

							</tr>  
				 <?php $m++; } ?>	
				</tbody>
	</table>


</div>
</div>
<?php } ?>
</td>
</tr>
<script>
    $(".close_tr").click(function() {
            $( ".sub" ).hide();
     });
</script>
                                            </div>
					</div>
				
				
 			</div>
			
			<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
                                    </form>
					</div>
                    <?php
                    }
                    ?>
				
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Courses Wise Penalties</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>course-grade/courses-wise-penalties/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Courses Wise Penalties</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix table-responsive">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th>S. No.</th>
						<th>Batch</th>
						<th>Year</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						//print_r($results);die;

					?>
							<tr class="id<?php echo $results['id'];?>">
								<td><?php echo $i;

									$i++; ?>
								</td>						
								
								<td><?php echo $results['short_code'] ?></td>
								<td><?php if($results['year_id'] == 1){ echo 'First Year'; } else if($results['year_id'] == 2){ echo 'Second Year'; } ?></td>
								<td><a href="<?php echo $this->mainconfig['host']; ?>course-grade/courses-wise-penalties/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>
							<?php /* 	
								<td><a href="<?php echo $this->mainconfig['host']; ?>grade-allocation/grade-allocation-report/type/edit/id/<?php echo $results['grade_report_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>grade-allocation/grade-allocation-report/type/delete/id/<?php echo $results['grade_report_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td> */ ?>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>
$(document).ready(function(){
	$('#batch').hide();
});
$('body').on('change','#year_id',function(){  
var academic_year_id = $('#academic_id').val();
var year_id = $('#year_id').val();
if(year_id == 1){
$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'course-grade/ajax-get-student-absence-data';?>',
			data: {academic_year_id:academic_year_id,year_id:year_id}
		}).done(function( data ) {
			 var result = $.parseJSON(data);
		   
			if(result !=0){
				 alert('This Batch and Year is already Existed');
				 $('#batch').hide();
				$("#academic_id").find('option').attr("selected",false) ;
				$("#year_id").find('option').attr("selected",false) ;
				$('#batch').val('');
				$('#course_grade_details').empty('');
			}
	
			else{
				
				$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'course-grade/ajax-get-student-absence';?>',
			data: {academic_year_id:academic_year_id,year_id:year_id}
		}).done(function( data ) {
			$('#course_grade_details').html(data);
			});
			}
				});
		}

else if(year_id == 2){
	$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'course-grade/ajax-get-second-year-penaltyterms-data';?>',
			data: {academic_year_id:academic_year_id,year_id:year_id}
		}).done(function( data ) {
			
			var result = $.parseJSON(data);
		   
			 if(result !=0){
				 alert('This Batch and Year is already Existed');
				  $('#batch').hide();
				$("#academic_id").find('option').attr("selected",false) ;
				$("#year_id").find('option').attr("selected",false) ;
				$('#batch').val('');
				$('#course_grade_details').empty('');
			}
		
			else{  
				
				$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'course-grade/ajax-get-second-year-penaltyterms';?>',
			data: {academic_year_id:academic_year_id,year_id:year_id}
		}).done(function( data ) {
			$('#course_grade_details').html(data);
			});
			}
			});
}			
});

 
 $('body').on('change', '#academic_id', function() {		
var academic_id=$('#academic_id').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	 
 });
 function penalties_view(val,academic_year_id,year_id){ 
	        var id = val;
			var academic_year_id = academic_year_id;
			var year_id = year_id;
			if(year_id == 1){
			$.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'course-grade/ajax-get-student-absence-view';?>",
              data: { id:id,academic_year_id:academic_year_id,year_id:year_id}
            }).done(function(data) {
				$(".sub").hide();
				$(data).insertAfter("tr.id"+id);
			});
			}else if(year_id == 2){
				
				$.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'course-grade/ajax-get-second-year-penaltyterms-view';?>",
              data: { id:id,academic_year_id:academic_year_id,year_id:year_id}
            }).done(function(data) {
				$(".sub").hide();
				$(data).insertAfter("tr.id"+id);
			});
				
			}	
     }
</script>