<?php 
//print_r( $this->academicresult);die;
?>
<div style="overflow-x:scroll">
<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
			
			
				<thead>
					<tr>
						
						<th rowspan="2">S.  No.</th>
						<th rowspan="2">Participants Name</th>
						<th rowspan="2">Participants ID</th>
						<th>Component</th>
						<?php   foreach($this->components as $m => $component) { ?>
						<th><?php echo $component['component_name']; ?></th>
						<?php if($this->course_type == '1') { ?>
						<input type="hidden" name="grade[component_id][]" id="grade" value="<?php echo $component['cr_eci_id'];?>"/>
						<?php }else if($this->course_type == '2') {  ?>
						<input type="hidden" name="grade[component_id][]" id="grade" value="<?php echo $component['el_eci_id'];?>"/>
						<?php } ?>
						<?php  } ?>
					</tr>
					<tr>
						
						
						<th>Weightage</th>
						<?php foreach($this->components as $m => $component) { ?>
						<th><?php echo $component['weightage']; ?></th>
						<?php } ?>
					</tr>
				</thead>
				<tbody>
				
				
				<tbody>
								<?php if(!empty($this->result))	 {  $i = 1;  
								
								foreach($this->result as $k => $result) { ?>
								<tr>
										<td><?php echo $i;

									$i++; ?>
								</td>
											
											<td><?php echo $result['student_name'];?></td> 
											<input type="hidden" name="grade[student_id][]" id="student_id" value="<?php echo $result['student_id']; ?>" />
											<td><?php echo $result['stu_id'];?></td> 											
											<td></td>
											<?php $alloted_grades = explode(',',$result['grade_value']);
                     						foreach($alloted_grades as $grds){ 					?>
											
										<td><input type="text" name="grade[grade_value_<?php echo $result['student_id'];?>][]" id="grade"  value="<?php echo $grds; ?>"/></td>
										
											<?php } ?>
		                               </tr>
									
								<?php }  } else { ?>
										<?php
											
											$i = 1;
										
										?>
										<?php foreach($this->category_data as $key=>$val){ ?>
										<tr>
										<td><?php echo $i;

									$i++; ?>
								</td>
											
											<td><?php echo $val['students'];?></td> 
											<input type="hidden" name="grade[student_id][]" id="student_id" value="<?php echo $val['student_id']; ?>" />
											<td><?php echo $val['stu_id'];?></td> 											
											<td></td>
											<?php foreach($this->components as $m => $component) { ?>
											<td><input type="text" name="grade[grade_value_<?php echo $val['student_id']; ?>][]" id="grade" /></td>
											<?php } ?>
										
								
		                               </tr>
									   
									  
									   <?php 
									 	 }
								}
											?>
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
		</div>