<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="<?php echo $this->mainconfig['publicpath'];?>images/favicon.ico" rel="icon" type="image/x-icon"> 
    <title>PWC ERP</title>

    <!-- Bootstrap -->
    <link href="<?php echo $this->mainconfig['publicpath'];?>vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo $this->mainconfig['publicpath'];?>vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?php echo $this->mainconfig['publicpath'];?>vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- Animate.css -->
    <link href="<?php echo $this->mainconfig['publicpath'];?>vendors/animate.css/animate.min.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?php echo $this->mainconfig['publicpath'];?>build/css/custom.min.css" rel="stylesheet">
    <style>
  
            body>div{
                position:absolute;
                background:#9495ad !important;
                width:100%;
                height:100%;
            }
            
        body>div>div.container{
                       position: absolute;
                       top:50%;
                       left:50%;
                       transform: translate(-50%,-50%);
                   }
            .login_form{
                border:1px solid #932E8F !important;
            }
            .login_form>h2{
                
                background-color:#932E8F!important;
                
            }
            
            
            .carousel-inner > .item > img{
                height: 290px!important;
            }
            

         
    </style>
    
  </head>

  <body class="login">
    <div>
      <a class="hiddenanchor" id="signup"></a>
      <a class="hiddenanchor" id="signin"></a>

     <?php echo $this->layout()->content; ?>  
    </div>
  </body>
</html>
