<style type="text/css">
* {
	margin: 0px;
	padding: 0px;
	font-family: Arial, sans-serif;
	font-weight: 300;
	
}
.credit table {
	border-collapse: collapse;
	width: 100%;
}
.credit table, th {
	border: 1px solid black;
	padding: 2px;
	
	
}
.credit {
	width: 100%;
	height: auto;
	margin: 0px auto;
	float: left;
	border: 1px solid #000;
}
table {
	border-collapse: collapse;
	width: 100%;
	border: 1px solid #000;
}
table, th, td {
	border: 1px solid black;
	padding: 5px;
	font-size: 20px !important;
	
}
</style>
<!-- widget grid -->
<!-- widget grid -->
<section id="widget-grid" class="">	
	<!-- row -->
	<div class="row">
		
		<!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
				<header>
					<span class="widget-icon"> <i class="fa fa-table"></i> </span>
					<h2></h2>

				</header>

				<!-- widget div-->
				<div>		
					<!-- widget content -->
						<div class="widget-body">
							<div class="table-responsive">
								<?php /* if(!empty($this->party_name)){
								
								?>
									<form id="basicForm" action="<?php echo $this->mainconfig['host']; ?>finance/journal/invoice-statement/save" method="post" class="form">
									 <div style="width:10%; z-index:999; float:right !important; position:fixed; margin-left:71%; margin-top:22%;">
											<textarea name="statement_remarks" required="required" rows="4" cols="50" style="resize:none;"><?php //echo $this->statement_remarks; ?></textarea>
											<input type="hidden" name="start_date" value="<?php echo $this->start_date; ?>" />
											<input type="hidden" name="end_date" value="<?php echo $this->enddate; ?>" />	
											<input type="hidden" name="party_name" value="<?php echo $this->party_name; ?>" />				
											<input type="submit" name="save" class="btn btn-primary" value="Save" />
									</div>		
									<?php } */ ?>
								<table style="margin-bottom:0px !important;" class="table table-bordered ">
									<thead>										
										<tr>											
											<th colspan="2"></th>
											<th colspan="2" style="text-align:center;">Balance</th>
										</tr>
										<tr>
											<th style="text-align:center;">S.No.</th>
											<th style="text-align:center;">Account Name</th>
											<th style="text-align:center;">Debit</th>
											<th style="text-align:center;">Credit</th>	
										</tr>
									</thead>
									<tbody>
										<?php //print_r($this->opening_balance); 
										$total_items = 0;
										$total_credit = 0;
										$total_debit = 0;
																				
										$i = 0;
										$days_count = 0;										
										$dealer_statement = $this->dealer_statement;
										if ( count($dealer_statement) > 0 ) {
											?>											  
											<?php
											$total_items = count($dealer_statement);
											$k = 0;
											foreach ($dealer_statement as $customer) {
												$opening_debit_amt = 0;
												$opening_credit_amt = 0;
												if( ($customer['operator'] == 2) ){													
													$opening_credit_amt =  $customer['start_balance'];
													$total_credit +=  $customer['start_balance']; 
												}else{
													$opening_debit_amt =  $customer['start_balance'];
													$total_debit  +=  $customer['start_balance'];														
												}
												$i++;												
												?>
												<tr>
													<td><?php echo $i; ?></td>
													<td>
													<?php echo $customer['name']; ?>
													</td>													
													<td style="text-align:right;width:15%;">
													<?php
															echo number_format($opening_debit_amt, 2);
															//$total_debit += $customer['debit_amount'];		
														?>
													</td>
													<td style="text-align:right;width:15%;">
													<?php														
															echo number_format($opening_credit_amt, 2);
															//$total_credit += $customer['credit_amount'];
														?>
													</td>													
												</tr>
												<?php
												// } //End
											}																							
											/*
											 * Vendor Pyments end
											 */
											?>
											<?php
											}											
											?>
											<?php 
											$vendor_statement = $this->vendor_statement;
										if ( count($vendor_statement) > 0 ) {
											?>											  
											<?php
											$total_items = count($vendor_statement);
											$k = 0;
											foreach ($vendor_statement as $vendor) {
												$opening_debit_amt = 0;
												$opening_credit_amt = 0;
												if( ($vendor['operator'] == 2) ){													
													$opening_credit_amt =  $vendor['start_balance'];
													$total_credit +=  $vendor['start_balance']; 
												}else{
													$opening_debit_amt =  $vendor['start_balance'];
													$total_debit  +=  $vendor['start_balance'];														
												}
												
												$i++;												
												?>
												<tr>
													<td><?php echo $i; ?></td>
													<td>
													<?php echo $vendor['name']; ?>
													</td>													
													<td style="text-align:right;width:15%;">
													<?php
															echo number_format($opening_debit_amt, 2);
															//$total_debit += $vendor['debit_amount']; 														
														?>
													</td>
													<td style="text-align:right;width:15%;">
													<?php														
															echo number_format($opening_credit_amt, 2);
															//$total_credit += $vendor['credit_amount'];
														?>
													</td>													
												</tr>
												<?php
												// } //End
											}																							
											/*
											 * Vendor Pyments end
											 */
											?>
											<?php
											}											
											?>
										<?php 
											$bank_statement = $this->bank_statement;
										if ( count($bank_statement) > 0 ) {
											?>											  
											<?php
											$total_items = count($bank_statement);
											$k = 0;
											foreach ($bank_statement as $bank) {
												$opening_debit_amt = 0;
												$opening_credit_amt = 0;
												if( ($bank['operator'] == 2) ){													
													$opening_credit_amt =  $bank['opening_balance'];
													$total_credit +=  $bank['opening_balance']; 
												}else{
													$opening_debit_amt =  $bank['opening_balance'];
													$total_debit  +=  $bank['opening_balance'];														
												}
												$i++;												
												?>
												<tr>
													<td><?php echo $i; ?></td>
													<td>
													<?php echo $bank['name']; ?>
													</td>													
													<td style="text-align:right;width:15%;">
													<?php
															echo number_format($opening_debit_amt, 2);
															//$total_debit += $vendor['debit_amount']; 														
														?>
													</td>
													<td style="text-align:right;width:15%;">
													<?php														
															echo number_format($opening_credit_amt, 2);
															//$total_credit += $vendor['credit_amount'];
														?>
													</td>													
												</tr>
												<?php
												// } //End
											}																							
											/*
											 * Vendor Pyments end
											 */
											?>
											<?php
											}											
											?>
										<?php 
											$account_statement = $this->account_statement;
										if ( count($account_statement) > 0 ) {
											?>											  
											<?php
											$total_items = count($account_statement);
											$k = 0;
											foreach ($account_statement as $account) {
												$opening_debit_amt = 0;
												$opening_credit_amt = 0;
												if( ($account['operator'] == 2) ){													
													$opening_credit_amt =  $account['opening_balance'];
													$total_credit +=  $account['opening_balance']; 
												}else{
													$opening_debit_amt =  $account['opening_balance'];
													$total_debit  +=  $account['opening_balance'];														
												}
												$i++;												
												?>
												<tr>
													<td><?php echo $i; ?></td>
													<td>
													<?php echo $account['name']; ?>
													</td>													
													<td style="text-align:right;width:15%;">
													<?php
															echo number_format($opening_debit_amt, 2);
															//$total_debit += $vendor['debit_amount']; 														
														?>
													</td>
													<td style="text-align:right;width:15%;">
													<?php														
															echo number_format($opening_credit_amt, 2);
															//$total_credit += $vendor['credit_amount'];
														?>
													</td>													
												</tr>
												<?php
												// } //End
											}																							
											/*
											 * Vendor Pyments end
											 */
											?>
											<?php
											}											
											?>
										
											
										<tr>
											<td style=" border-right:0px !important;"><b>Total<b/></td>
											<td style="text-align:right; border-left:0px !important;"><b><?php echo $i; //$total_items; ?><b/></td>
											<td style="text-align:right; border-left:0px !important;"><b><?php echo number_format( $total_debit, 2); ?><b/></td>	
											<td style="text-align:right; border-left:0px !important;"><b><?php echo number_format( $total_credit, 2); ?><b/></td>
										</tr>
										
									</tbody>
								</table>
							</div>
						</div>
					<!-- end widget content -->
				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->
		</article>
		<!-- WIDGET END -->
	</div>
	
	<!-- end row -->
</section>
<!-- end widget grid -->