<script src="<?php echo $this->mainconfig['publicpath'];?>vendors/select2/dist/js/select2.full.min.js"></script>
<script src="<?php echo $this->mainconfig['publicpath'];?>js/jquery-ui.min.js"></script>
<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Batch</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
							<div class="row">
															
								
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label"> From Date <span class="asterisk">*</span></label>
                                <?php echo $this->form->from_date; ?>
                            </div>
                          </div>  									
														
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label"> To Date <span class="asterisk">*</span></label>
                                <?php echo $this->form->to_date; ?>
                            </div>
                          </div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label"> Batch Name<span class="asterisk">*</span></label>
                                <?php echo $this->form->batch_code; ?>
                            </div>
                          </div>
						  
						  <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch Code <span class="asterisk">*</span></label>
                                <?php echo $this->form->short_code; ?>
                            </div>
							
                          </div>
						  
							
						</div>
						  
						  <!-- <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label"> Total No of Credits <span class="asterisk">*</span></label>
                                <?php //echo $this->form->tot_no_of_credits; ?>
                            </div>
                          </div> -->
							
							
							<div class="col-sm-2" style="padding-top:30px;">	
								<p>Weeks : <span id="week"></span></p>
							 </div>
							<div class="col-sm-2" style="padding-top:30px;">	
								<p>Days : <span id="days"></span></p>
							</div>
							</div>
							
						
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>master/academic">Back</a>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
<div class="alert alert-success">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Batch</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>master/academic/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Batch</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
				<thead>
					<tr>
						<th>S.  No.</th>												
						<th>From Date</th>
						<th>To Date</th>
						<th>Batch Name</th>
						<th>Batch Code</th>
					<!-- <th>Total No of Credits</th> -->
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						//print_r($results);die;

					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>						
								
								<td><?php echo $results['from_date']; ?></td>
								<td><?php echo $results['to_date']; ?></td>
								<td><?php echo $results['batch_code']; ?></td>
								<td><?php echo $results['short_code']; ?></td>
								<!-- <td><?php //echo $results['tot_no_of_credits']; ?></td> -->
								<td><a href="<?php echo $this->mainconfig['host']; ?>master/academic/type/edit/id/<?php echo $results['academic_year_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/academic/type/delete/id/<?php echo $results['academic_year_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>

<script>	
$(document).ready(function() {		
	$("#from_date").datepicker({ dateFormat: 'dd/mm/yy' }); 
	$("#to_date").datepicker({ dateFormat: 'dd/mm/yy' });  
}); 
	
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}
	
	
$('body').on('change', '#to_date', function() {

	var from_date=$('#from_date').val();
	var dateParts = from_date.split("/");
	var checkindate = new Date(dateParts[2], dateParts[1] - 1, dateParts[0]);
	var to_date=$('#to_date').val();
	var datePart = to_date.split("/");
	var check = new Date(datePart[2], datePart[1] - 1, datePart[0]);
	var difference = check - checkindate;
	var num_years = Math.floor(difference/31536000000);
	var num_months = (difference % 31536000000)/2628000000;
	var days = Math.floor(difference / (1000 * 3600 * 24));
	var diffWeeks = Math.floor(difference / (1000 * 60 * 60 * 24 * 7));
	//alert(num_years);
	//alert(num_months);
	if(days <= 731)
{
	//alert('Course Sholud be 2 Years');
}
else
{
	alert('Course Sholud not be More Than 2 Years');
	$('#to_date').val("");
	
}  

});
	
	
$('body').on('change', '#to_date', function() {
	
	var from_date=$('#from_date').val();
	var dateParts = from_date.split("/");
	var checkindate = new Date(dateParts[2], dateParts[1] - 1, dateParts[0]);
	
	
	var to_date=$('#to_date').val();
	var datePart = to_date.split("/");
	var check = new Date(datePart[2], datePart[1] - 1, datePart[0]);
	var difference = check - checkindate;
	var days = Math.floor(difference / (1000 * 3600 * 24)) + 1;
	var diffWeeks = Math.floor(difference / (1000 * 60 * 60 * 24 * 7)) ;
	
$('#days').html(days);
$('#week').html(diffWeeks);
});

	var from_date=$('#from_date').val();
	var dateParts = from_date.split("/");
	var checkindate = new Date(dateParts[2], dateParts[1] - 1, dateParts[0]);
	
	
	var to_date=$('#to_date').val();
	var datePart = to_date.split("/");
	var check = new Date(datePart[2], datePart[1] - 1, datePart[0]);
	var difference = check - checkindate;
	var days = Math.floor(difference / (1000 * 3600 * 24)) +1;
	var diffWeeks = Math.floor(difference / (1000 * 60 * 60 * 24 * 7));
	
$('#days').html(days);
$('#week').html(diffWeeks);	



</script>