<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" novalidate>
					<div class="panel-heading">									
						 <h4>Academic Assessment - Allocation</h4> 
					</div>
					<div class="panel-body">
						<div class="row">							
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Academic Year</label>
									<?php echo $this->form->academic_year; ?>
								</div>										
							</div> 
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Country</label>
									<?php echo $this->form->country_id; ?>
								</div>										
							</div> 
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Sub Program</label>
									<?php echo $this->form->subprogram_id; ?>
								</div>										
							</div> 
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Area of Learning</label>
									<?php echo $this->form->area_learning_id; ?>
								</div>										
							</div> 
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Early Learning Goals</label>
									<?php echo $this->form->elg_id; ?>
								</div>										
							</div> 
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Sub Area of Learning</label>
									<?php echo $this->form->sub_area_learning_id; ?>
								</div>										
							</div> 
							<div id="skill_type">
							</div>
							<?php /* <div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Skill Type</label>
									<?php echo $this->form->skilltype_id; ?>
								</div>										
							</div>  */ ?>
					<input type="hidden" name="allocation_id" id="allocation_id"  value="<?php echo $this->result['allocation_id'];?>" />		
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="padding-md">
	<div class="panel panel-default table-responsive">
		<div class="panel-heading">
			 Academic Assessment - Allocation
			<a class="btn btn-primary pull-right" style="margin-top: -9px;" href="<?php echo $this->mainconfig['host'];?>master/academic-allocation/type/add">Add </a>
		</div>
		<div class="padding-md clearfix">
			<table class="table table-striped" id="dataTable">
				<thead>
					<tr>
						<th>S.No.</th>	 
						<th>Academic Year</th>
						<th>Country</th>
						<th>Sub Program</th>
						<th>Area of Learning</th>
						<th>Early Learning Goals</th>
						<th>Sub Area Of Learning</th>
						<th>Skill Type</th>
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						
						if (count($this->paginator) != 0) {
							

						foreach ($this->paginator as $results) { 

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						<td><?php echo $results['academic_year']; ?></td>
						<td><?php echo $results['countries_name']; ?></td>
						<td><?php echo $results['subprogram_name']; ?></td>
						<td><?php echo $results['area_learning']; ?></td>
						<td><?php echo $results['elg']; ?></td>
						<td><?php echo $results['sub_area']; ?></td>
						<td><?php 

                                                $original_array=unserialize($results['skill_type_name']);
                                                foreach($original_array as $val)
                                                {
                                                    echo $val.',';
                                                }
                                                 ?>           </td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/academic-allocation/type/edit/id/<?php echo $results['allocation_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/academic-allocation/type/delete/id/<?php echo   $results['allocation_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script type="text/javascript">
$('.date').datepicker({
	dateFormat: 'yy-mm-dd',
	prevText: '<i class="fa fa-chevron-left"></i>',
	nextText: '<i class="fa fa-chevron-right"></i>' 
});
$('body').on('change','#sub_area_learning_id', function() {
var id = $('#sub_area_learning_id').val();
var allocation_id = $('#allocation_id').val();
//alert(id);
		$.ajax({ 
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'master/ajax-get-skill-type';?>',
				data: {id:id, allocation_id : allocation_id}
			}).done(function( data ) {
				$("#skill_type").html( data );
			 });
 });
 var id = $('#sub_area_learning_id option:selected').val();
 var allocation_id = $('#allocation_id').val();
		$.ajax({ 
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'master/ajax-get-skill-type';?>',
				data: {id:id, allocation_id : allocation_id}
			}).done(function( data ) {
				$("#skill_type").html( data );
			 });
</script>