<?php 
//print_r( $this->academicresult);die;
?>
<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
			
			
				<thead>
					<tr>
						
						<th>Experiential Learning Component</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Credit</th>
						

					</tr>
				</thead>
				<tbody>
				
				
				<tbody>
									
										<?php
											
											$i = 1;
											$total_credits=0;
										
										?>
										<?php foreach($this->academicresult as $key=>$val){ ?>
										<tr>
										
											
											<td><?php echo $val['elc_name'];?></td>
											<td><?php echo $val['start_date'];?></td>
											<td><?php echo $val['end_date'];?></td>
											<td><?php echo $val['credit_value'];?></td> 
											
											
								
		                               </tr>
									   
									  
									   <?php 
									   $total_credits=$total_credits+$val['credit_value'];
											 }
											
											?>
									<tr id="total">
						<td colspan="3" align="right"><b>Total Credits</b></td>
							<td><b></b> <b><?php echo  $total_credits;?></b></td>
							</tr>
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->