<?php if ($this->type) { ?>
<div class="padding-md right_col">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Country</i></div>
				
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" novalidate>
				
					<div class="panel-body">
						<div class="row">
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Country Name</label>
									<?php echo $this->form->countries_name; ?>
								</div>									
							</div>  
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Country Code</label>
									<?php echo $this->form->countries_iso_code_3; ?>
								</div>									
							</div> 	
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Country Currency</label>
									<?php echo $this->form->countries_currency; ?>
								</div>									
							</div> 	
						</div>
						</div>
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
				
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="right_col">
	<div class="">
	<div class="row">
	<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Country</i>
				
		</h3>
	</div>
	<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
		
				<a class="btn btn-primary pull-right" style="margin-top:25px;" href="<?php echo $this->mainconfig['host']; ?>master/country/type/add">Add Country</a>
			
	</div>
</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Country</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th>S.No</th>								
						<th>Country Name</th> 
						<th>Country Code</th>
						<th>Country Currency</th>
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
				//echo'<pre>';print_r($results);die;
					?>
					<tr>
						<td><?php echo $i;
							$i++; ?>
						</td>
						<td><?php echo $results['countries_name']; ?></td>
						<td><?php echo $results['countries_iso_code_3']; ?></td>
						<td><?php echo $results['countries_currency']; ?></td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/country/type/edit/id/<?php echo $results['countries_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/country/type/delete/id/<?php echo $results['countries_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>
					</tr>            
								<div style="col-sm-12"><?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?></div>
				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div>
</div>
</div><!-- /.padding-md -->		
<?php } ?>