<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">  Course</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
							<div class="row">
								
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Course Category <span class="asterisk">*</span></label>
                                <?php echo $this->form->course_category_id; ?>
                            </div>
							</div> 	
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Course Type <span class="asterisk">*</span></label>
                                <?php echo $this->form->ct_id; ?>
                            </div>
							</div> 	
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Course Code <span class="asterisk">*</span></label>
                                <?php echo $this->form->course_code; ?>
                            </div>
							</div> 								
														
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Course Name <span class="asterisk">*</span></label>
                                <?php echo $this->form->course_name; ?>
                            </div>
							</div> 
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Descrption <span class="asterisk">*</span></label>
                                <?php echo $this->form->course_description; ?>
                            </div>
							</div>
							
							
							
							
							</div>
							</div>
						<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>master/course">Back</a>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars">  Course </i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>master/course/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Course</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table id="datatable-responsive" class="table table-striped table-bordered mb30 jambo_table bulk_action">
				<thead>
					<tr>
						<th>S.No.</th>
						<th>Course Category</th>
						<th>Course Type</th>
						<th>Course Code</th>
						<th>Course Name</th>
						<th>Descrption</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {
//echo '<pre>' ;print_r($this->paginator);die;
						foreach($this->paginator as $results) {
						

					?>
							<tr>
								<td><?php echo $i;

									?>
								</td>						
								<td><?php echo $results['cc_name']; ?></td>
								<td><?php echo $results['ct_name']; ?></td>
								<td><?php echo $results['course_code']; ?></td>
								<td><?php echo $results['course_name']; ?></td>
								<td><?php echo $results['course_description']; ?></td>
								<td><a href="<?php echo $this->mainconfig['host']; ?>master/course/type/edit/id/<?php echo $results['course_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/course/type/delete/id/<?php echo $results['course_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

							</tr>            

						<?php $i++; }
						//$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>	

	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}
	
	
  $("#course_name").change(function(){
	  
	 $course_name=$("#course_name").val();
		
		if(!isNaN($course_name))
		{
			alert("Course Name Should be Characters Only");
			$("#course_name").val("");
		}
  });
  
  
 /* $("#course_code").change(function(){
	  
	 $course_code=$("#course_code").val();
		
		if(isNaN($course_code))
		{
			alert("Course code Should be Numarics Only");
			$("#course_code").val("");
		}
  });*/
  
  
  
  	
//check the same name validation	
$("#course_name").change(function(){
	
	var coursename=$('#course_name').val();
	
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/get-coursename-same';?>',
			data: {coursename:coursename}
		}).done(function( data ) {
			
			if((data!='')){
				alert("This Course name Exists");
				  $("#course_name" ).val("");
			}
		
			
		 });
});
  
	
</script>
