<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->Menu_form->getAction() ?>" method="post" data-validate="parsley" onsubmit="return select_submit();" novalidate>
					<div class="panel-heading">									
						 <h4>Menu</h4> 
					</div>
					<div class="panel-body">
						<div class="row">							                         
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Menu Title <span class="asterisk">*</span></label>
									<?php echo $this->Menu_form->menu_title; ?>
								</div>										
							</div>
							<div class="col-sm-3"  style="height: 100px;overflow-y: scroll;">
							<label  class="control-label" >Items <span class="asterisk">*</span></label>
							<?php foreach($this->items as $k=>$val){ //echo $k;;  ?>
							<label class="label-checkbox" style="padding-left:0px; margin:8px;"  >
							<input type="checkbox" name="item_id[]" class="items" required="required" id="item" <?php
										if(!empty($this->result['item_id'])){ 
												$data = explode(',',$this->result['item_id']);
												foreach($data as $key=>$Val){
													$checked = '';
													if($k == $Val)
													echo $checked = 'checked';
													} } ?> value="<?php echo $k;?>" />
							<span class="custom-checkbox" style="float:left;"></span> </label> <?php echo $val; ?>
							<?php } ?>
							</div> 

						</div>
						<br/>
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit" id="submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="padding-md">
	<div class="panel panel-default table-responsive">
		<div class="panel-heading">
			 Menu
			<a class="btn btn-primary pull-right" style="margin-top: -9px;" href="<?php echo $this->mainconfig['host']; ?>master/menu/type/add">Add Menu</a>
		</div>
		<div class="padding-md clearfix">
			<table class="table table-striped" id="dataTable">
				<thead>
					<tr>
						<th>S. No</th>	 
						<th>Title</th>
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						<td><?php echo $results['menu_title']; ?></td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/menu/type/edit/id/<?php echo $results['menu_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/menu/type/delete/id/<?php echo $results['menu_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div><!-- /.padding-md -->		
<?php } ?>
<script>

function select_submit(){
 //$("input.select:checked").length > 0;
 var selecteditems = new Array();
	$('input[name="item_id[]"]:checked').each(function() {
	selecteditems.push(this.value);
	});
	if(selecteditems.length<1)
	{
	  alert("should select minimum one item!");
	  return false;
	}
	 
}

</script>
