<script src="<?php echo $this->mainconfig['publicpath'];?>vendors/select2/dist/js/select2.full.min.js"></script>
<script src="<?php echo $this->mainconfig['publicpath'];?>js/jquery-ui.min.js"></script>
<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Program Calendar Year</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
							<div class="row">
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">Batch Code<span class="asterisk">*</span></label>
                                <?php echo $this->form->short_code; ?>
                            </div>
							</div>								
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                               <input type="text" id="academic_year_id" name="academic_year_id" class="form-control" readonly />
                            </div>
							</div> 	
																
														
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">Program Name <span class="asterisk">*</span></label>
                                <?php echo $this->form->pd_name; ?>
                            </div>
							</div>
							
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">Session Name <span class="asterisk">*</span></label>
                                <?php echo $this->form->se_name; ?>
                            </div>
							</div>

							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">Description <span class="asterisk">*</span></label>
                                <?php echo $this->form->pd_desc; ?>
                            </div>
							</div>	
							
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">Start Date <span class="asterisk">*</span></label>
                                <?php echo $this->form->start_date; ?>
                            </div>
							</div> 
							
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">End Date  <span class="asterisk">*</span></label>
                                <?php echo $this->form->end_date; ?>
                            </div>
							</div>
							
							<?php if($this->type=='edit') { ?>
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">No of Days <span class="asterisk">*</span></label>
                                <?php //echo $this->form->no_weeks; ?>
								<input type="text" id="no_days" name="no_days" class="form-control" value="<?php echo $this->result['no_days'];?>"/>
                            </div>
							</div>
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">No of Weeks <span class="asterisk">*</span></label>
                                <?php //echo $this->form->no_weeks; ?>
								<input type="text" id="no_weeks" name="no_weeks" class="form-control" value="<?php echo $this->result['no_weeks'];?>"/>
                            </div>
							</div>
							
							<?php } else{?>
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">No of Days <span class="asterisk">*</span></label>
                                <?php //echo $this->form->no_weeks; ?>
								<input type="text" id="no_days" name="no_days" class="form-control"/>
                            </div>
							</div>
							
							<div class="col-sm-3 ">
                            <div class="form-group">
                              <label class="control-label">No of Weeks <span class="asterisk">*</span></label>
                                <?php //echo $this->form->no_weeks; ?>
								<input type="text" id="no_weeks" name="no_weeks" class="form-control"/>
                            </div>
							</div>
							<?php } ?>
							</div>
							<!--  <div class="row">
							<div class="col-sm-3">
                            <div class="form-group">
                              <label class="control-label">Sort No.<span class="asterisk">*</span></label>
                                <?php echo $this->form->sort_no; ?>
                            </div>
							</div>
							
							
							
							</div> -->
							
							</div>
						<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>master/programdesign">Back</a>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Program Calendar Year </i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>master/programdesign/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Program Calendar Year Master</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
   <div class="x_content">
   
   <!--<div class="padding-md clearfix">
			<table class="table-striped table-bordered  jambo_table bulk_action" id="dataTable" width="100%" > -->
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
				<thead>
					<tr>
						<th>S.No.</th>
						<th>Batch Code</th>
						<th>Batch</th>
						<th>Program Name</th>
						<th>Session Name</th>
						<th>Description</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>No of Days</th>
						<th>No of Weeks</th>
						<!-- <th>Sort No.</th> -->
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {
//echo'<pre>';print_r($this->paginator);die;
						foreach ($this->paginator as $results) {
						

					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>						
								
								<td><?php echo $results['short_code']; ?></td>
								<td><?php echo $results['from_date'] .'&nbsp;&nbsp;-&nbsp;&nbsp;'. $results['to_date']; ?></td>
								<td><?php echo $results['pm_name']; ?></td>
								<td><?php echo $results['se_name']; ?></td>
								<td><?php echo $results['pd_desc']; ?></td>
								<td><?php echo $results['start_date']; ?></td>
								<td><?php echo $results['end_date']; ?></td>
								<td><?php echo $results['no_days']; ?></td>
								<td><?php echo $results['no_weeks']; ?></td>
								<!-- <td><?php // echo $results['sort_no']; ?></td> -->
								<td><a href="<?php echo $this->mainconfig['host']; ?>master/programdesign/type/edit/id/<?php echo $results['pd_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/programdesign/type/delete/id/<?php echo $results['pd_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>

<script>
$(document).ready(function() {		
	$("#start_date").datepicker({ dateFormat: 'dd/mm/yy' });  
	$("#end_date").datepicker({ dateFormat: 'dd/mm/yy' });  
	
}); 

$('body').on('change', '#end_date', function() {
	
	var start_date=$('#start_date').val();
	var dateParts = start_date.split("/");
	var checkindate = new Date(dateParts[2], dateParts[1] - 1, dateParts[0]);
	
	
	var end_date=$('#end_date').val();
	var datePart = end_date.split("/");
	var check = new Date(datePart[2], datePart[1] - 1, datePart[0]);
	var difference = check - checkindate;
	var days = Math.floor(difference / (1000 * 3600 * 24));
        var inc_days = days+1;
	var exdays_in_weeks = inc_days  % 7;
	var diffWeeks = Math.floor(difference / (1000 * 60 * 60 * 24 * 7));
	
	$('#batch').html(inc_days );
        var tot_weeks = diffWeeks+'.'+exdays_in_weeks;
	if(inc_days !=''){
	$('#no_days').val(inc_days );
	$('#no_weeks').val(Math.round(tot_weeks));
	}
});

	var start_date=$('#start_date').val();
	var dateParts = start_date.split("/");
	var checkindate = new Date(dateParts[2], dateParts[1] - 1, dateParts[0]);
	
	
	var end_date=$('#end_date').val();
	var datePart = end_date.split("/");
	var check = new Date(datePart[2], datePart[1] - 1, datePart[0]);
	var difference = check - checkindate;
	var days = Math.floor(difference / (1000 * 3600 * 24));
        var inc_days = days+1;
	var exdays_in_weeks = inc_days % 7;
	var diffWeeks = Math.floor(difference / (1000 * 60 * 60 * 24 * 7));
	
	$('#batch').html(inc_days );
        var tot_weeks = diffWeeks+'.'+exdays_in_weeks;
	if(inc_days !=0){
	$('#no_days').val(inc_days );
	$('#no_weeks').val(Math.round(tot_weeks));
	}
	

	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}
	
$("#no_days" ).change(function() {
  $no_days=$( "#no_days" ).val();
  
  if(isNaN($no_days))
  {
	  alert("Days should be numeric only ");
	  $("#no_days" ).val("");
  }
  
});	

$("#no_weeks" ).change(function() {
  $no_weeks=$( "#no_weeks" ).val();
  
  if(isNaN($no_weeks))
  {
	  alert("Weeks should be numeric only ");
	  $("#no_weeks" ).val("");
  }
  
});	
	
	
	
	
$("#sort_no" ).change(function() {
  $sort_no=$( "#sort_no" ).val();
  
  if(isNaN($sort_no))
  {
	  alert("Weeks should be numeric only ");
	  $("#sort_no" ).val("");
  }
  
});	
	
	

	
$("#pd_name").change(function(){
	
	var pd=$('#pd_name').val();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/get-program-design-same-name';?>',
			data: {pd:pd}
		}).done(function( data ) {
			//alert(data);
			if((data!='')){
				alert("This Program name Exists");
				  $("#pd_name" ).val("");
			}
		
			
		 });
});


$('body').on('change', '#academic_year_id', function() {		
var sel = document.getElementById("academic_year_id");
var value = sel.options[sel.selectedIndex].value; // or sel.value
var text = sel.options[sel.selectedIndex].text; 
//alert(text);
$('#payslipData').val(text);
 });
var academic_year_id =$('#academic_year_id option:selected').text();
$('#payslipData').val(academic_year_id);





$('body').on('change','#short_code',function() { 
		var short_id = $('#short_code').val();
		
		$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-academic';?>',
			data: {short_id : short_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if(result !=''){
			$('#academic_year_id').empty('');
			$('#academic_year_id').val(result['from_date']+'-'+result['to_date']);
			}
			
			
		})	
})
var short_id = $('#short_code option:selected').val();
		
		$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-academic';?>',
			data: {short_id : short_id}
		}).done(function( data ) {

			var result = $.parseJSON(data);
			if(result !=''){
			
			$('#academic_year_id').val(result['from_date']+'-'+result['to_date']);
			}
			
		})	

$('body').on('change','#short_code',function() { 
		var short_id = $('#short_code').val();
		
		$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-program-name';?>',
			data: {short_id : short_id}
		}).done(function( data ) {
			
			$('#pd_name').empty('');
			$('#pd_name').html(data);
			
		})	
})
 
</script>
