<?php if ($this->type) { ?>
<div class="padding-md right_col">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Tax</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" novalidate>
					
					<div class="panel-body">
						<?php /*<div class="row">
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Location</label>
									<?php echo $this->form->location_id; ?>
								</div>									
							</div>  
						</div>*/?>
							
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Title</label>
									<?php echo $this->form->title; ?>
								</div>									
							</div> 
							
						<?php /* <div class="row">	
								 <div class="col-sm-3 ">				
									<div class="form-group">
										<label class="control-label">Percentage</label>
										<?php echo $this->form->percentage;  ?>
									</div>									
								</div> 
								<div class="col-sm-2">	
									<div class="form-group">
										<label class="control-label">From Date</label>									
										<div class="input-group">			
											<?php echo $this->form->from_date; ?>
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>
								</div>
							
								<div class="col-sm-2" >	
									<div class="form-group">
										<label class="control-label">To Date</label>									
										<div class="input-group">			
										<?php echo $this->form->to_date; ?>
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
											</div>																		
									</div>
								</div>	 
								<div class="col-sm-1" >	
									<input style="margin-top:21px; " type="button" value="+" id="AddDate" class="btn btn-primary">
								</div>	
						</div> */ ?>
								
					<?php /*		<?php if(count($this->itemResult)>0 ){ //print_r(count($this->itemResult)); 
							$i=1;
								foreach($this->itemResult as $key=>$value){ //echo $value; ?>
								<div class="row" style="margin-bottom:5px; margin-left: -8px;">
									<?php if($i !=1 ){ ?>
									<div class="col-sm-3"></div>
									<?php } ?>
									<div class="col-sm-3 " >				
									<div class="form-group">
										<label class="control-label">Percentage</label>
										<input type="text" class="form-control" id="percentage1" name="items[percentage1][]" value="<?php echo $value['percentage'];?>" placeholder=""/> 		
									</div>											
									</div>
									<div class="col-sm-2">				
										<div class="form-group">
										<label class="control-label">From Date</label>
											<div class="input-group">
											<input type="text" class="form-control from_date1" id="from_date1" name="items[from_date1][]" value="<?php echo $value['from_date'];?>" placeholder=""/> 
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
											</div>
										</div>											
									</div>
									<div class="col-sm-2" >				
										<div class="form-group">
											<label class="control-label">To Date</label>
											<div class="input-group">
												<input type="text"  class="form-control to_date1" id="to_date1" name="items[to_date1][]" value="<?php echo $value['to_date'];?>" placeholder=""/> 
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
											</div>	
										</div>											
									</div>
									<?php if($i==1){?>
									<div class="col-sm-1" >	
										<input style="margin-top:21px; " type="button" value="+" id="AddDate" class="btn btn-primary">
									</div>
									<?php }else{ ?>
										<a href="#"  class="removeclass btn btn-primary remove_class" style="margin-top:22px; margin-left:23px;" >-</a>
								<?php 	}?>
								</div>	
								<?php $i++; } ?>									
								<?php 	} ?>
								<span id="datefields"></span>								
							<div style="display:none" class="select_data" >        
								<div class="row appended_row  padding-top"  id="appended_row1" style="margin-bottom:5px; margin-left: -8px;">
									<div class="col-sm-3"></div>
									<div class="col-sm-3 " >				
									<div class="form-group">
										<label class="control-label">Percentage</label>
										<input type="text" class="form-control" id="percentage1" name="items[percentage1][]" >		
									</div>											
									</div>
									<div class="col-sm-2">				
										<div class="form-group">
										<label class="control-label">From Date</label>
										<div class="input-group">
										<input type="text" class="form-control from_date1" id="from_date1" name="items[from_date1][]" > 
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
											</div>	
										</div>											
									</div>
									<div class="col-sm-2" >				
										<div class="form-group">
											<label class="control-label">To Date</label>
											<div class="input-group">
											<input type="text"  class="form-control to_date1" id="to_date1" name="items[to_date1][]" >
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
											</div>
										</div>											
									</div>
									<a href="#"  class="removeclass btn btn-primary remove_class" style="margin-top:22px; margin-left: 34px;" >-</a>
								</div>		
							</div> */ ?>	
						</div>	
							
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="right_col">
<div class="row">
	<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Tax</i>
				
		</h3>
	</div>
	<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
		
		<a class="btn btn-primary pull-right" style="margin-top:25px;" href="<?php echo $this->mainconfig['host']; ?>master/tax/type/add">Add</a> 
			
	</div>
</div>
	<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Tax</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">

		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th>S.No.</th>								
						<th>Title</th>	
						<!-- <th>Percentage</th>	
						<th>From Date</th>
						<th>To Date</th> -->
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						
						<td><?php echo $results['title'];?></td>
						<?php  /* <td><?php echo $results['percentage'];?></td>
						<td><?php echo date( DATE_PREFIX, strtotime( $results['from_date']) ); ?></td>
						<td><?php echo date( DATE_PREFIX, strtotime( $results['to_date']) ); ?></td> */ ?>
					
						
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/tax/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;<a href="<?php echo $this->mainconfig['host']; ?>master/tax/type/delete/id/<?php echo $results['id']; ?>" class="delete" title="Delete"><span class="fa fa-trash-o fa-lg"></span> </a></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div><!-- /.padding-md -->	
</div>

<?php } ?>
<script>
	$(document).ready(function() {		
	// Datepicker
		$('#from_date').datepicker( {format: 'yyyy-mm-dd'} );
		$('#to_date').datepicker( {format: 'yyyy-mm-dd'} );
		$('.from_date1').datepicker( {format: 'yyyy-mm-dd'} );
		$('.to_date1').datepicker( {format: 'yyyy-mm-dd'} );
	});
	$("body").on("click","#AddDate", function(e){
		//$("#datefields").show();	
		$( "#appended_row1" ).clone().find("input:text").val("").end().appendTo( "#datefields" );
		$('.from_date1').datepicker( {format: 'yyyy-mm-dd'} );
		$('.to_date1').datepicker( {format: 'yyyy-mm-dd'} );
	});
	 $("body").on("click",".removeclass", function(e){	 
		   $(this).parent('div').remove(); 
               return false;
                 
    });
	/*$("body").on("click","#hideDate", function(e){
		$( "#datefields").hide( );		
	});*/
	
</script>