<script src="<?php echo $this->mainconfig['publicpath'];?>vendors/select2/dist/js/select2.full.min.js"></script>
<script src="<?php echo $this->mainconfig['publicpath'];?>js/jquery-ui.min.js"></script>
<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">  Term </i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					
							<div class="row ">
							<div class="col-sm-3">	
									<div class="form-group">
										<label class="control-label">Batch<span class="asterisk">*</span> </label>
										<?php echo $this->form->academic_year_id; ?>
									</div>										
								</div>
								<div class="col-sm-3">	
									<div class="form-group">
										<label class="control-label">Year <span class="asterisk">*</span> </label>
										<?php echo $this->form->year_id; ?>
									</div>										
								</div>
								
								
							
								<div class="col-sm-3">	
									<div class="form-group">
										<label class="control-label">Term Name <span class="asterisk">*</span> </label>
										<?php echo $this->form->term_name; ?>
									</div>										
								</div>
								
								<div class="col-sm-3">	
									<div class="form-group">
										<label class="control-label">Description <span class="asterisk">*</span> </label>
										<?php echo $this->form->term_description; ?>
									</div>										
								</div>
							</div>
								
								<div class="row">
							<div class="col-sm-3">
							<div class="form-group">
							<input type="text" id="payslipData" class="form-control"  style="background-color:#fdf59a;" readonly /></div>
							</div>
							</div>
							
								<div class="row">
								<div class="col-sm-3">	
									<div class="form-group">
										<label class="control-label ">Start Date <span class="asterisk">*</span> </label>
										<?php echo $this->form->start_date; ?>
									</div>										
								</div>
								
								<div class="col-sm-3">	
									<div class="form-group">
										<label class="control-label ">End Date <span class="asterisk">*</span> </label>
										<?php echo $this->form->end_date; ?>
									</div>										
								</div>
								<div class="col-sm-2" style="padding-top:30px;">	
								<p>Days : <span id="batch"></span></p>
								</div>
								<div class="col-sm-2" style="padding-top:30px;">	
								<p>Weeks : <span id="week"></span></p>
							  </div>
							  </div>
							  <div class="row">
						<div class="col-sm-3">
                            <div class="form-group">
                              <label class="control-label"> Total No. of Credits <span class="asterisk">*</span></label>
                                <?php echo $this->form->tot_no_of_credits; ?>
                            </div>
                          </div>
						  <div id="electives_credits_row">
							<div class="col-sm-3">
							<label class="control-label"> Total No. of Electives Credits <span class="asterisk">*</span></label>
							<input type="text" name="electives_credits" id="electives_credits"  class="form-control" value="<?php echo $this->result['electives_credits']; ?>"/>
							</div>
							</div>
						  </div>
							<input type="hidden" name="term_id" id="term_id" value="<?php echo $this->result['term_id']; ?>" />
						</div>
					
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>master/termmaster">Back</a>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars">  Term</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>master/termmaster/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2> Term</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
				<thead>
					<tr>
						<th>S.  No.</th>
						<th>Batch</th>
						<th>Year</th>
						<th>Term Name </th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Description </th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
					//	print_r($results);die;

					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>
									
								<td><?php echo $results['from_date'] .'&nbsp;&nbsp;-&nbsp;&nbsp;'. $results['to_date']; ?></td>
								<td><?php if ($results['year_id']==1){
									echo'First Year';
								}
								else{
									echo'Second Year';
								}
								 ?></td>
								<td><?php echo ($results['term_name']);?></td>
								<td><?php echo ($results['start_date']);?></td>
								<td><?php echo ($results['end_date']);?></td>								
								<td><?php echo ($results['term_description']);?></td>
								
								<td><a href="<?php echo $this->mainconfig['host']; ?>master/termmaster/type/edit/id/<?php echo $results['term_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/termmaster/type/delete/id/<?php echo $results['term_id']; ?>" title="Delete" class="delete" onclick="return ConfirmDelete();"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>	

$(document).ready(function() {		
	$("#start_date").datepicker({ dateFormat: 'dd/mm/yy' });  
	$("#end_date").datepicker({ dateFormat: 'dd/mm/yy' }); 
}); 
	
	
function ConfirmDelete()
 {
	 
      var x = confirm("Are you sure you want to delete?");
      if (x)
          return true;
      else
        return false;
}

$('body').on('change', '#academic_year_id', function() {		


var academic_id=$('#academic_year_id').val();
   if(academic_id){
   $('#payslipData').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#payslipData').val(result['short_code']);
			}
	  });
	 }
	 
 }); 
 

var academic_id=$('#academic_year_id option:selected').val();
   if(academic_id){
   $('#payslipData').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#payslipData').val(result['short_code']);
			}
	  });
	 }
	else{
			$('#payslipData').hide();
	} 



$('body').on('change', '#end_date', function() {
	

	var start_date=$('#start_date').val();
	var dateParts = start_date.split("/");
	var checkindate = new Date(dateParts[2], dateParts[1] - 1, dateParts[0]);
	
	
	var end_date=$('#end_date').val();
	var datePart = end_date.split("/");
	var check = new Date(datePart[2], datePart[1] - 1, datePart[0]);
	var difference = check - checkindate;
	var days = Math.floor(difference / (1000 * 3600 * 24));
	var diffWeeks = Math.floor(difference / (1000 * 60 * 60 * 24 * 7));
	
$('#batch').html(days);
$('#week').html(diffWeeks);
});

	var start_date=$('#start_date').val();
	var dateParts = start_date.split("/");
	var checkindate = new Date(dateParts[2], dateParts[1] - 1, dateParts[0]);
	
	
	var end_date=$('#end_date').val();
	var datePart = end_date.split("/");
	var check = new Date(datePart[2], datePart[1] - 1, datePart[0]);
	var difference = check - checkindate;
	var days = Math.floor(difference / (1000 * 3600 * 24));
	var diffWeeks = Math.floor(difference / (1000 * 60 * 60 * 24 * 7));
	
$('#batch').html(days);
$('#week').html(diffWeeks);

$('body').on('change','#year_id',function() {  
var year_id = $('#year_id').val();
if(year_id == '1'){
	$('#electives_credits_row').hide();

}
else if(year_id == '2'){
	$('#electives_credits_row').show();
}
});

var year_id = $('#year_id option:selected').val();
if(year_id == '1'){
	$('#electives_credits_row').hide();
}
else if(year_id == '2'){
		$('#electives_credits_row').show();
}	

/*  Ramesh == Before Dates Disable*/
$('body').on('change', '#academic_year_id', function() {		
var academic_id=$('#academic_year_id').val();
	
   if(academic_id){
   /*ajax-get_term_lastdate */
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-term-lastdate';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			
			if((data!='')){
				
			var last_date=result['end_date'];
			
			}
			$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-academic-year';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			
			if((data!='')){
				 
			var from_date1=result['from_date'];
			var to_date1=result['to_date'];
			$('input#start_date').datepicker('option', 'minDate', last_date);
			$('input#end_date').datepicker('option', 'minDate', last_date);
			$('input#start_date').datepicker('option', 'maxDate', to_date1);
			$('input#end_date').datepicker('option', 'maxDate', to_date1);
				
							}
				});
	  });
	}
	 
 });
 
 var academic_id = $('#academic_year_id option:selected').val(); 
 var term_id = $('#term_id').val();
 
  if(academic_id){
   
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-term-lastdate-edit';?>',
			data: {academic_id:academic_id,term_id:term_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			
			if((data!='')){
				
			var last_date=result['end_date'];
			
			//$('input#start_date').datepicker('option', 'minDate', last_date+"+1D");
			//$('input#end_date').datepicker('option', 'minDate', last_date+"+1D");
				//$('#payslipData').val(result['short_code']);
			}
			$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-academic-year';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			
			if((data!='')){
				 
				var from_date1=result['from_date'];
				var to_date1=result['to_date'];
				 
				$('input#start_date').datepicker('option', 'minDate', last_date);
				$('input#end_date').datepicker('option', 'minDate', last_date);
				$('input#start_date').datepicker('option', 'maxDate', to_date1);
				$('input#end_date').datepicker('option', 'maxDate', to_date1);
					
						}
			});
		});
	 }
</script>
