<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" novalidate>
					<div class="panel-heading">									
						 <h4>TransportFee</h4> 
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Branch</label>
									<?php echo $this->form->branch; ?>
								</div>									
							</div> 
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">currency</label>
									<?php echo $this->form->currency; ?>
								</div>									
							</div> 
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Rate per km/mile</label>
									<?php echo $this->form->rate_km; ?>
								</div>									
							</div>  
							 
							
							<!--<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Distance</label>
								<?php //echo $this->form->distance; ?>
								</div>									
							</div>  
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Pick Up</label>
									<?php //echo $this->form->pick_up; ?>
								</div>									
							</div>  
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Drop</label>
									<?php //echo $this->form->drop; ?>
								</div>									
							</div>  
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">Pick Up & Drop</label>
									<?php //echo $this->form->pick_upanddrop; ?>
								</div>									
							</div>  --> 
						
						</div>
						
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	

<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="padding-md">
	<div class="panel panel-default table-responsive">
		<div class="panel-heading">
			 TransportFee
			<a class="btn btn-primary pull-right" style="margin-top: -9px;" href="<?php echo $this->mainconfig['host']; ?>master/transport-fee/type/add">Add</a>

		</div>
		<div class="padding-md clearfix">
			<table class="table table-striped" id="dataTable">
				<thead>
					<tr>
						<th>S. No</th>								
						<th>Branch</th>
						<th>currency</th>
						<th>Rate per km/mile</th>	
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						<td><?php echo $results['branch_name']; ?></td>
						<td><?php echo $results['currency']; ?></td>
						<td><?php echo $results['rate_km'];?></td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/transport-fee/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/transport-fee/type/delete/id/<?php echo $results['id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div><!-- /.padding-md -->		

<?php } ?>
</div>
<script type="text/javascript">
$('body').on('change','#branch', function() {
	var id = $(this).val();	
	//alert(id);
		$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-branch-currency';?>',
			data: {id:id}
		}).done(function( data ) { 
			//$( "#currency").html( data );
			var result = $.parseJSON( data );
			//alert(result);
			$('#currency').val(result['countries_currency']);	
		 });
});
</script>