<tr class="sub">
    <td colspan="6">
        <!-- <div class="col-sm-0" style="float:right;">
                         <a class="btn btn-primary" target="_blank" href="<?php //echo $this->mainconfig['host'];  ?>grade-allocation/grade-pdf/id/<?php //echo $this->grade_report_id;  ?>">Print</a></div> -->
        <div class="col-sm-2" style="float:right;"><button class="close_tr btn btn-primary">Close</button></div>
        <br></br>
        <?php
        $item_result = $this->result1;

        $i = 1;

        $EvaluationComponents_model = '';
        $tot_arr = $geWeightage = array();
        $weightage_arr = $component_arr = array();

        for ($i = 0; $i < count($item_result); $i++) {
            ?>

            <div class="box-body">
                <?php if ($this->ge != '0') {
                    if ($k == 0) {
                        ?>
                        <h4 style="background-color:#3c8dbc;padding:8px 8px;color:white;">General Electives</h4>

            <?php $k++;
        } ?>
                <?php } else { ?>

                    <h4 style="background-color:#3c8dbc;padding:8px 8px;color:white;"><?php echo $item_result[$i]['term_name'] . '-' . $item_result[$i]['course_name']; ?></h4> 

    <?php } ?>
                <div class="table-responsive" style="overflow-x:scroll">
                   <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
                        <thead>
                            <tr>
                                <th rowspan="2">S. No.</th>
                                <th rowspan="2">Name of Participants</th>
                                <th rowspan="2">ID Number</th>
                                <th rowspan="2">Exam Roll No</th>
                                <?php if ($this->ge != '0') { ?>
                                    <th rowspan="2">Course</th>
                                    <th rowspan="2">Course Code</th>

                                <?php } ?>
                                <th>Component</th>
                                <?php
                                $EvaluationComponents_model = new Application_Model_EvaluationComponents();
                                $result = $EvaluationComponents_model->getAllComponents(0, $item_result[$i]['department_id'], $item_result[$i]['employee_id'], 0, $item_result[$i]['course_id']);
                                $course_learning = new Application_Model_ElectiveSelection();
                                $StudentPortal_model = new Application_Model_StudentPortal();
                                $category_data = $StudentPortal_model->getstudentsdetails($item_result[$i]['academic_year_id']);

                                //===============[If ge Available]======================//
                                if($this->ge != '0') {
      $newData = $EvaluationComponents_model->getAllComponents(0, $item_result[$i]['department_id'], $item_result[$i]['employee_id'], 0, $item_result[$i]['course_id']);
                                    foreach ($newData as $Studkey => $newVal) {
                                        if (!in_array($newVal['component_id'], $component_arr)) {
                                            $component_arr[] = $newVal['component_id'];
                                            $geWeightage[$newVal['component_id']] = $newVal;
                                        } else {
                                            if ($geWeightage[$newVal['component_id']]['weightage'] != $newVal['weightage']) {
                                                $geWeightage[$newVal['component_id']]['weightage'] .= " / {$newVal['weightage']}";
                                            }
                                        }
                                    }

                                    $raw_data = $course_learning->getStudentsForElectiveByCourse($item_result[$i]['academic_year_id'], $item_result[$i]['course_id'], $item_result[$i]['term_id'], $this->ge[$i] == $this->aecc ? 'aecc' : 'electives');
                                    $newData = selectData($raw_data, array('students', 'student_id', 'stu_id', 'course_id', 'aecc','exam_roll'), count($raw_data));


                                    foreach ($newData as $Studkey => $newVal) {
                                        $geData[] = $newVal;
                                    }
                                    if ($i < (count($item_result) - 1))
                                        continue;
                                    $result = $geWeightage;
                                    $category_data = $geData;
                                }


//                              echo "<pre>";print_r($result);exit;
                                //=========================[END GE]=======================//
                                foreach ($result as $k => $val) {
                                    ?>

                                    <th><?php echo $val['component_name']; ?></th>
                                    <th>Rem</th>
                                <?php } ?>
                                <th>Total</th>
                                <th>credit</th>
                                <th>Grade Letter</th>
                                <th>Grade Point</th>
                                <th>Credit Point</th>
                                <th>CC1 Rem</th>


                            </tr>
                            <tr>


                                <th>Weightage</th>
                                <?php foreach ($result as $k => $val) {
                                    
                                    ?>
                                    <th><?php
                          echo $val['weightage'];
                            $new_arr = explode('/', $val['weightage']);
                            foreach ($new_arr as $weightage_key => $to_val) {
                                $tot_arr[$weightage_key] += $to_val;
                            }
                                    ?></th>
                                    <th></th>
                                <?php
                                }
                                $total_sub_mks = array_unique($tot_arr);
                                $total_sub_mks = array_values($total_sub_mks);
                                $tot_arr = array_values($tot_arr);
                                ?>
                                <th><?= implode('/', $total_sub_mks); ?></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th>(Credit x Grade Point)</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $m = 1;
                              $corce = array();
                            foreach ($category_data as $stu_data) {
                                ?>
        <?php $prin_len = count($result); ?>
                                <tr>
                                    <td><?php echo $m; ?></td>						

                                    <td><?php echo $stu_data['students']; ?></td>
                            <input type="hidden" name="grade[student_id_<?php echo $item_result[$i]['term_id']; ?>_<?php echo $item_result[$i]['course_id']; ?>][]" id="student_id" value="<?php echo $stu_data['student_id']; ?>" />

                            <td><?php echo $stu_data['stu_id']; ?></td>
                            <td><?php echo $stu_data['exam_roll']; ?></td>

                            <?php
                            //==============[if GE Available]========================//
                            if ($this->ge != '0') {
                                $item_result[$i]['course_id'] = $this->ge[$i] == $this->aecc ? $stu_data['aecc'] : $stu_data['course_id'];
                                $course_details = new Application_Model_Course();
                                $course = $course_details->getRecord($item_result[$i]['course_id']);
                                ?>
                           
                                <td><?php echo $course['course_name'] ;if(!in_array($item_result[$i]['course_id'],$corce)){$corce[] = $item_result[$i]['course_id'];}?></td>
                                <td><?php echo $course['course_code'] ; ?></td>
                            <?php
                            }
 else {
     $corce[] = $item_result[$i]['course_id'];
 }

                            //=============================[END GE]===================//
                            ?>

                            <td></td>
                            <?php
                            $component_grades = '';
                            $pass_fail = 'P';

                            $total_marks_obained = $total = 0;

                            //foreach($result as $k => $val) { 


                            $GradeAllocation_model = new Application_Model_GradeAllocation();
                            $grade_result = $GradeAllocation_model->getGradeRecords($item_result[$i]['academic_year_id'], $item_result[$i]['department_id'], $item_result[$i]['employee_id'], $item_result[$i]['term_id'], $item_result[$i]['course_id'], $stu_data['student_id']);

                            $component_grades = $grade_result['component_id'];
                            //$grade = $grade_result['grade_value'];
                            $component_res = explode(",", $grade_result['component_id']);
                            $number_result = explode(",", $grade_result['number_value']);
                            $grade_result = explode(",", $grade_result['grade_value']);
                            ?>

                            <?php
                            $comp_weightages = '';
                            // echo "<pre>";print_r($grade_result);
                            foreach ($grade_result as $k => $grade_value) {
                                $prin_len--;

                                // echo "<pre>";print_r($number_result);
                                $style = '';

                                if (strtolower($grade_value) == 'f') {
                                    $style = '';
                                    $pass_fail = 'F';
                                } else if (strtolower($grade_value) == 'ab') {
                                    $number_result[$k] = $grade_value;
                                    $style = 'style="color: #ff0000"';
                                    $style1 = 'style="color: #ff0000"';
                                    $pass_fail = 'F';
                                } else if (strtolower($grade_value) == 'na' || empty($grade_value)) {
                                    $number_result[$k] = 'NA';
                                    $style = 'style="color: #ff0000"';
                                    $pass_fail = 'F';
                                }
                                ?>
                                <td <?= $style; ?>><?php echo $number_result[$k]; ?></td>

                                <?php $total_marks_obained += is_numeric($number_result[$k]) ? (int) $number_result[$k] : 0; ?>
                                
                                
                                 <?php    $marks_obained = is_numeric($number_result[$k]) ? (int) $number_result[$k] : 1; ?>
                            

                                <?php
                                $EvaluationComponentsItems_model = new Application_Model_EvaluationComponentsItems();
                                
                                
                                $comp_weigh = $EvaluationComponentsItems_model->getweightages(0, 0, $item_result[$i]['course_id'], $component_res[$k]);
                                
                            
                                $comp_weightages = $comp_weightages . $comp_weigh['weightage'] . ",";
                                         $tot_marks = (int)$comp_weigh['weightage'];
                                           
                                          $num = round(((int) $marks_obained / $tot_marks) * 100);
                                         
                                          $ref_grade_item = new Application_Model_ReferenceGradeMasterItems();
                                            $letter_grade = $ref_grade_item->getRecordByNumGrade($num); 
                                           
                                ?>
                           
                            
                                 <td <?php
                            if (strtolower($letter_grade) == 'f') {
                                echo 'style="color: #ff0000; font-weight:bolder"';
                            }
                            ?>><?=$letter_grade!='F'?'P':'F';?> </td>
                                
                                
                                
                            <?php } for ($o = 0; $o < $prin_len; $o++) { ?>

                                <td>--</td>
                                <td>--</td>


        <?php }
        ?>

                            <input type="hidden" name="grade[weightages_<?php echo $item_result[$i]['term_id']; ?>_<?php echo $item_result[$i]['course_id']; ?>][]" value="<?php echo $comp_weightages; ?>" />
                            <input type="hidden" name="grade[grades_<?php echo $item_result[$i]['term_id']; ?>_<?php echo $item_result[$i]['course_id'] ?>][]" value="<?php echo $component_grades; ?>" />
                            <td><?= number_format($total_marks_obained, 0); ?></td>
        <?php
        // total credit value 
        $core_course_master = new Application_Model_Corecourselearning();
        $course_credit_info = $core_course_master->getCoreCouseDetailByTermAcademicCourse($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], $item_result[$i]['course_id']);
                
        ?>                                                           
                            <td><?= $course_credit_info['count_id']==0?$course_credit_info['credit_value']:0; ?></td>


                            <?php
                            //letter grade

                            $total_marks_obained = $total_marks_obained != 0 ? $total_marks_obained : 1;
                            $tot_marks = $tot_arr[array_keys($corce,$item_result[$i]['course_id'],true)[0]];
                            $num = round(((int) $total_marks_obained / $tot_marks) * 100);
                            $ref_grade_item = new Application_Model_ReferenceGradeMasterItems();
                            $letter_grade = $ref_grade_item->getRecordByNumGrade($num);
                            ?>
                            <td <?php
                            if (strtolower($letter_grade) == 'f') {
                                echo 'style="color: #ff0000; font-weight:bolder"';
                            }
                            ?>><?= $letter_grade; ?></td>




                            <?php
                            //grade point
                            if (!is_numeric($letter_grade)) {

                                $ReferenceGradeMaster_model = new Application_Model_ReferenceGradeMaster();

                                $letter_grade_result = $ReferenceGradeMaster_model->getNumberGradeValue(0, $letter_grade);
                                $numeric_grade = $letter_grade_result['number_grade'];
                            } else if (is_numeric($letter_grade)) {

                                $numeric_grade = $letter_grade;
                            } $total = $course_credit_info['count_id']==0?$numeric_grade * $course_credit_info['credit_value']:0;
                            ?>

                            <td><?= $numeric_grade; ?></td>

                            <td><?php echo number_format($total, 0); ?></td>


                            <td <?php
                            if (strtolower($pass_fail) == 'f') {
                                echo 'style="color: #ff0000; font-weight:bolder"';
                            }
                            ?>><?= $pass_fail; ?></td>


                            <input type="hidden" name="grade[grade_point_<?php echo $item_result[$i]['term_id']; ?>_<?php echo $item_result[$i]['course_id']; ?>][]" value="<?php $tot = number_format($total, 2);
                            echo $tot; ?>" />

                            </tr>  
        <?php $m++;
    } ?>							

                        </tbody>
                    </table>
                </div>
            </div>
            <div id="addmore_items_<?php echo $i; ?>"></div>
            <br>
        <?php
        }

        function selectData($array, $fieldname, $number = 0) {
            try {
                $filterd_value = array();
                if (is_array($array) && is_array($fieldname)) {
                    for ($i = 0; $i < $number; $i++) {
                        foreach ($fieldname as $field_key => $field_value) {
                            $filterd_value[$i][$field_value] = $array[$i][$field_value];
                        }
                    }
                    return $filterd_value;
                } else {
                    throw new Exception('first and second param should be of type array !');
                }
            } catch (Exception $e) {

                echo '<strong>Error Message !</strong>' . $e->getMessage();
            }
        }
        ?>

    </td>
</tr>
<script>
    $(".close_tr").click(function () {
        $(".sub").hide();
    });
</script>
<script>
    $('table').each(function () {
        var check_val = $(this).find('thead>tr:nth-child(2)>th:nth-child(1)').text();
        var check_second_val = $(this).find('thead>tr:nth-child(1)>th:nth-child(2)').text();
        if (check_val.toLowerCase() != 'weightage' && check_second_val.toLowerCase() == 'name of participants') {
            $(this).attr('style', 'display:none');
        }
    });
</script>
