<style>

    #batch{
        display:none;
    }


</style>
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<div class="right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>   
    <div class="padding-md ">
        <div class="row">
            <?php
            if (count($this->messages)) {
                foreach ($this->messages as $message) {
                    ?>
                    <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                        <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                        <strong>  <?php echo $this->escape($message); ?></strong>
                    </div>
                <?php }
            }
            ?>
            <div class="col-md-12">
                <h3 class="page-title txt-color-blueDark" >
                    <div><i class="fa fa-eye">Accumulative Tabulation Register</i></div>
                </h3>
                <div class="panel panel-default">

                    <div class="panel-body">
                        <div class="row">
                            <div class="pull-right col-xs-2 col-sm-2 col-md-2 col-lg-2"><div class="pull-right"><span class="pull-left" style="margin-right:.3em;"><small><b>Archive</b></small></span><input type="checkbox" id="archive" value="0"   data-toggle="toggle" data-size="sm"></div></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                  <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->academic_year_id; ?>
                                </div>
                            </div>
                            <?php /* <div class="col-sm-3 employee_class">
                              <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                              <?php echo $this->form->year; ?>
                              </div>
                              </div> */ ?>


                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly /></div>
                            </div>
                        </div>
                        <div class="row">
                            <button type="button" class="btn btn-primary" onclick="Export()">Export <i class="fa fa-file-excel-o"></i></button>
                            <div id="course_grade_details"></div>
                        </div>


                    </div>

                    <div class="panel-footer">									

                    </div>
                </div><!-- /panel -->
            </div><!-- /.col-->				
        </div><!-- /.row -->

    </div><!-- /.padding-md -->
    <script src="<?php echo $this->mainconfig['publicpath']; ?>js/table2excel.js"></script> 
    <script>

                                                    function ConfirmPublish()
                                                    {
                                                        var x = confirm("Are you sure you want to Publish?");
                                                        if (x) {
                                                            $('.load-box').css('display', 'block');
                                                            return true;
                                                        } else
                                                            return false;
                                                    }
                                                    $('body').on('change', "#archive", function () {
                                                        var value = $(this).parent().attr("class");
                                                        if (value.includes("off")) {
                                                            $(this).removeAttr("checked");
                                                            $(this).val("0");
                                                        } else
                                                        {
                                                            $(this).attr("checked", "checked");
                                                            $(this).val("1");
                                                        }
                                                    });

                                                    $('body').on('change', '#academic_year_id,#archive', function () {
                                                        var academic_id = $('#academic_year_id').val();
                                                        var archive = $('#archive').val();
                                                        if (academic_id) {
                                                            $('#batch').show();
                                                            $.ajax({
                                                                type: "POST",
                                                                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch-code'; ?>',
                                                                data: {academic_id: academic_id}
                                                            }).done(function (data) {
                                                                var result = $.parseJSON(data);
                                                                if ((data != '')) {
                                                                    $('#batch').val(result['short_code']);
                                                                } else {
                                                                    $('#batch').hide();
                                                                }

                                                            });


                                                            $('.load-box').css('display', 'block');
                                                            if (academic_id) {
                                                                $.ajax({
                                                                    type: "POST",
                                                                    url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-grade-details-tr-all-new'; ?>',
                                                                    data: {academic_year_id: academic_id, archive: archive}
                                                                }).done(function (data) {

                                                                    $('#course_grade_details').empty();
                                                                    $('.load-box').css('display', 'none');
                                                                    $('#course_grade_details').html(data);
                                                                    $('#course_grade_details').trigger("chosen:updated");
                                                                });

                                                            }
                                                        }
                                                    });

                                                    function Export() {
                                                        var name = $('#academic_year_id>option:selected').text();
                                                        $("#dataTable").table2excel({
                                                            filename: name + ".xls"
                                                        });
                                                    }
    </script>