<script
    src="https://code.jquery.com/jquery-3.5.1.js"
    integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc="
crossorigin="anonymous"></script>
<style>
    table{
        margin:0;
    }
    .sub{
        border:.01em solid #932e90;

    }
    .logo{
        display:none;
    }



</style>
<div class="grade-data-container container text-center" style="margin-top:10px;">
    <table class="table table-striped table-bordered mb30 jambo_table bulk_action" width="100%" cellspacing ="0" >
        <thead>
            <tr>
                <th class="sub">
                    S.No
                </th>
                <th class="sub">
                    Name
                </th class="sub">
                <th class="sub">
                    Exam Roll
                </th>
                  <th class="sub">
                    Registration No.
                </th>
                 <th class="sub">
                    Form id
                </th>
                <th class="sub">
                    Phone
                </th>
                 <th class="sub">
                    Email
                </th>
            </tr>
        </thead>
        <tbody>
        <?php $i =0 ;
        array_multisort( array_column($this->result, "exam_roll"), SORT_ASC, $this->result );
        foreach($this->result as $key => $value){ ?>
                <tr>
                    <td class="sub"><?=++$i;?></td>
                    <td class="sub"><?=$value['stu_fname'];?></td>
                     <td class="sub"><?=$value['exam_roll'];?></td>
                     <td class="sub"><?=$value['reg_no'];?></td>
                     <td class="sub"><?=$value['stu_id'];?></td>
                     <td class="sub"><?=$value['father_mobileno'];?></td>
                     <td class="sub"><?=$value['stu_email_id'];?></td>
                </tr>

        <?php } ?>
        </tbody>


    </table>
</div>
</center>
</body>

</html>

