              <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
                                 <caption> <b> <u>Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th> 
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                        //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                           
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>report/pass-fail-report/type/edit/id/<?php echo $results['id']; ?>/term/<?php echo $this->term; ?>/session/<?php echo $this->session; ?>"class="edit" title="Edit" target="_blank" ><span class="fa fa-edit fa-lg"></span></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         
                
                