<style>
   
    #refresh{
        cursor:pointer;
    }
    
    
</style>
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

<div class="right_col bdoypayment">
    <div class="load-box" style="z-index:998">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
    
     <?php if($this->type){
       //  print_r($this->row);
         ?> 
     <div class="row">
                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-5">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars">Alumni Details</i>

                        </h3>
                    </div>
                </div>
 <form method="post" action="" enctype="multipart/form-data">
                    <div class="row">
                     
                                <div class=" col-lg-3 ">
                                    <div class="form-group">
                                        <label>Name <span style="color:red">*</span></label>
                                        <input type="text" name="name" id="name" required class="form-control alumin" value="<?=$this->row['name']?>" >
                                </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Course</label>
                                        <input type="text" name="course" id="course" class="form-control alumin" value="<?=$this->row['course']?>" >
                                </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Subject</label>
                                        <input type="text" name="subject" id="subject" class="form-control alumin" value="<?=$this->row['subject']?>" >
                                </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Batch</label>
                                        <input type="text" name="batch" id="batch" class="form-control alumin" value="<?=$this->row['batch']?>">
                                </div>
                                </div>
                                  
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Date of Birth</label>
                                        <input type="date" name="date_of_birth" id="date_of_birth" class="form-control alumin" value="<?=$this->row['date_of_birth']?>">
                                </div>
                                </div>
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Marital Status</label>
                                        <select name="marital_status" id="marital_status" class="form-control alumin">
                                            <option value="">Select</option>
                                            <option value="married" <?php if($this->row['marital_status']=='married') { echo "selected";} ?>>Married</option>
                                            <option value="unmarried" <?php if($this->row['marital_status']=='unmarried') { echo "selected";} ?>>Unmarried</option>
                                            <option value="other" <?php if($this->row['marital_status']=='other') { echo "selected";} ?>>Other</option>
                                        </select>
                                        
                                </div>
                                </div>
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Mobile No  ( Whatsapp Number Please)<span style="color:red">*</span></label>
                                        <input type="text" name="mobile" id="mobile" required class="form-control alumin" value="<?=$this->row['mobile']?>">
                                </div>
                                </div>
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Email-Id<span style="color:red">*</span></label>
                                        <input type="text" name="email_id" id="email_id" required class="form-control alumin" value="<?=$this->row['email_id']?>" >
                                </div>
                                </div>
                           <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Permanent Address</label>
                                        <textarea name="address" id="address" class="form-control alumin" style="height:34px" ><?=$this->row['address']?></textarea>
                                </div>
                                </div>
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>City</label>
                                        <input type="text" name="city" id="city" class="form-control alumin" value="<?=$this->row['city']?>" >
                                </div>
                                </div>
                                   <div class="col-md-3">
                                    <div class="form-group">
                                        <label>State</label>
                                        <input type="text" name="state" id="state" class="form-control alumin" value="<?=$this->row['state']?>">
                                </div>
                                </div>
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Pin Code / Zip</label>
                                        <input type="text" name="pincode" id="pincode" class="form-control alumin" value="<?=$this->row['pincode']?>" >
                                </div>
                                </div>
                                   <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Country</label>
                                        <input type="text" name="country" id="country" class="form-control alumin" value="<?=$this->row['country']?>">
                                </div>
                                </div>
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Professional Details</label><br>
                                        
                                        <input type="radio" name="professional_details" id="professional_details" class="" value="working" <?php if($this->row['professional_details']=='working') { echo "checked";} ?> > Working
                                       <input type="radio" name="professional_details" id="professional_details" class=""  value="Not Working" <?php if($this->row['professional_details']=='not working') { echo "checked";} ?>> Not Working
                                </div>
                                </div>
                                   <div class="col-md-3">
                                    <div class="form-group">
                                        <label>If Working, then Current Organization</label>
                                        <input type="text" name="org_name" id="academic_year_list" class="form-control alumin" value="<?=$this->row['org_name']?>">
                                </div>
                                </div>
                                   <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Current Designation</label>
                                        <input type="text" name="designation" id="designation" class="form-control alumin"  value="<?=$this->row['designation']?>">
                                </div>
                                </div>
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Area of Experience / Expertise</label>
                                        <input type="text" name="exprience" id="exprience" class="form-control alumin" value="<?=$this->row['exprience']?>">
                                </div>
                                </div>
                                  
                                  <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Are you ready to give your precious time for various Alumni activities ?</label><br>
                                        <input type="radio" name="time" id="time" class="" value="yes" <?php if($this->row['time']=='yes') { echo "checked";} ?>> Yes
                                        <input type="radio" name="time" id="time" class="" value="no" <?php if($this->row['time']=='no') { echo "checked";} ?>> No
                                        <input type="radio" name="time" id="time" class="" value="maybe" <?php if($this->row['time']=='maybe') { echo "checked";} ?>> Maybe
                                </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Payment Mode<span style="color:red">*</span></label>
                                        <select name="pay_mode" id="pay_mode" required class="form-control alumin">
                                            <option value="">Select</option>
                                            <option value="Online" <?php if($this->row['pay_mode']=='Online') { echo "selected";} ?>>Online</option>
                                            <option value="NEFT" <?php if($this->row['pay_mode']=='NEFT') { echo "selected";} ?>>NEFT</option>
                                            <option value="RTGS" <?php if($this->row['pay_mode']=='RTGS') { echo "selected";} ?>>RTGS</option>
                                        </select>
                                        
                                </div>
                                </div>
                                  <div class="col-md-3">
                                    <div class="form-group">
                                        <label>Life Membership Registration Amount</label>
                                        <input type="text" name="reg_amt" id="reg_amt" class="form-control alumin" value="<?=$this->row['reg_amt']?>" readonly="readonly" >
                                </div>
                                </div>
                           <div class="row" >
                                   <div class="col-md-3" id="payment" style="display: none;" >
                                    <div class="form-group">
                                        <label>Bank Name</label>
                                        <input type="text" name="bank_name" id="bank_name" class="form-control alumin" value="<?=$this->row['bank_name']?>" >
                                </div>
                                </div>
                                   <div class="col-md-3" id="payment1" style="display: none;">
                                    <div class="form-group">
                                        <label>Transaction ID</label>
                                        <input type="text" name="mmp_txn" id="transaction_id" class="form-control alumin" value="<?=$this->row['mmp_txn']?>">
                                </div>
                                </div>
                                  <div class="col-md-3" id="payment2" style="display: none;" >
                                    <div class="form-group">
                                        <label>UTR No.</label>
                                        <input type="text" name="bank_txn" id="utr_no" class="form-control alumin" value="<?=$this->row['bank_txn']?>">
                                </div>
                                </div>
                                  <div class="col-md-3" id="payment3" style="display: none;">
                                    <div class="form-group">
                                        <label>Transaction Date</label>
                                        <input type="date" name="date" id="adhar_doc" class="form-control alumin" value="<?=$this->row['date']?>" >
                                </div>
                                </div>
                                <!--  <div class="col-md-3" id="payment4" style="display: none;" >-->
                                <!--    <div class="form-group">-->
                                <!--        <label> Document (Allow Only .jpg/.png/.pdf)</label>-->
                                <!--        <input type="file" name="document" id="document" class="form-control alumin"  >-->
                                <!--</div>-->
                                <!--</div>-->
                                <div class="col-md-3" id="payment5" style="display: none;" >
                                    <div class="form-group">
                                        <label> Download Document </label>
                                        <ul><li><a href="<?php echo $this->mainconfig['publicpath'].'alumini/doc/'.$this->row['document'] ?>" download="<?php echo $this->row['document'] ?>"><?=$this->row['document']?></a></li></ul>
                                        
                                </div>
                                </div>
                                </div>        
                    </div>
                    <div class="row"><input type="submit" name="" class="btn btn-info"></div>
                              </form>

   <?php } else { ?>    
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-5">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars">Alumni Details</i>

                        </h3>
                    </div>
                </div>
                
                
<!--                <div class="row">
                  <div class="pull-right col-xs-2 col-sm-2 col-md-2 col-lg-2"><div class="pull-right"><span class="pull-left" style="margin-right:.3em;"><small><b>Attendance</b></small></span><input type="checkbox" id="attend" value="0" data-toggle="toggle" data-size="sm"></div></div>
            </div>
                <div class="row">
                    <div class="pull-right col-xs-2 col-sm-2 col-md-2 col-lg-2"><div class="pull-right"><span class="pull-left" style="margin-right:.3em;"><small><b>Tuition Fee</b></small></span><input type="checkbox" id="pay" value="1"  checked="" data-toggle="toggle" data-size="sm"></div></div>
            </div>-->
                <div class="col-md-12">
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                    <label class="control-label">From Date<span class="asterisk">*</span></label>
                        <?php //echo $this->form->academic_year; ?>
                    <input type="date" name="f_date" id="f_date" class="form-control">
                        </div>
                    </div>     
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                        <label class="control-label">To Date<span class="asterisk">*</span></label>
                     <?php //echo $this->form->session; ?>
                        <input type="date" name="to_date" id="to_date" class="form-control">
                        </div>
                    </div>
                  <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <button type="button" id="getRecords" class="btn btn-primary pull-right" style="margin-top:1.5em;z-index:999;" value="0" >Get Records</button>
                        </div>
                   </div>
                   
                   
                <div style="float:left;padding-left:10%;">
                </div>
                </div>
                 <div class="col-md-12">
                   <div class="table-responsive" id="ajaxData"> 
                       <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                            <thead>
                                <tr>

                                    <th class="no-sort">S.No.</th>
                                    <th>Alumni Name</th>
                                    <th>Email ID</th>
                                    <th>Course</th>
                                    <th>Subject</th>
                                    <th>Batch </th>
                                    <th>Mobile No </th>
                                    <th>Payment Mode</th>
                                    <th>Registration Amount</th>
                                    <th>Payment Status</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                                                <tr>
                                                    <td colspan="9">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                               

                            </tbody>
                        </table>

                        
                       
                    </div>
                </div>
       
            </div>    
           

        </div>
   <?php } ?>
        </div>
 
 <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>-->
 <script type="text/javascript">
 
 
 
    $('body').on('click', '#getRecords', function() {
    
    let f_date = $('#f_date').val();
    let to_date = $('#to_date').val();
   
    
    $('.load-box').css('display','block');
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-alumni-record'; ?>',
        data: {f_date:f_date,to_date:to_date}
    }).done(function (data) {
        $('#ajajxData').empty('');
        $('#ajaxData').html(data);
        $('.load-box').css('display','none');

    });
});
   
    $("#pay_mode").change(function() {
    var pay=$("#pay_mode").val();
    
   // alert(pay);
    if(pay=='NEFT' || pay=='RTGS') {
        $("#payment").css("display", "block");
        $("#payment1").css("display", "block");
        $("#payment2").css("display", "block");
        $("#payment3").css("display", "block");
        $("#payment4").css("display", "block");
        $("#payment5").css("display", "block");
        }
        else {
        $('#payment').css('display','none');
        $('#payment1').css('display','none');
        $('#payment2').css('display','none');
        $('#payment3').css('display','none');
        $('#payment4').css('display','none');
        $("#payment5").css("display", 'none');
        }
    });   
    
    
 var pay1=$("#pay_mode").val();   
  if(pay1=='NEFT' || pay1=='RTGS') {
        $("#payment").css("display", "block");
        $("#payment1").css("display", "block");
        $("#payment2").css("display", "block");
        $("#payment3").css("display", "block");
        $("#payment4").css("display", "block");
         $("#payment5").css("display", "block");
        }
        else {
        $('#payment').css('display','none');
        $('#payment1').css('display','none');
        $('#payment2').css('display','none');
        $('#payment3').css('display','none');
        $('#payment4').css('display','none'); 
        $("#payment5").css("display", 'none');
        }
    </script>

