<style>
   
    #refresh{
        cursor:pointer;
    }
    
    
</style>
<div class="right_col bdoypayment">
    <div class="load-box" style="z-index:998">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
     <div class="row">
                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars">Transaction Details</i>

                        </h3>
                    </div>
                </div>
        <div class="panel panel-default">
            
            <div class="panel-body">
               
                <div class="col-md-12">
                  
                   
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label" style="float:left;">From Date<span class="asterisk"></span></label>-->
                           <?php //echo $this->form->from_Date; ?>
						   <input type="date" name="from_Date" id="from_Date" value="<?=date('Y-m-d')?>" class="form-control" placeholder="From Date" autocomplete="off">
                        </div>
                   </div>
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label" style="float:left;">To Date<span class="asterisk"></span></label>-->
                           <?php //echo $this->form->to_Date; ?>
						   <input type="date" name="to_Date" id="to_Date" value="<?=date('Y-m-d')?>" class="form-control" placeholder="To Date" autocomplete="off">
                        </div>
                   </div>
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label" style="float:left;">Department <span class="asterisk"></span></label>-->
                           <?php echo $this->form->department; ?>
                        </div>
                   </div>
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label" style="float:left;">Semester <span class="asterisk"></span></label>-->
                           <?php echo $this->form->cmn_terms; ?>
                        </div>
                   </div>
                       
                   
                   <div class="col-md-12">
                   
                       
                       <div class="col-sm-3 col-sm-offset-3 employee_class">
                        <div class="form-group">
                          
                        </div>
                   </div>
                       
                    <div class="col-sm-3 employee_class">
                        
                        
                   </div>
                        <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <button type="button" id="getRecords" class="btn btn-primary pull-right" style="margin-top:1.5em;z-index:999;" value="0" >Get Records</button>
                        </div>
                   </div>
                   </div>
                   
                <div style="float:left;padding-left:10%;">
                </div>
                </div>
                 <div class="col-md-12">
                   <div class="table-responsive" id="ajaxData"> 
                       <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                            <thead>
                                <tr>

                                    <th class="no-sort">S.No.</th>

                                    <th>Student Name</th>


                                    <th>UID</th>

                                    <th>Transaction Id</th>
                                    <th>Status</th>
                                    <th>Pay Mode</th>
                                    <th>Amount</th>
                                    <th>Batch</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                               
                                                <tr>
                                                    <td colspan="9">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                               

                            </tbody>
                        </table>

                        
                       
                    </div>
                </div>
                
            </div>    
           

        </div>
       
        </div>
 


<script>
     $('.datepicker').datepicker();
//Author: Kedar: 22 Oct 2020 : To get record by filter crieteria

$('body').on('click', '#getRecords', function() {
    
    let to_date= $('#to_Date').val();
    let from_date= $('#from_Date').val();
    let department = $('#department').val();
    let sem= $('#cmn_terms').val();
    $('.load-box').css('display','block');
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-txn-record1'; ?>',
        data: {to_date:to_date,from_date:from_date,department:department,sem:sem}
    }).done(function (data) {
        $('#ajajxData').empty('');
        $('#ajaxData').html(data);
        $('.load-box').css('display','none');

    });
});

  $('#department').change(function(){
        //alert('x');
		$.ajax({
			type: "POST",
			url: '<?php echo $this->mainconfig['host'] . 'fee-collection/ajax-get-semester'; ?>',
			data: {
				// degree: $('#degree_id').val(),
				
				batch: $('#department').val()
			}
		}).done(function (data) {
			// console.log(data);
			$('#cmn_terms').empty('');
			$('#cmn_terms').html(data);
			$("#cmn_terms").trigger("chosen:updated");
		});
	});
	  

</script>

