<style>
     @media print 
     {
/*                    table td:nth-child(4)
                     {
                         display:none;
                     }
                     table th:nth-child(4)
                     {
                         display:none;
                     }*/
                      *{
                        visibility:hidden;
                     }
                     table,th,td 
                     {
                         visibility:visible;                    
                     } 
                     .title1
                     {
                        visibility:visible; 
                     }
                   
     }
  </style> 
<div class="padding-md right_col">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye title1"> <?php echo $this->sub_title_name; ?></i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
							<div class="row">
															
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_year_id; ?>
                            </div>
							</div> 
							
							
							
							
							
							
							</div>
                                            <div class="col-sm-0" style="float:right;">
                                   <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host']; ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id; ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
							<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
                              <label class="control-label">&nbsp;</label>
							<input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly />
							</div>
						</div>
						</div>
						<div id="getstudent" class="col-sm-12">
							</div>
							</div>
						
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	


<script>
 jQuery(document).ready(function() {
		$('#batch').hide();
        $('body').on('change', function() {
			
            getstudentDetails();
        });
});
 
	
    function getstudentDetails() {
        $url = '<?php echo $this->mainconfig['host']; ?>report/ajax-student-cgpa-report';
        $.post($url,
                {
                    'academic_id': $('#academic_year_id').val()
        }).done(function(data) {
                  
                    //$('#payslipData').html('');
                    $('#getstudent').html(data);
                });

    }
    $('#print').click(function(){
window.print('#grade_data');
});






</script>