<style>
    @media print {
/*                    table td:nth-child(5)
                     {
                         display:none;
                     }
                     table th:nth-child(5)
                     {
                         display:none;
                     }*/
                      *{
                        visibility:hidden;
                     }
                     table,th,td 
                     {
                         visibility:visible;                    
                     } 
                     .title1
                     {
                        visibility:visible; 
                     }
                }
</style>
<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12 " >
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Fee Heads</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
						  <div class="row">

							<div class="col-sm-3 employee_class">
                            <div class="form-group" >
                            <label  class="control-label" >Fee Category<span class="asterisk">*</span></label>
                            <?php echo $this->form->feecategory_id; ?>
                            </div>
							</div>
						
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">Fee Heads Name<span class="asterisk">*</span></label>
                            <?php echo $this->form->feehead_name; ?>
                            </div>
							</div>
							</div>
							
					<!--	 <?php /* if(count($this->item_result)>0){
							//		print_r($this->item_result);die;
							$i=0;
						   foreach($this->item_result as $val){ 
						$i++; */
					?>
					<div class="row" id="" style="">
					
							<div class="col-sm-3">
							<label>Fee Head Name<span class="asterisk">*</span></label>
							<input type="text"  label="feehead_name_<?php // echo $i;?>"  class="form-control feehead_name" name="Fee[feehead_name][]" placeholder="" value="<?php echo $val['feehead_name'];?>"/> 
							</div>				  
													
						<a href="#" class="removeclass btn btn-primary remove_class" style="padding:7px 15px;margin:24px 15px; ">-</a>
						</div>   
					<?php // } ?>
					 <div class="col-sm-3"></div>    
					<input type="button" value="+" id="AddButton" class="btn btn-primary adjust-size" style="padding:7px 15px;margin-left:9px;">
					
					<?php  // }  else {    ?>
					 
		<input type="hidden" name="count_val" id="count_val" value="1" class="count_val" />  
		<div class="row" style="">
	
		<div class="col-sm-3"><label> Fee Head Name <span class="asterisk">*</span></label> <input type="text"  label="feehead_name_0"  class="form-control" name="Fee[feehead_name][]" style="" placeholder="Name" value="" /> 
		</div>
            <input type="button" value="+" id="AddButton" class="btn btn-primary adjust-size" style="padding:7px 15px;margin:24px 15px;"> 
       	
		
	</div>
	<?php // } ?>
       <div id="fields">
         <div class="padding-top"></div>
        </div>   -->
					</div>
					<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>fee-heads/index/">Back</a>
										</div>
										<?php }		?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars">Participants Assignment</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                        <h2 class="title1">Participants Assignment</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                    
                    
                    
                          <div class="panel panel-default">
                <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

                    <div class="panel-body">

                        <div class="row">
                            <div class="col-sm-3 employee_class ">
                                <div class="form-group ">

                                    <?php if ($this->type != 'edit') { ?>
                                        <label class="control-label ">Batch<span class="asterisk">*</span></label>
                                        <?php echo $this->form->academic_year_id; ?>
                                    <?php } ?>
                                </div>
                            </div>

                            <div class="col-sm-3 employee_class">
                                <div class="form-group">

                                    <?php if ($this->type != 'edit') { ?>
                                        <label class="control-label">Term <span class="asterisk">*</span></label>
                                        <?php echo $this->form->term_id; ?>
                                    <?php } ?>
                                </div>
                            </div>
                            
                            
                             <div class="col-sm-3 employee_class">
                            <div class="form-group">
                          
                            
                                  <label class="control-label">Course<span class="asterisk">*</span></label>
                                <?php echo $this->form->course_id; ?>
                            
                            </div>
							</div> 

                            <div class="col-sm-3 employee_class">




                                <!-- <div class="col-sm-3 employee_class">
    <div class="form-group">
    <label class="control-label">Credit<span class="asterisk">*</span></label>
                                <?php //echo $this->form->credit_id; ?>
    </div>
                                </div> -->
                            </div>
                        </div>
                        <div id="grade_data">
                        </div>

                    </div>
                    
                    
                    
                    
            <div class="x_content">
		
		<div class="padding-md clearfix">
                    <div class="col-sm-0" style="float:right;">
                                   <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host']; ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id; ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th style="text-align:center;">As. ID</th>	
						<th style="text-align:center;">Participant ID</th>
						<th style="text-align:center;">Name</th>
						<th style="text-align:center;">Download</th>
                                                <th style="text-align:center;">Uploaded Date</th>
					</tr>
				</thead>
				<tbody style="text-align:center;" id='mainData'>
					        


				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>	
 
	
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}


/*
var count = $('#count_val').val(); //Addmore script code

$("body").on("click","#AddButton",function(event){
		var count_value = count++;
		//alert(count_value);
		append_html = '<div class="row">';
		
		append_html += '<div class="col-sm-3 employee_class" style=""><label class="control-label "></label><input type="text"  class="form-control ec"  name="Fee[feehead_name][]"  style=" background:#FFFFFF;" label="feehead_name_'+count_value+'"   /></div>';
		append_html += '<a href="#" class="removeclass6 btn btn-primary remove_class6 " style="padding:7px 15px;margin:20px 15px;">-</a>';
		append_html += '</div>';	
        $('#count_val').append(count_value);		
		$('#fields').append(append_html);
		
		});
		$("body").on("click",".removeclass6", function(e){
		//alert('sdsd');

                $(this).parent('div').remove(); 				
				
        return false;

    });  */
    
    
    $('#term_id').change(function(){
        var academic_id = $('#academic_year_id').val();
        var term_id  = $(this).val();
        
        
     
    // alert(academic_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'].'participant-assignment/ajax-get-course';?>',
                data: {academic_year_id: academic_id,term_id: term_id}
            }).done(function (data) {
                //alert(data);
                $('#course_id').empty('');
                $('#course_id').html(data);
            });
    
    
 
        
        
        

        
        
    });
    
    
    
    $('#course_id').change(function(){
     var academic_id = $('#academic_year_id').val();
        var term_id  = $("#term_id").val();
        var course_id = $("#course_id").val();
                if(academic_id){
                 $.ajax({
                            type: "POST",
                            url: '<?php echo $this->mainconfig['host'] . 'participant-assignment/ajax-get-assignment-view'; ?>',
                            data: {term_id: term_id, batch: academic_id,course_id: course_id}
                        }).done(function (data) {
                           $('#mainData').empty();
                           $('#mainData').html(data);
                        });
                        }
    });
    
    
    
        $("#academic_year_id").change(function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#term_id').empty('');
                $('#term_id').html(data);
            })
        } 
    });
        
    
    
	

</script>


