<?php if ($this->type) { ?>
<div class="padding-md right_col">
	<div class="row">
		<div class="col-md-12">
			<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Fee Due Date</i></div>
				
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					<div class="row">
						<div class="col-sm-3">	
							<div class="form-group">
								<label class="control-label">Dump Year Planing </label>
								<?php echo $this->form->dump_year_planing; ?>
							</div>										
						</div>
					</div>	
						<div class="row">
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Country <span class="asterisk">*</span></label>
									<?php echo $this->form->country_id; ?>
								</div>										
							</div> 
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">State <span class="asterisk">*</span></label>
									<?php echo $this->form->state_id; ?>
								</div>										
							</div> 
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">City <span class="asterisk">*</span></label>
									<?php echo $this->form->city_id; ?>
								</div>										
							</div> 
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Location <span class="asterisk">*</span></label>
									<?php echo $this->form->location_id; ?>
								</div>										
							</div> 
						</div>
						<div class="row">							
							<?php /* <div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Branch <span class="asterisk">*</span></label>
									<?php echo $this->form->branch_id; ?>
									
								</div>										
							</div> */ ?>
						
							<span id="branch_id"></span>
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label"> Academic Year <span class="asterisk">*</span></label>
									<?php echo $this->form->academic_year; ?>
								</div>										
							</div>
						</div>	
						<div id="academic">
						<?php 
									
									if(!empty($this->item_result)){
											  $i=0; ?>
									<input type="hidden" name="fee_payment" id="fee_payment" value="<?php echo (count($this->item_result) +1 ); ?>" class="fee_payment">
									<?php
									foreach($this->item_result as $val){
									//print_r($val);die;
									//$total_amount += $val['total_price'];
									$i++;
									?>
										<div  class="row appended_row ">
											<div class="col-md-3">
												<label class="control-label">Fee Payment Frequency</label>		
												<select type="text" name="fre[frequency][]" label="frequeny0"  class="form-control">
												<?php  foreach($this->feepaymentfrequency as $k => $val1) { 
												$selected = '';
												if($k == $val['frequency']){
												$selected = "selected";
												} ?>
												
												<option value="<?php echo $k;?>" <?php echo $selected; ?>><?php echo $val1; ?></option>
												<?php }?>
												</select>
											</div>
											<div class="col-md-3" >
													<div class="form-group">
													<label class="control-label">Fine Amount</label>		
														<input type="text" name="fre[fine_amount][]" label="fine<?php echo $i;?>" class="form-control" value="<?php echo $val['fine_amount'];?>">
												</div>
											</div> 
											<div class="col-md-3">
												<label class="control-label">From Date</label>	
												<div class="input-group">
												<input type="text" name="fre[from_date][]" id="from_date<?php echo $i; ?>"  class="form-control from_date" value="<?php	echo $val['from_date']; ?>">
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>
											<div class="col-md-3">
												<label class="control-label">To Date</label>	
												<div class="input-group">
												<input type="text" name="fre[to_date][]" id="to_date<?php echo $i; ?>"  class="form-control to_date"  value="<?php
												echo $val['to_date']; ?>">
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>
										</div>
										<div class="row append_row">	
											<div class="col-sm-3">	
												<div class="form-group">
													<label class="control-label"> Payment Due Date</label>									
													<div class="input-group">			
														<input type="text" name="fre[payment_due_date][]" id="payment_due_date<?php echo $i; ?>"  class="form-control payment_due_date"  value="<?php echo $val['payment_due_date']; ?>">
														<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
													</div>
												</div>										
										</div>
										<div class="col-sm-3">	
											<div class="form-group">
												<label class="control-label">Fee Payment Reminder Date (Before)</label>									
												<div class="input-group">			
													<input type="text" name="fre[fee_payment_reminder_date_before][]" id="fee_payment_reminder_date_before<?php echo $i; ?>"  class="form-control fee_payment_reminder_date_before" value="<?php echo $val['fee_payment_reminder_date_before']; ?>">
													<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>	
											</div>
											<div class="col-sm-3">	
											<div class="form-group">
												<label class="control-label">Fee Payment Reminder Date (After)</label>									
												<div class="input-group">			
													<input type="text" name="fre[fee_payment_reminder_date_after][]" id="fee_payment_reminder_date_after<?php echo $i; ?>"  class="form-control fee_payment_reminder_date_after" value="<?php echo $val['fee_payment_reminder_date_after']; ?>">
													<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>	
											</div>
											
										
											<a  class="removeclass2 btn btn-primary remove_class2 " style="margin:24px 15px; padding: 7px 19px!important;" href="#">-</a>
										</div>
										
																					
									<?php		} 
											?>
										<div  class=" appended_row "><div class="col-sm-3"></div><div class="col-sm-3"></div><div class="col-sm-3"></div><a id="AddButton" class="btn btn-primary" style="margin:24px 20px; padding: 7px 19px!important;">+</a> 
										</div>
									<?php } else { ?>
										<input type="hidden" name="fee_payment" id="fee_payment" value="1" class="fee_payment">
										<div class="row appended_row">
											<div class="col-md-3">
												<label class="control-label">Fee Payment Frequency</label>		
												<select type="text" name="fre[frequency][]" label="frequeny0"  class="form-control">
												<?php  foreach($this->feepaymentfrequency as $k => $val) { ?>
												<option value="<?php echo $k;?>"><?php echo $val; ?></option>
												<?php }?>
												</select>
											</div>
											<div class="col-md-3">
													<div class="form-group">
														<label class="control-label">Fine Amount</label>	
														<input type="text" name="fre[fine_amount][]" label="fine0" class="form-control">
												</div>
											</div>  
											<div class="col-md-3">
												<label class="control-label">From Date</label>	
												<div class="input-group">
												<input type="text" name="fre[from_date][]" id="from_date0"  class="form-control from_date">
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>
											<div class="col-md-3">
												<label class="control-label">To Date</label>	
												<div class="input-group">
												<input type="text" name="fre[to_date][]" id="to_date0"  class="form-control to_date">
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>
										</div>	
										<div class="row appended_row">
											<div class="col-sm-3">	
												<div class="form-group">
													<label class="control-label"> Payment Due Date</label>									
													<div class="input-group">			
														<input type="text" name="fre[payment_due_date][]" id="payment_due_date0"  class="form-control payment_due_date">
														<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
													</div>
												</div>										
										</div>
										<div class="col-sm-3">	
											<div class="form-group">
												<label class="control-label">Fee Payment Reminder Date (Before)</label>									
												<div class="input-group">			
													<input type="text" name="fre[fee_payment_reminder_date_before][]" id="fee_payment_reminder_date_before0"  class="form-control fee_payment_reminder_date_before">
													<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>										
										</div>
										<div class="col-sm-3">	
											<div class="form-group">
												<label class="control-label">Fee Payment Reminder Date (After)</label>									
												<div class="input-group">			
													<input type="text" name="fre[fee_payment_reminder_date_after][]" id="fee_payment_reminder_date_after0"  class="form-control fee_payment_reminder_date_after" >
													<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>	
											</div>
										<a id="AddButton" class="btn btn-primary" style="margin:24px 15px; padding: 7px 19px!important;">+</a>
									</div>
										<?php } ?>
									
									<div  id="fields">
										<div class="padding-top"></div>
									</div>
								<span class="copy_append" style="display:none;">
									<option value="">Select</option>
												<?php foreach($this->feepaymentfrequency as $k=>$asset){?>
												<option value="<?php echo $k;?>"><?php echo $asset;?></option>
											<?php }?>
									</span>	
									 
									
								<?php /* 	if(!empty($this->date_result)){
											  $i=0; ?>
									<input type="hidden" name="dates" id="dates" value="<?php echo (count($this->date_result) +1 ); ?>" class="dates">
									<?php
									foreach($this->date_result as $val){
									//print_r($val);die;
									//$total_amount += $val['total_price'];
									$i++;
									?>
										<div  class="row appended_row " style="margin-left:33px;">
											<div class="col-md-3">
												<label class="control-label">From Date</label>	
												<div class="input-group">
												<input type="text" name="date[from_date][]" id="from_date<?php echo $i;?>"  class="form-control" value="<?php echo $val['from_date']; ?>">
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>
											<div class="col-md-3">
												<label class="control-label">To Date</label>	
												<div class="input-group">
												<input type="text" name="date[to_date][]" id="to_date<?php echo $i;?>"  class="form-control" value="<?php echo $val['to_date']; ?>">
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>
											<a  class="removeclass2 btn btn-primary remove_class2 " href="#">Remove</a>
											</div> 
									<?php		} 
											?>
										<div  class=" appended_row " style="margin-top: -10px; margin-bottom: 20px;  margin-left:-20%;"> <a id="AddButton1" class="btn btn-primary" style="margin-top: 4px;">Add More</a> 
										</div>
									<?php } else { ?>
									<div  class="row appended_row">
										<input type="hidden" name="dates" id="dates" value="1" class="dates">
											<div class="col-md-3">
												<label class="control-label">From Date</label>	
												<div class="input-group">
												<input type="text" name="date[from_date][]" id="from_date0"  class="form-control">
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>
											<div class="col-md-3">
												<label class="control-label">To Date</label>	
												<div class="input-group">
												<input type="text" name="date[to_date][]" id="to_date0"  class="form-control">
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
												</div>
											</div>
											
										<a id="AddButton1" class="btn btn-primary" style="margin-top:24px; padding: 7px 19px!important;">Add More</a> 
									</div>
										<?php } ?>
									
									<div  id="fields1">
										<div class="padding-top"></div>
									</div>   
						<div class="row">
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label"> Payment Due Date</label>									
									<div class="input-group">			
										<?php echo $this->form->payment_due_date; ?>
										<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									</div>
								</div>										
							</div>
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Fee Payment Reminder Date</label>									
									<div class="input-group">			
										<?php echo $this->form->fee_payment_reminder_date; ?>
										<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									</div>
								</div>										
							</div> */ ?>
					
					
							<?php  /* <div class="col-sm-3">	
								<div class="form-group" style="margin-left:-15px;">
									<label class="control-label"> Start Date <span class="asterisk">*</span></label>									
									<div class="input-group">			
										<?php echo $this->form->academic_year_start_date; ?>
										<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									</div>
								</div>										
							</div>
							
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label"> End Date <span class="asterisk">*</span></label>									
									<div class="input-group">			
										<?php echo $this->form->academic_year_end_date; ?>
										<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									</div>
								</div>										
							</div>
							</div>
						
						<?php //echo '<pre>';print_r($this->itemResult);?>
						<?php if(count($this->monthitemResult)>0){
							$i=1;
							foreach($this->monthitemResult as $k =>$val){ 
								if($i ==1){
						?>
						
						<div class="row">						
							<div class="col-sm-3 " style="margin-top:23px;">
								<select type="text" name="monthly" id="monthly" class="form-control" >
									<option value="1">monthly</option>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="monthly_fine_amount" value="<?php echo $val['fine_amount'];?>"  class="form-control">
							</div>
						</div>
						
						<?php }?>
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[month_from_date][]" value="<?php echo $val['from_date'];?>" class="fromdate<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[month_to_date][]" value="<?php echo $val['to_date'];?>" class="todate<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[month_due_date][]" value="<?php echo $val['due_date'];?>" class="date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
						
						<?php $i++;} }else{?>
						<div class="row">						
							<div class="col-sm-3 " style="margin-top:23px;">
								<select type="text" name="monthly" id="monthly" class="form-control" >
									<option value="">Select</option>
									<option value="1">monthly</option>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="monthly_fine_amount" value=""  class="form-control">
							</div>
						</div>
						<div style="display:none" class="select_data" id="monthlyFields" > 
							<?php for($i=1;$i<=12;$i++){ ?>
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[month_from_date][]"   value="" class="fromdate<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[month_to_date][]" value="" class="todate<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[month_due_date][]" value="" class="date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
							<?php } ?>
						</div>
						<?php }?>
						<!-- Quarterly -->
						<?php if(count($this->qtyitemResult)>0){
							$j = 1;
							foreach($this->qtyitemResult as $k =>$val){ 
								if($j ==1){
						?>
						
						<div class="row" style="margin-top:5px;">						
							<div class="col-sm-3 " style="margin-top:23px;">								
								<select type="text" name="quarterly"  id="quarterly" class="form-control" >	
									<option value="2">Quarterly</option>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="qty_fine_amount" value="<?php echo $val['fine_amount'];?>"  class="form-control">
							</div>
						</div>
						<?php }?>
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($j==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[qty_from_date][]" value="<?php echo $val['from_date'];?>" class="qty-from-date<?php echo $j;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($j==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[qty_to_date][]" value="<?php echo $val['to_date'];?>" class="qty-to-date<?php echo $j;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($j==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[qty_due_date][]" value="<?php echo $val['due_date'];?>" class="qty-date<?php echo $j;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
						<?php $j++;}}else{?>
						
						<div class="row" style="margin-top:5px;">						
							<div class="col-sm-3 " style="margin-top:23px;">								
								<select type="text" name="quarterly"  id="quarterly" class="form-control" >
									<option value="">Select</option>
									<option value="2">Quarterly</option>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="qty_fine_amount" value=""  class="form-control">
							</div>
						</div>
						
						<div style="display:none" class="select_data" id="quarterlyFields" > 
							<?php for($i=1;$i<=4;$i++){ ?>
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[qty_from_date][]" value=""  class="qty-from-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[qty_to_date][]" value="" class="qty-to-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[qty_due_date][]" value="" class="qty-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
							<?php } ?>
						</div>
						<?php } ?>
						<!-- Term -->
						<?php if(count($this->termitemResult)>0){
							$a = 1;
							foreach($this->termitemResult as $k =>$val){ 
								if($a ==1){
						?>
						
						<div class="row" style="margin-top:5px;">						
							<div class="col-sm-3 " style="margin-top:23px;">								
								<select type="text" name="term"  id="term" class="form-control" >	
									<option value="3">Term</option>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="term_fine_amount" value="<?php echo $val['fine_amount'];?>"  class="form-control">
							</div>
						</div>
						<?php }?>
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($a==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[term_from_date][]" value="<?php echo $val['from_date'];?>" class="qty-from-date<?php echo $a;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($a==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[term_to_date][]" value="<?php echo $val['to_date'];?>" class="qty-to-date<?php echo $a;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($a==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[term_due_date][]" value="<?php echo $val['due_date'];?>" class="qty-date<?php echo $a;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
						<?php $a++;}}else{?>
						<div class="row" style="margin-top:5px;">						
							<div class="col-sm-3 " style="margin-top:23px;">								
								<select type="text" name="term"  id="term" class="form-control" >
									<option value="">Select</option>
									<option value="3">Term</option>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="term_fine_amount" value=""  class="form-control">
							</div>
						</div>
						<div style="display:none" class="select_data" id="termFields" > 
							<?php for($i=1;$i<=3;$i++){ ?>
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[term_from_date][]" value=""  class="qty-from-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[term_to_date][]" value="" class="qty-to-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[term_due_date][]" value="" class="qty-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
							<?php } ?>
						</div>
						<?php } ?>
						
						<?php if(count($this->halfitemResult)>0){
							$m=1;
							foreach($this->halfitemResult as $k =>$val){
								if($m ==1){
						?>
						
						<div class="row" style="margin-top:5px;">						
							<div class="col-sm-3 " style="margin-top:23px;">								
								<select type="text" name="half_yearly" id="half_yearly" class="form-control" >
									<option value="4">Half Yearly</option>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="half_fine_amount" value="<?php echo $val['fine_amount'];?>"  class="form-control">
							</div>
						</div>
						<?php }?>
						
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($m==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[half_from_date][]" value="<?php echo $val['from_date'];?>" class="half-from-date<?php echo $m;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($m==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[half_to_date][]" value="<?php echo $val['to_date'];?>" class="half-to-date<?php echo $m;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($m==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[half_due_date][]" value="<?php echo $val['due_date'];?>" class="half-date<?php echo $m;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
						
						<?php $m++; } }else{?>
						<div class="row" style="margin-top:5px;">						
							<div class="col-sm-3 " style="margin-top:23px;">								
								<select type="text" name="half_yearly" id="half_yearly" class="form-control" >
									<option value="">Select</option>
									<option value="4">Half Yearly</option>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="half_fine_amount" value=""  class="form-control">
							</div>
						</div>
 
						<div style="display:none" class="select_data" id="halfYearlyFields" > 
							<?php for($i=1;$i<=2;$i++){ ?>
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">
										
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[half_from_date][]"  value="" class="half-from-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[half_to_date][]" value="" class="half-to-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[half_due_date][]" value="" class="half-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
							<?php } ?>
						</div>
						<?php } ?>
						
						<?php if(count($this->yearitemResult)>0){
							$l=1;
							foreach($this->yearitemResult as $k =>$val){ 
									if($l ==1){
						?>
						<div class="row" style="margin-top:5px;">						
							<div class="col-sm-3 " style="margin-top:23px;">								
								<select type="text" name="yearly"  id="yearly" class="form-control" >
																		 
									<?php //foreach($this->Nutrition as $k=>$val){
									?>										
									<option value="5">Yearly</option>
									<?php //}?>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="year_fine_amount" value="<?php echo $val['fine_amount'];?>"  class="form-control">
							</div>
						</div>
						<?php } ?>
							
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($l==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[year_from_date][]" value="<?php echo $val['from_date'];?>" class="year-from-date<?php echo $l;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($l==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[year_to_date][]" value="<?php echo $val['to_date'];?>" class="year-to-date<?php echo $l;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($l==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[year_due_date][]" value="<?php echo $val['due_date'];?>" class="year-date<?php echo $l;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
						<?php $i++; } }else{?>
						
						<div class="row" style="margin-top:5px;">						
							<div class="col-sm-3 " style="margin-top:23px;">								
								<select type="text" name="yearly"  id="yearly" class="form-control" >
									<option value="">select</option>									 
									<?php //foreach($this->Nutrition as $k=>$val){
									?>										
									<option value="5">Yearly</option>
									<?php //}?>
								</select>
							</div>
							<div class="col-sm-3 ">
								<label class="control-label">Fine Amount </label>
								<input type="text"  name="year_fine_amount" value=""  class="form-control">
							</div>
						</div>
						
						<div style="display:none" class="select_data" id="YearlyFields" > 
							<?php for($i=1;$i<=1;$i++){ ?>
							<div class="row" style="margin-top:5px;">
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">From Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wisefrom_date; ?>
											<input type="text" name="dueDate[year_from_date][]"  value="" class="year-from-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>	
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">To Date</label><?php }?>									
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[year_to_date][]" value="" class="year-to-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
								<div class="col-sm-3 ">	
									<div class="form-group">
										<?php if($i==1){?><label class="control-label">Payment Due Date</label><?php }?>
										<div class="input-group">			
											<?php //echo $this->form->term_wiseto_date; ?>
											<input type="text" name="dueDate[year_due_date][]" value="" class="year-date<?php echo $i;?> form-control">
											<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
										</div>
									</div>	
								</div>
							</div>
							<?php } ?>
						</div>
						<?php } ?> */ ?>
						</div>
						</div>
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="right_col">
	
		<div class="row">
	<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Fee Due Date</i>
				
		</h3>
	</div>
	<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
		
		<a class="btn btn-primary pull-right" style="margin-top:25px;" href="<?php echo $this->mainconfig['host']; ?>master/academic-year-planing/type/add">Add </a>

			
	</div>
</div>
	<div class="x_panel">
               
                    <div class="x_title">
                    <h2> Fee Due Date</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th>S.No.</th>												
						<th>Location</th>
						<th>Academic Year</th>
						<!-- <th>Academic Year End Date</th> -->
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						//print_r($results);die;

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>						
						<td><?php echo $results['location_name']; ?></td>
						<td><?php echo $results['academic_year_name']; ?></td>
						<!-- <td><?php //echo date( DATE_PREFIX, strtotime($results['academic_year_start_date'])); ?></td>
						<!-- <td><?php //echo date( DATE_PREFIX, strtotime($results['academic_year_end_date'])); ?></td> -->						
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/academic-year-planing/type/edit/id/<?php echo $results['academic_year_planing_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/academic-year-planing/type/delete/id/<?php echo $results['academic_year_planing_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div>
</div><!-- /.padding-md -->		
<?php } ?>
<script>
$(document).ready(function() {
	
	$('body').on('change', '#country_id', function() {
		var id = $(this).val();		
		if(id){			
			$.ajax({ 
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'ajax/state';?>',
				data: {country_id:id}
			}).done(function( data ) {
				$( "#state_id").html( data );
			});
		}
	});
	
	$('body').on('change', '#state_id', function() {
		var id = $(this).val();		
		if(id){			
			$.ajax({ 
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'ajax/city';?>',
				data: {state_id:id}
			}).done(function( data ) {
				$( "#city_id").html( data );
			});
		}
	});
	
	$('body').on('change', '#city_id', function() {
		var id = $(this).val();		
		if(id){			
			$.ajax({ 
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'ajax/academic-location';?>',
				data: {city_id:id}
			}).done(function( data ) {
				$( "#location_id").html( data );
			});
		}
	});
	$('body').on('change','#location_id', function() {
		var id = $(this).val();		
		if(id){			
			$.ajax({ 
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'master/ajax-get-branches';?>',
				data: {location_id:id}
			}).done(function( data ) {
				$( "#branch_id").html( data );
			});
		}
	});
	var id = $('#location_id option:selected').val();
	if(id){			
			$.ajax({ 
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'master/ajax-get-branches';?>',
				data: {location_id:id}
			}).done(function( data ) {
				$( "#branch_id").html( data );
			});
		}
	
	// Datepicker
	$('#fee_payment_reminder_date_before0').datetimepicker( {dateFormat: 'yyyy-mm-dd hh:ii' } );
$('.fee_payment_reminder_date_before').datetimepicker( {dateFormat: 'yyyy-mm-dd hh:ii' } );
$('.fee_payment_reminder_date_after').datetimepicker( {dateFormat: 'yyyy-mm-dd hh:ii' } );
$('.from_date').datepicker( {dateFormat: 'yy-mm-dd' } );
$('.to_date').datepicker( {dateFormat: 'yy-mm-dd' } );
$('.payment_due_date').datepicker( {dateFormat: 'yy-mm-dd' } );
	$('#fee_payment_reminder_date_after0').datetimepicker( {dateFormat: 'yy-mm-dd hh:ii' } );
	$('#payment_due_date0').datepicker({dateFormat: 'yy-mm-dd'});
	$('#from_date0').datepicker({dateFormat: 'yy-mm-dd'});
	$('#to_date0').datepicker({dateFormat: 'yy-mm-dd'});
	$('.date1').datepicker({dateFormat: 'yy-mm-dd'});
	$('.date2').datepicker({format: 'yyyy-mm-dd'});
	$('.date3').datepicker({format: 'yyyy-mm-dd'});
	$('.date4').datepicker({format: 'yyyy-mm-dd'});
	$('.date5').datepicker({format: 'yyyy-mm-dd'});
	$('.date6').datepicker({format: 'yyyy-mm-dd'});
	$('.date7').datepicker({format: 'yyyy-mm-dd'});
	$('.date8').datepicker({format: 'yyyy-mm-dd'});
	$('.date9').datepicker({format: 'yyyy-mm-dd'});
	$('.date10').datepicker({format: 'yyyy-mm-dd'});
	$('.date11').datepicker({format: 'yyyy-mm-dd'});
	$('.date12').datepicker({format: 'yyyy-mm-dd'});
	
	$('.fromdate1').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate2').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate3').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate4').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate5').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate6').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate7').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate8').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate9').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate10').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate11').datepicker({format: 'yyyy-mm-dd'});
	$('.fromdate12').datepicker({format: 'yyyy-mm-dd'});
	
	$('.todate1').datepicker({format: 'yyyy-mm-dd'});
	$('.todate2').datepicker({format: 'yyyy-mm-dd'});
	$('.todate3').datepicker({format: 'yyyy-mm-dd'});
	$('.todate4').datepicker({format: 'yyyy-mm-dd'});
	$('.todate5').datepicker({format: 'yyyy-mm-dd'});
	$('.todate6').datepicker({format: 'yyyy-mm-dd'});
	$('.todate7').datepicker({format: 'yyyy-mm-dd'});
	$('.todate8').datepicker({format: 'yyyy-mm-dd'});
	$('.todate9').datepicker({format: 'yyyy-mm-dd'});
	$('.todate10').datepicker({format: 'yyyy-mm-dd'});
	$('.todate11').datepicker({format: 'yyyy-mm-dd'});
	$('.todate12').datepicker({format: 'yyyy-mm-dd'});
	
	$('.qty-from-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-from-date2').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-from-date3').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-from-date4').datepicker({format: 'yyyy-mm-dd'});
	
	$('.qty-to-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-to-date2').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-to-date3').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-to-date4').datepicker({format: 'yyyy-mm-dd'});
	
	$('.qty-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-date2').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-date3').datepicker({format: 'yyyy-mm-dd'});
	$('.qty-date4').datepicker({format: 'yyyy-mm-dd'});
	
	$('.half-from-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.half-from-date2').datepicker({format: 'yyyy-mm-dd'});
	
	$('.half-to-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.half-to-date2').datepicker({format: 'yyyy-mm-dd'});
	
	$('.half-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.half-date2').datepicker({format: 'yyyy-mm-dd'});
	
	$('.year-from-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.year-from-date2').datepicker({format: 'yyyy-mm-dd'});
	
	$('.year-to-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.year-to-date2').datepicker({format: 'yyyy-mm-dd'});
	
	$('.year-date1').datepicker({format: 'yyyy-mm-dd'});
	$('.year-date2').datepicker({format: 'yyyy-mm-dd'});
	
	//$('.form-control').attr('required','required');
	
	$('#academic_year_start_date').datepicker({dateFormat: 'yy-mm-dd'});
	$('#academic_year_end_date').datepicker({dateFormat: 'yy-mm-dd'});
	

});
		
	$('body').on('change', '#monthly', function() {	
		var id = $(this).val();	
		if(id != ''){ 
			$("#monthlyFields").show();
		}else{
			$("#monthlyFields").hide();
		}	
	});
	
	$('body').on('change', '#term', function() {	
		var id = $(this).val();	
		if(id != ''){ 
			$("#termFields").show();
		}else{
			$("#termFields").hide();
		}	
	});	
	
	$('body').on('change', '#quarterly', function() {	
		var id = $(this).val();	
		if(id != ''){ 
			$("#quarterlyFields").show();
		}else{
			$("#quarterlyFields").hide();
		}	
	});	
	
	
	$('body').on('change', '#half_yearly', function() {	
		var id = $(this).val();	
		if(id != ''){ 
			$("#halfYearlyFields").show();
		}else{
			$("#halfYearlyFields").hide();
		}	
	});	
	
	$('body').on('change', '#yearly', function() {	
		var id = $(this).val();	
		if(id != ''){ 
			$("#YearlyFields").show();
		}else{
			$("#YearlyFields").hide();
		}	
	});	
	function rangeMonth($datestr) {
    date_default_timezone_set(date_default_timezone_get());
    $dt = strtotime($datestr);
    $res['start'] = date('Y-m-d', strtotime('first day of this month', $dt));
    $res['end'] = date('Y-m-d', strtotime('last day of this month', $dt));
    return $res;
    }
$('body').on('change','#dump_year_planing', function(){
	var id = $(this).val();	
	//alert(id); 
	if(id != '' ){	
		$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-academic-year-planning-dump';?>',
			data: {id:id}
		}).done(function( data ) {
			$( "#academic").html( data );
			
		 });
	}
});
var count = $('#fee_payment').val();
		$("body").on("click","#AddButton",function(event){
			
		var value = count++;
			append_html = '<div class="row" style="margin:0px 05px;">';
			append_html += '<div class="row">';
			append_html += '<div class="col-md-3"><label class="control-label">Fee Payment Frequency</label><select type="text" name="fre[frequency][]" label="frequency'+value+'" class="form-control">'+$('.copy_append').html()+'</select></div>';		
			append_html += '<div class="col-md-3"><div class="form-group"><label class="control-label">Fine Amount</label><input type="text" name="fre[fine_amount][]" label="fine'+value+'" class="form-control"></div></div>';
			append_html +=	'<div class="col-md-3"><label class="control-label">From Date</label>	<div class="input-group"><input type="text" name="fre[from_date][]" id="from_date'+value+'"  class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div>';
			append_html += '<div class="col-md-3"><label class="control-label">To Date</label><div class="input-group"><input type="text" name="fre[to_date][]" id="to_date'+value+'"  class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div>';
			append_html += '</div>';
			append_html += '<div class="row">';
			append_html += '<div class="col-sm-3"><div class="form-group"><label class="control-label"> Payment Due Date</label><div class="input-group"><input type="text" name="fre[payment_due_date][]" id="payment_due_date'+value+'"  class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div></div>';
			append_html += 	'<div class="col-sm-3"><div class="form-group"><label class="control-label">Fee Payment Reminder Date (Before)</label><div class="input-group"><input type="text" name="fre[fee_payment_reminder_date_before][]" id="fee_payment_reminder_date_before'+value+'"  class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div></div>';
			append_html += 	'<div class="col-sm-3"><div class="form-group"><label class="control-label">Fee Payment Reminder Date (After)</label><div class="input-group"><input type="text" name="fre[fee_payment_reminder_date_after][]" id="fee_payment_reminder_date_after'+value+'"  class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div></div>';
			append_html += '</div>';
			append_html += 	'<div class="col-sm-3"></div><div class="col-sm-3"></div><div class="col-sm-3"></div>';
			append_html += '<a href="#" class="removeclass2 btn btn-primary remove_class " style="margin:-82px 25px 0px; padding: 7px 19px!important;"">-</a>';
			append_html += '</div>';	
													
		$('#fields').append(append_html);
		$(".no-margin input[id='from_date"+value+"']").datepicker({dateFormat: 'yyyy-mm-dd'});
		$(".no-margin input[id='to_date"+value+"']").datepicker({format: 'yyyy-mm-dd'});
		$(".no-margin input[id='payment_due_date"+value+"']").datepicker({format: 'yyyy-mm-dd'});
		$(".no-margin input[id='fee_payment_reminder_date_before"+value+"']").datetimepicker( {format: 'yyyy-mm-dd hh:ii' } );
		$(".no-margin input[id='fee_payment_reminder_date_after"+value+"']").datetimepicker( {format: 'yyyy-mm-dd hh:ii' } );
	});
	/* var count = $('#dates').val();
		$("body").on("click","#AddButton1",function(event){
		var value1 = count++;
			append_html = '<div class="row">';
			append_html += '<div class="col-md-3"><label class="control-label">From Date</label><div class="input-group"><input type="text" name="date[from_date][]" id="from_date'+value1+'"  class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div>';
			append_html +=	'<div class="col-md-3"><label class="control-label">To Date</label><div class="input-group"><input type="text" name="date[to_date][]" id="to_date'+value1+'"  class="form-control"><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div>';
			append_html += '<a href="#" class="removeclass2 btn btn-primary remove_class " style="width:102px padding-top:5px;">Remove</a>';
			append_html += '</div>';													
		$('#fields1').append(append_html);
		$(".no-margin input[id='from_date"+value1+"']").datepicker({format: 'yyyy-mm-dd'});
		$(".no-margin input[id='to_date"+value1+"']").datepicker({format: 'yyyy-mm-dd'});
	}); */
	$("body").on("click",".removeclass2", function(e){
		//alert('sdsd');

                $(this).parent('div').remove(); 				
				
        return false;

    });
	$('body').on('click','#select1',function() {
//alert('sdsd'); 
var id = $('#select1').val();
  if(id == 'Select All') {
      // Iterate each checkbox
      $('.checkbox').each(function() {
          this.checked = true;
      });
  }
  else {
    $('.checkbox').each(function() {
          this.checked = false;
      });
  }
}); 
$('body').on('click','#unselect1',function() {
var id = $('#unselect1').val();
//alert(id);
  if(id == 'Unselect All') {
      // Iterate each checkbox
      $('.checkbox').each(function() {
          this.checked = false;
      });
  }
  else {
    $('.checkbox').each(function() {
          this.checked = true;
      });
  }
}); 


</script>
