<style>

    .link:link,
    .link:visited{
        position: relative;
        display: inline-block;
        padding:.2em 2em;
        border-radius:100px;
        /*  background-color:#faa2b1;*/
        -webkit-transition: all .2s;
        transition: all .2s;
    }


    .link::after{
        content: "";
        position:absolute;
        top:0px;
        left:0px;
        background-color:#faa2b1; 
        width:100%;
        height:100%;
        z-index:-1;
        border-radius:100px;
        -webkit-transition: all .2s;
        transition: all .2s;
    }



    .link:hover{
        box-shadow:0px 5px 6px #000;
    }

    .link:hover::after{
        transform:scale(2,3);

    }

    .link:active{
        box-shadow:0px 5px 1px #000;
    }

    dt{
        display:none;
    }

</style>
<link href="<?php echo $this->mainconfig['publicpath']; ?>css/custom.css" rel="stylesheet">
<div class="right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <?php if ($this->type=='add' || $this->type=='edit') { ?>
        <div class="padding-md">
            <div class="row">
                <div class="col-md-12 " >
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Schedule Tuition Fees </i></div>
                    </h3>
                    <div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

                            <div class="panel-body">
                                <div class="row">

      
                                    <div class="col-sm-3 employee_class" style="display:none;">
                                        <div class="form-group">
                                            <label  class="control-label" >Session<span class="asterisk">*</span></label>
                                            <?php echo $this->form->session_id; ?>
                                           
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label  class="control-label" >Session<span class="asterisk">*</span></label>
                                            <?php echo $this->form->session_id; ?>
                                           
                                        </div>
                                    </div>
                                     <?php echo $this->form->csrftoken; ?>
                                        <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">End Semester<span class="asterisk">*</span></label>
                                            <?php echo $this->form->year; ?>
                                        </div>
                                        </div>
                                        <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label"> Degree <span class="asterisk">*</span></label>
                                            <?php echo $this->form->degree_id; ?>
                                        </div>
                                        </div>
                                    
           
                                   
                                    <div class="col-sm-3 employee_class">
                                         <div class="form-group">
                                            <label class="control-label">Hon's Course<span class="asterisk">*</span></label>
                                            <?php echo $this->form->department; ?>
                                        </div>
                                    </div>
                                    
                                    
                                </div>
                                <div class="row">

                                      <div class="col-sm-3 employee_class">
                                            <div class="form-group">
                                                <label class="control-label">Start Date<span class="asterisk">*</span></label>
                                                <?php echo $this->form->feeForm_start_date; ?>
                                            </div>
                                        </div>      


                                      <div class="col-sm-3 employee_class">
                                            <div class="form-group">
                                                <label class="control-label"> End Date<span class="asterisk">*</span></label>
                                                <?php echo $this->form->feeForm_end_date; ?>
                                            </div>
                                        </div>      
                                       
                                         <div class="col-sm-3 employee_class">
                                            <div class="form-group">
                                                <label class="control-label"> Extended Date<span class="asterisk">*</span></label>
                                                <?php echo $this->form->feeForm_extended_date; ?>
                                            </div>
                                        </div> 
                                       <div class="col-sm-1 employee_class">
                                            <div class="form-group">
                                                <label class="control-label">Late Fine Fee @ <span class="asterisk">*</span></label>
                                                <?php echo $this->form->fineFee; ?>
                                            </div>
                                        </div>      
                                      <div class="col-sm-1 employee_class">
                                            <div class="form-group">
                                                <label class="control-label">per @ Day<span class="asterisk">*</span></label>
                                                <?php echo $this->form->perday_number; ?>
                                            </div>
                                        </div>  
                                        <!--<div class="col-sm-3 employee_class">
                                            <div class="form-group">
                                                <label class="control-label">Product Id (Account Name) <span class="asterisk">*</span></label>
                                                <?php //echo $this->form->product_id; ?>
                                            </div>
                                        </div> -->     
                                        <!--<div class="col-sm-3 employee_class">
                                            <div class="form-group">
                                                <label class="control-label">Account No <span class="asterisk">*</span></label>
                                                <?php ///echo $this->form->account_number; ?>
                                            </div>
                                        </div>-->
                                </div>
                                <div class="col-sm-6 employee_class">
                                    <span id="dobError" style="color:red;"></span>
                                </div>
                            </div>

                  
                    <div class="row">

                    </div>
                    </div> 
                </div>
                <div>
                    <div class="panel-footer">									
                        <div class="row">
                            <div class="col-sm-7 col-sm-offset-5">
                                <?php if ($this->type == 'add') { ?> 
                                    <div style="float:left;margin-right:2px;">
                                        <button class="btn btn-primary submit" onclick="return confirmUpdate()">Submit</button>
                                    </div>
                                    <div style="float:left;padding:0px 10px;">
                                        <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                    </div>
                                <?php } else { ?>
                                    <div style="float:left;">
                                        <button class="btn btn-primary submit" onclick="return confirmUpdate()">Update</button>
                                    </div>
                                    <div style="float:left;">
                                        <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>master/coursefee/">Back</a>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
                </form>
            </div><!-- /panel -->
        </div><!-- /.col-->				
    </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

    <?php
    if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                <?php echo $this->escape($message); ?>
            </div>
            <?php
        }
    }
    ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Schedule Semester Fees </i>

                    </h3>
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>master/createtuitionfees/type/add">Add </a>
                </div>
            </div>

            <div class="x_panel">

                <div class="x_title">
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label  class="control-label" >Academic Year<span class="asterisk">*</span></label>--->
                            <?php echo $this->form->academic_year; ?>

                        </div>
                    </div>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label  class="control-label" >Session<span class="asterisk">*</span></label>-->
                            <?php echo $this->form->session_id; ?>

                        </div>
                    </div>
                        <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">End Semester<span class="asterisk">*</span></label>-->
                            <?php echo $this->form->year; ?>
                        </div>
                        </div>
                        <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label"> Degree <span class="asterisk">*</span></label>-->
                            <?php echo $this->form->degree_id; ?>
                        </div>
                        </div>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="ajaxData" id="ajaxData">
                                    <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
                                        <thead>
                                            <tr>
                                                <th>S.No.</th>	
                                                <th>End Semester</th>
                                                <th>Degree</th>
                                                <th>Hon's Course</th>
                                                <th>Start Date</th>
                                                <th>End Date</th>
                                                <th>Exam Form Extended Date</th>
                                     
                                                <th>Late Fine @</th>
                                                <th>Per @ Day</th>
                                                <th>Product id</th>
                                                <th>Account No.</th>
                                                <th class="no_print" style="text-align:center;">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody style="text-align:center" >
                                  <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                       //print_r($results);die;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['term_name']; ?></td>
                                            <td><?php echo $results['degree']; ?></td>
                                            <td><?php echo $results['department']; ?></td>
                                           
                                            <td><?php
                                            $start_date = date_create($results['feeForm_start_date']);
                                            echo date_format($start_date,"d/m/Y"); ?>
                                            </td>
                                            <td><?php 
                                            $end_date = date_create($results['feeForm_end_date']);
                                            echo date_format($end_date,"d/m/Y"); ?>
                                            </td>
                                            <td><?php 
                                            $extended_date = date_create($results['feeForm_extended_date']);
                                            echo date_format($extended_date,"d/m/Y"); ?>
                                            </td>
                                            <td><?php echo $results['fineFee']; ?></td>
                                            <td><?php echo $results['perday_number']; ?></td>
                                            <td><?php echo $results['product_id']; ?></td>
                                            <td><?php echo $results['account_number']; ?></td>
                                            <td style="text-align:center" >
                                             
                                            <?php if($results['status']=='0') {?>
                                            <a title="Active" href="<?php echo $this->mainconfig['host']; ?>master/createtuitionfees/type/delete/id/<?php echo $results['id']; ?>/update/<?php echo $results['status']; ?>" <span style="color:green" class="fa fa-unlock fa-lg"></span>
                                            <?php } else {?>
                                          <a title="Deactived" href="<?php echo $this->mainconfig['host']; ?>master/createtuitionfees/type/delete/id/<?php echo $results['id']; ?>/update/<?php echo $results['status']; ?>" <span style="color:red" class="fa fa-lock fa-lg"></span>
                                                      
                                            <?php } ?>
                                              <a style="float: right" title="Edit" href="<?php echo $this->mainconfig['host']; ?>master/createtuitionfees/type/edit/id/<?php echo $results['id']; ?>" <span  class="fa fa-edit fa-lg"></span>
                                             
                                          </td>
                                                    </tr>    
                                          
                            <?php
                                }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                            ?>

                            </tbody>
                        </table>
                        </div>
                    </div>
                    </div>
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
<?php } ?>
</div>
<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script>    
<script>
    $('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session_id').empty('');
                $('#session_id').html(data);
                $('#session_id').trigger("chosen:updated");
            });
        }
    });
    $('body').on('change', '#degree_id', function () {
        //alert('Sm');
       $('.load-box').css('display','block');
        let degree = $(this).val();
        let session = $('#session_id').val();
        let cmn_term = $('#cmn_terms').val();

       
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-filter-tuition-fees'; ?>',
                data: {degree: degree,session:session,cmn_term:cmn_term}
            }).done(function (data) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
            });
        

    });
    var exam_start_date= $('#feeForm_start_date').val();
    var dateAr = exam_start_date.split('/');
    var feeForm_start_date = dateAr[2] + '/' + dateAr[1] + '/' + dateAr[0];
    
    var fullDate = new Date();
    var month = fullDate.getMonth()+1;
    var day = fullDate.getDate();

    var currentDate = fullDate.getFullYear() + '/' +(month<10 ? '0' : '') + month + '/' +(day<10 ? '0' : '') + day;

    if(new Date(currentDate) > new Date(feeForm_start_date) ){
//        $('#examFee').prop('readonly', true); 
        $('#fineFee').prop('readonly', false); 
    }
   
    
    function ConfirmDelete()
    {
        var x = confirm("Are you sure you want to delete?");
        if (x)
            return true;
        else
            return false;
    } 
    //Date: 18 oct Kedar
    $('.examFeePicker').datepicker({ format: 'dd/mm/yyyy' });   
    
    
    //Department on change degree id
//    $('body').on('change', '#degree_id', function () {
//        $('#deptId').empty('');
//        var degree_id = $('#degree_id').val();
//        if (degree_id) {
//            
//            $.ajax({
//                type: "POST",
//                url: '<?php echo $this->mainconfig['host'] .'master/ajax-get-dept-for-bulk'; ?>',
//                data: {degree_id: degree_id}
//            }).done(function (data) {
//                
//                $('#deptId').html(data);   
//                $('#department').select2();   
//            });
//        }
//    });
    $('body').on('change', '#degree_id', function () {
        $('#department').empty('');
        var degree_id = $('#degree_id').val();
        if (degree_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] .'master/ajax-Get-Dept'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                
                $('#department').html(data).trigger("chosen:updated");   
            });
        }
    });
    // EXam Fee Date select validation
    $('#dobError').text("");
    function confirmUpdate(){
        var start_date= $('#feeForm_start_date').val();
        var end_date= $('#feeForm_end_date').val();
        var extend_date= $('#feeForm_extended_date').val();
       
        var dateAr = start_date.split('/');
        var feeForm_start_date = dateAr[2] + '/' + dateAr[1] + '/' + dateAr[0]; 
        
        var dateAr1 = end_date.split('/');
        var feeForm_end_date = dateAr1[2] + '/' + dateAr1[1] + '/' + dateAr1[0]; 
        
        var dateAr2 = extend_date.split('/');
        var feeForm_extended_date = dateAr2[2] + '/' + dateAr2[1] + '/' + dateAr2[0]; 
        
        if(new Date(feeForm_end_date) <= new Date(feeForm_start_date) ){
          
           $('#dobError').text("*Form End date should not be equal or less than Form Start date.");
           $('#feeForm_end_date').val('');
           return false;
        }else if(new Date(feeForm_extended_date) <= new Date(feeForm_start_date) ){
          
           $('#dobError').text(" *Form Extended date should not be equal or less than Form Start date.");
           $('#feeForm_extended_date').val('');
           return false;
        }else if(new Date(feeForm_extended_date) <= new Date(feeForm_end_date) ){
        
           $('#dobError').text("*Form Extended date should not be equal or less than Form End date.");
           $('#feeForm_extended_date').val('');
           return false;
        }else{
            $('#dobError').text("");
        }
        return true;
    }
    
     //Dsiable Editing In Core Course Learning Date : 25 Oct 2021
    let type='<?= $this->type ?>';
    if(type == 'edit'){
        //disable the field
        
        $("#session_id").prop( "disabled", true ); 
        $("#cmn_terms").prop( "disabled", true ); 
        $("#degree_id").prop( "disabled", true ); 
        $("#department").prop( "disabled", true ); 
        
    

        //right before the form submits, we re-enable the fields, to make them submit.
        $( "#formValidate1" ).submit(function( event ) {
        $("#session_id").prop( "disabled", false );
        $("#cmn_terms").prop( "disabled", false );
        $("#degree_id").prop( "disabled", false );
        $("#department").prop( "disabled", false );
 
    });   
    }
//End
    
</script>
