<?php //$skill_type = unserialize($this->result['skill_type']);
						//print_r( $this->result['skill_type']);die;
if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" novalidate>
					<div class="panel-heading">									
						 <h4>Academic Assessment - Skill Type</h4> 
					</div>
					<div class="panel-body">
						<div class="row">							
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Sub Area</label>
									<?php echo $this->form->sub_area; ?>
								</div>										
							</div> 
						<?php /* 	<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Skill Type</label>
									<?php echo $this->form->skill_type; ?>
								</div>										
							</div>  */ ?>
							<?php 
									
									if(!empty($this->skill_type)){
											  $i=0; ?>
									<input type="hidden" name="skill_count" id="skill_count" value="<?php echo (count($this->skill_type) +1 ); ?>" class="skill_count">
									<?php
									foreach($this->skill_type as $val){
									//print_r($val);die;
									//$total_amount += $val['total_price'];
									$i++;
									?>
										<div  class="row appended_row ">
											<div class="col-md-3">
												<label class="control-label">Skill Type</label>		
												<input type="text"  class="form-control " label="skill_<?php echo $i; ?>" name="skill_type[]" value="<?php echo $val; ?>"  />
											</div>
											<a  class="removeclass3 btn btn-primary remove_class3 " href="#" style="margin:24px 15px; padding:7px 19px;">-</a>
											</div> 
									<?php		} 
											?>
										<div  class=" appended_row "><div class="col-md-3"></div><div class="col-md-3"></div> <a id="AddButton" class="btn btn-primary" style="margin:10px 22px; padding:7px 19px;">+</a> 
										</div>
									<?php } else { ?>
									<div  class="row appended_row ">
										<input type="hidden" name="skill_count" id="skill_count" value="1" class="skill_count">
											<div class="col-md-3">
												<label class="control-label">Skill Type</label>		
												<input type="text"  class="form-control" name="skill_type[]"label="skill_0"  />
											</div>
										<a id="AddButton" class="btn btn-primary" style="margin:24px 15px 0px; padding: 7px 19px!important;">+</a> 
									</div>
										<?php } ?>
									
									<div  id="fields">
										<div class="padding-top"></div>
									</div>
								

							
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="padding-md">
	<div class="panel panel-default table-responsive">
		<div class="panel-heading">
			 Academic Assessment - Skill Type
			<a class="btn btn-primary pull-right" style="margin-top: -9px;" href="<?php echo $this->mainconfig['host'];?>master/skill-type/type/add">Add </a>
		</div>
		<div class="padding-md clearfix">
			<table class="table table-striped" id="dataTable">
				<thead>
					<tr>
						<th>S.No.</th>	 
						<th>Sub Area</th>
						<th>Skill Type</th>
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						
						if (count($this->paginator) != 0) {
							

						foreach ($this->paginator as $results) { 

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						<td><?php echo $results['sub_area']; ?></td>
						<td><?php $skill_type = unserialize($results['skill_type']);
						foreach($skill_type as $val){ echo $val.',';} ?></td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/skill-type/type/edit/id/<?php echo $results['skill_type_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/skill-type/type/delete/id/<?php echo $results['skill_type_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script type="text/javascript">
$('.date').datepicker({
	dateFormat: 'yy-mm-dd',
	prevText: '<i class="fa fa-chevron-left"></i>',
	nextText: '<i class="fa fa-chevron-right"></i>' 
});
var count = $('#skill_count').val();
		$("body").on("click","#AddButton",function(event){
		var value = count++;
			append_html = '<div class="row">';
			append_html += '<div class="col-md-3"></div>';
			append_html += '<div class="col-md-3" style="margin:10px 5px;"><input type="text"  class="form-control" label="skill_'+value+'" name="skill_type[]"  style=" background:#FFFFFF;"/></div>';		
			append_html += '<a href="#" class="removeclass3 btn btn-primary remove_class3 " style="margin:10px 15px; padding:7px 19px;">-</a>';
			append_html += '</div>';													
		$('#fields').append(append_html);
	});
	$("body").on("click",".removeclass3", function(e){
		//alert('sdsd');

                $(this).parent('div').remove(); 				
				
        return false;

    });
</script>