<tr class="sub">
<td colspan="5">

         <div class="col-sm-2" style="float:right;"><button class="close_tr btn btn-primary">Close</button></div>
<br></br>
<?php 

$term_result = $this->term_result;

for($i=0;$i<count($term_result);$i++) {   ?>
 <div class="box-body">
	<h4 style="background-color:#3c8dbc;padding:8px 8px;color:white;"><?php echo $term_result[$i]['term_name'];?></h4>
	<div style="overflow-x:scroll;width:1043px;">
	<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
<thead>
					<tr>
						<th rowspan="2">S. No.</th>
						<th rowspan="2">Name of Participants</th>
						<th rowspan="2">ID Number</th>
						<th>Course</th>
						<?php 
						
						$Corecourselearning_model =  new Application_Model_Corecourselearning();
							$result = $Corecourselearning_model->getcorecourses($term_result[$i]['academic_year_id'],$term_result[$i]['term_id']);
							
							foreach($result as $k => $val) {
							?>
							<th><?php echo 	$val['course_name']; ?></th>
							<?php } ?>
							<?php  $ElectiveCourseLearning_model = new Application_Model_ElectiveCourseLearning();
									$elective_count = $ElectiveCourseLearning_model->getCount($term_result[$i]['academic_year_id'],$term_result[$i]['term_id']); 
									//$term_count = $elective_count['term_count'];
						//for($count=1;$count<=$term_count;$count++){		
               			 $ElectiveCourseLearning_model =  new Application_Model_ElectiveCourseLearning();
						$term_wise_electives = $ElectiveCourseLearning_model->getAllElectiveCourses($term_result[$i]['academic_year_id'],$term_result[$i]['term_id']);
                       	foreach($term_wise_electives as $e => $term_els) { ?>			
						<th>
						<?php echo $term_els['course_name']; ?>
						</th>
						<?php } ?>
							
						<!-- <th>Grade Point Average</th>  -->
					</tr>
					<tr>	
						<th>Credits</th>
						<?php foreach($result as $k => $val) {
							?>
						<th><?php echo $val['credit_value']; ?></th>
						<?php }
						//for($count=1;$count<=$term_count;$count++){	
						foreach($term_wise_electives as $e => $term_els) {  ?>
						<th>
						<?php echo $term_els['credit_value']; ?>
						</th>
						<?php } ?>
					<!-- 	<th></th>  -->
					</tr>
				</thead>
				<tbody>
				<?php $StudentPortal_model = new Application_Model_StudentPortal(); 
				 $category_data=$StudentPortal_model->getstudentsdetails($term_result[$i]['academic_year_id']);
				 $m = 1;
				 $total = 0;
				
				 foreach($category_data as $stu_data) {  $flag = 0;	 ?>
					
							<tr>
								<td><?php echo $m; ?></td>						
								
								<td><?php echo $stu_data['students']; ?></td>
								
							<input type="hidden" name="student[student_id_<?php echo $term_result[$i]['term_id'];?>][]" id="student_id" value="<?php echo $stu_data['student_id']; ?>" />
								<td><?php echo $stu_data['stu_id']; ?></td>
								<td></td>	
								<?php $total_credit_value = 0;
										$tot_grade = 0;
										$academic_courses = '';
										$academic_credits = '';
										$academic_grades = '';
										$total_grade = 0;
									foreach($result as $k => $val) {
									$ElectivesGradeAllocationReport_model = new Application_Model_ElectivesGradeAllocationReport(); 
									$grade_point = $ElectivesGradeAllocationReport_model->getGradePointValue($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$val['course_id'],$stu_data['student_id']);
									$academic_courses = $academic_courses.$val['course_id'].",";
									$academic_credits = $academic_credits.$val['credit_value'].",";
									$academic_grades = $academic_grades.$grade_point['grade_point'].",";
									$Coursewisepenalties_model = new Application_Model_Coursewisepenalties();
									$absence_value = $Coursewisepenalties_model->getAbsenceValues($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$stu_data['student_id']);
									$tot_absence = explode(',',$absence_value['absence']);
									?>
									
					<td><input type="text" name="student[absence_<?php echo $term_result[$i]['term_id'];?>_<?php echo $stu_data['student_id']; ?>][]" value="<?php echo $tot_absence[$k]; ?>"/></td>
							<?php  $total_credit_value  += $val['credit_value']; 
								//$tot_grade += ($total_grade)/($total_credit_value );
								} ?>
							<?php
							$ElectivesGradeAllocationReport_model = new Application_Model_ElectivesGradeAllocationReport();
							/* $electives = $ElectivesGradeAllocationReport_model->getElectives($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$stu_data['student_id']); */
							$Coursewisepenalties_model = new Application_Model_Coursewisepenalties();
									$absence_value = $Coursewisepenalties_model->getAbsenceValues($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$stu_data['student_id']);
									$electives = explode(',',$absence_value['academic_electives_ids']);
									$tot_absence = explode(',',$absence_value['academic_electives']);
							foreach($term_wise_electives as $e => $term_els) { 
							$flag=0;
							$academic_electives_ids = '';
							$aca_absence = '';
							foreach($electives as  $e => $els) {
								if($els == $term_els['course_id'] ){ 
                                 $flag=1;
								 $academic_electives_ids = $academic_electives_ids.$els;
								 $aca_absence = $aca_absence.$tot_absence[$e];
								 //$grade_val=$els['grade_point'];
								 //$tot_elective_grade += $term_els['credit_value']*$grade_val;
 								 ?>
								 <input type="hidden" name="student[academic_electives_ids_<?php echo $term_result[$i]['term_id'];?>_<?php echo $stu_data['student_id']; ?>][]" id="academic_electives_ids" value="<?php echo $academic_electives_ids; ?>" />
                              <?php }

							}	
						
							if($flag==1)
								 {
									  ?>
							<td>
							<input type="text" name="student[academic_electives_<?php echo $term_result[$i]['term_id'];?>_<?php echo $stu_data['student_id']; ?>][]" id="academic_electives" value="<?php echo  $aca_absence; ?>" readonly /></td>
							
							<?php
							
								 }
								 else
								 {
									 ?><td></td>
							<?php	 } 
							
							 }

								/*  $ElectivesGradeAllocationReport_model = new Application_Model_ElectivesGradeAllocationReport();
							$electives = $ElectivesGradeAllocationReport_model->getElectives($term_result[$i]['academic_year_id'],$term_result[$i]['term_id'],$stu_data['student_id']);
						   $count=0;
						   $tot_elective_grade =0;
						   //$tot_elective_and_course_credit = $term_count+$total_credit_value; 
						   $academic_electives = '';
							foreach($electives as $m => $els) { 
							$count++;
							$academic_electives = $academic_electives.$els['elective_id'].',';
							?>
							<td><?php //echo $els['grade_point']; 
							$tot_elective_grade += 1*$els['grade_point']; ?>
							<input type="text" name="student[academic_electives_<?php echo $term_result[$i]['term_id'];?>_<?php echo $stu_data['student_id']; ?>][]" id="academic_electives" /></td>
						<?php			
							}
							/* if($count!=$term_count)
							{
								?>
								<td><input type="text" name="student[academic_electives_<?php echo $term_result[$i]['term_id'];?>_<?php echo $stu_data['student_id']; ?>][]" id="academic_electives" /></td>  
								<?php
							} */
							?>
						<!-- 		<td><?php // $tot_grade_point = ($tot_elective_grade+$total_grade)/($tot_elective_and_course_credit) ;
								// echo $tot_grade_point; ?></td>  -->
<input type="hidden" name="student[academic_courses_<?php echo $term_result[$i]['term_id']; ?>][]" id="academic_courses" value="<?php echo  $academic_courses; ?>" />
<input type="hidden"  name="student[academic_credits_<?php echo $term_result[$i]['term_id'];?>][]"  id="academic_credits" value="<?php echo $academic_credits; ?>" />
<input type="hidden" name="student[academic_grades_<?php echo $term_result[$i]['term_id'];?>][]" id="academic_grades" value="<?php echo $academic_grades; ?>" />

<!-- <input type="hidden" name="student[total_academic_grade_<?php //echo $term_result[$i]['term_id'];?>][]" id="total_academic_grade" value="<?php //echo $tot_grade_point; ?>" />  -->
<!-- <input type="hidden" name="course[academic_electives_<?php //echo $term_result[$i]['term_id'];?>][]" id="academic_electives"
value="<?php //echo $academic_electives;?>" />  -->

							</tr>  
				 <?php $m++; } 
				 ?>	
				</tbody>
	</table>

</div>
</div>

<?php }  ?>
</td>
</tr>
<script>
    $(".close_tr").click(function() {
            $( ".sub" ).hide();
     });
</script>