<style>
    .link:link,
    .link:visited{
        position: relative;
        display: inline-block;
        padding:.2em 2em;
        border-radius:100px;
        /*  background-color:#faa2b1;*/
        -webkit-transition: all .2s;
        transition: all .2s;
    }


    .link::after{
        content: "";
        position:absolute;
        top:0px;
        left:0px;
        background-color:#faa2b1; 
        width:100%;
        height:100%;
        z-index:-1;
        border-radius:100px;
        -webkit-transition: all .2s;
        transition: all .2s;
    }



    .link:hover{
        box-shadow:0px 5px 6px #000;
    }

    .link:hover::after{
        transform:scale(2,3);

    }

    .link:active{
        box-shadow:0px 5px 1px #000;
    }
    input[type='checkbox']{display:none;}
    .checkbox{
        position:relative;
        width:1.3em;
        height:1.3em;
        border:.1em solid #3C87F9;
        color: #00c2c2;
        border-radius: 3px;
    }

    .checkbox>i{
        position:absolute;
        top:50%;
        left:50%;
        transform: translate(-50%, -50%);
    }




</style>
<div class="right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <div class="">
        <div class="">
            <div class="row">
                <?php
                if (isset($_SESSION['message']) && !empty($_SESSION['message'])) {
                    //foreach ($this->messages as $message) {
                    ?>
                    <div class="alert <?= $_SESSION['class']; ?> ">
                        <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                        <?php
                        echo $_SESSION['message'];
                        unset($_SESSION['message']);
                        unset($_SESSION['class']);
                        ?>
                    </div>
    <?php }
?>
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Notification Push</i>

                    </h3>
                </div>

            </div>

            <div class="panel panel-default">


                <div class="panel-body">

                    <div class="row">

                        <div class="col-sm-3 employee_class">
                            <div class="form-group">

                                <?php if ($this->type != 'edit') { ?>
                                    <label class="control-label">Semester <span class="asterisk">*</span></label>
    <?php echo $this->form->cmn_terms; ?>
<?php } ?>
                            </div>
                        </div>
                        <div class="col-sm-3 employee_class">
                            <div class="form-group">

                                <?php if ($this->type != 'edit') { ?>
                                    <label class="control-label"> Status <span class="asterisk">*</span></label>
    <?php echo $this->form->status; ?>
<?php } ?>
                            </div>
                        </div>
                        <!--                            <div class="col-sm-3 employee_class">
                                                        <div class="form-group">
                        
                        <?php if ($this->type != 'edit') { ?>
                                                                    <label class="control-label"> Degree <span class="asterisk">*</span></label>
    <?php echo $this->form->degree_id; ?>
<?php } ?>
                                                        </div>
                                                    </div>
                                                    <div class="col-sm-3 employee_class">
                                                        <div class="form-group">
                        
                        <?php if ($this->type != 'edit') { ?>
                                                                    <label class="control-label">Course Category <span class="asterisk">*</span></label>
    <?php echo $this->form->cc_id; ?>
<?php } ?>
                                                        </div>
                                                    </div>-->

                        <div class="row">
                            <button type="button" id="getRecords" class="btn btn-primary" style="float: right" value="0" >Get Assignments</button>

                        </div>
                    </div>
                    <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >
                        <div id="grade_data">
                        </div>

                </div>
                <div class="x_panel">

                    <div class="x_title">
                        <h2>Notification Push</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            </li>
                            <li><a class=""><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content table-responsive">

                        <div class="padding-md clearfix">
                            <div class='form-control-static'>
                                <span class='text-danger'>NOTE:- only .jpg, .png, .pdf, .docx, .doc, .ppt, .xls file can upload</span>
                            </div>
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th style="text-align:center;">Sl. No.</th>
                                        <th class='text-center'>Course</th>
                                        <th style="text-align:center;">Document Title</th>
                                        <th style="text-align:center;">Files&nbsp;(Download Files)</th>
                                        <th style="text-align:center;">Remarks</th>
                                        <th style="text-align:center">Assigned Date</th>
                                        <th style="text-align:center">Due Date</th>
                                        <th style="text-align:center">Upload documents</th>
                                        <th style="text-align:center;">Description</th>
                                        <th style="text-align:center;">Status</th>

<!--<th style="text-align:center">Actions</th>-->
                                    </tr>
                                </thead>
                                <tbody style="text-align:center;" id='mainData'>
                                    <?php
                                    $i = 1;
                                    $pagination_tr = '';
                                    if (count($this->paginator) != 0) {
                                        foreach ($this->paginator as $results) {
                                            ?>
                                            <tr>

        <?php if ($results['assignment_status'] != 'Completed') { ?>

                                                    <td>
                                                        <input type="checkbox" name='selected_id[]' value='<?= $results['submitted_id']; ?>' id="selected_id<?= $i; ?>" />
                                                        <label for="selected_id<?= $i; ?>" class='checkbox' id="checkbox_id<?= $i; ?>" ><i class=''></i></label>
                                                    </td>
                                                <?php } else { ?>
                                                    <td><i class='glyphicon glyphicon-ok'></i></td>
        <?php } ?>
                                        <script>
                                            $("#checkbox_id<?= $i; ?>").click(function () {
                                                if ($("#selected_id<?= $i; ?>").prop("checked") == false) {
                                                    $("#checkbox_id<?= $i; ?> > i").attr("class", 'glyphicon glyphicon-ok');
                                                } else if ($("#selected_id<?= $i; ?>").prop("checked") == true)
                                                {
                                                    $("#checkbox_id<?= $i; ?> > i").attr("class", '');
                                                }
                                            });

                                        </script>
                                        <td><?php
                                            echo $i;

                                            $i++;
                                            ?>
                                        </td>						
                                        <td><?= !empty($results['course_id']['course_code']) ? $results['course_id']['course_code'] : 'Core Course'; ?></td>

                                        <td><?php echo $results['document_title']; ?></td>

                                        <td><a href='<?= $this->baseUrl($results['filename']); ?>' class='link' download><?php echo $results['filename2']; ?></a></td>
                                        <td><?php echo $results['remarks']; ?></td>
                                        <td><?= $results['updated_date']; ?></td>
                                        <td><?= $results['due_date']; ?></td>

                                        <?php if ($results['assignment_status'] != 'Completed') { ?>
                                            <td><input type='file'  name="uploadFile_<?= $results['submitted_id']; ?>" id='uploadFile2'/></td>
                                        <?php } else { ?>
                                            <td><a href='<?= $this->baseUrl($results['upload_file']); ?>' class='link' download><?= $results['filename1']; ?></a></td>
                                        <?php } ?>
                                        <td><textarea class="form-control" name="description_<?= $results['description']; ?>" id ='description'> <?= $results['description']; ?>
                                            </textarea></td>
        <?php if ($results['assignment_status'] != 'Completed') { ?>
                                            <td>
                                                <select name='assignment_status_<?= $results['submitted_id']; ?>' class="form-control" id='status_id'>
                                                    <option value='0'>Incomplete</option>
                                                    <option value='1'>Completed</option>
                                                </select>
                                            </td>
                                        <?php } else { ?>
                                            <td>Completed</td>
        <?php } ?>
                                        </tr>   


                                        <?php
                                    }
                                } else {
                                    ?>
                                    <tr>
                                        <td colspan="11">No Records</td>
                                    </tr>
<?php }
?>


                                </tbody>
                            </table>
                            <div class='col-md-1 col-xs-12 col-lg-12 text-center'>
                                <input type="submit" name='submit' class='btn btn-primary' value="Submit"  />
                            </div>
<?php echo $pagination_tr; ?>
                        </div><!-- /.padding-md -->
                    </div><!-- /panel -->
                </div>
            </div>
            </form>
        </div><!-- /.padding-md -->		

    </div>


    <script>

        $('body').on('click', '#getRecords', function () {
            $('.load-box').css('display', 'block');
            var term_id = $('#cmn_terms').val();
            var status = $('#status').val();
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-assignment-view'; ?>',
                data: {term_id: term_id, status: status}
            }).done(function (data) {
                $('#mainData').empty('');
                $('#mainData').html(data);
                $('.load-box').css('display', 'none');
            });
        });

    </script>



