<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>404 Error</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
 <style>
       .errorPage{
           position:absolute;
           top:100%;
           left: 50%;
           transform: translate(-50%,-50%);
       }
   </style>

</head>
<body style="background-color: #C2CCD1;">
    <?php  if($this->errorview['display_startup_errors']=='1' && $this->errorview['display_errors']=='1'): ?>
  <h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>
<a href="<?php echo $this->mainconfig['erp']; ?>">Home Page</a>
  <?php 
 
  if (isset($this->exception)): ?>

  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
  <?php endif ;
  endif; ?>

</body>
</html> 

<?php  if($this->errorview['display_startup_errors']==0 && $this->errorview['display_errors']==0): ?> 
<div class="errorPage">        
  <p class="name h1">404</p>
  <p class="description h3">Oop's Page Not Found</p>        
  <p><button class="btn btn-danger" onClick="document.location.href = '<?php echo $this->mainconfig['host'];?>';">Back to main</button> <button class="btn btn-warning" onClick="history.back();">Previous page</button></p>        
</div> 
<?php endif;?>
  
