<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">

    <thead>

        <tr>

            <th>S.  No.</th>

            <th>Batch</th>
            <th>Term</th>

            <th>Course Code</th>

            <th>Action</th>

        </tr>

    </thead>

    <tbody>

        <?php
        $i = 1;

        $pagination_tr = '';

        if (count($this->paginator) != 0) {



            foreach ($this->paginator as $results) {

                //print_r($results);die;
                ?>

                <tr>

                    <td><?php echo $i;



        $i++;
        ?>

                    </td>	

                    <td><?php echo $results['short_code']; ?></td>
                    <td><?php echo $results['term_name']; ?></td>

                    <td><?php echo $results['course_code']; ?></td>



                    <td><a href="<?php echo $this->mainconfig['host']; ?>elective/selection/type/edit/id/<?php echo $results['academic_year_id']; ?>/term/<?php echo $results['term_id']; ?>/course/<?= $results['course_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>



                </tr>            



    <?php
    }

    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
}
?>



    </tbody>

</table>

<?php echo $pagination_tr; ?>
<script>
    setDatatables();
    </script>
    