<style>
.panel-body{padding: 15px 10px 0 10px;}
.form-control{width:95%;}
textarea{resize:none;}
</style>
<script src="<?php echo $this->mainconfig['publicpath'];?>js/jquery-ui.min.js"></script>
	  
<?php //print_r($this->academics_data);die;?>
<?php
error_reporting(0);
$date = new Zend_Date();
?>
<tr class="purchase-quatation-items-close ">
<td colspan="6">
<div class="purchase-quatation-items" style="display: block;"><div class="col-sm-12 " >
      <div id="log1">  
<div class="panel panel-default bor" >
 <div class="panel-body" style="">
     <div>
         <div class="col-sm-12" width="99%"><center>
                 <div class="form-group bor" style="">
                     
                     <label class="control-label"><strong>Elective Details</strong></label>
                 </div></center>
         </div>
		
     </div>
    </div>
     <div class="row" style="margin-bottom:5px;" >
         <div class="col-sm-12">
             <div class="form-group bor" >
                 <table width="99%" class="table table-striped table-bordered mb30 jambo_table bulk_action" border="0" >
				 <thead>
                     <tr align="center">
                         <th rowspan="2">S. No.</th>
						 <th rowspan="2">Participants Name</th> 
						 <?php // print_r($this->Electivecourse);die;
						 foreach($this->Electivecourse as $keys=>$vals){ 
						 $Electivecourse_model = new Application_Model_ElectiveCourseLearning();
						 $course_count = $Electivecourse_model->getTermCount($this->academic_year_id,$vals['term_id']);
						// print_r($course_count[0]['term_id']);die;
						 $count_id = count($course_count);
						// print_r($count_id);die;
						?>
						 <th colspan="<?php echo $count_id;?>" style="text-align:center;"><?php echo $vals['term_name'];?>
						 <input type="hidden" name="Elective[term_ids][]" id="term_ids" value="<?php echo $vals['term_id'];?>"/></th> 
                        <?php } 
						 ?>
					</tr>
					<tr>
						<?php //$k=1;
						//if($flag <= $this->Electivecourse_count[0]['counts']){
						//echo $this->Electivecourse_count[0]['counts'];
						$Electivecourse_model = new Application_Model_ElectiveCourseLearning();
						
						 foreach($this->Electivecourse as $k1=>$val){
						 $term_id = $val['term_id'];
						// print_r($term_id);die;
						 $course_count = $Electivecourse_model->getTermCount($this->academic_year_id,$term_id);
						// print_r($course_count[0]['term_id']);die;
						 $count_id = count($course_count);
						// echo $course_count[$k1]['counts'];
						 for($j=1;$j<=$count_id;$j++) {
						 //foreach($course_count as $value){
						 //for($m=1;$m<=$this->Electivecourse_count[0]['counts'];$m++) {
                      	?>
						<th style="text-align:center;">Elective <?php echo $j;?>
						 <input type="hidden" name="Elective[elective_name][]" id="elective_name" value="<?php echo $j;?>"/></th>
						 <?php  }
						 } ?>  
                     </tr>
						</thead>
                     <tbody>
                         <?php
                        // print_r($this->academics_data);
                     $t=1; 
					 if(!empty($this->ElectiveItems_data)){	
					//  echo '<pre>'; print_r($this->ElectiveItems_data); die;	 
                     // foreach ($this->ElectiveItems_data as $keys=>$electiveitems_result){ 
					  //echo '<pre>'; print_r($electiveitems_result['electives']); die;
                     $st = $this->student_data;
						// print_r($st);die;
							foreach($st as $k1=>$student){
							//print_r($this->ElectiveItems_data[$k1]['students_id']);die;
							//if($this->ElectiveItems_data[$k1]['students_id'] == $student['student_id']){ ?>					 
				       	<tr>
					
						   <td align="center"><?php echo $t++;?></td>
						   
						   <td align="left" id="students_id" name="students_id"><?php
						   
						          echo $student['students'];
							?>
						   <input type="hidden" name="Elective[students_id][]" id="students_id" value="<?php echo $student['student_id'];?>" />
						   <?php //}
						  // } ?></td> 
 
					 <?php 
						 $Electivecourse_model = new Application_Model_ElectiveCourseLearning();
						
						 foreach($this->Electivecourse as $k1=>$val){
						 $term_id = $val['term_id'];
						//print_r($term_id);die;
						 $course_count = $Electivecourse_model->getTermCount($this->academic_year_id,$term_id);
						 $count_id = count($course_count);
						 //print_r($course_count[$k1]['counts']);die;
						  $i=0;
						  for($j=1;$j<=$count_id;$j++) {
						  //echo $counts;
						 //print_r(count($this->ElectiveItems_data));die;?>
						   <td>
						   <select name="electives_<?php echo $student['student_id'];?>_<?php echo $term_id;?>_<?php echo $i;?>" class="form-control">
						  <?php  foreach($this->course_data as $k=>$val){
						    $selected ='';
							for($item_val=0;$item_val<count($this->ElectiveItems_data);$item_val++)
							{
							   if(($this->ElectiveItems_data[$item_val]['students_id']==$student['student_id']) && ($this->ElectiveItems_data[$item_val]['terms']==$term_id) && ($this->ElectiveItems_data[$item_val]['elective_name']==$j) && ($this->ElectiveItems_data[$item_val]['electives']==$k))
							    {
								   $selected="selected";
								} 
								
							}?>
							 
							<option value="<?php echo $k;?>"<?php echo $selected;?>><?php echo $val;?></option>
						<?php   } ?>
						          
							   
						  <?php $i++; } ?> 
						   </select>
						   </td> 
						  <?php 
						    }  
						  //} ?> 
						</tr>
						
                         <?php } }
                          //}
					 else{	
						$k2=1;								
					 if(($this->student_data) >0){
							$electives = $this->course_data;
						//echo '<pre>'; print_r($electives); die;	 
                       foreach ($this->student_data as $student_names){ 
                     ?>
								
				     <tr>
						   <td align="center"><?php echo $k2;?></td>
						   <td align="left" id="students_id" name="students_id"><?php echo $student_names['students'];?>
						   <input type="hidden" name="Elective[students_id][]" id="students_id" value="<?php echo $student_names['student_id'];?>" /></td> 
						 
						<?php 
						    $Electivecourse_model = new Application_Model_ElectiveCourseLearning();
						
						 foreach($this->Electivecourse as $k1=>$val){
						 $term_id = $val['term_id'];
						//print_r($term_id);die;
						 $course_count = $Electivecourse_model->getTermCount($this->academic_year_id,$term_id);
						 $count_id = count($course_count);
						 //print_r($course_count[$k1]['counts']);die;
						  $i=0;
						  for($j=1;$j<=$count_id;$j++) {
						  //echo $counts;
						 // print_r($electives);die;?>
						   <td>
						   <select name="electives_<?php echo $student_names['student_id'];?>_<?php echo $term_id;?>_<?php echo $i;?>" class="form-control">
						  <?php  foreach($this->course_data as $k=>$val){?>
						   <option value="<?php echo $k;?>"><?php echo $val;?></option>
						  <?php } ?> 
						   </select>
						   </td> 
						  <?php $i++;
						    }  
						  } ?> 
						</tr>
						<?php $k2++; } ?>
		
						<?php }  else { ?>
						 <tr><td><center><strong>No Data Available</strong></center></td></tr>  
								 <?php } } ?>	
					 </tbody>
                 </table>
             </div>
         </div>
     </div>

    
     </div>
 </div>
</div>

       </div>
 </div>
</td>
</tr>

<style type="text/css">
/*  .bor {border:1px solid #ccc; } */
    .table { margin-bottom: 0px !important;width: 100%;}
    .employee_class {margin-left: 4% !important;margin-right: 4% !important;}
    .panel-footer {padding: 5px;}
    .panel {margin-bottom: 10px !important;}
	a:hover{cursor:pointer;}
</style>

<script>
    $(".close_tr").click(function() {
            $( ".purchase-order-items-close" ).hide();
     });
  
 /* $('#form_date').datepicker({
	dateFormat: 'dd-mm-yy',
	prevText: '<i class="fa fa-chevron-left"></i>',
	nextText: '<i class="fa fa-chevron-right"><i>' 
}); */

  //$('body').on('change','#label_date', function() { 
  

 // })
</script>
<script type="text/javascript">
$(document).ready(function() {

var count = $('#count_val1').val();
     $("body").on("click","#AddButton", function(e){   
	 
      $( "#appended_row3" ).clone().find("input:text").val("").end().appendTo( "#fields" );
			var count_val = count++;
			
			//alert(count_val);
			$('#count_val').val(count_val);
		//	$('#label_uom').attr('label', 'uom_'+count_val);
		//	$('#label_uom').attr('data-options', count_val);
			$('#label_code').attr('label', 'itemcode_'+count_val);
			$('#label_code').attr('data-options', count_val);			
			$('#label_product').attr('onchange', 'select_rawm('+count_val+')');
			$('#label_product').attr('label', 'productid'+count_val);
			$('#label_tprice').attr('label', 'tprice_'+count_val);
			$('#product_qty1').attr('label', 'actqty_'+count_val);
		   //$('#item_qty11').attr('label', 'tprice_'+count_val);
			$('#product_qty1').attr('onchange', 'select_qty('+count_val+')');
			//$('#product_qty1').attr('onkeyup', 'select_qty('+count_val+')');				
			$('#label_uprices').attr('label', 'vehicle_'+count_val);		
			$('#label_uprices').attr('onkeyup', 'validations('+count_val+')');		
			$('#label_date').attr('label', 'vehicledate_'+count_val);
			$('#label_date').attr('onchange', 'mydate1('+count_val+')');
$('#bill').attr('label', 'bill_'+count_val);	
$('#brate').attr('label', 'baserate_'+count_val);	
$('#t_value').attr('label', 'total_value_'+count_val);
$('#transporter').attr('label', 'transporter_'+count_val);
$('#freight').attr('label', 'freight_'+count_val);	
$('#remark').attr('label', 'remarks_'+count_val);
		//	$('#label_uprice').attr('onchange', 'select_quantity('+count_val+')');
			//$('#label_uprice').attr('onkeyup', 'select_quantity('+count_val+')');
	     	//$('#item_qty12').attr('onchange', 'select_reject_qty(this.value,'+count_val+')');			
			// Validate 
			$('#label_tprice').attr('required', 'required');
		//	$('#label_uom').attr('required', 'required');
			$('#label_product').attr('required', 'required');
        
   /* $("#basicForm input[label='vehicledate_"+count_val+"']").datepicker({
	dateFormat: 'dd-mm-yy',
	prevText: '<i class="fa fa-chevron-left"></i>',
	nextText: '<i class="fa fa-chevron-right"><i>' 
});   */
//alert(count_val);
 
  return false;
	 });

    $("body").on("click",".removeclass", function(e){
                   $(this).parent('div').remove(); 
	});
});


/* function mydate1(num) { //alert(num);
 var d = $("#basicForm input[label='vehicledate_"+num+"']").val();
 //alert(d);
  //dt = d.getDate();
 // alert(dt);
 //var mn = d.getMonth();
 //alert(mn);
 // mn++; 
 //var yy = d.getFullYear();
 // alert(yy);
 // var format = dt + "/" + mn + "/" + yy;
  $("#basicForm input[label='vehicledate_"+num+"']").val(format);
} */
function  validations(vals){	
	var value = $("#basicForm input[label='vehicle_"+vals+"']").val();	
	//alert(value); 
		len=value.length;
		 n=value.charCodeAt(len-1);
		 if(n<47||n>123||len>10)
		 {
		  p=value.substr(0,len-1);
		 $("#basicForm input[label='vehicle_"+vals+"']").val(p);	
		 }		 
}



function  select_rawm(vals){	
	var id = $("#basicForm select[label='productid"+vals+"']").val();	
	//alert(id);
	var transaction = $('#transact_qty').val();
	$.ajax({
		type: "POST",
		url:"<?php echo $this->mainconfig['host'].'vehicle-allocation/ajax-product-Details';?>",
		data: { id: id,transaction_id:transaction }
	}).done(function( data ) {
	  var results = $.parseJSON(data)
	//	$("#basicForm input[label='uom_"+vals+"']").val(results['uom']);
		$("#basicForm input[label='baserate_"+vals+"']").val(results['unit_price'])
	 });		
}

function  select_qty(vals){
//alert('dsgsfg');	
	var id = $("#basicForm select[label='productid"+vals+"']").val();
	//alert(id);
	var quantity = $("#basicForm input[label='actqty_"+vals+"']").val();
	var qty_sent = $("#qty_"+id).val();
	// alert(qty_sent);
	 var total_limitqty=0;	
	 var sent_qtyval=0;
	var transaction = $('#transact_qty').val();
	$.ajax({
		type: "POST",
		url:"<?php echo $this->mainconfig['host'].'vehicle-allocation/ajax-product-quantity';?>",
		data: { id: id ,transaction_id:transaction}
	}).done(function( data ) {
		var results = $.parseJSON(data);
		var qty = results['quantity'];
		var products = results['product_id'];
		//alert(products);
		var brate = results['unit_price'];
		//alert(brate);
	//	$("#basicForm input[label='uom_"+vals+"']").val(results['uom']);
		//var load=parseFloat(results['loading_amount']);
		//alert(load);
		//var excise=parseFloat(results['excise_amount']);
		//alert(excise);
		//var cst=parseFloat(results['cst_amount']);
		//alert(cst);
		var load=parseFloat(results['loading']);
		// alert(load);
		var load_amount=0;
		//alert(load);
		var excise=parseFloat(results['excise_amount']);
		//alert(excise);
		var cst=parseFloat(results['cst_amount']);
		//alert(cst);
		var total_quantity=0;
		var total_price=0;
		var total_val=0;
		if(id == products){
		
	     $("#basicForm input[label='actqty_"+vals+"']").removeAttr("class");
		 $("#basicForm input[label='actqty_"+vals+"']").attr("class");
	     $("#basicForm input[label='actqty_"+vals+"']").addClass( "quantity_"+id );
		 $("#basicForm input[label='actqty_"+vals+"']").addClass( "form-control" );
		
         var value=0;	
         
        	 
		$('.quantity_'+id).each(function() {
		value = parseFloat($(this).val());
		
       	if (!isNaN(value))
		
		total_quantity += value;
		
		
		//total_price = value*brate;
	//	load_amount=value*load;
	//	total_val =  total_price+excise+cst+load_amount;
	//	alert(total_val);
	//	$("#basicForm input[label='total_value_"+vals+"']").val(total_val);
	   sent_qtyval = 5;
	   total_limitqty = parseInt(qty_sent)+parseInt(sent_qtyval);
		// alert(total_limitqty);
		if(total_quantity <= total_limitqty)
		{
		 // alert(qty_sent);
		  total_price = total_quantity*brate;
		 // alert(total_price);
		  load_amount=total_quantity*load;
		 // alert(load_amount);
		  total_val = parseFloat(total_price)+parseFloat(excise)+parseFloat(cst)+parseFloat(load_amount);
		//alert(total_val);
		$("#basicForm input[label='total_value_"+vals+"']").val(total_val);
		}
		else{
		//alert(total_limitqty);
		 alert('Quantity should be less than Product Total Quantity');
		 $("#basicForm input[label='actqty_"+vals+"']").val(0);
	    }
		});
		 }
		//$("#basicForm select[label='itemdata_"+vals+"']").html( data );
	 }); 	
}
</script>

