

                           

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action " id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;" rowspan="2">S. No.</th>
                                        <th style="text-align:center;" rowspan="2">Applicant Name</th>
                                       
                                        <th style="text-align:center;" rowspan="2">Roll No</th>
                                       
                                        <th style="text-align:center;" rowspan="2">Form Id</th>

                                        <th style="text-align:center" rowspan="2">Course</th>

                                        <th style="text-align:center" colspan="3">Subject Preference</th>
                                        <th style="text-align:center"rowspan="2">Status</th>
                                        <!--<th style="text-align:center"rowspan="2">Edit Form</th>--->
                                        <th style="text-align:center"rowspan="2">Action</th>
                                       
                                    </tr>
                                    <tr>
                                        <th>Core Course</th>
                                        <th>Generic</th>
                                        <th>Aecc</th>
                                    </tr>
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                         
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {

                                           //print_r($results['principal_status']);

                                            ?>

                                            <tr>

                                                <td><?php

                                                    echo $i;
                                                        $i++;

                                                    ?>

                                                </td>
                                                <td><?php echo strtoupper($results['applicant_name']);?></td>
                                                    <?php  $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                                <td><?=$results['roll_no1']; ?></td>

                                                <td id="form_id"><?php echo $results['form_id'];?></td>

                                                 <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                 <td><?php if($edu_details['core_course1']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course1'])['dpt_name'];}else{echo '--';}?></td>
                                                       
                                                <td><?php if($edu_details['ge1']){echo $geinfo->getRecord($edu_details['ge1'])['general_elective_name'];}else echo '--'; ?></td>
                                                 <td><?= !empty($edu_details['aecc1'])?$edu_details['aecc1']:'--'?></td>
                                               
                                             
                                                <td id='p_status-<?= $results['form_id']; ?>'>
                                                  <?php
                                                    if($results['principal_status'] == 1) {
                                                        echo 'Approved';
                                                    }else if($results['principal_status'] == 0){
                                                        echo 'Rejected';
                                                    }else{
                                                        echo 'Pending';
                                                    }
?>
                                              </td>
                                             <!--- <td><a href="<?php echo $this->mainconfig['host']; ?>multi-step-form/index/type/step4/a_id/<?php echo md5($results['application_no']); ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>--->

                                              <td class="principal_table">
                                                   <input type="hidden" value="<?= $results['form_id']; ?>" id="form_id">
                                                   <button type="button" id="approveBtn" class="btn btn-primary approveBtn" value="1" >Approve</button>
                                                   <button type="button" id="rejectBtn" class="btn btn-info rejectBtn" value="0" >Reject</button>
                                                 
                                              </td>
                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>
<script>
//Approve or reject a student by principal
$(".approveBtn").click(function() {
    let form_id = $(this).closest("td").find("#form_id").val();
    let buttonValue=$(this).closest("td").find('#approveBtn').val();
    
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-update-principal-status'; ?>',
        data: {form_id:form_id,buttonValue:buttonValue}
    }).done(function (data) {
         $("#p_status-"+form_id).text('Approved'); 
        alert("The Application Form this "+form_id+' is approved');
    });     
});
$(".rejectBtn").click(function() {

    let form_id = $(this).closest("td").find("#form_id").val();
    let buttonValue=$(this).closest("td").find('#rejectBtn').val();
    
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-update-principal-status'; ?>',
        data: {form_id:form_id,buttonValue:buttonValue}
    }).done(function (data) {
        $("#p_status-"+form_id).text('Rejected'); 
        alert("The Application Form this "+form_id+' is rejected');

    });   
});
//End

</script>