<table class="table table-striped table-bordered mb30 jambo_table bulk_action " id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;" >S. No.</th>
                                        <th style="text-align:center;" >Applicant Name</th>
                                       
                                        <th style="text-align:center;"> Father Name</th>
                                        <th style="text-align:center;"> Date Of Birth </th>
                                       
                                        <th style="text-align:center;">Form Id</th>

                                        <th style="text-align:center" >Course</th>

                                        <th style="text-align:center" >Core Course</th>
                                        <th style="text-align:center" >Account Type</th>
                                        <th style="text-align:center">Payment Action</th>
                                       
                                    </tr>
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                         
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {

                                          // print_r($results['fee_slip']);

                                            ?>

                                            <tr>

                                                <td><?php

                                                    echo $i;
                                                        $i++;

                                                    ?>

                                                </td>
                                                <td><?php echo strtoupper($results['applicant_name']);?></td>
                                                    <?php  $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                                <td><?=strtoupper($results['father_name']); ?></td>
                                                <td><?= $results['dob']; ?></td>

                                                <td id="form_id"><?php echo $results['form_id'];?></td>

                                                 <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                 <td><?php if($edu_details['core_course1']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course1'])['dpt_name'];}else{echo '--';}?></td>
                                                       
                                                
                                            

                                                 <td id="account_type">                  <?php    $accname = new Application_Model_FeeCategory();
	   $data =  $accname->getAccDropDownList();
	   ?>
	   <select class="form-control  fund_type<?=$i;?>"  name ="fund_type"  >
	       <?php foreach($data as $key => $val){ ?>
	       <option value = "<?=$val;?>" ><?=$val;?></option>
	       <?php } ?>
	       </select></td>
                                              <td class="principal_table">
                                                   
                             
                                                  <a class="btn btn-primary view" data-id= "<?= $results['form_id']; ?>" target="_blank" onclick="window.open('<?php echo $this->mainconfig['host'] . 'entrance-report/generate-slip'; ?>/form_id/<?= $results['form_id']; ?>/term_id/t1/prod_id/'+$('.fund_type<?=$i;?>').val(), '_blank', 'toolbar=yes,scrollbars=yes,resizable=yes');" href="#" id="generateSlip">generate slip </a>
                                                   <input type="hidden" value="<?= $results['form_id']; ?>" id="form_id">
                                                   <input type="checkbox" style="height: 25px; width: 25px; position: absolute; margin-left:1em;" name="check[]"  <?php if( $results['fee_slip']== 1){
                             echo "checked";} ?> id='check-<?= $results['form_id']; ?>' >  
                                                 
                                              </td>
                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>
<script>
    setDatatables();
    $('select[name="fund_type"]').change(function(){

    var form_id = $(this).parent().next().find('a').data('id');
    var  fund_type = $(this).val();
    $(this).parent().next().find('a').attr('onclick',"window.open('<?php echo $this->mainconfig['host'] . 'entrance-report/generate-slip'; ?>/form_id/"+form_id+"/term_id/t1/prod_id/"+fund_type+"',' _blank', 'toolbar=yes,scrollbars=yes,resizable=yes');");
    
});

$(".principal_table #generateSlip").click(function() {
    let form_id = $(this).closest('td').find("#form_id").val();
    let fund_type =  $(this).parent().prev().find('select').val();
    
         
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-upsert-fee-slip'; ?>',
        data: {form_id:form_id,fund_type:fund_type}
    }).done(function (data) {
        if(data){
            
            
        }
    });     
});

$(".principal_table input:checkbox").change(function() {
    let form_id = $(this).closest('td').find("#form_id").val();
    var ischecked= $(this).is(':checked');
    if(!ischecked){
        var buttonValue=0;
    }else{
       buttonValue=1;
    }
         
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-update-for-fee-slip'; ?>',
        data: {form_id:form_id,buttonValue:buttonValue}
    }).done(function (data) {
        
        
        
    }); 
});
    </script>