<style>
.modal-dialog {
    width: 690px;
    margin: 30px auto;
}
</style>
<div class="right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <?php if($this->type == "getStudents") { ?>

        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Entrance Exam [On-Board Students] </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">



                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Students  Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                           

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>
                                       <?php //echo '<pre>'; print_r($this->degree_id);die; ?>
                                        <th style="text-align:center;" rowspan="2">S. No.</th>
                                        <th style="text-align:center;" rowspan="2">Applicant Name</th>
                                        <th style="text-align:center;" rowspan="2">Form Id</th>
                                        <th style="text-align:center;" rowspan="2"> Roll No.</th>
                                        <th style="text-align:center;" rowspan="2">Father Name</th>
                                        <th style="text-align:center;" rowspan="2">Aadhar Number</th>
                                        <th style="text-align:center;" rowspan="2">Blood Group</th>
                                        <th style="text-align:center;" rowspan="2">Relegion</th>
                                        <th style="text-align:center;" rowspan="2">Nationality</th>
                                        <th style="text-align:center;" rowspan="2">	Email Id  </th>
                                        <th style="text-align:center;" rowspan="2">	Father Contact No  </th>
                                        <th style="text-align:center;" rowspan="2">	Mother's Name </th>
                                        <th style="text-align:center;" rowspan="2">	Guardian Name </th>
                                        <th style="text-align:center;" rowspan="2">	Category </th>
                                        <th style="text-align:center;" rowspan="2">	caste </th>
                                        <th style="text-align:center;" rowspan="2">	Caste Certificate Number </th>
                                        <th style="text-align:center;" rowspan="2">	State </th>
                                        <th style="text-align:center;" rowspan="2">	Home Town </th>
                                        <th style="text-align:center;" rowspan="2">	Appearing Status </th>
                                       
                                        

                                        <th style="text-align:center" rowspan="2">Course</th>

                                        <th style="text-align:center" colspan="3">First Preference</th>
                                        <th style="text-align:center"rowspan="2">Permanent Address</th>
                                        <th style="text-align:center"rowspan="2">Local Address</th>
                                        <?php if($this->degree_id == 1){?>
                                        <th style="text-align:center" colspan="9">Intermediate Educational Details</th>
                                        <th style="text-align:center" colspan="4">Last Educational Details</th>
                                        <?php }else{ ?>
                                        <th style="text-align:center" colspan="5">Matric Educational Details</th>
                                        <th style="text-align:center" colspan="5">Intermediate Educational Details</th>
                                        <th style="text-align:center" colspan="5">Graduation Educational Details</th>
                                        <th style="text-align:center" colspan="5">Other Educational Details</th>
                                        
                                        <th style="text-align:center" colspan="5">BCA/B.Sc(CS) Educational Details</th>
                                       <th style="text-align:center" colspan="5">Graduation with Maths Educational Details</th>
                                       <th style="text-align:center" colspan="4">Last Educational Details</th>
                                        <?php }?>
                                        <!--<th class="no_print" style="text-align:center">Edit | Delete</th>-->



                                    </tr>
                                    <tr>
                                        <th>Core Course</th>
                                        <th>Generic</th>
                                        <th>Aecc</th>
                                        <?php if($this->degree_id == 1){?>
                                        
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Roll No</th>
                                        <th>Obt. Marks</th>
                                        <th>Total Marks</th>
                                        <th> Percent</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>Name Of Institution</th>
                                        <th>Place</th>
                                        <th>Board</th>
                                        <th>Pass Year</th>
                                        <?php }else{ ?>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>Name Of Institution</th>
                                        <th>Place</th>
                                        <th>Board</th>
                                        <th>Pass Year</th>
                                        <?php }?>
                                    </tr>
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                         
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {

                                     //echo '<pre>'; print_r($this->paginator);die;

                                        foreach ($this->paginator as $results) {

                                          //echo '<pre>'; print_r($results);die;

                                            ?>

                                            <tr>

                                                <td>
                                                    <?php
                                                        echo $i;
                                                        $i++;
                                                    ?>
                                                </td>
                                                <td><?php echo $results['applicant_name'];?></td>
                                                    <?php  $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                                <td><?php echo $results['form_id'];?></td>
                                                <td><?php echo $results['class_roll'];?></td>
                                                <td><?=$results['father_name']; ?></td>
                                                <td><?=$results['aadhar']; ?></td>
                                                <td><?=$results['blood_group']; ?></td>
                                                <td><?=$results['religion']; ?></td>
                                                <td><?=$results['nationality']; ?></td>
                                                <td><?=$results['email_id']; ?></td>
                                                <td><?=$results['father_contact']; ?></td>
                                                <td><?=$results['mother_name']; ?></td>
                                                <td><?=$results['guard_name']; ?></td>
                                                <td><?=$results['caste_category']; ?></td>
                                                <td><?=$results['caste']; ?></td>
                                                <td><?=$results['certificate_no']; ?></td>
                                                <td><?=$results['p_state']; ?></td>
                                                <td><?=$results['p_homeTown']; ?></td>
                                                <td>
                                                <?php if($results['appearingStatus'] == 1){
                                                    echo 'Yes';
                                                }else{
                                                    echo 'No';
                                                }
                                                ?>
                                                </td>

                                                 <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                 <td><?php if($edu_details['core_course1']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course1'])['dpt_name'];}else{echo '--';}?></td>
                                                       
                                                <td><?php if($edu_details['ge1']){echo $geinfo->getRecord($edu_details['ge1'])['general_elective_name'];}else echo '--'; ?></td>
                                                 <td><?= !empty($edu_details['aecc1'])?$edu_details['aecc1']:'--'?></td>
                                                
                                             
                                              <td>
                                                  <b>Village:</b> <?= $results['p_address'] ?>,<b>Post-Office:</b><?= $results['p_postOffice'] ?>,<b>Police St.</b>:<?= $results['p_policeSt'] ?>,<b>District:</b><?= $results['p_district'] ?>,<b>State</b>:<?= $results['p_state'] ?>,<b>Pin Code:</b><?= $results['p_code'] ?>
                                              </td>

                                              <td >
                                                   <b>Village:</b> <?= $results['l_address'] ?>,<b>Post-Office:</b><?= $results['l_postOffice'] ?>,<b>Police St.</b>:<?= $results['l_policeSt'] ?>,<b>District:</b><?= $results['l_district'] ?>,<b>State</b>:<?= $results['l_state'] ?>,<b>Pin Code:</b><?= $results['l_code'] ?>
                                              </td>
                                              
                                              
                                              <?php if($this->degree_id == 1){?>
                                              <td>
                                                <?=  !empty($results['school'])?$results['school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_board'])?$results['i_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_roll'])?$results['i_roll']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['obt_marks'])?$results['obt_marks']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['total_marks'])?$results['total_marks']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['percent'])?$results['percent']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_division'])?$results['i_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['subject'])?$results['subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_pass_year'])?$results['i_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['l_institution'])?$results['l_institution']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['l_place'])?$results['l_place']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['last_board'])?$results['last_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['l_p_year'])?$results['l_p_year']:'N/A' ?>
                                              </td>
                                              
                                              <?php }else { ?>
                                              <td>
                                                <?=  !empty($results['mat_school'])?$results['mat_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['mat_board'])?$results['mat_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['mat_division'])?$results['mat_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['mat_subject'])?$results['mat_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['mat_pass_year'])?$results['mat_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['school'])?$results['school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_board'])?$results['i_board']:'N/A' ?>
                                              </td>   
                                              
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_division'])?$results['i_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['subject'])?$results['subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_pass_year'])?$results['i_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['grad_school'])?$results['grad_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_board'])?$results['grad_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_division'])?$results['grad_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_subject'])?$results['grad_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_pass_year'])?$results['grad_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['other_school'])?$results['other_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['other_board'])?$results['other_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['other_division'])?$results['other_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['other_subject'])?$results['other_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['other_pass_year'])?$results['other_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['bca_school'])?$results['bca_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['bca_board'])?$results['bca_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['bca_division'])?$results['bca_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['bca_subject'])?$results['bca_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['bca_pass_year'])?$results['bca_pass_year']:'N/A' ?>
                                              </td>
                                              <td>
                                                <?=  !empty($results['grad_math_school'])?$results['grad_math_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_math_board'])?$results['grad_math_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_math_division'])?$results['grad_math_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_math_subject'])?$results['grad_math_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_math_pass_year'])?$results['grad_math_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['l_institution'])?$results['l_institution']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['l_place'])?$results['l_place']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['last_board'])?$results['last_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['l_p_year'])?$results['l_p_year']:'N/A' ?>
                                              </td>
                                              <?php } ?>
                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
        
 
</div>
   
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Entrance Exam [On-Board Students]</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
                 <div class="col-sm-3 employee_class">
                    <div class="form-group disabled" >
                        <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                        <?php echo $this->form->academic_year_list; ?>
                    </div>
                </div>
                <div class="x_title">
                    
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="ajaxData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <caption><b> <u> Under Graduate Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th>Course Name</th>
                                    <th>Sanctioned Seats</th>
                                    <th>Admission Taken</th>  
                                    <th>On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                           
                                            
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/applicant-details/type/getStudents/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-info">View Applicants</button></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         
                <div class="x_panel">
                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                                 <caption> <b> <u>Post Graduate Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th>Course Name</th>
                                    <th>Sanctioned Seats</th>  
                                    <th>Admission Taken</th>  
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                            </td>
                                           
                                           
                                            <td style="text-align:center">
                                               
                                               
                                          <a class="btn btn-info"  href="<?php echo $this->mainconfig['host']; ?>entrance-report/applicant-details/type/getStudents/dept_id/<?php echo $results['course']; ?>" target="_blank">View Applicants </a>  
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->
<?php } ?>
</div>
<script>
//Added By Kedar : 08 Oct 2020
$('body').on('change', '#academic_year_list', function() {
    let year_id= $('#academic_year_list').val();
    
    if(year_id){
        $('.load-box').css('display','block');
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'entrance-report/ajax-get-applicants-detail-by-year-id';?>',
                data: {year_id:year_id}
            }).done(function( data ) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
        });
    }
});
//End : 08 Oct 2020
</script>