<style>
.modal-dialog {
    width: 690px;
    margin: 30px auto;
}
</style>
<div class="right_col">
   

    <?php if ($this->type == 'edit') { ?>
    <div class="">
        <div class="load-box">
                    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
                </div>
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Entrance Exam Report[Batch-2020]</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">

                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>entrance-report">Back </a>
                </div>
                <?php
                //  }
                ?>
            </div>                      
       
            <div class="clearfix"></div>
        </div>
       
            <div class="x_panel">
               
                <div class="x_title">
                    <b> <u><?= $this->department['department_type']; ?></u> Core Course Report</b>
                   
                   
                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="">Print </a>
                   
                   
                    <div class="clearfix"></div>
                </div>

            <div class="x_content">
                 <?php //echo '<pre>'; print_r($this->department); ?>
                <div class="padding-md clearfix">
                    <div class="table-responsive" id="studentData">
                         <table class="table right-column table-striped table-bordered mb30 jambo_table bulk_action testTable" id="" style="height:100%">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>Core Course Name</th>
                                <th>Sanctioned Seats</th>
                                <th>Admission Taken(Core)</th>  
                                <th>Admission Taken(AECC-English)</th>  
                                <th>Admission Taken(AECC-Hindi)</th>  
                               
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $i = 1;
                            $pagination_tr = '';
                            if (count($this->paginator) != 0) {
                                foreach ($this->paginator as $key=> $results) {
                                    //echo '<pre>'; print_r($results);
                                    //$result[$key]['Totalapplied']=$results['applied'];
                                   
                                    $allDepartmentIds[$key]=$results['id'];
                                    $allAcademicIds[$key]=$results['academic_year_id'];
                                       
                                    ?>
                                    <tr>
                                        <td><?php echo $i;
                                    $i++;
                                    ?>
                                        </td>

                                        <td><?php echo $results['department']; ?></td>
                                        <td>
                                            <?= !empty($results['max_seat'])?$results['max_seat']:'--' ?>
                                           
                                       
                                        </td>
                                        <td id="applied">
                                            <?php echo $results['applied'];?>
                                        <ul style="list-style: none;">
                                                <b><li>General:<?= !empty($results['caste']['General'])?$results['caste']['General']:'No Admission' ?></li></b>
                                                <b><li>BC-1(EBC):<?= !empty($results['caste']['BC-1(EBC)'])?$results['caste']['BC-1(EBC)']:'No Admission' ?></li></b>
                                                <b><li>BC-2(OBC):<?= !empty($results['caste']['BC-2(OBC)'])?$results['caste']['BC-2(OBC)']:'No Admission' ?></li></b>
                                                <b><li>EWS:<?= !empty($results['caste']['EWS'])?$results['caste']['EWS']:'No Admission' ?></li></b>
                                                <b> <li>SC:<?= !empty($results['caste']['SC'])?$results['caste']['SC']:'No Admission' ?></li></b>
                                                <b> <li>ST:<?= !empty($results['caste']['ST'])?$results['caste']['ST']:'No Admission' ?></li></b>
                                              </ul>
                                        </td>
                                        <td id="english"><?php echo $results['English'];?></td>
                                        <td id="hindi"><?php echo $results['Hindi'];?></td>
                                   
                                       
                                    </tr>            
                                   
                                <?php
                                }
                                  $deptIds= implode(",",$allDepartmentIds);
                                  $academicIds= implode(",",$allAcademicIds);
                                    // echo '<pre>';print_r($academicIds);
                               
                                ?>
                        <tfoot>
                            <tr>
                                <td class=" text-left" colspan = 3 style="letter-spacing:.1em; font-size: 1.5em">Total Count</td>
                        <td id="totalSum"   style="letter-spacing:.1em;font-size: 1.5em">
                            <input type="hidden" value="<?= $academicIds.'+'.$deptIds  ?>" id="ac_id"/>
                            <!--<a class="btn btn-primary pull-right" style="">Get GE </a>-->
                        </td>
                        <td id="totalSumEnglish"   style="letter-spacing:.1em;font-size: 1.5em"></td>
                        <td id="totalSumHindi"   style="letter-spacing:.1em;font-size: 1.5em"></td>
                            </tr>
                        </tfoot>            
                       
                               <?php
                                $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                            }
                            ?>

                        </tbody>
                       
                    </table>
                       
                        <?php echo $pagination_tr; ?>
                     </div>
                   
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
                <div class="getablea">
                           
                        </div>
            </div>
         
        </div>
    
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Entrance Exam Report[Batch- 2020]</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
               
                <div class="x_title">
                    <b> <u> Under Graduate Department Wise Report</u></b>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>
                                    <th>Admission Taken</th>  
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                           
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/index/type/edit/id/<?php echo $results['course']; ?>/s_id/<?php echo $results['session_id'] ?>"class="edit" title="Edit" target="_blank" ><span class="fa fa-edit fa-lg"></span></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
                <div class="x_panel">
               
                <div class="x_title">
                    <b> <u>Post Graduate Department Wise Report</u></b>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>  
                                    <th>Admission Taken</th>  
                                    <!---<th class="no_print">Action</th>--->
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->
<?php } ?>
</div>
<script>
    //setDatatables();
    $(function () {
        let resultCore = [];
        let resultEnglish = [];
        let resultHindi = [];
        let myTr = [];
        let course='<?=!empty($this->department['id'])?$this->department['id']:'';?>';
        //alert(course);
        let degree_id  = '<?=!empty($this->department['degree_id'])?$this->department['degree_id']:'';?>';
        if(degree_id == 1){
           
            myTr.push($('#ac_id').val());

            if(myTr.length > 0){
                $('.load-box').css('display','block');
                let myString= myTr.toString();
                let arr = myString.split('+');
                let academic_year_id=arr[0];
                let department_id=arr[1];
                //alert(department_id);
                //alert(academic_year_id);
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-get-ge'; ?>',
                    data: {academic_year_id: academic_year_id,department_id:department_id,course:course}
                }).done(function (data) {
                    //alert(data);
                    $('.getablea').html(data);
                   // setDatatables();
                    $('.load-box').css('display','none');
                    // $('table').wrap('<td></td>').parent().wrapAll('<table id="dataTable"><thead><tr></tr></thead><tbody><tr></tr></tbody><tfoot><tr></tr></tfoot></table>');
                   
                });
            }
        }
        $('.testTable tr').each(function(){
            $('#applied', this).each(function(index, val){
                //alert('k');
                if(!resultCore[index]) resultCore[index] = 0;
              resultCore[index] += parseInt($(val).text());
            });
        });
        $('#totalSum').text(resultCore);
        $('.testTable tr').each(function(){
            $('#hindi', this).each(function(index, val){
               
                if(!resultHindi[index]) resultHindi[index] = 0;
              resultHindi[index] += parseInt($(val).text());
              //alert(resultHindi);
            });
        });
        $('#totalSumHindi').text(resultHindi);
        $('.testTable tr').each(function(){
            $('#english', this).each(function(index, val){
                //alert('k');
                if(!resultEnglish[index]) resultEnglish[index] = 0;
              resultEnglish[index] += parseInt($(val).text());
            });
        });
        $('#totalSumEnglish').text(resultEnglish);
    });

//End
//Script for modal

$(".view_document").click(function() {
    let application_no = $(this).closest("td").find("#app_number").val();        
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-get-applicant-info'; ?>',
            data: {application_no:application_no}
        }).done(function (data) {
            //alert(data);
            $('#resultas').html(data);
           });
    //$("#resultas").append(application_no);      
});
$("#cnf_cert").click(function() {
    let docArray = [];
    let form_id = $('.documentTable').find("#form_id").html();
    let app_id = $('.documentTable').find("#app_id").val();
    let course_id = $('.documentTable').find("#course_id").val();
        //alert(app_id);
    $(".documentTable td input[type=checkbox]:checked").each(function () {
        let documents = $(this).val();
        docArray.push(documents);
    });
    //alert(docArray);
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-upsert-documents'; ?>',
        data: {docArray:docArray,form_id:form_id,app_id:app_id,course_id:course_id}
    }).done(function (data) {
        //alert(data);
         $('#alert_msg').text(data);
        //$('#msg').html(data);
       });
    //console.log(docArray);
});
//Approve or reject a student by principal
$(".approveBtn").click(function() {
    let form_id = $(this).closest("td").find("#form_id").val();
    let buttonValue=$(this).closest("td").find('#approveBtn').val();
    
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-update-principal-status'; ?>',
        data: {form_id:form_id,buttonValue:buttonValue}
    }).done(function (data) {
         $("#p_status-"+form_id).text('Approved'); 
        alert("The Application Form this "+form_id+' is approved');
    });     
});
$(".rejectBtn").click(function() {

    let form_id = $(this).closest("td").find("#form_id").val();
    let buttonValue=$(this).closest("td").find('#rejectBtn').val();
    
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-update-principal-status'; ?>',
        data: {form_id:form_id,buttonValue:buttonValue}
    }).done(function (data) {
         $("#p_status-"+form_id).text('Rejected'); 
        alert("The Application Form this "+form_id+' is rejected');

    });   
});
//End
function refreshPage() {
    location.reload(true);
}
</script>