<div id="content">
<?php
if (count($this->messages)) {
	foreach ($this->messages as $message) {
		?>
		<div class="alert alert-success">
			<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
			<?php echo $this->escape($message); ?></div>
		<?php
	}
}
?>
<div class="row">
	<div class="col-xs-12">
		<form id="basicForm" action="<?php echo $this->mainconfig['host']; ?>finance/Candhformreport/index/type/search<?php //echo $this->form->getAction() ?>" method="post" class="form">		
		   <div class="panel">
				<div class="row" style="margin:0px;">					
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">Start Date</label>
							<?php echo $this->Candhformreport_form->start_date; ?>
						</div>
					</div>
					<div class="col-sm-3" >
						<div class="form-group" style=" padding-right:0px;">
							<label class="control-label">End Date </label>
							<?php echo $this->Candhformreport_form->end_date; ?>
						</div>
					</div> 
					<div class="col-sm-2" style="float:left;width:100px;">
						<div class="form-group">
							<div style="float:left">
								<br />							
								<input type="submit" style="margin-top:5px;" class="btn btn-primary" name="submit" value="Submit" id="submit_val">
							</div>											
						</div>
					</div>
					
						<div class="col-sm-2" style="float:right;width:100px;">
							<div class="form-group">
								<br />
								 <input type="submit" style="margin-top:5px;" class="btn btn-primary" name="print" value="print" onclick="this.form.target='_blank';return true;"> 
							</div>											
						</div> 
				</div>
								
			</div>
		</form>
	</div>
</div>
<?php 

$end_dates = $this->enddate;
$findMont = date("m", strtotime($end_dates));
$findYear = date("Y", strtotime($end_dates));

$totalday = cal_days_in_month(CAL_GREGORIAN, $findMont, $findYear); // 31
//echo $totalday ;
if(($this->type == 'search') || ($this->type == '') )
{ 
/* $purchase_statement = $this->purchase_statement;
if ( count($purchase_statement) > 0 ) {
	$amount = 0;
	foreach ($purchase_statement as $purchase) {
		$amount += $purchase['paid_amount'];
	}
	$trading_total_debit += $amount;			
}	 */										
										
?>

<!-- widget grid -->
<!-- widget grid -->
<section id="widget-grid" class="">	
	<!-- row -->
	<div class="row">
		
		<!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
				<header>
					<span class="widget-icon"> <i class="fa fa-table"></i> </span>
					<h2></h2>

				</header>

				<!-- widget div-->
				<div>		
					<!-- widget content -->
						<div class="widget-body">
							<div class="table-responsive">
							<table class="table table-striped mb30" id="table2">
									  <thead>
									  <tr>
										<td colspan="4" align="center"><strong>C & H Form Report</strong></td> 												
										</tr>
										 <tr>
											<th>C Form</th>					
											<th>Total Invoice Count</th>
											<th>Total Amount</th>
											<th>% of C Form</th> 
										 </tr>
									  </thead>
									  <tbody>      

									<?php //$i=1; 

									if(count($this->paginator) !=0){

									foreach ($this->paginator as $result){ ?>

										 <tr>

											<td><?php //echo $result['c_form_no'];?></td>

											<td><?php echo $result['sales_invoice_id'];?></td>
											
											<td><?php  echo $result['total_amount'];?></td>
										   <td><?php  //echo number_format($result['after_discount_price']);?></td>
										 </tr> 
									<?php } ?>

										   <tr class="odd gradeX">
											<td colspan="4" align="center"> <?php  //echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>
											</td>
										   </tr>
										<?php } else { ?>
										   <tr class="odd gradeX">
											   <td colspan="4" align="center">No Results Found</td>
										   </tr>
									<?php }?>
									</tbody>
								</table>
								<table class="table table-striped mb30" id="table2">
									  <thead>
										 <tr>
											<th>H Form</th>					
											<th>Total Invoice Count</th>
											<th>Total Amount</th>
											<th>% of H Form</th> 
										 </tr>
									  </thead>
									  <tbody>      

									<?php $i=1; 

									if(count($this->paginator1) !=0){

									foreach ($this->paginator1 as $result1){ ?>

										 <tr>

											<td><?php //echo $result['h_form_no']; ?></td>

											<td><?php echo $result1['sales_invoice_id'];?></td>
											
											<td><?php  echo $result1['total_amount'];?></td>
										   <td><?php  //echo $result['after_discount_price'];?></td>
										 </tr> 
									<?php } ?>

										   <tr class="odd gradeX">
											<td colspan="4" align="center"> <?php // echo $this->paginationControl($this->paginator1, 'Sliding', 'pagination.phtml'); ?>
											</td>
										   </tr>
										<?php } else { ?>
										   <tr class="odd gradeX">
											   <td colspan="4" align="center">No Results Found</td>
										   </tr>
									<?php }?>
									</tbody>
								</table>
							</div>
						</div>
					<!-- end widget content -->
				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->
		</article>
		<!-- WIDGET END -->
	</div>
	
	<!-- end row -->
</section>
<!-- end widget grid -->
<?php } ?> 
</div>
<script type="text/javascript">
	$("#start_date").datepicker({ 
		dateFormat: 'yy-mm-dd',
		prevText: '<i class="fa fa-chevron-left"></i>',
		nextText: '<i class="fa fa-chevron-right"></i>'
	});
	$("#end_date").datepicker({ 
		dateFormat: 'yy-mm-dd',
		prevText: '<i class="fa fa-chevron-left"></i>',
		nextText: '<i class="fa fa-chevron-right"></i>'
	});
</script>