
<style type="text/css">
.modal-header .close {
    margin-top: -2px;
    color: white;
    }
.modal-header {
    border-bottom: 0px solid #666;
}
.modal-body,.modal-header{
    background-color: #666;

}
.modal{
    display: block;
    background-color: white;
}
.register_form{
    padding-top: 20px;
    text-align: center;
}
.Login_header{
    border-color: #2e6da4;
    display: inline-block;
    margin-bottom: 20px;
    line-height: 1.42857143;
    white-space: nowrap;
    vertical-align: middle;
    user-select: none;
     text-align: center;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}

.register_btn{
    color: #fff;
    background-color: #932e90;
    border-color: #2e6da4;
    display: inline-block;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    padding: 6px 55px;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}

* {
  box-sizing: border-box;
}
.header-text{
    background-color: #932e90;
    min-width: 200px;
    min-height: 30px;
    margin-bottom: 4em;
}


.regForm {
  background-color: #ffffff;
  margin: 100px auto;
  font-family: Raleway;
  padding: 40px;
  width: 50%;
  border: 4px solid white;
  border-radius:8px;
  min-width: 295px;
}
.resets_pass {
    margin-top: 30px !important;
}
    .load-box{
        display:none;
        position:absolute;
        width:100%;
        height:100%;
        background:rgba(255,255,255,.4);
        z-index: 999;
    }
    
    .load-box>img{
        position:absolute;
        top:60%;
        left:50%;
        width:40em;
        transform: translate(-50%,-50%);
        
        
    }
    .login_area{
     
        
    }
    
    .mob_info{
        position:absolute;
    }
    
</style>

<div class="login_area">
<form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

    <div class="row">
        <div class="col-sm-12 employee_class " style="text-align: center" >
            <b style="color:#932e90">*Note : &nbsp;REGISTERED &nbsp;APPLICANTS &nbsp;&nbsp;LOGIN HERE !.</b>
        </div>
        <hr>
      
    </div><br>
    <div class="row">
        <div class="col-sm-4 employee_class">
            <div class="form-group disabled" >
                <label><b>Application Number:</label><span class="asterisk">*</span>

            </div>
        </div>
        <div class="col-sm-8 employee_class">
            <div class="form-group disabled" >
                 <?php echo $this->form->applicant_number; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 employee_class">
            <div class="form-group disabled" >
               <label style="float:left;"><b>Password:</b><span class="asterisk">*</span></label>

            </div>
        </div>
        <div class="col-sm-8 employee_class">
            <div class="form-group disabled" >
                <?php echo $this->form->password; ?>
            </div>
        </div>
        <?php if($_SESSION['flash_message_error']) {?>
               <p style="color:red;text-shadow:2px 2px 2px rgba(0,0,0,.1); text-align: right"><?php echo $_SESSION['flash_message_error']; 
                    session_unset('flash_message_error');?> </p>
              
        <?php }?>
    </div>
   
    <div class="row">
        
            <div class="col-sm-4 resets_pass">
                <a class="reset_pass" id='forgot_pword' style="color:#932e90;text-shadow:0 0px 0 #932e90;" href="<?php echo $this->mainconfig['host'] . 'entrance-exam-form/forgot-password'; ?>">Forgot  Password?</a>
            </div>
            <div class="col-sm-8 employee_class register_form" >
                <div style="float:right;">
                    <button  type="submit" class="btn btn-primary" id="submit">Log In</button>
                </div>
            </div>
       
    </div>
</form>
</div>

<!--- Modal for confirmation----> 
<div class="container">


  <!-- The Modal -->
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        
        
        <!-- Modal body -->
        <div class="modal-body">
            <div class="row">
                <div class="col-sm-9">
                   
                        <img class="img img-rounded"  src="<?php echo $this->mainconfig['host'] .'public/images/pwc-web-logo.png' ?>"  alt="img">
                    
                   
                </div>
                <div class="col-sm-2">
                   
                </div>
            </div><br><br>
              
            <div class="row">
                <div class="col-sm-6">
                    <h4 style="color:white"><p>Click to register:</p></h4>
                </div>
                <div class="col-sm-offset-3 col-sm-2 ">
                   <button type="button" class="btn btn-primary" onclick="window.location.href='<?php echo $this->mainconfig['host'] . 'entrance-exam-form/instruction'; ?>'">Register</button>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6">
                    <h4 style="color:white"><p>Already registered?</p>
                    <p>Click to fill in your application:</p></h4>
                </div><br>
                <div class="col-sm-offset-3 col-sm-2 ">
                    <button type="button" class="btn btn-success" data-dismiss="modal">Log In</button>      
                </div>
            </div>
            
             <div class="row">
                 <div class="col-sm-4">
                    <a href='<?php echo $this->mainconfig['host'] ?>public/pdfUpload/ProspectusColor-PDF-2020-21.pdf' target="_blank" class="btn btn-success">Propectus 2020-2021</a>      
                
                    
                </div>
                <div class="col-sm-6">
                    
              <a href='<?php echo $this->mainconfig['host'] ?>public/pdfUpload/User-Manual.pdf' target="_blank" class="btn btn-primary">User Manual</a>      
                
            </div>
            </div>
        
      </div>
    </div>
  </div>
  
</div>
<!--- End---->

 
<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script> 
<script>
    $('.mob_info').hide();
    var modal = document.getElementById('myModal');
    $(window).load(function(){
        var login_error= "<?php echo $this->invalid; ?>";
        //alert(login_error);
        if(login_error){
            $('#myModal').modal('hide');
        }else{
            $('#myModal').modal('show');
        }
        
       
    });
    
    window.onclick = function(event) {
        if (event.target == modal) {
            $('#myModal').modal({backdrop: 'static', keyboard: false});
        }
    }
    
    //Check Duplicate email id in table
    $('#emailError').text("");
    $("#email_id").change(function(){
     var email_id = $('#email_id').val();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'entrance-exam-form/ajax-check-duplicate-email'; ?>',
            data: {email_id:email_id}
        }).done(function( data ) {
            //alert(data);
            if(data==1){
                $('#emailError').text("*Email id is already registered with us.");
                $('#email_id').val('');
            }else{
                $('#emailError').text("");
            }
        }); 
    });
    //End
    

//To MATCH PASSWORD
   
    $('#cnf_password').blur(function() {
        if ($('#password').val() == $('#cnf_password').val()) {
            $('#cnf_password').css("color", "green");
            $('#cnf_password').val('' + 'Matched');
            return false;
        } else { 
            $('#cnf_password').css("color", "red");
            $('#cnf_password').val('' + 'Not Matched');
            return true; 
        }
    });
//End
</script>
