<style>
    .multistepformArea{
    padding-top: 1px;
    background-color: white;
	width: 70%;
	margin: 50px auto;
	position: relative;
}
/*form styles*/
.regForm {
    width: 90%;
	margin: 50px auto;
	position: relative;
}
#formValidate1 fieldset {
	background: white;
	border: 0 none;
	border-radius: 3px;
	box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.1);
	box-sizing: border-box;
	position: relative;
}
.sub{
    text-align: center;
    padding-top: 1em;
}
.admit{
    text-shadow:1px 1px RGBA(147,46,144,1);
}

table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  text-align: left;    
}

.table>thead>tr>th {
    text-align: center;
        
}

</style>
<?php 
$dataArray= array(
    'core_course' =>'Core Course',
    'ge' =>'Generic Elective',
    'aecc'=>'Ability Enhancement Compulsory Course ',
    'comp' =>'Compulsory'
);
$prefArray= array(
    'tablea' =>'(A)	First Preference',
    'tableb' =>'(B)	Second Preference',
);

?>
<?php if($this->payment_detail['payment_status'] == 1){ ?>
<div class="downloadArea" id="downloadArea">
    <div class="multistepformArea">
        <form class="regForm" id="formValidate1" action="" method="post" data-validate="parsley" >

            <div class="row">
                <div class="col-sm-12">
                    <fieldset>
                        &nbsp; <p><legend >&nbsp;&nbsp; List of Documents to download. </legend></p>

                    <div class="col-sm-12 employee_class">
                        <div class="form-group">
                           
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                                <tbody>
                                    <thead>
                                        <tr>
                                            <?php if($this->payment_detail['exam_date']!= '0000-00-00'){ ?>
                                             <th><button type="button" id="appForm" class="btn btn-success">Application Form</button></th> 
                                            <th><button type="button" id="admitCard" class="btn btn-success">Admit Card</button></th> 
                                             <?php } else { ?>
                                             <th><button type="button" id="appForm" class="btn btn-success">Application Form </button></th> 
                                             <?php } ?>
<!--                                            <th>
                                            <button type="button" id="baptismcert" class="btn btn-success">Baptism Certificate</button>
                                            </th> -->
<!--                                            <th>
                                            <button type="button" id="casteCert" class="btn btn-success">Caste Certificate</button>
                                            </th>  -->
                                        </tr>
                                    </thead>
                                   
                                </tbody>
                            </table>
                        </div>
                    </div>
                    

                    </fieldset> 
                    &nbsp;<br>

                </div>
            </div>
        </form>
    </div>
    </div>
    <!----Admit Card For Print--->
    <div class="admitCardPreview" id="admitCardPreview">
        
    </div>
    <div class="applicationFormPreview" id="applicationFormPreview">
        
    </div>
    <div class="castePreview" id="castePreview">
        
    </div>
<?php }else{?>
    <div class="multistepformArea">
        <form class="regForm" id="formValidate1" action="" method="post" data-validate="parsley" >
    <div class="col-sm-12 employee_class">
                        <div class="form-group">
                           
                            <table class="table table-bordered table-bordered mb30 jambo_table bulk_action coreTable">
                                <tbody>
                                    <thead>
                                     
                                    </thead>
                                   
                                <tbody>
                                    <tr class="info">
                                        <td colspan="2">Your are not authorized to download documnets.</td> 
                                           
                                        </tr>
                                        <tr class="danger">
                                             <td>Payment Status</th> 
                                             <td>Unpaid</td> 
                                           
                                        </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
        </form>
    </div>
    
<?php } ?>
<script>
    $('#admitCardPreview').hide(); 
    
    $('#admitCard').click(function(){
        var application_no = '<?php echo isset($this->a_id)? $this->a_id:'';?>';
        //alert(challan);
        
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'entrance-exam-form/admit-Card-Preview'; ?>',
            data: {application_no:application_no}
        }).done(function (data) {

            if(data){
                
                $('#castePreview').empty(); 
                $('#applicationFormPreview').empty();
                $('#admitCardPreview').show();
                $('#admitCardPreview').html(data);
            }else{
                //alert('no');
            }
        });
    });
    
    $('#appForm').click(function(){
        var application_no = '<?php echo isset($this->a_id)? $this->a_id:'';?>';
        //alert(challan);
        $('#applicationFormPreview').empty();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'entrance-exam-form/application-form-Preview'; ?>',
            data: {application_no:application_no}
        }).done(function (data) {

            if(data){
                $('#castePreview').empty();
                $('#admitCardPreview').empty();
                //$('#downloadArea').empty();
                $('#applicationFormPreview').html(data);
            }else{
                //alert('no');
            }
        });
    });
    $('#casteCert').click(function(){
        var application_no = '<?php echo isset($this->a_id)? $this->a_id:'';?>';
        //alert(challan);
        $('#castePreview').empty();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'entrance-exam-form/caste-Certifiate-Preview'; ?>',
            data: {application_no:application_no}
        }).done(function (data) {

            if(data){
                 
                $('#admitCardPreview').empty();
               $('#applicationFormPreview').empty();
             //   $('#downloadArea').empty();
                $('#castePreview').html(data);
            }else{
                //alert('no');
            }
        });
    });
    
    function myFunction() {
        $('body').css('visibility', 'hidden');
        $('#applicationFormPreview').css('visibility', 'visible');
        $('#applicationFormPreview').css({"position": "static", "top": "-3em"});
        
        
        window.print();
  
}


</script>