
<style type="text/css">

.register_form{
    padding-top: 20px;
    text-align: center;
}
.Login_header{
    border-color: #2e6da4;
    display: inline-block;
    margin-bottom: 20px;
    line-height: 1.42857143;
    white-space: nowrap;
    vertical-align: middle;
    user-select: none;
     text-align: center;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}

.register_btn{
    color: #fff;
    background-color: #932e90;
    border-color: #2e6da4;
    display: inline-block;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: 400;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    padding: 6px 55px;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}

* {
  box-sizing: border-box;
}
.header-text{
    background-color: #932e90;
    min-width: 200px;
    min-height: 30px;
    margin-bottom: 4em;
}


.regForm {
  background-color: #ffffff;
  margin: 100px auto;
  font-family: Raleway;
  padding: 40px;
  width: 35%;
  border: 4px solid white;
  border-radius:8px;
  min-width: 295px;
}
.resets_pass {
    margin-top: 30px !important;
}
    .load-box{
        display:none;
        position:absolute;
        width:100%;
        height:100%;
        background:rgba(255,255,255,.4);
        z-index: 999;
    }
    
    .load-box>img{
        position:absolute;
        top:60%;
        left:50%;
        width:40em;
        transform: translate(-50%,-50%);
        
        
    }
    .login_area{
        padding-top: 5%;
        
    }
    
    .mob_info{
        position:absolute;
    }
    
</style>

<div class="login_area">
<form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

    <div class="row">
         
        <div class="col-sm-12 employee_class " style="text-align: center" >
            <b style="color:#932e90">Please enter your email address. You will receive a password via email.!</b>
            <hr>
        </div>
    </div><br>
    <div class="row">
        <div class="col-sm-3 employee_class">
            
               
            <div class="form-group disabled" >
                <label><b>Email Id:</b></label>

            </div>
        </div>
        <div class="col-sm-9 employee_class">
            
            <div class="form-group disabled" >
                 <?php echo $this->form->email_id; ?>
                <?php if($_SESSION['flash_message_error']) {?>
                <b style="color:blueviolet;text-shadow:2px 2px 2px rgba(0,0,0,.1); text-align: left"><?php echo $_SESSION['flash_message_error']; 
                    session_unset('flash_message_error'); ?> </b>
              
                <?php } ?>
            </div>
        </div>
    </div>
   
   
    <div class="row">
         
            <div class="col-sm-12 employee_class register_form" >
                <div style="float:right;">
                    <button  type="submit" class="btn btn-primary" id="submit">Get Your Password</button>
                    <a href="<?php echo $this->mainconfig['host'] . 'entrance-exam-form/index'; ?>" ><button  type="button" class="btn btn-success">Login</button></a>
                </div>
            </div>
         
    </div>
</form>
</div>


 
<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script> 
<script>
   
  

//To MATCH PASSWORD
   
    $('#cnf_password').blur(function() {
        if ($('#password').val() == $('#cnf_password').val()) {
            $('#cnf_password').css("color", "green");
            $('#cnf_password').val('' + 'Matched');
            return false;
        } else { 
            $('#cnf_password').css("color", "red");
            $('#cnf_password').val('' + 'Not Matched');
            return true; 
        }
    });
//End
</script>
