<style>
   
    bannertext h1 {
    text-transform: uppercase;
    color: #fff;
     font-family: Raleway;
        font-size:4em;
    margin-top: 55px;
}
 .navbar{
        padding-top:20px;
    }
/*.bannertext p {*/
/*    margin-top:1em !important;*/
/*}*/
 .footer_social_browser_contact_area{
           position:fixed;
           width:100%;
           bottom:0;
       }
       .tabsdiv{
           margin-top:4rem !important;
       }
     @media screen and (min-width: 1300px) {
.tabs02 {
    margin-top: -5rem !important;
    
}
}   
/*.Programmestabs>li a{*/
/*    box-shadow:1px 1px 4px #000;*/
/*}*/


</style>

<section class="wellcome_slides_area clearfix" id="home" >
        <div id="demo" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active" style="background-color: #000">
                    
                    <img src="<?php echo $this->mainconfig['publicpath']; ?>img/1572850572.jpg" alt="MIT WPU Banner" class="w-100 d-none d-md-block">
                   
                    <div class="d-none d-md-block">
					
                    </div>
                </div>
            </div>
        </div>
        <div class="banner-form" id="contact-form">
            <div class="container">
                <div class="row">
                
<form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

    <div class="row">
        <div class="col-sm-12 employee_class " style="text-align: center" >
            <b style="color:#000">REGISTERED APPLICANTS LOGIN HERE :</b>
        </div>
        <hr>
    </div><br>
    <div class="row">
        <div class="col-sm-4 employee_class">
            <div class="form-group disabled" >
                <label><b>Application Number:</label></h2>

            </div>
        </div>
        <div class="col-sm-8 employee_class">
            <div class="form-group disabled" >
                 <?php echo $this->form->applicant_no; ?>
                <?php echo $this->form->csrftoken; ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 employee_class">
            <div class="form-group disabled" >
               <label style="float:left;"><b>Password:</b></label>

            </div>
        </div>
        <div class="col-sm-8 employee_class">
            <div class="form-group disabled" >
                <?php echo $this->form->password; ?>
            </div>
        </div>
        <?php //if($_SESSION['flash_message_error']) {?>
               <p style="color:red;text-shadow:2px 2px 2px rgba(0,0,0,.1); text-align: right"><?php //echo $_SESSION['flash_message_error']; 
                    //session_unset('flash_message_error');?> </p>
              
        <?php //}?>
    </div>
   
    <div class="row">
        <div class="col-sm-12">
            <div class="col-sm-3 resets_pass">
              <!--  <a class="reset_pass" id='forgot_pword' style="color:#932e90;text-shadow:0 0px 0 #932e90;" href="<?php echo $this->mainconfig['host'] . 'entrance-exam-form/forgot-password'; ?>">Forgot  Password?</a>-->
            </div>
            <div class="col-sm-offset-9 employee_class register_form" >
              <button  type="submit" class="register_btn" id="submit">Log In</button>
            </div>
        </div>   
    </div>
</form>


                </div>
            </div>
            
        </div>
        
    </section>
    <section class="Programmesection d-block d-md-none">
      
    </section>
    <section class="d-none d-md-block">

    </section>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
   