<link href="<?php echo $this->mainconfig['publicpath'];?>vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
 <script src="<?php echo $this->mainconfig['publicpath'];?>js/jquery-1.12.2.min.js"></script>
<script src="<?php echo $this->mainconfig['publicpath'];?>vendors/bootstrap/dist/js/bootstrap.min.js"></script>
	
	 <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 100%;
	  margin: auto;
  }
  
  </style>
   <div class="container">
	  <div class="row">
	  <div class="col-sm-9">
	  <div style="" align="center">
                  <h1><img src="<?php echo $this->mainconfig['publicpath'];?>img/1572850577Logo.png" style="" alt="..." class=""></h1>
                  </div>
				  <hr>
				  </div>
				  
		 <div class="col-sm-3">
		 <p><a target="_blank" class="btn btn-success" href="<?php echo $this->mainconfig['host'];?>/entrance-exam-form/">Online Registration</a></p>
		 </div>		 
				  
				  </div>
         <?php if($_SESSION['flash_message']) {?>
       <div class='row'>
                 <div class="alert alert-info ">
                   
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $_SESSION['flash_message']; unset($_SESSION['flash_message'])?>
</div>
       </div>
         <?php }?>
	 <div class="row">
	 <div class="col-sm-8">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="2000">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
     	<!--  <li data-target="#myCarousel" data-slide-to="3"></li>
 <li data-target="#myCarousel" data-slide-to="4"></li>
	  <li data-target="#myCarousel" data-slide-to="5"></li>-->
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <!--<div class="item active">
        <img src="<?php echo $this->mainconfig['publicpath'];?>images/banner1.jpg" alt="Chania" width="460" height="350">
      </div>-->

      <div class="item active">
        <img src="<?php echo $this->mainconfig['publicpath'];?>img/iih1.jpg" alt="Chania" width="460" height="350">
      </div>
    
      

      <div class="item">
        <img src="<?php echo $this->mainconfig['publicpath'];?>img/iih2.jpg" alt="Flower" width="460" height="350">
      </div>
	  <div class="item">
        <img src="<?php echo $this->mainconfig['publicpath'];?>img/iih3.jpg" alt="Flower" width="460" height="350">
      </div>
	
	  
 <!--	 <div class="item">
        <img src="<?php echo $this->mainconfig['publicpath'];?>images/dmii.png" alt="Flower" width="460" height="350">
      </div>-->
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  </div>

	<div class="col-sm-4" style="">
	 <div class="login_wrapper"  style="">
	  <?php// echo '<pre>'; print_r($_SESSION); exit;?>
        <div class="animate form login_form" style="border:1px solid #9b131f;padding:5px;">
		 <h2 style="text-align:center;color:#fff;background-color:#424170 !important;margin-top:-5px;margin-bottom:5px;margin-left:-5px;margin-right:-5px;">Login</h2>
          <section class="login_content">
                
                
            <form method="post" id='form'>
                <div id="userInfo">
              <div>
                  <input type="text" class="form-control" name="admin_user_name" autocomplete="off" id="admin_user_name" placeholder="Username" required="" />
              </div>
              <div>
                  <input type="password" class="form-control" name="password" autocomplete="off" id="password" placeholder="Password" required="" />
              </div>
                  <!-----------------------Captcha Code div ------------- !--->
                  
                  
                    <?php if($_SESSION['accountLockedmsg']) {?>
                
                  <div class="col-sm-12" style="margin-left:-2em;" >
                      <div class="col-sm-6">
                          <input type="text" class="form-control" name="captcha" id="captcha" required="required" autocomplete="off" placeholder="Enter Captcha">
                      </div>
                      <div class="col-sm-6">
                        <img src="<?=$this->mainconfig['host']?>index/captcha" alt="PHP Captcha">
                    </div>
                     
                  </div>
                 <div>
                       <p style="color:red;text-shadow:2px 2px 2px rgba(0,0,0,.1)"><?php echo '<b>Invalid Username or Password or Captcha!</b>'?> </p>
                      </div>
                  
                      <?php }session_unset('accountLockedmsg');?>
                  
               
              </div>
                
                    <div class="separator">
                    <div class="clearfix"></div>
                    <br />
                    </div>
                
              <div id='btn'>
                <button class="btn btn-default" id="loginAttempt" style="color:#9b131f;text-shadow:0 0px 0 #9b131f;" type="submit">Log in</button>
                <a class="reset_pass" id='forgot_pword' style="color:#9b131f;text-shadow:0 0px 0 #9b131f;" href="#">Forgot  Password?</a>
              </div>

              <div class="clearfix"></div>
			  
			  
            </form>
			
          </section>
		 
        </div>

      </div>
	  </div>
	  </div>
        <div class="row">
            <div class="col-sm-12" style="padding:60px 0px 0px 500px;">
               <p>©<?php echo date('Y'); ?> All Rights Reserved.</p>
             </div>
        </div>
	</div>
  
 
<script>
    $('#forgot_pword').click(function(){
        $('#userInfo').empty();
        $('#userInfo').html('<div><input class="form-control" type="email" required="" placeholder="Enter Email ID" name="f_username"/></div>');

        $('#btn').css({"position":"absolute","left":"0px","margin-top":"20px"});
        $("#forgot_pword").css("display","none");
        $('#btn > .btn').empty();
        $('#btn > .btn').text("Send Mail");  
    });
    //set Timer after failed login attempt : Kedar 10 Dec 2019  
    function Timer(duration, display) {
        var timer = duration, hours, minutes, seconds;
        setInterval(function () {
            hours = parseInt((timer /3600)%24, 10)
            minutes = parseInt((timer / 60)%60, 10)
            seconds = parseInt(timer % 60, 10);

            hours = hours < 10 ? "0" + hours : hours;
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;

            display.text(hours +":"+minutes + ":" + seconds);

                    --timer;
        }, 1000);
    }

    jQuery(function ($){
        var current_date = new Date();
        var time_hr =  current_date.getHours();
        var time_mn = current_date.getMinutes();
        var mt=Math.round(60-time_mn)/60;
        var calculated_time=24 + mt;
        var dt = calculated_time-time_hr;
        var twentyFourHours = dt * 60 * 60;
        var display = $('#remainingTime');
        Timer(twentyFourHours, display);
    });
    //End
</script>
      


