<?php //echo "<pre>"; print_r($item_result);exit; ?>
<style>
    .my.table>tbody>tr>td, .my.table>tbody>tr>th, .my.table>tfoot>tr>td, .my.table>tfoot>tr>th, .my.table>thead>tr>td, .my.table>thead>tr>th {
        padding: 2px !important;
        line-height: 1.42857143;
        vertical-align: middle !important;
        border-top: 1px solid #ddd;
    }
    .my.table{
        margin-bottom: 0px;
    }
    #section-label{
        display:none;
    }
</style>    
<div class="right_col">
    <?php if ($this->type) { ?>
        <div class="padding-md">
            <?php
            if (count($this->messages)) {
                foreach ($this->messages as $message) {
                    ?>
                    <div class="alert alert-success ">
                        <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                        <?php echo $this->escape($message); ?>
                    </div>
                <?php
                }
            }
            ?>
            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Interactive Learning Sessions</i></div>
                    </h3>
                    <div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                            <div class="panel-body">


                                <div class="row">
                                    <input type="hidden" name="submit_type" id="submit_type" value=""/>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Batch<span class="asterisk">*</span></label>

                                            <?php if ($this->type == 'edit') { ?>
                                                <?php echo $this->form->Academic_id; ?>
                                            <?php } else { ?>
                                                <?php
                                                if (in_array($this->role_id, $this->administrator_role)) {
                                                    //print_r($this->administrator_role);exit;
                                                    ?>
                                                    <?php echo $this->form->academic_year_id;
                                                }
                                                ?>
    <?php } ?>
                                        </div>
                                    </div>

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Terms <span class="asterisk">*</span></label>
                                            <?php if ($this->type == 'edit') { ?>
                                                <?php echo $this->form->Term_id; ?>
                                            <?php } else { ?>
                                                <?php
                                                if (in_array($this->role_id, $this->administrator_role)) {
                                                    //print_r($this->administrator_role);exit;
                                                    ?>
                                                    <?php echo $this->form->term_id;
                                                }
                                                ?>
    <?php } ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Section<span class="asterisk">*</span></label>
                                            <?php if ($this->type == 'edit') { ?>
                                                <?php echo $this->form->section; ?>
                                            <?php } else { ?>
                                                <?php
                                                if (in_array($this->role_id, $this->administrator_role)) {
                                                    //print_r($this->administrator_role);exit;
                                                    ?>
                                                    <?php echo $this->form->section;
                                                }
                                                ?>
    <?php } ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <?php if ($this->type == 'edit') { ?>
                                                <label class="control-label">Version <span class="asterisk"></span></label>
        <?= $this->form->version_id; ?>
    <?php } ?>
                                        </div>	


                                        <!-- <div class="col-sm-3 employee_class">
            <div class="form-group">
            <label class="control-label">Credit<span class="asterisk">*</span></label>
    <?php //echo $this->form->credit_id;    ?>
            </div>
                                        </div> -->
                                    </div>

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <?php if ($this->type == 'edit') { ?>
                                                <label class="control-label">From Date <span class="asterisk"></span></label>
        <?= $this->form->from_date; ?>
    <?php } ?>

                                        </div>

                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <?php if ($this->type == 'edit') { ?>
                                                <label class="control-label">To Date <span class="asterisk"></span></label>
        <?= $this->form->to_date; ?>
    <?php } ?>

                                        </div>

                                    </div>
                                </div>

                            <?php if ($this->type != 'edit'): ?>
                                    <?php
                                    $publish_var = "Waiting for publish";
                                    $publish_bg = "panel-warning";
                                    ?>
                                    <?php if (count($this->paginator) == 0) { ?>
            <?php $publish_var = "Nothing to publish"; ?>
            <?php $publish_bg = "panel-success"; ?>
        <?php } $noopen = true;?> <?php if(!$noopen){?>
                                    <div class="row">
                                        <div class="panel-group" id="accordion">
                                            <div class="panel <?= $publish_bg; ?> ">
                                                <div class="panel-heading text-center">
                                                    <h4 class="panel-title">
                                                        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1">
        <?= $publish_var; ?></a>
                                                    </h4>
                                                </div>
                                                <div id="collapse1" class="panel-collapse collapse">
                                                    <div class="panel-body">

                                                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
                                                            <thead>
                                                                <tr>
                                                                    <th>S.  No.</th>	
                                                                    <th>Batch Code</th>
                                                                    <th>Terms</th>
                                                                    <th>Status</th>
                                                                    <th>Updated Date</th>
                                                                    <th>Action</th>
                                                                    <!--<th>View</th>-->
                                                                </tr>
                                                            </thead>
                                                            <tbody>

                                                                <?php
                                                                // print_r($this->paginator);exit;
                                                                $i = 0;
                                                                $pagination_tr = '';
                                                                if (count($this->paginator) != 0) {
                                                                    // print_r($this->paginator);exit;
                                                                    foreach ($this->paginator as $results) {
                                                                        ?>
                                                                    <td><?= ++$i; ?></td>
                                                                    <td><?= $results['short_code']; ?></td>
                                                                    <td><?= $results['term_name']; ?></td>
                                                                    <td>Not Published</td>
                                                                    <td><?= $results['updated_date']; ?></td>
                                                                    <td><button class="btn btn-primary" onclick="ajaxfunction(<?= $results['term_id'] ?>,<?= $results['academic_year_id'] ?>);" >Edit And Publish</button></td>
                                                                    <!--<td><a class="component_view" id="<?php echo $results['ec_id']; ?>"> View</a></td>-->

                                                                    </tr>            

                                                                    <?php
                                                                }
                                                                $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                                            }
                                                            ?>  </tbody>
                                                        </table>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
        <?php }?>
    <?php endif; ?>
                                <div class="" id="grade_data">
                                    <div id='f_div' style="display:none">
                                    </div>

                                    <div id="item_details"><?php if (count($this->result) > 0) { ?>
                                        <?php // print_r($this->result);exit;   ?>
                                        </div>
        <?php
    } else {
        ?>

                                        <input type="hidden" name="academic_year_id" value="<?php echo $this->result['academic_year_id']; ?>"/>
                                        <input type="hidden" name="department_id" value="<?php echo $this->result['department_id']; ?>"/>
                                        <input type="hidden" name="employee_id" value="<?php echo $this->result['employee_id']; ?>"/>
                                        <input type="hidden" name="batch" value="<?php echo $this->batch_short_code; ?>"/>
        <?php
    }
    ?>



                                    <div class="text-center">
                                        <div class="col-sm-0" style="float:right;">
              <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host'];   ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id;   ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
                                        <?php
                                        $item_result = $this->result;
//echo '<pre>'; print_r($this->result['class_value'][0]['date']); die;  
                                        ?>
    <?php $x = ''; ?>

    <?php if ($item_result['day_diff'] > 0) { ?>
                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action" style="width:100%;" >
                                                <thead>
                                                    <tr>
                                                        <th style="text-align:center;">Date </th>	
                                                        <th style="text-align:center;">Day</th>
                                                        <th style="text-align:center;">Day count</th>
                                                        <th style="text-align:center;">Class I</th>
                                                        <th style="text-align:center;">Class II</th>
                                                        <th style="text-align:center;">Class III</th>
                                                        <th style="text-align:center;">Class IV</th>
                                                        <th style="text-align:center;">Class V</th>
                                                    </tr>
                                                </thead>
                                                <?php $j = 0; ?>
                                                <?php $l = 0; ?>


                                                    <?php if ($item_result['selected_date'] == 0)
                                                        $date = strtr($item_result['start_date'], '/', '-');
                                                    else
                                                        $date = $item_result['selected_date'];
                                                    ?> 

                                                <tbody style="text-align:center;">
                                                        <?php for ($i = 0; $i <= $item_result['day_diff']; $i++): ?> 
                                                            <?php $course1 = $course2 = $course3 = $course4 = $course5 = 0; ?>
                                                            <?php $inc_date = date("d-m-Y", strtotime($date . ' + ' . $i . ' days')); ?>

                                                        <tr>
                                                            <?php $k = 0; ?>
                                                            <?php $holiday_name = ''; ?>
                                                            <?php $background_color = ''; ?>
                                                            <?php $text_color = 'red'; ?>
                                                            <?php $border_color = ''; ?>
                                                            <?php for ($holi = 0; $holi < count($item_result['holidays']); $holi++): ?>
                                                                <?php if (strtotime($date . ' + ' . $i . ' days') >= strtotime(date("m/d/Y", strtotime($item_result['holidays'][$holi]['start']))) AND ( strtotime($date . ' + ' . $i . ' days') <= strtotime(date("m/d/Y", strtotime($item_result['holidays'][$holi]['end']))))) {
                                                                    ?>
                                                                    <?php $k = 1; ?>   
                                                                    <?php $holiday_name = $item_result['holidays'][$holi]['title']; ?>
                    <?php $background_color = $item_result['holidays'][$holi]['backgroundColor']; ?>
                    <?php $text_color = $item_result['holidays'][$holi]['textColor']; ?>
                    <?php $border_color = $item_result['holidays'][$holi]['borderColor']; ?>
                    <?php break; ?>
                <?php }endfor; ?>
            <?php if (in_array(date('D', strtotime($inc_date)),$item_result['weekends']) || $k == 1) { ?>
                                                        <input type="text" value="<?= $inc_date; ?>" style="display:none" name="date[]">
                                                        <input type="text" value="<?= date('l', strtotime($inc_date)); ?>" style="display:none;" name="days[]">
                                                        <td style="box-shadow:2px 2px 4px <?= $border_color; ?>;  border:2px dashed <?= $border_color; ?>; background-color:<?= $background_color; ?>; text-align: center; color:<?= $text_color; ?>; font-weight: bold; font-size:130%;"><?= $inc_date; ?></td>
                                                        <td colspan='2' style="border:2px dashed <?= $border_color; ?>; background-color:<?= $background_color; ?>; text-align: center; color:<?= $text_color; ?>; font-weight: bold; font-size:130%;"><?= date('l', strtotime($inc_date)) . " " . $holiday_name; ?></td>
                                                        <td style="border:2px dashed <?= $border_color; ?>; background-color:<?= $background_color; ?>; text-align: center; color:<?= $text_color; ?>; font-weight: bold; font-size:130%;" >
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>
                                                                </thead>
                                                                <tbody>

                                                                    <tr>

                                                                        <td>
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_1']) { ?>

                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course1 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                    <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course1 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?>
                                                                        </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_1']; ?>
                    <?php } ?>
                <?php endfor; ?>

                                                                        </td>


                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>


                                                        <td style="border:2px dashed <?= $border_color; ?>; background-color:<?= $background_color; ?>; text-align: center; color:<?= $text_color; ?>; font-weight: bold; font-size:130%;">
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>
                                                                </thead>
                                                                <tbody>

                                                                    <tr>


                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>      
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_2']) { ?>
                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course2 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                    <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course2 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?>
                                                                        </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?> 
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_2']; ?>
                    <?php } ?>
                <?php endfor; ?>
                                                                        </td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>

                                                        </td>
                                                        <td style="border:2px dashed <?= $border_color; ?>; background-color:<?= $background_color; ?>; text-align: center; color:<?= $text_color; ?>; font-weight: bold; font-size:130%;">
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>

                                                                </thead>
                                                                <tbody>
                                                                    <tr>


                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>      
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_3']) { ?>


                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course3 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                    <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course3 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?>
                                                                        </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_3']; ?>
                    <?php } ?>
                <?php endfor; ?>
                                                                        </td>
                                                                    </tr>    
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                        <td style="border:2px dashed <?= $border_color; ?>; background-color:<?= $background_color; ?>; text-align: center; color:<?= $text_color; ?>; font-weight: bold; font-size:130%;">
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>
                                                                <thead>
                                                                <tbody>
                                                                    <tr> 
                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_4']) { ?>


                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course4 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                    <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course4 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?>
                                                                        </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_4']; ?>
                    <?php } ?>
                <?php endfor; ?>
                                                                        </td>

                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                        <td style="border:2px dashed <?= $border_color; ?>; background-color:<?= $background_color; ?>; text-align: center; color:<?= $text_color; ?>; font-weight: bold; font-size:130%;">
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>

                                                                </thead>
                                                                <tbody>
                                                                    <tr>


                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_5']) { ?>


                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course5 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                    <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course5 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?>
                                                                        </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_5']; ?>
                                                            <?php } ?>
                                                        <?php endfor; ?>
                                                                        </td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>
            <?php }else { ?>
                <?php //if(date('l', strtotime($inc_date)) != 'Sunday' AND $k==0) { ?>
                                                        <input type="text" value="<?= $inc_date; ?>" style="display:none" name="date[]">
                                                        <td><?= $inc_date; ?></td>
                                                        <input type="text" value="<?= date('l', strtotime($inc_date)); ?>" style="display:none;" name="days[]">
                                                        <td class="text-left"><?= date('l', strtotime($inc_date)); ?></td>
                                                        <td><?= ++$j ?></td>
                                                        <input type="text" value="<?= $j; ?>" style="display:none" name="day_count[]">

                                                        <td style="text-align:center;">
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>
                                                                </thead>
                                                                <tbody>
                                                                    <?php $disable = ""; ?>
                                                                    <?php for ($attendance = 0; $attendance < count($item_result['Attendance_result']); $attendance++): ?>    
                    <?php if ($item_result['Attendance_result'][$attendance]['date'] == $item_result['class_value'][$l]['date'] && $item_result['Attendance_result'][$attendance]['class_1'] != '0') : ?>
                        <?php $disable = "disabled"; ?>
                        <?php break; ?>
                                                                                <?php endif; ?>

                                                                            <?php endfor; ?>

                                                                    <tr>

                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_1']) { ?>


                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course1 = 1; ?>
                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                    <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course1 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?>
                                                                        </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_1']; ?>
                    <?php } ?>
                <?php endfor; ?>
                                                                        </td>

                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>


                                                        <td>
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>
                                                                </thead>
                                                                <tbody>

                                                                    <?php $disable = ""; ?>
                                                                    <?php for ($attendance = 0; $attendance < count($item_result['Attendance_result']); $attendance++): ?>    
                    <?php if ($item_result['Attendance_result'][$attendance]['date'] == $item_result['class_value'][$l]['date'] && $item_result['Attendance_result'][$attendance]['class_2'] != '0') : ?>
                        <?php $disable = "disabled"; ?>
                                                                                    <?php break; ?>
                                                                                <?php endif; ?>

                                                                            <?php endfor; ?>  
                                                                    <tr>

                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_2']) { ?>


                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course2 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                    <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course2 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?>
                                                                        </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_2']; ?>
                    <?php } ?>
                <?php endfor; ?>
                                                                        </td>



                                                                    </tr>
                                                                </tbody>
                                                            </table>

                                                        </td>
                                                        <td>
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>

                                                                </thead>
                                                                <tbody>

                                                                    <tr>

                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>    
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_3']) { ?>


                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course3 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                    <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course3 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?>
                                                                        </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?> 
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_3']; ?>
                    <?php } ?>
                <?php endfor; ?>
                                                                        </td>

                                                                    </tr>    
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                        <td>
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>
                                                                <thead>
                                                                <tbody>

                                                                    <tr>

                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>   
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_4']) { ?>


                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course4 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                                                                                <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course4 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?> </td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_4']; ?> 
                    <?php } ?>
                <?php endfor; ?>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>
                                                        <td>
                                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action">
                                                                <thead>

                                                                </thead>
                                                                <tbody>

                                                                    <tr>



                                                                        <td>  
                                                                            <?php $chekdateinc = 0; ?>
                                                                            <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                                                                                <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>   
                                                                                    <?php for ($course_result = 0; $course_result < count($item_result['course_result']); $course_result++): ?>
                                                                                        <?php if ($this->result['course_result'][$course_result]['course_id'] == $this->result['class_value'][$checkdate]['class_5']) { ?>


                                                                                            <?= $this->result['course_result'][$course_result]['course_code']; ?>
                                                                                            <?php $course5 = 1; ?>

                                                                                        <?php } ?>
                                                                                    <?php endfor; ?>
                                                                                <?php } else { ?>
                                                                                    <?php $chekdateinc++; ?>
                                                                                <?php } ?>
                                                                            <?php endfor; ?>
                                                                            <?php if ($course5 != 1) { ?>
                                                                                <?= "--"; ?>

                                                                            <?php } ?></td>
                                                                        <td class='col-md-4'>
                <?php $chekdateinc = 0; ?>
                <?php for ($checkdate = 0; $checkdate < count($this->result['class_value']); $checkdate++): ?>
                    <?php if ($this->result['class_value'][$checkdate]['date'] == $inc_date) { ?>  
                        <?php if (!empty($this->result['class_value'])) echo $this->result['class_value'][$checkdate]['description_5']; ?>
                    <?php } ?>
                                                        <?php endfor; ?>
                                                                        </td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </td>

            <?php } ?>
                                                <?php $l++; ?>
                                                    </tr>

        <?php endfor; ?>
                                                </tbody>
                                            </table>

    <?php }else { ?>
                                            <table class="my table table-striped table-bordered mb30 jambo_table bulk_action" style="width:100%;" id="dataTable">
                                                <thead>
                                                    <tr>
                                                        <th style="text-align:center;">Date </th>	
                                                        <th style="text-align:center;">Day</th>
                                                        <th style="text-align:center;">Day count</th>
                                                        <th style="text-align:center;">I</th>
                                                        <th style="text-align:center;">II</th>
                                                        <th style="text-align:center;">III</th>
                                                        <th style="text-align:center;">IV</th>
                                                        <th style="text-align:center;">V</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td colspan="8" style='text-align: center;'> <?= 'no data found'; ?></td>
                                                    </tr>
                                                </tbody>
                                            </table>
    <?php } ?>





                                    </div>
                                </div>

                                            <?php //print_r($this->result);exit;     ?>


                                <div class="panel-footer">									
                                    <div class="row">
                                        <div class="col-sm-7 col-sm-offset-5">

    <?php if ($this->type == 'add') { ?>
                                              <!--  <div style="float:left;margin-right:2px;">

                                                    <button class="btn btn-primary submit" id="btn" name="Add" >Submit</button>
                                                </div>-->
                                                <div style="float:left;margin-right:2px;">
                                                    <button class="btn btn-primary submit" id="publish" onclick ="return ConfirmDelete('Are you sure you want to publish this ?');" name="publish" >Publish</button>
                                                </div>
                                                <div style="float:left;padding:0px 10px;">
                                                    <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                                </div>
                                            <?php } else { ?>
                                                <div style="float:left;">
                                                    <!--<button class="btn btn-primary submit">Update</button> -->
                                                </div>
                                                <div style="float:left;">
                                                <!--<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>evaluation-components/index">Back</a>-->
                                                </div>
    <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div><!-- /panel -->
                </div><!-- /.col-->				
            </div><!-- /.row -->
        </div>	
        <!-- /.padding-md -->	
<?php } else { ?>

            <?php
            if (count($this->messages)) {
                foreach ($this->messages as $message) {
                    ?>
                <div class="alert alert-success ">
                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
                </div>
            <?php
        }
    }
    ?>
        <!-- widget grid -->
        <div class="">
            <div class="">
                <div class="row">

                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars"> Interactive Learning Sessions</i>

                        </h3>
                    </div>
                    <?php
                    if (in_array($this->role_id, $this->administrator_role)) {
                        ?>	
                        <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                            <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>batch-schedule/index/type/add">Add </a>
                        </div>
        <?php
    }
    ?>
                </div>

                <div class="x_panel">

                    <div class="x_title">
                        <h2>Interactive Learning Sessions</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            </li>
                            <li><a class=""><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="padding-md clearfix">
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
                                <thead>
                                    <tr>
                                        <th>S.  No.</th>	
                                        <th>Batch Code</th>
                                        <th>Terms</th>
                                        <th>Version No</th>
                                        <th>Updated Date</th>
                                        <th>Action</th>
                                        <!--<th>View</th>-->
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    // print_r($this->paginator);exit;
                                    $i = 0;
                                    $pagination_tr = '';
                                    if (count($this->paginator) != 0) {

                                        foreach ($this->paginator as $results) {
                                            ?>
                                        <td><?= ++$i; ?></td>
                                        <td><?= $results['short_code']; ?></td>
                                        <td><?= $results['term_name']; ?></td>
                                        <td><?= $results['publish']; ?></td>
                                        <td><?= $results['updated_date']; ?></td>
                                        <td><a href="<?php echo $this->mainconfig['host']; ?>batch-schedule/index/type/edit/id/<?php echo $results['batch_schedule_id']; ?>/version/<?= $results['publish']; ?>" class="edit" title="Edit">View</a></td>
                                        <!--<td><a class="component_view" id="<?php //echo $results['ec_id'];  ?>"> View</a></td>-->

                                        </tr>            

            <?php
        }
        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
    }
    ?>

                                </tbody>
                            </table>
        <?php echo $pagination_tr; ?>
                        </div><!-- /.padding-md -->
                    </div><!-- /panel -->
                </div>
            </div>
        </div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>

    $(document).ready(function () {

        $('#version_id-label').css("display", "none");
        $('#Academic_id-label').css("display", 'none');
        $('#Term_id-label').css("display", 'none');
    });



//automaticaly fired
    if ($('#Academic_id').val()) {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
            data: {academic_year_id: $('#Academic_id').val()}
        }).done(function (data) {

            $('#Term_id').empty('');
            $('#Term_id').html(data);
            $('#Term_id').val("<?php echo $_SESSION['myVal']['term_id']; ?>");
            $('#section').val("<?= $_SESSION['myVal']['section'];?>");
            getVersion($('#Academic_id').val(), $('#Term_id').val(),$('#section').val())
        });
    }

    //set version automaticaly
    function getVersion(academic_id, term_id, section) {

        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-get-version'; ?>',
            data: {academic_year_id: academic_id, term_id: term_id,section : section}
        }).done(function (data) {
            //alert(data);
            $('#version_id').empty('');
            $('#version_id').html(data);
            $('#version_id').val("<?php echo $_SESSION['myVal']['version_id']; ?>");

            $curr_date = '<?= date("Y-m-d"); ?>';
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-get-batch-scedule-sessions'; ?>',
                data: {term_id: $('#Term_id').val(), version: $('#version_id').val(), batch_id: $('#Academic_id').val(), start_date: $("#from_date").val(), end_date: $("#to_date").val(),section:$('#section').val()}
            }).done(function (data) {
                json_obj = JSON.parse(data);
                $('#grade_data').append('<div class="col-md-12 col-xs-12 table-responsive"><div class="page-header text-center"><h2><strong>Selected Sessions</strong></h2></div><table class="table table-striped table-bordered mb30 jambo_table bulk_action"><thead><tr id="session_head"><th>Courses</th></tr></thead><tbody><tr id="session_body"><th>Sessions</th></tr></tbody></table></div>');
                for (x in json_obj) {
                    if (json_obj[x].course_count != null) {
                        $('#session_head').append('<th>' + json_obj[x].course_code + '</th>');
                    }
                }
                for (x in json_obj) {
                    if (json_obj[x].course_count != null) {
                        $('#session_body').append('<td>' + json_obj[x].course_count + '</td>');
                    }
                }
                //  $('#grade_data').html(text);
            });
        })
    }




    $("#academic_year_id").change(function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#term_id').empty('');
                $('#term_id').html(data);
            })
        }
    });




    $("#Academic_id").change(function () {
        var academic_id = $('#Academic_id').val();
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#Term_id').empty('');
                $('#Term_id').html(data);
            })
        }
    });





    $("#Term_id").change(function () {
        var term_id = $('#Term_id').val();
        var academic_id = $('#Academic_id').val()
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-get-version'; ?>',
                data: {academic_year_id: academic_id, term_id: term_id}
            }).done(function (data) {
                //alert(data);
                $('#version_id').empty('');
                $('#version_id').html(data);
            })
        }
    });
    
    $("#term_id").change(function () {
        var term_id = $('#term_id').val();
        if (term_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-get-section'; ?>',
                data: {term_id: term_id}
            }).done(function (data) {
             //   alert(data);
               $('#section').empty('');
                $('#section').html(data);
            })
        }
    });




    function ConfirmDelete($data)
    {
        var x = confirm($data);
        if (x)
            return true;
        else
            return false;
    }
    $("#cc_name").change(function () {

        var course_name = $('#cc_name').val();
        //alert(coursename);
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/get-course-category'; ?>',
            data: {course_name: course_name}
        }).done(function (data) {

            if ((data != '')) {
                alert("This Course Name Exists");
                $("#cc_name").val("");
            }
        });
    });




    $('body').on('change', '#department_id', function () {
        var department_id = $('#department_id').val();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'evaluation-components/ajax-get-employee'; ?>',
            data: {department_id: department_id}
        }).done(function (data) {

            $('#employee_id').empty('');
            $('#employee_id').html(data);

        })
    })
    $("body").on("click", ".removeclass", function (e) {//alert('sdsd');
        $(this).parent('div').remove();
        return false;
    });

    $('body').on('change', '#academic_year_id', function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $('#batch').show();
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch-code'; ?>',
                data: {academic_id: academic_id}
            }).done(function (data) {
                var result = $.parseJSON(data);
                if ((data != '')) {
                    $('#batch').val(result['short_code']);
                }
            });
        }

    });




    var academic_id = $('#academic_year_id option:selected').val();
    if (academic_id) {
        $('#batch').show();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch-code'; ?>',
            data: {academic_id: academic_id}
        }).done(function (data) {
            var result = $.parseJSON(data);
            if ((data != '')) {
                $('#batch').val(result['short_code']);
            }
        });
    } else {
        $('#batch').hide();
    }

    $("#section").change(function () {
    <?php if($this->type != 'edit'){ ?>
        var id = $(this).attr("id");
        $('#grade_data>img').remove();
        $('#grade_data').prepend('<img class="col-md-offset-5"  src="<?php echo $this->mainconfig['publicpath'];?>/images/loader.gif" width="200px"  class="loder_img1" />');
        $('.loder_img1').attr('style','display:block;');
        $("#item_details").attr('style','display:none')
        
        
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-schedule-components-view'; ?>",
            data: {batch_id: $("#academic_year_id").val(),
                term_id: $("#term_id").val(),
            section: $("#section").val()}
        }).done(function (data) {
            $(".sub").hide();
            $('.loder_img1').attr('style','display:none;');
            $('#grade_data>img').remove();
            $("#item_details").html(data);
            $("#item_details").attr('style','display:block')
        });
        <?php } ?>
    });





    function ajaxfunction(term_id, batch_id) {

        var id = $(this).attr("id");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-evaluation-components-view'; ?>",
            data: {batch_id: batch_id,
                term_id: term_id}
        }).done(function (data) {
            $(".sub").hide();
            $('#item_details').empty('');
            $("#item_details").html(data);
            $("#academic_year_id").val(batch_id);
            $("#term_id").val(term_id);

            window.scrollTo(0, 500);
            if ($('#academic_year_id').val()) {
                if ($('#term_id').val()) {
                    $.ajax({
                        type: "POST",
                        url: '<?php echo $this->mainconfig['host'] . 'attendance/ajax-get-course-new'; ?>',
                        data: {academic_year_id: $('#academic_year_id').val(), term_id: $('#term_id').val()}
                    }).done(function (data) {
                        $('#new_div').remove();
                        $('#new_div1').remove();

                        var json_obj = JSON.parse(data);
                        $('#grade_data').append('<div id="new_div"class="col-md-12 col-xs-12 table-responsive"><div class="page-header text-center"><h2><strong>Selected Sessions</strong></h2></div><table class="table table-striped table-bordered mb30 jambo_table bulk_action"><thead><tr id="session_head"><th>Courses</th></tr></thead><tbody><tr id="session_body"><th>Sessions</th></tr></tbody></table></div>');
                        i = 0;
                        for (x in json_obj) {
                            $('#session_head').append('<th>' + json_obj[x].course_code + '</th>');
                            i++
                        }
                        i = 0;
                        for (x in json_obj) {
                            $('#session_body').append('<td id="course1_' + i + '" data-id="' + json_obj[x].course + '">0</td><th style="display:none"></th>');
                            i++
                        }


                        $('#f_div').append('<div id="new_div1"class="col-md-12 col-xs-12 table-responsive"><div class="page-header text-center"><h2><strong>Selected Sessions</strong></h2></div><table class="table table-striped table-bordered mb30 jambo_table bulk_action"><thead><tr id="session_head"><th>Courses</th></tr></thead><tbody><tr id="session_body"><th>Sessions</th></tr></tbody></table></div>');
                        i = 0;
                        for (x in json_obj) {
                            $('#session_head').append('<th><input name="course_code[]" style="display:none;" value="' + json_obj[x].course_code + '"/>' + json_obj[x].course_code + '</th>');
                            i++
                        }
                        i = 0;
                        for (x in json_obj) {
                            $('#session_body').append('<td id="course_' + i + '" data-id="' + json_obj[x].course + '">0</td><th style="display:none"><input name="course_count[]" value="0"/></th>');
                            i++
                        }


                        $.ajax({
                            type: "POST",
                            url: '<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-get-batch-scedule-sessions1'; ?>',
                            data: {term_id: $('#term_id').val(), batch_id: $('#academic_year_id').val()}
                        }).done(function (data) {

                            json_obj = JSON.parse(data);

                            for (x in json_obj) {

                                for (i = 0; i < $('#session_head th').length; i++) {
                                    if (x == $('#course_' + i).data('id')) {
                                        $('#course_' + i).empty();
                                        if (json_obj[x].course_count != null) {
                                            $('#course_' + i).text(json_obj[x].course_count);
                                            $('#course_' + i).next('th').children("input").attr('value', json_obj[x].course_count);
                                        } else {
                                            $('#course_' + i).text(0);
                                            $('#course_' + i).next('th').children("input").attr('value', '0');
                                        }
                                    }
                                }


                            }
                        });

                    });
                }
            }


        });

    }




    $("#version_id").change(function () {
        var term_id = $('#Term_id').val();
        var academic_id = $('#Academic_id').val();
        var version_id = $("#version_id").val();
        var id = $(this).attr("id");



        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-batch-schedule-view'; ?>",
            data: {batch_id: academic_id,
                term_id: term_id, version_id: version_id,section:$('#section').val()}
        }).done(function (data) {
            $('#item_details').empty('');
            $("#grade_data").html(data);


            $curr_date = '<?= date("Y-m-d"); ?>';
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-get-batch-scedule-sessions'; ?>',
                data: {term_id: $('#Term_id').val(), version: $('#version_id').val(), batch_id: $('#Academic_id').val(), start_date: $("#from_date").val(), end_date: $("#to_date").val()}
            }).done(function (data) {
                json_obj = JSON.parse(data);
                var text = '';
                $('#grade_data').append('<div class="col-md-12 col-xs-12 table-responsive"><div class="page-header text-center"><h2><strong>Selected Sessions</strong></h2></div><table class="table table-striped table-bordered mb30 jambo_table bulk_action"><thead><tr id="session_head"><th>Courses</th></tr></thead><tbody><tr id="session_body"><th>Sessions</th></tr></tbody></table></div>');
                for (x in json_obj) {
                    if (json_obj[x].course_count != null) {
                        $('#session_head').append('<th>' + json_obj[x].course_code + '</th>');
                    }
                }
                for (x in json_obj) {
                    if (json_obj[x].course_count != null) {
                        $('#session_body').append('<td>' + json_obj[x].course_count + '</td>');
                    }
                }
            });
        });
    });

    $('#publish').click(function () {
        $('#submit_type').val('publish');
    });
    $('#btn').click(function () {
        $('#submit_type').val('add');
    });


</script>

<script>
    $(document).ready(function () {
        $("#from_date").datepicker({dateFormat: 'dd/mm/yy'});
        $("#to_date").datepicker({dateFormat: 'dd/mm/yy'});
        
        $("#formValidate1").click(function () {
            var term_id = $('#Term_id').val();
            var batch_id = $('#Academic_id').val();
            var version_id = $('#version_id').val();
            var form_date = $("#from_date").val();
            var to_date = $("#to_date").val();
            var varDate = new Date(form_date);
            var varDate1 = new Date(form_date);
            if (term_id !== '' && batch_id !== '' && version_id !== '' && form_date !== '' && to_date !== '') {

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-batch-schedule-view'; ?>',
                    data: {
                        term_id: term_id,
                        batch_id: batch_id,
                        version_id: version_id,
                        start_date: form_date,
                        end_date: to_date,
                    section :  $('#section').val()}
                }).done(function (data) {

                    $('#item_details').empty('');
                    $('#grade_data').html(data);


                    $.ajax({
                        type: "POST",
                        url: '<?php echo $this->mainconfig['host'] . 'batch-schedule/ajax-get-batch-scedule-sessions'; ?>',
                        data: {term_id: $('#Term_id').val(), version: $('#version_id').val(), batch_id: $('#Academic_id').val(), start_date: $("#from_date").val(), end_date: $("#to_date").val(),section : $('#section').val()}
                    }).done(function (data) {
                        json_obj = JSON.parse(data);
                        var text = '';
                        $('#grade_data').append('<div class="col-md-12 col-xs-12 table-responsive"><div class="page-header text-center"><h2><strong>Selected Sessions</strong></h2></div><table class="table table-striped table-bordered mb30 jambo_table bulk_action"><thead><tr id="session_head"><th>Courses</th></tr></thead><tbody><tr id="session_body"><th>Sessions</th></tr></tbody></table></div>');
                        for (x in json_obj) {
                            if (json_obj[x].course_count != null) {
                                $('#session_head').append('<th>' + json_obj[x].course_code + '</th>');
                            }
                        }
                        for (x in json_obj) {
                            if (json_obj[x].course_count != null) {
                                $('#session_body').append('<td>' + json_obj[x].course_count + '</td>');
                            }
                        }
                    });
                })
            }
        });
    });

    $('#print').click(function () {
        window.print('#grade_data');
    });

</script>
