<style>

    @media print {

                    table td:nth-child(5)

                     {

                         display:none;

                     }

                     table th:nth-child(5)

                     {

                         display:none;

                     }

                      *{

                        visibility:hidden;

                     }

                     table,th,td 

                     {

                         visibility:visible;                    

                     } 

                     .title1

                     {

                        visibility:visible; 

                     }

                }
                

    .ui-datepicker-calendar {
    display: none;
    }
    .dataTable  tbody {
    width: 100%;
    
}

#component_paper_chosen{
    display:none;
}

</style>

<div class="right_col">

    <?php if ($this->type) { ?>

        <div class="padding-md">

            <div class="row">

                <div class="col-md-12 " >

                    <h3 class="page-title txt-color-blueDark" >

                        <div><i class="fa fa-eye">Razor Pay:</i></div>

                    </h3>

                    <div class="panel panel-default">

                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >



                            <div class="panel-body">

                                <div class="row">



                                    <div class="col-sm-2 employee_class">

                                        <div class="form-group" >

                                            <label  class="control-label" >Degree

                                            <span class="asterisk">*</span></label>

                                            <?php echo $this->form->degree_id; ?>

                                        </div>

                                    </div>
                                    <div class="col-sm-4 employee_class">

                                        <div class="form-group" >

                                            <label  class="control-label" >From Semester

                                            <span class="asterisk">*</span></label>

                                            <?php echo $this->form->semester; ?>

                                        </div>

                                    </div>

                                    <div class="col-sm-4">

                                        <div class="form-group">

                                            <label  class="control-label" >To Semester

                                            <span class="asterisk">*</span></label>

                                           <?php echo $this->form->nextSem; ?>

                                        </div>

                                    </div>

                                    

                                    <div class="col-sm-2">

                                        <div class="form-group">

                                            <label  class="control-label" >Minimum Credit(%)

                                                <span class="asterisk">* </span></label>

                                              

                                            <?php echo $this->form->credit_score; ?>

                                            <span id="credit_error" style="color:red;"></span>

                                        </div>

                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-sm-4">

                                        <div class="form-group">

                                            <label  class="control-label" >Passed in No. of papers

                                                <span class="asterisk">*</span></label>

                                            <?php echo $this->form->semester_paper_count; ?>

                                        </div>

                                    </div>

                                    <div class="col-sm-4">

                                        <div class="form-group">

                                            <label  class="control-label" >Must appear in no. of papers

                                                <span class="asterisk">*</span></label>

                                            <?php echo $this->form->appeared_paper; ?>

                                        </div>

                                    </div>

                                    <div class="col-sm-4">

                                        <div class="form-group">

                                            <label  class="control-label" >Appear in Components (paper)

                                                <span class="asterisk">*</span></label>

                                            <?php echo $this->form->component_paper; ?>

                                        </div>

                                    </div>

                                </div>

                            </div>

                            <div>

                                <div class="panel-footer">									

                                    <div class="row">

                                        <div class="col-sm-7 col-sm-offset-5">

                                            <?php if ($this->type == 'add') { ?> 

                                                <div style="float:left;margin-right:2px;">

                                                    <button class="btn btn-primary submit">Submit</button>

                                                </div>

                                                <div style="float:left;padding:0px 10px;">

                                                    <button type="reset" class="btn btn-danger btn-default">Reset</button>

                                                </div>

                                            <?php } else { ?>

                                                <div style="float:left;">

                                                    <button class="btn btn-primary submit">Update</button>

                                                </div>

                                                <div style="float:left;">

                                                    <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>promotion/index/">Back</a>

                                                </div>

                                            <?php } ?>

                                        </div>

                                    </div>

                                </div>

                            </div>

                        </form>

                    </div><!-- /panel -->

                </div><!-- /.col-->				

            </div><!-- /.row -->



        </div><!-- /.padding-md -->	

    <?php } else { ?>



        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Razor Pay </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 



<!--                        <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>promotion/index/type/add">Add </a>-->

                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Payment Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                            

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;">S. No.</th>	
                                        <th style="text-align:center;">Applicant Number</th>
                                        
                                        <th style="text-align:center;">Applicant Name</th>
                                        
                                        <th style="text-align:center;">Payment Id</th>

                                        <th style="text-align:center">Amount</th>

                                        <th style="text-align:center">Currency</th>

                                        <th style="text-align:center">Fee</th>
                                        
                                        <th style="text-align:center">Course</th>
                                        
                                        <th style="text-align:center">Status</th>
                                        <th style="text-align:center">Payment Method</th>
                                        
                                        <th style="text-align:center">description</th>
                                        <th style="text-align:center">Card id</th>
                                        <th style="text-align:center">Card issuer</th>
                                        <th style="text-align:center">Card Type</th>
                                        <th style="text-align:center">Card  Network</th>
                                        <th style="text-align:center">Card  Number</th>
                                        <th style="text-align:center">Bank</th>
                                        <th style="text-align:center">VPA</th>
                                        <th style="text-align:center">Email</th>
                                        <th style="text-align:center">contact</th>
                                        <th style="text-align:center">Tax</th>
                                        <th style="text-align:center">Error Ccode</th>

                                        <th class="no_print" style="text-align:center">Edit | Delete</th>



                                    </tr>

                                </thead>

                                <tbody style="text-align:center;">

                                    <?php

                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {

                                            //print_r($results);die;

                                            ?>

                                            <tr>

                                                <td><?php

                                                    echo $i;



                                                    $i++;

                                                    ?>

                                                </td>	
                                                <td><?php echo $results['applicant_id'];?></td>

                                                <td><?=$results['name']; ?></td>

                                                <td><?php echo $results['id'];?></td>

                                                <td><?php echo $results['amount']/100; ?></td>
                                                <td><?php echo $results['currency'];?></td>

                                                <td><?php echo $results['fee']/100; ?></td>
                                                <td><?php echo $results['course'];?></td>

                                                <td><?php echo $results['status']; ?></td>
                                                <td><?php echo $results['method']; ?></td>
                                                <td><?php echo $results['description'];?></td>

                                                <td><?php echo $results['card_id']; ?></td>
                                                <?php 
                                                $cad = new Application_Model_Razorcard();
                                                if($results['card_id']){
                                                
                                                    $cadetails = $cad->getRecordById($results['card_id']);
                                                    
                                                        $results['issuer'] = $cadetails['issuer'];
                                                        $results['type'] = $cadetails['type'];
                                                        $results['network'] = $cadetails['network'];
                                                        $results['last4'] = $cadetails['last4'];
                                                        
                                                        
                                                        
                                                }
                                                ?>
                                                <td><?php echo $results['issuer']; ?></td>
                                                <td><?php echo $results['type']; ?></td>
                                                <td><?php echo $results['network']; ?></td>
                                                <td><?php if($results['last4']){echo "xxxx xxxx xxxx ".$results['last4'];} ?></td>
                                                <td><?php echo $results['bank']; ?></td>
                                                <td><?php echo $results['vpa']; ?></td>
                                                <td><?php echo $results['email'];?></td>

                                                <td><?php echo $results['contact']; ?></td>
                                                <td><?php echo $results['tax']; ?></td>
                                                <td><?php echo $results['error_code']; ?></td>

                                                <td><a href="<?php echo $this->mainconfig['host']; ?>promotion/index/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>promotion/index/type/delete/id/<?php echo $results['id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->		

<?php } ?>

</div>

<script>



</script>

