<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
    <thead>
        <tr>
            <th style="text-align:center;" >S.No.</th>
            <th style="text-align:center;" >Batch</th>
            <th style="text-align:center;" >Term</th>
            <th style="text-align:center;" >Section Name</th>
            <th style="text-align:center;" >Status</th>
            <th class="no_print" style="text-align:center;" >Action</th>
        </tr>
    </thead>
    <tbody style="text-align:center;" >
        <?php
        $i = 1;
        $pagination_tr = '';
        if (count($this->paginator) != 0) {

            foreach ($this->paginator as $results) {
                //print_r($results);die;
                ?>
                <tr>
                    <td><?php
                        echo $i;

                        $i++;
                        ?>
                    </td>
                    <td><?php echo $results['short_code']; ?></td>
                    <td><?php echo $results['term_name']; ?></td>
                    <td><?php echo $results['name'] ?></td>
                    <td><?php echo $results['status'] == 0 ? 'Active' : 'Deactive'; ?></td>
                    <td><a href="<?php echo $this->mainconfig['host']; ?>master/section/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a><!--&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/corecourselearning/type/delete/id/<?php // echo $results['ccl_id'];    ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a>--></td>

                </tr>            

                <?php
            }
            $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
        }
        ?>

    </tbody>
</table>
<?php echo $pagination_tr; ?>

<script>
setDatatables();
</script>