<div class="col-md-12">
<?php //echo '<pre>'; print_r($this->paginator);exit; ?>
    <div class="table-responsive" id="studentData"> 
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">
            <thead>
                <tr>
                    <th>Batch</th>
                    <th>Credits</th>

                </tr>
            </thead>
           
            <tbody>
                <?php foreach ($this->paginator as $key => $value) { ?>
                   
                <tr>					
                    <td><?php echo $value['short_code']; ?></td>
                    <td>  <input type="text" name="credit_number[]" class="form-control" value="4" /> </td>
                    <input type="hidden" name="academic_id[]" value="<?= $value['academic_id'] ?>" />
                <tr>
                <?php }?>

            </tbody>
            
        </table>
    </div>
</div>
