<div class="col-md-12">
<?php //echo '<pre>'; print_r($this->paginator);exit; ?>
    <div class="table-responsive" id="studentData"> 
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  >
            <thead>
                <tr>
                    <th>Department</th>
                    <th>Course Code</th>
                    <th> cc Name </th>
                    <th> Semester </th>
                    <th>Credit Value</th>
                    <th> Countable(YES/NO)</th>
                    <th>Course Name </th>
                    <th>Remove</th>
                </tr>
            </thead>
           
            <tbody>
                <?php 
                //echo '<pre>';print_r($this->paginator);exit;
                foreach ($this->paginator as $key => $value) { ?>
                   
                <tr>
                    <td><?php echo $value['department']; ?></td>					
                    <td><?php echo $value['course_code']; ?></td>
                    <input type="hidden" name="course_id[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['course_id'] ?>" />
                    <input type="hidden" name="term_id[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['term_id'] ?>" />
                    <input type="hidden" name="course_code[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['course_code'] ?>" />
                    <input type="hidden" name="cc_id[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['cc_id'] ?>" />
                    <input type="hidden" name="credit_id[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['credit_id'] ?>" />
                    <input type="hidden" name="re_credit[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['re_credit'] ?>" />
                    <input type="hidden" name="ge_id[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['ge_id'] ?>" />
                    <input type="hidden" name="count_id[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['count_id'] ?>" />
                    <input type="hidden" name="degree_id[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['degree_id'] ?>" />
                    <input type="hidden" name="cmn_terms[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['cmn_term'] ?>" />
                     <input type="hidden" name="department[<?= $value['department_id'] ?>][<?= $value['cmn_term'] ?>][]" value="<?= $value['department'] ?>" />
                    <td><?php echo $value['cc_name']; ?></td>
                    <td><?php echo $value['term_description']; ?></td>
                    <td><?php echo $value['credit_value']; ?></td>
                    <td><?php if($value['count_id'] == 0)echo 'YES';else echo 'NO'; ?></td>
                    <td><?php echo $value['course_name']; ?></td>
                    <td style="color:red;font-size:2em; cursor:pointer; text-align:center; vertical-align:center;" class="removecell" ><i class="fa fa-remove"></i></td>
                <tr>
                <?php }?>

            </tbody>
            
        </table>
    </div>
</div>
<script>
    $('.removecell').click(function(){
       $(this).parent().remove();
    });
</script>