<?php 
//echo "<pre>";print_r( $this->academicresult);die;
?>
<style type="text/css">
    .dd_faculty_list{
        padding-top: 10px;
        font-weight: bold;
    }
    .select2-container{
	z-index: 999;
}

span.select2-container{
  width: 20em !important;  
}
</style>    
<div style="overflow-x:scroll">
<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
			
			
				<thead >
					<tr >
					
                                            <th style="width:10%;">Course Category </th>
                                            <th style="text-align:center;width:14%;">Course/Paper Name </th>
                                            <th style="text-align:center;width:10%;">Course/Paper Code </th>
                                            <th style="text-align:center;width:22%;">HOD</th>
                                            <th style="text-align:center;width:15%;">Faculty</th>
                                         
					</tr>
				</thead>
                                <tbody>
                                <?php if(!empty($this->paginator)){
                                $i = 1;
                                $disable_co_faculty = false;
                                $isfaculty = false;
                                
                                foreach($this->paginator as $key=> $result){ 
                                //  print_r($this->item_result[$key]['faculty_id']); die();
                                  
                              
                            ?>
                            <tr>
                            
                            <td><?php //echo $val['cc_name'];?>Addon Course
                                <input type="hidden" value="Addon Course" name="course_category">
                                <input type="hidden" value="<?php echo $result['course_name'];?>" name="course_name[]">
                                <input type="hidden" value="<?php echo $result['course_id'];?>" name="course_id[]">
                                <input type="hidden" value="<?php echo $result['course_code'];?>" name="course_code[]">
                                <input type="hidden" value="<?php echo $result['addon_course_id'];?>" name="addon_course_id">
                            </td>
                            <td><?php echo $result['course_name'];?></td>
                           <td><?php echo $result['course_code'];?></td>
                            <td><select data-si-no="<?php echo $i;?>" id="employee_name<?php echo $i;?>"  name="employee_id[]"
                               class="form-control faculty_list_dd" 
                              <?php if($disable_co_faculty){echo 'disabled = "disabled"';} ?>>
					<option value="">Select</option>
                        <?php  foreach($this->hod as $e=>$emp){
                                    $selected = '';
                            if($e == $this->item_result[$key]['employee_id']){ $selected = "selected"; }?>
                                <option value="<?php echo $e;?>" <?php echo $selected; ?>><?php echo $emp;?></option>
                                            <?php } 
                                            //$faculty_ids = explode(',', $existed_result['faculty_id']);
                                            ?>
                                       </select>
                                 
                            </td>
                        <td>   
                            <?php
                                $selected_faculty = array();
                            ?>
                <select multiple="multiple" id="faculty_name" name="faculty_id[]" class="form-control f-list">
                            <option value="">Select</option>
                            
                                <?php   
                                $visiting_ids = explode(',', $this->item_result[$key]['faculty_id']);
                                
                                foreach($this->employee as $em=>$empe){
                                        $selected = '';
                                    if(in_array($em, $visiting_ids)){
                                            $selected = "selected";
                                            $selected_faculty[] = $empe;
                                    }?>
                                    <option value="<?php echo $em;?>" <?php echo $selected; ?>><?php echo $empe;?></option>
                                <?php } 
                                    
                                ?>
                            </select>
                        </td>
                    </tr>
									   
									  
                    <?php
                        $isfaculty = FALSE;
                        $disable_co_faculty = false;
                        $i++; 
                    }

                   }
 ?>
								
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
</div>	
		
<script>
$('#formValidate1').submit(function() {
      $('select').attr('disabled',false);
});
function select_department(value,num){
	var department_name = value;
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-department-name';?>',
			data: {department_name:department_name}
			
		}).done(function( data ) {
			
				
			$('#employee_name'+num+'').empty('');
			$('#employee_name'+num+'').append(data);
			
		
			
		 });
}
		/*$("#department_name").change(function(){
	
	
	var department_name=$('#department_name').val();
	//alert(department_name);
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-department-name';?>',
			data: {department_name:department_name}
			
		}).done(function( data ) {
			
				
			$('#employee_name').empty('');
			$('#employee_name').append(data);
			
		
			
		 });
}); */
    
    $('.faculty_list_dd').change(function(){
        //saving the default value        
        var si_no = $(this).data('si-no');
        var batch_id = $('#academic_year_id').val();
        var term_id = $('#term_id'+si_no).val();
        var course_id = $('#course_id'+si_no).val();
        var faculty_id = $('#default-emp'+si_no).val();
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'master/ajax-is-grade-allocated';?>',
                data: {batch_id:batch_id,term_id: term_id, course_id: course_id, faculty_id: faculty_id}

        }).done(function( data ) {
                if(data == 1){
                    $('#employee_name'+si_no).val(faculty_id);
                    alert("Grade is already generated. First, delete the grade before editing it.")
                }
                    
         });
    });
    $(document).ready(function(){
    /*
        $("select.vf-list, select.f-list").change(function(){
            //var el = $(e+" option:selected");
            var op_list = $( this ).find("option:selected");
            var str = "";
            $( op_list ).each(function() {                
               str += $( this ).text() + "<br/>";
            });
            $( this ).next('div').html( str );
            //var selectedCountry = $(".vf-list option:selected").val();
            //alert("You have selected the country - " + selectedCountry);
        });
        */
        $('select.vf-list, select.f-list').select2();
    });
</script>