 <div class="col-md-12">
                   
                   <div class="table-responsive" id="studentData"> 
                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">
                            <thead>
                                <tr>
                                    <th class="no-sort">S.No.</th>
                                    <th>Student Name</th>
                                    <th>Father Name</th>
                                    <th>UID</th>
                                    <th>Roll No.</th>
                                    <th>Email Id</th>
                                    <th>Mobile No.</th>
                                    <th>Action</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                               
                              
                                        if(!empty($this->resultData)){
                                            
                                        
                                      //echo"<pre>";print_r($this->resultData);exit;
                                        ?>
                                        <tr>
                                          
                                            <td><?php echo '1'; ?></td>						

                                            <td><?php echo $this->resultData['studentName']; ?></td>
                                            <td><?php echo $this->resultData['FatherName']; ?></td>
                                            <td><?php echo $this->resultData['stu_id']; ?></td>
                                            <td><?php echo $this->resultData['roll_no']; ?></td>
                                            <td><?php echo $this->resultData['stu_email_id']; ?></td>
                                            <td><?php echo $this->resultData['stu_mobileno']; ?></td>
                                            <td style="text-align:center" ><a href="<?php echo $this->mainconfig['host']; ?>master/update-mobile/type/edit/id/<?php echo $this->resultData['student_id'] ?>" <span class="fa fa-edit fa-lg"></span></td>
                                        </tr>            

                                    <?php
                                  
                                    }else{?>
                            <td colspan="7"><b style="text-align: center;">Oop's..! Form id not exists. </b></td>
                                    <?php }
                               
                                ?>

                            </tbody>
                        </table>
                    </div>
                </div>
       