 <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">

                                <thead>

                                    <tr>

                                        <th>S.  No.</th>												

                                       <th>Academic Year</th>
                                       <th>Addon Course</th>
                                       <th class="no_print">Action</th>

                                    </tr>

                                </thead>

                                <tbody>

    <?php
    $i = 1;

    $pagination_tr = '';

    if (count($this->paginator) != 0) {



        foreach ($this->paginator as $results) {

            //print_r($results);die;
            ?>

                                            <tr>

                                                <td><?php echo $i;



                                $i++;
            ?>

                                                </td>						



                                                 <td><?php echo $results['academic_year']; ?></td>

                                                <td><?php echo $results['name']; ?></td>

                                                <td><a href="<?php echo $this->mainconfig['host']; ?>master/addonemployeeallotment/type/edit/id/<?php echo $results['addon_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>

                                                    <?php
                                                    if (in_array($this->role_id, $this->administrator_role)) {
                                                        ?><!--

                                                                                    &nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/employeeallotment/type/delete/id/<?php echo $results['ea_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a>-->

                <?php
            }
            ?>

                                                </td>





                                            </tr>            



        <?php
        }

        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
    }
    ?>



                                </tbody>

                            </table>

    <?php echo $pagination_tr; ?>
<script>
    setDatatables();
    </script>