 <div class="col-md-12">
                   
                   
                                <?php
                                        if(!empty($this->resultData['roll_no'])) {?>
                                          <div class="table-responsive" id="studentData"> 
                                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">
                                                <thead>
                                                    <tr>
                                                        <th class="no-sort">S.No.</th>
                                                        <th>Applicant Name</th>
                                                        <th>Form Id</th>
                                                        <th>Email Id </th>
                                                        <th>Phone Number</th>
                                                        <th>Course </th>
                                                        <th>Roll No </th>
                                                        <th>Status </th>

                                                    </tr>
                                                </thead>
                                                <tbody>
                                            <td><?php echo '1'; ?></td>						
                                            <td><?php echo $this->resultData['applicant_name']; ?></td>
                                            <td><?php echo $this->resultData['form_id']; ?></td>
                                            <td><?php echo $this->resultData['email_id']; ?></td>
                                            <td><?php echo $this->resultData['phone']; ?></td>
                                            <td><?php echo $this->resultData['course']; ?></td>
                                            <td><?php echo $this->resultData['roll_no']; ?></td>
                                            <td><b> Roll number is assigned</b></td>
                                        <?php }else
                              
                                        if(!empty($this->resultData)) { ?>
                                        <div class="table-responsive" id="studentData"> 
                                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">
                                            <thead>
                                                <tr>
                                                    <th class="no-sort">S.No.</th>
                                                    <th>Applicant Name</th>
                                                    <th>Application Number</th>
                                                    <th>Form Id</th>
                                                    <th>Email Id </th>
                                                    <th>Phone Number</th>
                                                    <th>Course </th>
                                                    <th>Payment Mode </th>
                                                    <th>Action</th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                        <tr>
                                          
                                            <td><?php echo '1'; ?></td>						
                                            <td><?php echo $this->resultData['applicant_name']; ?></td>
                                            <td><?php echo $this->resultData['application_no']; ?></td>
                                            <td><?php echo $this->resultData['form_id']; ?></td>
                                            <td><?php echo $this->resultData['email_id']; ?></td>
                                            <td><?php echo $this->resultData['phone']; ?></td>
                                            <td><?php echo $this->resultData['course']; ?></td>
                                            <td><?php echo $this->resultData['payment_mode']; ?></td>
                                            <td style="text-align:center" ><a href="<?php echo $this->mainconfig['host']; ?>master/update-offline-applicant-info/type/edit/id/<?php echo $this->resultData['id'] ?>" <span class="fa fa-edit fa-lg"></span></td>
                                        </tr>            

                                    <?php
                                  
                                    }else{?>
                                        <td colspan="7"><b style="text-align: center;">Oop's..! Form id not exists. </b></td>
                                    <?php }
                               
                                ?>

                            </tbody>
                        </table>
                    </div>
                </div>
       