<div class="right_col">
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Earned Academics Credit</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
						<div class="row">
															
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_year; ?>
                            </div>
							</div> 
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Session<span class="asterisk">*</span></label>
                                <?php echo $this->form->session; ?>
                            </div>
							</div> 
                            
							<!--<div class="col-sm-3 employee_class">
                                <div class="form-group">
                                <label class="control-label">Credit's<span class="asterisk">*</span></label>
                                <?php echo $this->form->credit_number; ?>
                                </div>
							</div> ---> 
                            <?php echo $this->form->csrftoken; ?>                                                    
														
							<div class="col-sm-3 employee_class">
                                <div class="form-group">
                                <label class="control-label"> status<span class="asterisk">*</span></label>
                                <?php echo $this->form->status; ?>
                                </div>
							</div>  									
														
							
							
						</div>
                        <div class="ajaxData" id="ajaxData">
                            
                        </div>
                        
					</div>
						<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									
                                    <div style="float:left;margin-right:2px;">
                                    <button class="btn btn-primary submit">Submit</button>
                                    </div>
										
									
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
</div>
<script>
    //To filter Session
    $('body').on('change', '#academic_year', function () {
        $('#department').removeAttr('disabled');
        var year_id = $('#academic_year').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    $('body').on('change', '#session', function () {
        var session = $('#session').val();
        if (session) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Batch-By-Session'; ?>',
                data: {session: session}
            }).done(function (data) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
            });
        }
    });
    //End 
    </script>