<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->Event_form->getAction() ?>" method="post" data-validate="parsley" novalidate>
					<div class="panel-heading">									
						 <h4>Event</h4> 
					</div>
					<div class="panel-body">
						<?php if($this->type != 'edit'){?>
						<div class="col-sm-3 " style="margin-left:75.5%;margin-bottom:10px;" >
							<select type="text" onchange="locationDump(0);" class="form-control" id="location" >
								<option value="">Dump data from location</option>									 
								<?php foreach($this->Location as $k=>$val){									
								?>										
								<option value="<?php echo $k;?>" ><?php echo $val;?></option>
								<?php }?>
							</select>
						</div>
						<?php } ?>
						<?php if($this->type != 'edit'){?>
						<div class="col-sm-3 " style="margin-left:75.5%;margin-bottom:10px;" >
							<select type="text" onchange="branchDump(0);" class="form-control" id="branch" >
								<option value="">Dump data from branch</option>									 
								<?php foreach($this->Branch as $k=>$val){									
								?>										
								<option value="<?php echo $k;?>" ><?php echo $val;?></option>
								<?php }?>
							</select>
						</div>
						<?php } ?>
						<div class="row">
						 <div class="col-sm-3">
									<div class="form-group">
										<label class="control-label">Country <span class="asterisk">*</span></label>
										<?php echo $this->Event_form->country; ?>
									</div>											
								</div>
								<div class="col-sm-3">
									<div class="form-group">
										<label class="control-label">State <span class="asterisk">*</span></label>
										<?php echo $this->Event_form->state; ?>
									</div>											
								</div>
								<div class="col-sm-3">
									<div class="form-group">
										<label class="control-label">City <span class="asterisk">*</span></label>
										<?php echo $this->Event_form->city; ?>
									</div>											
								</div>
							<?php /* 	<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Location Name <span class="asterisk">*</span></label>
									<?php echo $this->Event_form->location_id; ?>
									
								</div>										
							</div> */ ?>
							<div id="location_id"></div>
							<div></div>
								<div id="branch_id"></div>											
							
							<div class="col-sm-2" style="height: 100px;overflow-y: scroll;margin-top:20px;margin-left:6px;">	
								<input type="button" id="select2" value="Select All"  style="border:none;"/>
								<input type="button" id="unselect2" value="Unselect All" style="border:none;"/>
									<div class="form-group">
									 <label  class="control-label">subprogram</label>
									  <?php foreach($this->subprogram as $k=>$val){ //print_r($val); die; ?>
										<label class="label-checkbox" style="padding-left:0px; margin:1px;" >
										<input type="checkbox" name="subprogram_id[]" id="subprogram_id"  class="checkbox2" label="subprogram" <?php
										  if(!empty($this->result['subprogram_id'])){ 
												$data = explode(',',$this->result['subprogram_id']);
												foreach($data as $key=>$Val){
													$checked = '';
													if($k == $Val)
													echo $checked = 'checked';
													}
													  }	
										?> value="<?php echo $k;?>"/>
												<span class="custom-checkbox" style="float:left;"></span> </label> <?php echo $val; ?>
										<?php } ?>
									</div> 
								</div>
							<?php /*<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Branch<span class="asterisk">*</span></label>
									<?php echo $this->Event_form->branch_id; ?>
								</div>										
							</div>
							<div class="col-sm-3">	
							<div class="form-group">
									<label class="control-label">Academic Year<span class="asterisk">*</span></label>
								
								<select type="text" name="academic_year" id="academic_year" class="form-control " >
								<?php	if($this->type =='edit'){ ?>
								<option value="<?php  echo $this->result['academic_year'];?>" ><?php echo $this->result['academic_year'];?></option>
								 
								<?php } else {  ?>
									<option value="" >Select Academic Year</option>
									<option value="<?php echo $this->AcademicYear;?>">Current Year</option>
									<option value="<?php echo $this->NextYear;?>">Next Year</option>
										<?php	}?>					
								</select>
									
								</div>
							</div> 
							<div class="col-sm-3" style="height: 100px;overflow-y: scroll;margin-top:20px">
							<label  class="control-label">Branch</label>
							<?php foreach($this->branch as $k=>$val){ //print_r($val); die; ?>
							<label class="label-checkbox" style="padding-left:0px; margin:8px;" >
							<input type="checkbox" name="branch_id[]" id="branch_id" class="checkbox branch_id" <?php
										if(!empty($this->result['branch_id'])){ 
												$data = explode(',',$this->result['branch_id']);
												foreach($data as $key=>$Val){
													$checked = '';
													if($k == $Val)
													echo $checked = 'checked';
													} } ?> value="<?php echo $k;?>" />
							<span class="custom-checkbox" style="float:left;"></span> </label> <?php echo $val; ?>
							<?php } ?>
							</div> */ ?>
						
							</div>
							<div class="row" id="event">
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Academic Year</label>
									<?php echo $this->Event_form->academic_year; ?>
									
								</div>										
							</div>
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Event Name <span class="asterisk">*</span></label>
									<?php //echo $this->Event_form->event_name; ?>
									<input type="text" class="form-control" name="event[event_name][]" id="event_name" value="<?php echo $this->result['event_name']; ?>"/>
								</div>										
							</div>
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Event Start Date <span class="asterisk">*</span></label>
									<div class="input-group">
										<?php //echo $this->Event_form->event_date; ?>
										<input type="text" class="form-control" name="event[event_date][]" id="event_date" value="<?php echo $this->result['event_date'];?>"/>
										
										<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									</div>		
								</div>										
							</div>	
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Event End Date <span class="asterisk">*</span></label>
									<div class="input-group">
										<?php //echo $this->Event_form->event_end_date; ?>
										<input type="text" class="form-control" name="event[event_end_date][]" id="event_end_date" value="<?php echo $this->result['event_end_date']; ?>"/>
										<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
									</div>		
								</div>										
							</div>							                         
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Event Description </label>
									<?php //echo $this->Event_form->event_description; ?>
									<textarea class="form-control" name="event[event_description][]" id="event_description"><?php echo $this->result['event_description']; ?></textarea>
								</div>										
							</div>
							</div>
							
							<?php
							if(!empty($this->sms_email_date_time)){
											  $i=0; ?>
									<input type="hidden" name="sms_email" id="sms_email" value="<?php echo (count($this->sms_email_date_time) +1 ); ?>" class="sms_email">
									<?php
									foreach($this->sms_email_date_time as $val){
									//print_r($val);die;
									//$total_amount += $val['total_price'];
									$i++;
									?>
										<div  class="row appended_row ">
											<div class="col-sm-3">	
												<div class="form-group">
													<label class="control-label">Sms & Email Trigger Date & Time</label>
													<div class="input-group">	
												<input type="text"  class="form-control sms_email_trigger_date_time " id="sms_email_date<?php echo $i; ?>" name="sms_email_trigger_date_time[]" value="<?php echo $val ;?>"  />
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
													</div>
											</div>
										</div>
											<a  class="removeclass6 btn btn-primary remove_class6 "style="padding:7px 19px;margin:20px 15px;" href="#">-</a>
											</div> 
									<?php		} 
											?>
										<div  class=" appended_row "> <div class="col-sm-3"></div><a id="AddButton6" class="btn btn-primary" style="padding:7px 19px;margin:20px 05px;">+</a> 
										</div>
									<?php } else { ?>
									<div  class="row appended_row ">
										<input type="hidden" name="sms_email" id="sms_email" value="1" class="sms_email">	
										<div class="col-sm-3">	
												<div class="form-group">
													<label class="control-label">Sms & Email Trigger Date & Time</label>
													<div class="input-group">	
												<input type="text"  class="form-control sms_email_trigger_date_time" id="sms_email_date" name="sms_email_trigger_date_time[]"/>
												<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
													</div>
											</div>
										</div>
										<a id="AddButton6" class="btn btn-primary" style="margin:24px 15px; padding: 7px 19px!important;">+</a> 
									</div>
										<?php } ?>
									
									<div  id="fields7">
										<div class="padding-top"></div>
									</div>
									<input type="hidden" name="event_id" id="event_id" value="<?php echo $this->result['event_id']; ?>" />
							
						</div>
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->
	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->	
<div class="padding-md">
	<div class="panel panel-default table-responsive">
		<div class="panel-heading">
			 Event
			<a class="btn btn-primary pull-right" style="margin-top: -9px;" href="<?php echo $this->mainconfig['host']; ?>master/event/type/add">Add Event </a>
		</div>
		<form class="no-margin" action="<?php echo $this->mainconfig['host']; ?>master/event/type/search" method="post" data-validate="parsley" novalidate>
			<div class="row" style="margin: 10px 5px 0px 5px;;">
				<div class="col-sm-3">	
					<div class="form-group">
						<label class="control-label">Country </label>
							<?php echo $this->form->country; ?>
					</div>										
				</div>				
				<div class="col-sm-3">	
					<div class="form-group">
						<label class="control-label">State </label>
						<?php echo $this->form->state; ?>
					</div>										
				</div>
				<div class="col-sm-3">	
					<div class="form-group">
						<label class="control-label">City </label>
						<?php echo $this->form->city; ?>
					</div>										
				</div>
				 <div class="col-sm-3" style="height: 100px;overflow-y: scroll;margin-top:20px">
							<label  class="control-label">Location</label>
							<?php foreach($this->location as $k=>$val){ //print_r($val); die; ?>
							<label class="label-checkbox" style="padding-left:0px; margin:8px;" >
							<input type="checkbox" name="location_id[]" id="location_id" class="checkbox" <?php
										/* if(!empty($this->result['branch_id'])){ 
												$data = explode(',',$this->result['branch_id']);
												foreach($data as $key=>$Val){
													$checked = '';
													if($k == $Val)
													echo $checked = 'checked';
													} }  */ ?> value="<?php echo $k;?>" />
							<span class="custom-checkbox" style="float:left;"></span> </label> <?php echo $val; ?>
							<?php } ?>
						 </div>	
					</div> 
					<div class="row">
					<div class="col-sm-3" style="height: 100px;overflow-y: scroll;margin:20px 20px 0px;">
							<label  class="control-label">Branch</label>
							<?php foreach($this->branch as $k=>$val){ //print_r($val); die; ?>
							<label class="label-checkbox" style="padding-left:0px; margin:8px;" >
							<input type="checkbox" name="branch_id[]" id="branch_id" class="checkbox" <?php
										/* if(!empty($this->result['branch_id'])){ 
												$data = explode(',',$this->result['branch_id']);
												foreach($data as $key=>$Val){
													$checked = '';
													if($k == $Val)
													echo $checked = 'checked';
													} } */ ?> value="<?php echo $k;?>" />
							<span class="custom-checkbox" style="float:left;"></span> </label> <?php echo $val; ?>
							<?php } ?>
						 </div>	 
						 <div class="col-sm-3" style="height: 100px;overflow-y: scroll;margin-top:20px">
							<label  class="control-label">Subprogram</label>
							<?php foreach($this->subprogram as $k=>$val){ //print_r($val); die; ?>
							<label class="label-checkbox" style="padding-left:0px; margin:8px;" >
							<input type="checkbox" name="subprogram_id[]" id="subprogram_id" class="checkbox" <?php
										/* if(!empty($this->result['branch_id'])){ 
												$data = explode(',',$this->result['branch_id']);
												foreach($data as $key=>$Val){
													$checked = '';
													if($k == $Val)
													echo $checked = 'checked';
													} } */ ?> value="<?php echo $k;?>" />
							<span class="custom-checkbox" style="float:left;"></span> </label> <?php echo $val; ?>
							<?php } ?>
						 </div>
						 <div class="col-sm-3">	
							<div class="form-group">
								<label class="control-label">Event Name</label>
								<?php echo $this->form->holiday_name; ?>
							</div>										
						</div>
						<div class="col-sm-3">	
							<div class="form-group">
								<label class="control-label">Academic Year</label>
								<?php echo $this->form->academic_year; ?>
							</div>										
						</div>	
						
					</div>	
				<div class="row" style="margin:0px 6px;">	
				<div class="col-sm-3">				
					<button class="btn btn-primary submit">Submit</button>
				
			<!--	<a class="btn btn-primary" style="margin-left: 65%;" href="<?php //echo $this->mainconfig['host']; ?>master/holiday/type/export">Export Excel</a> -->
				<button class="btn btn-primary" name="export" value="Export Excel" >Export Excel</button>
			</div>
			</div>
		</form>	
		
		<div class="padding-md clearfix">
			<table class="table table-striped" id="dataTable">
				<thead>
					<tr>
						<th>S. No.</th>	
						<th>Location Name</th>
						<th>Event Name</th>	
						<th>Event Start Date</th>
						<th>Event End Date</th> 
						<th>Event Description</th>
						<th>Email & SMS Trigger Date & Time</th>
						<th>Action</th>   
					</tr>
				</thead>
				<?php if(!empty($this->searchResult)) { ?>
						<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->searchResult) != 0) {

						foreach ($this->searchResult as $results) {

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						<td><?php echo $results['location_name']; ?></td>
						<td><?php echo $results['event_name']; ?></td>
						<td><?php echo date( DATE_PREFIX, strtotime($results['event_date'])); ?></td>
						<td><?php echo date( DATE_PREFIX, strtotime($results['event_end_date'])); ?></td>
						<td>
						<?php 
						$SubString = substr($results['event_description'],0,50);
						if(strlen($results['event_description']) >100){
							echo $SubString.'...';
						}else{
							echo $SubString;
						}
						 ?>
							<td><?php  if(!empty($results['sms_email_trigger_date_time'])) {  $sms_email_trigger_date_time = unserialize($results['sms_email_trigger_date_time']);
						foreach($sms_email_trigger_date_time as $val){
							echo $val; 
						} }
							?></td>
						<?php //echo $results['event_description']; ?></td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/event/type/edit/id/<?php echo $results['event_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/event/type/delete/id/<?php echo $results['event_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

					</tr>            

								<?php }
								//$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			
				<?php } else { ?>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						<td><?php echo $results['location_name']; ?></td>
						<td><?php echo $results['event_name']; ?></td>
						<td><?php echo date( DATE_PREFIX, strtotime($results['event_date'])); ?></td>
						<td><?php echo date( DATE_PREFIX, strtotime($results['event_end_date'])); ?></td>
						<td>
						<?php 
						$SubString = substr($results['event_description'],0,50);
						if(strlen($results['event_description']) >100){
							echo $SubString.'...';
						}else{
							echo $SubString;
						}
						 ?>
						
						<td><?php  if(!empty($results['sms_email_trigger_date_time'])) {  $sms_email_trigger_date_time = unserialize($results['sms_email_trigger_date_time']);
						foreach($sms_email_trigger_date_time as $val){
							echo $val; 
						} }
							?></td>
							
						<?php //echo $results['event_description']; ?></td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/event/type/edit/id/<?php echo $results['event_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/event/type/delete/id/<?php echo $results['event_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
				<?php } ?>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div><!-- /.padding-md -->		
<?php } ?>
<script>
$(document).ready(function() {		
	// Datepicker
	$('#event_date').datepicker( {format: 'yyyy-mm-dd'} );
	$('#event_end_date').datepicker( {format: 'yyyy-mm-dd'} );
	$('#sms_email_date').datetimepicker( {format: 'yyyy-mm-dd hh:ii' } )
$('.sms_email_trigger_date_time').datetimepicker( {format: 'yyyy-mm-dd hh:ii' } )
});
$('body').on('change','#location_id', function() {	
	var id = $(this).val();	
	//alert(id);
		if(id){ 
		//alert(id);
			$.ajax({ 
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'master/ajax-get-branch';?>',
				data: {id:id}
			}).done(function( data ) {
				//$("#branch_id").html( data );
				var result = $.parseJSON( data );
				//alert(result);
				$.each(result,function(index, value){
    //alert('My array has at position ' + index + ', this value: ' + value);
});
			for(var val in result ){
				//alert(result[val]);
			$('#branch').val(result);
				}	
			 });
		}
	});	
	
	
	function  locationDump(vals){
	var id = $("#location").val();	
	//alert(id); 
	if(id != '' ){	
		$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-event-dump';?>',
			data: {id:id}
		}).done(function( data ) {
			//$("#formValidate1 div[label='program_info"+vals+"']").html( data );
			$( "#event").html( data );
			// Datepicker
			$('#event_start_date').datepicker( {format: 'yyyy-mm-dd'} );
			$('#event_end_date').datepicker( {format: 'yyyy-mm-dd'} );
		 });
	}else{
		$( "#event").find("input:text").val("").end();
		$( "#event_description").val("");
		$( "#branch_id").val("");
	}
}

$('body').on('change', '#country', function() {
	var id = $(this).val();		
		$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-state';?>',
			data: {id:id}
		}).done(function( data ) {
			$( "#state").html( data );
		 });
});
$('body').on('change', '#state', function() {
	var id = $(this).val();		
		$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-city';?>',
			data: {id:id}
		}).done(function( data ) { 
			$( "#city").html( data );
		 });
});

$('body').on('change', '#city', function() {
	var id = $(this).val();		
		$.ajax({                                                  
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-event-location';?>',
			data: {id:id}
		}).done(function( data ) { 
			$( "#location_id").html( data );
		 });
});

var id = $('#city option:selected').val();
var event_id = $('#event_id').val();
//alert(event_id);
$.ajax({                                                  
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-event-location-edit';?>',
			data: {id:id,event_id:event_id}
		}).done(function( data ) { 
		//alert(data);
			$( "#location_id").html( data );
		 });
$('body').on('change','#location_id', function() { 
	var selectedLocation = new Array();
	$('input[name="location_id[]"]:checked').each(function() {
	selectedLocation.push(this.value);
	});
//alert(selectedLanguage);
			if(selectedLocation){
			//alert(selectedLocation);
				$.ajax({ 
						type: "POST",
						url:'<?php echo $this->mainconfig['host'].'master/ajax-get-event-branch';?>',
						data: {selectedLocation:selectedLocation}
					}).done(function( data ) {
						$("#branch_id").html( data );
						//alter(branch_id);
					 });
			}
});
	
			
				//var sThisVal = new Array();
			$(document).ready(function() {
			var selectedLocation = new Array();
					 $("input:checkbox[class=checkbox1]:checked").each(function() {
						selectedLocation.push($(this).val());
								//alert(selectedLocation);
						}); 						
						
						if(selectedLocation){
						$.ajax({ 
								type: "POST",
								url:'<?php echo $this->mainconfig['host'].'master/ajax-get-event-branch';?>',
								data: {selectedLocation:selectedLocation}
							}).done(function( data ) {
							//alert(data);
								$("#branch_id").html( data );
							 });
					}
		
			});
			$('body').on('click','#select1',function() {
//alert('sdsd'); 
var id = $('#select1').val();
  if(id == 'Select All') {
      // Iterate each checkbox
      $('.checkbox1').each(function() {
          this.checked = true;
      });
  }
  else {
    $('.checkbox1').each(function() {
          this.checked = false;
      });
  }
}); 
$('body').on('click','#unselect1',function() {
var id = $('#unselect1').val();
//alert(id);
  if(id == 'Unselect All') {
      // Iterate each checkbox
      $('.checkbox1').each(function() {
          this.checked = false;
      });
  }
  else {
    $('.checkbox1').each(function() {
          this.checked = true;
      });
  }
});
$('body').on('click','#select2',function() {
//alert('sdsd'); 
var id = $('#select2').val();
  if(id == 'Select All') {
      // Iterate each checkbox
      $('.checkbox2').each(function() {
          this.checked = true;
      });
  }
  else {
    $('.checkbox2').each(function() {
          this.checked = false;
      });
  }
}); 
$('body').on('click','#unselect2',function() {
var id = $('#unselect2').val();
//alert(id);
  if(id == 'Unselect All') {
      // Iterate each checkbox
      $('.checkbox2').each(function() {
          this.checked = false;
      });
  }
  else {
    $('.checkbox2').each(function() {
          this.checked = true;
      });
  }
});
$('body').on('click','#select3',function() {
//alert('sdsd'); 
var id = $('#select3').val();
  if(id == 'Select All') {
      // Iterate each checkbox
      $('.checkbox3').each(function() {
          this.checked = true;
      });
  }
  else {
    $('.checkbox3').each(function() {
          this.checked = false;
      });
  }
}); 
$('body').on('click','#unselect3',function() {
var id = $('#unselect3').val();
//alert(id);
  if(id == 'Unselect All') {
      // Iterate each checkbox
      $('.checkbox3').each(function() {
          this.checked = false;
      });
  }
  else {
    $('.checkbox3').each(function() {
          this.checked = true;
      });
  }
});
var count = $('#sms_email').val();
		$("body").on("click","#AddButton6",function(event){
		var count_value = count++;
		append_html = '<div class="row">';
		append_html +=	'<div class="col-sm-3"><div class="form-group"><label class="control-label">Sms & Email Trigger Date & Time</label><div class="input-group"><input type="text" class="form-control sms_email_trigger_date_time" name="sms_email_trigger_date_time[]" id="sms_email_date'+count_value+'" /><span class="input-group-addon"><i class="fa fa-calendar"></i></span></div></div></div>';	
		append_html += '<a href="#" class="removeclass6 btn btn-primary remove_class6 " style="padding:7px 19px;margin:20px 15px;">-</a>';
		append_html += '</div>';			
		$('#fields7').append(append_html);
		$(".no-margin input[id='sms_email_date"+count_value+"']").datetimepicker({format: 'yyyy-mm-dd hh:ii'});
		});
		$("body").on("click",".removeclass6", function(e){
		//alert('sdsd');

                $(this).parent('div').remove(); 				
				
        return false;

    });

</script>