<?php if ($this->type) { ?>
<div class="padding-md right_col">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Fee Type – Franchise</i></div>
				
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" novalidate>
					
					<div class="panel-body">
						<div class="row">							                         
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Fee Head<span class="asterisk">*</span></label>
									<?php echo $this->form->fee_type_title; ?>
								</div>										
							</div>												
						</div>		
</div>						
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="right_col">
	
		<div class="row">
	<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars">   Fee Type – Franchise</i>
				
		</h3>
	</div>
	<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">
		
			<a class="btn btn-primary pull-right" style="margin-top:25px;" href="<?php echo $this->mainconfig['host']; ?>master/feestype/type/add">Add Fee Type </a>

			
	</div>
</div>
	<div class="x_panel">
               
                    <div class="x_title">
                    <h2> Fee Type – Franchise</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th>S.No.</th>	 
						<th>Fee Head</th>
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {

					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>
								<td>
								<?php 
								$SubString = substr($results['fee_type_title'],0,18);
								if(strlen($results['fee_type_title']) >50){
									echo $SubString.'...';
								}else{
									echo $SubString;
								}
								 ?>
								<?php //echo $results['fees_type_title']; ?></td>
								<td><a href="<?php echo $this->mainconfig['host']; ?>master/feestype/type/edit/id/<?php echo $results['fee_type_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/feestype/type/delete/id/<?php echo $results['fee_type_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div>
</div><!-- /.padding-md -->		
<?php } ?>
<script type="text/javascript">	
/*
$(document).ready(function() { 
	 var count = $('#count_val').val();
     $("body").on("click","#AddButton", function(e){ 
	 
        $( "#appended_row1:last" ).clone().find("input:text").val("").end().appendTo( "#fields" );			
			var count_val = count++;
			$('#count_val').val(count_val);
          return false;		  
    });

    $("body").on("click",".removeclass", function(e){
                   $(this).parent('div').remove(); 
               return false;
    });
});	

$('body').on('change', '#organization_id', function() {		
	var org_id = $(this).val();		
		$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'admission/ajax-get-students';?>',
			data: {org_id:org_id}
		}).done(function( data ) {
			$( "#student_name").html( data );
		 });
});	 */
</script>
