<?php 
//print_r( $this->academicresult);die;
?>
<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
			
			
				<thead>
					<tr>
						
						<th style="text-align:center;" >Term Name</th>
						<th style="text-align:center;" >Course Name </th>
						<th style="text-align:center;" > Course Category Name</th>
						<th style="text-align:center;" >Credit Value </th>

					</tr>
				</thead>
				<tbody>
				
				
				<tbody style="text-align:center;" >
									
										<?php
											
											$i = 1;
											$total_credits=0;
										
										?>
										<?php if($this->corecourseresult !=0){ 
										foreach($this->corecourseresult as $key=>$val){ ?>
										<tr>
										
											
											<td><?php echo $val['term_name'];?></td> 
											<td><?php echo $val['course_name'];?></td>
											<td><?php echo $val['cc_name'];?></td> 
											<td><?php echo $val['credit_value'];?></td> 
											
								
		                               </tr>
									   
									  
									   <?php 
									   $total_credits=$total_credits+$val['credit_value'];
											 }
											
											?>
									<tr id="total">
						<td  colspan="3" align="right"><b>Total Credits</b></td>
							<td><b></b> <b><?php echo  $total_credits;?></b></td>
							</tr>
							
							
							<?php } else {?>

           <tr>

               <td colspan="5" align="center">No Results Found</td>

           </tr>

            <?php }?>
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->