<style>
   
    #refresh{
        cursor:pointer;
    }
    
    
</style>
<div class="right_col bdoypayment">
    <div class="load-box" style="z-index:998">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars">Payment Information</i>

                        </h3>
                    </div>
                </div>
                <div class="col-md-12">
                   <!--<div class="col-sm-3 employee_class">-->
                   <!--     <div class="form-group">-->
                   <!--         <label class="control-label" style="float:left;">Merchant Id:<span class="asterisk"></span></label>-->
                   <!--         <?php echo $this->form->mer_id; ?>-->
                   <!--     </div>-->
                   <!--</div>-->
                   
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label" style="float:left;">Date<span class="asterisk"></span></label>
                           <input type="date" class="form-control" id ="Date" />
                        </div>
                   </div>
                       
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <i class="fa fa-refresh" style="font-size:1.5em;margin-top:1.5em" id="refresh" aria-hidden="true"></i>
                        </div>
                   </div>
                   
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <button type="button" class="btn btn-primary pull-left"  style="margin-top:1.5em;z-index:999;" id ="stop"  onClick="stop()">Stop Refresh</button>
                        </div>
                   </div>
                   
                <div style="float:left;padding-left:10%;">
                </div>
                </div>
                 <div class="col-md-12">
                   <div class="table-responsive" id="studentData"> 
                   
                   

                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">

                            <thead>

                                <tr>

                                    <th class="no-sort">S.No.</th>

                                    <th>Student Name</th>


                                    <th>UID</th>

                                    <th>Exam Roll</th>

                                    <th>Roll No.</th>

                                    <th>Transaction Id</th>
                                    <th>Status</th>
                                    <th>Pay Mode</th>
                                    <th>Amount</th>
                                    <th>PF</th>
                                    <th>Tax</th>
                                    <th>Batch</th>
                                    <th>Date</th>
                                </tr>

                            </thead>

                            <tbody>

                   
                   
                      </tbody>

                        </table>
                       
                    </div>
                </div>
                
            </div>    
           

        </div>
       
        </div></center>
    </div>
    <?php 
    

    ?>

<script>
$(document).ready(function(){
    
var oTable = $('#datatable-responsive').DataTable( );
    let i =0;
    let timer = '';
    let timer2 = '';
    let tran_id_arr = [];
    $('#Date').change(function(){
        timer2='';
      $('#datatable-responsive').DataTable().destroy();
         $('table tbody').empty();
         i =0;
         tran_id_arr = [];
         $('#datatable-responsive').DataTable().draw();
         timerfunction(); 
    });
    
    
     function myfunction() {
            // $('.load-box').show();
        clearInterval(timer);
        clearInterval(timer2);
         const mer_id = $('#mer_id').val();
           const tran_id = $('#tran_id').val();
           var date = $('#Date').val();
           
           if(!date)
            date = "<?=Date("Y-m-d");?>";
          $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Pay-single'; ?>',
                data: {mer_id,tran_id:tran_id_arr,date:date}
            }).done(function (data) {
                if(data){
              tran_id_arr.push(data);
                }
             const tran_id = data;
               $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Pay'; ?>',
                data: {mer_id,tran_id,i}
            }).done(function (data) {
               
               
               if(data != '0'){
                   $('#datatable-responsive').DataTable().destroy();
                    $('table tbody').prepend(data);
               i++;
                
                 $('.load-box').hide();
            timerfunction();
               }
               else
               {
                   $('.load-box').hide();
                 setTimeOutFunction();
               }
             
              
            });
            });
    }
    function timerfunction() {
         timer = setInterval(myfunction(),0);
    }
    
    
        timerfunction();
        function stop() { 
            clearInterval(timer); 
        }
    $('#refresh').click(function(){
        clearInterval(timer2);
       timerfunction();
});





 function myfunction2() {
        clearInterval(timer2);
         const mer_id = $('#mer_id').val();
           const tran_id = $('#tran_id').val();
           var date = $('#Date').val();
           
           if(!date)
            date = "<?=Date("Y-m-d");?>";
          $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Pay-single1'; ?>',
                data: {mer_id,tran_id:tran_id_arr,date:date}
            }).done(function (data) {
                if(data){
              tran_id_arr.push(data);
                }
             const tran_id = data;
               $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-update-Pay'; ?>',
                data: {mer_id,tran_id,i}
            }).done(function (data) {
               
               
               if(data != '0'){
                   
            timerfunction2();
               }
               else
               {
                   setTimeOutFunction();
               }
             
              
            });
            });
    }

 function timerfunction2() {
         timer2 = setInterval(myfunction2(),0);
    }
    
    function setTimeOutFunction(){
       timerfunction2();
    }

   



    
}); 




</script>

