<style>
    dt{
        display:none;
    }

</style>
<style>
    @media print {
        table td:nth-child(7)
        {
            display:none;
        }
        table th:nth-child(7)
        {
            display:none;
        }
        *{
            visibility:hidden;
        }
        table,th,td 
        {
            visibility:visible;                    
        } 
        .title1
        {
            visibility:visible; 
        }
    }
</style>

<div class="right_col">
    <?php if ($this->type) { ?>
        <div class="padding-md ">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Section</i></div>
                    </h3>
                    <div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                                            <?php echo $this->form->year_id; ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Session <span class="asterisk">*</span></label>
                                            <?php echo $this->form->session; ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Batch<span class="asterisk">*</span></label>
                                            <?php echo $this->form->academic_year_id; ?>
                                        </div>
                                    </div>
                                    <?php echo $this->form->csrftoken; ?>			
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label"> Term<span class="asterisk">*</span></label>
                                            <?php echo $this->form->term_id; ?>
                                        </div>
                                    </div>

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Section Name<span class="asterisk">*</span></label>
                                            <?php echo $this->form->name; ?>
                                        </div>
                                    </div> 
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Status<span class="asterisk">*</span></label>
                                            <?php echo $this->form->status; ?>
                                        </div>
                                    </div> 
                                </div>
                               

                            </div>
                            <div>
                                <div class="panel-footer">									
                                    <div class="row">
                                        <div class="col-sm-7 col-sm-offset-5">
                                            <?php if ($this->type == 'add') { ?> 
                                                <div style="float:left;margin-right:2px;" >
                                                    <button class="btn btn-primary submit" id="removebtn">Submit</button>
                                                </div>
                                                <div style="float:left;padding:0px 10px;">
                                                    <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                                </div>
                                            <?php } else if ($this->type == 'add') { ?>	
                                                <div style="float:left;margin-right:2px;">
                                                    <button class="btn btn-primary submit">Submit</button>
                                                </div>
                                            <?php } else { ?>
                                                <div style="float:left;">
                                                    <button class="btn btn-primary submit">Update</button>
                                                </div>
                                                <div style="float:left;">
                                                    <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>master/corecourselearning">Back</a>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div><!-- /panel -->
                </div><!-- /.col-->				
            </div><!-- /.row -->

        </div><!-- /.padding-md -->	
    <?php } else { ?>

        <?php
        if (count($this->messages)) {
            foreach ($this->messages as $message) {
                ?>
                <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                <?php echo $this->escape($message); ?>
                </div>
            <?php }
        }
        ?>
        <!-- widget grid -->
        <div class="">
            <div class="">
                <div class="row">

                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars"> Section</i>

                        </h3>
                    </div>

                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                        <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>master/section/type/add">Add </a>
                    </div>
                </div>

                <div class="x_panel">

                    <div class="x_title">
                        <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <label class="control-label">Academic Year<span class="asterisk">*</span></label>
    <?php echo $this->form->year_id; ?>
                            </div>
                        </div>
                        <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <label class="control-label">Session <span class="asterisk">*</span></label>
    <?php echo $this->form->session; ?>
                            </div>
                        </div>
                        <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <label class="control-label">Batch<span class="asterisk">*</span></label>
    <?php echo $this->form->academic_year_id; ?>
                            </div>
                        </div>
                        <br>
                        <button type="button" id="getRecords" class="btn btn-primary" style="float: right" value="0" >Get Record</button>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="padding-md clearfix">
                            <div class="col-sm-0" style="float:right;">
                                           <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host'];   ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id;   ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
                        <div class="ajaxData" id="ajaxData">
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
                                <thead>
                                    <tr>
                                        <th style="text-align:center;" >S.No.</th>
                                        <th style="text-align:center;" >Batch</th>
                                        <th style="text-align:center;" >Term</th>
                                        <th style="text-align:center;" >Section Name</th>
                                        <th style="text-align:center;" >Status</th>
                                        <th class="no_print" style="text-align:center;" >Action</th>
                                    </tr>
                                </thead>
                                <tbody style="text-align:center;" >
                                    <?php
                                    $i = 1;
                                    $pagination_tr = '';
                                    if (count($this->paginator) != 0) {

                                        foreach ($this->paginator as $results) {
                                            //print_r($results);die;
                                            ?>
                                            <tr>
                                                <td><?php
                                                    echo $i;

                                                    $i++;
                                                    ?>
                                                </td>
                                                <td><?php echo $results['short_code']; ?></td>
                                                <td><?php echo $results['term_name']; ?></td>
                                                <td><?php echo $results['name'] ?></td>
                                                <td><?php echo $results['status'] == 0 ? 'Active' : 'Deactive'; ?></td>
                                                <td><a href="<?php echo $this->mainconfig['host']; ?>master/section/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a><!--&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/corecourselearning/type/delete/id/<?php // echo $results['ccl_id'];   ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a>--></td>

                                            </tr>            

                                            <?php
                                        }
                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                    }
                                    ?>

                                </tbody>
                            </table>
    <?php echo $pagination_tr; ?>
                        </div>
                        </div><!-- /.padding-md -->
                    </div><!-- /panel -->
                </div>
            </div>
        </div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>
    $(document).ready(function () {
        $('#r_credit').hide();
        $('#course_id').removeAttr('class');
        $('#course_id').attr('class', 'form-control chosen');
        $(".chosen").chosen();
        $("#course_id").trigger("chosen:updated");
    });

    function ConfirmDelete()
    {
        var x = confirm("Are you sure you want to delete?");
        if (x)
            return true;
        else
            return false;
    }
    $("#cc_name").change(function () {

        var course_name = $('#cc_name').val();

        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/get-course-category'; ?>',
            data: {course_name: course_name}
        }).done(function (data) {

            if ((data != '')) {
                alert("This Course Name Exists");
                $("#cc_name").val("");
            }
        });
    });

//To filter Session
    $('body').on('change', '#year_id', function () {
        var year_id = $('#year_id').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    //Get Batch By Session
    $('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#academic_year_id').empty('');
                $('#academic_year_id').html(data);
                $('#academic_year_id').trigger("chosen:updated");
            });
        }
    });
    //End
    $('body').on('change', '#academic_year_id', function () {
        var academic_year_id = $('#academic_year_id').val();
        //alert(academic_year_id);
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-term-name'; ?>',
            data: {academic_year_id: academic_year_id}
        }).done(function (data) {

            $('#term_id').empty('');
            $('#term_id').html(data);
            $("#term_id").trigger("chosen:updated");
        });
    });
    // For Filtering record
    $('body').on('click', '#getRecords', function () {
        var batch_id = $('#academic_year_id').val();
        if (batch_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-filter-section-records'; ?>',
                data: {batch_id: batch_id}
            }).done(function (data) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
            });
        }
    });


  



</script>
