<?php
//echo "<pre>";print_r($this->category_data);die;
?>
<style>
    input { 
        text-align: center; 
    }

    input:focus{
        border:2px solid #00ed22;

    }
</style>
<?php
$attendanceCheck = array(
    '0' => 'Allowed',
    '1' => 'Not Allowed'
);

$str = '';

if ($this->attend_status['attend_status'] == "0") {
    $str = '1';
} else {
    $str = '0';
}
// echo '<pre>';print_r($this->attend_status);die;
?>
<div style="overflow-x:scroll">
    <div class="padding-md clearfix">

        <div class="col-sm-0" style="float:right;">
            <a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a>
        </div>
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable-grade" id="dataTable" >

            <thead>
                <tr>
                    <th>S.No.</th>
                    <th>Participants Name</th>
                    <th>Roll No.</th>
                    <th>Batch</th>
                    <th> UID</th>
                    <th> Reg. No.</th>
                    <th>Exam Roll. No.</th>
                    <th>Attendance Status</th>
                    <th>Remarks </th>
                </tr>
            </thead>
            <tbody>
                <?php
                if (!empty($this->result)) {
                   

                    foreach ($this->result as $k => $result) {
                        //echo "<pre>";print_r($result);exit; 
                         $i = 1;
                        ?>
                        <tr>
                            <td><?php
                                echo $i;
                               $i++;
                                ?>
                            </td>
                            <td><?php echo $result['student_name']; ?></td> 
                    <input type="hidden" name="stu_id[]" id="student_id" value="<?php echo $result['student_id']; ?>" /> 
                    <input type="hidden" name="grade[academic_id_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" id="term_id1" value="<?php echo $result['academic_id']; ?>" />
                    <input type="hidden" name="grade[term_id_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" id="academic_id1" value="<?php echo $result['term_id']; ?>" />
                    <input type="hidden" name="u_id[]" id="student_id" value="<?php echo $result['stu_id']; ?>" />
                    <td><?php echo $result['roll_no']; ?></td> 		
                    <td><?php echo $result['stu_id']; ?></td> 		 
                    <td><?php echo $result['stu_id']; ?></td>
                    <td><?php echo $result['reg_no']; ?></td>
                    <td><?php echo $result['exam_roll']; ?></td>
                    <td>

                        <select id=attendance_status"<?php echo $i; ?>" name="attendance_val[]" class="attendance_status" <?= $str == "1" ? 'style="border:2px solid #ff0000"' : ''; ?> >

                            <?php foreach ($attendanceCheck as $k => $val) { ?> 

                                <option value="<?php echo $k; ?>" <?= $str == $k ? 'selected ' : ''; ?>><?= $val; ?></option>
                            <?php } ?>

                        </select>

                    </td>
                    <td><input type="text" name="attend_remarks[]" id="attend_remarks" value="<?= $values['stu_status'] == 3 ? 'T.C.' : $values['attend_remarks']; ?>"/></td>
                    </tr>
                <?php  }
            } ?>

            <?php
            if (isset($this->category_data)) {
                $i = 1;
                foreach ($this->category_data as $key => $val) {
                    //echo "<pre>";print_r($val);exit;  
                   
                    ?>
                    <tr>
                        <td><?php
                    echo $i;
                    $i++;
                    ?>
                        </td>
                        <td><?php echo $val['students']; ?></td> 
                    <input type="hidden" name="stu_id[]" id="student_id" value="<?php echo $val['student_id']; ?>" /> 
                    <input type="hidden" name="grade[student_id][]" id="student_id" value="<?php echo $val['student_id']; ?>" />
                    <input type="hidden" name="grade[academic_id_<?php echo $val['student_id']; ?>][]" id="term_id1" value="<?php echo $val['academic_id']; ?>" />
                    <input type="hidden" name="grade[term_id_<?php echo $val['student_id']; ?>][]" id="academic_id1" value="<?php echo $val['term_id']; ?>" />
                    <input type="hidden" name="u_id[]" id="student_id" value="<?php echo $val['stu_id']; ?>" />
                    <td><?php echo $val['roll_no']; ?></td> 	
                    <input type="hidden" name="batch_code[]" id="batch_code" value="<?php echo $val['short_code'] ? $val['short_code'] : $val['batch']; ?>" />
                    <td><?php echo $val['short_code'] ? $val['short_code'] : $val['batch']; ?></td> 		

                    <td><?php echo $val['stu_id']; ?></td>
                    <td><?php echo $val['reg_no']; ?></td>
                    <td><?php echo $val['exam_roll']; ?></td>
                    <td>

                        <select id=attendance_status"<?php echo $i; ?>" name="attendance_val[]" class="attendance_status" <?= $str == "1" ? 'style="border:2px solid #ff0000"' : ''; ?> >

                            <?php foreach ($attendanceCheck as $k => $val) { ?> 

                                <option value="<?php echo $k; ?>" <?= $str == $k ? 'selected ' : ''; ?>><?= $val; ?></option>
        <?php } ?>

                        </select>

                    </td>  
                    <td><input type="text" name="attend_remarks[]" id="attend_remarks" value="<?= $values['stu_status'] == 3 ? 'T.C.' : $values['attend_remarks']; ?>"/></td>
                    </tr>

    <?php }
} ?>
            </tbody>
        </table>
    </div>
</div>
<script>

   


    $('body').on('change', ".attendance_status", function () {
        if (parseInt($(this).val()))
            $(this).css({"border": "2px solid #ff0000"});
        else
            $(this).css({"border": "1px solid #555"});
    });
     setDatatablesManual();
</script> 
