<style>
    .dailogBtn{
        background-color: lightcoral;
    }
    #wrapper{
          min-height: 104px !important;
    }
    .ui-dialog-titlebar { display: none; }
    .ui-dialog{
        width: 400px !important;
  
    }
    ui-widget-content {
    border: 2px solid lightcoral;
    }  
    
</style>
<style>
    .ui-datepicker-calendar {
    display: none;
    }
</style>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<div class="right_col">
    
<div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
    <?php if ($this->type) { ?>
        <div class="padding-md ">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-sm-12">
                        <div class="col-sm-6">
                            <h3 class="page-title txt-color-blueDark" >
                                <div><i class="fa fa-eye">Monthly (Offline) Attendance</i></div>
                            </h3>
                    
                        </div>
                    
                        <!--<div class="col-sm-3" style="margin-top:15px;">    <span><b>PREVIOUS FORM</b></span>
                             <input type="checkbox" id="payment" value="1"  checked data-toggle="toggle" data-size="sm">
                       </div>
                          
                        <div class="col-sm-3" style="margin-top:15px;">
                           <span><b>TR SWITCH</b></span>
                                    <input type="checkbox" id="trVal" value="1"  checked data-toggle="toggle" data-size="sm"> 
                        </div>-->
                     
                  
                    
                    <div class="x_panel">
                    

                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                            <div class="panel-body">
                                <?php
                                $hide_filter_block = '"';
                                if (in_array($this->role_id, $this->administrator_role)) {
                                    $hide_filter_block = '';
                                }
                                ?>
                                <div class="row" <?php echo $hide_filter_block; ?> >

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Academic Year</label>
                                            <?php echo $this->form->academic_year; ?>
                                        </div>
                                    </div>
                                     <?php echo $this->form->csrftoken; ?>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Session </label>
                                            <?php echo $this->form->session; ?>
                                        </div>
                                    </div>	
                                    
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Semester<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cmn_terms; ?>
                                        </div>
                                    </div>	
                                    
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Degree<span class="asterisk">*</span></label>
                                            <?php echo $this->form->degree_id; ?>
                                        </div>
                                    </div>	

                                    
                                    
                                </div>    
                                <div class="row">
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Course Category<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cc_id; ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Course Group<span class="asterisk">*</span></label>
                                            <?php echo $this->form->ge_id; ?>
                                        </div>
                                    </div>
                                    <div id="course_ids"></div>
                                    
                                   
                                    <!---<div class="col-sm-3 employee_class employee_id">
                                        <div class="form-group">
                                            <label class="control-label">Faculty<span class="asterisk">*</span></label>
                                            <?php echo $this->form->employee_id; ?>
                                        </div>

                                    </div>	--->

                                    <div id="term_ids"></div>

                                    
                                    
                                    <div class="col-sm-3 employee_class">
                                      <div class="form-group">
                                          <label class="control-label">Hon's Course<span class="asterisk"></span></label>
                                          <?php echo $this->form->department; ?>
                                      </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Department<span class="asterisk">*</span></label>
                                            <?php echo $this->form->department_id; ?>
                                        </div>
                                    </div>
                                    <div id="section_list">
                                        
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                      <div class="form-group">
                                          <label class="control-label">Attendance Month<span class="asterisk">*</span></label>
                                          <?php echo $this->form->effective_month; ?>
                                      </div>
                                    </div>
                                    
<!--                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                         <label class="control-label">Component Paper<span class="asterisk">*</span></label>
                                         <?php echo $this->form->component_paper; ?>
                                        </div>
                                    </div> -->
                                    <div class="col-sm-3 employee_class">
                                      <div class="form-group">
                                          <label class="control-label">Theory (Conducted class)<span class="asterisk">*</span></label>
                                          <input type ="text" data-toggle="number" class="form-control" name="theory"  value="<?=empty($this->result[0]['theory'])?0:$this->result[0]['theory'];?>"/>
                                      </div>
                                    </div> 
                                    <div class="col-sm-3 employee_class">
                                      <div class="form-group">
                                          <label class="control-label">Practical (Conducted class)<span class="asterisk">*</span></label>
                                          <input type ="text" data-toggle="number" class="form-control" name="practical"  value="<?=empty($this->result[0]['practical'])?0:$this->result[0]['practical'];?>"/>
                                      </div>
                                    </div> 
                                    <div class="col-sm-3 employee_class">
                                      <div class="form-group">
                                          <label class="control-label">Total Class Conducted<span class="asterisk">*</span></label>
                                          <?php echo $this->form->conducted_class; ?>
                                      </div>
                                    </div> 
                                     <button type="button" id="getStudentList" class="btn btn-primary" style="float: right; margin-top: 2em" value="0" >Get Student List</button>
                                    
                                   
                                </div>
                              
                                <div class="row" <?php echo $hide_filter_block; ?>>


                                    <div id="components_ids"></div>
                                </div>
                                <div class="" id="grade_data">
                                </div>
                                <input type="hidden" name="students_name" id="students_name" value="<?php echo $this->students_name; ?>"/> 
                                
                                <input type="hidden" name="grade_allocate_id" id="grade_allocate_id" value="<?php echo $this->grade_allocate_id; ?>" />
                            
                            </div>

                            <div class="panel-footer">									
                                <div class="row">
                                    <div class="col-sm-7 col-sm-offset-5">
                                        <?php if ($this->type == 'add') { ?> 
                                            <div style="float:left;margin-right:2px;">
                                                <button class="btn btn-primary submit" id="restirct">Submit</button>
                                            </div>
                                            <div style="float:left;padding:0px 10px;">
                                                <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                            </div>
                                        <?php
                                        } else {
                                            $login_empl_id = $this->login_storage->empl_id;


                                            if (!$this->isGradeReportPublished) {
                                                //  echo "<pre>";print_r($this->administrator_role); exit;
                                                if (($login_empl_id == $this->grade_detail['employee_id']) || in_array($this->role_id, $this->administrator_role)) {
                                                    ?>
                                                        
                                                    
                                                   
                                                    <?php
                                                }
                                            } else {
                                                echo '<div class="pull-right font-weight-bold">Grade is already published. You can\'t edit it</div>';
                                            }
                                            ?>
											<div style="float:left;">
												<button class="btn btn-primary submit">Update</button>
											</div>
                                            <div style="float:left;">
                                                <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>batch-attendance/index">Back</a>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                    </div>
                    </form>
                </div><!-- /panel -->
            </div><!-- /.col-->				
        </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                <strong>  <?php echo $this->escape($message); ?></strong>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
                
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Monthly (View) Attendance</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>		
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                   <!---<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>batch-attendance/index/type/add">Add </a>--->
                </div>
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
                
                <div class="x_title">
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">Academic Year</label>-->
                            <?php echo $this->form->academic_year; ?>
                        </div>
                    </div>
                    
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">Session </label>-->
                            <?php echo $this->form->session; ?>
                        </div>
                    </div>	
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label">Semester </label>-->
                            <?php echo $this->form->cmn_terms; ?>
                        </div>
                    </div>	
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">Attendance Month </label>-->
                            <?php echo $this->form->effective_month; ?>
                        </div>
                    </div>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                          <!--  <label class="control-label">Degree </label>-->
                            <?php echo $this->form->degree_id; ?>
                        </div>
                    </div>	
                   
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label">Course Category<span class="asterisk">*</span></label>-->
                            <?php echo $this->form->cc_id; ?>
                        </div>
                    </div>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">Course Group<span class="asterisk">*</span></label>-->
                            <?php echo $this->form->ge_id; ?>
                        </div>
                    </div>
                    
                    <div id="course_ids"></div>
                    
                    <div class="col-sm-3 employee_class">
                       <div class="form-group">
                          <!-- <label class="control-label">Hon's Course<span class="asterisk"></span></label>-->
                           <?php echo $this->form->department; ?>
                       </div>
                    </div>
                    <div class="col-sm-12 employee_class pull-right">
                       <div class="form-group">
                           
                          <button type="button" id="getRecords" class="btn btn-primary" style="float: right; margin-top: 2em" value="0" >Get Records</button>
                       </div>
                    </div>
                    
                 
                    
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData"> 
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Batch-Name</th>
                                    <th>Semester</th>  
                                    <th>course Category</th>  
                                    <th>Course</th>   
                                    <th>Section</th>   
                                    <th>Attendance Month</th>
                                    <th class="no_print">Action</th>
                                    <th class="no_print">Delete Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['batch']; ?></td>
                                            <td><?php echo $results['term_name']; ?></td>
                                            <td><?php echo $results['cc_name']; ?></td>
                                            <td><?php  if(empty($results['department'])){ echo $results['course_name'];}else{ echo $results['department'];
                                            }?></td>
                                            </td>
                                            <td><?php echo $results['sectionName']; ?></td>
                                            <td style="text-align:center">
                                                <?php
                                                  
                                                   echo date("F Y", strtotime( $results['effective_date']));
                                                    //echo $results['effective_date']; 
                                                ?>
                                            </td>
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>batch-attendance/index/type/edit/id/<?php echo md5($results['id']); ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></td>
                                            <td style="text-align:center">
                                                    <input type="hidden" value="<?= md5($results['id']); ?>" id="delete_id">
                                                   <button type="button" id="dailogBtn" class="btn btn-primary dailogBtn" value="0" >Delete</button>
                                                
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                               }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
      <div id="wrapper">
        <h2 style="color:solid black; font-size: 1.5em;">Are you sure to delete this record?</h2>
        <input type="hidden" value="<?= md5($results['id']); ?>" id="delMasterId">
        <br>
        <button type="button" id="deleteBtn" class="btn btn-primary dailogBtn" style="float: right" value="0" >Yes</button>
        <button type="button" id="noDeletebtn" class="btn btn-success" style="float: right" value="0" >No</button>
    </div>
<?php } ?>
</div>
<script> 
    $('body').on('change', "#trVal", function () {
        var value = $(this).parent().attr("class");
        //alert(value);
        if (value.includes("off")) {
            $(this).removeAttr("checked");
            $(this).val("0");
        } else
        {
            $(this).attr("checked", "checked");
            $(this).val("1");
        }
    });
    $('body').on('change', "#payment", function () {
        var value = $(this).parent().attr("class");
        //alert(value);
        if (value.includes("off")) {
            $(this).removeAttr("checked");
            $(this).val("0");
        } else
        {
            $(this).attr("checked", "checked");
            $(this).val("1");
        }
    });
    </script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
 <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" crossorigin="anonymous"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<script>
    //To filter Session
    $('body').on('change', '#academic_year', function () {
        $('#department').removeAttr('disabled');
        var year_id = $('#academic_year').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    
    
    $('body').on('change', '#course_id', function () {

        let course_id = this.value;
        let session = $('#session').val();
        let term_id = $('#cmn_terms').val();
        let ge_id= $('#ge_id').val();
        //alert(course_id);
        if(ge_id== 24 || ge_id== 27 || ge_id==26){
            if(course_id != 14){
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-section'; ?>',
                    data: {course_id: course_id, session: session, term_id: term_id}
                }).done(function (data) {
                    $('#section_list').empty('');
                    $('#section_list').html(data).trigger("chosen:updated");
                });
            }
        }


    });
    
    $('#department').on('change', function() {
    $('.load-box').css('display','block');
    let teacher_dept= this.value;
    let session= $('#session').val();
    let term_id= $('#cmn_terms').val();
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-section'; ?>',
        data: {teacher_dept:teacher_dept,session:session,term_id:term_id}
    }).done(function( data ) {
        $('#section_list').empty('');
        $('#section_list').html(data).trigger("chosen:updated"); 
        $('.load-box').css('display','none');
    });
    

});
    //To delete daily Attendance: 11 Aug 2020
    $('#wrapper').dialog({
        autoOpen: false,
        //title: 'Basic Dialog'
    });
    $('#noDeletebtn').click(function () {
        $('#wrapper').dialog('close');
        return false;
    });
    $('.dailogBtn').click(function() {

        let delete_id = $(this).closest("td").find("#delete_id").val();
        $('#wrapper').dialog('open');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-monthly-attend'; ?>',
            data: {delete_id:delete_id}
        }).done(function (data) {
            $('#delMasterId').empty();
            $('#delMasterId').val(data);
            //alert(data);

        });  

        return false;
    });

    $("#deleteBtn").click(function() {
        let delMasterId = $('#delMasterId').val();
        if(delMasterId){
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-delete-monthly-attend'; ?>',
                data: {delete_id:delMasterId}
            }).done(function (data) {
              alert('Record is deleted');
              window.location.reload();
            });
        }
    });
    //End
    
    
    
    
    let checkStudentData= $('#studentData').val();
    let checkgradeData= $('#grade_data').val();
    if(!checkStudentData || !checkgradeData){
         $('#restirct').prop('disabled', true);
    }else{
        $('#restirct').prop('disabled', false);
    }
    //End 
    $('body').on('change', '#cmn_terms,session', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
    });
    
    $('#conducted_class').css("background-color", "#D3D3D3");
   
        
    $(window).on('load', function() {
       //alert('hello'); 
		let degree_id= $('#degree_id').val();
        var cc_id = $('#cc_id').val();
        var cc_id_InArray = ["1", "7", "11","16","17","18"];
		if(degree_id == 1){
			
			if(jQuery.inArray(cc_id, cc_id_InArray)!='-1'){
            //alert(cc_id);
            $("#ge_id,#course_id").attr('disabled','disabled').trigger("chosen:updated");      
			}else{
				$("#ge_id,#course_id").removeAttr('disabled').trigger("chosen:updated");    
			}
			$("#course_id").removeAttr('disabled').trigger("chosen:updated");
		}else{
			$("#course_id").attr('disabled','disabled').trigger("chosen:updated");
		}
        
        var id  = '<?=!empty($this->id)?$this->id:'';?>';
        if(id){
            var totalConductedClass= $('#conducted_class').val();
            var totalAttendClass= $('#attended_class').val();
            var percent= Math.round((totalAttendClass/totalConductedClass)*100);
            $('#percent_sum').val(percent);
            $("#course_id").removeAttr('required').trigger("chosen:updated"); 
            $("#conducted_class,#percent_sum,#course_id").prop('readonly', true); 
            $('.percent_sum').css("background-color", "#eee");
//			$('.load-box').css('display','none');
        }
        
        //alert(percent);
    });
    

    $('body').on('change', '#department_id', function () {
        $("#course_id").removeAttr('required').trigger("chosen:updated"); 
        $("#course_id").attr('disabled','disabled').trigger("chosen:updated"); 
        var department_id = $('#department_id').val();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-employee'; ?>',
            data: {department_id: department_id}
        }).done(function (data) {

            $('#employee_id').empty('');
            $('#employee_id').html(data);

        });
    });
    // To check existed result
    $('body').on('keyup', '[name="theory"],[name="practical"]', function () {
        var term_id = $('#cmn_terms').val();
        var cc_id = $('#cc_id').val();
        var ge_id = $('#ge_id').val();
        var course_id = $('#course_id').val();
        var hons_id = $('#department').val();
        var effective_month = $('#effective_month').val();
        //var dateAr = selected_date.split('/');
        //var effective_date = dateAr[2] + '/' + dateAr[1] + '/' + dateAr[0];
        var id  = '<?=!empty($this->id)?$this->id:'';?>';
        //alert(ge_id);
        if(!id){
            
            //alert(effective_date);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-existed-batch-attendance'; ?>',
                data: {term_id: term_id, course_id: course_id,effective_month:effective_month,hons_id:hons_id,ge_id:ge_id,cc_id:cc_id}
            }).done(function (data) {

                if((data!='')){
                    //alert(data);
                    alert("Batch Attendance For this month already made!");
                    $('#cmn_terms').val(''); 
                    $('#effective_month').val('');
                    $('#course_id').val('');
                    $('[name="theory"]').val('');
                       
                }  
            });
        }
    });
    


    $('body').on('change', '#cc_id', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
        let cc_id = $('#cc_id').val();
        let degree_id = $('#degree_id').val();
        let term_id = $('#cmn_terms').val();
        let employee_id= '<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>'; 
        if (cc_id == 2) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group-with-empl-for-daily'; ?>',
                data: {cc_id: cc_id,degree_id:degree_id,employee_id :employee_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }else{
             $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group'; ?>',
                data: {cc_id: cc_id, term_id: term_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }
        if(degree_id){
        //alert(degree_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-dept-with-empl'; ?>',
                data: {degree_id: degree_id,employee_id : employee_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data).trigger("chosen:updated");
                $('.load-box').css('display','none');
            });
        }
    });


    
//Disable some field on change course Category(1)
    $('body').on('change', '#cc_id,#department', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
		let degree_id= $('#degree_id').val();
        var cc_id = $('#cc_id').val();
        var cc_id_InArray = ["1","5", "7", "11","16","17","18"];
		//alert(degree_id);
		if(degree_id == 1){
			
			if(jQuery.inArray(cc_id, cc_id_InArray)!='-1'){
				//alert(cc_id);
				$("#ge_id,#course_id").empty();
				$("#department").removeAttr('disabled').trigger("chosen:updated");
				$("#ge_id,#course_id").attr('disabled','disabled').trigger("chosen:updated");   
				$("#ge_id,#course_id").removeAttr('required').trigger("chosen:updated"); 
				
				
			}else{
				$("#department").empty();
				$("#department").attr('disabled','disabled').trigger("chosen:updated");
				$("#ge_id,#course_id").removeAttr('disabled').trigger("chosen:updated"); 
				$("#ge_id,#course_id").attr('required',true).trigger("chosen:updated"); 
					
			}
			$("#course_id").removeAttr('disabled').trigger("chosen:updated");
		}else{
			$("#course_id").attr('disabled','disabled').trigger("chosen:updated");
		}			
    });

//End
//to get course on basis of  ge id
    $('body').on('change', '#ge_id', function () {
     
        $('#grade_data').empty('');
        $('#studentData').empty('');
        $('#course_ids').empty('');
        $('.load-box').css('display','block');
        var employee_id = '';
        var department_id = '';
        var department = '';
        var ct_id = $('#cc_id').val();
        var ge_id = $('#ge_id').val();
        var term_id = $('#cmn_terms').val();
        //alert('ge');
        if(ge_id == 25){
             $("#department").removeAttr('disabled').trigger("chosen:updated");
              $('.load-box').css('display','none');
        }else{
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-base-of-course'; ?>',
            data: {Ct_id: ct_id, employee_id: employee_id, department_id: department_id, term_id: term_id, ge_id: ge_id, cc_dept: department}
        }).done(function (data) {
            
           $('#course_ids').html(data);
            $(".chosen-select").chosen();
            var exists=$('#course_ids option[value]').length;
            //alert(exists);
            $('.load-box').css('display','none');
            if(exists > 1){
            $("#department").empty();
            $("#department").attr('disabled','disabled').trigger("chosen:updated");
            }else{
                $("#department").removeAttr('disabled').trigger("chosen:updated");
            }
        });
        }
    });
    
//To get  course category and department on degree change

    $('body').on('change', '#degree_id', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
        var degree_id = $('#degree_id').val();
         $('.load-box').css('display','block');
        $('#cc_id').empty();
        if (degree_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Dept'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data);
                $('.load-box').css('display','none');
            });
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-course-cat'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                    // alert(data);
                    $('#cc_id').html(data).trigger("chosen:updated");
                    $('.load-box').css('display','none');
                
            });
        }
    });
    
    $('body').on('keypress mousedown','input[name^="attended_class"],#conducted_class,.c_percent,input[name^="percent_sum"]',function(e){
        event.preventDefault();
       
    });
    
       
   $('body').on('keyup','input[name="theory"],input[name="practical"]',function(){
	  
       var theory = isNaN(parseInt($('input[name="theory"]').val()))?0:parseInt($('input[name="theory"]').val());
       var practical = isNaN(parseInt($('input[name="practical"]').val()))?0 : parseInt($('input[name="practical"]').val());
      var total =  theory  + practical ;
       $('#conducted_class').val(total);
   });
$('body').on('click','.sorting_desc,.sorting_asc',function(){
 $('.load-box').css('display','block');
var x = 1;
    $('th[id^="total"]').each(function(col){
        var id = $(this).attr('id');
      
$('input[data-id="#'+id+'"]').each(function(e){
            $(this).attr('tabindex',(x));
            x+=1;
    });
});
$('.load-box').hide();
});

//Semester end Attendance Filter code : Date: 26 March 2020 :Kedar
var default_type  = '<?= $this->type ?>';

//alert(default_type);
if(!default_type){
   
    $(function() {
        $('.monthYearPicker').datepicker( {
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'mm-yy',
            onClose: function(dateText, inst) { 
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(year, month, 1));
            }
        });
    });
    
    //Data on Employee Id : date: 12 Nov 2020: Kedar
    $('body').on('change', '#cc_id', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
        let cc_id = $('#cc_id').val();
        let degree_id = $('#degree_id').val();
        let term_id = $('#cmn_terms').val();
        let employee_id= '<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>'; 
        
        if(degree_id){
        //alert(degree_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-dept-with-empl'; ?>',
                data: {degree_id: degree_id,employee_id : employee_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data).trigger("chosen:updated");
                $('.load-box').css('display','none');
            });
        }
        
        if (cc_id == 2) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group-with-empl-for-daily'; ?>',
                data: {cc_id: cc_id,degree_id:degree_id,employee_id :employee_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }else{
            $('.monthYearPicker').datepicker();
            $('#monthPick').datepicker({
                format: "mm/yyyy",
                viewMode: "months", 
                minViewMode: "months"
            });
        
             $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group'; ?>',
                data: {cc_id: cc_id, term_id: term_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }
        
    });
    
    //End
    
    $('#getRecords').on('click',function () {
        $('#studentData').empty('');
        var term_id = $('#cmn_terms').val();
        var course_id = $('#course_id').val();
        var cc_id = $('#cc_id').val();
        var ge_id= $('#ge_id').val();
        var hons_id = $('#department').val();
        var session = $("#session").val();
        var degree_id= $("#degree_id").val();
		 var selected_date = $('#effective_month').val();
        var dateAr = selected_date.split('-');
        var effective_date = dateAr[1] + '-' + dateAr[0];
        let employee_id= '<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>'; 
        //alert(effective_date);
        if(session && term_id && degree_id && effective_date){
            $('.load-box').css('display','block');
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-monthly-wise-Student'; ?>',
                data: {session:session,term_id:term_id,degree_id:degree_id,effective_date:effective_date,cc_id:cc_id,ge_id:ge_id,hons_id:hons_id,course_id:course_id,employee_id:employee_id}
            }).done(function( data ) {
                $('.load-box').css('display','none');
                $('#studentData').empty('');
                //alert(data);
                $('#studentData').html(data);     
            });
        }else{
            alert('Please select the required field.');
        }
      
    });
}else{
	//to get monthly attendace
	
    $('body').on('click','#getStudentList', function () {
        var employee_id = $('#employee_id').val();
        var department_id = $('#department_id').val();
        var honors_id = $('#department').val();
        var ct_id = $('#ge_id').val();
        var term_id = $('#cmn_terms').val();
        var degree_id = $('#degree_id').val();
        var course_id = $('#course_id').val();
        var session = $("#session").val();
        var section = $("#section").val();
        var tabId = $("#trVal").val();
        let pay = $('#payment').val();
        //alert(academic_id);
        //alert(default_type);
        $('#restirct').prop('disabled', false);
        $('.load-box').css('display','block');
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-monthly-students-details'; ?>",
            data: {employee_id: employee_id, department_id: department_id, ct_id: ct_id, term_id: term_id, course_id: course_id,session_id: session,degree_id:degree_id,honors_id:honors_id,section:section,tabId:tabId,pay:pay}
        }).done(function (data) {
           
            $('.load-box').css('display','none');
            $('#grade_data').empty('');
            
            $("#grade_data").html(data);
             //setDatatablesManual();
        });
        if(course_id){
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-code'; ?>",
            data: {course_id: course_id}
        }).done(function (data) {
            if(data){
                
            $("<div id='course_container'style='background-color: rgb(253, 245, 154); display: block;' class='col-md-3 text-center'><h2>"+data+"</h2></div>").insertAfter("#dataTable_length");
            }else{
                $("<div id='course_container'style=' display: none;' class='col-md-3 text-center'>");
            }
        });
        }
    });
//End
    $(function() {
        $('.monthYearPicker').datepicker( {
            changeMonth: true,
            changeYear: true,
            showButtonPanel: true,
            dateFormat: 'mm-yy',
            onClose: function(dateText, inst) { 
                var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                $(this).datepicker('setDate', new Date(year, month, 1));
            }
        });
    });
   
   var employee_id = $('#employee_id option:selected').val();
    var department_id = $('#department_id option:selected').val();
    var academic_year_id = $('#academic_id option:selected').val();
    var grade_allocate_id = $('#grade_allocate_id').val();
    var department = $('#department').val();
    var session = $('#session').val();
    var ct_id = $('#cc_id option:selected').val();
    var ge_id = $('#ge_id option:selected').val();
    var term_id = $('#cmn_terms option:selected').val();
    var id  = '<?=!empty($this->id)?$this->id:'';?>';
    var courseIdSelected= '<?= $this->course_id; ?>';
    
    if (term_id) {
          $('.load-box').css('display','block');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-base-of-course'; ?>',
            data: {Ct_id: ct_id, employee_id: employee_id, department_id: department_id, term_id: term_id, ge_id: ge_id, cc_dept: department}
        }).done(function (data) {

            
            $('#course_ids').html(data);
            $(".chosen-select").chosen();
       
            $('#course_id').val(<?=$this->course_id;?>);
                getstudents();
            
            });
             
            $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-section'; ?>',
            data: {teacher_dept:department,session:session,term_id:term_id,course_id:courseIdSelected}
        }).done(function( data ) {

            $('#section_list').empty('');
            $('#section_list').html(data);
            $('#section').val(<?=$this->section;?>).trigger("chosen:updated"); 
            //var ge_id = $('#ge_id').val();
            getstudents();
                
            
            });
            
       

    }
}
function getstudents(){
     var term_id = $('#cmn_terms').val();
            var course_id = $('#course_id').val();
            var session_id = $('#session').val();
            var degree_id = $('#degree_id').val();
            if(department != 0){
                        $('#course_id').attr('disabled','disabled');
                        $('#course_id').removeAttr('required');
                    }
            if (course_id != '' || department) {
                
                $.ajax({
                    type: "POST",
                     url: "<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-monthly-students-details'; ?>",
                    
data: {employee_id: employee_id, department_id: department_id, ct_id: ct_id, term_id: term_id, course_id: courseIdSelected, honors_id: department, session_id: session_id, grade_allocate_id: grade_allocate_id,id:id,degree_id:degree_id}
                }).done(function (data) {
                    $('#grade_data').empty('');	
                    $("#grade_data").html(data);
                    $('.load-box').css('display','none');
                        
                });
    }
}
var table = '';
      setDatatablesManual();
       function setDatatablesManual(){
      $.fn.dataTable.ext.search.push(
    function( settings, data, dataIndex ) {
        var min = parseInt( $('#manualmin').val(), 10 );
        var max = parseInt( $('#manualmax').val(), 10 );
        var age = parseFloat(data[2]) || 0; // use data for the age column
 
        if ( ( isNaN( min ) && isNaN( max ) ) ||
             ( isNaN( min ) && age <= max ) ||
             ( min <= age   && isNaN( max ) ) ||
             ( min <= age   && age <= max ) )
        {
            return true;
        }
        return false;          
    }
);
   
  table = $('#dataTable').DataTable({
       "pageLength": -1,
        
    });
}

 // Event listener to the two range filtering inputs to redraw on input
            $('#manualmin, #manualmax').keyup(function () {
                //alert("hello");
                table.draw();
            });

            $('#manualmin, #manualmax').change(function () {
                //alert("hello");
                table.draw();
            });

    //End
    
    //Dsiable Editing In Core Course Learning Date : 25 Oct 2021
    let type='<?= $this->type ?>';
    if(type == 'edit'){
        //disable the field
        
        $("#academic_year").prop( "disabled", true ); 
        $("#session").prop( "disabled", true ); 
        $("#cmn_terms").prop( "disabled", true ); 
        $("#degree_id").prop( "disabled", true ); 
        $("#cc_id").prop( "disabled", true ); 
        $("#effective_month").prop( "disabled", true ); 
        
    

        //right before the form submits, we re-enable the fields, to make them submit.
        $( "#formValidate1" ).submit(function( event ) {
        $("#academic_year").prop( "disabled", false );
        $("#session").prop( "disabled", false );
        $("#cmn_terms").prop( "disabled", false );
        $("#degree_id").prop( "disabled", false );
        $("#cc_id").prop( "disabled", false );
        $("#effective_month").prop( "disabled", false );
 
    });   
    }
//End
</script>
