<style>
    #Auto_no{
        display:none;
    }
    
    </style>
<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12 " >
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Rating Master</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
						  <div class="row">

							<div class="col-sm-3 employee_class">
                            <div class="form-group" >
                            <label  class="control-label" >Rating Id<span class="asterisk">*</span></label>
                            <?php echo $this->form->Auto_no; ?>
                            <?php echo $this->form->Auto_no1; ?>
                            </div>
							</div>
						
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">Name / Description<span class="asterisk">*</span></label>
                            <?php echo $this->form->text_filed; ?>
                            </div>
							</div>
                                                      
                                                      
                                                      
                                                      <div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">Rating Value<span class="asterisk">*</span></label>
                            <?php echo $this->form->rating_value; ?>
                            </div>
							</div>
                                                      
                                                                                                            <div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">status<span class="asterisk">*</span></label>
                            <?php echo $this->form->status; ?>
                            </div>
							</div>
							
							</div>
       <div id="fields">
         <div class="padding-top"></div>
        </div>  
					</div>
					<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>fee-heads/index/">Back</a>
										</div>
										<?php }		?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars">Rating Master</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>rating-master/index/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Fee Heads</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
				<thead>
					<tr>
						<th style="text-align:center;">Rating Id</th>	
						<th style="text-align:center;">Description</th>
						<th style="text-align:center;">Value</th>
						<th style="text-align:center;">Status</th>
                        <th class="no_print" style="text-align:center;">Edit</th>
					</tr>
				</thead>
				<tbody style="text-align:center;">
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						//print_r($results);die;

					?>
							<tr>
								<td><?php echo $results['Auto_no']; ?>
								</td>						
								
								
								<td><?php echo $results['text_filed']; ?></td>
								
								<td><?php echo $results['rating_value']; ?></td>
                                                                <td><?php echo $results['status']; ?></td>
                                                                
								
								<td><a href="<?php echo $this->mainconfig['host']; ?>rating-master/index/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>	
 
	
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}


/*
var count = $('#count_val').val(); //Addmore script code

$("body").on("click","#AddButton",function(event){
		var count_value = count++;
		//alert(count_value);
		append_html = '<div class="row">';
		
		append_html += '<div class="col-sm-3 employee_class" style=""><label class="control-label "></label><input type="text"  class="form-control ec"  name="Fee[feehead_name][]"  style=" background:#FFFFFF;" label="feehead_name_'+count_value+'"   /></div>';
		append_html += '<a href="#" class="removeclass6 btn btn-primary remove_class6 " style="padding:7px 15px;margin:20px 15px;">-</a>';
		append_html += '</div>';	
        $('#count_val').append(count_value);		
		$('#fields').append(append_html);
		
		});
		$("body").on("click",".removeclass6", function(e){
		//alert('sdsd');

                $(this).parent('div').remove(); 				
				
        return false;

    });  */
	

</script>
