<table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                            <thead>
                                <tr>

                                    <th class="no-sort">S.No.</th>

                                    <th>Student Name</th>
                                    <th>Class Roll</th>
                                    <th>Form Id</th>
                                    <th> Exam Roll</th>
                                    <th>Semester</th>
                                    <th>No. Of Installment</th>
                                    <th>Total Amount</th>
                                    <th>Paid Amount</th>
                                    <th>Due Amount</th>
                                    <th>Type(Regular/Installment)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    //echo '<pre>'; print_r($this->semester);exit;
                                    foreach ($this->paginator as $results) {
                                        $total_fees=round($results['fee']+$results['due_amount']);
                                        $due_fees = round($total_fees-$results['paid_fees']);
                                        //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['stu_fname']; ?></td>
                                            <td><?php echo $results['roll_no']; ?></td>
                                            <td><?php echo $results['stu_id']; ?></td>
                                            <td><?php echo $results['exam_roll']; ?></td>
                                            <td><?php 
                                                 switch ($this->semester) {
                                                    case "t1":
                                                      echo "Sem-1";
                                                      break;
                                                    case "t2":
                                                      echo "Sem-2";
                                                      break;
                                                    case "t3":
                                                      echo "Sem-3";
                                                      break;
                                                    case "t4":
                                                      echo "Sem-4";
                                                      break;
                                                    case "t5":
                                                      echo "Sem-5";
                                                      break;
                                                    case "t6":
                                                      echo "Sem-6";
                                                      break;
                                                    default:
                                                      echo "n/a";
                                                }
                                                ?>
                                            </td>
                                            <td><?php echo !empty($results['total_installment']) ? $results['total_installment'] :'<b style="color:blue">Description Missing </b>' ; ?></td>
                                            <td><?php echo $total_fees; ?></td>
                                            <td><?php echo $results['paid_fees']; ?></td>
                                            <td><?php echo $due_fees; ?></td>
                                            <td><?php echo !empty(ltrim($results['description'],"1st ")) ? ltrim($results['description'],"1st ") :'<b style="color:blue">Description Missing </b>' ; ?></td>
                                            
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="6">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
<script>
   
    setDatatables();
</script>