<table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" >
                            <thead>
                                <tr>

                                    <th class="no-sort">S.No.</th>

                                    <th>Student Name</th>
                                    <th>Class Roll</th>
                                    <th>Form Id</th>
                                    <th> Exam Roll</th>
                                    <th>Semester</th>
                                    <th>Exam Fee</th>
                                    <th>Paid Amount</th>
                                    <th>Exam Due Amount</th>
<!--                                    <th>Tuition Due Amount</th>-->
                                    <th>Eligible</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                  if($this->examFee !=''){
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>';print_r($results);exit;
                                     //$total_fees=$this->semFee;
                                     $exam_fees=$this->examFee;
                                     //$pay=$this->payment;
                                     
                                     
//                                     $due_fees = round($total_fees-$results['paid_fees']);
//                                     if($pay=='1' && $due_fees >0) {
//                                      echo $pay; die();
//                                     continue;
//                                     }
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['stu_fname']; ?></td>
                                            <td><?php echo $results['roll_no']; ?></td>
                                            <td><?php echo $results['stu_id']; ?></td>
                                            <td><?php echo $results['exam_roll']; ?></td>
                                            <td><?php 
                                                 switch ($this->semester) {
                                                    case "t1":
                                                      echo "Sem-1";
                                                      break;
                                                    case "t2":
                                                      echo "Sem-2";
                                                      break;
                                                    case "t3":
                                                      echo "Sem-3";
                                                      break;
                                                    case "t4":
                                                      echo "Sem-4";
                                                      break;
                                                    case "t5":
                                                      echo "Sem-5";
                                                      break;
                                                    case "t6":
                                                      echo "Sem-6";
                                                      break;
                                                    default:
                                                      echo "n/a";
                                                }
                                                ?>
                                            </td>
                                             <td><?php echo $results['exam_fee']; ?></td>
                                            <td><?php 
                                               $paidfee = new Application_Model_UgNonformSubmissionModel();
                                              $payfee=  $paidfee->getPaidRecordbyfid($results['stu_id'],$results['term_id']);
                                              if($payfee) { echo $exam_fees+$results['late_fine'] ; } else { 
                                              echo '0'; }?></td>
                                            <td><?php if($payfee) { echo '0' ; } else { 
                                              echo $exam_fees; } ?></td>
<!--                                            <td><?php 
                                              //echo $due_fees;  ?></td>-->
                                            <td class="<?php echo (!empty($payfee)) ? 'text-success' :'text-danger' ; ?>"><?php echo (!empty($payfee)) ? 'Yes' :'No' ; ?></td>
                                            
                                        </tr>            

                                    <?php
                                    
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="6">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } }?>

                            </tbody>
                        </table>
<script>
   
    setDatatables();
</script>