<table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" >
                            <thead>
                                <tr>

                                    <th class="no-sort">S.No.</th>
                                    <th>Form Id</th>
                                    <th>Student Name</th>
                                    <th>Father Name</th>
                                    <th>Mother Name</th>
                                    <th>Class Roll</th>
                                    <th>Board / University (Last Exam)</th>
                                    <th>Department</th>
                                    <th>Programme</th>
                                    <!--<th>Exam Roll</th>-->
                                    <th>Status</th>
                                    <th>Paid Amount</th>
                                     <th>Total Amount</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->students) != 0) {
                                    $academic = new Application_Model_Academic();
                                foreach($this->students as $student){
                                    $check = false;
                                    $batch = $academic->getAcademicdepartment($student['academic_id']); ?>
                                    <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						
                                            <td><?php echo $student['stu_id']; ?></td>
                                            <td><?php echo $student['stu_fname']; ?></td>
                                            <td><?php echo $student['father_fname']; ?></td>
                                            <td><?php echo $student['mother_fname']; ?></td>
                                            <td><?php echo $student['roll_no']; ?></td>
                                            <td><?php echo $student['university']; ?></td>
                                            <td><?php echo $batch['department']; ?></td>
                                            <td><?php echo $batch['department_type']; ?></td>
                                             <!--<td><?php echo $student['exam_roll']; ?></td>-->
                                              <td class="text-center" style="vertical-align: middle;" >
                                               <?php 
                                               echo($student['stu_status'] == 1 
                                                    ? "<b style='color:green;'>Active</b>" 
                                                    : ($student['stu_status'] == 2 
                                                        ? "<b>Discontinue</b>" 
                                                        : ($student['stu_status'] == 3 
                                                            ? "<b style='color:red;'>T.C</b>." 
                                                        : ($student['stu_status'] == 4 
                                                            ? "<b style='color:red;'>Alumni</b>." 
                                                        : ($student['stu_status'] == 5 
                                                            ? "<b style='color:red;'>Left</b>." 
                                                            : "<b>Block Marksheets</b>"))))); 
                                                ?>

                                            </td>
                                  <?php  foreach ($this->paginator as $results) {
                                        if($student['stu_id'] == $results['u_id']){
                                        //echo '<pre>'; print_r($results);
                                        ?>
                                        
                                           
                                            <td><?php echo $results['amt'] + $results['fine']; ?></td>
                                           
                                             <td><?php echo $results['examFee']; ?></td>
                                        </tr>            
                                        
    <?php $check = true ;
                                            break;
                                        } 
                                        
                                        
                                        
                                        
                                        
                                   } if(!$check){ ?>
                                
                             
                                        <td>0</td>
                                        
                                        <td>600</td>
                                            
                                           
                                            
                                        </tr>   
                        <?php  } }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="6">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
<script>
   
    setDatatables();
</script>