
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action "
               id="dataTable" border ='1' width="100%">
                    <thead><tr  id="header">
                            <th colspan="3" class="text-center course_code"></th>     
                            <th colspan="3" class="text-center">PATNA WOMEN'S COLLEGE, AUTONOMOUS, PATNA UNIVERSITY</th>     
                            <th colspan="3" class="text-center">Examination Date___________</th>     
                </tr>
            <tr >
                <th>S.No.</th>
                <th>Form Id</th>
                <th style="width: 15em">Student Name</th>
                <th>Exam Roll No.</th>
                <th>Registration No</th>
                <th>Copy Number</th>
                <th>Student Signature</th>
                <th>Invigilator Signature</th>
<!--                <th style='display:none'>Photo</th>-->
                <th  style="width: 50px;">Photo</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;
           $date=date('Y'); 
$backmodel =  new Application_Model_BackSelectionItems(); 
$backyear  = new Application_Model_Examchecker();
            if (count($this->paginator) != 0) {
//echo "<pre>";print_r($this->paginator);die;
 $studetails = array();
   $notstuarr = array('F-2019-10665','F-2019-10640','F-2019-10502');
                foreach ($this->paginator as $results) {
                   
                  if($this->exmtype=='2') {
                    
                    //   $getpreviousyear=  $backyear->getPreviousattemptyear($results['cmn_terms'],$results['session']);
                       $getpreviousyear = $backyear->getPreviousrecord($results['cmn_terms'],$results['session'],$results['academic_id'],$results['student_id']);
                    //   if($results['stu_id']=='F-2019-8478'){
                    //   echo "<pre>".$results['student_id']; print_r($getpreviousyear);exit();
                    //   }
                       if($getpreviousyear) {
                                if($date > $getpreviousyear['last_attempt_year'] && !in_array($results['stu_id'],$notstuarr)){
                                  continue;
                                }
                       }
                    else {
                        if($results['sem']!='t1'){
                      $getpreviousrecor=  $backyear->getPreviousrecord($results['cmn_terms'],$results['session'],$results['academic_id'],$results['student_id']);
                      //echo "<pre>";print_r($getpreviousrecor);die;
                    //     if($results['student_id']='1292') {
                    //  echo "<pre>";print_r($getpreviousrecor);die;
                    //     }
                   if($getpreviousrecor) {
                      if($date > $getpreviousrecor['last_attempt_year']){
                          continue;
                    }
                        }
                    }
                      
                    }
                  } 
                   
                    ?>
                    <tr>
                        <td><?php echo $i;
                        $studetails['sno'][] =$i;
                    $i++;
                    ?>
                        </td>						

                        <td><?php echo $results['stu_id']; ?></td>
                        <td><?php echo $results['stu_fname']; ?></td>
                        <td><?php echo $results['exam_roll']; ?></td>
                        <td><?php echo $results['reg_no']; ?></td>
                        <td ></td>
                        <td></td>
                        <td></td>

                        <td ><img class="img img-rounded" data-base64 ="<?=$src;?>"  src="<?php echo $this->mainconfig['host'] . $results['filename']; ?>" width="100px" height="70px" alt="img"></td>

                    </tr>            

                <?php
                
                
                    
                    
                } 
             
            }
            ?>

        </tbody>
</table>

<script>

setDatatables();

</script>
