<?php
$stu_details = $this->stu_details;
$ref_grade_item = new Application_Model_ReferenceGradeMasterItems();
$url = $this->url;
$passmarks = $this->passpercent;

$sl_no = $this->gradesheet_number;
//===============[WIDTHS]
$marks_width = '20px';
$marks_width1 = '20px';
$marks_width4 = '25px';
$marks_width3 = "14px";
$total_width = "10px";
$single_pr = $this->single;
$cgpaf = array();
$academic_model = new Application_Model_Academic();
$academic_details = $academic_model->getRecord($stu_details['academic_id']);
$d_id = $academic_details['department'];
$deg_details = new Application_Model_Department();
$degree_id = $deg_details->getRecord($d_id)['degree_id'];
?>
<style>
    .sub{
        font-size:0.75em;
        border:.01em solid #932e90;
        text-align: center;;  
    }
    .course_credit>span{
        display:inline;
        width:50%;
    }
</style>



<div class="grade-data-container" style="margin-top:10px;">
    <table class="tablestyle1" width="100%" cellspacing ="0" >
        <thead>
            <tr>
                <th class="sub" colspan="4">Course Title</th>
            </tr>
            <tr>
                <?php
                $department_details = $deg_details->getRecord($d_id);
                ?>
                <th class="sub" >SUBJECT</th>
                <th class="sub" style='text-align:center;' colspan ="3"><?php if(in_array($d_id,array(15,30))){?><?=$academic_details['batch_code'];?><?php }else{ ?><?=$academic_details['batch_code'];?>&mdash;<?= $department_details['description']; }?></th>
            </tr>
            <tr>
                <th class="sub">Semester</th>
                <th class="sub"> Paper Code</th>
                <th class="sub" colspan=2>Course Name</th>
            </tr>
        </thead>

        <tbody> 





            <?php
            if (!$single_pr) {
                foreach ($this->term_marks as $term_index => $term_id) {
                    //  echo "<pre>"; print_r($this->term_marks);exit;
                    //====chnage according to term id iterate====//
                    $term_pr_id = $term_id;
                    $term_details = $this->stu_term_details[$term_pr_id];
                    $stu_marks = $this->student_marks_details[$term_pr_id];
                    $non_term = $term_one = $promo_one = $sgpa_one = $course_group_arr = array();
                    $empty_cell_prin_len = count($header_component);
                    $all_total = $ob_total = $cr_total = $gr_total = $crp_total = 0;
                    $sgpa_span = $this->sgpaspan[$term_details['term_id']]['sgpa_span'];
                    foreach ($stu_marks as $key => $value) {
                        if ($key == 1 && in_array($term_pr_id, array(310, 314))) {
                            $key = 2;
                        } else if ($key == 2 && in_array($term_pr_id, array(310, 314))) {
                            $key = 1;
                        }
                        $courseMaster = new Application_Model_Course();
                        $course_details['course_code'] = '';
                        $course_details['course_name'] = '';
                        $course_details1['course_code'] = '';
                        $course_details1['course_name'] = '';
                        $course_details = $courseMaster->getRecord($stu_marks[$key]['course_id']);
                        ?>
                        <tr>
                            <?php
                            if (!in_array($sgpa, $term_one)) {
                                $term_one[] = $sgpa;
                                ?>

                                <th class='sub' width="<?= $marks_width; ?>" style="width:20px !important" rowspan="<?= $sgpa_span + (count($stu_marks) - $sgpa_span); ?>"><?= $term_details['term_name']; ?></th>
                            <?php } $course_code = !empty($course_details['course_code']) ? "{$course_details['course_code']}  " : ''; ?>

                            <?php if (strpos($course_details['course_code'], "Course 11")) { ?>
                                <td>Optional Course</td>
                                <td><?= htmlentities($course_details['course_name']); ?></td>
                            <?php } else { ?>
                                <td class="sub" style="text-align:left"><?= $course_code; ?></td>
                                <td class="sub" colspan = "2" style="text-align:left"> <?= htmlentities($course_details['course_name']); ?></td>
                            <?php } ?>


                        </tr>

                        <?php
                    }
                }
                ?>
                        <?php if($degree_id == 1 && !$this->year_id){ ?>
                <tr>
                    <th colspan="4" class="sub">NON-ACADEMIC CREDIT</th> 
                    <?php
                    $nonAcadCourse = new Application_Model_NonAcademicCourse();
                    $courseList = $nonAcadCourse->getRecordsBySessionforBackPage($academic_details['session']);
                    $studentCredit = new Application_Model_NonAcademicCreditCourseAllotmentModel();
                    
                    $credit_course = $studentCredit->getRecordbystuId($stu_details['stu_id']);
                    $studentCreditCourse = explode('/',$credit_course['credit_course']);
                    $rows = 3;
                    $column = (int)($courseList['total']/3);
                    ?>
                </tr>
                <!--<tr>-->
                <!--    <td colspan="4" style="padding: 0;">-->
                <!--        <table  width="100%" cellspacing ="0" >-->
                <?php $inc = 0; $arr_course =  explode('/',$courseList['credit_course']); ?>
                <?php 
                preg_match('/^F-2018-\d{1,}/', $stu_details['stu_id'], $output_array);
                if(!empty($output_array[0])){ ?>
                <tr>
                    <td colspan="4" class="sub" style="padding: 0;">
                        <?php echo  $courseList['credit_course']; ?>
                    </td>
                </tr>
                <?php }else{ ?>
                <tr>
                    
                    <?php for($j = 0; $j<$rows;$j++){ ?>
                    <?php if($j==($rows-1)){ ?>
                    <td class="sub " colspan="2"  style="text-align:left;">
                        <?php } else { ?>
                        <td class="sub " colspan="1" style="text-align:left;padding:0;">
                            
                        <?php } ?>
                        <table style="width:100%" cellspacing = 0>
                            <?php for($i=0;$i<$column;$i++){ ?>
                            
                            <tr style="width:100%" class="course_credit">
                                
                                  <?php if(in_array($arr_course[$inc],$studentCreditCourse)){ ?>
                       <td class="sub" style="text-align:left"> <?php echo $arr_course[$inc]; $inc++; ?></td> <td class="sub" style="width:25px"><span style='font-family:helvetica; color:blue; font-size:12px;'>&#10004;</span></td >
                        <?php } else{ ?>
                        <td class="sub" style="text-align:left"><?php echo $arr_course[$inc]; $inc++; ?> </td><td class="sub" style="width:25px"><span style='font-family:helvetica; color:blue; font-size:12px;'>X</span></td>
                        <?php } ?>
                            </tr>
                            
                            <?php } ?> 
                            
                        </table>
                      
                    </td>
                    <?php } ?>
                    
                </tr>
                
          
                <!--</table>-->
                <!--</td>-->
                <!--</tr>-->
                        <?php 
                }
                        } ?>
                <tr>
                    <th colspan="4" class="sub">GRADING OF MARKS</th> 
                </tr>   
                <tr>
                    <th  class="sub">Letter Grades</th> 
                    <th  class="sub">Attributes</th> 
                    <th  class="sub">Grade Point</th> 
                    <th  class="sub">Marks Equivalent</th> 
                </tr>     
                <?php
                $grades = $ref_grade_item->getRecordByDegId($degree_id, $academic_details['session']);
                foreach ($grades as $grade_key => $grade_val) {
                    if ($grade_val['letter_grade'] != 'NA' && $grade_val['letter_grade'] != 'Ab' && $grade_val['letter_grade'] != 'F' && $grade_val['letter_grade'] != 'D') {
                        ?>
                        <tr>
                            <td class="sub" ><?= "{$grade_val['letter_grade']}"; ?></td>
                            <td class="sub" > <?= "{$grade_val['des']}"; ?></td> 
                            <td class="sub" > <?= "{$grade_val['number_grade']}"; ?></td> 
                            <td class="sub" > <?= "{$grade_val['marks_from']}-{$grade_val['marks_to']}%"; ?></td> 
                        </tr>
        <?php } else if ($grade_val['letter_grade'] == 'F' || $grade_val['letter_grade'] == 'D') {
            ?>
                        <tr>
                            <td class="sub" ><?= "{$grade_val['letter_grade']}"; ?></td>
                            <td class="sub" > <?= "{$grade_val['des']}"; ?></td> 
                            <td class="sub" > <?= "{$grade_val['number_grade']}"; ?></td> 
                            <td class="sub" > <?= "Below {$grade_val['marks_to']}"; ?></td> 
                        </tr>

        <?php }
    }
    ?>
    <!--<th class="sub" colspan="<?= (count($grades) - 1) > 8 ? 7 - ((count($grades) - 1) - 8) : (count($grades) - 1) < 8 ? 7 + (8 - (count($grades) - 1)) : 7; ?>"></th>-->
    <!--<th class="sub"></th>-->



<?php } ?>
<?php if (!$this->year_id) { ?> 
    <!--           <tr>-->
    <!--               <th class="sub">Credits</th>-->
    <!--               <th class="sub">Academic</th>-->
    <!--               <th class="sub">Non - Academics</th>-->
    <!--               <th class="sub" rowspan=3>Non Academic Credits :  Extension and Extra Curricular Activities : NSS / NCC   	-->


                <!--</th>-->

                <!--           </tr>-->
                <!--           <tr>-->
                <!--               <td class="sub">Total Required</td>-->
                <!--               <td class="sub">140</td>-->
                <!--               <td class="sub">4</td>-->
                <!--           </tr>-->
                <!--           <tr>-->
                <!--          <td class="sub">Total Earned</td>-->
                <!--               <td class="sub">140</td>-->
                <!--               <td class="sub">4</td>-->
                <!--           </tr>-->
                <tr>
                    <th class="sub"><img src="<?php echo $this->mainconfig['publicpath']; ?>images/picture1.png" style="height:100px" alt="..."  ></th>
                    <th class="sub"><img src="<?php echo $this->mainconfig['publicpath']; ?>images/picture2.png" style="height:100px" alt="..."  ></th>
                     <?php 

                     
                     if($academic_details['session']<7){ ?>
                    <th class="sub" colspan=2>Final Percentage of Marks (%) = CGPA based on all <?=words($this->termcount );?> semesters x <?php if ($degree_id == 3) echo '9.25';else if ($degree_id > 1) echo '9.5';
            else echo '9'; ?></th>
            <?php }else{ ?>
            <th class="sub" colspan=2>Final Percentage of Marks (%) = CGPA based on all <?=words($this->termcount );?>  semesters x <?php if ($degree_id == 3) echo '9.25';else if ($degree_id > 1) echo '9.5';
            else echo '9.5'; ?></th>
            <?php } ?>

                </tr>
                <?php
            }

            function words($num) {
                $numarr = array(2 => "two", 4 => "four", 6 => "six");
                return $numarr[$num];
            }
            ?>
        </tbody>


    </table>
</div>
</center>
</body>

</html>


