<style>

    #refresh{
        cursor:pointer;
    }


</style>
<div class="right_col bdoypayment">
    <div class="load-box" style="z-index:998">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Proficency Report</i>

                    </h3>
                </div>
            </div>
            <div class="col-md-12">
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <!--<label class="control-label">Academic Year<span class="asterisk">*</span></label>-->
                        <?php echo $this->form->academic_year; ?>
                    </div>
                </div>     
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <!--<label class="control-label">Session<span class="asterisk">*</span></label>-->
                        <?php echo $this->form->session; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
                        <?php echo $this->form->academic_id; ?>
                    </div>
                </div>


                <div class="col-md-12">


                    <div class="col-sm-3 col-sm-offset-3 employee_class">
                        <div class="form-group">

                        </div>
                    </div>

                    <div class="col-sm-3 employee_class">


                    </div>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <button type="button" id="getRecords" class="btn btn-primary pull-right" style="margin-top:1.5em;z-index:999;" value="0" >Get Records</button>
                        </div>
                    </div>
                </div>

                <div style="float:left;padding-left:10%;">
                </div>
            </div>
            <div class="col-md-12">
                <div class="table-responsive" id="ajaxData"> 
                    <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                        <thead>
                           <tr>
                                <th>S.No.</th>
                                <th>applicant name</th>
                                <th>application no</th>
                                <th>form id</th>
                                <th>email</th>
                                <th>department</th>
                                <th>phone</th>
                                <th>roll no</th>
                            </tr>
                        </thead>
                        <tbody>

                            <tr>
                                <td colspan="8">
                                    <h2 style="color:red">
                                        No Records Available.
                                    </h2>
                                </td>
                            </tr>


                        </tbody>
                    </table>



                </div>
            </div>

        </div>    


    </div>

</div>



<script>
    $('.datepicker').datepicker();

//Author: Kedar: 22 Oct 2020 : To get record by filter crieteria

    $('body').on('click', '#getRecords', function () {

        let academic_id = $('#academic_id').val();
        $('.load-box').css('display', 'block');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'report/ajax-get-student-report-record'; ?>',
            data: {academic_id: academic_id}
        }).done(function (data) {
            $('#ajajxData').empty('');
            $('#ajaxData').html(data);
            $('.load-box').css('display', 'none');

        });
    });

    //To filter Session
    $('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    //Get Batch By Session
    $('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#academic_id').empty('');
                $('#academic_id').html(data);
                $('#academic_id').trigger("chosen:updated");
            });
        }
    });
    //End   

</script>

