<style>
@page {
  size: A4;
  margin: 11mm 17mm 17mm 17mm;
}

@media print {
  .footer {
    position: fixed;
    bottom: 0;
  }
.header{
            text-align: center;
            height: 20px;
            position:fixed;
            margin:0px;
            top:0px;
        }
  .content-block, p {
    page-break-inside: avoid;
  }

  html, body {
    width: 210mm;
    height: 297mm;
  }

</style>
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<div class="right_col bdoypayment">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <div class="">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h3 class="page-title txt-color-blueDark">
                    <i class="fa fa-bars">Attendance Sheet</i>

                </h3>
            </div>
           
        </div>
        <div class="x_panel">
            <div class="row">
                <div class="pull-right col-xs-2 col-sm-2 col-md-2 col-lg-2"><div class="pull-right"><span class="pull-left" style="margin-right:.3em;"><small><b>Payment</b></small></span><input type="checkbox" id="examType" value="1"  checked data-toggle="toggle" data-size="sm"></div></div>
                <div class="pull-right col-xs-2 col-sm-2 col-md-2 col-lg-2"><div class="pull-right"><span class="pull-left" style="margin-right:.3em;"><small><b>Attendance</b></small></span><input type="checkbox" id="attend" value="1"  checked data-toggle="toggle" data-size="sm"></div></div>
                <div class="pull-right col-xs-1 col-sm-1 col-md-1 col-lg-1">
                <div class="pull-right"><label for="month-visit">Exam Month?
                    </label>
                <input type="text" data-toggle="month-picker" size="11" id="month-visit" name="month-visit">
                </div>
                </div>
            </div>
            <div class="x_title"></div>
    <div class="x_title">
                <div class="row">
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                             <label class="control-label">Academic Year</label>
                                    <?php echo $this->form->academic_year; ?>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                              <label class="control-label">Session<span class="asterisk">*</span></label>
                                <?php echo $this->form->session; ?>
                        </div>
                    </div>	
                    <div class="col-sm-3">
                        <div class="form-group">
                              <label class="control-label">Degree<span class="asterisk">*</span></label>
                                <?php echo $this->form->degree_id; ?>
                        </div>
                    </div>	
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">Course Category<span class="asterisk">*</span></label>
                                <select name="cc_id" id="cc_id" class="form-control chosen-select" required="required" >
                                <option value='0'>Core course</option>
                                <option value='1'>others</option>
                                </select>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">Student Type<span class="asterisk">*</span></label>
                                <select name="col" id="col" class="form-control chosen-select" required="required" >
                                <option value='1'>Collegiate</option>
                                <option value='2'>NonCollegiate</option>
                                <option value='3'>New Admissions</option>
                                </select>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label class="control-label">Department<span class="asterisk">*</span></label>
                                <select name="department" id="department" class="form-control chosen-select" required="required">
                                <?php $department_type = new Application_Model_DepartmentType(); 
                                    $result = $department_type->getDropdownList();
                                foreach($result as $key => $val){
                                ?>
                                <option value = "<?=$key;?>" ><?=$val;?></option>
                                <?php } ?>
                                
                                </select>                       
                                
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_year_id; ?>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group" id ="term_div">
                            <label class="control-label">Term<span class="asterisk">*</span></label>
                            <?php echo $this->form->term_id; ?>
                        </div>
                    </div>
                    <div class="col-sm-3" id ="course_div">
                       <div class="form-group">
                        <label class="control-label">Courses<span class="asterisk">*</span></label>
                         <?php echo $this->form->course_id; ?>
                        </div>
                    </div>
                </div>
        <div class="row">
                <div class="col-md-3 pull-left"  style="padding-left : 0 ; margin-left: 0;"><p>Min. S.No. <input type ="number" id ="min"  /> </p></div>
		<div class="col-md-3"><p>Max S.No.<input type ="number" id = "max" /></p></div>
		 <div class="col-md-4 pull-right">
                   <button class= 'btn btn-primary pull-right' id ="printB">Marks Folio&nbsp;<i class="fa fa-file-excel-o" aria-hidden="true"></i></button> &nbsp;&nbsp; <button class= 'btn btn-primary pull-right' id ="printA">print</button>
               
                </div>
        </div>
        </div>
        <br/>
         <div class="x_content">
	<div id="studentData"> 
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
        <thead>
            <tr>
              <th>S.No.</th>
                <th>Form Id</th>
                <th style="width: 15em">Student Name</th>
                <th>Exam Roll No.</th>
                <th>Registration No</th>
                <th>Copy Number</th>
                <th>Student Signature</th>
                <th>Invigilator Signature</th>
                <th  style="width: 50px;">Photo</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $i = 1;

            if (count($this->paginator) != 0) {

                foreach ($this->paginator as $results) {
                   //echo "<pre>";print_r($results);die;
                    ?>
                    <tr>
                        <td><?php echo $i;

                    $i++;
                    ?>
                        </td>						

                        <td><?php echo $results['stu_id']; ?></td>
                        <td><?php echo $results['stu_fname']; ?></td>
                        <td><?php echo $results['exam_roll']; ?></td>
                        <td><?php echo $results['reg_no']; ?></td>
                        <td ></td>
                        <td></td>
                        <td></td>
                        <td><img class="img img-rounded"  src="<?php echo $this->mainconfig['host'] . $results['filename']; ?>" width="100px" height="70px" alt="img"></td>

                    </tr>            

                <?php
                } 
            }
            ?>

        </tbody>
        </table>
        </div>
        </div>
            </div>
    </div>
        </div>
    <div class='panel-footer'>
         
        
    </div>
        </div>    
<script>
    //To filter Session
    $('body').on('change', '#academic_year', function () {
        $('#department').removeAttr('disabled');
        var year_id = $('#academic_year').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    //End
    $('body').on('change', '#cc_id,#degree_id', function () {
    $('.load-box').css('display','block');
        var cc_id = $('#cc_id').val();
        if (cc_id=='0') {
             $('#academic_year_id>option').each(function(){
                            $(this).attr('selected',false);
                        });
                         $('#academic_year_id').select2();
             $('.load-box').css('display','none');
            
        }
        $('.load-box').css('display','none');
    });
    
    
    $('body').on('change',"#degree_id,#session,#department",function(){
        
        var degree_id = $('#degree_id').val();
        var session_id = $('#session').val();
        var department_id = $('#department').val();
        
        if(degree_id && academic_year_id){
        
             	$.ajax({ 

			type: "POST",

			url:'<?php echo $this->mainconfig['host'].'report/ajax-get-academics';?>',

			data: {session_id:session_id,degree_id:degree_id,department : department_id}

		}).done(function( data ) {

			$('#academic_year_id').empty();
			$('#academic_year_id').html(data);
			if($('#col').val() == 3){
			    $('select#academic_year_id  option').attr('selected','selected');
			    
			    
			    
			}

	  });
        }                
    });
    
</script>


<script>

$(document).ready(function() {		

	//$("#stu_dob").datepicker({ dateFormat: 'dd-mm-yy' });  
	var dateObj = new Date();
var month = dateObj.getUTCMonth() + 1; //months from 1-12
var day = dateObj.getUTCDate();
var year = dateObj.getUTCFullYear();

	$('#month-visit').val( month.length>1?month:"0"+month+"-"+year );

}); 





	function ConfirmDelete()

	{

	var x = confirm("Are you sure you want to delete?");

	if(x)

		return true;

	else

		return false;

	}

	

$('body').on('change',"#attend",function(){
var value = $(this).parent().attr("class");
if(value.includes("off")){
    $(this).removeAttr("checked");
     $(this).val("0");
}
else
{
    $(this).attr("checked","checked");
    $(this).val("1");
}
});

$('body').on('change',"#examType",function(){
var value = $(this).parent().attr("class");
if(value.includes("off")){
    $(this).removeAttr("checked");
     $(this).val("0");
}
else
{
    $(this).attr("checked","checked");
    $(this).val("1");
}
});

 

$('body').on('change', '#academic_year_id', function() {		

var academic_id=$('#academic_year_id').val();

   if(academic_id){

   $('#batch').show();

	$.ajax({ 

			type: "POST",

			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',

			data: {academic_id:academic_id}

		}).done(function( data ) {

			var result = $.parseJSON(data);

			if((data!='')){

				$('#batch').val(result['short_code']);

			}

	  });

	 } 

 }); 

$('body').on('change', '#degree_id,#cc_id', function() {		

var degree_id=$('#degree_id').val();
var session=$('#session').val();

   if(degree_id){

	$.ajax({ 

			type: "POST",

			url:'<?php echo $this->mainconfig['host'].'elective/ajax-get-academics';?>',

			data: {degree_id:degree_id,session_id:session}

		}).done(function( data ) {

			var result = $.parseJSON(data);
                        $('#academic_year_id>option').each(function(){
                            $(this).removeAttr('selected');
                        });
                        
			if((data!='')){
			    if($('#cc_id').val() != 0){
                                for(index in result){
                                 $('#academic_year_id>option[value="'+result[index]['academic_year_id']+'"]').prop('selected',true) ;
                                }
			    }
                              
			}
                    $('#academic_year_id').select2();

	  });

	 } 

 }); 

 

var academic_id=$('#academic_year_id').val();

   if(academic_id){

   $('#batch').show();
                                    var data = '<?=!empty($this->term_id)?$this->term_id:'';?>';
                                  if(data){
                                    var patt = /\d$/g;
                                    var prev_val = parseInt(data.match(patt))-1;
                                    var patt = /(<?=!empty($this->term_id)?$this->term_id:'';?>)/;
                                    data = data.replace(patt,'t'+prev_val);
                                    
                                   $('#term_id').val(data);
                                   $('#term_id').trigger('chosen:updated');
                                   var term_id = data;
                                   
                                   $('#term_id2>option').show();
                                    $('#term_id2>option[value="'+term_id+'"]').hide();
                                    $('#term_id2>option[value="'+term_id+'"]').next().prop('selected',true);
                                    var term2 = $('#term_id2').val();
                                      if((academic_id) && (term_id)){
                                            $.ajax({ 
                                                            type: "POST",
                                                            url:'<?php echo $this->mainconfig['host'].'elective/ajax-get-course';?>',
                                                            data: {academic_year_id:academic_id,term_id : term_id}
                                                    }).done(function( data ) {
                                                        $('#course_id').html(data);
                                                        $('#course_id').trigger('chosen:updated');

                                                       if(term2){ 
                                                        $.ajax({ 
                                                            type: "POST",
                                                            url:'<?php echo $this->mainconfig['host'].'elective/ajax-get-course';?>',
                                                            data: {academic_year_id:academic_id,term_id : term2}
                                                    }).done(function( data ) {
                                                        var patt = /(<?=$this->course_id;?>)_(\d+)_(\d+)/g;
                                                        var prev_val = data.match(patt);
                                                        data = data.replace(patt,'<?=!empty($this->course_id)?$this->course_id:'';?>');
                                                          $('#course_id2').html(data);
                                                          $('#course_id2').val('<?=$this->course_id;?>');
                                                          $('[value="<?=$this->course_id;?>"]').attr('value',prev_val);
                                                          $('#course_id2').trigger('chosen:updated');
                                                        });
                                                        }  
                                              });
                                            }
                                   
                                   
                                   

                                        
                                            $.ajax({ 
                                            type: "POST",
                                            url: '<?php echo $this->mainconfig['host'].'elective/ajax-get-students1';?>',
                                            data: {academic_year_id:academic_id} 
                                                   }).done(function( data ) {
                                           x = JSON.parse('<?=$this->student_ids;?>');
                                           if(x){
                                            $('#selected_student').html(data);
                                            var i = 0;
                                           for(arr in x){
                                               $('option[value="'+x[arr]+'"]').prop('selected',true);
                                               i++;
                                           }
                                                $('#selected_student').select2();
                                                $('#selected_student').trigger('refresh');
                                                    $('#selected_student').parent().append('<div class="form-control-static pull-right" id="count" style="font-size:1.6em;"><strong>'+(i-3)+' : Selected Students</strong></div>')  
                                           }
                                    });
			
                }
	 
	 }

	else{

$('#batch').hide();

}

$('#col').change(function(){
   if($(this).val() == '3')
   {
       $('#term_div').hide();
       $('#course_div').hide();
   }
   else{
       $('#term_div').show();
       $('#course_div').show();
   }
});



$('body').on('change','#academic_year_id,#course_id,#examType,#attend,#month-visit',function () { 
  $('.load-box').css('display','block');
var academic_year_id = $('#academic_year_id').val();  
var term_id = $('#term_id').val();

var course_id = $('#course_id').val();
var Month= $('#month-visit').val();
var exmtype = $('#col').val();
        var arrMonth = Month.split("-"); 
const date = new Date(arrMonth[1], arrMonth[0]-1, 10);  // 2009-11-10
const month = date.toLocaleString('default', { month: 'short' });
const short_year = date.getFullYear().toString();

if(((academic_year_id) && (term_id)) || $('#col').val() == 3 ){
                                    $.ajax({ 
                                            type: "POST",
                                            url: '<?php echo $this->mainconfig['host'].'report/ajax-get-student-by-dept?v1';?>',
                                            data: {academic_year_id:academic_year_id,term_id : term_id,course_id:course_id,cc_id : $('#cc_id').val(),col:$('#col').val(),course_code: $('#course_id option:selected').text(),examtype : $('#examType').val(),attend:$('#attend').val(),month:month+'-'+short_year,exmtype:exmtype} 
                                                   }).done(function( data ) {
                                                       $('#studentData').empty();
                                                       $('#studentData').html(data);
                                                         $('.load-box').css('display','none');   
                                    });
                                    
                                    }
                                    else
                                    {
                                        $('.load-box').css('display','none');    
                                    }
});

// 

$('body').on('change', '#term_id', function() {	

var academic_year_id = $('#academic_year_id').val();
var term_id = $(this).val();
$('#term_id2>option').show();
$('#term_id2>option[value="'+term_id+'"]').hide();
$('#term_id2>option[value="'+term_id+'"]').next().prop('selected',true);
var term2 = $('#term_id2').val();
   if((academic_year_id) && (term_id) ){
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'elective/ajax-get-course';?>',
			data: {academic_year_id:academic_year_id,term_id : term_id,cc_id : $('#cc_id').val(),col:$('#col').val(),course_code: $('#course_id option:selected').text()}
		}).done(function( data ) {
                    $('#course_id').html(data);
                    $('#course_id').trigger('chosen:updated');
                    
                   if(term2){ 
                    $.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'elective/ajax-get-course';?>',
			data: {academic_year_id:academic_year_id,term_id : term2}
		}).done(function( data ) {
                    $('#course_id2').html(data);
                    $('#course_id2').trigger('chosen:updated');
                    });
                    }  
	  });
   }

 }); 
$('body').on('change', '#term_id2', function() {	

var academic_year_id = $('#academic_year_id').val();
var term_id = $(this).val();
$('#term_id>option').show();
$('#term_id>option[value="'+term_id+'"]').hide();

   if((academic_year_id) && (term_id) ){
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'elective/ajax-get-course';?>',
			data: {academic_year_id:academic_year_id,term_id : term_id}
		}).done(function( data ) {
                    $('#course_id2').html(data);
                    $('#course_id2').trigger('chosen:updated');

	  });
   }

 }); 




 $('#print').click(function(){

window.print('#grade_data');

});
      function onStudentSelect() {
        var op_list = $('#selected_student').find("option:selected");
        var str = "";
        $(op_list).each(function () {
            str += $(this).text() + "<br/>";
        });
      $('#selected_student').next('div').html(str);
    }
    $(document).ready(function () {
        onStudentSelect();
      onAcademicSelect();
    });
    
    
 $('#selected_student').select2();
      function onAcademicSelect() {
        var op_list = $('#academic_year_id').find("option:selected");
        var str = "";
        $(op_list).each(function () {
            str += $(this).text() + "<br/>";
        });
      $('#academic_year_id').next('div').html(str);
    }
     $('#academic_year_id').select2();
     
     
//     function printData()
//{
//    window.print();
////   var divToPrint=document.getElementById("dataTable");
////   newWin= window.open("");
////   newWin.document.write(divToPrint.outerHTML);
////   newWin.print();
////   newWin.close();
//}
//Get Batch By Session :  kedar : date : 16 April 2021
    $('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#academic_year_id').empty('');
                $('#academic_year_id').html(data);
                $('#academic_year_id').trigger("chosen:updated");
            });
        }
    });
    //End


let min = 1;
let max = 25;
let myTimeout = '';
 $('body').on('click',"#printB",function(){
      downloadExcel();
 });
 
 function downloadExcel(){
$('.load-box').css('display','block');
var course_code = $('#course_id option:selected').text();
var session = $('#session option:selected').text();
var academic_year  = $('#academic_year option:selected').text();
var term_id  = $('#term_id option:selected').text();
var col  = $('#col option:selected').text();

if(course_code && session && academic_year){
    var studetails = [];
    var table = $('table>tbody tr.odd,tr.even');
    var sno = [];
    var stuid = [];
    var stufname = [];
    var examroll = [];
    var regno = [];
    table.each(function(e){
        sno.push($('td',this).eq(0).text());
        stuid.push($('td',this).eq(1).text());
        stufname.push($('td',this).eq(2).text());
        examroll.push($('td',this).eq(3).text());
        regno.push($('td',this).eq(4).text());
    });
    
     if(sno.length==1){
            sno.push('NA');
        stuid.push('NA');
        stufname.push('NA');
        examroll.push('NA');
        regno.push('NA');
 }
    studetails[0] = sno.join(",").trim();
    studetails[1] = stuid.join(",").trim();
    studetails[2] = stufname.join(",").trim();
    studetails[3] = examroll.join(",").trim();
    studetails[4] = regno.join(",").trim();
    var result = Object.keys(studetails).map((key) => [studetails[key]]);
  studetails =  result.join("_");

 
 
	$.ajax({ 
			type: "POST",
			url:'https://script.google.com/macros/s/AKfycbyVNygSbaR_16Lj1u5AWMpA3P_CyhbYLX0kco9DFa-BxSM81PoJbWMEXaU7ZvMqsRyx/exec',
			data: {sheetName:"Sheet1",studetails ,otherdetails:course_code+","+session+","+academic_year+","+term_id+","+col,rowHeight:50}
		}).done(function( data ) {
		    $('.load-box').css('display','none');  
                  if(data.Ok == '200'){
                  window.open('https://docs.google.com/spreadsheets/d/16Rn2EyptItCGOos8D9WKzUE6OO0RuGS6vHf9ZNIfBG4/export?format=xlsx');
                  }
                  

	  });
}


}


 function setranges(){
     $("#min").val(min);
     $("#max").val(max);
        oTable.draw();
        clearTimeout(myTimeout);
        downloadExcel();
  
 }
 
 


</script>




