<style>

    #register{
        display:none;
    }
    .input-group-addon>div {
        width: 49px !important;
        height: 32px !important;
        margin: 0 !important;
    }

    #prev_chosen,#revalDate_chosen{
        width:100% !important;
    }

</style>
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script><div class="padding-md right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div> 
    <div class="row">
        <div class="col-md-12">
            <h3 class="page-title txt-color-blueDark" >
                <div><i class="fa fa-eye"> Grade Sheet [Non Collegiate]</i></div>
            </h3>
            <div class="row">
                <div class="pull-right col-xs-4 col-sm-4 col-md-4 col-lg-4">

                    <div class="input-group">
                        <select name="revalDate" id="revalDate" class="form-control chosen-select">
                            <option value="">Select Revaluation Dates</option>
                        </select>
                        <span class="input-group-addon" style="padding:0"><input type="checkbox" id="reval" value="0"   data-toggle="toggle" data-size="sm"></span>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                    <div class="panel-body">
                        <div class="row">

                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->academic_year; ?>
                                </div>
                            </div> 
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->session; ?>
                                </div>
                            </div> 
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->filter_status; ?>
                                </div>
                            </div> 
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->academic_year_id; ?>
                                </div>
                            </div> 


                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Year<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->year_id; ?>
                                </div>
                            </div>

                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Term<span class="asterisk">*</span></label>-->
                                    <select name="term_id" id="term_id" class="form-control">
                                        <option>Select Term</option>
                                    </select>
                                </div>
                            </div>


                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Participant Name</label>-->
                                    <?php echo $this->form->stu_id; ?>
                                </div>
                            </div>

                            <button type="button" id="getRecords" class="btn btn-primary" style="float: right" value="0" >Get Records</button>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label class="control-label">&nbsp;</label>
                                    <input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly />
                                </div>
                            </div>
                        </div>
                        <div id="getstudent" class="col-sm-12">
                        </div>
                    </div>

                </form>
            </div><!-- /panel -->
        </div><!-- /.col-->				
    </div><!-- /.row -->

</div><!-- /.padding-md -->	


<script>
    jQuery(document).ready(function () {
        $('#batch').hide();
        $('body').on('change','#stu_id,#revalDate,#reval', function () {
            $('.load-box').css('display', 'block');
            getstudentDetails();
        });
    });

    $('body').on('click', '#getRecords', function () {
        if ($('#academic_year_id').val()) {
            $('.load-box').css('display', 'block');
            getstudentDetails();
        } else {
            alert('PLease select required field.')
        }
    
    });
    $('body').on('change', "#reval", function () {
        var value = $(this).parent().attr("class");
        if (value.includes("off")) {
            $(this).removeAttr("checked");
            $(this).val("0");
            $('#course_grade_details').empty();
            $('#revalDate').empty();
        } else
        {
            $(this).attr("checked", "checked");
            $(this).val("1");
            var academic_id = $('#academic_year_id').val();
            var term_id = $('#term_id').val();
            if (academic_id && term_id) {
                $('.load-box').css('display', 'block');
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-reval-date'; ?>',
                    data: {academic_year_id: academic_id, term_id: term_id, archive: $('#reval').val(), type: 'B'}
                }).done(function (data) {
                    $('#revalDate').empty();
                    $('.load-box').css('display', 'none');
                    $('#revalDate').html(data);
                    $('#revalDate_chosen').removeAttr("style");
                    $('#revalDate').trigger("chosen:updated");
                });
            }
        }
    });

    function getstudentDetails() {
        $url = '<?php echo $this->mainconfig['host']; ?>report/get-back-student-report';
        $.post($url,
                {
                    'academic_id': $('#academic_year_id').val(),
                    'year_id': $('#year_id').val(),
                    'term_id': $('#term_id').val(),
                    'stu_id': $('#stu_id').val(),
                    'reval_status': $('#reval').val(),
                    'revalDate': $('#revalDate').val(),
                    'filter_status': $('#filter_status').val()
                })
                .done(function (data) {
                    $('.load-box').css('display', 'none');
                    //$('#payslipData').html('');
                    $('#getstudent').html(data);
                });

    }

    $("#academic_year_id").change(function () {
        var academic_year_id = $("#academic_year_id").val();
        //alert(academic_year_id);
        //var sel = document.getElementById("academic_year_id");
        //var value = sel.options[sel.selectedIndex].value; // or sel.value
        //var text = sel.options[sel.selectedIndex].text; 
        //alert(text);
        //$('#batch').val(text);
        if (academic_year_id != '') {
            $.ajax({
                type: "POST",
                url: "<?php echo $this->mainconfig['host'] . 'report/ajax-get-student-names'; ?>",
                data: {academic_year_id: academic_year_id}
            }).done(function (data) {
                //alert(data);	
                $("#stu_id").html(data);
            });
        }
    });


    $('body').on('change', '#academic_year_id', function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $('#batch').show();
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch-code'; ?>',
                data: {academic_id: academic_id}
            }).done(function (data) {
                var result = $.parseJSON(data);
                if ((data != '')) {
                    $('#batch').val(result['short_code']);
                }
            });
        }

    });

    $('body').on('change', '#year_id', function () {
        var academic_id = $('#academic_year_id').val();
        var year_id = $('#year_id').val();
        if (academic_id && year_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-term-year-batch'; ?>',
                data: {batch_id: academic_id, year_id: year_id}
            }).done(function (data) {

                $('#term_id').html(data);

            });
        }

    });
   //To filter Session
    $('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    //Get Batch By Session
    $('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#academic_year_id').empty('');
                $('#academic_year_id').html(data);
                $('#academic_year_id').trigger("chosen:updated");
            });
        }
    });

</script>