<?php
      // echo '<pre>'; print_r($_SESSION['admin_login']['admin_login']->participants_file);exit;
?>
<style>
    #hiderow,
    .delete {
        display: none;
    } 
    .words{
      font: 10px/1.4 Georgia, serif !important;  
      padding:0px !important;
      margin:0px !important;
      text-align: left !important;
    }
    * { margin: 0; padding: 0; }
    body { font: 16px/1.4 Georgia, serif; }
    #page-wrap {text-align: center; margin: 20px 0 0 0;  }
            #page-wrap h4{border-bottom: 1px solid black;}
    textarea { border: 0; font: 14px Georgia, Serif; overflow: hidden; resize: none; }
    table { border-collapse: collapse; }
    table td, table th { border: 1px solid black; padding: 5px; }
    #details{
        text-align: center;
        font: 28px Georgia, Serif;
    }
    #header { height: 20px; width: 100%; margin: 20px 0; background: #222; text-align: center; color: white; font: bold 15px Helvetica, Sans-Serif; text-decoration: uppercase; letter-spacing: 20px; padding: 8px 0px; }

    #address { width: 250px; height: 150px; float: left; }
    #customer { overflow: hidden; }

    #logo { text-align: right; float: right; position: relative; margin-top: 25px; border: 1px solid #fff; max-width: 540px; max-height: 100px; overflow: hidden; }
    #logo:hover, #logo.edit { border: 1px solid #000; margin-top: 0px; max-height: 125px; }
    #logoctr { display: none; }
    #logo:hover #logoctr, #logo.edit #logoctr { display: block; text-align: right; line-height: 25px; background: #eee; padding: 0 5px; }
    #logohelp { text-align: left; display: none; font-style: italic; padding: 10px 5px;}
    #logohelp input { margin-bottom: 5px; }
    .edit #logohelp { display: block; }
    .edit #save-logo, .edit #cancel-logo { display: inline; }
    .edit #image, #save-logo, #cancel-logo, .edit #change-logo, .edit #delete-logo { display: none; }
    #customer-title { font-size: 20px; font-weight: bold; float: left; }

    #meta { margin-top: 1px; width: 350px; float: right; }
    #meta td { text-align: right;  }
    #meta td.meta-head { text-align: left; background: #eee; }
    #meta td textarea { width: 100%; height: 20px; text-align: right; }

    #items { clear: both; width: 100%; margin: 30px 0 0 0; border: 1px solid black; }
    #items th { background: #eee; }
    #items textarea { width: 80px; height: 50px; }
    #items tr.item-row td { border: 0; vertical-align: top; }
    #items td.description { width: 300px; }
    #items td.item-name { width: 175px; }
    #items td.description textarea, #items td.item-name textarea { width: 100%; }
    #items td.total-line { border-right: 0; text-align: right; }
    #items td.total-value { border-left: 0; padding: 10px; }
    #items td.total-value textarea { height: 20px; background: none; }
    #items td.balance { background: #eee; }
    #items td.blank { border: 0; }

    #terms { text-align: center; margin: 20px 0 0 0; }
    #terms h5 { text-transform: uppercase; font: 13px Helvetica, Sans-Serif; letter-spacing: 10px; border-bottom: 1px solid black; padding: 0 0 8px 0; margin: 0 0 8px 0; }
    #terms textarea,#page-wrap textarea{ width: 100%; text-align: center;}

    textarea:hover, textarea:focus, #items td.total-value textarea:hover, #items td.total-value textarea:focus, .delete:hover { background-color:#EEFF88; }

    .delete-wpr { position: relative; }
    .delete { display: block; color: #000; text-decoration: none; position: absolute; background: #EEEEEE; font-weight: bold; padding: 0px 3px; border: 1px solid; top: -6px; left: -22px; font-family: Verdana; font-size: 12px; }


</style>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
        <title>Editable Invoice</title>
        <link rel='stylesheet' type='text/css' href='css/style.css' />
        <link rel='stylesheet' type='text/css' href='css/print.css' media="print" />
        <script type='text/javascript' src='js/jquery-1.3.2.min.js'></script>
        <script type='text/javascript' src='js/example.js'></script>
    </head>
    <body>
        <div id="page-wrap">
            <h4>TRANSACTIONS FOR <?= $this->data['term_name'];?></h4>
        </div>
            <div id="identity">
                <textarea id="address">
Development Management Institute Biscomaun Bhawan,
 BRLPS, 5th Floor,
Gandhi Maidan, Patna, Bihar – 800 001
Phone: 0612-2675283
                </textarea>

                <div id="logo">

                    <div id="logoctr">
                        <a href="javascript:;" id="change-logo" title="Change logo">Change Logo</a>
                        <a href="javascript:;" id="save-logo" title="Save changes">Save</a>
                        |
                        <a href="javascript:;" id="delete-logo" title="Delete logo">Delete Logo</a>
                        <a href="javascript:;" id="cancel-logo" title="Cancel changes">Cancel</a>
                    </div>

                    <div id="logohelp">
                   <input id="imageloc" type="text" size="50" value="" /><br />
                        (max width: 540px, max height: 100px)
                    </div>
                    
                    
                <?php // echo '<pre>'; print_r($this->mainconfig['host'].$_SESSION['admin_login']['admin_login']->participants_file);exit; ?>
                    <img style='width:540px; height:100px'id="image" src="<?php echo $this->mainconfig['host'].$_SESSION['admin_login']['admin_login']->participants_file; ?>" alt="logo" />
                </div>

            </div>

        
            <div style="clear:both;"></div>
            <div id="customer">
                <table id="meta">
                    <tr>
                        <td class="meta-head">Name</td>
                        <td><textarea><?=$_SESSION['admin_login']['admin_login']->participant_fname.' '.$_SESSION['admin_login']['admin_login']->participant_lname;?></textarea></td>
                    </tr>
                    <tr>
                        <td class="meta-head">ID No.</td>
                        <td><textarea><?=$_SESSION['admin_login']['admin_login']->roll_no;?></textarea></td>
                    </tr>
                    <tr>
                        <?php 
                                            
                                            $date_arr = explode('-',$this->data['due_date']);
                                            ?>
                        <td class="meta-head">Last Date</td>
                        <td><textarea id="date"><?= in_array('1970',$date_arr)? 'NA':date('d M, Y', strtotime($this->data['due_date'])); ?></textarea></td>
                    </tr>
                    <tr>
                        <td class="meta-head">Amount Due</td>
                        <td><div class="due">INR <?= $this->data['due_fee']; ?></div><br>
                        </td>
                    </tr>
                </table>
                
      <p class='words'><?= $this->data['due_fee_in_words']; ?> only /-</p>
            </div>
            
            <table id="items">
                <tr>
                    <th>Service Fee</th>
                    <th>Tuition Fee</th>
                    <th>Other Annual Charges</th>
                    <th>Scholarship</th>
                    <th>Fee to Pay</th>
                </tr>

                <tr class="item-row">
                    <td class="item-name"><textarea>INR <?= $this->data['service_fee']; ?></textarea></td>
                    <td class="description"><textarea>INR <?= $this->data['tuition_fee']; ?></textarea></td>
                    <td><textarea class="cost">INR <?= $this->data['other_annual_charges']; ?></textarea></td>
                    <td><textarea class="qty"><?= $this->data['fee_discount']; ?></textarea></td>
                    <td><span class="price">INR <?= $this->data['fee_to_pay']; ?></span></td>

                </tr>
                <tr>
                    <td id='details' colspan="5">
                        Transaction Details   
                    </td>
                </tr>
                <tr>

                    <th colspan="2">SL.</th>
                    <th colspan="2">Transaction Amount</th>
                    <th colspan="2">Transaction Date</th>


                </tr>

                <?php $i = 0;
                foreach ($this->data['trans_details'] as $key => $value) { ?>
                    <tr>
                        <td colspan="2"><?= $i + 1; ?></td>
                        <td colspan="2"><?='INR ' ?><?= $value['trans_amount']; ?></td>
                        <td colspan="2"><?='INR ' ?><?= $value['trans_date']; ?></td>
                    </tr>
    <?php $i++;
} ?>
                <tr>
                    <td colspan="2" class="blank"> </td>
                    <td colspan="2" class="total-line">Subtotal</td>
                    <td class="total-value"><div id="subtotal">INR <?= $this->data['fee_to_pay']; ?></div></td>
                </tr>
                <tr>

                    <td colspan="2" class="blank"> </td>
                    <td colspan="2" class="total-line">Total</td>
                    <td class="total-value"><div id="total">INR <?= $this->data['fee_to_pay']; ?></div></td>
                </tr>
                <tr>
                    <td colspan="2" class="blank"> </td>
                    <td colspan="2" class="total-line">Amount Paid</td>

                    <td class="total-value"><textarea id="paid">INR <?= $this->data['total']; ?></textarea></td>
                </tr>
                <tr>
                    <td colspan="2" class="blank"> </td>
                    <td colspan="2" class="total-line">Amount Paid in Words</td>

                    <td class="total-value"><textarea id="paid"><?= $this->data['total_in_words']; ?> only /--</textarea></td>
                </tr>
               
            </table>

            <div id="terms">
                <h5>Terms</h5>
                <p class='words'>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text
                    ever 1500s</p>
            </div>

        </div>

    </body>

</html>

