   
<div class="padding-md right_col">
        <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
 </div>   
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Students Ranking</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
							<div class="row">

							
							
							</div>
							<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
                              <label class="control-label">&nbsp;</label>
							<input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly />
							</div>
						</div>
						</div>
						<div id="section-to-print" class="col-sm-12">
                                                    
                                                 <div class="padding-md clearfix">
	<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="tblData">
                               <thead>
					<tr>
					    <th>Sr No </th>
                                            <th>Participant ID </th>
						<th>Participant Name</th>
                                                <th>Examination ID</th>
                                                <th>Registration No</th>
                                                 <th>Batch </th>
                                                <th>Total CGPA </th>
                                                <th>Percantage(%) </th>
					</tr>
				</thead>
				
				<tbody>

					<?php $i=1;
                                        $result=$this->topresult;

                                       //  print_r($result);
					      foreach($result as $results) {

					?>

					<tr>
                                        <td><?php echo $i;?> </td>
					<td><?php echo $results['stu_id'];?> </td>
                                         <td> <?php echo $results['stu_name'];?></td>
                                         <td> <?php echo $results['exam_roll'];?></td>
                                         <td> <?php echo $results['reg_no'];?></td>
                                          <td> <?php echo $results['short_code'];?></td>
                                        <td><?=($results['total_cgpa'])?> </td>
                                        <td>
                                            
                                          <?php // if ($results['degree_id'] == 3)
                                        //                 $percent = number_format((round($results['total_cgpa'],2) * 9.25), 2);
                                        //             else if ($results['degree_id'] > 1) {
                                        //                 $percent = number_format((round($results['total_cgpa'],2) * 9.5), 2);
                                        //             }
                                        //             else {
                                        //                 $percent = number_format((round($results['total_cgpa'],2) * 9), 2);  
                                        //             }
                                                  $Actualcgpa =  round($results['total_cgpa'],2);
                                                              if($results['session']<7){ // #303
                    $percent = number_format(($Actualcgpa * 9), 2);
                   }
                   else
                   $percent = number_format(($Actualcgpa * 9.5), 2);
                    if ($this->paginator['degree'] == 3)
                        $percent = number_format(($Actualcgpa * 9.25), 2);
                    else if ($this->paginator['degree'] > 1) {
                        $percent = number_format(($Actualcgpa * 9.5), 2);
                    } 
                                                    echo $percent;
                                            ?>
                                        </td>
					</tr>
					<?php 
                                        
                                        $i++;} ?>										
				</tbody>
                                
			</table>
			 <?php //echo $pagination_tr; ?>
		</div>   
                                                   
							</div>
							</div>
							
						
				</form>
					<div class="row">
							    <div class="col-md-offset-3 col-md-3 text-right">
                                                                <button class="downloadAll btn btn-primary" type ="button" id="btnExport" onclick="exportTableToExcel('tblData', 'student-list')" >Export <i class="fa fa-file-excel-o"></i></button></div>
							    </div>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	

<script type="text/javascript">
     function exportTableToExcel(tableID, filename = ''){
    var downloadLink;
    var dataType = 'application/vnd.ms-excel';
    var tableSelect = document.getElementById(tableID);
    var tableHTML = tableSelect.outerHTML.replace(/ /g, '%20');
    
    // Specify file name
    filename = filename?filename+'.xls':'excel_data.xls';
    
    // Create download link element
    downloadLink = document.createElement("a");
    
    document.body.appendChild(downloadLink);
    
    if(navigator.msSaveOrOpenBlob){
        var blob = new Blob(['\ufeff', tableHTML], {
            type: dataType
        });
        navigator.msSaveOrOpenBlob( blob, filename);
    }else{
        // Create a link to the file
        downloadLink.href = 'data:' + dataType + ', ' + tableHTML;
    
        // Setting the file name
        downloadLink.download = filename;
        
        //triggering the function
        downloadLink.click();
    }
}
    </script>
<script>
 jQuery(document).ready(function() {
		$('#batch').hide();
        $('body').on('change', '#year_id,#academic_year_id,#stu_id', function() {
			  $('.load-box').css('display','block');
            getstudentDetails();
        });
	});
 
	
    function getstudentDetails() {
        $url = '<?php echo $this->mainconfig['host']; ?>report/ajax-get-students-result-list';
        $.post($url,
                {
                    'academic_id': $('#academic_year_id').val(),
					'limit': $('#limit').val(),
					'stu_id': $('#stu_id').val()
        })
                .done(function(data) {
                  
                    //$('#payslipData').html('');
                    $('#getstudent').html(data);
                      $('.load-box').hide();
                });

    }

 $("#academic_year_id").change(function() {
	 var academic_year_id=$("#academic_year_id").val();

  if(academic_year_id !=''){
        $('.load-box').css('display','block');
	 $.ajax({ 
			type: "POST",
			url:"<?php echo $this->mainconfig['host'].'report/ajax-get-student-names';?>",
			data: { academic_year_id : academic_year_id}
		}).done( function( data ) { 
	   //  alert(data);	
			$("#stu_id").html(data);
                          $('.load-box').css('display','none');
		});
	}
});


 $('body').on('change', '#academic_year_id', function() {		
var academic_id=$('#academic_year_id').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	 
 });
 
 


</script>

    