<style>

    body>div>h1 {

    display: none;

}

    .bdoypayment{

        margin-top: 4.5em;

        padding-left: 24.5em;

        padding-right: 54.5em;

    }

    label.indent{

        padding-left: 1.8em;

    }

    .cont{

        position:absolute;

        top:50%;

        left:50%;

        transform: translate(-50%,-50%);

        

        

    }

    

    

    

</style>

<div class="right_col bdoypayment">

    <center>  <div class="panel-body cont">

        





        <div class="panel panel-default">

<?php 





 ?> 



            <div class="panel-body" style="width:100em;" >

                <div class="col-md-12">


                  

                      <p class="col-md-12 text-center text-info">Thank you very much for your contribution. Have a nice day! </p>
  


                </div>

                

            </div>    

            <div class="panel-footer">
                This page is automatic redirect on home page after <span id="countdown">20</span> seconds or <a href="<?=$this->mainconfig['erp'].'academic/seminarassociation/' ?>">click here</a> to go to home page
                <?php if($this->response_data['f_code'] =='Ok'){ ?>

                <a href ="" onclick="window.print()" style="boder:1px solid #000;padding: 1em;">print</a>

                <?php } 
                header( "refresh:20;url=".$this->mainconfig['erp'].'academic/seminarassociation/');
                ?>

                

            </div>



        </div>

       

        </div></center>

    </div>

    <?php 

    



    ?>
<script>
    var seconds = document.getElementById("countdown").textContent;
var countdown = setInterval(function() {
    seconds--;
    document.getElementById("countdown").textContent = seconds;
    if (seconds <= 0) clearInterval(countdown);
}, 1000);
    </script>








