
<style type="text/css">

    .bold-checkbox{
        position: absolute; top: 12px; font-weight:bold;
    }
body.modal-open .supreme-container{
    display: none;
        
        
}
@media print {
  .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12 {
    float: left;
  }
  .col-sm-12 {
    width: 100%;
  }
  .col-sm-11 {
    width: 91.66666667%;
  }
  .col-sm-10 {
    width: 83.33333333%;
  }
  .col-sm-9 {
    width: 75%;
  }
  .col-sm-8 {
    width: 66.66666667%;
  }
  .col-sm-7 {
    width: 58.33333333%;
  }
  .col-sm-6 {
    width: 50%;
  }
  .col-sm-5 {
    width: 41.66666667%;
  }
  .col-sm-4 {
    width: 33.33333333%;
  }
  .col-sm-3 {
    width: 25%;
  }
  .col-sm-2 {
    width: 16.66666667%;
  }
  .col-sm-1 {
    width: 8.33333333%;
  }
  .col-sm-pull-12 {
    right: 100%;
  }
  .col-sm-pull-11 {
    right: 91.66666667%;
  }
  .col-sm-pull-10 {
    right: 83.33333333%;
  }
  .col-sm-pull-9 {
    right: 75%;
  }
  .col-sm-pull-8 {
    right: 66.66666667%;
  }
  .col-sm-pull-7 {
    right: 58.33333333%;
  }
  .col-sm-pull-6 {
    right: 50%;
  }
  .col-sm-pull-5 {
    right: 41.66666667%;
  }
  .col-sm-pull-4 {
    right: 33.33333333%;
  }
  .col-sm-pull-3 {
    right: 25%;
  }
  .col-sm-pull-2 {
    right: 16.66666667%;
  }
  .col-sm-pull-1 {
    right: 8.33333333%;
  }
  .col-sm-pull-0 {
    right: auto;
  }
  .col-sm-push-12 {
    left: 100%;
  }
  .col-sm-push-11 {
    left: 91.66666667%;
  }
  .col-sm-push-10 {
    left: 83.33333333%;
  }
  .col-sm-push-9 {
    left: 75%;
  }
  .col-sm-push-8 {
    left: 66.66666667%;
  }
  .col-sm-push-7 {
    left: 58.33333333%;
  }
  .col-sm-push-6 {
    left: 50%;
  }
  .col-sm-push-5 {
    left: 41.66666667%;
  }
  .col-sm-push-4 {
    left: 33.33333333%;
  }
  .col-sm-push-3 {
    left: 25%;
  }
  .col-sm-push-2 {
    left: 16.66666667%;
  }
  .col-sm-push-1 {
    left: 8.33333333%;
  }
  .col-sm-push-0 {
    left: auto;
  }
  .col-sm-offset-12 {
    margin-left: 100%;
  }
  .col-sm-offset-11 {
    margin-left: 91.66666667%;
  }
  .col-sm-offset-10 {
    margin-left: 83.33333333%;
  }
  .col-sm-offset-9 {
    margin-left: 75%;
  }
  .col-sm-offset-8 {
    margin-left: 66.66666667%;
  }
  .col-sm-offset-7 {
    margin-left: 58.33333333%;
  }
  .col-sm-offset-6 {
    margin-left: 50%;
  }
  .col-sm-offset-5 {
    margin-left: 41.66666667%;
  }
  .col-sm-offset-4 {
    margin-left: 33.33333333%;
  }
  .col-sm-offset-3 {
    margin-left: 25%;
  }
  .col-sm-offset-2 {
    margin-left: 16.66666667%;
  }
  .col-sm-offset-1 {
    margin-left: 8.33333333%;
  }
  .col-sm-offset-0 {
    margin-left: 0%;
  }
  .visible-xs {
    display: none !important;
  }
  .hidden-xs {
    display: block !important;
  }
  table.hidden-xs {
    display: table;
  }
  tr.hidden-xs {
    display: table-row !important;
  }
  th.hidden-xs,
  td.hidden-xs {
    display: table-cell !important;
  }
  .hidden-xs.hidden-print {
    display: none !important;
  }
  .hidden-sm {
    display: none !important;
  }
  .visible-sm {
    display: block !important;
  }
  table.visible-sm {
    display: table;
  }
  tr.visible-sm {
    display: table-row !important;
  }
  th.visible-sm,
  td.visible-sm {
    display: table-cell !important;
  }
       #non-printable { display: none; }
        #printable { display: block; } 
        
  .printdiv:last-child {
     page-break-inside: avoid;
}
body * {
    visibility: hidden;
  }
  #section-to-print, #section-to-print * {
    visibility: visible;
    
  }
  #offlinPayment{
      width:100%;
  }
 
  
 #transaction { margin-top: 35%}
  .pagebreak {
       clear: both;
      page-break-after: always; }
}
 @page
    {
        size:  auto;   /* auto is the initial value */
        margin: 1mm;
         margin-top:-30%;/* this affects the margin in the printer settings */
    }
</style>
<link rel="stylesheet" type="text/css" href="https://printjs-4de6.kxcdn.com/print.min.css">


<div class="admitCard" id="admitCardPreview">
    <div class="multistepformArea offlinPayment" id="offlinPayment">
<!--          <div style="float:right;padding-bottom: 3em;">

        <button type="button" id="printAppForm2" onclick="window.print()" class="btn btn-primary">Print</button>
    </div>-->
         <div class="col-md-12" id="section-to-print"> 
        <div class="masterbox panel-default panel pagebreak">
             <div class="panel-body">
                                <div class="row">   
                <div class="col-sm-12 employee_class ">
                     <div class=" col-sm-2 ">
                        <div class="form-group" style="float:right; padding-top: 1em;">
                            <img src="<?php echo $this->mainconfig['publicpath']; ?>img/logo.png" style="width:120px; height: 130px;"> 
                        </div>
                    </div>
                    <div class="col-sm-8 employee_class ">

                        <div class = 'sub' style="text-align: center;">
                            
                           <h4 style="text-align: center;">PATNA WOMEN'S COLLEGE </h4>
                           <h5 style="text-align: center;">Autonomous  </h5>
                          <h4 style="text-align: center;">PATNA  UNIVERSITY </h4>
                          <h5 style="text-align: center;"> 3rd Cycle NAAC Accredited at A Grade with CGPA 3.58/4</h4>       
                          <h6 style="text-align: center;">College with Potential for Excellence'(CPE) status accorded by UGC</h4> 
                          <h5 style="text-align: center;">BAILEY ROAD,PATNA - 800 001, BIHAR</h4>
                          <h5 style="text-align: center;">Admit Card -  <?= $this->paginator['course_name'] ?> -Sem-1 -  <?= $this->paginator['session'] ?></h4>
                        </div>
                    </div>
                   <div class=" col-sm-2">
                    <div class="form-group" style="float:right;">
                        <img src="<?php echo $this->baseUrl($this->paginator['photo']);?>" alt="img" style="width:120px; height: 130px;"> 
                        <h4 style="text-align: center"> <?= $this->paginator['form_id'] ?> </h4>
                    </div>
                </div>
                </div>
                <div class="row">
                      <div class="col-sm-2"></div>
                <div class="col-sm-4 employee_class admit">

                    <h4>Name Of Candidate : </h4>
                    <h4>D.O.B :  </h4> 
                    <h4>Address: </h4>
                    <h4>Father Name: </h4>
                    <h4> Subject: </h4>
                  

                </div>
                  
                <div class="col-sm-6 employee_class admit">

                    <h4><?= ucfirst($this->paginator['applicant_name']) ?> </h4>
                    <h4><?= $this->paginator['dob'] ?></h4>
                    <h4><?= ucfirst($this->paginator['p_address']) ?> </h4>
                    <h4> <?= ucfirst($this->paginator['father_name'] )?> </h4>
                    <h4> <?= ucfirst($this->paginator['course_name']) ?> </h4>
                  
                    <p style="margin-left: 50%;">Candidate full signature</p>  
                </div>
                     
                </div>
                <div class="row">
                <div class="col-sm-10 employee_class  ">

                    <div class = 'sub' style="text-align: center;">
                        <p style ="font-size:1.2em; letter-spacing:.03em; font-weight:900; text-shadow:0px 0px RGBA(147,46,144,1);text-align: center"><u>To be filled by College Office</u>
                        </p>

                    </div>
                </div>
                </div>
                 <div class="row">
                      <div class="col-sm-2"></div>
                    <div class=" col-sm-4 admit">
                        <h4>Exam Roll No.: </h4> 
                        <h4>Payment Id :  </h4> 
                        <h4>Payment Bank: </h4> 
                        <h4>Time of Entrance test: </h4> 
                        <h4>Place of Exam: </h4> 
                        <h4>Date of Entrance Test: </h4> 


                    </div>
                    <div class=" col-sm-6 admit">
                        <h4> <?= !empty($this->payment_detail['roll']) ? $this->payment_detail['roll'] :'N/A'  ?> </h4> 
                        <h4> <?= !empty($this->payment_detail['mmp_txn']) ? $this->payment_detail['mmp_txn'] :'N/A'  ?> </h4> 
                        <h4> <?= !empty($this->payment_detail['bank_name']) ? $this->payment_detail['bank_name'] :'N/A'  ?> </h4> 
                        <h4> <?= !empty($this->payment_detail['examtime_start']) ? $this->payment_detail['examtime_start'] :'N/A'  ?>  To <?= !empty($this->payment_detail['examtime_end']) ? $this->payment_detail['examtime_end'] :'N/A'  ?></h4>
                        <h5>PATNA WOMEN'S COLLEGE, BAILEY ROAD,PATNA - 800 001, BIHAR  </h5> 
                        <h4><?= !empty($this->payment_detail['exam_date'])? date('d-m-Y',strtotime($this->payment_detail['exam_date'])) :'N/A' ?></h4> <br>
                        
						 <figure class="figure">
                                                <img src="<?php echo $this->mainconfig['publicpath']; ?>images/principal.jpg" alt="..." height='100em' > <figcaption class="figure-caption text-center">Principal</figcaption>
                                          </figure>
                    </div>
                    
                 </div>
            

               <br>
                                </div>
                 
             </div>
        </div>
            
             <div class="masterbox panel-default panel " id="transaction"> 
                  
            
                <div class="row">
                <div class="col-sm-10 employee_class">
 
                    <div class = 'sub' style="text-align: center;">
                        <p style ="font-size:1.2em; letter-spacing:.03em; font-weight:900; text-shadow:0px 0px RGBA(147,46,144,1);text-align: center"><u>Transaction Slip</u>
                        </p>

                    </div>
                </div>
                </div>
                                    
               <table cellspacing="0" cellpadding="1" border="1" width="80%" style="border-collapse:collapse" align="center">
                  <tbody><tr><td colspan="2">  
                                                    
                    <tr><td>Transaction Date:</td><td><?= !empty($this->payment_detail['submit_date'])? date('d-m-Y',strtotime($this->payment_detail['submit_date'])):'N/A' ?></td></tr>
                    
                    <tr><td>Atom Transaction Reference No.</td><td><?= !empty($this->payment_detail['mmp_txn'])?$this->payment_detail['mmp_txn']:'N/A' ?></td></tr>
                    <tr><td>Amount</td><td><?= !empty($this->payment_detail['exam_fee'])?$this->payment_detail['exam_fee']:'N/A' ?> (Rs.)</td></tr>
                    <tr><td>Student Name</td><td><?= !empty($this->payment_detail['applicant_name'])?$this->payment_detail['applicant_name']:'N/A' ?></td></tr>
                    <tr><td>Student Form Id</td><td><?= !empty($this->payment_detail['email_id'])?$this->payment_detail['form_id']:'N/A' ?></td></tr>
                    <tr><td>Student Email Id</td><td><?= !empty($this->payment_detail['email_id'])?$this->payment_detail['email_id']:'N/A' ?></td></tr>
                    <tr><td>Transaction Status</td><td>Success</td></tr>
                    </tbody>
                </table>
                 
                   
            

               <br>     
           
        </div>
              
        </div>
 <div style="float:right;padding-bottom: 3em;">

                    <button type="button" id="printAppForm1" onclick="window.print()" class="btn btn-primary">Print</button>
                </div>
    </div>
</div>
