
<style>
@media print {
  .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12 {
    float: left;
  }
  .col-sm-12 {
    width: 100%;
  }
  .col-sm-11 {
    width: 91.66666667%;
  }
  .col-sm-10 {
    width: 83.33333333%;
  }
  .col-sm-9 {
    width: 75%;
  }
  .col-sm-8 {
    width: 66.66666667%;
  }
  .col-sm-7 {
    width: 58.33333333%;
  }
  .col-sm-6 {
    width: 50%;
  }
  .col-sm-5 {
    width: 41.66666667%;
  }
  .col-sm-4 {
    width: 33.33333333%;
  }
  .col-sm-3 {
    width: 25%;
  }
  .col-sm-2 {
    width: 16.66666667%;
  }
  .col-sm-1 {
    width: 8.33333333%;
  }
  .col-sm-pull-12 {
    right: 100%;
  }
  .col-sm-pull-11 {
    right: 91.66666667%;
  }
  .col-sm-pull-10 {
    right: 83.33333333%;
  }
  .col-sm-pull-9 {
    right: 75%;
  }
  .col-sm-pull-8 {
    right: 66.66666667%;
  }
  .col-sm-pull-7 {
    right: 58.33333333%;
  }
  .col-sm-pull-6 {
    right: 50%;
  }
  .col-sm-pull-5 {
    right: 41.66666667%;
  }
  .col-sm-pull-4 {
    right: 33.33333333%;
  }
  .col-sm-pull-3 {
    right: 25%;
  }
  .col-sm-pull-2 {
    right: 16.66666667%;
  }
  .col-sm-pull-1 {
    right: 8.33333333%;
  }
  .col-sm-pull-0 {
    right: auto;
  }
  .col-sm-push-12 {
    left: 100%;
  }
  .col-sm-push-11 {
    left: 91.66666667%;
  }
  .col-sm-push-10 {
    left: 83.33333333%;
  }
  .col-sm-push-9 {
    left: 75%;
  }
  .col-sm-push-8 {
    left: 66.66666667%;
  }
  .col-sm-push-7 {
    left: 58.33333333%;
  }
  .col-sm-push-6 {
    left: 50%;
  }
  .col-sm-push-5 {
    left: 41.66666667%;
  }
  .col-sm-push-4 {
    left: 33.33333333%;
  }
  .col-sm-push-3 {
    left: 25%;
  }
  .col-sm-push-2 {
    left: 16.66666667%;
  }
  .col-sm-push-1 {
    left: 8.33333333%;
  }
  .col-sm-push-0 {
    left: auto;
  }
  .col-sm-offset-12 {
    margin-left: 100%;
  }
  .col-sm-offset-11 {
    margin-left: 91.66666667%;
  }
  .col-sm-offset-10 {
    margin-left: 83.33333333%;
  }
  .col-sm-offset-9 {
    margin-left: 75%;
  }
  .col-sm-offset-8 {
    margin-left: 66.66666667%;
  }
  .col-sm-offset-7 {
    margin-left: 58.33333333%;
  }
  .col-sm-offset-6 {
    margin-left: 50%;
  }
  .col-sm-offset-5 {
    margin-left: 41.66666667%;
  }
  .col-sm-offset-4 {
    margin-left: 33.33333333%;
  }
  .col-sm-offset-3 {
    margin-left: 25%;
  }
  .col-sm-offset-2 {
    margin-left: 16.66666667%;
  }
  .col-sm-offset-1 {
    margin-left: 8.33333333%;
  }
  .col-sm-offset-0 {
    margin-left: 0%;
  }
  .visible-xs {
    display: none !important;
  }
  .hidden-xs {
    display: block !important;
  }
  table.hidden-xs {
    display: table;
  }
  tr.hidden-xs {
    display: table-row !important;
  }
  th.hidden-xs,
  td.hidden-xs {
    display: table-cell !important;
  }
  .hidden-xs.hidden-print {
    display: none !important;
  }
  .hidden-sm {
    display: none !important;
  }
  .visible-sm {
    display: block !important;
  }
  table.visible-sm {
    display: table;
  }
  tr.visible-sm {
    display: table-row !important;
  }
  th.visible-sm,
  td.visible-sm {
    display: table-cell !important;
  }
       #non-printable { display: none; }
        #printable { display: block; } 
        
  .printdiv:last-child {
     page-break-inside: avoid;
}
body * {
    visibility: hidden;
  }
  #section-to-print, #section-to-print * {
    visibility: visible;
    font-size:12px;
  }
  #section-to-print {
    position: relative;
    left: 0;
    top: 0px;
  }
   #transaction, #transaction * {
    visibility: visible;
    font-size:12px;
  }
  #transaction {
    position: relative;
    left: 0;
    top: 350px;
  }
  
  #applicationFormPreview{
      width:100%;
  }
  
  .pagebreak {
       clear: both;
      page-break-after: always; }
}
 @page 
    {
        size:  auto;   /* auto is the initial value */
        margin: 1mm;
        margin-top:-40%; 
       /* this affects the margin in the printer settings */
    }   
   
    
</style>
<div class="appForm" id="applicationFormPreview">
<div class="multistepformArea" id="applicationFormPreview">
       <div style="float:right;padding-bottom: 3em;" id="divbutton">
            <button type="button" id="printAppForm2"  class="btn btn-primary" onclick="window.print()">Print</button>
        </div>
  <form class="regForm" id="formValidate1" action="" method="post" data-validate="parsley" >
        <div class="row" id="section-to-print">
        <div class="col-sm-12 employee_class pagebreak">
                
            <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">

                <thead>
                    <tr>
                       
                    </tr>
                </thead>
                <tbody>
                   
                    <tr>
               
                        <td class="col-sm-2 col-sm-offset-1">
                           
                            <div class="form-group">
                                 <img src="<?php echo $this->mainconfig['publicpath']; ?>img/logo.png" width="120" height="130"> 
                              
                               
                            </div>
                 

                        </td>

                        <td class="col-sm-8">
                            <div class = 'sub' style="text-align: center;">
                                <h4> PATNA WOMEN'S COLLEGE</h4>
                                <h5>AUTONOMOUS</p></h5>
                                <h4>PATNA UNIVERSITY</h4>
                                <h5>3rd Cycle NAAC Accredited at A Grade with CGPA 3.58/4</h5>
                                <h5>College with Potential for Excellence(CPE) status accorded by UGC</h5>
                                <h5> BAILEY ROAD,PATNA - 800 001, BIHAR</h5>
                                <h5>Application Form</h5>
                                <h5><?= $this->paginator['course_name'] ?> -Sem-1 -  <?= $this->paginator['session'] ?></h5>
                        </div>
                        </td>
                        <td class="col-sm-2 col-sm-offset-1">
                            <div class="form-group" style="padding-top: 1em;">
                                 <img src="<?php echo $this->baseUrl($this->paginator['photo']);?>" alt="img" height="160" width="190">
                                  <h4 style="text-align: center"> <?= $this->paginator['form_id'] ?> </h4><br>
                            </div>
                        </td>
           

                    </tr>
                  
                </tbody>
            </table>
         
                <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">

                    <thead>
                        <tr>
                            <th  style="width:15%" id="a"> Applicant Information</th>
                            <th style="width:15%"></th>   
                            <th style="width:8%"></th>   
                            <th style="width:15%"></th>   
                        </tr>
                    </thead>
                    <tbody>
                        
                        <tr>
                            
                            <td class="">
                              Name
                            </td>
                            
                            <td class="">
                               <?= $this->paginator['applicant_name'] ?>
                            </td>
                            <td class="">
                              Gender
                            </td>
                            
                            <td class="">
                                <?php if($this->paginator['gender'] == 1){
                                    echo 'Female';
                                }else{
                                    echo 'Transgender';
                                }  ?>
                            </td>
                            
                        </tr>
                        <tr>
                            
                            <td class="">
                              Date of Birth
                            </td>
                            
                            <td class="">
                                <?= $this->paginator['dob'] ?>
                            </td>
                            <td class="">
                             Nationality
                            </td>
                            <td>
                                <?php if($this->paginator['nationality']){
                                    echo $this->paginator['nationality'];
                                 }else{
                                    echo 'N/A';
                                 }  ?>
                            </td>
                            
                        </tr>
                        <tr>
                            
                            <td class="">
                              Father's Name
                            </td>
                            
                            <td class="">
                               
                                <?php echo $this->paginator['father_name'];?>
                            </td>
                            <td class="">
                              Religion
                            </td>
                            
                            <td class="">
                                <?php if($this->paginator['religion'] == 'others'){
                                    echo $this->paginator['others_religion'];
                                 }else{
                                   echo $this->paginator['religion'];
                                 }  ?>
                            </td>
                            
                        </tr>
                        <tr>
                            
                            <td class="">
                              Mother's Name
                            </td>
                            
                            <td class="">
                                <?= $this->paginator['mother_name'] ?>
                            </td>
                            <td class="">
                              Category
                            </td>
                            
                            <td class="">
                                <?= $this->paginator['caste'] ?>
                            </td>
                            
                        </tr>
                    </tbody>
                </table>
                <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1" >
                    <?php if(!empty($this->paginator['degree'] == 1)){ ?>
            
                    <?php
                    $cc_id_InArray = ["4", "16", "17","18","19","20","21"];
                    if (in_array($this->paginator['course'], $cc_id_InArray, TRUE)) { ?>
                    <p><legend>Preference:</legend></p>
                    <?php } else{ ?>
                     &nbsp;<p><legend>&nbsp;&nbsp;i. First Preference:</legend></p>
                    <?php }?>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Core Course:<span class="asterisk">*</span></label><br>
                       <?php if(!empty($this->paginator['corecourse1'])){
                             echo $this->paginator['corecourse1'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Generic Elective:<span class="asterisk">*</span></label><br>
                       <?php if(!empty($this->paginator['ge1'])){
                             echo $this->paginator['ge1'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">AECC<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['aecc1']; ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">Compulsary Subject<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['comp_evs']; ?>
                    </div>
                </div>	
            
                <?php 
                $cc_id_InArray = ["4", "16", "17","18","19","20","21"];
                if (!in_array($this->paginator['course'], $cc_id_InArray, TRUE)) { ?>
           
                    &nbsp;<p><legend>&nbsp;&nbsp; ii.Second Preference:</legend></p>
                
            
          <!------Second Row ------->
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label"> Core Course<span class="asterisk">*</span></label><br>
                         <?php if(!empty($this->paginator['corecourse2'])){
                             echo $this->paginator['corecourse2'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Generic Elective<span class="asterisk">*</span></label><br>
                        <?php if(!empty($this->paginator['ge2'])){
                             echo $this->paginator['ge2'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>
                
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                       <label class="control-label">AECC<span class="asterisk">*</span></label><br>
                        <?php if(!empty($this->paginator['aecc2'])){
                             echo $this->paginator['aecc2'];
                         } else {
                             echo 'N/A';
                         }
                         ?>
                    </div>
                </div>	
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Compulsory Subject<span class="asterisk">*</span></label><br>
                        <?php echo $this->paginator['comp_evs']; ?>
                    </div>
                </div>
             	
                
          
                <?php }} ?>
                   
                </table> 
            <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">

                    <thead>
                        <tr>
                            <th  style="width:5%" id="a"> Appearing Status</th>
                           
                            <th style="width:15%">
                           </th>  
                             
                        </tr>
                    </thead>
                    <tbody>
                       
                        <tr>
                           
                            <td class="">
                             Appearing Status
                            </td>
                           
                            <td class="">
                              <?php if($this->paginator['appearingStatus'] == 1){
                                echo 'Yes';
                            } else {
                                echo 'No';
                            }
                            ?>
                            </td>
                           
                           
                           
                        </tr>
                       
                    </tbody>
                </table> 

        <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">
            <?php if($this->paginator['degree'] != 1){ ?>
                    &nbsp;<p><legend>  &nbsp; i. Academic Details</legend></p>
                    <thead>
                        <tr>
                            <th>Name Of Examination</th>
                            <th>Board/University</th>
                            <th>Name of Institution</th>
                            <th>Division/Grade</th>    
                            <th>Subject</th>
                            <th>Passing Year</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if($this->paginator['course_name'] == 'M.C.A'){  ?>
                        <tr>
                            <td><b>Matriculation</b></td>
                            <td>
                                
                                <?=  !empty($this->paginator['mat_board']) ? $this->paginator['mat_board'] :'N/A' ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_school']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_division'];  ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_subject'];  ?>
                            </td>
                            <td>
                                <?php   echo $this->paginator['mat_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b>10+2</b></td>
                            <td>
                                <?php echo  $this->paginator['i_board'];  ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['school'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['i_division']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['subject']; ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['i_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        
                        <tr>
                            <td><b> BCA/B.Sc in CS</b></td>
                            <td>
                                <?php echo  $this->paginator['bca_board'];   ?>
                            </td>
                            <td>
                                <?php  echo  $this->paginator['bca_school']; ?>
                            </td>
                            <td>
                                <?php echo  $this->paginator['bca_division'];    ?>
                            </td>
                            <td>
                                <?php  echo  $this->paginator['bca_subject']; ?>
                            </td>
                            <td>
                                <?php  echo  $this->paginator['bca_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td> <b>Graduation with Maths </b></td>
                            <td>
                                <?=  !empty($this->paginator['grad_math_board'])?$this->paginator['grad_math_board']:'N/A' ?>
                                
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_math_school'])?$this->paginator['grad_math_school']:'N/A' ?>
                               
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_math_division'])?$this->paginator['grad_math_division']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_math_subject'])?$this->paginator['grad_math_subject']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_math_pass_year'])?$this->paginator['grad_math_pass_year']:'N/A' ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td> <b>Certification CS</b></td>
                            <td>
                                <?php echo $this->paginator['cert_board'];   ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['cert_school'];   ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['cert_division'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['cert_subject'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['cert_pass_year'];   ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b> Other </b></td>
                            <td>
                                <?php echo $this->paginator['other_board'];    ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_school'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_division'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_subject']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['other_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        <?php }else { ?>
                        <tr>
                            <td><b>Matriculation</b></td>
                            <td>
                                <?php echo $this->paginator['mat_board'];   ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_school'];   ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['mat_division'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['mat_subject'];  ?>
                            </td>
                            <td>
                                <?php echo$this->paginator['mat_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b>Intermediate</b></td>
                            <td>
                                <?php echo $this->paginator['i_board']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['school'];   ?>
                            </td>
                            <td>
                                <?php  echo$this->paginator['i_division'];     ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['subject']; ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['i_pass_year'];   ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b> Graduation  </b></td>
                            <td>
                                <?= !empty($this->paginator['grad_board'])?$this->paginator['grad_board']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_school'])?$this->paginator['grad_school']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_division'])?$this->paginator['grad_division']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_subject'])?$this->paginator['grad_subject']:'N/A' ?>
                            </td>
                            <td>
                                <?= !empty($this->paginator['grad_pass_year'])?$this->paginator['grad_pass_year']:'N/A' ?>
                            </td>
                                
                        </tr>
                        <tr>
                            <td><b> Other </b></td>
                            <td>
                                <?php echo $this->paginator['other_board'];  ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_school']; ?>
                            </td>
                            <td>
                                <?php  echo $this->paginator['other_division'];   ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_subject'];   ?>
                            </td>
                            <td>
                                <?php echo $this->paginator['other_pass_year'];  ?>
                            </td>
                                
                        </tr>
                        <?php } ?>
                    </tbody>
                </table> 
            </div>
            <div class="col-sm-12">
             
                        &nbsp;<p><legend>  &nbsp; ii. Last Examination Details</legend></p>

                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                            <thead>
                                <tr>
                                    <th>Name of Institution</th>
                                    <th>Place</th>
                                    <th>Board/University</th>
                                    <th>Passing Year</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td><?php echo $this->paginator['l_institution']; ?></td>
                                    <td><?php echo $this->paginator['l_place']; ?></td>
                                    <td><?php echo $this->paginator['last_board']; ?></td>
                                    <td><?php echo $this->paginator['l_p_year']; ?></td>

                                </tr>

                            </tbody>
                        </table>
                    <?php }else{ ?>
                        <fieldset>
                   
                    &nbsp;<p><legend>  &nbsp;i. Intermediate Education Details</legend></p>
                <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                    <thead>
                        <tr>
                            <th>School/College</th>
                            <th>Board/University</th>
                            <th>Division/Grade</th>
                            <th>Roll No</th>
                            <th>Obtained Marks</th>
                            <th>Total Marks</th>
                            <th>Percentage </th>
                            <th>Passing Year</th>
                        </tr>
                    </thead>
                    <tbody>
                      
                        <tr>
                            <td> <?= !empty($this->paginator['school'])?$this->paginator['school']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['i_board'])?$this->paginator['i_board']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['i_division'])?$this->paginator['i_division']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['i_roll'])?$this->paginator['i_roll']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['obt_marks'])?$this->paginator['obt_marks']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['total_marks'])?$this->paginator['total_marks']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['percent'])?$this->paginator['percent']:'N/A' ?></td>
                            <td> <?= !empty($this->paginator['i_pass_year'])?$this->paginator['i_pass_year']:'N/A' ?></td>
                               
                        </tr>
                   
                    </tbody>
                </table>
                     &nbsp;<p><legend>  &nbsp;ii. Last Examination Details</legend></p>

                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
                            <thead>
                                <tr>
                                    <th>Name of Institution</th>
                                    <th>Place</th>
                                    <th>Board/University</th>
                                    <th>Passing Year</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td><?php echo $this->paginator['l_institution']; ?></td>
                                    <td><?php echo $this->paginator['l_place']; ?></td>
                                    <td><?php echo $this->paginator['last_board']; ?></td>
                                    <td><?php echo $this->paginator['l_p_year']; ?></td>

                                </tr>

                            </tbody>
                        </table>
                
               <?php } ?>
            
                    
                </table>   
       
       
        </div>
            
   
     </div>
      <div class=" panel-default panel" id="transaction"> 
                  
             <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">

                    <thead>
                        <tr>
                            <th  style="width:5%" id="a"> Extra Circular Activities</th>
                           
                            <th style="width:15%">
                           </th>   
                             
                        </tr>
                    </thead>
                    <tbody>
                        
                        <tr>
                            
                            <td class="">
                             Extra-Curricular Activities
                            </td>
                            
                            <td class="">
                               <?php if($this->paginator['ExtraCurricularSelection']){
                                    echo $this->paginator['ExtraCurricularSelection'];
                                 }else{
                                    echo 'N/A';
                                 }  ?>
                            </td>     
                        </tr>
                        <tr>
                            
                          
                        </tr>
                        
                    </tbody>
                </table>   
        
        <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">

                    <thead>
                        <tr>
                            
                             
                        </tr>
                    </thead>
                    <tbody>
                        
                        <tr>
                            
                            <td colspan="2">
                                <h4 style=" text-align:center" ><b> Declaration</b></h4>
                            </td>
                            
                        </tr>
                        <tr>
                            <td  style="width:5%" ></td>
                            <td>I declare that all particulars furnished above are true and correct. I have studied the College prospectus and promise to abide by the rules and regulations of the College.
</td>
                        </tr>
                        <tr>
                            <td  style="width:5%; vertical-align: bottom" >
                                Date:_______________
                                   
                            </td>
                            <td style="height: 4em; vertical-align: bottom;text-align: right">
                                Signature of Applicant
                            </td>
                        </tr>
                    </tbody>
                </table>   
        <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">

                    <thead>
                        <tr>
                            
                             
                        </tr>
                    </thead>
                    <tbody>
                        
                       
                        <tr>
                            <td  style="width:5%" ></td>
                            <td>I give an assurance that my daughter/ward will observe the rules and regulations of the College faithfully.
</td>
                        </tr>
                        <tr>
                            <td  style="width:5% ;vertical-align: bottom" >
                                Date:_______________
                            </td>
                            <td style="height: 4em; vertical-align: bottom; text-align: right">
                                Signature of Parent/Guardian
                            </td>
                        </tr>
                    </tbody>
                </table>   
               </form>
                 
                   
        
               <br>     
           
        </div>
                           <div style="float:right;padding-bottom: 3em;" >
                            
                            <button type="button" id="printAppForm1" class="btn btn-primary" onclick="window.print()">Print</button>
                        </div></div>
</div>


<script>
//  $( "#printAppForm2" ).click(function() {
//   
//  $('#downloadArea').hide();
//  $('#divbutton').hide();
//});
    </script>