<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Experiential Courses Wise Grade After Penalties </i></div>
		</h3>
			<div class="panel panel-default">
			<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					<div class="row">
						<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_id; ?>
                            </div>
							</div>
						<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->year_id; ?>
                            </div>
						</div>
												
					</div>
					
					<div class="row">
							<div class="col-sm-3">
							<div class="form-group">
							<input type="text" id="batch" class="form-control"  style="background-color:#fdf59a;" readonly /></div>
							</div>
							</div>
					<div class="row">
					<div id="course_grade_details"></div>
					</div>
				
				
 			</div>
			
			<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-8">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Experienatial Course Grade After Penalties Report</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-4">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>experiential-course/gradeaftr-penalty/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Experiential Course Grade After Penalties Report</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th>S. No.</th>
						<th>Batch</th>
						<th>Year</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php
						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {
						foreach ($this->paginator as $results) {
						//print_r($results);die;
					?>
						<tr class="id<?php echo $results['id'];?>">
						<td><?php echo $i;
									$i++; ?>
						</td>								
						<td><?php echo $results['from_date'].'-'.$results['to_date']; ?></td>
						<td><?php if($results['year_id'] == 1){ echo 'First Year'; } else if($results['year_id'] == 2){ echo 'Second Year'; } ?></td>
<td><a  class="grade_view" id="<?php echo $results['id'];?>" onclick="view_grades_after_penalties(<?php echo $results['id'];?>,<?php echo $results['year_id']; ?>,<?php echo $results['academic_id']; ?>)"> View </a></td>
						</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>
$(document).ready(function(){
	$('#batch').hide();
});
$('body').on('change','#year_id',function(){  
var academic_year_id = $('#academic_id').val();
var year_id = $('#year_id').val();
//alert(year_id);
	
	$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'experiential-course/ajax-check-gradeaftrpenalty-data';?>',
			data: {academic_year_id:academic_year_id,year_id:year_id}
		}).done(function( data ) {
		   var result = $.parseJSON(data);
			if(result !=0){
				alert('This Batch and Year is already Existed');
				$("#academic_id").find('option').attr("selected",false) ;
				$("#year_id").find('option').attr("selected",false) ;
				$('#payslipData').val();
				$('#batch').hide();
				$('#batch').val('');
				$('#course_grade_details').empty('');
			}
	else {

		$.ajax({
				type: "POST",
				url:'<?php echo $this->mainconfig['host'].'experiential-course/ajax-get-grade-after-penalties';?>',
				data: {academic_year_id:academic_year_id,year_id:year_id}
			}).done(function( data ) {
				
				$('#course_grade_details').empty('');
				$('#course_grade_details').html(data);	
			});	
       }
    });	 
});


 $('body').on('change', '#academic_id', function() {		
var academic_id=$('#academic_id').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	 
 }); 
 
  function view_grades_after_penalties(val,year_id,academic_id){
		 var id = val;
		 var year_id = year_id;
		 var academic_id = academic_id;
		 if(year_id == '1'){
			 
		 $.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'experiential-course/ajax-get-expcourses-grades-after-penalties-view';?>",
              data: { id:id,year_id:year_id,academic_year_id:academic_id}
            }).done(function(data) {
				$(".sub").hide();
				$(data).insertAfter("tr.id"+id);
			});
		 }else if(year_id == '2'){
			 
			 $.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'experiential-course/ajax-get-expsecond-year-grade-after-penalties-view';?>",
              data: { id:id,year_id:year_id,academic_year_id:academic_id}
            }).done(function(data) {
				$(".sub").hide();
				$(data).insertAfter("tr.id"+id);
			});
			 
		 }
		 
	 }
</script>