
<script>
    
    
var id = '<?=$this->id?$this->id:0;?>';
if(id != 0){
$('#fac').hide();
   $('<div class="col-sm-12 text-center"><h4 class="text-danger"><strong>**Published TABULATION REGISTER Cannot be Modified.<br><small class="text-danger"><b>(Note:</b>&nbsp; Course Listed only with Created Evaluation Components.<b>)</b></small></strong></h4></div>').insertBefore('table');
}
else
{
   $('#fac').show(); 
}
</script>
<style>
@media print {
  * {
    display: none;
  }
  #printBox {
    display: block;
  }
}
    
/*    button{*/
/*        display:none;*/
/*    }*/
    
/*     table
    {
        width: auto;
        font-size: 1em;
    }
    table tr{
        padding:0 !important;
    }
    table tr,th,td {
        min-width: .1em !important;
        max-width:3.5em !important;
        word-wrap:break-word !important;
         padding:0.5em !important;
    }*/
    
/*     table {
    table-layout: auto !important;
}

.table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th {
    width: auto !important;
    padding:0 !important;
}*/

/*   @media print*/
/*{*/
/*  table { page-break-after:auto !important; }*/
/*  tr    { page-break-inside:avoid !important; page-break-after:auto !important; }*/
/*  td    { page-break-inside:avoid !important; page-break-after:auto !important; }*/
/*  thead { display:table-header-group !important;}*/
/*  tfoot { display:table-footer-group !important; }*/
/*}*/
/*</style>
<?php
 $eval_items = new Application_Model_EvaluationComponentsItems();
    $course_learning = new Application_Model_ElectiveSelection();
                    $StudentPortal_model = new Application_Model_StudentPortal();
                      
                        $Corecourselearning_model = new Application_Model_Corecourselearning();
                         $acd_details = new Application_Model_Academic();
                        $deg_details = new Application_Model_Department();
                          $term_details = new Application_Model_TermMaster();
                             $semester_rule = new Application_Model_SemesterRule();
                              $course_details = new Application_Model_Course();
                                 $GradeAllocation_model = new Application_Model_GradeAllocation();
$fail_Val = array('D'=>'F','F'=>'F');
$item_result = $this->result;
$passpercent = $this->passpercent;
$acad = $this->acad;
$ter = $this->term;
$dept_name = $this->dept_name;


//====Variable Declaration==========//
$i = 1;
$k = 0;
$mks = $tot_credit=$mksweightage = $tot_credit_point = $tot_grade_point = $one_row = $stu_data_pr = $component = $weightage = 0;
$EvaluationComponents_model = '';
$geData = array();
$geWeightage = array();
$ct_arr = $weightage_arr = $component_arr = array();
$extraSem = 0;
$session = $this->session;
//======['start printing tabulation register']=======//

    ?>
<!--[table head to be aligned into middle]---------->
    <style>


        
    </style>
    <div class="box-body table-responsive" >
        <div style="overflow-x:scroll" >
            <div id='printBox'>
            <table class="mb30 jambo_table bulk_action datatable datatable-multi-row"  border ='1' id='dataTable' style="height:20em;" >
                <thead>
                    <tr style="padding:0">
                        <?php  ?>
                        <input type ="hidden" id='tabl_id' value="<?=$this->id?$this->id:0;?>"/>
                        <th rowspan="4"  class="complex">S. No.</th>
                        <th rowspan="4" data-datatable-multi-row-rowspan="4" class="complex">UID</th> 
                             <th rowspan="4" data-datatable-multi-row-rowspan="4" class="complex">Reg. No./Exam. Roll No./Candidate Name/Father Name</th>
                        <th></th>
                        <?php
                       
                        for ($i = 0; $i < count($item_result); $i++) { 
                         $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']); 
                        ?>
                       
                        <th colspan = "<?=count($course_type_result)+2?>">Semester <?=$i+1;?></th>
                        
                        <?php } ?>
                        <th rowspan="2"   style='padding: 0.2em;'>Grand Total</th>
                        <th rowspan="2"   style='padding: 0.2em;'>CGPA (cr. point/cr.)</th>
                        <th rowspan="2"   style='padding: 0.2em;'>%(Percentage)</th>
                        <th rowspan="2"   style='padding: 0.2em;'>CGPA Grades</th>
                        <th rowspan="2"   style='padding: 0.2em;'>Remarks/Fail in</th>
                        </tr>
                        
                        
<!--                        <th rowspan="2" class="complex">ID Number</th>-->
                        
                     <tr>
            
                <?php
                /*
                 * calling model course_corse_learning
                 * if course credit has been created
                 * then get the courseType value 
                 * 
                 */
                 $student_course = [];
                for ($i = 0; $i < count($item_result); $i++) {
                 
                $tot_arr = array(); 
        $credit_head_arr = array();
                
                $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
//-------------------------------------------------------****************------------------------------------------------------------------------------------------------//     
                foreach ($course_type_result as $course_type_key => $course_type_val) {//====printing upper head with component==// 
          
                    $item_result[$i]['course_id'] = $course_type_val['course_id'];
                    $student_course[] = $course_type_val;
                    ?>
                  
<!--                    <th rowspan="2" class="complex">Course Code</th>-->
                    <?php if ($component == 0) { ?>
                   
                        <th class="complex" >Course Code</th>
 
                        <?php $component++;
                    } ?>
                    <?php
                    //====================[getting all the evaluation component]======================================//
                  $EvaluationComponents_model = new Application_Model_EvaluationComponents();
                    $result = $EvaluationComponents_model->getAllComponentsonTerms(0, 0, $item_result[$i]['course_id']); 
                     if($course_type_key == 1 && $item_result[$i]['term_id']===310){
                                    $course_type_val = $course_type_result[2]; 
                                }
                                else if($course_type_key == 2 && $item_result[$i]['term_id']===310){
                                   $course_type_val = $course_type_result[1];
                                } 
                  
                    ?>
                        
                    <th class="complex" style='padding: .2em;'>
                        <?php if(!in_array($course_type_val['ge_id'],array(34,37,38,14,35,4,3,10,11,23,9))){  
                        if(!in_array($course_type_val['course_code'],array('AECC 101(H)','AECC 101(E)'))) { 
                            echo $course_type_val['course_code']; 
                        }else {
                             echo 'AECC'; 
                        }
                            }
                        else{ echo $course_type_val['ct_name']; } ?></th>
                   
                 
                    
    <?php   } //print_r($course_type_val);
                 //   die();?>
                <th rowspan="1"   style='padding: 0.2em;'>Total</th>
                <th class="complex" style='padding: 0.2em;'>SGPA <br/>(Cr. Point/ Cr.)</th>
                
               
                <?php  } ?>
                </tr> <?php //==========[END Printing upper components]====================//  ?>
  <!-----------------------------------------------------------**************************---------------------------------------------------------------------------->
                <tr>
                    <?php
                     
                    for ($i = 0; $i < count($item_result); $i++) {
                       
                    //========================[Getting all the course and ge_id for the weightage]============================//
                    $newData = $EvaluationComponents_model->getAllComponentsonTerms1($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], 0);

                   
                    $getNewWeightage = $ct_arr = $getWeightage = array();

                    //==================[Fettering Weightage according to their courses_id]=============================================]=======//
                    foreach ($newData as $Studkey => $newVal) {
                        $getWeightage[$newVal['ct_id']][$newVal['course_id']][$newVal['component_id']] = $newVal['weightage'];
                    }
                    
                     $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
                    //===========================[Start printing the lower head with weightage]==============================================//
                    foreach ($course_type_result as $course_type_key => $course_type_val) {
                        $component_arr = array();
                        $item_result[$i]['course_id'] = $course_type_val['course_id'];
                        //===============[Filtering according to their component id]======================//
                        foreach ($getWeightage[$course_type_val['ct_id']] as $Studkey => $newVal) {
                            Ksort($newVal);
                            foreach ($newVal as $component_id => $weightage_val) {
                                $getNewWeightage[$course_type_val['ct_id']][$component_id][] = $weightage_val;
                            }
                        }
                        
                        $result = $getNewWeightage[$course_type_val['ct_id']];
                        if($course_type_val['count_id'] == 0){
                        $credit_head_arr[$item_result[$i]['term_id']][] = $course_type_val['credit_value'];
                        $tot_credit+=$course_type_val['credit_value'];
                        }
                        ?>
                        <?php if ($weightage == 0) { ?>
                            <th >Credit</th>
                            <?php $weightage++;
                        }else if($course_type_key == 0){  ?>
                      
                        <th></th>
                        <?php } ?>
                        <?php $arr_check = array(); ?>
                        <!--weightage---->
                        <th><?= $course_type_val['credit_value'];?></th>
                        <?php
                        
                        
                        /*
                         * this loop making single head uniqe if duplicates 
                         * marks and print the weightage
                         * 
                         * 
                         */
                         
                        foreach ($result as $k => $val) {
                            $val1 = $val;
                            $val = array_unique($val);
                            ?>
                            
                              
                             <?php // implode('/', $val);
                                $new_arr = $val1;
                                foreach ($new_arr as $weightage_key => $to_val) {
                                    $tot_arr[$course_type_val['ct_id']][$weightage_key] += $to_val;
                                }
                                ?>
                           
                            <?php
                        }

                        $total_sub_mks = array_unique($tot_arr[$course_type_val['ct_id']]);
                        ?>
                        
    <?php }?> 
      <th><?= array_sum($credit_head_arr[$item_result[$i]['term_id']]); ?></th>
    <?php } ?>
    <th></th>
    <th><?=$tot_credit;?></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
                </tr>
                
                
                
                   <tr>
                    <?php
                    for ($i = 0; $i < count($item_result); $i++) {
                              
                $tot_arr = array(); 
                $credit_head_arr = array();
                 $total_head_arr = array();
                    //========================[Getting all the course and ge_id for the weightage]============================//
                    $newData = $EvaluationComponents_model->getAllComponentsonTerms1($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], 0);

                   
                    $getNewWeightage = $ct_arr = $getWeightage = array();

                    //==================[Fettering Weightage according to their courses_id]=============================================]=======//
                    foreach ($newData as $Studkey => $newVal) {
                        $getWeightage[$newVal['ct_id']][$newVal['course_id']][$newVal['component_id']] = $newVal['weightage'];
                    }
                    
                     $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
                    //===========================[Start printing the lower head with weightage]==============================================//
                    foreach ($course_type_result as $course_type_key => $course_type_val) {
                        $component_arr = array();
                        $item_result[$i]['course_id'] = $course_type_val['course_id'];
                        //===============[Filtering according to their component id]======================//
                        foreach ($getWeightage[$course_type_val['ct_id']] as $Studkey => $newVal) {
                            Ksort($newVal);
                            foreach ($newVal as $component_id => $weightage_val) {
                                $getNewWeightage[$course_type_val['ct_id']][$component_id][] = $weightage_val;
                            }
                        }
                        
                        $result = $getNewWeightage[$course_type_val['ct_id']];
                        ?>
                        <?php if ($mksweightage == 0) { ?>
                            <th >Full Marks/ Pass Marks</th>
                            <?php $mksweightage++;
                        }else if($course_type_key == 0){ ?>
                    
                        <th></th>
                        <?php } ?>
                        <?php $arr_check = array(); ?>
                        <!--weightage---->
                        <th>
                        <?php
                        $x = 0;
                        /*
                         * this loop making single head uniqe if duplicates 
                         * marks and print the weightage
                         * 
                         * 
                         */
                         
                        foreach ($result as $k => $val) {
                            $val1 = $val;
                            $val = array_unique($val);
                            ?>
                            
                             <?php // implode('/', $val);
                                $new_arr = $val1;
                                foreach ($new_arr as $weightage_key => $to_val) {
                                    $tot_arr[$course_type_val['ct_id']][$weightage_key] += $to_val;
                                }
                                ?>
                           
                            <?php
                        }
                        $passpercent = $this->passpercent;
                        $total_sub_mks = array_unique($tot_arr[$course_type_val['ct_id']]);
                           if($total_sub_mks[0]==250){
                                    $passpercent = 50;}
                               else if($total_sub_mks[0]==25){
                                   $passpercent = 50;
                    }
                    
                                   $passmarks = ((int)$passpercent/100)*(int)$total_sub_mks[0];
                                   if($course_type_val['count_id'] == 0){
                            $total_head_arr[$item_result[$i]['term_id']][]  =  $total_sub_mks[0]; 
                             $mks += $total_sub_mks[0];
                                   }
                        echo $total_sub_mks[0].'/<br/>'.$passmarks;
                     
                        ?>
                    
                        
    <?php }?>  
    <th><?=array_sum($total_head_arr[$item_result[$i]['term_id']]);?></th>
    <?php }?>
    <th></th>
   <th><?=$mks;?></th>
   <th></th>
   <th></th>
   <th></th>
   <th></th>
                </tr>
               
                
                
               
  <!-----------------------[End printing head]--------------------------------------------------------------------------------------------------->
                </thead>
                <tbody>
                     
                    <?php 
                    $m = 1;
                    $inde = 0;
                    $corce = array();
                 
                //===============[Degree_id & cmn terms]==========================//    
                       if(!empty($acad)){
                        $d_id = $acd_details->getRecord($acad)['department'];
                        $degree_id= $deg_details->getRecord($d_id)['degree_id'];
                      
                        $term_count = $term_details->getRecordByAcademicId($acad);
                     
                       // $details = $semester_rule->checkRow($degree_id, $cmn_term);
               //========================[END]========================//
               
                    $category_data = $StudentPortal_model->getstudentsdetailsFinal($acad,count($term_count));
                    
                    foreach ($category_data as $stu_data){
                    $credit_arr = array();
                    $credit_remarks = $grade_arr = array();
                    $cgpa_remarks='';
                     $gp_tot = $gr_tot = $count_id = $p_count = $appear_count = $tot_credit_point = $total_gradepoint = $one_row = $stu_data_pr = 0;
                    $fail_in =$gp =  $fcourse_ids= $promotion = $pass_in_ct_id  = $fail_ct_id =  $ge_check_arr = array();
                    
                    $sgparem = '';
                        ?>
                   
                        <tr title = "<?php echo $stu_data['students']; ?>">
                            <input type='text' style="display:none;" name='stu_ids[]' value="<?=$stu_data['student_id'];?>" />
                           
                            <?php
                            for ($i = 0; $i < count($item_result); $i++) {
                            $tot_arr = array(); 
                           $tgp = $tcp = $tot_term_cr = $tot_term_mks_head =  $tot_term_masrks = 0;
                        $ge_check_arr = array();
                     //   $sgparem = '';
                        
                            $course_type_result = $Corecourselearning_model->getcourseTypeOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
  
    
                            foreach ($course_type_result as $course_type_key => $course_type_val) {
                                  if($course_type_key == 1 && $item_result[$i]['term_id']===310){
                                    $course_type_val = $course_type_result[2]; 
                                }
                                else if($course_type_key == 2 && $item_result[$i]['term_id']===310){
                                   $course_type_val = $course_type_result[1];
                                } 
                                $ge_id_arr = $Corecourselearning_model->getcourseTypeOn1($item_result[$i]['academic_year_id'], $item_result[$i]['term_id']);
                                $ge_id = 0;
                                if ($course_type_val['ge_id'] != 0) {
                                    $ge_id = $course_type_val['ge_id'];
                                    foreach ($ge_id_arr as $ge_key => $ge_val) {
                                        $item_result[$i]['course_id'] = $course_learning->getStudentSelectedElectivesOnGeId($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], $stu_data['student_id'], $ge_val['ge_id'],$ge_val['course_id']);
                                        
                              if (!empty($item_result[$i]['course_id']) && !in_array($ge_val['course_id'], $ge_check_arr) && $course_type_val['ct_id']==$ge_val['ct_id']) {
                                            $ge_check_arr[] = $ge_val['course_id'];
                                            $count_id = $ge_val['count_id'];
                                            $prin_len = 0;
                                            break;
                                        } else {
                                         $item_result[$i]['course_id']='';
                                         $count_id = 0;
                                        }
                                    }
                                } else{
                                          $item_result[$i]['course_id'] = $course_type_val['course_id'];
                                }
                                
                             //   $result = $EvaluationComponents_model->getAllComponentsonTerms(0, 0, $item_result[$i]['course_id']);
                            if(empty($item_result[$i]['course_id']))
                                   $prin_len = 1;
                                ?>

                                <?php if ($stu_data_pr == 0) { ?>
                                    <td rowspan="3" data-datatable-multi-row-rowspan="3" class="group" style="vertical-align:middle;"><?php echo $m; ?></td>	
                                    <td rowspan="3" data-datatable-multi-row-rowspan="3" class="group" style="vertical-align:middle;"><?php echo $stu_data['stu_id']; ?></td>
                            <input type='text' style="display:none;"  name="grade[student_id_<?= $stu_data['student_id'].$item_result[$i]['academic_year_id']; ?>_<?php echo $item_result[$i]['term_id']; ?>_<?php echo $item_result[$i]['course_id']; ?>][]" id="student_id" value="<?php echo $stu_data['student_id']; ?>" />
<!--                            <td><?php echo $stu_data['stu_id']; ?></td>-->
                          
                            <?php $stu_data_pr++;
                        }
                        ?>

                        <?php
                          if($item_result[$i]['course_id']){
                       
                        $course = $course_details->getRecord($item_result[$i]['course_id']);
                          }
                          else{
                                    $course['course_name'] ='--'; 
                                $course['course_code'] ='--'; 
                          }
                        ?>

                        <?php 
                        if (!in_array($item_result[$i]['course_id'], $corce[$course_type_val['ct_id']])) {
                            $corce[$course_type_val['ct_id']][] = $item_result[$i]['course_id'];
                        } ?> 
<!--                        <td><?php echo $course['course_code']; ?></td>-->
                        <?php
                        ?>
                        <?php if ($one_row == 0) { ?>
                            <td><?php echo $stu_data['reg_no']; ?>/ <?php echo $stu_data['exam_roll']; ?>/ <?php echo $stu_data['students']; ?>/ <?=$stu_data['father_name']; ?></td>
                            <td></td>
                            <?php $one_row++;
                        } ?>
                        <?php
                        $total_divisor = $total_marks_obained = $total = 0;
                        if(!empty($item_result[$i]['course_id'])){
                        $component_grades = '';
                        $letter_grade1 = '';
                        $pass_fail = 'P';
                        $pass_fail_final = 'P';
                        $new_numeric = 0;
                        // foreach($result as $k => $val) { 
                        
//                        if($this->archive==1 ){
//                         $grade_result = $GradeAllocation_model->getGradeDeletedFinalRecordsOn($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], $item_result[$i]['course_id'], $stu_data['student_id']);}
//                      
//                        
//                     if(count($grade_result)==1  && empty($grade_result[0])){
                        $grade_result = $GradeAllocation_model->getGradeFinalRecordson($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], $item_result[$i]['course_id'], $stu_data['student_id']);
//                     }
                        $component_grades = $grade_result['component_id'];
                        //$grade = $grade_result['grade_value'];
                        $component_res = $grade_result['total_weightage'];
                        $number_result =  $grade_result['number_value'];
                       
                        $grade_result = explode(",", $grade_result['grade_value']);
                        ?>

                        <?php
                        $comp_weightages = '';
                       
                       
                            $prin_len--;
                            // echo "<pre>";print_r($number_result);
                            $style = '';
                            $gradePr ="";
                                $letter_grade='';
                                        if (in_array("F",$grade_result) || in_array("D",$grade_result)) {
                                            $style = '';
                                            $pass_fail = 'F';
                                            $pass_fail_final = 'F';
                                            $style="style='color:red'";
                                            
                                        } else if (in_array("Ab",$grade_result) ) {
                                            $number_result = is_numeric($number_result) ? (int) $number_result : 'Ab';
                                            $style = 'style="color: #ff0000"';
                                            $style1 = 'style="color: #ff0000"';
                                            $gradePr = "Ab";
                                            $pass_fail = 'F';
                                             $pass_fail_final = 'F';
                                              $style="style='color:red'";
                                              $sgparem ="F";
                                            
                                        } else if (in_array("Na",$grade_result)
                                                || in_array("NA",$grade_result)) {
                                            $number_result = is_numeric($number_result) ? (int) $number_result : 'NA';
                                            $style = 'style="color: #ff0000"';
                                            $pass_fail = 'F';
                                            $gradePr = "NA";
                                             $pass_fail_final = 'F';
                                           $style="style='color:red'";
                                          $sgparem ="F";
                                        }
                                        else if($number_result == ''){
                                        $number_result = '--';
                                        $letter_grade = '--';
                                        }
                                        elseif ($number_result == 0) {
                                            $number_result = 0;
                                        } else if (!count($grade_result)) {
                                            $number_result = '--';
                                            $letter_grade = '--';
                                        }
                                      
                            ?>

                          
 
                            <?php $marks_obained = $total_marks_obained = is_numeric($number_result) ? (int) $number_result : 0; ?>
                            <?php 
                            if($course_type_val['count_id'] == 0){
                            $gr_tot+=$total_marks_obained;
                            }

                            $tot_marks = (int) $component_res;
                            $total_divisor += (int) $tot_marks;
                      if($letter_grade == '--'){
                                $letter_grade = '--';
                            }
                            elseif ($tot_marks != 0 && $marks_obained > 0) {
                                
                                $letter_grade = $pass_fail;
                            } 
                            
                            elseif ($tot_marks == 0) {
                                $letter_grade = '--';
                            } elseif ($marks_obained == 0) {
                                $letter_grade = 'F';
                                $pass_fail = 'F';
                                 $pass_fail_final = 'F';
                                  $style="style='color:red'";
                            }
                            ?>
                            <?php if(count($grade_result) == 1 && empty($grade_result[0])){ 
                                $prin_len = 0;
                            for ($o = 0; $o < $prin_len; $o++) { ?>

                            <!--<td>--</td>-->
                          
                            <?php } } ?>
                            
                            <?php
                             if($total_marks_obained == 0){
                                $pass_fail = '--';
                            }
                if (in_array(strtolower($letter_grade),array('f','d'))) {
                    $pass_fail='F';
                     $pass_fail_final = 'F';
                     $style="style='color:red'";
                   
                }
                            ?>
            <?php  
                        } else{
                            $total_marks_obained = '--';
            for ($o = 0; $o < $prin_len; $o++) { ?>

                            <!--<td>--</td>-->
                            
            <?php 
                
            }    }
            // if($ge_id != 0){
            //  echo $ge_id; die;
            // }
            ?>
                           
                          <td <?= $style; ?>><?= $total_marks_obained==0?$gradePr:$total_marks_obained; ?><?php if($pass_fail_final == 'F' && $total_marks_obained!= '--'){echo '*';} ?>  <?php if(!in_array($ge_id,array(0,34,37,38,30,24,27,26,25,32,33))){echo $course['course_code']; } ?></td>

            <?php
            if($item_result[$i]['course_id']){
            // total credit value 
           
            $course_credit_info = $Corecourselearning_model->getCoreCouseDetailByTermAcademicCourse($item_result[$i]['academic_year_id'], $item_result[$i]['term_id'], $item_result[$i]['course_id']);
            //  echo "<pre>";print_r($course_credit_info);exit;
            ?>                  
                        <?php
                        //==========[Add all the credit point of all the coure of student simply]
                         $tot_credit_point += (double) ($course_credit_info['count_id'] == 0 ? $course_credit_info['credit_value'] : 0);
                         $tcp +=(double) ($course_credit_info['count_id'] == 0 ? $course_credit_info['credit_value'] : 0);
                        ?>
                      
                        <!--<td class="no_print"><?= $course_credit_info['count_id'] == 0 ? $course_credit_info['credit_value'] : 0; ?></td>-->
            <?php
            
             
                       
            
            //letter grade
            $total_marks_obained = $total_marks_obained != 0 ? $total_marks_obained : '--';
//$tot_term_masrks
            $original_grade = '';
            $tot_marks = $tot_arr[$course_type_val['ct_id']][array_keys($corce[$course_type_val['ct_id']], $item_result[$i]['course_id'], true)[0]];
            if (!empty($total_divisor)) {
                if($total_marks_obained != '--' ){
                $num = round(((int)$total_marks_obained / $total_divisor) * 100);
                $ref_grade_item = new Application_Model_ReferenceGradeMasterItems();  
                $letter_grade = $ref_grade_item->getRecordByNumGrade($num,$degree_id,$session);
                $original_grade =$letter_grade;
                $letter_grade = strtolower($letter_grade) == 'd'?'F':$letter_grade;
                }
                else {
                    $letter_grade = 'F';
                }
            } else {
                $letter_grade = 'F';
                $pass_fail='F';
                 $pass_fail_final = 'F';
            }
            ?>
                        <?php
                        if (strtolower($letter_grade) == 'f') {
                           
                            $pass_fail = 'F';
                             $pass_fail_final = 'F';   
                        }
                        $pass_fail =  $letter_grade == 'F' ? 'F' : 'P';
                       
            ?> 
            
            
            <?php
            //grade point
            $pass_fail = $pass_fail_final;
             
            if($letter_grade == 'F'){
            $sgparem = 'F';
            $cgpa_remarks = 'F';
            $credit_remarks[$i]='F';
            }
            else
            {$credit_remarks[$i]='P';}
            if (!is_numeric($letter_grade) && !empty($letter_grade)  ) {
                $ReferenceGradeMaster_model = new Application_Model_ReferenceGradeMaster();
                     $letter_grade = $pass_fail == 'F' ? 'F' : $letter_grade;
                     
                $letter_grade_result = $ReferenceGradeMaster_model->getNumberGradeValue(0, $letter_grade,$degree_id,$session);
                $numeric_grade = $letter_grade_result['number_grade'];
            } else if (is_numeric($letter_grade)) {
                
                $numeric_grade = $letter_grade;
            } $total = $course_credit_info['count_id'] == 0 ? $numeric_grade * $course_credit_info['credit_value'] : 0;
            }
            $credit_arr[$i][] = empty($numeric_grade)?0:$numeric_grade;
            ?>
                        <!--<td class="no_print"><?=empty($numeric_grade)?0:$numeric_grade;?></td>-->
            <?php
            //======[Adding all the grade point of all the core of same student];
            if($course_type_val['count_id'] == 0){
             $tot_term_masrks += $total_marks_obained;
            }
            $total_gradepoint += $total;
            $tgp+=$total;
            $grade_arr[$i][] = $total;
            ?>
                        <!--<td class="no_print"><?php echo number_format($total, 0); ?></td>-->
                       
                         <?php
                          
            if (strtolower($pass_fail) == 'f') {
                if(!empty($item_result[$i]['course_id'])){
                    $fail_in[] = $course_type_val['ct_name'];
                    $fail_ct_id[] = $course_type_val['ct_id'];
                     $fcourse_ids[] =   $item_result[$i]['course_id'];
                     
                    
                }
               
            }else if(strtolower($pass_fail) == 'p'){
                    if(!empty($item_result[$i]['course_id']))
                    $pass_in_ct_id[] = $course_type_val['ct_id'];
                    $gp[] = $total;
                }
            ?>
                        <input type='text' style="display:none;"  name="grade[grade_point_<?= $stu_data['student_id'].$item_result[$i]['academic_year_id']; ?>_<?php echo $item_result[$i]['term_id']; ?>_<?php echo $item_result[$i]['course_id']; ?>][]" value="<?php $tot = number_format($total, 2);
            echo $tot;
            ?>" />
                           <?php }
                           if(strtolower($pass_fail) == 'p'){
                            $sgpa = $tgp / $tcp;
                           }else{
                           $sgpa ='0';
                           } 
                           
                           ?>
                        
                        
                       <?php //==================[Promotion Rules]=====================//
                       
//                               $final_remarks = 'P';
//                               if($details[0]['credit_score']<=round(number_format($sgpa, 2)*10) 
//                                   && $details[0]['semester_paper_count'] <= count(array_unique($pass_in_ct_id))
//                                   && $details[0]['appeared_paper'] <= $appear_count){
//                                   $term_name = $term_details->getAcademicTermIdAction($item_result[$i]['academic_year_id'],$cmn_term);
//                                   $promotion = "Promoted to $term_name";
//                               }
//                           else {
//                                    $final_remarks ='F';
//                                    $promotion = "--";
//                                }
                       ?>
                        
                        
                    <td rowspan="1" data-datatable-multi-row-rowspan="3" class="group" style="vertical-align:middle;"><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{ echo $tot_term_masrks; }?></td>    
                      <td rowspan="3" data-datatable-multi-row-rowspan="3" class="group" style="vertical-align:middle;"><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{ echo number_format($sgpa, 2); }?></td>
                      
                    <!--<td><?=$promotion;?></td>-->
                    <?php if (strtolower($final_remarks) == 'f') {
              
            }?>
        <!--<td><?=implode('/', array_unique($fail_in)); ?></td>-->
         <?php $termDet = new Application_Model_TermMaster();
        
                $year_id = $termDet->getRecord($item_result[$i]['term_id']);
                $term_string = "/term/{$year_id['cmn_terms']}";
                $year_id = $year_id['year_id'];
        ?>
        <!--            <td>  <a class="btn btn-primary" target="_blank" href="<?php echo $this->mainconfig['host'];?>report/secondyeargradesheetreport/id/<?php echo $stu_data['student_id']; ?>/acd_id/<?php echo $item_result[$i]['academic_year_id']; ?>/year/<?php echo $year_id.$term_string; ?>">Download</a></td>-->
        <!--<td>   <a class="btn btn-link" target="_blank"  onclick="window.open('<?php echo $this->mainconfig['host'];?>report/secondyeargradesheetreport/id/<?php echo $stu_data['student_id']; ?>/acd_id/<?php echo $item_result[$i]['academic_year_id']; ?>/year/<?php echo $year_id.$term_string; ?>/mode/view', '_blank', 'toolbar=yes,scrollbars=yes,resizable=yes,top=100,left=100,width=1100,height=800');" href="#">View </a></td>-->
       
        
                      
                        <?php }  $cgpa = number_format($total_gradepoint/$tot_credit,2);   $percent =  number_format(($cgpa*9),2);
                                if($degree_id==3)
                                $percent = number_format(($cgpa*9.25),2);
                                else if($degree_id > 1 ){
                                    $percent = number_format(($cgpa*9.5),2);
                                }
                               if($percent>0){
                                 $letter_grade = $ref_grade_item->getRecordByNumGrade1($percent,$degree_id,$session); 
                               }
                               else
                               {
                                   $letter_grade['letter_grade'] = "F";
                                   $letter_grade['Des'] = "Fail";
                               }
                                
                                 if(!empty($fail_in)){
                                     $cgpa_remarks = $sgparem ='F';
                                     $count_id = 0;
                                    
                                 }
                                 ?>
                                 
                        <td><?php if($cgpa_remarks == 'F' && $count_id == 0){echo '--';}else{ echo $gr_tot;} ?></td>
                      <td rowspan="3" data-datatable-multi-row-rowspan="3"><?php if($cgpa_remarks == 'F' && $count_id == 0){echo '--';}else{ echo number_format($total_gradepoint/$tot_credit,2);} ?></td>
                       <td rowspan="3" data-datatable-multi-row-rowspan="3"><?php if($cgpa_remarks == 'F' && $count_id == 0){echo '--';}else{ echo $percent.'%'; } ?></td>
                        <td rowspan="3" data-datatable-multi-row-rowspan="3"><?php if($cgpa_remarks == 'F' && $count_id == 0){if($degree_id!=3){echo 'Pending';}else{echo 'Pending';}}else{ echo $letter_grade['letter_grade']." (".$letter_grade['des'].")"; } ?></td>
                         <td rowspan="3" data-datatable-multi-row-rowspan="3"><?=implode('/', array_unique($fail_in)); ?></td>
                    </tr> 
                    
                    <tr>
  
                        <?php 
                         $k=0;
                        for ($i = 0; $i < count($item_result); $i++) {
                            
                        foreach($credit_arr[$i] as $credit_key => $cval) {  ?>
                        
                        <?php if($k == 0){?>
                        
                        <td>GRADE POINT</td>
                        <td></td>
                        
                        <?php $k++; } ?>
                       <td class="no_print"><?= $cval ?>
                        <?php } ?>
                        <th></th>
                        <?php }?>
                        <td>--</td>
                    </tr>
                    
                       <tr>
                
                        <?php 
                        $gp_term_total = $k=0;
                        for ($i = 0; $i < count($item_result); $i++) {
                           $gp_term_total = 0;$sgparem='';
                        foreach($grade_arr[$i] as $grade_key => $gval) { ?>
                        
                        <?php if($k == 0){?>
                         <td>Credit Point (Cr. X  Grade Point)</td>
                      
                        <td></td>
                        <?php $k++; } ?>
                       <td class="no_print"><?php if( $gval == 0){echo "--";$sgparem='F';}else{echo $gval;} ?>
                        <?php $gp_tot+=$gval; $gp_term_total+=$gval;} ?>
                        <th class="group" style="vertical-align:middle;"><?php if($sgparem == 'F' && $count_id == 0){echo '--';}else{ echo $gp_term_total;} ?></th>
                        <?php } ?>
                      
                        <td><?php if($cgpa_remarks == 'F' && $count_id == 0){echo '--';}else{echo $gp_tot;}?></td>
                        
                    </tr>
                    
        <?php $m++; ?>
       
    <?php }
                       }
    ?>	
   
  
                </tbody>
                
            </table>
        </div>
        </div>
       
    </div>
    <iframe name="print_frame" width="0" height="0" frameborder="0" src="about:blank"></iframe>
    <div id="addmore_items_<?php echo $i; ?>"></div>
    <br>
    <?php


function selectData($array, $fieldname, $number = 0) {
    try {
        $filterd_value = array();
        if (is_array($array) && is_array($fieldname)) {
            for ($i = 0; $i < $number; $i++) {
                foreach ($fieldname as $field_key => $field_value) {
                    $filterd_value[$i][$field_value] = $array[$i][$field_value];
                }
            }
            return $filterd_value;
        } else {
            throw new Exception('first and second param should be of type array !');
        }
    } catch (Exception $e) {

        echo '<strong>Error Message !</strong>' . $e->getMessage();
    }
}
?>
<!--<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>-->


