
<?php if($this->type !="pay"){?>

<style>
    .multistepformArea{
    padding-top: 1px;
    background-color: white;
	width: 60%;
    min-width: 300px;
	margin: 50px auto;
	position: relative;
}
/*form styles*/
.regForm {
    width: 90%;
    min-width: 300px;
	margin: 50px auto;
	position: relative;
}
#formValidate1 fieldset {
	background: white;
	border: 0 none;
	border-radius: 3px;
	box-shadow: 0 0 1px 1px rgba(0, 0, 0, 0.1);
	box-sizing: border-box;
	position: relative;
}
</style>

<div class="payment">
<div class="multistepformArea">
<form class="regForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >


<div class="row">
    <div class="col-sm-12">
        <fieldset>
    &nbsp; <p><legend >&nbsp;&nbsp;  </legend></p>
        
            <input type="hidden" name="application_no" value="<?= $this->paginator['application_no']; ?>">
            <input type="hidden" name="applicant_name" value="<?= $this->paginator['applicant_name']; ?>">
            <input type="hidden" name="email_id" value="<?= $this->paginator['email_id'] ?>">
            <input type="hidden" name="phone" value="<?=$this->paginator['phone']; ?>">
            <input type="hidden" name="form_id" value="<?= $this->paginator['form_id']; ?>">
            <input type="hidden" name="course" value="<?= $this->paginator['course'] ;?>">
            <input type="hidden" name="form_fee" value="<?= isset($this->paginator['form_fee']) ? $this->paginator['form_fee'] : '900'?>">
            <input type="hidden" name="pay"  value ="pay"/>
            <?php echo $this->form->csrftoken; ?>
        <label>&nbsp; &nbsp; Name: </label> <b> &nbsp;  <?= $this->paginator['applicant_name'] ?></b>
        <label>&nbsp; &nbsp; Email Id :  </label> <b> &nbsp;  <?= $this->paginator['email_id'] ?></b>
        <label>&nbsp; &nbsp; Phone No.:</label>  <b> &nbsp;  <?= $this->paginator['phone'] ?></b> 
        <label>&nbsp; &nbsp; Course (Applied For):</label>  <b> &nbsp; <?= $this->paginator['course_name'] ?></b>  
        <label>&nbsp; &nbsp; Form Id :</label>  <b> &nbsp;  <?= $this->paginator['form_id'] ?></b> </p> <br>
        <p> &nbsp; &nbsp; Please choose the following payment method for final submission of your form. </p>
            <div class="col-sm-3 employee_class">
                <div class="form-group">
                    <input type='Checkbox' name='form_fee' class='evs' value='<?= isset($this->paginator['form_fee']) ? $this->paginator['form_fee'] : '900'?>' checked='checked' onclick="return false" />
                  Application fee: Rs. 1500/-
                  <input type="hidden" name="form_fee" value="1">
                </div>
            </div>
            <div class="col-sm-3 col-sm-offset-3 employee_class">
                <div class="form-group">
                    <?php if($this->paymode ==='R') { ?>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <button id="onlinePayment" value="Online" class="btn btn-primary submit paymentMode" >Pay Now</button>
                    <?php } else if($this->paymode ==='A'){ ?>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  
                    <a href="<?=  $this->baseUrl("multi-step-form/atompayment/a_id/".md5($this->paginator['application_no'])); ?>"> <button  type="button" id="onlinePayment" value="Online" class="btn btn-primary submit paymentMode">Online</button></a>
                    <?php } ?>
                    
                </div>
            </div>
         

            </div>
        </div>
        <div style="float:right;margin-right:2px;padding-bottom: 3em;">

</div>
        </fieldset> 
        </form>
    </div>
</div>
</div></div>
<?php } else{?>
<?php $data = $this->pay_data; ?>
<!--  The entire list of Checkout fields is available at
 https://docs.razorpay.com/docs/checkout-form#checkout-fields -->
<form action="<?=$this->baseUrl('multi-step-form/verify'); ?>" method="POST">
  <script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $data['key']?>"
    data-amount="<?php echo $data['amount']?>"
    data-currency="INR"
    data-name="<?php echo $data['name']?>"
    data-image="<?php echo $data['image']?>"
    data-description="<?php echo $data['description']?>"
    data-prefill.name="<?php echo $data['prefill']['name']?>"
    data-prefill.email="<?php echo $data['prefill']['email']?>"
    data-prefill.contact="<?php echo $data['prefill']['contact']?>"
      data-prefill.application_no="<?php echo $data['prefill']['application_no']?>"
    data-notes.shopping_order_id="3456"
    data-notes.applicant_no ="<?php echo $this->paginator['application_no'];?>"
    data-notes["App No"] ="<?php echo $this->paginator['application_no'];?>"
    data-notes.applicant_name ="<?php echo $this->paginator['applicant_name'];?>"
     data-notes["App Name"] ="<?php echo $this->paginator['applicant_name'];?>"
    data-order_id="<?php echo $data['order_id']?>"
    <?php if ($displayCurrency !== 'INR') { ?> data-display_amount="<?php echo $data['display_amount']?>" <?php } ?>
    <?php if ($displayCurrency !== 'INR') { ?> data-display_currency="<?php echo $data['display_currency']?>" <?php } ?>
	
	
  >
  </script>
  <!-- Any extra fields to be submitted with the form but not sent to Razorpay -->

  <input type="hidden" name="shopping_order_id" value="3456">
  <input type="hidden" name="amount" value="<?php echo $data['amount'];?>">
  <input type="hidden" name="applicant_no " value="<?php echo $this->paginator['application_no'];?>">
  <input type="hidden" name="applicant_name" value="<?php echo $this->paginator['applicant_name'];?>">
  <input type="hidden" name="applicant_email" value="<?php echo $this->paginator['email_id'];?>">
  
</form>
<script>
    $('.razorpay-payment-button').hide();
 $('.razorpay-payment-button').trigger('click');

$('#modal-close').click(function(){
    $('input[name="pay"]').val('');
    location.reload();
    
});
</script>
<?php } ?>

