<div class="right_col">
     <?php if($_SESSION['flash_message']) {?>
  
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $_SESSION['flash_message']; session_unset('flash_message')?>
</div>
 <?php  } ?>
    <div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Change Password</i></div>
		</h3>
			
			
		</div><!-- /.col-->				
	</div>
    </div>
     <div class="x_content">
    <div class="row">
        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >
					<div class="col-sm-3"><h4><span style="color:#777;">Password details</span></h4></div>
					</div>
					 <div class="row masterbox">
					 <div class="row">
					      <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Current Password<span class="asterisk">*</span></label>
                                <?php echo $this->form->current_password; ?>
                            </div>
							</div>
                                                <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">New Password<span class="asterisk">*</span></label>
                                <?php echo $this->form->new_password; ?>
                            </div>
							</div>
                                                <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Confirm Password<span class="asterisk">*</span></label>
                                <?php echo $this->form->confirm_pword; ?>
                              <div id="error">
                              </div>
                            </div>
							</div>
                                             
                                             		
                                         </div>
                                             
                                         </div>
     </div>						
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
										<div style="float:left;margin-right:2px;">
										<button onclick="return confirmPword();" class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
                                                                </div>
                                                        </div>
</form>
</div>
<script>
    
    function confirmPword(){
  
    var password = $("#new_password").val();
    var confirm_pword =$("#confirm_pword").val(); 
    if(password == confirm_pword)
    {
        
        $("#error").text("redirecting..."); 
        $("#error").css("color","green");
        return true;
    }
    else
    {
        $("#error").text('password does not match'); 
        $("#error").css("color","red");
        return false;
    }
    
}

</script>