<?php $result = $this->result; ?>
<?php //echo "<pre>"; print_r($result);exit;    ?>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

    .column {
        display: inline;
        float: left;
        width: 30%;
        padding: 10px;
    }

   
    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>
<div class="right_col">

    <div class="row">
        <div class=" col-xs-12">
            <h3 class="page-title txt-color-blueDark" >
                <div><i class="fa fa-eye">Holidays</i></div>
            </h3>

        </div>
    </div>
    <div class="x_panel">

        <div class="x_title">
            <h2>DMI Holiday</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
              
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">
               <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
                        <thead>
                            <tr>
                                <th style="text-align:center;">S. No.</th>
                                <th class='text-center'>Particulars</th>
                                <th style="text-align:center;">Day</th>
                                <th style="text-align:center;">Starting Date</th>
                                <th style="text-align:center;">Ending Date</th>
                      
                            </tr>
                        </thead>
                        <tbody style="text-align:center;">
                           
                             <?php $i = 0;
                                    $j=1;
                    while ($i < count($result)) { ?>
                           <?php  $date = $result[$i]['start'];
                            $cd1='';
                           ?>
                            <tr>
                                <td><?=$j++;?></td>
                                <td><?= $result[$i]['title']; ?></td>
                                <?php   while (strtotime($date) <= strtotime($result[$i]['end'])) {
            $cd1.=date(" l,", strtotime($date));
            $date = date("Y-m-d", strtotime("+1 day", strtotime($date)));
        } ?>
                                <td><?=$cd1;?></td>
                                <?php $start = explode(" ",$result[$i]['start']); ?>
                                <?php $end = explode(" ", $result[$i]['end']); ?>
                                <td><?= $start[0]; ?></td>
                                <td><?= $end[0]; ?></td>
                            </tr>
                            
                    <?php $i++;} ?>
                        </tbody>
               </table>
            
            
            
        </div>
    </div>
</div>
<script>
    var elements = document.getElementsByClassName("column");
    var i;
    function listView() {
        for (i = 0; i < elements.length; i++) {
            elements[i].style.width = "100%";
        }
    }
    function gridView() {
        for (i = 0; i < elements.length; i++) {
            elements[i].style.width = "30%";
        }
    }
</script>