<?php //header("Location:".$this->mainconfig['host'] . 'student-portal/my-data' );             ?>
<?php //echo $_SERVER['PHP_SELF'];exit; ?>

<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
<style>


    .green{
        background:green;      
    }

    .toDoParrent{
        padding-top:3%;
        background:#ffc10a; min-height:70px;
    }


    .toDoChild{

        color:#fff;

    }
    .toDoChild:hover{
        opacity:0.6;

    }
    .circle{
        padding:40px;

        -webkit-border-radius: 100%;
        -moz-border-radius: 100%;
        border-radius: 100%;
        border:3px solid #fff;

    }

    .toDoRight{
        -webkit-box-shadow: 0px 0px 0px #fff;
        -moz-box-shadow: 0px 0px 0px #fff;
        box-shadow:0px 0px 0px #fff;
        opacity:1;
        background:#9B59B6;
        -webkit-transition: all .5s ease;
        -moz-transition: all .5s ease;
        transition: all .5s ease;
        cursor:pointer;
    }


    .toDoRight:hover{
        opacity:0.6;
    }

    .toDoRight:active{
        opacity:1;
        border-right: 3px solid #000;
    }
    .todoleft:active{
        opacity:1;
        border-right: 3px solid #000;
    }

    .todoleft:hover{
        opacity:0.6;
    }

    .todoleft{
        cursor:pointer;
        -webkit-box-shadow: 0px 0px 0px #fff;
        -moz-box-shadow: 0px 0px 0px #fff;
        box-shadow:0px 0px 0px #fff;
        background:#3498DB;
        min-height:200px;
        opacity:1;
        -webkit-transition: all .5s ease;
        -moz-transition: all .5s ease;
        transition: all .5s ease;
    }

    .btn-align{
        position:absolute;
        bottom:0%;
        right:0%;
    }

    .hide{
        display:none;
    }


    #data1{

        display:grid;
        grid-template-columns: repeat(3,1fr);
        grid-gap:10px;


    }

    #data1>div{
        position: relative;

        cursor: pointer;
        transition: all .2s;
    }


    #data1>div>span{
        position:absolute;
        top:50%;
        left:50%;
        transform: translate(-50%,-50%);
    }





</style>
<!-- page content -->
<div class="right_col" role="main" >
    <!-- top tiles -->
    <div class="row tile_count hide">
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Users</span>
            <div class="count">2500</div>
            <span class="count_bottom"><i class="green">4%</i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-clock-o"></i> Average Time</span>
            <div class="count">123.50</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>3% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Male Students</span>
            <div class="count green">2,500</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Female Students</span>
            <div class="count">4,567</div>
            <span class="count_bottom"><i class="red"><i class="fa fa-sort-desc"></i>12% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Collections</span>
            <div class="count">2,315</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
        </div>
        <div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
            <span class="count_top"><i class="fa fa-user"></i> Total Connections</span>
            <div class="count">7,325</div>
            <span class="count_bottom"><i class="green"><i class="fa fa-sort-asc"></i>34% </i> From last Week</span>
        </div>
    </div>
    <!-- /top tiles -->

    <div class="row" >
        <div class="col-md-12 col-sm-12 col-xs-12" >
            <div class="dashboard_graph">

                <div class="row x_title" >
                    <div class="col-md-4 pull-left" style="border:0px solid #fff;">
                      <!--  <h3>Report Range <small>&nbsp; on the basis of 'Term' and 'Academic ID' </small></h3>-->
                    </div>
                    <div class='col-md-2 '> <h2 class='green' style='font-weight: 600;' id="batch" class="form-control"></h2></div>
                    <div class="col-md-6">
                        <div id="reportrange" class="pull-right" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 0px solid #ccc">

                            <ul class="list-unstyled list-inline">
                                <li><?= $this->form->academic_year_id; ?></li>
                                <li><?= $this->form->term_id; ?></li>	
                                <li><?= $this->form->section; ?></li>	
                            </ul>			
                        </div>
                    </div>
                </div>



                <div class="clearfix"></div>
            </div>
        </div>

    </div>
    <br />






    <!---- [Responsive calendar Zabuto] ----------->
    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="x_content text-center">
            <h4></h4>

            <div class='row'>
                <div id="date-popover" class="popover top" style="cursor: pointer; display: block; margin-left: 33%; margin-top: -50px; width: 175px;" data-original-title="" title="">
                    <div class="arrow"></div>
                    <h3 class="popover-title" style="display: none;"></h3>

                    <div id="date-popover-content" class="popover-content"></div>
                </div>
                <div class="col-md-12" id='my-calendar'>




                </div>
            </div>

            <div class="clearfix"></div>
        </div>

    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="x_panel tile fixed_height_320" style="overflow-y:scroll;">
            <div class="x_title">
                <h2 id='date-change'><?= date('l d M Y'); ?> Session</h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>



            <div class="x_content text-center">
                <!--<img src="<?php //echo $this->mainconfig['publicpath'];?>/images/loader.gif" width='200px'  class="loder_img1" />-->
                <h4></h4>

                <div class='row'>
                    <div class="col-md-12" id='data' >
                        <table class="table">
                            <tr>
                                <th><Strong>Class I:</strong></th>
                                <td ><a href="#" id='class_I' data-toggle="popover"   data-trigger="focus"   data-html="true" data-placement='top' title="Faculties" data-content="">(No Class)</a></td>
                            </tr>
                            <tr>
                                <th><strong>Class II:</strong></th>
                                <td>
                                    <a href="#" id='class_II' data-toggle="popover"   data-trigger="focus"   data-html="true" data-placement='top' title="Faculties" data-content="">(No Class)</a>
                                </td>
                            </tr>
                            <tr>
                                <th><strong>Class III:</strong></th>
                                <td>
                                    <a href="#" id='class_III' data-toggle="popover"    data-trigger="focus"  data-html="true" data-placement='top' title="Faculties" data-content="">(No Class)</a>
                                </td>
                            </tr>
                            <tr>
                                <th><strong>Class IV:</strong></th>
                                <td ><a href="#"  id='class_IV' data-toggle="popover"   data-trigger="focus"  data-html="true" data-placement='top' title="Faculties" data-content="">(No Class)</a></td>
                            </tr>
                            <tr>
                                <th><strong>Class V:</strong></th>
                                <td ><a href="#" id='class_V' data-toggle="popover"   data-trigger="focus"   data-html="true" data-placement='top' title="Faculties" data-content="">(No Class)</a></td>
                            </tr>
                        </table>



                    </div>
                </div>

                <div class="clearfix"></div>
            </div>

        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12" >
        <div class="x_panel tile fixed_height_320 overflow_hidden" style="overflow-x:scroll;">
            <div class="x_title">
                <h2>Sessions:&nbsp;<small id='column_chart_data'></small></h2>
                <div class="clearfix"></div>
            </div>
            <div class='x_content text-center'>
             <!--   <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px' class="loder_img" />-->
                <div id="columnchart_values" ></div>
            </div>
        </div>
    </div>



    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel tile fixed_height_320">
            <div class="x_title">
                <h2 id=''>Yearly Attendance</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content text-center">
                <!--<img src="<?php //echo $this->mainconfig['publicpath'];                 ?>/images/loader.gif" width='200px'  class="loder_img1" />-->
                <h4></h4>

                <div class='row'>
                    <div class="col-md-12 text-center" id='data'>
                        <div class='col-md-offset-2' id="calendar_basic" >
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>




    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="x_panel tile fixed_height_320">
            <div class="x_title">
                <h2>Monthly Attendance</h2>

                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <!--<img src="<?php //echo $this->mainconfig['publicpath'];                 ?>/images/loader.gif" width='200px'  class="loder_img1" />-->
                <h4></h4>

                <div class='row'>
                    <div class="col-md-12" id='data'>
                        <div id="filter_div"></div>
                        <div id="chart_div"></div>
                    </div>
                </div>

                <div class="clearfix"></div>
            </div>

        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="x_panel tile fixed_height_320" style="overflow-y:scroll;">
            <div class="x_title">
                <h2>End Sem Form Fee Status:  <span id='course_fee_paid' style='color:#ff2a70;'> </span> </h2>

                <div class="clearfix"></div>
            </div>
            <div class="x_content ">
                
               

                <div class='row'>
                    <div class="col-md-12">

                       
                <h2>Last Day To Pay Fee:<span id='course_fee_end_date' style='color:#ff2a70;'> </span> </h2> 


                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="col-md-4 col-sm-4 col-xs-12">
        <div class="x_panel tile fixed_height_320">
            <div class="x_title">
                <h2>Sem Fee Transaction's | <span id='fee_paid' style='color:#226B4A;'> </span> | <span id='fee_due' style='color:#ff2a70;'> </span></h2>
                <h2>Last Day To Pay Fee:<span id='end_date' style='color:#ff2a70;'> </span> </h2> 
<!--                <ul class="nav navbar-right panel_toolbox">
                    <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Settings 1</a>
                            </li>
                            <li><a href="#">Settings 2</a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="close-link"><i class="fa fa-close"></i></a>
                    </li>
                </ul>-->
                <div class="clearfix"></div>
            </div>

            <div class="x_content text-center">
                <!--<img src="<?php //echo $this->mainconfig['publicpath'];                 ?>/images/loader.gif" width='200px'  class="loder_img1" />-->
                <h4></h4>

                <div class='row'>
                    <div class="col-md-12" id='data'>

                        <canvas id="chart-area" width="762" height="381" class="chartjs-render-monitor" style="display: block; width: 762px; height: 381px;"></canvas>


                    </div>
                    
                </div>

                <div class="clearfix"></div>
            </div>

        </div>
    </div>

    <div class="clearfix"></div>
</div>

<style>
    a:hover{
        color:#9b131f;
        text-decoration:underline;
    }
</style>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/zabuto_calendar/1.6.3/zabuto_calendar.min.js"></script>-->
<script type="text/javascript" src="<?php echo $this->mainconfig['publicpath'] . '/vendors/my_cal.js'; ?>"></script>
<script src='http://www.chartjs.org/dist/2.7.2/Chart.bundle.js'></script>
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>


<script>

//==============[GET LATEST TERM AND BATCH ACCORDING TO CURRENTDATE]==========//


   /* $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-recent-term-and-batch'; ?>',
        data: {my_date: '<?= date('d-m-Y'); ?>'}
    }).done(function (data) {
        json_new_obj = JSON.parse(data);
        $('#academic_year_id').val(json_new_obj.batch_id);
        var academic = json_new_obj.batch_id;
        if (academic) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-terms-default'; ?>',
                data: {academic_year_id: academic}
            }).done(function (data) {
                //alert(json_new_obj.term_id);
                $('#term_id').empty('');
                $('#term_id').html(data);
                $('#term_id').val(json_new_obj.term_id);
                
                
                  $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-notification'; ?>',
                data: {'_param0': academic, '_param1': json_new_obj.term_id}
            }).done(function (data) {
                json_obj = JSON.parse(data);
                // alert(JSON.stringify(json_obj));
                $('#notification').empty();
                $('#menu1').empty();
                $('#notification').text(json_obj.length);

                for (x in json_obj)
                {
                    $('#menu1').append('<li><a href="'+json_obj[x].assignment_id+'"><span class="image"><img src="<?php echo $this->mainconfig['publicpath']  ?>images/img.png" class="img-thumbnail profile_img" alt="Profile Image"></span><span><span>' + json_obj[x].course_id.course_code + '</span><span class="time">' + json_obj[x].updated_date + '</span></span><span class="message">' + json_obj[x].document_title + '</span></a></li>');
                }
            });
                

                getSessions();

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-fee-trans-details'; ?>',
                    data: {batch_id: academic, term_id: $('#term_id').val()}
                }).done(function (data) {
                    var json_obj = JSON.parse(data);
                    mydonutChart(json_obj);
                });



                monthlyAttendance(<?= date('m'); ?>,<?= date('Y') ?>);
                DatebirthDay(<?= date('m'); ?>);
                getSessions();

                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-attendance-dates'; ?>',
                    data: {
                        batch_id: academic,
                        term_id: $('#term_id').val()

                    }
                }).done(function (data) {
                    json_obj = JSON.parse(data);

                    drawChart(json_obj);
                });



                academic_id = $('#academic_year_id').val();
                term_id = $('#term_id').val();
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-student-class'; ?>',
                    data: {batch_id: academic_id,
                        term_id: term_id,
                        date: <?= date('Y-m-d'); ?>}
                }).done(function (data) {
                    json_obj = JSON.parse(data);
                    $('#date-change').text(json_obj['date']);
                    myVarChart(json_obj);
                });



            });
        }
    });*/


//========[]==========//


    $('#batch').hide();
//get-terms
    $("#academic_year_id").change(function () {
        var academic_id = $('#academic_year_id').val();
<?php $_SESSION['stu_academic'] ?>

        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-terms-default'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#term_id').empty('');
                $('#term_id').html(data);
                term_id = $('#term_id').val();
                term_name = $('#term_id option:selected').text();
<?php $_SESSION['term_id'] = term_id; ?>
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-fee-trans-details'; ?>',
                    data: {batch_id: academic_id, term_id: term_id}
                }).done(function (data) {
                    var json_obj = JSON.parse(data);
                    mydonutChart(json_obj);
                    monthlyAttendance(<?= date('m'); ?>,<?= date('Y') ?>);
                    DatebirthDay(<?= date('m'); ?>);
                    $('#columnchart_values > div >div > span').removeAttr('style');
                    $('#columnchart_values > div >div > span').empty();
                    //getSessions();

                });
                if (json_obj['message'] != '')
                    $('#foot').text(json_obj['message']);

            })
        }
    });

    $('#term_id').change(function () {
        var academic_id = $('#academic_year_id').val();
        var term_id = $('#term_id').val();
        var term_name = $('#term_id option:selected').text();
        <?php $_SESSION['stu_academic'] = academic_id; ?>
        <?php $_SESSION['stu_term_id'] = term_id; ?>
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-fee-trans-details'; ?>',
                data: {batch_id: academic_id, term_id: term_id}
            }).done(function (data) {
                var json_obj = JSON.parse(data);
                //console.log(json_obj);
                mydonutChart(json_obj);
                monthlyAttendance(<?= date('m'); ?>,<?= date('Y'); ?>);
                DatebirthDay(<?= date('m'); ?>);
                $('#columnchart_values > div >div > span').removeAttr('style');
                $('#columnchart_values > div >div > span').empty();
                 $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-section'; ?>',
                data: {
                    term_id: term_id
                }
            }).done(function (data) {
                $('#section').empty();
                 $('#section').html(data);
            });
                });
            }
    });





</script>
<script src="http://www.datejs.com/build/date.js" type="text/javascript"></script>


<script>

    $(document).ready(function () {

        $("#date-popover").popover({html: true, trigger: "manual"});
        $("#date-popover").hide();
        $("#date-popover").click(function (e) {
            $(this).hide();
        });

        $("#my-calendar").zabuto_calendar({today: true,
            action: function () {
                return myDateFunction(this.id, false);
            },
            action_nav: function () {
                return myNavFunction(this.id);
            },
            ajax: {
                url: "<?php echo $this->mainconfig['host'] . 'student-portal/my-data'; ?>",
                modal: true,
            },
            legend: [

                {type: "text", label: "Special event", badge: "00"},
                {type: "block", label: "Regular event"}
            ]
        });
    });



    function myDateFunction(id, fromModal) {
        $("#date-popover").hide();
        if (fromModal) {
            $("#" + id + "_modal").modal("hide");
        }
        var date = $("#" + id).data("date");
        var hasEvent = $("#" + id).data("hasEvent");
        if (hasEvent && !fromModal) {
            return false;
        }
        var section = $('#section').val();
        if ($('#academic_year_id').val() || section) {
            academic_id = $('#academic_year_id').val();
            term_id = $('#term_id').val();
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-student-class'; ?>',
                data: {batch_id: academic_id,
                    term_id: term_id,
                    date: date,
                    section : section,
                }
            }).done(function (data) {
                json_obj = JSON.parse(data);
                $('#date-change').text(json_obj['date']);
                myVarChart(json_obj);

            });
        }
        return true;
    }
    
    

    function myNavFunction(id) {
        $("#date-popover").hide();
        var nav = $("#" + id).data("navigation");
        var to = $("#" + id).data("to");
        monthlyAttendance(to.month, to.year);
        DatebirthDay(to.month)
        console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
    }
</script>


<script>


    function myVarChart(json_obj) {
        var count = [];
        var label_code = ['No Class', 'No Class', 'No Class', 'No Class', 'No Class'];
        var label_name = ['', '', '', '', ''];
        var teachers = ['No Teachers', 'No Teachers', 'No Teachers', 'No Teachers', 'No Teachers'];
        var teacher1, teacher2, teacher3, teacher4, teacher5;
        var teacherS1, teacherS2, teacherS3, teacherS4, teacherS5;

        for (x in json_obj) {
            if (json_obj[x]['course_name'] != null && json_obj[x]['cordinator'] != null) {
                label_code[x] = json_obj[x]['course_code'];
                label_name[x] = json_obj[x]['course_name'];
                if (json_obj[x]['faculty'] == "Not Allotted") {
                    str = json_obj[x]['cordinator'] + ',' + json_obj[x]['dmi_faculty'] + json_obj[x]['visiting_faculty'];
                    teachers[x] = str.replace(/(,$)/g, "")

                } else
                    teachers[x] = json_obj[x]['faculty'];

            } else
            {
                label_code[x] = 'No Class';
                label_name[x] = '';
                teachers[x] = 'No teachers';
            }

        }


        $('#class_I').text(label_name[0] + '(' + label_code[0] + ')');
        $('#class_II').text(label_name[1] + '(' + label_code[1] + ')');
        $('#class_III').text(label_name[2] + '(' + label_code[2] + ')');
        $('#class_IV').text(label_name[3] + '(' + label_code[3] + ')');
        $('#class_V').text(label_name[4] + '(' + label_code[4] + ')');


        $('#class_I').attr('data-content', '(' + teachers[0] + ')');
        $('#class_II').attr('data-content', '(' + teachers[1] + ')');
        $('#class_III').attr('data-content', '(' + teachers[2] + ')');
        $('#class_IV').attr('data-content', '(' + teachers[3] + ')');
        $('#class_V').attr('data-content', '(' + teachers[4] + ')');
    }
</script>
<!---- my dognut chart --->
<script>
    function mydonutChart(json_obj) {
        
         Chart.pluginService.register({
  beforeDraw: function (chart) {
    if (chart.config.options.elements.center) {
      //Get ctx from string
      var ctx = chart.chart.ctx;

      //Get options from the center object in options
      var centerConfig = chart.config.options.elements.center;
      var fontStyle = centerConfig.fontStyle || 'Arial';
      var txt = centerConfig.text;
      var color = centerConfig.color || '#000';
      var sidePadding = centerConfig.sidePadding || 20;
      var sidePaddingCalculated = (sidePadding/100) * (chart.innerRadius * 2)
      //Start with a base font of 30px
      ctx.font = "30px " + fontStyle;

      //Get the width of the string and also the width of the element minus 10 to give it 5px side padding
      var stringWidth = ctx.measureText(txt).width;
      var elementWidth = (chart.innerRadius * 2) - sidePaddingCalculated;

      // Find out how much the font can grow in width.
      var widthRatio = elementWidth / stringWidth;
      var newFontSize = Math.floor(30 * widthRatio);
      var elementHeight = (chart.innerRadius * 2);

      // Pick a new font size so it will not be larger than the height of label.
      var fontSizeToUse = Math.min(newFontSize, elementHeight);

      //Set font settings to draw it correctly.
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      var centerX = ((chart.chartArea.left + chart.chartArea.right) / 2);
      var centerY = ((chart.chartArea.top + chart.chartArea.bottom) / 2);
      ctx.font = fontSizeToUse+"px " + fontStyle;
      ctx.fillStyle = color;

      //Draw text in center
      ctx.fillText(txt, centerX, centerY);
    }
  }
});
        
        var duers = isNaN(parseInt(json_obj['due_fee']))?0:parseInt(json_obj['due_fee']);
        var endDate = json_obj['end_date'];
        var paid = isNaN(parseInt(json_obj['paid_fee']))?0:parseInt(json_obj['paid_fee']);
        //For Sem Form Fee
        var payment_status = json_obj['payment_status'];
        var form_end_date = json_obj['form_end_date'];
        var course_fee = json_obj['course_fee'];
        //alert(endDate);
        
        $('#fee_due').text('Due: INR '+ duers);
        $('#fee_paid').text('Paid: INR '+ paid);
        if (parseFloat(duers) != 0) {
             $('#end_date').text(endDate);
        }else{
            $('#end_date').text('Your fee has been paid.');
        }
        //End Sem Form Fee
        if (parseFloat(payment_status) == 1) {
            //alert('sm');
             $('#course_fee_end_date').text('Your End Sem fee has been paid.');
             $('#course_fee_paid').text('Paid');
            
        }else{
             //alert('kk');
            $('#course_fee_end_date').text(form_end_date);
            $('#course_fee_paid').text('INR '+ course_fee + ' end sem fee pending. ');
           
        }
        
       
       var due =  isNaN(parseInt(json_obj['due_fee']))?0:parseInt(json_obj['due_fee']);
       var total = isNaN(parseInt(json_obj['total']))?0:parseInt(json_obj['total']);
       var paidpercent = (parseInt(due)/(parseInt(due) + parseInt(total)) )*100;
      // alert(paidpercent);
        var config = {
            type: 'doughnut',
            data: {
                datasets: [{
                        data: [
                            json_obj['paid_fee'],
                            json_obj['due_fee']
                        ],
                        backgroundColor: [
                            '#226B4A',
                            '#ff2a70',
                        ],
                        label: 'Dataset 1'
                    }],
                labels: [
                    'Paid Fee',
                    'Due Fee',
                ]
            },
            options: {
                responsive: true,
                legend: {
                    position: 'bottom',
                },
                title: {
                    display: true,
                    text: ''
                },
                animation: {
                    animateScale: true,
                    animateRotate: true
                },
                 elements: {
      center: {
      text: isNaN(parseInt(paidpercent))?0+'%':parseInt(paidpercent)+'%',
      color: '#ff2a70', //Default black
      fontStyle: 'Helvetica', //Default Arial
      sidePadding: 15 //Default 20 (as a percentage)
    }
  }
            }
        };
        var ctx = document.getElementById('chart-area').getContext('2d');
      
        window.myDoughnut = new Chart(ctx, config);

    }
</script>

<script>
    $(document).ready(function () {
        $('[data-toggle="popover"]').popover();
    });
</script>


<script>
    function monthlyAttendance(months, year) {
        if ($('#academic_year_id').val()) {
            academic_id = $('#academic_year_id').val();
            term_id = $('#term_id').val();
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-attendance'; ?>',
                data: {
                    batch_id: academic_id,
                    term_id: term_id,
                    month: months,
                    year: year
                }
            }).done(function (data) {
                json_obj = JSON.parse(data);
                mydonutChartAttendance(json_obj);
            });
        }
    }
</script>

<script>

    function mydonutChartAttendance(json_obj) {

        // Load the Visualization API and the controls package.
        google.charts.load('current', {'packages': ['corechart', 'controls']});

        // Set a callback to run when the Google Visualization API is loaded.
        google.charts.setOnLoadCallback(drawDashboard);

        // Callback that creates and populates a data table,
        // instantiates a dashboard, a range slider and a pie chart,
        // passes in the data and draws it.
        function drawDashboard() {
            // Create our data table.
            var data = google.visualization.arrayToDataTable([
                ['Name', 'Attendance'],
                ['Present', json_obj.total_present],
                ['Absent', json_obj.total_absent],
                ['Leave', json_obj.total_leaves]
            ]);

            // Create a dashboard.
            var dashboard = new google.visualization.Dashboard(
                    document.getElementById('dashboard_div'));

            // Create a range slider, passing some options
            var donutRangeSlider = new google.visualization.ControlWrapper({
                'controlType': 'NumberRangeFilter',
                'containerId': 'filter_div',
                'options': {
                    'filterColumnLabel': 'Attendance'
                }
            });

            // Create a pie chart, passing some options
            var pieChart = new google.visualization.ChartWrapper({
                'chartType': 'PieChart',
                'containerId': 'chart_div',
                'options': {
                    'width': 300,
                    'height': 300,
                    'pieSliceText': 'value',
                    'legend': 'right'
                }
            });

            // Establish dependencies, declaring that 'filter' drives 'pieChart',
            // so that the pie chart will only display entries that are let through
            // given the chosen slider range.
            dashboard.bind(donutRangeSlider, pieChart);

            // Draw the dashboard.
            dashboard.draw(data);
        }

    }
</script>



<script type="text/javascript">

</script>


<!-- BirthDay ----->
<script>

    function DatebirthDay(month) {

        if ($('#academic_year_id').val()) {
            academic_id = $('#academic_year_id').val();
            term_id = $('#term_id').val();
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-birth-day'; ?>',
                data: {batch_id: academic_id,
                    term_id: term_id,
                    date: month}
            }).done(function (data) {
                json_obj = JSON.parse(data);
                //   alert(JSON.stringify(json_obj));
                $('#data1').empty();
                for (x in json_obj) {
                    $('#data1').append('<div><img src="/dmi-erp/academic/public/images/cake.png" class="media-object" style="width:60px"></div><div><span><h4 class="media-heading" >' + json_obj[x].stu_fname + '</h4></span></div><div><span><h4 class="media-heading" >' + json_obj[x].stu_dob + '</h4></span></div>')

                }

            });

        }


    }
</script>




<script type="text/javascript">
    google.charts.load("current", {packages: ["calendar"]});

    if ($('#academic_year_id').val()) {
        academic_id = $('#academic_year_id').val();
        term_id = $('#term_id').val();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-attendance-dates'; ?>',
            data: {
                batch_id: academic_id,
                term_id: term_id,

            }
        }).done(function (data) {
            json_obj = JSON.parse(data);
            drawChart(json_obj);
        });
    }
       
    
    $('#academic_year_id,#term_id,#section').change(function () {
        if ($('#academic_year_id').val()) {
            academic_id = $('#academic_year_id').val();
            term_id = $('#term_id').val();
            section = $('#section').val();
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-attendance-dates'; ?>',
                data: {
                    batch_id: academic_id,
                    term_id: term_id,
                    section: section
                }
            }).done(function (data) {
                json_obj = JSON.parse(data);
                drawChart(json_obj);
                getSessions();
            });
         
        }

    });


    function drawChart(json_obj) {

        var present = [];
        var absent = [];
        var i = 0;
        for (x in json_obj['present']) {
            datestr = json_obj['present'][x].date;
            resultArr = datestr.split("-");
            present[x] = [new Date(parseInt(resultArr[2]), parseInt(resultArr[1]) - 1, parseInt(resultArr[0])), 2];
        }

        for (x in json_obj['Absent']) {
            datestr = json_obj['Absent'][x].date;
            resultArr = datestr.split("-");
            absent[x] = [new Date(parseInt(resultArr[2]), parseInt(resultArr[1]) - 1, parseInt(resultArr[0])), -2];
        }

        var dataTable = new google.visualization.DataTable();
        dataTable.addColumn({type: 'date', id: 'Date'});
        dataTable.addColumn({type: 'number', id: 'Won/Loss'});
        dataTable.addRows(present);
        dataTable.addRows(absent);

        var chart = new google.visualization.Calendar(document.getElementById('calendar_basic'));

        var options = {
            title: "Attendance",
        };
        chart.draw(dataTable, options);
    }
</script>


<script>
    function getSessions() {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'student-portal/ajax-get-batch-scedule-sessions1'; ?>',
            data: {term_id: $('#term_id').val(), batch_id: $('#academic_year_id').val(), top_id: 3,section:$('#section').val()}
        }).done(function (data){
            var json_obj = JSON.parse(data);
            $('.loder_img').css("display", "none");
            drawChart1(json_obj);
        });
    }

</script>





<script type="text/javascript">
    var i = 0;
    google.charts.load("current", {packages: ['corechart']});
    google.charts.setOnLoadCallback(drawChart1);
    function drawChart1(json_obj) {
        $('#top').val('3');



        var course_details = [];

        var second_arr = [["Element", "Density", {role: "style"}]];
        var course_count = [];


        for (x in json_obj)
        {
            var seq = getRandomColor();
            if (json_obj[x].course_code) {
                var one_arr = [];
                one_arr.push(json_obj[x].course_code);
                if (json_obj[x].course_count != null) {
                    one_arr.push(json_obj[x].course_count);
                    one_arr.push(seq);
                }
                second_arr.push(one_arr);

            }
        }
        var data = google.visualization.arrayToDataTable(second_arr);
        var view = new google.visualization.DataView(data);
        view.setColumns([0, 1,
            {calc: "stringify",
                sourceColumn: 1,
                type: "string",
                role: "annotation"},
            2]);

        var options = {
            title: "",
            width: "500",
            bar: {groupWidth: "100%"},
            legend: {position: "none"},
        };
        var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));

        chart.draw(view, options);


        $('#columnchart_values > div >div > span').removeAttr('style');
        $('#columnchart_values > div >div > span').empty();
        $('#columnchart_values > div >div > span').html("<div class='text-center'><p style='font-size:14px; '><b>No Record Found</p></h4></div>");

    }//=======[TRIGGER ON CHANGE ON THE BASIS OF TERM_ID]=====//
    $('#term_id').change(function () {

    });
//=======[TRIGGER ON CHANGE ON THE BASIS OF BATCH_ID]=====//
    $('#academic_year_id').change(function () {
        $('#columnchart_values > div >div > span').removeAttr('style');
        $('#columnchart_values > div >div > span').empty();

        $('#chart_div > div >div > span').removeAttr('style');
        $('#chart_div > div >div > span').empty();

        $('#chart_div1 > div >div > span').removeAttr('style');
        $('#chart_div1 > div >div > span').empty();

        $('.loder_img').css("display", "initial");
        $('.loder_img3').css("display", "initial");
        $('.loder_img4').css("display", "initial");
        setCourseRatings();
        setInstructorRatings();
        getAll();
        getSessions();
    });

//======[GET RANDOM COLOR]=======// 
    function getRandomColor() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }

</script>


















