<style>

</style>
<div class="right_col">
  
    <?php if($this->type == "getStudents") { ?>

        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Entrance Exam [I-Card ] </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">



                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Students  Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                           

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;" >S. No.</th>
                                        <th style="text-align:center;" >Applicant Name</th>
                                        <th style="text-align:center;" >Session</th>
                                        <th style="text-align:center;" >Form Id</th>
                                        <th style="text-align:center;" >Roll No.</th>
                                        <th style="text-align:center;">Father Name</th>
                                        <th style="text-align:center;">Aadhar Number</th>
                                        <th style="text-align:center;">Blood Group</th>
                                        <th style="text-align:center;">Nationality</th>
                                        <th style="text-align:center;">	Email Id  </th>
                                        <th style="text-align:center;">	Father Contact No  </th>
                                        <th style="text-align:center">Course</th>
                                        <th style="text-align:center">Permanent Address</th>
                                        <th style="text-align:center">Local Address</th>

                                    </tr>
                                   
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                         
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {

                                           //print_r($results);die;

                                            ?>

                                            <tr>

                                                <td>
                                                    <?php
                                                        echo $i;
                                                        $i++;
                                                    ?>
                                                </td>
                                                <td><?php echo $results['applicant_name'];?></td>
                                                 <td><?php echo $deptType->getRecord($results['course'])['session']; ?></td>
                                                    <?php  $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                                <td><?php echo $results['form_id'];?></td>
                                                <td><?=$results['class_roll']; ?></td>
                                                <td><?=$results['father_name']; ?></td>
                                                <td><?=$results['aadhar']; ?></td>
                                                <td><?=$results['blood_group']; ?></td>
                                                <td><?=$results['nationality']; ?></td>
                                                <td><?=$results['email_id']; ?></td>
                                                <td><?=$results['father_contact']; ?></td>
                                                
                                                 <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                
                                                  

                                              <td >
                                                   <b>Village:</b> <?= $results['l_address'] ?>,<b>Post-Office:</b><?= $results['l_postOffice'] ?>,<b>Police St.</b>:<?= $results['l_policeSt'] ?>,<b>District:</b><?= $results['l_district'] ?>,<b>State</b>:<?= $results['l_state'] ?>,<b>Pin Code:</b><?= $results['l_code'] ?>
                                              </td> 
                                              
                                              <td >
                                                   <b>Village:</b> <?= $results['l_address'] ?>,<b>Post-Office:</b><?= $results['l_postOffice'] ?>,<b>Police St.</b>:<?= $results['l_policeSt'] ?>,<b>District:</b><?= $results['l_district'] ?>,<b>State</b>:<?= $results['l_state'] ?>,<b>Pin Code:</b><?= $results['l_code'] ?>
                                              </td>
                                              
                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
        
 
</div>
<?php  } else if($this->type == "download-icard") { ?>
        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Entrance Exam [I-Card] </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">



                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">I-Card Section</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                           

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;" >S. No.</th>
                                        <th style="text-align:center;" >Applicant Name</th>
                                        <th style="text-align:center;" >Form Id</th>
                                        <th style="text-align:center;" > </th>

                                    </tr>
                                   
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {

                                           //print_r($results);die;

                                            ?>

                                            <tr>

                                                <td>
                                                    <?php
                                                        echo $i;
                                                        $i++;
                                                    ?>
                                                </td>
                                                <td><?php echo $results['applicant_name'];?></td>
                                      
                                                <td><?php echo $results['form_id'];?></td>
                                                <td>
					
					<a class="btn btn-primary pdf"  target="_blank" href="<?php echo $this->mainconfig['host'];?>entrance-report/icardprint/a_id/<?php echo $results['application_no']; ?>">PDF </a>
                                        </td>
                                             
                                            </tr>            
 
                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>
                            <div class="row">
							    <div class="col-md-offset-3 col-md-3 text-right"><button class="downloadAll btn btn-primary" type ="button" >download <i class="fa fa-download"></i></button></div>
							    <div class=" col-md-3 text-left"><button class="cancel btn btn-primary" type ="button" >Stop <i class="fa fa-close"></i></button></div>
							</div>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
        
 
</div>
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Entrance Exam [I-Card]</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
               
                <div class="x_title">
                    <b> <u> Under Graduate Department Wise Report</u></b>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>
                                    <th>Admission Taken</th>  
                                    <th>On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                           
                                            
                                           <td style="width:25em;">
                                                <a href="<?php echo $this->mainconfig['host']; ?>entrance-report/icard-details/type/getStudents/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-info">View Applicants</button></a>
                                                <a href="<?php echo $this->mainconfig['host']; ?>entrance-report/icard-details/type/download-icard/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-primary">Download I-Cards</button></a>
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
                <div class="x_panel">
               
                <div class="x_title">
                    <b> <u>Post Graduate Department Wise Report</u></b>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>  
                                    <th>Admission Taken</th>  
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                            </td>
                                           
                                           
                                            <td style="width:25em;">
                                               
                                               
                                          <a class="btn btn-info"  href="<?php echo $this->mainconfig['host']; ?>entrance-report/icard-details/type/getStudents/dept_id/<?php echo $results['course']; ?>" target="_blank">View Applicants </a>  
                                          
                                           <a href="<?php echo $this->mainconfig['host']; ?>entrance-report/icard-details/type/download-icard/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-primary">Download I-Cards</button></a>
                                          
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->
<?php } ?>
</div>
<script>

</script>