<style>
.modal-dialog {
    width: 690px;
    margin: 30px auto;
}
</style>
<div class="right_col">
   

    <?php  if($this->type == "getDocumentVerifiedStudents") { ?>
    <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">
            <div class="load-box">
                    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
                </div>
            <div class="">

                <div class="row">
                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Document Verified Students(Batch-2020) </i>
                        </h3>
                    </div>
               
                </div>
                <div class="x_panel">
                    <div class="x_title">
                        <div class="clearfix">
                            <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <label class="control-label">Filter Record By Status:</label>                                                                   <?php echo $this->form->status_filter; ?>
                                <span id="dobError" style="color:red;"></span>
                            </div>
                        </div>	
                        </div>

                    </div>

                    <div class="x_content">

                        

                        <div class="padding-md clearfix table-responsive" id="verifiedStudents">

                           

                           

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                         
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {


                                            ?>

                                               

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                               

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
</div>
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Entrance Exam [Principal Interface]</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
               
                <div class="x_title">
                    <b> <u> Under Graduate Department Wise Report</u></b>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>
                                    <th>Scrutinized  Students</th>  
                                    <th>On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);die;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                           
                                            
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/verified-student/type/getDocumentVerifiedStudents/dept_id/<?php echo $results['course']; ?>"class="edit" target="_blank" title="Edit"><button type="button" class="btn btn-info">View Applicants</button></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
                <div class="x_panel">
               
                <div class="x_title">
                    <b> <u>Post Graduate Department Wise Report</u></b>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>  
                                    <th>Scrutinized Students</th>  
                                    <th class="no_print">On-Board Students</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                            </td>
                                           
                                           
                                            <td style="text-align:center">
                                               
                                               
                                          <a class="btn btn-info"  href="<?php echo $this->mainconfig['host']; ?>entrance-report/verified-student/type/getDocumentVerifiedStudents/dept_id/<?php echo $results['course']; ?> " target="_blank">View Applicants </a>  
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->
<?php } ?>
</div>
<script>

    $("option[value='2']").attr('selected','selected');
    var status_filter = $('#status_filter').val();
    let course = '<?php echo $results['course'];?>';
    //alert(course);
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-get-record-by-pstatus'; ?>',
        data: {status_filter:status_filter,course:course}
    }).done(function (data) {
        
        $('#verifiedStudents').empty('');
        $('#verifiedStudents').html(data);
         //alert(data);

    });
    
//End
$('body').on('change', '#status_filter', function () {
        
    var status_filter = $('#status_filter').val();
    let course = '<?php echo $results['course'];?>';
    //alert(course);
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-get-record-by-pstatus'; ?>',
        data: {status_filter:status_filter,course:course}
    }).done(function (data) {
        
        $('#verifiedStudents').empty('');
        $('#verifiedStudents').html(data);
         //alert(data);

    });
});
function refreshPage() {
    location.reload(true);
}
</script>