<div class="workplace">
  <?php
	if ($this->type) {
	?>
   
  <div class="row-fluid">
		
               <div class="span12 block-fluid">                 
                    <div class="head clearfix">
                     <!-- <div class="isw-cloud"></div> -->    
                        <h3>Non Tender</h3>
                    </div>
				<div class="span6" style="width:43%;">
                                          

                        <div class="row-form clearfix">
                            <div class="span6">Project Name</div>
                            <div class="span6">
									<select name="select">
											 <option value="0">Select Any Item</option>
											 <option value="1">Arjun</option>
											 <option value="0">Abdul</option>
											 <option value="1">Arnold</option>
									</select>

							</div>
                        </div>                         
                        
                        <div class="row-form clearfix">
                            <div class="span6">Non Tender Name</div>
                            <div class="span6"><input type="text" placeholder="Enter the Tender Name"/></div>
                        </div>                                   

                        <div class="row-form clearfix">
                            <div class="span6">Non Tender Number</div>
                            <div class="span6"><input type="text" placeholder="Enter the Tender Number"/> </div>
                        </div> 
						<div class="row-form clearfix">
                            <div class="span6">Description</div>
                            <div class="span6"><textarea></textarea> </div>
                        </div> 

						<div class="row-form clearfix">
                           <strong>Status</strong><br />
								
									
										<input type="checkbox" value=""/>Active
													
									
									
										<input type="checkbox" value=""/>Submitted
									
									
										<input type="checkbox" value=""/>InActive
									
								
									<div class="row-form clearfix">
										<div class="span6">Remarks</div>
										<div class="span6"><textarea>Enter the Remark</textarea></div>
									</div>
									<div class="row-form clearfix">
										<div class="span6">Date</div>
										<div class="span6"><input type="text" id="mask_ssn"/></div>
									</div>
									
						 </div>
                   
                </div>         
                <div class="span6" style="width:43%;">
						<div class="row-form clearfix">
                            <div class="span6">Tender Number</div>
                            <div class="span6"><input type="text" disabled  placeholder="-1"/>
							
							</div>
                        </div> 

                        <div class="row-form clearfix">
                            <div class="span6">Client:</div>
                            <div class="span6"><input value=""  type="text" disabled  placeholder="All" /> </div>
                        </div>
						<div class="row-form clearfix">
                            <div class="span6">Architect:</div>
                            <div class="span6"><input value=""  type="text" disabled  placeholder="All"/> </div>
                        </div>
						<div class="row-form clearfix">
                            <div class="span6">Location:</div>
                            <div class="span6"><input value=""  type="text" disabled  placeholder="All"/>  </div>
                        </div>
						

                  </div>
                                                    
                </div>
				
				<div class="block-fluid" style="padding-top:1%;">
							
							<button type="submit" class="btn btn-default" style="margin-left:45%;">Save</button>
							
				</div>
				
		</div>
					
		
		</div>
					
					
                
	<div class="dr"><span></span></div>
  
  <?php } else { ?>
  <?php if (count($this->messages))   { 

    foreach ($this->messages as $message) {?>
  <div class="alert alert-success">
    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
    <?php echo $this->escape($message); ?> </div>
  <?php } } ?>             
	
	<div class="row-fluid">
		
		<div class="span12"> 
				
			
			<div class="head clearfix">
				<div class="isw-grid"></div>
				<h1>Credit Note And Debit Note</h1>
				<ul class="buttons">
					<!-- <li><a href="#" class="isw-download"></a></li>                                                        
					<li><a href="#" class="isw-attachment"></a></li> -->
					<li>
					<!--	<a href="#" class="isw-settings"></a> -->
						<ul class="dd-list">
							<li><a href="<?php echo $this->mainconfig['host'];?>inventory/purchase/credit-debit"><span class="isw-plus"></span>Add New </a></li>
							<!-- <li><a href="#"><span class="isw-edit"></span> Edit</a></li>
							<li><a href="#"><span class="isw-delete"></span> Delete</a></li> -->
						</ul>
					</li>
				</ul>    
			</div>
			<div class="block-fluid" style="padding:1%;">
				<a  href="<?php echo $this->mainconfig['host'];?>index"><u>Home</u></a> &nbsp >> &nbsp Inventory Management  &nbsp >> &nbsp  Note And Debit Note
			</div>
			<div class="block-fluid" style="padding-top:2%;">
						<div class="row-form clearfix">
								<label class="checkbox inline span2">
                                Type  
								</label>

								<label class="checkbox inline">
                                    <input type="radio" name="radio2"/>Credit Note
								</label>
								<label class="checkbox inline">
									<input type="radio" name="radio2"/>Debit Note
								</label>
						</div>
			<div class="row-fluid" style="margin-bottom:0px;">
						 <div class="span12 ">                 
								
							<div class="span6" style="padding:2%;">
			 
									<div class="row-form clearfix">
										<div class="span5">Supplier Name</div>
										<div class="span5">
												<select name="select">
											 <option value="0">Select Any Item </option>
											 <option value="1">SMS</option>
											 <option value="0">Public School</option>
											 <option value="1">Civil Work</option>
									</select>
										</div>
									</div>
									 
									
									<div class="row-form clearfix">
										<div class="span5">From Date</div>
										<div class="span5"><input type="date">
												
										</div>
									</div>
									
									
							</div> 
							<div class="span6">
							
									
									<div class="row-form clearfix">
										<div class="span5">Bill Number</div>
										<div class="span5">
												<select name="select">
											 <option value="0">Select Any Item</option>
											 <option value="1">Acid Wash</option>
											 <option value="0">Breaking Work</option>
											 <option value="1">Civil Work</option>
									</select>
										</div>
									</div> 
									<div class="row-form clearfix">
										<div class="span5">To Date</div>
										<div class="span5"><input type="date">
												
										</div>
									</div>
									
									
									 
									<div class="row-form clearfix">
										
										<div class="span5">
												 <button class="btn link_navPopMessages" type="button">Search</button>
										
											</div> 
									</div>
				
							</div>
							
							
							
						</div>
					
			</div>
			<div class="block-fluid table-sorting clearfix">
						<table cellpadding="0" cellspacing="0" width="100%" class="table">
							<thead>
								<tr>
									<th>SNo</th>
									<th>Tender No</th>
									<th>Tender Name</th>
									
								</tr>
							</thead>
							<tbody>
								<tr>
								  <td>1</td>
									<td>3256</td>
									<td>Green Homes</td>
							</tbody>
						</table>
		</div>
				
			
		</div>                           
		
	
	<div class="dr"><span></span></div> 	
  <?php } ?>
</div>