<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->Email_form->getAction() ?>" method="post" data-validate="parsley" novalidate>
					<div class="panel-heading">									
						 <h4>Email</h4> 
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-sm-3">				
								<div class="form-group">
									<label class="control-label">Template Name<span class="asterisk">*</span></label>
									<?php echo $this->Email_form->template_name; ?>
								</div>									
							</div>
						</div>
						<?php /* <div class="row">
							<div class="col-sm-3">				
								<div class="form-group">
									<label class="control-label">Template Type<span class="asterisk">*</span></label>
									<?php echo $this->Email_form->type; ?>
								</div>									
							</div>
						</div> */ ?>
						 <div class="row">
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label"> Subject<span class="asterisk">*</span></label>
									<?php echo $this->Email_form->subject; ?>
								</div>									
							</div>
						</div> 
						<div class="row">
							<div class="col-sm-10">	
								<div class="form-group">
									<label class="control-label">Description<span class="asterisk">*</span></label>
									<?php echo $this->Email_form->description; ?>
								</div>										
							</div> 
						</div>
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->
	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->	
<div class="padding-md">
	<div class="panel panel-default table-responsive">
		<?php /* <div class="panel-heading">
			 Email
			<a class="btn btn-primary pull-right" style="margin-top: -9px;" href="<?php echo $this->mainconfig['host']; ?>master/email/type/add">Add Email </a>
		</div> */ ?>
		<div class="padding-md clearfix">
			<table class="table table-striped" id="dataTable">
				<thead>
					<tr>
						<th>S. No.</th>								
						<th>Template Name</th> 
						<th>Description</th>
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						<td><?php echo $results['template_name']; ?></td>
						<td><?php 
						$SubString = substr($results['description'],0,50);
						if(strlen($results['description']) >100){
							echo $SubString.'...';
						}else{
							echo $SubString;
						}
						 ?></td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/email/type/edit/id/<?php echo $results['email_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a><?php /* &nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/email/type/delete/id/<?php echo $results['email_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a> */ ?></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div><!-- /.padding-md -->		
<?php } ?>
<script type="text/javascript">
$(document).ready(function() {	
	$('#wysihtml5-textarea').wysihtml5();
});	
/*
$(document).ready(function() { 
	 var count = $('#count_val').val();
     $("body").on("click","#AddButton", function(e){ 
	 
        $( "#appended_row1:last" ).clone().find("input:text").val("").end().appendTo( "#fields" );			
			var count_val = count++;
			$('#count_val').val(count_val);
          return false;		  
    });

    $("body").on("click",".removeclass", function(e){
                   $(this).parent('div').remove(); 
               return false;
    });
});	

$('body').on('change', '#organization_id', function() {		
	var org_id = $(this).val();		
		$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'admission/ajax-get-students';?>',
			data: {org_id:org_id}
		}).done(function( data ) {
			$( "#student_name").html( data );
		 });
});	 */
</script>
