<?php 
//print_r( $this->academicresult);die;
?>
<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
			
			
				<thead>
					<tr>
						
						<th>S. No.</th>
						<th>Year</th>
						<th>Term Name</th>
						<th>Start Date</th>
						<th>End Date</th>
					
					</tr>
				</thead>
				<tbody>
				
				
				<tbody>
									
										<?php
											
											$i = 1;
											
										 if($this->academicresult !=0){
										 foreach($this->academicresult as $key=>$val){ ?>
										<tr>
										
											<td><?php echo $i;?></td>
											<td><?php if ($val['year_id']==1){
									echo'First Year';
								}
								else{
									echo'Second Year';
								}
								 ?></td> 
											<td><?php echo $val['term_name'];?></td>
											<td><?php echo $val['start_date'];?></td>
											<td><?php echo $val['end_date'];?></td>											
											
											
								
		                               </tr>
									   
									  
									   <?php 
									   
											$i++; }
											
											?>
									
									 <?php } else {?>

           <tr>

               <td colspan="5" align="center">No Results Found</td>

           </tr>

            <?php }?>
									
									
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->