<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->SMS_form->getAction() ?>" method="post" data-validate="parsley" novalidate>
					<div class="panel-heading">									
						 <h4>SMS</h4> 
					</div>
					<div class="panel-body">
						<div class="row">
							<div class="col-sm-3 ">				
								<div class="form-group">
									<label class="control-label">  Name <span class="asterisk">*</span></label>
									<?php echo $this->SMS_form->sms_type; ?>
								</div>									
							</div> 
							
							<div class="col-sm-3">	
								<div class="form-group">
									<label class="control-label">Description <span class="asterisk">*</span></label>
									<?php echo $this->SMS_form->description; ?>
								</div>										
							</div> 
						</div>
						<div class="panel-footer ">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div >
										<button class="btn btn-primary submit">Update</button>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div><!-- /.padding-md -->
	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->	
<div class="padding-md">
	<div class="panel panel-default table-responsive">
		<?php /* <div class="panel-heading">
			 SMS
			<a class="btn btn-primary pull-right" style="margin-top: -9px;" href="<?php echo $this->mainconfig['host']; ?>master/sms/type/add">Add SMS </a>
		</div> */ ?>
		<div class="padding-md clearfix">
			<table class="table table-striped" id="dataTable">
				<thead>
					<tr>
						<th>S. No.</th>								
						<th> Name</th> 
						<th>Description</th>
						<th>Action</th>   
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {

					?>
					<tr>
						<td><?php echo $i;

							$i++; ?>
						</td>
						<td><?php if($results['sms_type']=='1'){echo 'Admission Enquiry';}
								  if($results['sms_type']=='2'){echo 'Enquiry FollowUp';}
								  if($results['sms_type']=='3'){echo 'Admission 1';} 
								  if($results['sms_type']=='4'){echo 'Admission 2';}  	
								  if($results['sms_type']=='5'){echo 'Admission';}  
								  if($results['sms_type']=='6'){echo 'Admission';}  
								  if($results['sms_type']=='7'){echo 'Admission';}  
								  if($results['sms_type']=='8'){echo 'Seat Booking';}  	   
								  if($results['sms_type']=='9'){echo 'Seat Booking';}  
								  if($results['sms_type']=='10'){echo 'Successful Parent Referral';}  
								  if($results['sms_type']=='11'){echo 'Child Birthday Wishes';}  
								  if($results['sms_type']=='12'){echo 'Wedding Aniversary';}  
								  if($results['sms_type']=='13'){echo 'Branch Transfer -Request';} 
								  if($results['sms_type']=='14'){echo 'Branch Transfer -Approved';}	
								  if($results['sms_type']=='15'){echo 'Branch Transfer -Cancelled';}	
								  if($results['sms_type']=='16'){echo 'Admission Discontinuation';} 
								  if($results['sms_type']=='17'){echo 'Todays Attendance – Absent';}
								  if($results['sms_type']=='18'){echo 'Request Received';}
								  if($results['sms_type']=='19'){echo 'Request Execution Intimation';}  
								  if($results['sms_type']=='20'){echo 'Suggestion Received';}  
								  if($results['sms_type']=='21'){echo 'Complaint Received';}  
								  if($results['sms_type']=='22'){echo 'Complaint Closure Intimation';} 
								  if($results['sms_type']=='23'){echo 'Compliments';}  
								  if($results['sms_type']=='24'){echo 'Fee Payment Reminders Before Due Date';}  
								  if($results['sms_type']=='25'){echo 'Fee Payment Reminders After Due Date';} 
								  if($results['sms_type']=='26'){echo 'Fee Payment Acknowledgement';}  
								  if($results['sms_type']=='27'){echo 'Change of Program-Confirmation';}  
								  if($results['sms_type']=='28'){echo 'PDC Cheque Notification to parent';} 
								  if($results['sms_type']=='29'){echo 'Fee Refund'; }
								  if($results['sms_type']=='30'){echo 'Cheque Bounce';}
								   if($results['sms_type']=='31'){echo 'Parent Feedback Acknowledgement';}
								   if($results['sms_type']=='32'){echo 'Event Unattended ';}
								    if($results['sms_type']=='33'){echo 'Seat Booking Confirmation';}
									 if($results['sms_type']=='34'){echo 'Cancel Payment';}
									 if($results['sms_type']=='35'){echo 'Admission Cancellation';}
									  if($results['sms_type']=='36'){echo 'Change of Program – Request';}
									   if($results['sms_type']=='37'){echo 'Change of Program – Cancellation';}
									   if($results['sms_type']=='38'){echo 'Branch Transfer – Modified';}
									    if($results['sms_type']=='39'){echo 'Student Migration – Intimation & New Fee Details';}
										 if($results['sms_type']=='40'){echo 'Charitable Donation';}
									    if($results['sms_type']=='41'){echo 'School Transportation Request – Parent login';}
										 if($results['sms_type']=='42'){echo 'School transportation Confirmation & Fee details';}
										  if($results['sms_type']=='43'){echo 'Absent -> Present';}
										    if($results['sms_type']=='44'){echo 'Present -> Present & Left';}
											if($results['sms_type']=='45'){echo 'Admission Fee Quote';}
											if($results['sms_type']=='46'){echo 'Hardware Health Status – Repair';}
											if($results['sms_type']=='47'){echo 'Hardware Health Status – Broken Beyond Repair';}
											if($results['sms_type']=='48'){echo 'Camp Admission Enquiry';}
											if($results['sms_type']=='49'){echo 'Camp Enquiry Followup';}
											if($results['sms_type']=='50'){echo 'Camp Fee Quote';}
											if($results['sms_type']=='51'){echo 'Camp Admission';}
											if($results['sms_type']=='52'){echo 'Special Care Quote (Branch to Parent)';}
											if($results['sms_type']=='53'){echo 'Special care payment confirmation';}
											if($results['sms_type']=='54'){echo 'Special Care Request – Cancellation';}
											if($results['sms_type']=='55'){echo 'Fee Received Successfully';}
									   
									   
									   
								  ?> </td>
						<td>		  
						<?php 
						$SubString = substr($results['description'],0,50);
						if(strlen($results['description']) >100){
							echo $SubString.'...';
						}else{
							echo $SubString;
						}
						 ?>
						<?php //echo $results['description']; ?></td>
						<td><a href="<?php echo $this->mainconfig['host']; ?>master/sms/type/edit/id/<?php echo $results['sms_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a><?php /* &nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>master/sms/type/delete/id/<?php echo $results['sms_id']; ?>" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a> */ ?></td>

					</tr>            

								<?php }
								$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
								} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
</div><!-- /.padding-md -->		
<?php } ?>

<script type="text/javascript">
$(document).ready(function() {	
	$('#wysihtml5-textarea').wysihtml5();
});
function  getTextCount(vals){
	var id = $("#description").val();
		//var str = id;
		var stringLength = id.length;
		if(stringLength > 159){
			alert('Please Enter Below 160 Charectors Only');
		}
}		
	 
/*
$(document).ready(function() { 
	 var count = $('#count_val').val();
     $("body").on("click","#AddButton", function(e){ 
	 
        $( "#appended_row1:last" ).clone().find("input:text").val("").end().appendTo( "#fields" );			
			var count_val = count++;
			$('#count_val').val(count_val);
          return false;		  
    });

    $("body").on("click",".removeclass", function(e){
                   $(this).parent('div').remove(); 
               return false;
    });
});	

$('body').on('change', '#description', function() {		
	var org_id = $(this).val();		
		$.ajax({
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'admission/ajax-get-students';?>',
			data: {org_id:org_id}
		}).done(function( data ) {
			$( "#student_name").html( data );
		 });
});	 */
</script>
