<div style="width:800px; height:auto;margin:0px auto;">
<div style="float:left; width:100%;  border-bottom:1px solid #e2e2e2;">
  <div style="float:left; width:100%;">
    <div style="width:65%; float:left;"> <img src="<?php echo $this->mainconfig['publicpath'];?>images/img.jpg"/> </div>
    <div style="width:32%; text-align:right; font-size:12px; font-family:arial;float:left;padding-top: 45px;">
     <?php //echo @(PAN_NO) ?> <br />
      <br />
      <?php //echo @(CST_TIN) ?> 
    </div>
   </div>
  <div style="float:left; width:100%;">
    <p><?php echo @(CLIENT_ADD) ?> <br />
      <?php //echo @(CLIENT_ADDTWO) ?>
    </p>
  </div>
</div>
</div>


