<style type="text/css">
    #gs_content{
        height: 200px;
    }
</style>    

<div class="right_col">
    <?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> <?php echo $this->sub_title_name; ?></i></div>
		</h3>
			<div class="panel panel-default">
                            <div class="col-sm-0" style="float:right;">
                                   <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host']; ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id; ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
                                            
					<div class="row" >
						<div class="col-sm-4 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->batch_id; ?>
                            </div>
							</div>
							<?php /* <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->year; ?>
                            </div>
							</div>	 */ ?>
						<div class="col-sm-4 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch Name<span class="asterisk">*</span></label>
                              <span class="form-control" id="batch_name"></span>
                            </div>
						</div>
                                            <div class="col-sm-4 employee_class">
                            <div class="form-group">
                              <label class="control-label">Year<span class="asterisk">*</span></label>
                                <?php echo $this->form->year_id; ?>
                            </div>
						</div>
						<div class="col-sm-4 employee_class">
                            <div class="form-group">
                              <label class="control-label">Experiential Learning Component<span class="asterisk">*</span></label>
                                <?php echo $this->form->el_component_id; ?>
                            </div>
						</div>	
                                            <div class="col-sm-4 employee_class">
                            <div class="form-group">
                              <label class="control-label">Sector<span class="asterisk">*</span></label>
                                <?php echo $this->form->sector; ?>
                            </div>
						</div>
                                            <div class="col-sm-4 employee_class">
                            <div class="form-group">
                              <label class="control-label">Location<span class="asterisk">*</span></label>
                                <?php echo $this->form->project_location; ?>
                            </div>
						</div>
                                            <div class="col-sm-4 employee_class">
                            <div class="form-group">
                              <label class="control-label">Hosting Organization<span class="asterisk">*</span></label>
                                <?php echo $this->form->hosting_org; ?>
                            </div>
						</div>
                                            <div class="col-sm-12 employee_class">
                            <div class="form-group">
                              <label class="control-label">Project Name<span class="asterisk">*</span></label>
                                <?php echo $this->form->project_name; ?>
                              <small>Max. 300 characters are allowed</small>
                            </div>
						</div>
                                            
											
					</div>
					
					
					<div class="" id="grade_data">
					</div>
				
				
 			</div>
			
			<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
                                                                                    <button id="btnAdd" class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { 
                                                                            ?>
                                                                            
                                                                    
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
                                                                    
                                                                  
                                                                    
                                                                    
                                                                    
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>experiential/experiential-learning-project">Back</a>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars"> <?php echo $this->sub_title_name; ?></i>

                    </h3>
                </div>
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>experiential/experiential-learning-project/type/add">Add </a>
		</div>
            </div>

            <div class="x_panel">

                <div class="x_title">
                    <h2><?php echo $this->sub_title_name; ?></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="padding-md clearfix table-responsive">
                        
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
                                <thead>
                                    <tr>
                                        <th>Sr. No.</th>
                                        <th>Batch Name</th>
                                        <th>Year</th>
                                        <th>Component Name</th>
                                        <th>Sector</th>
                                        <th>Location</th>
                                        <th>Hosting Organization</th>
                                        <th>Project Name</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $cnt = 0;
                                    foreach($this->result as $row){
                                        $cnt++;
                                        ?>
                                    <tr>
                                        <td><?php echo $cnt; ?></td>
                                        <td><?php echo $row['short_code']; ?></td>
                                        <td><?php echo $this->year_id[$row['year_id']] ?></td>
                                        <td><?php echo $row['elc_name']; ?></td>
                                        <td><?php echo $row['sector']; ?></td>
                                        <td><?php echo $row['project_location']; ?></td>
                                        <td><?php echo $row['hosting_org']; ?></td>
                                        <td><?php 
                                              
                                              echo htmlspecialchars($row['project_name']); 
                                              
                                        
                                              ?></td>
                                        <td><a href="<?php echo $this->mainconfig['host']; ?>experiential/experiential-learning-project/type/edit/id/<?php echo $row['el_project_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a><!-- | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>experiential/experiential-learning-project/type/delete/id/<?php echo $row['el_project_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a>--></td>
                                    </tr>
                                    <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div>
<?php
}
?>
</div>
<script type="text/javascript">
    function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}
$("#gs_system_name").on('keydown', function(evt) { 
    var char = evt.keyCode;    
    if ((char >= 65 && char <=90) || (char >= 96 && char <=105) || char == 189 || char == 8 || char == 16 ) {
           
        return true;
    }
        return false;
});
$('body').on('change', '#year_id', function() {	
    var batch_id=$('#batch_id').val();
    var year_id=$('#year_id').val();
            $.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'experiential/ajax-get-el-components';?>',
			data: {batch_id:batch_id,year_id: year_id}
		}).done(function( data ) {
			
				$('#el_component_id').html(data);
			
	  });
});
var academic_id=$('#batch_id').val();
   if(academic_id){
   
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch_name').text(result['short_code']);
			}
	  });
	 }
 $('body').on('change', '#batch_id', function() {		
var academic_id=$('#batch_id').val();
   if(academic_id){
   
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch_name').text(result['short_code']);
			}
	  });
	 }
	 
 });
 $('#datatable-responsive').DataTable();
</script>
