<style>
    .link:link,
    .link:visited{
        position: relative;
        display: inline-block;
        padding:.2em 2em;
        border-radius:100px;
        /*  background-color:#faa2b1;*/
        -webkit-transition: all .2s;
        transition: all .2s;
    }


    .link::after{
        content: "";
        position:absolute;
        top:0px;
        left:0px;
        background-color:#faa2b1; 
        width:100%;
        height:100%;
        z-index:-1;
        border-radius:100px;
        -webkit-transition: all .2s;
        transition: all .2s;
    }



    .link:hover{
        box-shadow:0px 5px 6px #000;
    }

    .link:hover::after{
        transform:scale(2,3);

    }

    .link:active{
        box-shadow:0px 5px 1px #000;
    }

    dt{
        display:none;
    }
</style>

<div class="right_col">
    <?php if ($this->type) { ?>
        <div class="padding-md">
            <div class="row">
                <div class="col-md-12 " >
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Hon's Course</i></div>
                    </h3>
                    <div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

                            <div class="panel-body">
                                <div class="row">


                                </div>


                                <div class="panel panel-default">


                                    <div class="panel-body">

                                        <div class="row">
                                            <div class="col-sm-3"><h4><span style="color:#777;">Add</span></h4></div>
                                        </div>
                                        <div class="row masterbox">
                                            <div class="row">
                                                <div class="col-sm-3 employee_class">
                                                    <div class="form-group">
                                                        <label class="control-label">Degree<span class="asterisk">*</span></label>
                                                        <?php echo $this->form->degree_id; ?>
                                                    </div>
                                                </div>
                                                <div class="col-sm-3 employee_class">
                                                    <div class="form-group">
                                                        <label class="control-label">Department Type<span class="asterisk">*</span></label>
                                                        <?php echo $this->form->department_type; ?>
                                                    </div>
                                                </div>
                                                <div class="col-sm-3 employee_class">
                                                    <div class="form-group">
                                                        <label class="control-label">Hon's Course<span class="asterisk">*</span></label>
                                                        <?php echo $this->form->department; ?>
                                                    </div>
                                                </div>
                                              
                                           
                                                <div class="col-sm-3">
                                                    <div class="form-group">
                                                        <label class="control-label">Status<span class="asterisk"></span></label>
                                                        <?php echo $this->form->status; ?> 
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                                <div>
                                    <div class="panel-footer">									
                                        <div class="row">
                                            <div class="col-sm-7 col-sm-offset-5">
                                                <?php if ($this->type == 'add') { ?> 
                                                    <div style="float:left;margin-right:2px;">
                                                        <button class="btn btn-primary submit"><span class='glyphicon glyphicon-plus-sign'></span>&nbsp;Add </button>
                                                    </div>
                                                    <div style="float:left;padding:0px 10px;">
                                                        <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                                    </div>
                                                <?php } else { ?>
                                                    <div style="float:left;">
                                                        <button class="btn btn-primary submit">Update</button>
                                                    </div>
                                                    <div style="float:left;">
                                                        <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>plan/department/">Back</a>
                                                    </div>
                                                <?php } ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </form>
                    </div><!-- /panel -->
                </div><!-- /.col-->				
            </div><!-- /.row -->

        </div><!-- /.padding-md -->	
    <?php } else { ?>

        <?php
        if (count($this->messages)) {
            foreach ($this->messages as $message) {
                ?>
                <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                    <?php echo $this->escape($message); ?>
                </div>
                <?php
            }
        }
        ?>
        <!-- widget grid -->
        <div class="">
            <div class="">
                <div class="row">

                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars">Hon's Course</i>

                        </h3>
                    </div>

                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                        <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>plan/department/type/add">Add </a>
                    </div>
                </div>

                <div class="x_panel">

                    <div class="x_title">
                        <h2>Hon's Course</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            </li>
                            <li><a class=""><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="padding-md clearfix">
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
                                <thead>
                                    <tr>
                                        <th style="text-align:center;">S. No.</th>	
                                        <th style="text-align:center;">Hon's Course</th>
                                        <th style="text-align:center;">Department Type</th>
                                        <th style="text-align:center">Degree</th>
                                        <th style="text-align:center">status</th>
                                        <th class="no_print" style="text-align:center">Actions</th>
                                    </tr>
                                </thead>
                                <tbody style="text-align:center;">
                                    <?php
                                    $i = 1;
                                    $pagination_tr = '';
                                    if (count($this->paginator) != 0) {

                                        foreach ($this->paginator as $results) {
                                            ?>
                                            <tr>
                                                <td><?php
                                                    echo $i;
                                                    $i++;
                                                    ?>
                                                </td>						
                                             <!--   <td><?php// echo date('d-m-Y', strtotime($results['created_date'])); ?></td>-->
                                                <td><?php echo $results['department']; ?></td>
                                                <td><?php echo $results['department_type']; ?></td>
                                                   <td><?=$results['degree_id'];  ?></td>
                                                <?php if ($results['status'] == 0) { ?>
                                                    <td>Active</td>
                                                <?php } else { ?>
                                                    <td class='text-danger'>Inactive</td>
                                                <?php } ?>
     <td><a href="<?php echo $this->mainconfig['host']; ?>plan/department/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit">View / Edit</a>&nbsp;</td> 
                                            </tr>            
                                            <?php
                                        }
                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                    }
                                    ?>
                                </tbody>
                            </table>
                            <?php echo $pagination_tr; ?>
                        </div><!-- /.padding-md -->
                    </div><!-- /panel -->
                </div>
            </div>
        </div><!-- /.padding-md -->		
    <?php } ?>
</div>
<script>

    $('#dataTable').DataTable();

</script> 
<script>


    $(document).ready(function () {

        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'plan/ajax-get-all-batch'; ?>',
            data: {}
        }).done(function (data) {

            $('#batch_id').empty('');
            
            $('#batch_id').html(data);


<?php if (isset($_SESSION['update'])) { ?>
                var batch_id = <?php echo $_SESSION['update']['batch_id']; ?>;

                for (x in batch_id) {

                    $('#batch_id  option[value="' + batch_id[x].academic_year_id + '"]').attr('selected', true);
                }

                // $('#course_b_id option').prop('selected', true);
                $('#batch_id option:nth-child(1)').prop('selected', false);
<?php } ?>

        });

    });



    function onStudentSelect() {
        var op_list = $('#batch_id').find("option:selected");
        var str = "";
        $(op_list).each(function () {
            str += $(this).text() + "<br/>";
        });
        $('#batch_id').next('div').html(str);
    }
    $(document).ready(function () {
        onStudentSelect();
    });
     $('#batch_id').select2();

</script>


