<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                                 <caption> <b> <u> Under Graduate Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>
                                    <th>Admission Taken</th>  
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                           
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/index/type/edit/id/<?php echo $results['course']; ?>/s_id/<?php echo $results['session_id'] ?>"class="edit" title="Edit" target="_blank" ><span class="fa fa-edit fa-lg"></span></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
                <div class="x_panel">
               
              

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <caption> <b> <u>Post Graduate Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>  
                                    <th>Admission Taken</th>  
                                    <!---<th class="no_print">Action</th>--->
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>