<table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Department</th>  
                                    <th>Cut-Off-List </th>   
                                    <th>Declared By</th>   
                                    <th> Date</th>
                                    <th class="no_print">View List</th>
                                    <!---<th class="no_print">Delete Action</th>---->
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                      $emplyeeData = new Application_Model_HRMModel();
                                      
                                      $data= $emplyeeData->getEmployeeData($results['published_by']);
                                      //echo '<pre>'; print_r($data);exit;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['department_type']; ?></td>
                                            <td>
                                                <?php 
                                                switch ($results['cutoff_list']) {
                                                    case "1":
                                                      echo "1st List";
                                                      break;
                                                    case "2":
                                                      echo "2nd List";
                                                      break;
                                                    case "3":
                                                      echo "3rd List";
                                                      break;
                                                    case "4":
                                                      echo "4th List";
                                                      break;
                                                    case "5":
                                                      echo "5th List";
                                                      break;
                                                    default:
                                                      echo "n/a";
                                                }
                                                ?>
                                            </td>
                                            
                                          
                                             <td><?php echo $data['empl_firstname']; ?></td>
                                            
                                            <td style="text-align:center">
                                                <?php
                                                  $start_date = date_create($results['submit_date']);
                                                  $result['effective_date'] = date_format($start_date,"d/m/Y"); 
                                                    echo $result['effective_date'];
                                                ?>
                                            </td>
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/edit-declared-result/e_id/<?php echo $results['id']; ?>" class="edit" title="View" target="_blank"><span class="fa fa-edit fa-lg"></span></td>
                                            
                                           <!----- <td style="text-align:center">
                                                    <input type="hidden" value="<?= $results['id']; ?>" id="delete_id">
                                                   <button type="button" id="dailogBtn" class="btn btn-primary dailogBtn" value="0" >Delete</button>
                                                
                                            </td>---->
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="6">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>