
<div class="x_title">
    <b>Document List</b>
    <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li class="dropdown">
            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
        </li>
        <li><a class="close" data-dismiss="modal"><i class="fa fa-close"></i></a>
        </li>
    </ul>
       
    <div class="clearfix">
        <label id="alert_msg" style="color:green;  position: absolute;"></label>   
    </div>
    
</div>
<?php //echo '<pre>'; print_r($this->paginator); ?>
<table class="table left-column table-striped table-bordered mb30 jambo_table bulk_action documentTable" id="" style="height:100%">
        <thead>
            <tr>
                <th rowspan="2">S.No.</th>
                <th rowspan="2">Applicant Name</th>
                <th rowspan="2">Form Id</th>  
               
                    <?php if($this->paginator['degree_id'] != 1){  ?>
                      
                    <th>1st Year Mark's Sheet  </th>   
                    <th>2nd Year Mark's Sheet  </th>   
                    <th>3rd Year Mark's Sheet  </th>   
                    <th>SLC Cert.  </th>
                    <th> Char Cert.  </th>   
                    <th>Migration Cert. </th>   
                    <th> Caste Cert.  </th>
                    <th> EWS Cert.  </th>
                    <th> Baptism Cert.  </th>  
                    <th> Undertaking Cert.  </th>  
                    <?php }else { ?>
                    <th> Mark's Sheet  </th>   
                    <th>SLC Cert.  </th>
                    <th> Char Cert.  </th>   
                    <th>Migration Cert. </th>   
                    <th> Caste Cert.  </th>
                    <th> EWS Cert.  </th>
                    <th> Baptism Cert.  </th>  
                    <th> Undertaking Cert.  </th> 
                    <?php } ?>
                </tr>
        </thead>
        <tbody>
            <?php
                //echo '<pre>'; print_r($this->paginator);
           

                    ?>
                    <tr>
                       
                        <td>
                            1.<input type="hidden" value="<?php echo $this->paginator['course']; ?>" id="course_id">
                        </td>						

                        <td><input type="hidden" value="<?php echo $this->paginator['application_no']; ?>" id="app_id"><?php echo $this->paginator['applicant_name']; ?></td>
                        <td id="form_id"><?php echo $this->paginator['form_id']; ?></td>
                        <?php if($this->paginator['degree_id'] != 1){  ?>
                        <td style="text-align: center"><input type="checkbox" name="f_year" value="f_doc" <?php if( in_array("f_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="s_year" value="s_doc" <?php if( in_array("s_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="t_year" value="t_doc" <?php if( in_array("t_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="slc_cert" value="slc_doc" <?php if( in_array("slc_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="char_cert" value="char_doc" <?php if( in_array("char_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="mig_cert" value="mig_doc" <?php if( in_array("mig_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                       
                        <td style="text-align: center"><input type="checkbox" name="caste_cert" value="caste_doc" <?php if( in_array("caste_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                         <td style="text-align: center"><input type="checkbox" name="ews_cert" value="ews_doc" <?php if( in_array("ews_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="bapt_cert" value="bapt_doc"<?php if( in_array("bapt_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                         <td style="text-align: center"><input type="checkbox" name="under_cert" value="under_cert"<?php if( in_array("under_cert", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <?php }else{ ?>
                            
                        <td style="text-align: center"><input type="checkbox" name="inter_cert" value="inter_doc" <?php if( in_array("inter_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        
                        <td style="text-align: center"><input type="checkbox" name="slc_cert" value="slc_doc" <?php if( in_array("slc_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="char_cert" value="char_doc" <?php if( in_array("char_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="mig_cert" value="mig_doc" <?php if( in_array("mig_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                       
                        <td style="text-align: center"><input type="checkbox" name="caste_cert" value="caste_doc" <?php if( in_array("caste_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                         <td style="text-align: center"><input type="checkbox" name="ews_cert" value="ews_doc" <?php if( in_array("ews_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="bapt_cert" value="bapt_doc"<?php if( in_array("bapt_doc", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <td style="text-align: center"><input type="checkbox" name="under_cert" value="under_cert"<?php if( in_array("under_cert", explode(',',$this->paginator['certificate_list']))){
                             echo "checked";} ?> > </td>
                        <?php } ?>
                        

                    </tr>            
                    
                <?php
                ?>
                <tfoot>  
               
                </tfoot>
                        <?php
                
            ?>

        </tbody>
    </table>
<script>
    $(function () {
        let result = [];
        $('.geTable tr').each(function(){
            $('#geTaken', this).each(function(index, val){
                //alert('k');
                if(!result[index]) result[index] = 0;
              result[index] += parseInt($(val).text());
            });
            //alert(result);
        });
        //setDatatables();
        $('#totalGeSum').text(result);
    });
</script>