<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
    <caption> <b> <u> Addon Course Wise Report</u></b></caption>
    <thead>
        <tr>
<th>S.No.</th>
<th>Academic Year </th>
<th>Session </th>
<th>Semester </th>
<th>Value Added Course </th>
<th>Course Code </th>
<th>Capacity </th>
<th>Countable </th>  
<th class="no_print">Edit</th>
        </tr>
    </thead>
    <tbody>
        <?php
        $i = 1;
        $pagination_tr = '';
        if (count($this->paginator) != 0) {
            foreach ($this->paginator as $results) {
                // echo '<pre>'; print_r($results); exit;
                ?>
                <tr>
                    <td><?php
                        echo $i;

                        $i++;
                        ?>
                    </td>


                    <td><?php echo $results['academic_year']; ?></td>
<td><?php echo $results['session']; ?></td>
<td><?php echo $results['semester']; ?></td>
<td><?php echo $results['course_name']; ?></td>
<td><?php echo $results['course_code']; ?></td>
<td><?php echo $results['capacity'];?></td>
<td><?php  if($results['countable']=='0'){ echo "Yes"; } else { echo "No" ; } ?></td>
 <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/addon-course-report/type/edit/id/<?php echo $results['itemid']; ?>/acad/<?php echo $results['academic_year']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-info">Edit</button></a></td>

                       </tr>            

                <?php
            }
            $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
        } else {
            ?>
            <tr>
                <td colspan="5">
                    <h2 style="color:red">
                        No Records Available.
                    </h2>
                </td>
            </tr>
<?php } ?>

    </tbody>
</table>
<?php echo $pagination_tr; ?>