<table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Date</th>
                                    <th> Department</th>
                                    <th>Total Admission Taken </th>    
                                    
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                       
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>		
                                          
                                            <td><?php echo $this->effective_date; ?></td>
                                            <td><?php echo $results['department_type']; ?></td>
                                           
                                            <td><?php echo $results['total_count']; ?></td>
                                          
                                           
                                            
                                         
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="6">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>