<style>

</style>
<div class="right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    
<?php  if($this->type == "download-icard") { ?>
        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Entrance Exam [Application Form] </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">



                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Form Preview</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                           

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;" >S. No.</th>
                                        <th style="text-align:center;" >Applicant Name</th>
                                        <th style="text-align:center;" >Form Id</th>
                                        <th style="text-align:center;" >Application No. </th>
                                        <th style="text-align:center;" > </th>

                                    </tr>
                                   
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) { ?>

                                            <tr>

                                                <td>
                                                    <?php
                                                        echo $i;
                                                        $i++;
                                                    ?>
                                                </td>
                                                <td><?php echo $results['applicant_name'];?></td>
                                      
                                                <td><?php echo $results['form_id'];?></td>
                                                <td><?php echo $results['application_no'];?></td>
                                                <td>
					
					<a class="btn btn-primary pdf"  target="_blank" href="<?php echo $this->mainconfig['host'];?>entrance-report/appformprint/a_id/<?php echo $results['application_no']; ?>">clik to print </a>
                                        </td>
                                             
                                            </tr>            
 
                                            <?php

                                        }
                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>
                            <div class="row">
							    <div class="col-md-offset-3 col-md-3 text-right"><button class="downloadAll btn btn-primary" type ="button" >download <i class="fa fa-download"></i></button></div>
							    <div class=" col-md-3 text-left"><button class="cancel btn btn-primary" type ="button" >Stop <i class="fa fa-close"></i></button></div>
							</div>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
        
 
</div>
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Entrance Exam [Application Form]</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
               
                <div class="x_title">
                    <div class="col-sm-3 employee_class">
                    <div class="form-group disabled" >
                        <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                        <?php echo $this->form->academic_year_list; ?>
                    </div>
                    </div>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    
                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="ajaxData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <caption>  <b> <u> Under Graduate Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>
                                    <th>Admission Taken</th>  
                                    <th>On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                           
                                            
                                           <td style="width:25em;">
                                                <a href="<?php echo $this->mainconfig['host']; ?>entrance-report/application-form/type/download-icard/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-primary">Download Form</button></a>
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                      
                <div class="x_panel">
               
               

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" style="height:100%">
                            <caption>  <b> <u>Post Graduate Department Wise Report</u></b> </caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>  
                                    <th>Admission Taken</th>  
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                            </td>
                                           
                                           
                                            <td style="width:25em;">
                                               
                                               
                                          
                                           <a href="<?php echo $this->mainconfig['host']; ?>entrance-report/application-form/type/download-icard/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-primary">Download Form</button></a>
                                          
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->
<?php } ?>
</div>
<script>
//Added By Kedar : 08 Oct 2020
$('body').on('change', '#academic_year_list', function() {
    let year_id= $('#academic_year_list').val();
    
    if(year_id){
        $('.load-box').css('display','block');
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'entrance-report/ajax-get-icard-applicant-detail-by-year-id';?>',
                data: {year_id:year_id}
            }).done(function( data ) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
        });
    }
});
//End : 08 Oct 2020
</script>