<style>
    .dailogBtn{
        background-color: lightcoral;
    }
    
    .ui-dialog-titlebar { display: none; }
    .ui-dialog{
        width: 400px !important;
    }
    ui-widget-content {
    border: 2px solid #c31616;
    }  
</style>
<div class="right_col">
<div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
<?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                <strong>  <?php echo $this->escape($message); ?></strong>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    
            <div class="row">
                
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Declared Result List</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>		
                
            </div>

            <div class="x_panel">
                 <div class="col-sm-3 employee_class">
                        <div class="form-group disabled" >
                            <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                            <?php echo $this->form->academic_year_list; ?>
                        </div>
                    </div>   
                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="ajaxData"> 
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" >
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Department</th>  
                                    <th>Cut-Off-List </th>   
                                    <th>Declared By</th>   
                                    <th> Date</th>
                                    <th class="no_print">View List</th>
                                    <!---<th class="no_print">Delete Action</th>---->
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                      $emplyeeData = new Application_Model_HRMModel();
                                      
                                      $data= $emplyeeData->getEmployeeData($results['published_by']);
                                      //echo '<pre>'; print_r($data);exit;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['department_type']; ?></td>
                                            <td>
                                                <?php 
                                                switch ($results['cutoff_list']) {
                                                    case "1":
                                                      echo "1st List";
                                                      break;
                                                    case "2":
                                                      echo "2nd List";
                                                      break;
                                                    case "3":
                                                      echo "3rd List";
                                                      break;
                                                    case "4":
                                                      echo "4th List";
                                                      break;
                                                    case "5":
                                                      echo "5th List";
                                                      break;
                                                    default:
                                                      echo "n/a";
                                                }
                                                ?>
                                            </td>
                                            
                                          
                                             <td><?php echo $data['empl_firstname']; ?></td>
                                            
                                            <td style="text-align:center">
                                                <?php
                                                  $start_date = date_create($results['submit_date']);
                                                  $result['effective_date'] = date_format($start_date,"d/m/Y"); 
                                                    echo $result['effective_date'];
                                                ?>
                                            </td>
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/edit-declared-result/e_id/<?php echo $results['id']; ?>" class="edit" title="View" target="_blank"><span class="fa fa-edit fa-lg"></span></td>
                                            
                                           
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="6">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
   
</div>
<script>
//Added By Kedar:07 Oct 2020

$('body').on('change', '#academic_year_list', function() {
    let year_id= $('#academic_year_list').val();
    
    if(year_id){
        $('.load-box').css('display','block');
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'entrance-report/ajax-get-declare-list-by-year-id';?>',
                data: {year_id:year_id}
            }).done(function( data ) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
        });
    }
});
</script>

