
<div class="right_col">
    <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
    <?php if($this->type == "getStudents") { ?>

        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Entrance Exam [Declined Students]-<?=date('Y')?> </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">



                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Students  Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                            <form action="" method="post" class="form-class">

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>
                                       <?php //echo '<pre>'; print_r($this->course_id);die; ?>
                                        <th style="text-align:center;" rowspan="2">S. No.</th>
                                        <th style="text-align:center;" rowspan="2">Applicant Name</th>
                                        <th style="text-align:center;" rowspan="2">Application No.</th>
                                        <th style="text-align:center;" rowspan="2">Applicant Contact</th>
                                        <th style="text-align:center;" rowspan="2">Form Id</th>
                                       
                                        <th style="text-align:center;" rowspan="2">	Email Id  </th>
                                        <th style="text-align:center" rowspan="2">Course</th>

                                        <th style="text-align:center" colspan="3">First Preference</th>
                                       <th style="text-align:center" rowspan="2"> Records Status</th>
                                       <th style="text-align:center" rowspan="2">Delete Records</th>
                                       


                                    </tr>
                                    <tr>
                                        <th>Core Course</th>
                                        <th>Generic</th>
                                        <th>Aecc</th>
                                    
                                    </tr>
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                         $edudetails = new Application_Model_ApplicantEducationalDetailModel();
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {
                                                $isexist = "not exist";
                                        
                                                  if($results['photo']!=''){
                                                   $filename = realpath(APPLICATION_PATH . '/../') . '/' . $results['photo']; 
                                                  }
                                                    if($results['educertificate']!=''){
                                                   $filename1 = realpath(APPLICATION_PATH . '/../') . '/' . $results['educertificate']; 
                                                    }
                                                    if($results['casteCertificate']!=''){
                                                  $filename2 = realpath(APPLICATION_PATH . '/../') . '/' . $results['casteCertificate']; 
                                                    }
                                                  if($results['baptism']!=''){
                                                  $filename3 = realpath(APPLICATION_PATH . '/../') . '/' . $results['baptism']; 
                                                  }
                                                  if (file_exists($filename) or file_exists($filename1) or file_exists($filename2) or file_exists($filename3)) {
                                                         $isexist = "File exists";
                                                  } else {
                                                      
                //                                       $updateData = array(
                //       'photo'=>"deleted",
                //       'casteCertificate'=>"deleted",
                //       'educertificate' => "deleted"
                //       );
                //   $edudetails->update($updateData, array('application_no=?' => $results['application_no']));
                                                  continue;} ?> 

                                          

                                            <tr>

                                                <td>
                                                    <?php
                                                        echo $i;
                                                       
                                                    ?>
                                                </td>
                                                <td><?php echo $results['applicant_name'];?></td>
                                                <td><?php echo $results['application_no'];?>
                                                    <input type="hidden" name="rhide" id="rhide_<?php echo $results['application_no'];?>" value="<?php echo $results['application_no'];?>">
                                                <input type="hidden" name="patha" id="patha_<?php echo $results['application_no'];?>" value="<?php echo $results['application_no'];?>"></td>
                                                    <?php  $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                                <td><?php echo $results['phone'];?></td>
                                                <td><?php echo $results['form_id'];?></td>
                                                 <td><?=$results['email_id']; ?></td>
                                               
                                                

                                                 <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                 <td><?php if($edu_details['core_course1']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course1'])['dpt_name'];}else{echo '--';}?></td>
                                                       
                                                <td><?php if($edu_details['ge1']){echo $geinfo->getRecord($edu_details['ge1'])['general_elective_name'];}else echo '--'; ?></td>
                                                 <td><?= !empty($edu_details['aecc1'])?$edu_details['aecc1']:'--'?></td>
                                                 
                                                 <td style="color:red">
                                                    <?= $isexist;?>
                                                 </td>
                                                 <td>
                                                    <!-- <?php if($results['photo']) {?>
                                                     <a download="<?php echo $results['application_no'];?>.jpg" href="<?php echo $this->mainconfig['host'].$results['photo']?>" class="btn btn-info">Download Photo</a>
                                                     <?php } if($results['educertificate']) {?>
                                                     <a  download="<?php echo $results['application_no'].'_edu';?>.pdf" href="<?php echo $this->mainconfig['host'].$results['educertificate']?>" target="_blank" class="btn btn-info">Download Certificate</a>
                                                      <?php } if($results['casteCertificate']) { ?>
                                                     <a  download="<?php echo $results['application_no'].'_caste';?>.pdf" href="<?php echo $this->mainconfig['host'].$results['casteCertificate']?>" target="_blank" class="btn btn-info">Download Caste</a>
                                                      <?php } if($results['baptism']){?>
                                                     <a  download="<?php echo $results['application_no'].'_batsim';?>.pdf" href="<?php echo $this->mainconfig['host'].$results['baptism']?>" target="_blank" class="btn btn-info">Download Baptism</a>
                                                    <?php  } ?> <button name="download" type="button" id="download" onclick="window.open('<?php echo $this->mainconfig['host'].$results['educertificate']?>')">Download</button>-->
                                                     <!--<button name="delete" type="button" id="dltbtn<?php echo $results['application_no'];?>" class="btn btn-danger">Delete Record</button>-->
                                                    <input type="checkbox" name="chkdlt[]" value="<?php echo $results['application_no']?>" id="chkdlt" checked="cheked">
                                                 </td>
                                             

                                              
                                             
                                             
                                     </tr>  
    
  <script>       
let r_hide<?=$i?>= $('#rhide'+'_<?php echo $results['application_no'];?>').val();
let path<?=$i?>= $('#patha'+'_<?php echo $results['application_no'];?>').val();
$('#dltbtn'+path<?=$i?>).click(function(){
//alert(path<?=$i?>);
  $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'entrance-report/ajax-get-rejected-data-by-registration-id';?>',
                data: {r_hide:r_hide<?=$i?>,path:path<?=$i?>}
            }).done(function( data ) {
                alert(data);
        });


});
</script>
                                            <?php
 $i++;
                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>
                                <div style="text-align: center;">
                                    <input type="submit" name="delete" id="dtlbtn" value="Delete" class="btn btn-danger">
                                </div>
                            </form>
    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
        
 
</div>                  
<?php } else { ?>

   <?php 
    //echo '<pre>';print_r($this->messages);exit;
   if (count($this->messages)) {
     
        foreach ($this->messages as $message) {
            
            ?>
            <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars"> Entrance Exam [Declined Students]-<?=date('Y')?> </i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  
                ?>
            </div>

            <div class="x_panel">
<!--                <div class="col-sm-3 employee_class">
                    <div class="form-group disabled" >
                        <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                        <?php //echo $this->form->academic_year_list; ?>
                    </div>
                </div>-->
                <div class="x_title">
                    
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content" id="">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="ajaxData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
                            <caption><b> <u> Under Graduate Department Wise Report</u></b></caption>     
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Rejected Students</th>   
                                    <th>On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $deptType = new Application_Model_DepartmentType();
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                     // echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                           <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                        
                                           <td><?php echo $results['COUNT(newdb.application_no)'];?></td>
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/rejected-applicant-details/type/getStudents/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-info">View Applicants</button></a></td>
                                        </tr>
                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                        
               
               
                <div class="x_title">
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                   
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
                            <caption><b> <u> Post Graduate Department Wise Report</u></b></caption>        
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Rejected Students</th>   
                                    <th>On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                        
                                           <td><?php echo $results['COUNT(newdb.application_no)'];?></td>
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/rejected-applicant-details/type/getStudents/dept_id/<?php echo $results['course']; ?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-info">View Applicants</button></a></td>
                                       
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->
<?php } ?>
</div>
<script>
   
 //Added By Kedar:08 Oct 2020

$('body').on('change', '#academic_year_list', function() {
    let year_id= $('#academic_year_list').val();
    
    if(year_id){
        $('.load-box').css('display','block');
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'entrance-report/ajax-get-applied-applicants-by-year-id';?>',
                data: {year_id:year_id}
            }).done(function( data ) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
        });
    }
});
$(document).on('click','#dtlbtn',function() { 
 $('.load-box').css('display','block');
 });

</script>