<?php 
//print_r( $this->academicresult);die;
?>
<div class="row">

<div class="padding-md clearfix">
 
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
			
			
				<thead>
					<tr>
						
						<th>S.   No.</th>
						<th>Participants Name</th>
						<?php foreach($this->Term_data as $courses){ ?>
						<th><?php echo $courses['course_name'];?></th>
						<?php } ?>
					</tr>
				</thead>
				<tbody>
				
				
				<tbody>
									
										<?php
											
											$i = 1;
										
										?>
										<?php foreach($this->Category_data as $key=>$val){ ?>
										<tr>
										<td><?php echo $i;

									$i++; ?>
								</td>
											
											<td><?php echo $val['students'];?></td> 
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>	
											
								
		                               </tr>
									   
									  
									   <?php 
									 	 }
											
											?>
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
                <script>
                    $('#print').click(function(){
                         window.print();   
                    });
             </script>