     <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th style="text-align:center;">As. ID</th>	
						<th style="text-align:center;">Participant ID</th>
						<th style="text-align:center;">Name</th>
						<th style="text-align:center;">Download</th>
                        <th style="text-align:center;">Uploaded Date</th>
					</tr>
				</thead>
				<tbody >
					        
                    <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->result) != 0) {
                                    foreach ($this->result as $results) {
                                        //echo '<pre>';print_r($results);exit;
                                        ?>
                                        <tr>
                                            
                                         
                                    
                                            <td><?php echo $i; $i++; ?>
                                            </td>	
                                           <td><?=$results['student_id']; ?>
                                            </td>
                                            <td><?=$results['stu_name']; ?>
                                            </td>
                                            <?php if($results['filename1']) {?>
                                            <td><a href='<?=$this->baseUrl($results['upload_file']);?>' class='link' download><?=$results['filename1'];?></a></td>
                                            <?php }else{?>
                                            <td>--</td>
                                            <?php }?>
                                             <td><?=$results['stu_updated_date']; ?>
                                            </td>
                                            
                                        </tr>   
                                        
                                        
    <?php
    }
}else{ ?>
    <tr>
        <td colspan="4">No Records</td>
    </tr>
<?php }
?>



				</tbody>
			</table>


 