<style type="text/css">
    #gs_content{
        height: 200px;
    }
</style>    
<link href="<?php echo $this->mainconfig['publicpath']; ?>css/custom.css" rel="stylesheet">
<div class="right_col">
    <?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Datatables Settings</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
                                            
					<div class="row" >
						<div class="col-sm-4 employee_class">
                            <div class="form-group">
                              <label class="control-label">url<span class="asterisk">*</span></label>
                                <?php echo $this->form->url; ?>
                            </div>
							</div>
						</div>
						
											
					</div>
					
					
					<div class="" id="grade_data">
                                           
                                            <div class="col-sm-12 employee_class">
                                                 <table class="table table-striped table-bordered mb30 jambo_table bulk_action ">
                                                     <thead>
                                                         <tr>
                                                             <th>Fields</th>
                                                             <th>Values</th>
                                                         </tr>
                                                         
                                                     </thead>
                                                     <tbody>
                                                          <?php 
                                                    $dtsettings = new Application_Model_DtMaster();
                                                    $result = $dtsettings->getRecords();
                                                    foreach($result as $key => $value){
                                            
                                            ?>
                                                         <tr><td><?=$value['fields'];?></td>
                                                         <td>
                                                            <?php  if($value['type'] == 'checkbox') {?>
                                                             <label for="<?=$value['id'];?>" class="checkbox" value="<?=$value['fields'];?>"></label>
                                                    <?php } ?>
                                                             <input type="<?=$value['type'];?>" class="form-control" size ="3" id="<?=$value['id'];?>" name="<?=$value['fields'];?>"   /></td>
                                                         </tr>
                                                    <?php } ?>
                                                     </tbody>
                                                 </table>
                                                </div>
                                            
                                            
                                                    
                                            
					</div>
				
				
 			</div>
			
			<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
                                                                                   <button type="submit" class="btn btn-primary">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { 
                                                                            ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>global-settins/datatable">Back</a>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars"> Global Settings</i>

                    </h3>
                </div>
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>global-settings/datatable/type/add">Add </a>
		</div>
            </div>

            <div class="x_panel">

                <div class="x_title">
                    <h2>Global Settings</h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="padding-md clearfix">
                        <form action="POST">
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>System Name</th>
                                        <th>Category</th>
                                        <th>Value</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    foreach($this->result as $row){
                                        ?>
                                    <tr>
                                        <td><?php echo $row['gs_display_name']; ?></td>
                                        <td><?php echo $row['gs_system_name']; ?></td>
                                        <td><?php echo $this->gs_category[$row['gs_category']]; ?></td>
                                        <td><?php 
                                              $gs_content = substr($row['gs_content'], 0, 100);
                                              echo htmlspecialchars($gs_content); 
                                        
                                              ?></td>
                                        <td><a href="<?php echo $this->mainconfig['host']; ?>global-settings/index/type/edit/id/<?php echo $row['global_setting_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>
                                    </tr>
                                    <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </form>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div>
<?php
}
?>
</div>
<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script> 
<script type="text/javascript">


$('select').change(function(){
    var url = $('select option:selected').text(); 
     $.ajax({
                        type: "POST",
                        url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-datatable-settings'; ?>',
                        data: {path_name: url}
                    }).done(function (data){
                        data = JSON.parse(data);
                        for(ele in data){
                         $('input[name="'+ele+'"]').val(data[ele]);
                      }
                    });


});
</script>
