<style>
    .link:link,
    .link:visited{
        position: relative;
        display: inline-block;
        padding:.2em 2em;
        border-radius:100px;
        /*  background-color:#faa2b1;*/
        -webkit-transition: all .2s;
        transition: all .2s;
    }


    .link::after{
        content: "";
        position:absolute;
        top:0px;
        left:0px;
        background-color:#faa2b1; 
        width:100%;
        height:100%;
        z-index:-1;
        border-radius:100px;
        -webkit-transition: all .2s;
        transition: all .2s;
    }



    .link:hover{
        box-shadow:0px 5px 6px #000;
    }

    .link:hover::after{
        transform:scale(2,3);

    }

    .link:active{
        box-shadow:0px 5px 1px #000;
    }

    dt{
        display:none;
    }
</style>

<div class="right_col">
    <?php if ($this->type) { ?>
        <div class="padding-md">
            <div class="row">
                <div class="col-md-12 " >
                    <?php
                    if (count($this->messages)) {
                        foreach ($this->messages as $message) {
                            ?>
                            <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                                <?php echo $this->escape($message); ?>
                            </div>
                            <?php
                        }
                    }
                    ?>
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Examination Dates </i></div>
                    </h3>
                    <div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >




                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                                            <?php echo $this->form->academic_year; ?>
                                        </div>
                                    </div>
                                    <?php echo $this->form->csrftoken; ?>      
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Session<span class="asterisk">*</span></label>
                                            <?php echo $this->form->session; ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Batch<span class="asterisk">*</span></label>
                                            <?php echo $this->form->academic_id; ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Semester<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cmn_terms; ?>
                                        </div>
                                    </div>


                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Exam Type<span class="asterisk">*</span></label>
                                            <?php echo $this->form->exam_type; ?>
                                        </div>
                                    </div>

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Month Of Examination<span class="asterisk">*</span></label>
                                            <?php echo $this->form->exam_date; ?>
                                        </div>
                                    </div>

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Result Publish Date<span class="asterisk">*</span></label>
                                            <?php echo $this->form->result_publish_date; ?>
                                        </div>
                                    </div>

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Revaluation Date<span class="asterisk">*</span></label>
                                            <?php echo $this->form->reval_date; ?>
                                        </div>
                                    </div>

<div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">End Of Examination<span class="asterisk">*</span></label>
                                            <?php echo $this->form->end_date; ?>
                                        </div>
                                    </div>

                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <label class="control-label">Status<span class="asterisk"></span></label>
                                            <?php echo $this->form->status; ?> 
                                        </div>
                                    </div>
                                </div>
                            </div>
                    </div>
                    <div>
                        <div class="panel-footer">									
                            <div class="row">
                                <div class="col-sm-7 col-sm-offset-5">
                                    <?php if ($this->type == 'add') { ?> 
                                        <div style="float:left;margin-right:2px;">
                                            <button class="btn btn-primary submit"><span class='glyphicon glyphicon-plus-sign'></span>&nbsp;Add </button>
                                        </div>
                                        <div style="float:left;padding:0px 10px;">
                                            <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                        </div>
                                    <?php } else { ?>
                                        <div style="float:left;">
                                            <button class="btn btn-primary submit">Update</button>
                                        </div>
                                        <div style="float:left;">
                                            <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>plan/exam-dates">Back</a>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    </form>
                </div><!-- /panel -->
            </div><!-- /.col-->				
        </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

    <?php
    if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                <?php echo $this->escape($message); ?>
            </div>
            <?php
        }
    }
    ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars"> Examination Dates </i>

                    </h3>
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>plan/exam-dates/type/add">Add </a>
                </div>
            </div>

            <div class="x_panel">

                <div class="x_title">
                    <div class="row">
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">Academic Year<span class="asterisk">*</span></label>-->
                            <?php echo $this->form->academic_year; ?>
                        </div>
                    </div>
                    <?php echo $this->form->csrftoken; ?>      
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label">Session<span class="asterisk">*</span></label>-->
                            <?php echo $this->form->session; ?>
                        </div>
                    </div>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label">Semester<span class="asterisk">*</span></label>-->
                            <?php echo $this->form->cmn_terms; ?>
                        </div>
                    </div>


                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">Exam Type<span class="asterisk">*</span></label>-->
                            <?php echo $this->form->exam_type; ?>
                        </div>
                    </div>
                    </div>
                    <ul class="nav navbar-right panel_toolbox">
                        <button class="btn btn-primary" id="getRecords">Get Records</button>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="ajaxData" id="ajaxData">
                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
                            <thead>
                                <tr>
                                    <th >S. No.</th>
                                    <th>Session</th>
                                    <th>Batch</th>
                                    <th>Semester</th>
                                    <th>Exam Type</th>
                                    <th >Month Of Exam </th>
                                    <th >Result Publish Date</th>
                                    <th >Revaluation Date</th>
                                    <th class="no_print" style="text-align:center">Mark-Sheet Status</th>
                                    <th class="no_print" style="text-align:center">Admit Card Status</th>
                                    <th class="no_print" style="text-align:center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                        ?>
                                        <tr>
                                            <td><?php
                                                echo $i;
                                                $i++;
                                                ?>
                                            </td>
                                            <td><?php echo $results['session']; ?></td>
                                            <td><?= !empty($results['academic_id']) ? $results['short_code'] : 'N/A' ?></td>
                                            <td><?php echo $results['term_name']; ?></td>
                                            <?php if ($results['exam_type'] == 1) { ?>
                                                <td>Collegiate</td>
                                            <?php } else { ?>
                                                <td class='text-danger'>Non-Collegiate</td>
                                            <?php } ?>
                                            <td><?php echo $results['exam_date']; ?></td>
                                            <td><?php echo $results['result_publish_date']; ?></td>
                                            <td><?php echo $results['reval_date']; ?></td>

                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>plan/exam-dates/type/lock_marksheet/id/<?php echo $results['id']; ?>/update_id/<?php echo $results['mark_sheet_status']; ?>" class="delete" title="Update"><?php
                                                    if ($results['mark_sheet_status'] == 0) {
                                                        echo '<span style="color:red" class="fa fa-lock fa-lg"></span>';
                                                    } else {
                                                        echo '<span style="color:green" class="fa fa-unlock fa-lg"></span>';
                                                    }
                                                    ?></a>
                                            </td>
                                            
                                            
                                            <td  style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>plan/exam-dates/type/lock_admitcard/id/<?php echo $results['id']; ?>/update_id/<?php echo $results['admit_card_status']; ?>" class="delete" title="Update"><?php
                                        if ($results['admit_card_status'] == 0) {
                                            echo '<span style="color:red" class="fa fa-lock fa-lg"></span>';
                                        } else {
                                            echo '<span style="color:green" class="fa fa-unlock fa-lg"></span>';
                                        }
                                                    ?></a></td>
                                            <td><a href="<?php echo $this->mainconfig['host']; ?>plan/exam-dates/type/edit/id/<?php echo $results['id']; ?>" class="edit" title="Edit">View / Edit</a>&nbsp;</td> 
                                        </tr>            
                                <?php
                            }
                            $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                        }
                        ?>
                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                        </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>
    $('.datepicker').datepicker();

    //To filter Session
    $('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    //Get Batch By Session
    $('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#academic_id').empty('');
                $('#academic_id').html(data);
                $('#academic_id').trigger("chosen:updated");
            });
        }
    });
    //End
    //For FilterData 
    $('body').on('click', '#getRecords', function () {
        var year_id = $('#academic_year').val();
        var session = $('#session').val();
        var sem = $('#cmn_terms').val();
        var type = $('#exam_type').val();
        
        if (type) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'plan/ajax-get-filter-record'; ?>',
                data: {year_id: year_id,session:session,sem:sem,type:type}
            }).done(function (data) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
              
            });
        }
    });
    //End
    
    //Dsiable Editing In Core Course Learning Date : 25 Oct 2021
    let type='<?= $this->type ?>';
    if(type == 'edit'){
        //disable the field
        
        $("#academic_year").prop( "disabled", true ); 
        $("#session").prop( "disabled", true ); 
        $("#cmn_terms").prop( "disabled", true ); 
        $("#academic_id").prop( "disabled", true ); 
        
    

        //right before the form submits, we re-enable the fields, to make them submit.
        $( "#formValidate1" ).submit(function( event ) {
        $("#academic_year").prop( "disabled", false );
        $("#session").prop( "disabled", false );
        $("#cmn_terms").prop( "disabled", false );
        $("#academic_id").prop( "disabled", false );
 
    });   
    }
//End

</script> 


