<style>
    .my.table>tbody>tr>td, .my.table>tbody>tr>th, .my.table>tfoot>tr>td, .my.table>tfoot>tr>th, .my.table>thead>tr>td, .my.table>thead>tr>th {
    padding: 0px !important;
    line-height: 1.42857143;
    vertical-align: middle !important;
    border-top: 1px solid #ddd;
}


.my.table{
    margin-bottom:0px;
}
</style>  







<div class="right_col">
  
<?php if ($this->type) {  ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">Participants Attendance</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
                                           
						<div class="row">

							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            
                            <?php if($this->type!='edit'){?>
                                <label class="control-label">Batch<span class="asterisk">*</span></label>
                            <?php echo $this->form->academic_year_id; ?>
                            <?php } ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            
                            <?php if($this->type!='edit'){?>
                                <label class="control-label">Term <span class="asterisk">*</span></label>
                            <?php echo $this->form->term_id; ?>
                            <?php } ?>
                            </div>
							</div>
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            
                            <?php if($this->type!='edit'){?>
                                <label class="control-label">Section <span class="asterisk">*</span></label>
                            <?php echo $this->form->section; ?>
                            <?php } ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                          
                            <?php if($this->type!='edit'){ ?>
                                  <label class="control-label">Course<span class="asterisk">*</span></label>
                                 
                                <?php echo $this->form->course_id; ?>
                            <?php } ?>
                            </div>
							</div> 
                                                    	<div class="col-sm-3 employee_class">
                            
							
							

							<!-- <div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">Credit<span class="asterisk">*</span></label>
                            <?php //echo $this->form->credit_id; ?>
                            </div>
							</div> -->
                                                        </div>
							</div>
							<div class="row">
                                                            <div class="col-sm-3" >                           
                                                            <div class="form-group">
                                                         
                                                         <?php if($this->type!='edit'){ ?> 
                                                                <label class="control-label">Date<span class="asterisk">*</span></label>
                                                             <?=$this->form->date;?>
                                                         <?php } ?>
                                                             </div>
                                                            </div>
							<div class="col-sm-3">
							<div class="form-group">
                                                            
                                                        <?php if($this->type!='edit'){ ?>
                                                            <label class="control-label">Batch<span class="asterisk"></span></label>
                                                            <input type="text" id="batch" class="form-control" style="background-color:#fdf59a;" readonly />    <?php } ?>

							</div>
							</div>
                                                               
							</div>
							</div>
                                         
							<div class="">
							<div id="item_details"></div>
							</div>
					
						 
						  <?php if(count($this->result) >0){
                                                      $item_result = $this->result;
                                                      $cl_no = $this->no_of_classes; 
                                                      //$cl_no = 1;
                                                      for($dcl = 1; $dcl<=$cl_no; $dcl++){
                                                      ${"course$dcl"} ='';
                                                      }
                                                    
                                                     //echo "<pre>"; print_r($item_result);exit;
                                                      
                                                    // strpos($item_result[$i]['class_1'],"Absent");
                                                   // strpos($item_result[$i]['class_1'],"Absent");
                                                      for($dcl = 1; $dcl<=$cl_no; $dcl++){
                                                      for($i=0; $i<count($item_result); $i++){
                                                          $absent = strpos($item_result[$i]["class_$dcl"],"Absent")>-1? 'Absent':$item_result[$i]["class_$dcl"];
                                                          $leave = strpos($item_result[$i]["class_$dcl"],"Leave")>-1 ? 'Leave':$item_result[$i]["class_$dcl"];
                                                      if($absent!='Absent' && $leave!='Leave'){
                                                          ${"course$dcl"} = $item_result[$i]["class_$dcl"];
                                                          break;
                                                      }   
                                                      }
                                                      }
                                                      //print_r($item_result);exit;
                                                      ?>                                       <?php $date = (explode('/',$_SERVER['REQUEST_URI']));
                                                      $date = $date[count($date)-7  ];  ?><div class='pull-left'><span style='margin-left:1.5em; padding:.5em; font-size:1.3em; '>DATE :- &nbsp; <?=$date; ?></span></div><div class="col-sm-0" style="float:right;">
                                   <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host']; ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id; ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
                                                      <table class="my table table-striped table-bordered mb30 jambo_table bulk_action" style="width:100%;" id="">
                                <thead>
                                   
                                    <tr>
                                        <th style="text-align:center;">So No.</th>
                                        <th style="text-align:center">Student Name</th>
                                         <?php for($dcl = 1; $dcl<=$cl_no; $dcl++){ ?>
                                
                                        <th style="text-align:center;"> <table class="my table table-striped table-bordered mb30 jambo_table bulk_action" ><thead><tr><th style="text-align:center" colspan='3'><ul class='list-unstyled list-inline'><li><?=$this->classrecords[$cl_no - $dcl];?></li><li><?=$item_result[0]["faculty_$dcl"];?></li></ul></th></tr>
                                                <tr>
                                                    <td style="text-align:center">Present</td>
                                                    <td style="text-align:center">Absent</td>
                                                    <td style="text-align:center">Leave</td>
                                                </tr>
                                                <tr>
                                                   <th colspan='3' class="text-center"><?php if(${"course$dcl"}!='0'){?>
                                                            <?=${"course$dcl"}; ?>
                                                    <?php }else{ ?>
                                                        <?='--';?>
                                                        <?php }?>
                                                    </th>
                                                </tr>
                                                </thead>
                                            </table></th>
                                         <?php } ?>
                                       </tr>
                                   
                                </thead>
                                <tbody>
                                    <?php $j=0; ?>

                                     <?php for($i=0;$i<count($item_result); $i++){ ?>
                                    
                                    
                                    <?php 
                                    
                                     for($dcl = 1; $dcl<=$cl_no; $dcl++){ 
                                                 ${'class_'.$dcl.'_P'}=${'class_'.$dcl.'_A'}=${'class_'.$dcl.'_L'}='';
                                                  
                                                  //background variable 
                                                  ${'class_'.$dcl.'_P_b'}=${'class_'.$dcl.'_A_b'}=${'class_'.$dcl.'_L_b'}='';
                                                  
                                                     ${"absent$dcl"} = strpos($item_result[$i]["class_$dcl"],"Absent")>-1? 'Absent':$item_result[$i]["class_$dcl"];
                                                     ${"leave$dcl"} = strpos($item_result[$i]["class_$dcl"],"Leave")>-1 ? 'Leave':$item_result[$i]["class_$dcl"];  
                                                     
                                                     if(${"absent$dcl"}=='Absent'){ 
                                                        ${"class_".$dcl."_A"} = 'A'; 
                                                            ${"class_".$dcl."_A_b"} = 'danger';
                                                        
                                                      } else if(${"leave$dcl"}=='Leave'){
                                                         ${"class_".$dcl."_L"} = 'L'; 
                                                      ${"class_".$dcl."_L_b"} = 'info';
                                                       
                                                      } else if($item_result[$i]["class_$dcl"]!='0') {
                                                     ${"class_".$dcl."_P"} = 'P'; 
                                                    ${"class_".$dcl."_P_b"} = 'success';
                                                    
                                             }
                                           }
                                        ?>
                                        <tr>
                                            <td><?=++$j;?></td>
                                            <td><?=$item_result[$i]['student_name'];?></td>
                                            <?php for($dcl = 1; $dcl<=$cl_no; $dcl++){ ?>
                                            <td>
                                                <table class="my table table-striped table-bordered mb30 jambo_table bulk_action" >
                                                 
                                                    <tbody>
                                                        <tr>
                                                        <td style="text-align:center; width:32%; height:19px;"  class="<?=${"class_".$dcl."_P_b"};?>"><?=${"class_".$dcl."_P"};?></td>
                                                        <td style="text-align:center;  width:32%; height:19px;" class="<?=${"class_".$dcl."_A_b"};?>"> <?=${"class_".$dcl."_A"};?></td>
                                                        <td style="text-align:center;  width:32%; height:19px;" class="<?=${"class_".$dcl."_L_b"};?>"><?=${"class_".$dcl."_L"};?></td>
                                                        </tr>
                                                    </tbody>
                                                </table>
                                            </td>
                                            <?php } ?>
                                            
                                        </tr>
                                     <?php } ?>
                                </tbody>
                                </table>
                                
                                                      
                                                  <?php } ?>
			</div>
					<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit" id="btn" >Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<!--<button class="btn btn-primary submit">Update</button>-->
										</div>
										<div style="float:left;">
										<!--<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>evaluation-components/index">Back</a>-->
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
</div>	
<!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Participants Attendance</i>
				
		</h3>
	</div>
		
                                           
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>attendance/index/type/add">Add/ Edit </a>
		</div>
                   
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Participants Attendance</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
                    

			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
				<thead>
					<tr>
						<th>S.  No.</th>	
						<th>Batch Name</th>
						<th>Date</th>
						<th>Term Name</th>
						<th>Section</th> 
						<th>Action</th>
						<!--<th>View</th>-->
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						//print_r($results);die;

                                                    ?><td><?=$i++?></td>
                                <td><?=$results['short_code'];?></td>
                                <td><?=$results['date']?></td>
                                <td><?=$results['term_name'];?></td>
                                <td><?=$results['name'];?></td>
							

                                                                <td><a href="<?php echo $this->mainconfig['host']; ?>attendance/index/type/edit/id/<?php echo $results['date']; ?>/term/<?=$results['term_id']; ?>/batch/<?=$results['batch_id'];?>/section/<?=$results['section'];?>" class="edit" title="Edit">View</a><!--<?php //if(in_array($this->role_id,$this->administrator_role)){?>&nbsp; | &nbsp;  <a href="<?php //echo $this->mainconfig['host']; ?>attendance/index/type/delete/id/<?php echo $results['ec_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a><?php //} ?>--></td>
								<!--<td><a class="component_view" id="<?php echo $results['ec_id'];?>"> View</a></td>-->

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>


<!--- update 30-04-2019 ---------------->
 <!--         <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
              <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 
-->
       <script src="<?php echo $this->mainconfig['publicpath']; ?>build/js/jquery-ui_date.js"></script>
       <script src="<?php echo $this->mainconfig['publicpath']; ?>vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<script>
     //Edited by satyam 
 
                var selected_date = [];
  
 </script> 



<script>
	
         
        
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}


 $("#academic_year_id").change(function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#term_id').empty('');
                $('#term_id').html(data);
            })
        } 
    });
    
    
    
    $("#term_id").change(function () {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
    // alert(academic_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'].'attendance/ajax-get-section';?>',
                data: {academic_year_id: academic_id,term_id: term_id}
            }).done(function (data) {
                //alert(data);
                $('#section').empty('');
                $('#section').html(data);
            })
         
    });
    $("#section").change(function () {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
    // alert(academic_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'].'attendance/ajax-get-course';?>',
                data: {academic_year_id: academic_id,term_id: term_id}
            }).done(function (data) {
                //alert(data);
                $('#course_id').empty('');
                $('#course_id').html(data);
            })
         
    });
    
     $("#course_id").change(function() {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
        var course_id = $("#course_id").val();
     
      // alert(academic_id);
	        var id=$(this).attr("id");
			$.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'attendance/ajax-get-date';?>",
              data: { batch_id:academic_id,term_id:term_id,course_id:course_id,section:$('#section').val()}
            }).done(function(data) {
                data = JSON.parse(data);
                selected_date = [];
                   for(date_key in data){
                       selected_date.push(data[date_key]);
                   }
                   
                  // alert(selected_date[0]);
				//$('#date').empty('');
				//$("#date").html(data);
			});
              
     });
     //--------------------------satyam 30-04-2019------------------------------------
       $("#course_id").change(function() {
        
        
        $('#date').val("");  
        $('#item_details').empty('');
       
       
       
       });
     //-------------------------------------------------------------------------------
    
    
     $("#date").change(function() {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
        var course_id = $("#course_id").val();
        var date_val = $("#date").val();
	        var id=$(this).attr("id");
			$.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'attendance/ajax-student-list-view';?>",
              data: { batch_id:academic_id,
                       term_id:term_id,course_id:course_id,date_val: date_val,section: $('#section').val()}
            }).done(function(data) {
				$('#item_details').empty('');
				$("#item_details").html(data);
                                
                                
                                 $.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'attendance/ajax-get-faculty';?>',
			data: {batch_id:$('#academic_year_id').val(), term_id:$('#term_id').val(), course_id:$('#course_id').val(),section: $('#section').val()}
		}).done(function( data ) {
                $('#faculty_1').empty(data);
                $('#faculty_2').empty(data);
                $('#faculty_3').empty(data);
                $('#faculty_4').empty(data);
                $('#faculty_5').empty(data);
                
		$('#faculty_1').html(data);
                $('#faculty_2').html(data);
                $('#faculty_3').html(data);
                $('#faculty_4').html(data);
                $('#faculty_5').html(data);
	  });
                                
                                
                                
                                
			});
     });



$('body').on('change', '#academic_year_id', function() {		
var academic_id=$('#academic_year_id').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	 
 });
 
 
var academic_id=$('#academic_year_id option:selected').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	else{
$('#batch').hide();
}
$('#course_id').change(function(){
});



$('#print').click(function(){
window.print('#grade_data');
});

//$('#date').datepicker({
//              
//	//maxDate: 10,
//        //minDate:10,
//        changeMonth: true,
//        changeYear: true
//}); 
 </script>
 
<script>
function available(date) {
    
    var days = String(date.getDate());
    var month = String(date.getMonth()+1);
    days = days.length>1?days:'0'+days ;
    month = month.length>1?month:'0'+month;
    
    dmy = days + "-" +  month  + "-" + date.getFullYear(); 
   
   
   
       if ($.inArray(dmy, selected_date) != -1) {
    return [true, "cal-highlight","Available"];
  } else {
    return [false,"","unAvailable"];
  }

}
</script>

<script>
   
    var date_obj = {
    dateFormat: 'dd-mm-yy',
    changeMonth: true,
    changeYear: true,
    maxDate: new Date(),
    beforeShowDay: available
    }  
 
     <?php if(strpos($_SESSION['admin_login']['admin_login']->empl_id,'F')){ ?>
         date_obj.minDate = -8;
     <?php }?>
$('#date').datepicker(date_obj);

</script>
