<style>
     @media print 
     {
/*                     table td:nth-child(7)
                     {
                         display:none;
                     }
                     table th:nth-child(7)
                     {
                         display:none;
                     }*/
                      *{
                        visibility:hidden;
                     }
                     table,th,td 
                     {
                         visibility:visible;                    
                     } 
                     .title1
                     {
                        visibility:visible; 
                     }
                   
     }
  </style> 
<?php $result = $this->result; ?>
<?php //echo "<pre>"; print_r($result);exit;  ?>
<style>
    .text-bold-marked{
        border:1px dashed red;
        font-weight:700;
        font-size:22px;

    }

    .table-shadow{
        -webkit-box-shadow: 4px 3px 8px #000;
        box-shadow: 2px 3px 4px #000;
        border:10px inset #aaa;
    }
    .my.table>tbody>tr>td, .my.table>tbody>tr>th, .my.table>tfoot>tr>td, .my.table>tfoot>tr>th, .my.table>thead>tr>td, .my.table>thead>tr>th {
        padding: 0px !important;
        line-height: 1.42857143;
        vertical-align: middle !important;
        border-top: 1px solid #ddd;
    }
    .my.table{
        margin-bottom:0px;
    }
</style>
<div class="right_col">
    <div class="row">
        <div class="col-md-12">
            <h3 class="page-title txt-color-blueDark" >
                <div><i class="fa fa-eye title1">Student Attendance Report</i>
                    <div id="chart_div" style='position:absolute; right:0px; top:-14px;' class='pull-right' ></div>
                </div>
            </h3>
            <div class="panel panel-default">

                <div class='panel-title'>


                </div>
                
                  <div class="panel panel-default">
                <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                    <div class="panel-body">

                        <div class="row">

							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            
                            <?php if($this->type!='edit'){?>
                                <label class="control-label">Batch<span class="asterisk">*</span></label>
                            <?php echo $this->form->academic_year_id; ?>
                            <?php } ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            
                            <?php if($this->type!='edit'){?>
                                <label class="control-label">Term <span class="asterisk">*</span></label>
                            <?php echo $this->form->term_id; ?>
                            <?php } ?>
                            </div>
							</div>
							
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                          
                            <?php if($this->type!='edit'){ ?>
                                  <label class="control-label">Course<span class="asterisk">*</span></label>
                                <?php echo $this->form->course_id; ?>
                            <?php } ?>
                            </div>
							</div> 
                                                    	<div class="col-sm-3 employee_class">
                            
							
							

							<!-- <div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">Credit<span class="asterisk">*</span></label>
                            <?php //echo $this->form->credit_id; ?>
                            </div>
							</div> -->
                                                        </div>
							</div>
							<div class="row">
							<div class="col-sm-3">
							<div class="form-group">
                                                            
                                                        <?php if($this->type!='edit'){ ?>
                                                            <label class="control-label">Batch<span class="asterisk"></span></label>
                                                            <input type="text" id="batch" class="form-control" style="background-color:#fdf59a;" readonly />    <?php } ?>

							</div>
							</div>
                                                               
							</div>
                        <div id="grade_data">
                        </div>

                    </div>
                
                <div class='panel-body'>
                    <div class="col-sm-0" style="float:right;">
                                   <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host']; ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id; ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>

                    <table  class="table table-striped table-bordered mb30 jambo_table bulk_action refresh"  id ='dataTable'style="width:100%;" >
                        <thead>
                            <tr>
                                <th style="text-align:center;">Sl. No.</th>
                                <th>Participants Name</th>
                                <th class='text-center'>Session</th>
                                <th style="text-align:center;">Total Class</th>
                                <th style="text-align:center;">Present</th>
                                <th style="text-align:center;">Absent</th>
                                <th style="text-align:center;">Leave</th>
                                
                                <th style="text-align:center">Last Updated on</th>
                            </tr>
                        </thead>
                        <tbody style="text-align:center;" id ="mainData">
                            <?php
                            $i = 1;
                            $pagination_tr = '';
                            if (count($result) != 0) {
                                foreach ($result as $results) {
                                    ?>
                                    <tr>
                                        <td><?php echo $i;
                            $i++;
                            ?> </td>						
                                        <td><?php echo $results['course_code']; ?></td>
                                        <td><?php echo $results['total_class']; ?></td>
                                        <td><?php echo ((int)$results['p']+(int)$results['A']+(int)$results['L']); ?></td>
                                        <td><?php echo $results['p']; ?></td>
                                        <td><?php echo $results['A']; ?></td>
                                        <td><?php echo $results['L']; ?></td>
                                         <td><?php if($results['updated_date'])echo $results['updated_date'];else echo "0000-00-00"; ?></td>
                                    </tr> 
    <?php
    }
}
?>   </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
        <script>	
 
	
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}


 $("#academic_year_id").change(function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-terms'; ?>',
                data: {academic_year_id: academic_id}
            }).done(function (data) {
                //alert(data);
                $('#term_id').empty('');
                $('#term_id').html(data);
            })
        } 
    });
    
    
    
    $("#term_id").change(function () {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
    // alert(academic_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'].'attendance/ajax-get-course';?>',
                data: {academic_year_id: academic_id,term_id: term_id}
            }).done(function (data) {
                //alert(data);
                $('#course_id').empty('');
                $('#course_id').html(data);
            })
         
    });
    
     $("#course_id").change(function() {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
        var course_id = $("#course_id").val();
        $('.refresh').fadeOut('slow');

        var id=$(this).attr("id");
			$.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'attendance/ajax-get-attendance-view';?>",
              data: { batch_id:academic_id,term_id:term_id,course_id:course_id}
            }).done(function(data) {
                    if(data)
                                $('#dataTable').DataTable().destroy();
				$('#mainData').empty('');
				$("#mainData").html(data);
                               $('.refresh').fadeIn('slow');
                                $('#dataTable').DataTable();
			});
              
     });
    
    
     $("#date").change(function() {
        var term_id= $('#term_id').val();
        var academic_id = $('#academic_year_id').val();
        var course_id = $("#course_id").val();
        var date_val = $("#date").val();
	        var id=$(this).attr("id");
			$.ajax({
              type: "POST",
               url:"<?php echo $this->mainconfig['host'].'attendance/ajax-student-list-view';?>",
              data: { batch_id:academic_id, term_id:term_id,course_id:course_id}
            }).done(function(data) {
				$('#mainData').empty('');
				$("#mainData").html(data); 
			});
     });



$('body').on('change', '#academic_year_id', function() {		
var academic_id=$('#academic_year_id').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	 
 });
 
 
var academic_id=$('#academic_year_id option:selected').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	else{
$('#batch').hide();
}
$('#course_id').change(function(){
});

$('#print').click(function(){
window.print('#grade_data');
});



</script>

