
<table class="table table-striped table-bordered mb30 jambo_table bulk_action coreTable">
    <thead>
    <tr>
        
        <th style="width:50%"> Generic Elective</th>
         <th style="text-align: center;"> Select your choice</th>
    <tr>
    </thead>
    <tbody>
<?php
                                $isExist = array();
                                foreach ($this->paginator as $key => $value) {
                                     if(!in_array($value['ge_id'],$isExist)){
                                    $isExist[] = $value['ge_id'];
                                    //echo '<pre>';print_R($results);
                                    ?>

   
        <tr>
    <td><label> <?php echo $value['general_elective_name']; echo " ";?></label>  </td>
   
    <td id='<?php echo $key; ?>' colspan="2"><input type="radio" value="<?= $value['ge_id'];?>" required> </td> 
        </tr>
  
                               <?php 
                                }}
                               ?>
 
    </tbody>
</table>
<script>

</script>