<div id="content" class="right_col">
<?php
if (count($this->messages)) {
	foreach ($this->messages as $message) {
		?>
		<div class="alert alert-success">
			<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
			<?php echo $this->escape($message); ?></div>
		<?php
	}
}
?>
<div class="row">

<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Trading Account</i>
		</h3>
	</div>

	<div class="col-xs-12">
		<form id="basicForm" action="<?php echo $this->mainconfig['host']; ?>finance/trading-account/index/type/search<?php //echo $this->form->getAction() ?>" method="post" class="form">		
		   <div class="panel">
				<div class="row" style="margin:0px;">
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">Start Date</label>
							<?php echo $this->TradingAccount_form->start_date; ?>
							<!-- <input class="form-control start_date" type="text" name="start_date" value="" required="required"> -->
						</div>
					</div>
					<div class="col-sm-3">
						<div class="form-group" style=" padding-right:0px;">
							<label class="control-label">End Date </label>
							<?php echo $this->TradingAccount_form->end_date; ?>
							<!--<input class="form-control end_date" type="text" name="end_date" value="" required="required">-->
						</div>
					</div>
					<div class="col-sm-2" style="float:left;width:100px;">
						<div class="form-group">
							<div style="float:left">
								<br />							
								<input type="submit" style="margin-top:5px;" class="btn btn-primary" name="submit" value="Submit" id="submit_val">
							</div>											
						</div>
					</div>
					<div class="col-sm-2" style="float:right;width:100px;">
					<div class="form-group">
							<br/>
							 <input type="submit" style="margin-top:5px;" class="btn btn-primary" name="print" value="Print" onclick="this.form.target='_blank';return true;"> 
							<br />	
						</div>											
					</div> 
				</div>
								
			</div>
		</form>
	</div>
</div>

<?php 
//if ( ( !empty($postvalue['start_date']) ) && ( !empty($postvalue['end_date']) ) ) { 
//$statement_remarks = $this->statement_remarks;
$end_dates = $this->enddate;
$findMont = date("m", strtotime($end_dates));
$findYear = date("Y", strtotime($end_dates));;

$totalday = cal_days_in_month(CAL_GREGORIAN, $findMont, $findYear); // 31
//echo $totalday ;
if(($this->type == 'search') || ($this->type == '') )
{ 
?>

<!-- widget grid -->
<!-- widget grid -->
<section id="widget-grid" class="">	
	<!-- row -->
	<div class="row">
		
		<!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
			<!--	<header>
					<span class="widget-icon"> <i class="fa fa-table"></i> </span>
					<h2></h2>

				</header>

				<!-- widget div-->
				<div>		
					<!-- widget content -->
						<div class="widget-body">
							<div class="table-responsive">	
	<div class="x_panel">
               
                    <div class="x_title">
                    
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">							
								<table style="margin-bottom:0px !important;" class="table table-bordered jambo_table bulk_action">
								<thead>
									<tr>
										<td colspan="2" style="text-align:center;">Trading Account</td>
									</tr>
									<tr>
										<td style="text-align:center;">Account</td>
										<td style="text-align:center;">Sales</td>										
									</tr>
									</thead>
									<tr>
									<td>
										<table style="margin-bottom:0px !important;" class="table table-bordered ">
											<thead>										
												
												<tr>
													<!--<th style="text-align:center;">S.No.</th> -->
													<td style="text-align:center;">Account Name</td>
													<td style="text-align:center;">Balance</td>
														
												</tr>
											</thead>
											<tbody>
												<?php //print_r($this->opening_balance); 
												$total_items = 0;
												$total_credit = 0;
												$total_debit = 0;
																						
												$i = 0;
												$days_count = 0;										
												?>
												
												<?php 
												$account_statement = $this->account_statement;
												if ( count($account_statement) > 0 ) {
													?>											  
													<?php
													$total_items = count($account_statement);
													$k = 0;
													foreach ($account_statement as $account) {
														$i++;												
														?>
														<tr>
															<td>
															<?php echo $account['name']; ?>
															</td>													
															<td style="text-align:right;width:15%;">
															<?php
																
																	//$amount = $account['payment_amount']  + $account['receipt_amount'] + $account['debit_amount'] + $account['credit_amount'] + $account['opening_balance'];

																	$debit_amount = 0;
																	$credit_amount = 0;
																	if($account['operator'] == 2){	
																		$debit_amount = ($account['payment_amount']  + $account['debit_amount']);
																		$credit_amount = $account['receipt_amount'] + $account['credit_amount'] + $account['opening_balance'];
																	}else{
																		$debit_amount = ($account['payment_amount']  + $account['debit_amount'] + $account['opening_balance']);
																		$credit_amount = $account['receipt_amount'] + $account['credit_amount'];
																	}
																	
																	$total_account_amt	= 0;
																	if( $debit_amount > $credit_amount){								
																		$total_account_amt = $debit_amount - $credit_amount;
																	}
																	
																	if( $credit_amount > $debit_amount){
																		$total_account_amt = $credit_amount - $debit_amount;
																	}
																	echo number_format(($total_account_amt),2);
																	$total_debit += ($total_account_amt);
																
																
																?>
															</td>													
														</tr>
														<?php
														// } //End
													}																							
													/*
													 * Vendor Pyments end
													 */
													?>
													<?php
													}											
													?>
												
												
													<?php 
													$purchase_statement = $this->purchase_statement;
													if ( count($purchase_statement) > 0 ) {
													?>											  
													<?php
													$total_items = count($purchase_statement);
													$k = 0;
													$debit_amount = 0;
													$amount = 0;
													foreach ($purchase_statement as $purchase) {
														
														$amount += $purchase['paid_amount'];
													}
														$i++;												
														?>
														<tr>
															<!-- <td><?php //echo $i; ?></td> -->
															<td>
															<?php echo 'PURCHASE'; ?>
															</td>													
															<td style="text-align:right;width:15%;">
															<?php
																//echo $debit_amount;
																
																	
																	echo number_format(($amount),2);
																	$total_debit += ($amount);
																
																
																?>
															</td>												
														</tr>
													<?php
													}											
													?>											
												</tbody>
											</table>
										</td>
										<td>
										<table style="margin-bottom:0px !important;" class="table table-bordered ">
											<thead>	
												<tr>													
													<td style="text-align:center;">Account Name</td>
													<td style="text-align:center;">Balance</td>
												</tr>
											</thead>
											<tbody>
											<?php 
											$waybill_statement = $this->waybill_statement;
											if ( count($waybill_statement) > 0 ) {
											?>											  
											<?php
											$total_items = count($waybill_statement);
											$k = 0;
											$debit_amount = 0;
											foreach ($waybill_statement as $waybill) {
												
												$amount = $waybill['waybill_amount'];
											}
												$i++;												
												?>
												<tr>
												<!--	<td><?php //echo $i; ?></td> -->
													<td>
													<?php echo 'DIRECT EXPORT'; ?>
													</td>													
													<td style="text-align:right;width:15%;">
													<?php
														//echo $debit_amount;
														
															
															echo number_format(($amount),2);
															$total_credit += ($amount);
														
														
														?>
													</td>												
												</tr>
											<?php
											}											
											?>
											<?php 
											$sales_statement = $this->sales_statement;
											if ( count($sales_statement) > 0 ) {
											?>											  
											<?php
											$total_items = count($sales_statement);
											foreach ($sales_statement as $sales) {
											$amount = $sales['paid_amount'];
											}															
												$i++;																						
											/*
											 * Vendor Pyments end
											 */
											?>
												<tr>
												<!--	<td><?php //echo $i; ?></td> -->
													<td>
													<?php echo 'INDIRECT EXPORT'; ?>
													</td>													
													<td style="text-align:right;width:15%;">
													<?php
					
											
															echo number_format(($amount),2);
															$total_credit += ($amount);
														
														
														?>
													</td>													
												</tr>
												
											<?php
											}											
											?>


										<?php 
											$retail_statement = $this->retail_statement;
											if ( count($retail_statement) > 0 ) {
											?>											  
											<?php
											$total_items = count($retail_statement);
											foreach ($retail_statement as $retail) {
											$amount = $retail['paid_amount'];
											}															
												$i++;																						
											/*
											 * Vendor Pyments end
											 */
											?>
												<tr>
												<!--	<td><?php //echo $i; ?></td> -->
													<td>
													<?php echo 'AUTO AND DV'; ?>
													</td>													
													<td style="text-align:right;width:15%;">
													<?php
					
											
															echo number_format(($amount),2);
															$total_credit += $amount;
														
														
														?>
													</td>													
												</tr>
												
											<?php
											}											
											?>
											<tr>
												<td>
												<strong><?php echo 'Total'; ?></strong>
												</td>													
												<td style="text-align:right;width:15%;">
												<strong> <?php echo number_format( round($total_credit), 2); ?> </strong>
												</td>													
											</tr>											
										</tbody>
									</table>
									</td>
									</tr>										
									<tr>
										<?php  $gross_profit = $total_credit * 17.05 / 100; ?>
										<td style="">Gross Profit <span style="float:right;"><?php echo number_format($gross_profit, 2); ?><span/></td>
										<td style="border-left:0px !important;">Closing Stock <span style="float:right;"><?php 
											$closing_Stock = ($total_debit + $gross_profit) - $total_credit;
											echo number_format(round($closing_Stock),2);
										?><span/></td>	
									</tr>
									<tr>
										<td><b>Total<b/><span style="float:right;text-align:right;" align="right"><?php echo number_format( round($gross_profit+$total_debit), 2); ?><span/></td>	
										<td align="right"><b><?php echo number_format( round($total_credit+$closing_Stock), 2); ?></td>
									</tr>
								</table>
								</div>
								</div>
							</div>
						</div>
					<!-- end widget content -->
				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->
		</article>
		<!-- WIDGET END -->
	</div>
	
	<!-- end row -->
</section>
<!-- end widget grid -->
<?php } ?> 
</div>
<script type="text/javascript">
	$("#start_date").datepicker({ 
		dateFormat: 'yy-mm-dd',
		prevText: '<i class="fa fa-chevron-left"></i>',
		nextText: '<i class="fa fa-chevron-right"></i>'
	});
	$("#end_date").datepicker({ 
		dateFormat: 'yy-mm-dd',
		prevText: '<i class="fa fa-chevron-left"></i>',
		nextText: '<i class="fa fa-chevron-right"></i>'
	});
</script>