<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
                                 <caption> <b> <u> Under Graduate Department Wise Report</u></b></caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th> Batch Name</th>
                                    <th>Applied Students</th>  
                                    <th>On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['department']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                           
                                            
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>entrance-report/scrutiny/type/getStudents/dept_id/<?php echo $results['academic_year_id']; ?>/acad/<?=$this->year_id;?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-info">View Applicants</button></a></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }else{?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                <div class="x_panel">
                        <div class="table-responsive" id="">
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
                            <caption><b> <u>Post Graduate Department Wise Report</u></b></caption>
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Course Name</th>
                                    <th>Sanctioned Seats</th>  
                                    <th>Applied Students</th>   
                                    <th class="no_print">On-Board Applicants</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->pgData) != 0) {
                                    foreach ($this->pgData as $results) {
                                      //echo '<pre>'; print_r($results);
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>

                                           
                                            <td><?php echo $results['department_type']; ?></td>
                                            <td><?php echo $results['max_seat']; ?></td>
                                            <td><?php echo $results['total_count'];?></td>
                                            </td>
                                           
                                           
                                            <td style="text-align:center">
                                               
                                               
                                          <a class="btn btn-info"  href="<?php echo $this->mainconfig['host']; ?>entrance-report/scrutiny/type/getStudents/dept_id/<?php echo $results['academic_year_id']; ?>/acad/<?=$this->year_id;?>" target="_blank">View Applicants </a>  
                                            </td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                               }else{?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
                                <?php } ?>

                            </tbody>
                        </table>
                               <?php echo $pagination_tr; ?>
<script>
    setDatatables();
</script>