<style>
    .modal-dialog {
        width:850px;
        margin: 30px auto;
    }
    .select2{
        width:300px !important;
    }
</style>
<div class="right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <?php
    if ($this->type == "getStudents") {

        if (count($this->messages)) {

            foreach ($this->messages as $message) {
                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

                <?php  
            }
        }
        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars"> Scrutiny Interface </i>
                        </h3>
                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">



                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">Students  Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">



                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;" rowspan="2">S. No.</th>
                                        <th style="text-align:center;" rowspan="2">Applicant Name</th>

                                        <th style="text-align:center;" rowspan="2">User ID</th>

                                        <th style="text-align:center;" rowspan="2">Enrollment Id</th>

                                        <th style="text-align:center" rowspan="2">Course</th>

                                        
                                        <th style="text-align:center"rowspan="2">Edit Form</th>
                                        <th style="text-align:center"rowspan="2">Doc. Submitted</th>


                                            <!--<th class="no_print" style="text-align:center">Edit | Delete</th>-->



                                    </tr>
                                   
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
									//echo 'hii'; die();
                                   
                                     $deptinfo = new Application_Model_Department();
									  $acadid = new Application_Model_Academic();
                                    $deptType = new Application_Model_DepartmentType();
                                    $stuportal = new Application_Model_StudentPortal();
									        $max_reg = $stuportal->getmaxRegno();
											$max_exam = $stuportal->getmaxExamno();
									
                                  //  $addoncourse = new Application_Model_AddonCourseModel();
                                  //  $addons = new Application_Model_AddonCourseAssignmentModel();
								      //$deptid= $deptinfo->getRecordbyDepartmentType($results['course'])['id'];

                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {
											
											  //$res= $stuportal->getsturecordsbyph($results['phone']);
											   //$deptinfo->getRecordbyDepartmentType($results['course']);
											 // print_r($results); die();
											  
											 
											 // if($res) {
												//  continue;
											  //}

                                          
                                            ?>

                                            <tr>

                                                <td><?php echo $i; $i++;?></td>
                                                <td><?php echo $results['applicant_name']; ?></td>
                                                <td><?= $results['user_id']; ?></td>
                                                <td><?php echo $results['form_id']; ?></td>
                                                <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                <?php if ($results['scrutiny_status'] != 1) { ?>
                                                <td><a href="<?php echo $this->mainconfig['host']; ?>multi-step-form/index/type/step4/a_id/<?php echo md5($results['application_no']); ?>/role/admin/"target="_blank" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>
                                                <?php } else { ?>
                                                <td>
												<input type="hidden" name="stu_name"   id="stu_name"   value="<?php echo $results['applicant_name']; ?>">
												<input type="hidden" name="stu_fname"   id="stu_fname"   value="<?php echo $results['father_name']; ?>">
												<input type="hidden" name="father_contact" id="father_contact" value="<?php echo $results['father_contact']; ?>">
												<input type="hidden" name="stu_email"  id="stu_email"    value="<?php echo $results['email_id']; ?>">
												<input type="hidden" name="stu_phone" id="stu_phone"     value="<?php echo $results['phone']; ?>">
												<input type="hidden" name="gender"  id="gender"       value="<?php echo $results['gender']; ?>">
												<input type="hidden" name="dob"  id="dob"          value="<?php echo $results['dob_date']; ?>">
												<input type="hidden" name="aadhar" id="aadhar"        value="<?php echo $results['aadhar_number']; ?>">
												<input type="hidden" name="caste_category" id="caste_category" value="<?php echo $results['caste_category']; ?>">
												<input type="hidden" name="religion"  id="religion"     value="<?php echo $results['religion']; ?>">
												<input type="hidden" name="nationality" id="nationality"    value="<?php echo $results['nationality']; ?>">
												<input type="hidden" name="academic_id" id="academic_id"    value="<?php echo $acadid->getRecordByDeptyear($results['acad_year_id'],$deptinfo->getRecordbyDepartmentType($results['course'])['id']); ?>">
												<input type="hidden" name="reg_no"  id="reg_no"       value="<?php echo $max_reg+1; ?>">
												<input type="hidden" name="exam_roll" id="exam_roll"     value="<?php echo $max_exam+1; ?>">
												<input type="hidden" name="roll_no"   id="roll_no"     value="<?php echo $max_exam+1; ?>">
												<input type="hidden" name="year_id"   id="year_id"     value="<?php echo $results['acad_year_id']; ?>">
												
												
                                                <a href="<?php echo $this->mainconfig['host']; ?>multi-step-form/index/type/step4/a_id/<?php echo md5($results['application_no']); ?>/role/admin/" target="_blank" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>
												<a href="#" onclick="SubmitFormData()" class="btn btn-primary" title="Edit">Pay Now</a></td>
                                                </td> 
                                                <?php } ?>
                                                <td class="view_document">
                                                <input type="hidden" value="<?= $results['application_no']; ?>" id="app_number">
                                                <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">View Docs.</button></td>
                                            </tr>            

                                            <?php
                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                    }
                                    ?>

                                </tbody>

                            </table>


                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">

                    <div class="modal-body" id="resultas">

                    </div>
                    <div class="modal-footer">

                        <button type="button" id="" data-dismiss="modal" class="btn btn-default">Cancel</button>
                        <button type="button" id="cnf_cert" class="btn btn-primary">Save/Update</button>
                    </div>
                </div>

            </div>
        </div>
        <!---End Modal--->

    </div>

    <?php } else { ?>

        <?php
        if (count($this->messages)) {
            foreach ($this->messages as $message) {  ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php
        }
    }
    ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars"> Scrutiny Interface  </i>

                    </h3>
                </div>

            </div>

            <div class="x_panel">

                <div class="x_title">
                    <div class="col-sm-3 employee_class">
                        <div class="form-group disabled" >
                            <label class="control-label">Academic Year<span class="asterisk">*</span></label>
    <?php echo $this->form->academic_year_list; ?>
                        </div>
                    </div>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>

                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="ajaxData">
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
                                <caption> <b> <u> Under Graduate Department Wise Report</u></b></caption>
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th> Course Name</th>
                                        <th> Batch Name</th>
                                        <!--<th>Sanctioned Seats</th>-->
                                        <th>Applied Students</th>  
                                        <th>On-Board Applicants</th>
                                    </tr>
                                </thead>
                                <tbody>
    <?php
    $i = 1;
    $pagination_tr = '';
    if (count($this->paginator) != 0) {
        foreach ($this->paginator as $results) {
           // echo '<pre>'; print_r($results);
			
			 $applicantCourseData = new Application_Model_ApplicantPaymentDetailModel();
			 
			 
			  
            ?>
                                            <tr>
                                                <td><?php
            echo $i;

            $i++;
            ?>
                                                </td>


                                                <td><?php echo $results['department_type']; ?></td>
                                                <td><?php echo $results['department']; ?></td>
                                                <!--<td><?php echo $results['max_seat']; ?></td>-->
                                                <td><?php echo $applicantCourseData->getallcount($results['academic_year_id']);?></td>


                                                <td style="text-align:center"><a class="report" href="<?php echo $this->mainconfig['host']; ?>entrance-report/scrutiny/type/getStudents/dept_id/<?php echo $results['academic_year_id']; ?>/acad/<?=$this->acad;?>" target="_blank" class="edit" title="Edit"><button type="button" class="btn btn-info">View Applicants</button></a></td>
                                            </tr>            

            <?php
        }
        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
    } else {
        ?>
                                        <tr>
                                            <td colspan="5">
                                                <h2 style="color:red">
                                                    No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
    <?php } ?>

                                </tbody>
                            </table>
    <?php echo $pagination_tr; ?>
                            <div class="x_panel">




                                <div class="table-responsive" id="">
                                    <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
                                        <caption><b> <u>Post Graduate Department Wise Report</u></b></caption>
                                        <thead>
                                            <tr>
                                                <th>S.No.</th>
                                                <th> Course Name</th>
												<th> Batch Name</th>
                                                <th>Applied Students</th>   
                                                <th class="no_print">On-Board Applicants</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                                    <?php
                                                    $i = 1;
                                                    $pagination_tr = '';
                                                    if (count($this->pgData) != 0) {
                                                        foreach ($this->pgData as $results) {
                                                            //echo '<pre>'; print_r($results);
                                                            ?>
                                                    <tr>
                                                        <td><?php
                                                            echo $i;

                                                            $i++;
                                                            ?>
                                                        </td>


                                                        <td><?php echo $results['department_type']; ?></td>
														<td><?php echo $results['department_type']; ?></td>
                                                        <td><?php echo $results['total_count']; ?></td>
                                                        </td>


                                                        <td style="text-align:center">


                                                            <a class="btn btn-info" class="report"  href="<?php echo $this->mainconfig['host']; ?>entrance-report/scrutiny/type/getStudents/dept_id/<?php echo $results['academic_year_id']; ?>/acad/<?=$this->acad;?>" target="_blank">View Applicants </a>  
                                                        </td>
                                                    </tr>            

                                                    <?php
                                                }
                                                $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                            } else {
                                                ?>
                                                <tr>
                                                    <td colspan="5">
                                                        <h2 style="color:red">
                                                            No Records Available.
                                                        </h2>
                                                    </td>
                                                </tr>
    <?php } ?>

                                        </tbody>
                                    </table>
    <?php echo $pagination_tr; ?>
                                </div>
                            </div><!-- /.padding-md -->
                        </div><!-- /panel -->
                    </div>
                </div>
<?php } ?>
        </div>
        <script>
           
            $(document).ready(function () {
                var addoncapacity = [];
                var applied = []
                var selectedaddon = [];
                
               var courseval = `<?=json_encode($courseDetails);?>`;
                courseval = JSON.parse(courseval);
                for(i in courseval){
                addoncapacity[courseval[i]['id']] = courseval[i]['capacity'];
                applied[courseval[i]['id']] = courseval[i]['total_applied'];
                }
                
                $('.selected_courses').select2();
                
            $(".selected_courses").on("change", function(){
                var singleid = $("option:selected", this).val();
             console.log(applied);
                if(!selectedaddon[singleid])
                selectedaddon[singleid]  = 0;
              
                
                selectedaddon[singleid] +=1; 
                var totalapplied = parseInt(applied[singleid]) +  parseInt(selectedaddon[singleid]);
                
                if(totalapplied>addoncapacity[singleid] && singleid){
                    alert("Seating Capacity Of '"+$("option:selected", this).text()+"' is already full.")
                    selectedaddon[singleid] -=1
                    $("option:selected", this).attr("selected",false)
                }
                
            var msg = $("#msg");
            var count = 0;
    
          for (var i = 0; i < this.options.length; i++)
          {
              
            var option = this.options[i];
        
            option.selected ? count++ : null;
        
            if (count > 2)
            {
                option.selected = false;
                option.disabled = true;
                  $(this).select2();
                alert("Please select only two options.");
                count--;
                
            }else{
                option.disabled = false;
                  $(this).select2();
            }
          }
                });
                
                
                
            $('input[type="checkbox"]').click(function () {
                var checkbox = $(this);
                var patt = /F-\d{4}-\d{1,}/i;

                var str = $(this).attr('id');
                var form_id = str.match(patt);
                var selectId = 'select_' + form_id;
                //alert(selectId);
                var select = $('#' + selectId + '>option');
                var course_id = [];
                console.log(select);
                if (checkbox.is(":checked")) {
                    select.each(function () {
                        if ($(this).prop("selected")) {
                            course_id.push($(this).val());


                        }
                    });
                    //alert(form_id[0]);
                    if (course_id) {
                        $.ajax({
                            type: "POST",
                            url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-insert-addons'; ?>',
                            data: {form_id: form_id[0], course_id: course_id}
                        }).done(function (data) {
                           courseval = JSON.parse(data);
                           for(i in courseval){
                addoncapacity[courseval[i]['id']] = courseval[i]['capacity'];
                applied[courseval[i]['id']] = courseval[i]['total_applied'];
                }
                        });
                    }
                }

            });
                
                
                
                

            });
        


            //Script for modal

            $(".view_document").click(function () {
                let application_no = $(this).closest("td").find("#app_number").val();
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-get-applicant-info'; ?>',
                    data: {application_no: application_no}
                }).done(function (data) {
                    //alert(data);
                    $('#resultas').html(data);
                });
                //$("#resultas").append(application_no);      
            });
            $("#cnf_cert").click(function () {
                let docArray = [];
                let form_id = $('.documentTable').find("#form_id").html();
                let app_id = $('.documentTable').find("#app_id").val();
                let course_id = $('.documentTable').find("#course_id").val();
                //alert(app_id);
                $(".documentTable td input[type=checkbox]:checked").each(function () {
                    let documents = $(this).val();
                    docArray.push(documents);
                });
                //alert(docArray);
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-upsert-documents'; ?>',
                    data: {docArray: docArray, form_id: form_id, app_id: app_id, course_id: course_id}
                }).done(function (data) {
                    //alert(data);
                    $('#alert_msg').text(data);
					setTimeout("location.reload(true);",2000)
                    //$('#msg').html(data);
                });
                //console.log(docArray);
            });

            //Added By Kedar : 08 Oct 2020
            $('body').on('change', '#academic_year_list', function () {
                let year_id = $('#academic_year_list').val();
               
                if (year_id) {
                    
                    $.ajax({
                        type: "POST",
                        url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-get-scrutiny-applicants-by-year-id'; ?>',
                        data: {year_id: year_id}
                    }).done(function (data) {
                        $('#ajaxData').empty('');
                        $('#ajaxData').html(data);
                        $('.load-box').css('display', 'none');
                    });
                }
            });
            //End : 08 Oct 2020

function SubmitFormData(){
	
	//alert('hii');
	
	 let stu_name = $('#stu_name').val();
	 let stu_fname = $('#stu_fname').val();
	 let father_contact = $('#father_contact').val();
	 let stu_email = $('#stu_email').val();
	 let stu_phone = $('#stu_phone').val();
	 let gender = $('#gender').val();
	 let dob = $('#dob').val();
	 let aadhar = $('#aadhar').val();
	 let caste_category = $('#caste_category').val();
	 let religion = $('#religion').val();
	 let nationality = $('#nationality').val();
	 let academic_id = $('#academic_id').val();
	 let reg_no = $('#reg_no').val();
	 let exam_roll = $('#exam_roll').val();
	 let roll_no = $('#roll_no').val();
	 let year_id = $('#year_id').val();
	 
	   $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-insert-erp-records'; ?>',
                     data: {stu_name: stu_name,stu_fname:stu_fname,father_contact:father_contact,stu_email:stu_email,stu_phone:stu_phone,gender:gender,dob:dob,aadhar:aadhar,caste_category:caste_category,religion:religion,nationality:nationality,academic_id:academic_id,reg_no:reg_no,exam_roll:exam_roll,roll_no:roll_no,year_id:year_id}
                    }).done(function (data) {
						
					
						var dt = JSON.parse(data);
					    window.location.href = "<?php echo $this->mainconfig['host'] ?>fee-collection/pay?stid="+dt['sid']+"&academic="+dt['academic']+"&term="+dt['term']+"&collection_id=";
                        
                    });
	
	
	
}


        </script>