<div class="row">
                                        
                                     <?php 
                                        // $i =0; 
                                     
                                    // foreach($this->course_cat as $cat_index => $cat_value ){ 
                                         //$str = '';
                                        // $paper_val = '';
                                        // $inc2 = $inc = 0;
                                           //print_r($this->course_cat);
                                               //  die();
                                         
                                         ?> 
                                        <?php  ?>
                                        <?php //foreach($this->core_details_arr as $core_index => $core_val){
                                           // if($core_val['cc_name'] == $cat_value ){
                                                //$str.= $core_val['ct_name'].',';
                                                //}
                                            //}
                                           
                                            //if($i == 0){
                                            //foreach($this->core_details_arr as $core_index => $core_val){
                                                //if($core_val['ge_id']==0){
                                                   // $paper_val.= $core_val['course_code'].',';
                                                ////}
                                           // }
                                            ////$i++;
                                            //}
                                          
                                            ?>
                                        
<!--                                        <div class="col-sm-6 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label"><?=$cat_value;?><span class="asterisk">*</span></label>
                                            
                                                <input type="text" name="course_group[]" value ="<?=$str;?>" class="form-control" readonly="readonly"  />
                                            </div>
                                        </div> -->
                                             <?php 
                                             //$inc = 0;
                                             //foreach($this->course_val as $Course_index => $course_val){
                                             //  print_r($this->ge_arr);
                                               //  die(); 
                                               
                                            ///if($this->ge_arr[$cat_index] == $course_val['ge_id'] && $course_val['ge_id'] !=0  )                                             {
                                               // print_r($course_val);
                                                // die();
                                               // $course_model = new Application_Model_Course();
                                               // $result_course = $course_model->getRecord($course_val['electives']);
                                                
                                               // $paper_val.= $result_course['course_code'].',';}
                                             //}
                                            ?>
<!--                                        <div class="col-sm-6 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Papers <span class="asterisk">*</span></label>
                                            
                                                <input type ="text" name="paper_name[]" value="<?=$paper_val;?>" class="form-control" readonly="readonly" />           
                                            </div>
                                        </div>-->
                                
                                     <?php //} ?>
 <table class="table table-bordered">
                                            <thead>
                                                <tr><th>Course Code</th><th>Paper</th><th>Allowed</th></tr>
                                            </thead>
                                            <tbody>
                                                
                                                <?php
                                                
                                                ?>
                                                <?php 
                                            ///  echo "<pre>";print_r($this->exam_sch); 
                                                 foreach($this->exam_sch as $key => $value ){ 
                                               //echo "<pre>";print_r($this->exam_sch); 
                                                //die();
                                                  $course_name = new Application_Model_Course();
                                                     $datetime = new Application_Model_ExamScheduleModel();
                                                     $exam_date =$datetime->getDateByCourseId($value['course_id']); 
                                                    $coursname = $course_name->getRecord($value['course_id']);
                                               
                                               $allow_model1 = new Application_Model_BatachSemesterAttendance();
//                                                 if($value['ge_id']==0 || $value['cc_id']==5 || $value['cc_id']==10 || $value['cc_id']==15 || $value['cc_id']==23 || $value['cc_id']==24) {
//                                                  $value['course_id'] = 0;
//                                                   $attendstatus = $allow_model1->checkCoreRecordBycid($this->fid,$value['course_id'],$value['cc_id']);
//                                              //echo "<pre>";print_r($attendstatus); 
//                                                //die();
//                                              }
//                                            else {
//                                              $attendstatus = $allow_model1->checkRecordBycid($this->fid,$value['course_id']);
//                                            } 
                                                if($value['ge_id']==0)
                                                     $value['course_id'] = 0;
                                                $attendstatus = $allow_model1->checkRecordBycid($this->fid,$value['course_id'],$this->term_id);
                                              foreach ($attendstatus as $attend_key => $atted_val){
                                              
                                                  
                                                ?>
                                                <tr>
                                                    
                                                    <td><?=$coursname['course_code'];?></td>
                                                     <td><?=$coursname['course_name'];?></td>
                                                     <?php if($atted_val['attend_status'] == 1){ ?>
                                                  <td>No</td>
                                                   
                                                     <?php }else{?>                                                    
                                                  <td>Yes</td>
                                                  
                                                     <?php } ?>
                                                </tr>
                                              <?php }
                                                     } ?>
                                            </tbody>
                                            
                                        </table>
                                    </div>