<?php 
//echo "<pre>";print_r( $this->weightage);die;
?>
<style>
    input { 
    text-align: center; 
}

input:focus{
    border:2px solid #00ed22;
    
}
    </style>
    <?php
    $attendanceCheck= array(
        '0' =>'Allowed',
        '1' =>'Not Allowed'
    );
    //echo "<pre>"; print_r($attendanceCheck);
    ?>
<div style="overflow-x:scroll">
<div class="padding-md clearfix">
    <div class="col-sm-0" style="float:right;">
        <a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a>
    </div>
<table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable-grade" id="dataTable">
						
    <thead>
        <tr>
            <th>S.No.</th>
            <th>Participants Name</th>
            <th>Roll No.</th>
            <th>Batch</th>
            <th> UID</th>
            <th> Reg. No.</th>
            <th>Exam Roll. No.</th>
            <th style="width:2%">Total class Attend</th>
            <th style="width:2%">Total Percent</th>  
        </tr>
    </thead>
    <tbody>
        <?php if(!empty($this->result))	 {  $i = 1;  

        foreach($this->result as $k => $result) { 

        ?>
        <tr>
            <td><?php echo $i;
                $i++; ?>
            </td>
		<td><?php echo $result['student_name'];?></td> 
                <input type="hidden" name="stu_id[]" id="student_id" value="<?php echo $result['student_id']; ?>" /> 
                 <input type="hidden" name="grade[academic_id_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" id="term_id1" value="<?php echo $result['academic_id']; ?>" />
            <input type="hidden" name="grade[term_id_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" id="academic_id1" value="<?php echo $result['term_id']; ?>" />
           <input type="hidden" name="u_id[]" id="student_id" value="<?php echo $result['stu_id']; ?>" />
            <td><?php echo '#123' ?></td> 		
            <td><?php echo $result['stu_id']; ?></td> 		 
            <td><?php echo $result['stu_id'];?></td>
            <td><?php echo $result['reg_no'];?></td>
            <td><?php echo $result['exam_roll'];?></td>
            
           <td><input type="text" name="attended_class[]" class="attended_class"  id = "attended_class" value="<?php echo $result['attended_class']; ?>" /></td>
           
</tr>
        <?php }  }else { ?>
        <?php
          $i = 1;
          $j=1;
        ?>
        <?php if($this->category_data){foreach($this->category_data as $key=>$val){ //echo "<pre>";print_r($val);   ?>
        <tr>
            <td><?php echo $i;
                $i++; ?>
            </td>
            <td><?php echo $val['students'];?></td> 
            <input type="hidden" name="stu_id[]" id="student_id" value="<?php echo $val['student_id']; ?>" /> 
            <input type="hidden" name="grade[student_id][]" id="student_id" value="<?php echo $val['student_id']; ?>" />
            <input type="hidden" name="grade[academic_id_<?php echo $val['student_id']; ?>][]" id="term_id1" value="<?php echo $val['academic_id']; ?>" />
            <input type="hidden" name="grade[term_id_<?php echo $val['student_id']; ?>][]" id="academic_id1" value="<?php echo $val['term_id']; ?>" />
            <input type="hidden" name="u_id[]" id="student_id" value="<?php echo $val['stu_id']; ?>" />
            <td><?php echo '#123';?></td> 	
            <input type="hidden" name="batch_code[]" id="batch_code" value="<?php echo $val['short_code']; ?>" />
            <td><?php echo $val['short_code'];?></td> 		
           
            <td><?php echo $val['stu_id'];?></td>
            <td><?php echo $val['reg_no'];?></td>
            <td><?php echo $val['exam_roll'];?></td>
           
            <td><input type="text" name="attended_class[]" id="attended_class" tabindex="<?php echo $j;
                $j++; ?>" data-toggle="number" autocomplete="off" class="attended_class"  value="<?php echo $val['attended_class']; ?>" /></td>
            <td><input type="text" name="percent_sum[]" id="percent_sum" class="percent_sum"  readonly value="<?php echo $val['percent_sum']; ?>" /></td>
        </tr>
        <?php } }} ?>
    </tbody>
</table>
</div>
</div>
<script>
     modifiedDataTable(true);
   $('div.dt-buttons').hide();
  
    $('body').on('change', '.attended_class', function () {
        var total_conducted_cl=$('#conducted_class').val();
         $('input[name^="attended_class"').each(function(){
            
         });
         var attended_class = $(this).val();
         if(Number(attended_class) > Number(total_conducted_cl)){
                alert('Class Attended should not be greater than  total class conducted!');
                $(this).val('');

                $(this).focus();
                return false;
         }
       
    });
    $('body').on('keyup', '.attended_class', function () {
        var tot_conducted_cl = $('#conducted_class').val();
        
       
        if(tot_conducted_cl == ''){
            alert('Please First put total class conducted field!');
        }
        $('input[name^="attended_class"').each(function(e){
            var number =  $(this).val();
            //alert(number);
            
            if(number != '' && tot_conducted_cl != ''){
                
                var percent = Math.round(($(this).val() / tot_conducted_cl)*100);
                
                $('.percent_sum').eq(e).val(percent);
                $('.percent_sum').css("background-color", "#D3D3D3");
            }else{
                
                $('.percent_sum').eq(e).val(0);
            }
        }); 
    });
    
    //To accept only no.
    $('input[data-toggle="number"]').bind('keyup blur',function(){
        var node = $(this);
        
        node.val(node.val().replace(/[^0-9]/g,'') );
    });
</script>

