<style>
    body#LoginForm{padding-top: 20em}
.form-heading { color:#fff; font-size:23px;}
.login-form .form-control {
  background: #f7f7f7 none repeat scroll 0 0;
  border: 1px solid #d4d4d4;
  border-radius: 4px;
  font-size: 14px;
  height: 50px;
  line-height: 50px;
}
.main-div {
  background: #ffffff none repeat scroll 0 0;
  border-radius: 2px;
  margin: 10px auto 30px;
  max-width: 50%;
  padding: 50px 70px 70px 71px;
  margin-top: 15em;
  
}


.login-form{ text-align:center;}

.login-form  .btn.btn-primary {
  background: #f0ad4e none repeat scroll 0 0;
  border-color: #f0ad4e;
  color: #ffffff;
  font-size: 14px;
  width: 100%;
  height: 100%;
  line-height: 50px;
 
}


.login-form .btn.btn-primary.reset {
  background: #ff9900 none repeat scroll 0 0;
}
</style>


<body >
<div class="container">
    
<div class="login-form">
<div class="main-div">
    <div class="panel">
   <h3> To Upload Documents </h3>
   <h3>Please Enter Your Application Number</h3>
   </div>
    <form class="documentForm" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

        <div class="form-group">


            <input type="text" name="app_no" class="form-control" id="app_no" placeholder=" A-2020-XXXX" required>

        </div>

        
       
        <button type="submit" class="btn btn-primary">Go To Upload </button>

    </form>
    </div>
</div></div></div>


</body>
</html>
