<style>
    .link:link,
    .link:visited{
        position: relative;
        display: inline-block;
        padding:.2em 2em;
        border-radius:100px;
        /*  background-color:#faa2b1;*/
        -webkit-transition: all .2s;
        transition: all .2s;
    }


    .link::after{
        content: "";
        position:absolute;
        top:0px;
        left:0px;
        background-color:#faa2b1; 
        width:100%;
        height:100%;
        z-index:-1;
        border-radius:100px;
        -webkit-transition: all .2s;
        transition: all .2s;
    }



    .link:hover{
        box-shadow:0px 5px 6px #000;
    }

    .link:hover::after{
        transform:scale(2,3);

    }

    .link:active{
        box-shadow:0px 5px 1px #000;
    }

    dt{
        display:none;
    }
</style>

<div class="right_col">
   

        <?php if (count($this->messages)) {
            foreach ($this->messages as $message) {
                ?>
              <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
        <!-- widget grid -->
     
                <div class="row">

                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars"> OTP Dashboard</i>

                        </h3>
                    </div>

                </div>

                <div class="x_panel">

                    <div class="x_title">
                        <h2>OTP</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li class="dropdown">
                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            </li>
                            <li><a class=""><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <div class="x_content">

                        <div class="padding-md clearfix">
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">
                                <thead>
                                    <tr>
                                        <th style="text-align:center;">S. No.</th>	
                                        <th style="text-align:center;">Student Name</th>
                                        <th style="text-align:center;">Registration Number</th>
                                        <th style="text-align:center">Examination Id</th>    
                                        <th style="text-align:center">OTP</th>
                                       
                                    </tr>
                                </thead>
                                <tbody style="text-align:center;">
                                    <?php
                                    
                                     $i=1;

                                        foreach ($this->studata as $results) {
                                            
                                           //print_r($results);
                                           //die();
                                            ?>
                                            <tr>
                                                <td><?php echo $i;

                                            $i++;
                                            ?>
                                                </td>						


                                              <td><?=$results['stu_fname']?></td>

                                                <td><?=$results['u_id']?></td>
                                                <td><?=$results['exam_roll']?></td>
                                                 <td><?=$results['otp']?></td>
                                              

                                            </tr>            

                                        <?php
                                        }  
                                    ?>

                                </tbody>
                            </table>
   
                        </div><!-- /.padding-md -->
                    </div><!-- /panel -->
                </div>
            </div>
      
<script>

    $('#dataTable').DataTable();

</script>