<?php //echo "<pre>";print_r($this->elective);exit;   ?>
<style type="text/css">

    .bold-checkbox{
        position: absolute; top: 12px; font-weight:bold;
    }

</style>
<link rel="stylesheet" type="text/css" href="https://printjs-4de6.kxcdn.com/print.min.css">

  
<style>

 @page 
    {
        size:  auto;   /* auto is the initial value */
        margin: 0mm;  /* this affects the margin in the printer settings */
    }


   
    #custom_data_records{
        width:100%;
        text-align: right;
        font-size:1.5em;

    }
    
    .load-box{
        display:none;
        position:absolute;
        width:100%;
        height:100%;
        background:rgba(146,40,46,.5);
        z-index: 999;
    }
    
    .load-box>img{
        position:absolute;
        top:50%;
        left:50%;
        width:40em;
        transform: translate(-50%,-50%);
        
        
    }
    
</style>
<!-- <link href="<?php echo $this->mainconfig['publicpath']; ?>css/custom.css" rel="stylesheet"> -->

<?php if ($this->type=='add') { ?>


<?php } else {?>
<div class="right_col examid">

    <div class="">
      
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars"> Payment Dashboard</i>

                    </h3>
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">   

                    
                </div>
            </div>

            <div class="x_panel">
                <div class="x_title">
                    <div class="row">
                        <div class="col-sm-5">
                            <h2 class="title1">Payment Information</h2></div>
                      
                    <div class="clearfix"></div>
                </div>
                     </div>
               
                <div class="x_content">
  
                    <div class="padding-md clearfix">
                        <div class="col-sm-0" style="float:right;">
                          
                        </div>
                        <div class="table-responsive" id="studentData"> 


<!--///////   raushan  -->
<div class="panel panel-default">               
                            <div class="panel-body">
                                <div class="row">
               <div class="col-sm-6">        
              <form method="post" action="<?php echo $this->form->getAction() ?>type/add">
              <input type="hidden" name="registraion_num" value="<?=$this->fid;?>">
              <input type="hidden" name="exmination_id" value="<?=$this->eid;?>">
              <input type="hidden" name="stu_name" value="<?=$this->stdname;?>">
              <input type="hidden" name="total_fee" value="<?=$this->totalfee;?>">
              <input type="hidden" name="exam_fee" value="<?=$this->feeamount;?>">
             <input type="hidden" name="late_fine" value="<?=$this->examfeena;?>">
             <input type="hidden" name="email" value="<?=$this->email;?>">
             <input type="hidden" name="last_id" value="<?=$this->last_id;?>">
             <input type="hidden" name="phone" value="<?=$this->phone;?>">
          
                        <p>Student Name : <?=$this->stdname;?> </p>
                        <p>Your Registration Id : <?=$this->fid;?> </p>
                        <p>Your Examination Id: <?=$this->eid;?> </p>
                        <p>Your Exam fee : <?=$this->feeamount;?>   </p>
                        <p>Your late Fine Exam  :  <?=$this->examfeena;?>   </p>
                        <p>Total  :  <?=$this->totalfee;?>  </p>
                                    <div class="col-sm-3 employee_class">
                                        <label></label>
                                        <div class="form-group" >
                                            <input type="submit" name="pay" value="Pay Now">
                                        </div>
                                    </div>
              </form>
                   </div>


<div class="col-sm-6">
 <div class="padding-md clearfix">
 <form method="post" action="<?php echo $this->mainconfig['host']; ?>application/previewpgform/type/view" target="_blank">
  <input type="hidden" name="stu_id" value="<?=$this->fid;?>">
  <input type="submit" class="btn btn-success" value="Preview From">
 </form>
 </div>

</div>

                                </div>
                            </div>
                       

                    </div>
                  

                                       </div>
   
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->     
  </div><!-- /.col-->    
<?php } ?>

 <script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>

<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script> 


