<?php //echo "<pre>";print_r($this->elective);exit;   ?>
<style type="text/css">

    .bold-checkbox{
        position: absolute; top: 12px; font-weight:bold;
    }
    
    body.modal-open .supreme-container{
    display: none;
        
        
}

</style>
<link rel="stylesheet" type="text/css" href="https://printjs-4de6.kxcdn.com/print.min.css">

  
<style>
@media print {
  .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12 {
    float: left;
  }
  .col-sm-12 {
    width: 100%;
  }
  .col-sm-11 {
    width: 91.66666667%;
  }
  .col-sm-10 {
    width: 83.33333333%;
  }
  .col-sm-9 {
    width: 75%;
  }
  .col-sm-8 {
    width: 66.66666667%;
  }
  .col-sm-7 {
    width: 58.33333333%;
  }
  .col-sm-6 {
    width: 50%;
  }
  .col-sm-5 {
    width: 41.66666667%;
  }
  .col-sm-4 {
    width: 33.33333333%;
  }
  .col-sm-3 {
    width: 25%;
  }
  .col-sm-2 {
    width: 16.66666667%;
  }
  .col-sm-1 {
    width: 8.33333333%;
  }
  .col-sm-pull-12 {
    right: 100%;
  }
  .col-sm-pull-11 {
    right: 91.66666667%;
  }
  .col-sm-pull-10 {
    right: 83.33333333%;
  }
  .col-sm-pull-9 {
    right: 75%;
  }
  .col-sm-pull-8 {
    right: 66.66666667%;
  }
  .col-sm-pull-7 {
    right: 58.33333333%;
  }
  .col-sm-pull-6 {
    right: 50%;
  }
  .col-sm-pull-5 {
    right: 41.66666667%;
  }
  .col-sm-pull-4 {
    right: 33.33333333%;
  }
  .col-sm-pull-3 {
    right: 25%;
  }
  .col-sm-pull-2 {
    right: 16.66666667%;
  }
  .col-sm-pull-1 {
    right: 8.33333333%;
  }
  .col-sm-pull-0 {
    right: auto;
  }
  .col-sm-push-12 {
    left: 100%;
  }
  .col-sm-push-11 {
    left: 91.66666667%;
  }
  .col-sm-push-10 {
    left: 83.33333333%;
  }
  .col-sm-push-9 {
    left: 75%;
  }
  .col-sm-push-8 {
    left: 66.66666667%;
  }
  .col-sm-push-7 {
    left: 58.33333333%;
  }
  .col-sm-push-6 {
    left: 50%;
  }
  .col-sm-push-5 {
    left: 41.66666667%;
  }
  .col-sm-push-4 {
    left: 33.33333333%;
  }
  .col-sm-push-3 {
    left: 25%;
  }
  .col-sm-push-2 {
    left: 16.66666667%;
  }
  .col-sm-push-1 {
    left: 8.33333333%;
  }
  .col-sm-push-0 {
    left: auto;
  }
  .col-sm-offset-12 {
    margin-left: 100%;
  }
  .col-sm-offset-11 {
    margin-left: 91.66666667%;
  }
  .col-sm-offset-10 {
    margin-left: 83.33333333%;
  }
  .col-sm-offset-9 {
    margin-left: 75%;
  }
  .col-sm-offset-8 {
    margin-left: 66.66666667%;
  }
  .col-sm-offset-7 {
    margin-left: 58.33333333%;
  }
  .col-sm-offset-6 {
    margin-left: 50%;
  }
  .col-sm-offset-5 {
    margin-left: 41.66666667%;
  }
  .col-sm-offset-4 {
    margin-left: 33.33333333%;
  }
  .col-sm-offset-3 {
    margin-left: 25%;
  }
  .col-sm-offset-2 {
    margin-left: 16.66666667%;
  }
  .col-sm-offset-1 {
    margin-left: 8.33333333%;
  }
  .col-sm-offset-0 {
    margin-left: 0%;
  }
  .visible-xs {
    display: none !important;
  }
  .hidden-xs {
    display: block !important;
  }
  table.hidden-xs {
    display: table;
  }
  tr.hidden-xs {
    display: table-row !important;
  }
  th.hidden-xs,
  td.hidden-xs {
    display: table-cell !important;
  }
  .hidden-xs.hidden-print {
    display: none !important;
  }
  .hidden-sm {
    display: none !important;
  }
  .visible-sm {
    display: block !important;
  }
  table.visible-sm {
    display: table;
  }
  tr.visible-sm {
    display: table-row !important;
  }
  th.visible-sm,
  td.visible-sm {
    display: table-cell !important;
  }
       #non-printable { display: none; }
        #printable { display: block; } 
        
  .printdiv:last-child {
     page-break-inside: avoid;
}
}
 @page 
    {
        size:  auto;   /* auto is the initial value */
        margin: 0mm;  /* this affects the margin in the printer settings */
    }


   
    #custom_data_records{
        width:100%;
        text-align: right;
        font-size:1.5em;

    }
    
    .load-box{
        display:none;
        position:absolute;
        width:100%;
        height:100%;
        background:rgba(146,40,46,.5);
        z-index: 999;
    }
    
    .load-box>img{
        position:absolute;
        top:50%;
        left:50%;
        width:40em;
        transform: translate(-50%,-50%);
        
        
    }
    
</style>
<!-- <link href="<?php echo $this->mainconfig['publicpath']; ?>css/custom.css" rel="stylesheet"> -->

<div class="right_col">
     <?php
     
    if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div <?php
            if ($_SESSION['admin_login']['admin_login']->flash_error == 0) {
                echo 'class="alert alert-danger"';
                $_SESSION['admin_login']['admin_login']->flash_error = 1;
            } else {
                echo "class='alert alert-success'";
            }
            ?>>
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php
        }
    }
    ?>

    <?php if ($this->type=='add') { ?>
        <div class="padding-md">
            <?php
             $course_name = new Application_Model_Course();
            ?>

            <div class="row examid">
                <div class="col-md-9" id="non-printable">
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye"> Exam Form</i></div>
                    </h3>
                </div>
                
                 <div class="col-md-3" id="non-printable">
                    <h3 class="page-title txt-color-blueDark" >
                        
                    </h3>
                </div>
          
                      <div class="col-md-12">
                   
                    <div class="panel panel-default masterbox" id="printable">
                       
                          <div class="col-sm-12">
                                  <div class="col-sm-offset-1 col-sm-2 employee_class">
                                            <div class="form-group disabled">
                                              <figure class="figure">
                                              <img src="<?php echo $this->mainconfig['host']; ?>images/img.png" alt="..." class="img"> 
          
                                          </figure>
                                            </div>
                                        </div> 
                                <div class="col-sm-6">
                                   <h2 style="text-align: center;">PATNA WOMEN'S COLLEGE </h2>
                                   <h3 style="text-align: center;">Autonomous  </h3>
                                   <h4 style="text-align: center;">PATNA  UNIVERSITY </h4>
                                 <h5 style="text-align: center;"> Examination Form Of Semester End.</h5>
                                    <h2 style="text-align: center;"><strong>NON-Collegiate</strong></h2>
                               
                                </div>
                        <div class="col-sm-offset-1 col-sm-2 employee_class">
                            <div class="form-group disabled" style="width:50%;">
                                              <figure class="figure">
                                              <img src="<?php echo $this->mainconfig['host']; ?><?=$this->stu_details['filename']?>" alt="..." class="img-thumbnail"> 
                                         <figcaption class="figure-caption text-center"><?=$this->fid?></figcaption>
                                          </figure>
                                            </div>
                                        </div> 
                                 
                    </div>
                        
<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>save" method="post" data-validate="parsley"  enctype="multipart/form-data">

                            <div class="panel-body">

                                
                                <div class="row">
                                    
                                       
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled" >
                                                <label class="control-label">Year<span class="asterisk">*</span></label>
                                                <?php echo $this->form->year; ?>
                                            </div>
                                        </div>

                                        <div class="col-sm-4 employee_class">
                                                    <div class="form-group">
                                             <label class="control-label">Session<span class="asterisk">*</span></label>
                                                     <?php echo $this->form->session;    ?>
                                            <input type="hidden" name="session_id" id="session_id" value="<?=$this->s_id?>">
                                            <input type="hidden" name="academic_id" id="academic_id" value="<?=$this->acd_id?>">
                                            <input type="hidden" name="f_id" id="f_id" value="<?=$this->fid?>">
                                            <input type="hidden" name="st_id" id="st_id" value="<?=$this->st_id?>">
                                            <input type="hidden" name="non_data" id="non_data" value="1">
                                               </div>
                                           </div> 
        <div class="col-sm-4 employee_class">
            <div class="form-group">
              <label class="control-label">Semester<span class="asterisk">*</span></label>
                <?php   $semattend = new Application_Model_BatachSemesterAttendance(); ?>
            
              <select name="semester" id=""  class="form-control chosen-select" required="required">
              <option value="<?=$this->term_details['term_id']?>"><?=$this->term_details['term_name']?></option>
              </select>
            </div>
            </div>
           </div>
         
              <div class="row">
             
                    <div class="col-sm-4 employee_class">
                        <div class="form-group disabled">
                            <label class="control-label">Name <span class="asterisk">*</span></label>
                                <input type="text" name="stu_name" id="stu_name" value="<?=$this->stu_name?>" class="form-control" required="true" readonly="readonly" autocomplete="off">
                                            </div>
                                        </div> 
                                           <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                              <label class="control-label">Date of Birth<span class="asterisk">*</span></label>
                                                    <?php echo $this->form->stu_dob; ?>  
                                            </div>
                                        </div> 
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Father's/ Mother's Name<span class="asterisk">*</span></label>
                                                <?php echo $this->form->father_fname; ?>
                                             </div>
                                        </div>
 
<!--             </div>
                                <div class="row">
                                
                                    <div class="row">-->
                                        
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                              <label class="control-label">Registration Number<span class="asterisk">*</span></label>
                                                    <?php echo $this->form->registration_no; ?>  
                                            </div>
                                        </div> 
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Examination Id<span class="asterisk">*</span></label>
                                                    <?php echo $this->form->exam_roll; ?> 
                                            </div>
                                        </div>
<!--                                        </div>
                                    </div>-->
<!--                                <div class="row">
                                    <div class="row">
                                        -->
                                        

                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Examination<span class="asterisk">*</span></label>
                                                    <?php echo $this->form->examination; ?>
                                            </div>
                                        </div>  

                                        

                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">College<span class="asterisk">*</span></label>
                                                    <?php echo $this->form->college; ?>
                                                <span id="erremail" style="color:red;"></span>
                                            </div>
                                        </div>   
                                        
                                        
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                  <label class="control-label">Email<span class="asterisk">*</span></label>
                                                    <input type="email" name="email" id="email" value="" class="form-control" required="true">
                                                <span id="erremail" style="color:red;"></span>
                                            </div>
                                        </div>   
                                       <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                  <label class="control-label">Phone<span class="asterisk">*</span></label>
                                                    <input type="number" name="phone" id="phone" class="form-control" required="true">
                                                <span id="erremail" style="color:red;"></span>
                                            </div>
                                        </div>  
                                    </div>
                                   
                                </div>  
                                <div class="row">   
                                    <div class="col-sm-3"><h4><span style="color:#777;">Subjects of Examination </span></h4></div>
                                </div>
                                     <div class="row">     
                                   <?php //print_r($this->checkk);
                                     //die();
                                   foreach($this->checkk as $key=> $value) {
                                       
                                       $coursemodel = new Application_Model_Course();
                                       $getrow = $coursemodel->getRecord($value['course_id']);
                                      // print_r($getrow);
                                     //die();
                                   ?>
                                        
                                      
                                        <div class="col-sm-6 employee_class">
                                            <div class="form-group disabled">
                                               
                                                <input type="text" name="course_code[]" value ="<?=$getrow['course_code']?>" class="form-control" readonly="readonly"  />
                                            </div>
                                        </div> 
                                        
                                        
                                         <div class="col-sm-6 employee_class">
                                            <div class="form-group disabled">
                                               
                                            <input type="text" name="course_name[]" value ="<?=$getrow['course_name']?>" class="form-control" readonly="readonly"  />
                                            </div>
                                        </div> 
                                       
                                       
                                        
                                   <?php } ?>
                                    

                                   
                                    </div>
                                    <div class="col-sm-12"><h4><span style="color:#777;">
                                <p> To,</p>
                                  <p>The Principal Madam,  </p>

                                   <p>I request for permission to appear at the <?=$this->semester;?> Examination to be held in <?php echo date('F')?> <?php echo date('Y')?>.</p>

                                      <p> Centre of Examination : Patna Women's College  </p>     

                                    <p>Examination Roll No. : <?=$this->checkk[0]['exam_roll'];?>  </p>

                                     <p>Date of Commencement of Examination <?php echo date('F')?> <?php echo date('Y')?>.</p>

                                        <p style="float: right;">Full Signature of the Candidate</p>
                                </span></h4></div>
                                </div>
                            </div>
              
                <div class="panel-footer">                                  
                    <div class="row">
                        <div class="col-sm-7 col-sm-offset-5">
                            <?php //if ($this->type == 'add' && $this->extdate >= $curdate  && $this->payactivaion == 1) { ?> 
                                <div style="float:left;margin-right:2px;">
                                    <input type="submit" class="btn btn-primary submit" name="submit" value="Save">
                                </div>
                             <?php //} ?>
                        </div>
                    </div>
                </div>
                   </form>
                    </div>
            </div>
        </div><!-- /panel -->
    <!-- /.padding-md --> 
    <?php } elseif($this->type=='otpverify') {  ?>
    <div class="examid">
      
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Non-collegiate Student Examination Form</i>
<?=$this->mssg;?>
                    </h3>
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">   
                </div>
            </div>

            <div class="x_panel">
  <div class="load-box">
             <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
        </div>
                <div class="x_title">
                    <div class="row">
                        <div class="col-sm-5">
                            <h2 class="title1">OTP Verification</h2></div>
                        
                      
                    <div class="clearfix"></div>
                </div>
                     </div>
               
                <div class="x_content">

                    <div class="padding-md clearfix">
                        
                        <div class="table-responsive" id="studentData"> 


<!--///////   raushan  -->
<div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-sm-6 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Admission Form No . <span class="asterisk">*</span></label>
                                            <?php //echo $this->form->stu_id; ?>
											 <input type="text" name="stu_id" id="stu_id" value="" placeholder="F-XXXX-XXXX" class="form-control" required="true">
                                        </div>
                                    </div>
                                    
                                     <div class="col-sm-6 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Enter Your Otp . <span class="asterisk">*</span></label>
                                            <?php //echo $this->form->otp; ?>
											<input type="number" name="otp" id="otp" value="" placeholder="Enter Your OTP" class="form-control" required="true">
                                        </div>
                                    </div>
									</div>
									<div class="row">
                                    <div class="col-sm-6 employee_class">
                                        <div class="col-md-3">
                                        <div class="form-group" >
                                            <input type="submit" name="search" class="btn btn-info" value="Verify And proceed">
                                    </div>
                                        </div>
                                       <div class="col-md-3">
                                        <div class="form-group" >
                                             <a href="<?=$this->manconfig['host']?>application/pgnoncollegiate"  class="btn btn-primary">Generate OTP</a>
                                    </div>
                                        </div>
                                    </div>

                                  <div class="col-sm-6"> 
                                   <p style="font-size:12px ">For any query please send email on : support@finessewebtech.com with details infromation:</p>
                                        <ul> <ol>
                                          1. Form Id          
                                              </ol>
                                             <ol>2. Email ID : placed while feeling up form</ol>
                                            <ol>3. Your Question:</ol>
                                       </ul> 
                                         </div>

                                </div>
                            </div>
                        </form>

                    </div></div>
   
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div>
    
<?php } else { ?>

    
   
    <div class="">
    <!-- widget grid -->
    <div class="row">    
            <div class="col-sm-12">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">  Non-Collegiate Examination Form</i>
<?=$this->mssg;?>
                    </h3>
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">   
                </div>
            </div>

            <div class="x_panel col-sm-12 masterbox examid">
  <div class="load-box">
             <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
        </div>
                <div class="x_title">
                    <div class="row">
                        <div class="col-sm-5">
                            <h2 class="title1">Exam Form Using Registration ID</h2></div>
                        
                      
                    <div class="clearfix"></div>
                </div>
                     </div>
               
                <div class="x_content">

                    <div class="padding-md clearfix">
                        
                        <div class="table-responsive" id="studentData"> 


<!--///////   raushan  -->
<div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-sm-4 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Admission Form No . <span class="asterisk">*</span></label>
                                            <?php //echo $this->form->stu_id; ?>
											 <input type="text" name="stu_id" id="stu_id" value="" class="form-control" required="true" placeholder="F-XXXX-XXXX">
                                        </div>
                                    </div>
                                     <div class="col-sm-4 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Mobile Number . <span class="asterisk">*</span></label>
                                            <?php //echo $this->form->phone; ?>
											<input type="number" name="phone" id="phone" placeholder="For OTP Enter Valid phone No" class="form-control" required="true" maxlength="10">
                                        </div>
                                    </div>
                                      <div class="col-sm-4 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Email Id . <span class="asterisk">*</span></label>
                                           <input type="email" name="email" id="email" placeholder="For OTP Provide your valid email id" class="form-control" required="true">
                                        </div>
                                      </div>
									  </div>
							   <div class="col-sm-12">
							   <div class="col-sm-6 employee_class">
                                        <div class="col-sm-3">
                                    
                                     
                                        <div class="form-group" >
                                            <input type="submit" name="search" class="btn btn-info" value="Send Otp">
                                    </div>
                                        </div>
                                       <div class="col-sm-3">
                                        <div class="form-group" >
                                            <a href="<?php echo $this->mainconfig['host']; ?>application/pgnoncollegiate/type/otpverify" class="btn btn-primary"> I Already have the Otp</a>
                                        </div>  
                                    </div>
                                   </div>

                                    <div class="col-sm-6">
                                         <p style="font-size:12px ">For any query please send email on : support@finessewebtech.com with details infromation:</p>
                                        <ul> <ol>
                                          1. Form Id          
                                              </ol>
                                             <ol>2. Email ID : placed while feeling up form</ol>
                                            <ol>3. Your Question:</ol>
                                       </ul> 
                                    </div>


                                </div>
                                  <!--<div class="col-sm-12">
                                    <h4 style="color:#000FFF; font-weight: 800">
                                       Notice:  "After the announcement of End Semester Examination schedule, College Office will provide the Admit Card for the students of Semester-II and IV. The examination schedule will be announced after the lockdown."
                                    </h4>
                                </div>-->
                            </div>
                        </form>

                    </div></div>
   
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
       
    </div><!-- /.padding-md -->   
    </div>

<?php } ?>

<script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script> <script>
    $(document).ready(function() {
  
      var aca =  $('#academic_id').val();
      var sem =  $('#semester').val();
      var sid =  $('#st_id').val();
      
       // alert(sem);
        $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'application/ajax-get-student-course'; ?>',
                data: {batch_id: aca, term_id: sem,sid:sid}
            }).done(function (data) {
              //alert(data);
               $('#getcourse').html(data);
            });

    $('#semester').change(function(){
      var aca =  $('#academic_id').val();
      var sem =  $('#semester').val();
      var sid =  $('#st_id').val();
      
       // alert(sem);
        $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'application/ajax-get-student-course'; ?>',
                data: {batch_id: aca, term_id: sem,sid:sid}
            }).done(function (data) {
              //alert(data);
               $('#getcourse').html(data);
            });
    });
});
</script>


