
<style>
    #academic_year_id{
        display:none;
    }   
    #academic_year_id_chosen{
        display:none;
    }
 </style>

 <?php 

 echo $this->form->academic_year_id; 
                                    $academic_details = new Application_Model_Academic();
                                    $term_details = new Application_Model_TermMaster();
                                    $acad_info = $academic_details->getRecord($this->academic_id);
                                    $term_id = 0;
                                    
                                    preg_match('/^F-2018-\d{1,}/', $this->u_id, $output_array);
                                   
                                    if(!empty($output_array[0])){
                                        if($this->academic_id=='65'){
                                        $term_det = $term_details->getTermRecordsbycmn1($this->academic_id,'t2');
                                        }
                                        else
                                        {
                                             $term_det = $term_details->getTermRecordsbycmn1($this->academic_id,'t4');
                                        }
                                         
                                    }
                                    else {
                                             $term_det = $term_details->getTermRecordsbycmn1($this->academic_id,'t2');
                                        }                 
?>

<div class="padding-md right_col">
    <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
 </div>   
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye">View and Download Mark Sheet</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">

							<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
                              <label class="control-label">&nbsp;</label>
							<input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly />
							</div>
						</div>
						</div>
                                            <div class="row">
                                                <div class="col-md-12" id="grade_sheet">
                                                    
                                                </div>
                                            </div>
						<div id="getstudent" class="col-sm-12">
							</div>
							</div>
						
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<script>


//  $(document).ready(function() {
// 		$('#batch').hide();
//               	$('.load-box').css('display','block');	
//             getstudentDetails();
//         $('body').on('change', '#term_id, #stu_id', function() {
	
//         });
// 	});
 
	
//     function getstudentDetails() {
        
        
//                 $.ajax({ 
// 			type: "POST",
// 			url:"<?php echo $this->mainconfig['host'].'application/ajax-get-grade-view';?>",
// 			data: { 'academic_id': <?=$this->academic_id?>,
// 					'year_id':<?=$term_det['year_id'];?>,
//                                         'term_id':<?=$term_det['term_id'];?>,
// 					'stu_id': "<?=$this->id;?>",'phone':"<?=$this->phone;?>"}
// 		}).done( function( data ) { 
//                                         //alert(data);	
//                         $("#grade_sheet").empty();
// 			$("#grade_sheet").html(data);
//                         $('.load-box').css('display','none');
// 		});
	
        
        
        
//         $url = '<?php echo $this->mainconfig['host']; ?>application/get-student-report';
//         $.post($url,
//                 {'academic_id': <?=$this->academic_id?>,
// 					'year_id':<?=$term_det['year_id'];?>,
//                                         'term_id':<?=$term_det['term_id'];?>,
// 					'stu_id': "<?=$this->id;?>",'phone':"<?=$this->phone;?>"
//         })
//                 .done(function(data) {
                  
//                     //$('#payslipData').html('');
//                     $('#getstudent').html(data);
//                       $('.load-box').css('display','none');
//                 });

//     }

//  $("#academic_year_id").change(function() {
// 	 var academic_year_id=$("#academic_year_id").val();
//   if(academic_year_id !=''){
//         $('.load-box').css('display','block');
// 	 $.ajax({ 
// 			type: "POST",
// 			url:"<?php echo $this->mainconfig['host'].'report/ajax-get-student-names';?>",
// 			data: { academic_year_id : academic_year_id}
// 		}).done( function( data ) { 
// 	     //alert(data);	
// 			$("#stu_id").html(data);
//                           $('.load-box').css('display','none');
// 		});
// 	}
// });


//  $('body').on('change', '#academic_year_id', function() {		
// var academic_id=$('#academic_year_id').val();
//   if(academic_id){
//   $('#batch').show();
// 	$.ajax({ 
// 			type: "POST",
// 			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
// 			data: {academic_id:academic_id}
// 		}).done(function( data ) {
// 			var result = $.parseJSON(data);
// 			if((data!='')){
// 				$('#batch').val(result['short_code']);
// 			}
// 	  });
// 	 }
	 
//  });
 
//   $('body').on('change', '#year_id', function() {		
// var academic_id=$('#academic_year_id').val();
// var year_id = $('#year_id').val();
//   if(academic_id && year_id){
//       $('.load-box').css('display','block');
// 	$.ajax({ 
// 			type: "POST",
// 			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-term-year-batch';?>',
// 			data: {batch_id:academic_id,year_id: year_id}
// 		}).done(function( data ) {
			
// 				$('#term_id').html(data);
//                                   $('.load-box').css('display','none');
			
// 	  });
// 	 }
	 
//  });

</script>