<?php //echo "<pre>";print_r($this->elective);exit;   ?>
<style type="text/css">

    .bold-checkbox{
        position: absolute; top: 12px; font-weight:bold;
    }
    
    body.modal-open .supreme-container{
    display: none;
        
        
}

</style>
<link rel="stylesheet" type="text/css" href="https://printjs-4de6.kxcdn.com/print.min.css">

  
<style>
@media print {
  .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11, .col-sm-12 {
    float: left;
  }
  .col-sm-12 {
    width: 100%;
  }
  .col-sm-11 {
    width: 91.66666667%;
  }
  .col-sm-10 {
    width: 83.33333333%;
  }
  .col-sm-9 {
    width: 75%;
  }
  .col-sm-8 {
    width: 66.66666667%;
  }
  .col-sm-7 {
    width: 58.33333333%;
  }
  .col-sm-6 {
    width: 50%;
  }
  .col-sm-5 {
    width: 41.66666667%;
  }
  .col-sm-4 {
    width: 33.33333333%;
  }
  .col-sm-3 {
    width: 25%;
  }
  .col-sm-2 {
    width: 16.66666667%;
  }
  .col-sm-1 {
    width: 8.33333333%;
  }
  .col-sm-pull-12 {
    right: 100%;
  }
  .col-sm-pull-11 {
    right: 91.66666667%;
  }
  .col-sm-pull-10 {
    right: 83.33333333%;
  }
  .col-sm-pull-9 {
    right: 75%;
  }
  .col-sm-pull-8 {
    right: 66.66666667%;
  }
  .col-sm-pull-7 {
    right: 58.33333333%;
  }
  .col-sm-pull-6 {
    right: 50%;
  }
  .col-sm-pull-5 {
    right: 41.66666667%;
  }
  .col-sm-pull-4 {
    right: 33.33333333%;
  }
  .col-sm-pull-3 {
    right: 25%;
  }
  .col-sm-pull-2 {
    right: 16.66666667%;
  }
  .col-sm-pull-1 {
    right: 8.33333333%;
  }
  .col-sm-pull-0 {
    right: auto;
  }
  .col-sm-push-12 {
    left: 100%;
  }
  .col-sm-push-11 {
    left: 91.66666667%;
  }
  .col-sm-push-10 {
    left: 83.33333333%;
  }
  .col-sm-push-9 {
    left: 75%;
  }
  .col-sm-push-8 {
    left: 66.66666667%;
  }
  .col-sm-push-7 {
    left: 58.33333333%;
  }
  .col-sm-push-6 {
    left: 50%;
  }
  .col-sm-push-5 {
    left: 41.66666667%;
  }
  .col-sm-push-4 {
    left: 33.33333333%;
  }
  .col-sm-push-3 {
    left: 25%;
  }
  .col-sm-push-2 {
    left: 16.66666667%;
  }
  .col-sm-push-1 {
    left: 8.33333333%;
  }
  .col-sm-push-0 {
    left: auto;
  }
  .col-sm-offset-12 {
    margin-left: 100%;
  }
  .col-sm-offset-11 {
    margin-left: 91.66666667%;
  }
  .col-sm-offset-10 {
    margin-left: 83.33333333%;
  }
  .col-sm-offset-9 {
    margin-left: 75%;
  }
  .col-sm-offset-8 {
    margin-left: 66.66666667%;
  }
  .col-sm-offset-7 {
    margin-left: 58.33333333%;
  }
  .col-sm-offset-6 {
    margin-left: 50%;
  }
  .col-sm-offset-5 {
    margin-left: 41.66666667%;
  }
  .col-sm-offset-4 {
    margin-left: 33.33333333%;
  }
  .col-sm-offset-3 {
    margin-left: 25%;
  }
  .col-sm-offset-2 {
    margin-left: 16.66666667%;
  }
  .col-sm-offset-1 {
    margin-left: 8.33333333%;
  }
  .col-sm-offset-0 {
    margin-left: 0%;
  }
  .visible-xs {
    display: none !important;
  }
  .hidden-xs {
    display: block !important;
  }
  table.hidden-xs {
    display: table;
  }
  tr.hidden-xs {
    display: table-row !important;
  }
  th.hidden-xs,
  td.hidden-xs {
    display: table-cell !important;
  }
  .hidden-xs.hidden-print {
    display: none !important;
  }
  .hidden-sm {
    display: none !important;
  }
  .visible-sm {
    display: block !important;
  }
  table.visible-sm {
    display: table;
  }
  tr.visible-sm {
    display: table-row !important;
  }
  th.visible-sm,
  td.visible-sm {
    display: table-cell !important;
  }
       #non-printable { display: none; }
        #printable { display: block; } 
        
  .printdiv:last-child {
     page-break-inside: avoid;
}
}
 @page 
    {
        size:  auto;   /* auto is the initial value */
        margin: 0mm;  /* this affects the margin in the printer settings */
    }


   
    #custom_data_records{
        width:100%;
        text-align: right;
        font-size:1.5em;

    }
    
    .load-box{
        display:none;
        position:absolute;
        width:100%;
        height:100%;
        background:rgba(146,40,46,.5);
        z-index: 999;
    }
    
    .load-box>img{
        position:absolute;
        top:50%;
        left:50%;
        width:40em;
        transform: translate(-50%,-50%);
        
        
    }
    
</style>
<!-- <link href="<?php echo $this->mainconfig['publicpath']; ?>css/custom.css" rel="stylesheet"> -->

<div class="right_col">

    
    
    
        <?php
      
    if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div <?php
            if ($_SESSION['admin_login']['admin_login']->flash_error == 0) {
                echo 'class="alert alert-danger"';
                $_SESSION['admin_login']['admin_login']->flash_error = 1;
            } else {
                echo "class='alert alert-success'";
            }
            ?>>
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php
        }
    }
    ?>
    <?php if ($this->type=='add') { ?>
        <div class="padding-md">
           
             
  
            <?php
//              } else {
            $allowed =  $this->stu_allow;
            $li = '';
            $i=0;
          
           foreach($allowed as $key => $value) {
             
                
               if($value['attend_status']==1){
                   
                    if($value['course_id']==0) {
                      $li.= '<li>Core Course</li>'; 
                   } 
                   else if($value['course_id'] !=0){
                       $course_name = new Application_Model_Course();
                      $coursname1 = $course_name->getRecord($value['course_id']);
                       $li.="<li> {$coursname1['course_name']}</li>";
                   }
               }
                       }  
            
            ?>
            
            <?php if(!empty($li)){ ?>
    <script>
        
   $('body').append(' <div class="modal fade supreme-container" id="AshutoshModal" role="dialog"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal">&times;</button><h4 class="modal-title">Modal Header</h4></div><div class="modal-body"><p><b>Your are not allowed in these papers :- <ol><?php echo $li;?></b></ol></p><p><b> Please contact examination Department</b></p></div><div class="modal-footer"><b>Do you want to proceed ? </b><button type="button" class="btn btn-info" data-dismiss="modal">Yes</button> <a href="<?php echo $this->mainconfig['host']; ?>application/examform" class="btn btn-danger">NO</a></div></div></div></div>');
      $(function(){
       
       $('#AshutoshModal').modal();    
        });
 
        
    </script>
    <?php } ?>
              
            <div class="row examid">
                <div class="col-md-9" id="non-printable">
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye"> Exam Form</i></div>
                    </h3>
                </div>
                
                 <div class="col-md-3" id="non-printable">
                    <h3 class="page-title txt-color-blueDark" >
                        
                    </h3>
                </div>
                    
                    <div class="col-md-12">
                    <div class="panel panel-default masterbox" id="printable">
                        
                          <div class="row">
                               <div class="col-sm-offset-1 col-sm-2">
                                            <div class="form-group disabled">
                                                  <figure class="figure">
                                                <img src="<?php echo $this->mainconfig['publicpath']; ?>images/img.png" alt="..." > <figcaption class="figure-caption text-center"></figcaption>
                                          </figure>
                                            </div>
                                        </div> 
                                    <div class="col-sm-6 employee_class">
                                   <h2 style="text-align: center;">PATNA WOMEN'S COLLEGE </h2>
                                   <h3 style="text-align: center;">Autonomous  </h3>
                                   <h4 style="text-align: center;">PATNA  UNIVERSITY </h4>
                                 <h5 style="text-align: center;"> Examination Form Of Semester End. </h5>
                                </div>
                               
                                     <div class="col-sm-offset-1 col-sm-2">
                                            <div class="form-group disabled">
                                                  <figure class="figure">
                                                <img src="<?php echo $this->mainconfig['host']; ?><?=$this->stu_pic_path;?>" alt="..." class="img-thumbnail"> <figcaption class="figure-caption text-center"><?=$this->fid?></figcaption>
                                          </figure>
                                            </div>
                                        </div> 
                              </div>
<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>save" method="post" data-validate="parsley"  enctype="multipart/form-data">

                            <div class="panel-body">

                                
                                <div class="row">
                                    <div class="row">
                                 
                                       
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled" >
                                                <label class="control-label">Year<span class="asterisk">*</span></label>
                                                <input type="test" name="year" class="form-control chosen-select" value="<?php echo date('Y')?>">
                                            </div>
                                        </div>

                                        <div class="col-sm-4 employee_class">
            <div class="form-group">
              <label class="control-label">Session<span class="asterisk">*</span></label>
    <?php echo $this->form->session;    ?><input type="hidden" name="session_id" id="session_id" value="<?=$this->s_id?>">
    <input type="hidden" name="academic_id" id="academic_id" value="<?=$this->acd_id?>">
    <input type="hidden" name="f_id" id="f_id" value="<?=$this->fid?>">
     <input type="hidden" name="st_id" id="st_id" value="<?=$this->st_id ?>">
            </div>
                                        </div> 
                                        <div class="col-sm-4 employee_class">
            <div class="form-group">
              <label class="control-label">Semester<span class="asterisk">*</span></label>
                <?php 
                $semattend = new Application_Model_BatachSemesterAttendance();
               // echo $this->acd_id;
               // die();
                $data = $semattend->getTermIdByFid($this->fid,$this->acd_id);
              // die();
                //echo $this->form->semester; ?>
              <select name="semester" id="semester"  class="form-control chosen-select" required="required">
                  
                  <option value=""> Select Semester</option>
                  <?php
                  foreach ($data as $key=> $value){ ?>
                  
                  <option value="<?=$value['cmn_terms']?>" <?php if($this->termid === $value['cmn_terms']) { echo 'selected'; }?>> <?=$value['term_name']?> </option>
                      
               <?php    }
                  ?>
              </select>
            </div>
                                        </div>
                            
                                                        
                                    </div>
                                    
                                </div>


                                <div class="row">
                                    <div class="row">   
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Name <span class="asterisk">*</span></label>
                                                <input type="text" name="stu_name" id="stu_name" value="<?=$this->stu_fname?> <?=$this->stu_lname?>" class="form-control" required="true" readonly="readonly" autocomplete="off">
                                            </div>
                                        </div> 
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Father's Name<span class="asterisk">*</span></label>
    <?php echo $this->form->father_fname; ?>
                                            </div>
                                        </div>
                                       
                                       
<!--                                    </div>

                                </div>-->
<!--                                <div class="row">
                                
                                    <div class="row">-->
                                         <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                              <label class="control-label">Date of Birth<span class="asterisk">*</span></label>
    <?php echo $this->form->stu_dob; ?>  
                                            </div>
                                        </div> 
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                              <label class="control-label">Registration Number<span class="asterisk">*</span></label>
    <?php echo $this->form->registration_no; ?>  
                                            </div>
                                        </div> 
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Examination Id<span class="asterisk">*</span></label>
    <?php echo $this->form->exam_roll; ?> 
                                            </div>
                                        </div>
<!--                                        </div>
                                    </div>-->
<!--                                <div class="row">
                                    <div class="row">-->
                                        
                                        

                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Examination<span class="asterisk">*</span></label>
    <?php echo $this->form->examination; ?>
                                            </div>
                                        </div>  

                                        

                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">College<span class="asterisk">*</span></label>
    <?php echo $this->form->college; ?>
                                                <span id="erremail" style="color:red;"></span>
                                            </div>
                                        </div>  
                                        
                                         <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Email<span class="asterisk">*</span></label>
                                                    <input type="email" name="email" id="email" value="" class="form-control" required="true">
                                                <span id="erremail" style="color:red;"></span>
                                            </div>
                                        </div>  
                                        <div class="col-sm-4 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Mobile Number<span class="asterisk">*</span></label>
                                                <input type="number" name="phone" id="phone" maxlength="10" value="" class="form-control" required="true">
                                                <span id="erremail" style="color:red;"></span>
                                            </div>
                                        </div>  

                                   </div>
                                   
                                </div>  
                                <div class="row">   
                                    <div class="col-sm-3"><h4><span style="color:#777;">Subjects of Examination </span></h4></div>
                                </div>

                                <div class="row" id="getcourse">
                                    <div class="row">
                                        
                                     <?php 
                                     //die();
//                                     $i =0;
//                                     foreach($this->course_cat as $cat_index => $cat_value ){ 
//                                         $str = '';
//                                         $paper_val = '';
                                         ?> 
                                        
                                        <?php 
                                        
//                                        foreach($this->core_details_arr as $core_index => $core_val){
//                                            if($core_val['cc_name'] == $cat_value ){
//                                                $str[]=$core_val['ct_name'];
//                                                }
//                                            }
//                                            if($i == 0){
//                                            foreach($this->core_details_arr as $core_index => $core_val){
//                                                if($core_val['ge_id']==0){
//                                                    $paper_val[] = $core_val['course_code'];
//                                                }
//                                            }
//                                            $i++;
//                                            }
                                            ?>
                                        
                                        <div class="col-sm-6 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label"><?=$cat_value;?><span class="asterisk">*</span></label>
                                                <input type="text" name="course_group[]" value ="<?=implode(',',$str);?>" class="form-control" readonly="readonly"  />
                                            </div>
                                        </div> 
                                             <?php 
                                            
                                             foreach($this->course_val as $Course_index => $course_val){
                                                 
                                            if($this->ge_arr[$cat_index] == $course_val['ge_id'] && $course_val['ge_id'] !=0  )                                             {$course_model = new Application_Model_Course();
                                                $result_course = $course_model->getRecord($course_val['electives']);
                                               
                                                $paper_val[] = $result_course['course_code'];}
                                             }
                                            ?>
                                        <div class="col-sm-6 employee_class">
                                            <div class="form-group disabled">
                                                <label class="control-label">Papers <span class="asterisk">*</span></label>
                                                <input type ="text" name="paper_name[]" value="<?=implode(',',$paper_val);?>" class="form-control" readonly="readonly" />           
                                            </div>
                                        </div>
                                     <?php //} ?>

                                    </div>
                                    


                                     <div class="col-sm-6 employee_class">
                                        <div class="form-group disabled">
                                            <label class="control-label">Atom Transaction ID and Transaction Date :  </label>
                                            <span id="erremail1" style="color:red;"></span>
                                        </div>
                                    </div>
                                    </div>
                                    <div class="col-sm-12"><h4><span style="color:#777;">
                                <p> To,</p>
                                  <p>The Principal Madam,  </p>

                                   <p>I request for permission to appear at the <?=$this->semester;?> Examination to be held in 2019</p>

                                      <p> Centre of Examination : Patna Women's College  </p>     

                                    <p>Examination Roll No. : <?=$this->exam_roll;?>  </p>

                                     <p>Date of Commencement of Examination December <?=date('Y')?>.</p>

                                        <p style="float: right;">Full Signature of the Candidate</p>
                                </span></h4></div>
                                </div>
                            </div>
                </div> 
                <div class="panel-footer">                                  
                    <div class="row">
                        <div class="col-sm-7 col-sm-offset-5">
                            <?php //if ($this->type == 'add' && $this->extdate >= $curdate  && $this->payactivaion == 1) { ?> 
                                <div style="float:left;margin-right:2px;">
                                    <input type="submit" class="btn btn-primary submit" name="submit" value="Save">
                                </div>
                             <?php //} ?>
                        </div>
                    </div>
                </div>
                   </form>

            </div>
        </div><!-- /panel -->
    </div>           
 

    <?php } elseif($this->type=='otpverify') {  ?>
    <div class="examid">
      
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars"> Verify OTP</i>
<?=$this->mssg;?>
                    </h3>
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">   
                </div>
            </div>

            <div class="x_panel">
  <div class="load-box">
             <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
        </div>
                <div class="x_title">
                    <div class="row">
                        <div class="col-sm-5">
                            <h2 class="title1">Exam Form Using Registration ID</h2></div>
                        
                      
                    <div class="clearfix"></div>
                </div>
                     </div>
               
                <div class="x_content">

                    <div class="padding-md clearfix">
                        
                        <div class="table-responsive" id="studentData"> 


<!--///////   raushan  -->
<div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-sm-4 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Admission Form No . <span class="asterisk">*</span></label>
                                            <?php echo $this->form->stu_id; ?>
                                        </div>
                                    </div>
                                    
                                     <div class="col-sm-4 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Enter Your Otp . <span class="asterisk">*</span></label>
                                            <?php echo $this->form->otp; ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-4 employee_class">
                                        
                                        <label></label>
                                        <div class="form-group" >
                                            <input type="submit" name="search" class="btn btn-info" value="Verify And proceed">
                                    </div>
                                        <label>For any query please send email on : support@finessewebtech.com with details infromation and your form id </label>
                                    </div>



                                </div>
                            </div>
                        </form>

                    </div></div>
   
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div>
    
<?php } else { ?>
 
    <div class="examid">
    <!-- widget grid -->
    <div class="row">    
            <div class="col-sm-12">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Student Examination Form</i>
<?=$this->mssg;?>
                    </h3>
                </div>

                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">   
                </div>
            </div>

            <div class="x_panel col-sm-12 masterbox">
                <div class="x_title">
                    <div class="row">
                        <div class="col-sm-5">
                            <h2 class="title1">Exam Form Using Registration ID</h2></div>
                        
                      
                    <div class="clearfix"></div>
                </div>
                     </div>
               
                <div class="x_content">

                    <div class="padding-md clearfix">
                        
                        <div class="table-responsive" id="studentData"> 


<!--///////   raushan  -->
<div class="panel panel-default">
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" enctype="multipart/form-data" >

                            <div class="panel-body">
                                <div class="row">

                                    <div class="col-sm-4 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Admission Form No . <span class="asterisk">*</span></label>
                                            <?php echo $this->form->stu_id; ?>
                                        </div>
                                    </div>
                                     <div class="col-sm-4 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Mobile Number . <span class="asterisk">*</span></label>
                                            <?php echo $this->form->phone; ?>
                                        </div>
                                    </div>
                                    
                                     <div class="col-sm-4 employee_class">
                                        <div class="form-group" >
                                            <label  class="control-label" >Email Id . <span class="asterisk">*</span></label>
                                           <input type="email" name="email" id="email" value="" class="form-control" required="true">
                                        </div>
                                      </div>
                                    <div class="col-sm-6 employee_class">
                                        
                                        <label></label>
                                        <div class="form-group" >
                                            <input type="submit" name="search" class="btn btn-info" value="Send Otp">
                                    </div>
                                        <label></label>
                                        <div class="form-group" >
                                            <a href="<?php echo $this->mainconfig['host']; ?>application/examform/type/otpverify" class="btn btn-primary"> I Already have the Otp</a>
                                        </div>  
                                    </div>



                                </div>
                            </div>
                        </form>

                    </div></div>
   
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
       
    </div><!-- /.padding-md --> 
    </div>    
<?php } ?>



<script src="<?php echo $this->mainconfig['publicpath']; ?>js/customradio.js"></script> <script>
    $(document).ready(function() {
  
      var aca =  $('#academic_id').val();
      var sem =  $('#semester').val();
      var sid =  $('#st_id').val();
      
       // alert(sem);
        $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'application/ajax-get-student-course'; ?>',
                data: {batch_id: aca, term_id: sem,sid:sid}
            }).done(function (data) {
              //alert(data);
               $('#getcourse').html(data);
            });

    $('#semester').change(function(){
      var aca =  $('#academic_id').val();
      var sem =  $('#semester').val();
      var sid =  $('#st_id').val();
      
       // alert(sem);
        $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'application/ajax-get-student-course'; ?>',
                data: {batch_id: aca, term_id: sem,sid:sid}
            }).done(function (data) {
              //alert(data);
               $('#getcourse').html(data);
            });
    });
});
</script>


