<style>
.panel-body{padding: 15px 10px 0 10px;}
.form-control{width:95%;}
textarea{resize:none;}
</style>

<?php
error_reporting(0);
$date = new Zend_Date();
?>
<tr class="feeclose">
<td colspan="6">
<div class="purchase-quatation-items" style="display: block;"><div class="col-sm-12 " >
      <div id="">  
<div class="panel panel-default bor" >
 <div class="panel-body" style="">
     <div> 
         <div class="col-sm-12" width="99%"><center>
                 <div class="form-group bor" style="">
                     
                     <label class="control-label"><strong><h4 style="text-align:center;">Fee Details</h4></strong></label>
                 </div></center>
         </div>
		
     </div>
    </div>
     <div class="row" style="margin-bottom:5px;" >
         <div class="col-sm-12">
             <div class="form-group bor" >
                 <table class="table table-striped table-bordered mb30 table bulk_action" border="1" >
				 <thead>
                     <tr align="center">
                         <th rowspan="2" bgcolor="#f7ffe6" style="text-align:center;">S.No.</th>
						 <th rowspan="2" bgcolor="#f7ffe6" style="text-align:center;">Particulars</th> 
						 <th colspan="3" bgcolor="#f7ffe6" style="text-align:center;">First Year</th> 
                         <th colspan="2" bgcolor="#f7ffe6" style="text-align:center;">Second Year</th>
						 <th rowspan="3" bgcolor="#f7ffe6" style="text-align:center;">Total (Rs.)</th>
							</tr>
							<tr>
						 <th style="text-align:center;">TERM 1</th>
						 <th style="text-align:center;">TERM 2</th>
                         <th style="text-align:center;">TERM 3</th>
						 <th style="text-align:center;">TERM 4</th> 
						 <th style="text-align:center;">TERM 5</th> 
                     </tr>
					 <tr>
					 <td colspan="2" bgcolor="#ffffcc">Due Date for Payment</td>
					 <?php $items_result=$this->result1; 
					 //echo'<pre>';print_r($items_result);die;
					 if(!empty($items_result)){
                    // foreach($items_result as $k=>$i_results) { ?>
					  <td bgcolor="#ffffcc"><?php echo $items_result['t1_date'];?></td>
					  <td bgcolor="#ffffcc"><?php echo $items_result['t2_date'];?></td>
					  <td bgcolor="#ffffcc"><?php echo $items_result['t3_date'];?></td>
					  <td bgcolor="#ffffcc"><?php echo $items_result['t4_date'];?></td>
					  <td bgcolor="#ffffcc"><?php echo $items_result['t5_date'];?></td>
					 
					 <?php //}
					 } else{ ?>
					 
					 <td bgcolor="#ffffcc"></td>
					 <td bgcolor="#ffffcc"></td>
					 <td bgcolor="#ffffcc"></td>
					 <td bgcolor="#ffffcc"></td>
					 <td bgcolor="#ffffcc"></td>
					 <?php } ?>
					 </tr>
						</thead>
                     <tbody>
                         <?php
                        // print_r($this->academics_data);
                        // $i=1;
                       $letters = array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z');
                       $i=0;
					  				
                     //echo '<pre>'; print_r($this->Feeheads_data['feehead_name']);						
					 if(($this->Category_data) >0){
							$fee_head = $this->Feeheads_data;
						//echo '<pre>'; print_r($this->Category_data['feecategory_id']); 
                       foreach ($this->Category_data as $key=>$categories){ 
					 ?>
								
				       	<tr>
						   <!-- <td align="center"><?php //echo $letters[$i];?></td> -->
						   <td align="left" colspan="7" bgcolor="#f7ffe6"><?php 
						  // if($categories['category_id'] == $fee_head[$key]['feecategory_id']){
						   echo $letters[$i].'. '.$categories['category_name'].' '.'(Rs.)';
						  // } ?>
						   <input type="hidden" name="terms[category_id][]" id="category_id" value="<?php echo $categories['category_id'];?>" />
						   </td> 
						   <td bgcolor="#f7ffe6" ></td>
						  
						</tr>
						<?php $j=1;
						$term1_cat_tot=0;
						$term2_cat_tot=0;
						$term3_cat_tot=0;
						$term4_cat_tot=0;
						$term5_cat_tot=0;
						foreach($this->Feeheads_data as $keys=>$vals){
						//print_r($
						if($categories['category_id'] == $vals['feecategory_id']){ ?>
						<tr>
						<td align="center"><?php echo $j;?><input type="hidden" name="terms[count][]" value="<?php echo $j;?>"/></td>
						<td><?php echo $vals['feehead_name'] ;?><input type="hidden" name="terms[feehead_id<?php echo $categories['category_id'];?><?php echo $j;?>][]" id="feehead_id<?php echo $j;?>" value="<?php echo $vals['feehead_id'];?>" /></td>
						<?php if(!empty($this->result1)){
						$TermItems_model = new Application_Model_FeeStructureTermItems();
							$cat_ids = $categories['category_id'];
							$fhead_ids = $vals['feehead_id'];
						?>
						
						<td>
						<?php $term1_result = $TermItems_model->getFeesRecords($this->structure_id,$cat_ids,$fhead_ids,1); ?>
						<?php $term1_cat_tot +=$term1_result['fees'];
						echo $term1_result['fees'];?></td>
						
						<td><?php $term2_result = $TermItems_model->getFeesRecords($this->structure_id,$cat_ids,$fhead_ids,2); ?>
						<?php $term2_cat_tot +=$term2_result['fees'];
						echo $term2_result['fees'];?></td>
						
						<td><?php $term3_result = $TermItems_model->getFeesRecords($this->structure_id,$cat_ids,$fhead_ids,3); ?>
						<?php $term3_cat_tot +=$term3_result['fees'];
						echo $term3_result['fees'];?></td>
						
						<td><?php $term4_result = $TermItems_model->getFeesRecords($this->structure_id,$cat_ids,$fhead_ids,4); ?>
						<?php $term4_cat_tot +=$term4_result['fees'];
						echo $term4_result['fees'];?></td>
						
						<td><?php $term5_result = $TermItems_model->getFeesRecords($this->structure_id,$cat_ids,$fhead_ids,5); ?>
						<?php $term5_cat_tot +=$term5_result['fees'];
						echo $term5_result['fees'];?></td>
						
						<td style="text-align:center;"><?php echo $term1_result['feeheads_total'];?> 
						</td>
						
						
						
						
						
						<?php //}
                        } else { 
						?>						
						<td>
						<input type="text" name="term_<?php echo $categories['category_id'];?>_<?php echo $vals['feehead_id'];?>_1" id ="term<?php echo $j;?>1" class="form-control term1<?php echo $categories['category_id']; ?> term" onchange="select_term1_fees(this.val,<?php echo $j;?>,<?php echo $i;?>,<?php echo $categories['category_id'];?>)" style="text-align:right;" value="0"/></td>
						<td><input type="text" name="term_<?php echo $categories['category_id'];?>_<?php echo $vals['feehead_id'];?>_2" id ="term<?php echo $j;?>2" class="form-control term2<?php echo $categories['category_id']; ?>" onchange="select_term2_fees(this.val,<?php echo $j;?>,<?php echo $i;?>,<?php echo $categories['category_id'];?>)" style="text-align:right;" value="0" /></td>
						<td><input type="text" name="term_<?php echo $categories['category_id'];?>_<?php echo $vals['feehead_id'];?>_3" id ="term<?php echo $j;?>3" class="form-control term3<?php echo $categories['category_id']; ?>" onchange="select_term3_fees(this.val,<?php echo $j;?>,<?php echo $i;?>,<?php echo $categories['category_id'];?>)" style="text-align:right;" value="0"/></td>
						<td><input type="text" name="term_<?php echo $categories['category_id'];?>_<?php echo $vals['feehead_id'];?>_4" id ="term<?php echo $j;?>4" class="form-control term4<?php echo $categories['category_id']; ?>" onchange="select_term4_fees(this.val,<?php echo $j;?>,<?php echo $i;?>,<?php echo $categories['category_id'];?>)" style="text-align:right;"  value="0" /></td>
						<td><input type="text" name="term_<?php echo $categories['category_id'];?>_<?php echo $vals['feehead_id'];?>_5" id ="term<?php echo $j;?>5" class="form-control term5<?php echo $categories['category_id']; ?>" onchange="select_term5_fees(this.val,<?php echo $j;?>,<?php echo $i;?>,<?php echo $categories['category_id'];?>)" style="text-align:right;" value="0"/></td>
						<td><span id="feeheads_total<?php echo $j;?>">0</span>
						<input type="hidden" name="terms[feeheads_total_val<?php echo $categories['category_id'];?>][]" id="feeheads_total_val<?php echo $j;?>" /> 
						</td>
						<?php } ?>
						</tr>
						
						<?php  } 
						     $j++;
						   } ?>
						   <tr>
						<td bgcolor="#ccf5ff"></td>
						<td bgcolor="#ccf5ff" style="text-align:right;"><?php echo 'Total '.$letters[$i].' (Rs.)';?></td>
						<?php $TermItems_model = new Application_Model_FeeStructureTermItems();
							$category_id = $categories['category_id'];
							$terms1_total=$TermItems_model->getFeeTermTotals($this->structure_id,$category_id,1);
							?>
						<td bgcolor="#ccf5ff" style="text-align:left;">
						<?php echo $term1_cat_tot;?></td>
						
						<td bgcolor="#ccf5ff" style="text-align:left;"><?php
						echo $term2_cat_tot;?></td>
						<td bgcolor="#ccf5ff" style="text-align:left;"><?php echo $term3_cat_tot;?></td>
						<td bgcolor="#ccf5ff" style="text-align:left;"><?php echo $term4_cat_tot;?></td>
						<td bgcolor="#ccf5ff" style="text-align:left;"><?php echo $term5_cat_tot;?></td>
						<td bgcolor="#ccf5ff" style="text-align:center;"> <?php
						?><?php echo $terms1_total['cat_row_total']; ?></td>
						</tr>
						<input type="hidden" name="terms[count_i][]" id="count_i" value="<?php echo $i;?>" />
								 <?php  $i++; 
										 
								  } ?>
						
		<tr>
						<td bgcolor="#b3ecff"></td>
						<td bgcolor="#b3ecff" style="text-align:right;"><?php 
						$lets = "";
						$cats = $categories['category_id'].length;
						
						for($l=0;$l < $cats;$l++){
						  $lets = $lets.$letters[$l].'+';
						  
						}
						 echo 'Grand Total ('.rtrim($lets,'+').') (Rs.)';
						
						?></td>
						 <?php $items_result=$this->result1; 
								if(!empty($items_result)){
								 ?>	
						<td bgcolor="#b3ecff" style="text-align:left;"><?php echo $items_result['grand_term1_result'];?></td>
						
						<td bgcolor="#b3ecff" style="text-align:left;"><?php echo $items_result['grand_term2_result'];?></td>
						
						<td bgcolor="#b3ecff" style="text-align:left;"><?php echo $items_result['grand_term3_result'];?></td>
						
						<td bgcolor="#b3ecff" style="text-align:left;"><?php echo $items_result['grand_term4_result'];?></td>
						
						<td bgcolor="#b3ecff" style="text-align:left;"><?php echo $items_result['grand_term5_result'];?></td>
						
						<td bgcolor="#b3ecff" style="text-align:center;"><?php echo $items_result['total_grand_value'];?></td>
						
						<?php  }
						else{ ?>
						<td bgcolor="#b3ecff" style="text-align:right;"><span id="term1_grandtotal_" ></span>
						<input type="hidden" name="terms_fee[grand_result1][]" id="grand_result1" value="0"/></td>
						<td bgcolor="#b3ecff" style="text-align:right;"><span id="term2_grandtotal_" ></span>
						<input type="hidden" name="terms_fee[grand_result2][]" id="grand_result2" value="0" /></td>
						<td bgcolor="#b3ecff" style="text-align:right;"><span id="term3_grandtotal_" ></span>
						<input type="hidden" name="terms_fee[grand_result3][]" id="grand_result3" value="0" /></td>
						<td bgcolor="#b3ecff" style="text-align:right;"><span id="term4_grandtotal_" ></span>
						<input type="hidden" name="terms_fee[grand_result4][]" id="grand_result4" value="0" /></td>
						<td bgcolor="#b3ecff" style="text-align:right;"><span id="term5_grandtotal_" ></span>
						<input type="hidden" name="terms_fee[grand_result5][]" id="grand_result5" value="0" /></td>
						<td bgcolor="#b3ecff" style="text-align:center;"><span id="grand_total" ></span>
						<input type="hidden" name="terms_fee[grandtotal_total][]" id="grandtotal_total" value="0"/></td>
						<?php } ?>
						
						</tr>
								 <?php 
								 }  else { ?>
							 <tr><td colspan="8"><center><strong>No Data Available</strong></center></td></tr>  
								 <?php } ?>	
					 </tbody>
                 </table>
             </div>
         </div>
     </div>

    
     </div>
 </div>
</div>

       </div>
 </div>
</td>
</tr>

<style type="text/css">
/*  .bor {border:1px solid #ccc; } */
    .table { margin-bottom: 0px !important;width: 100%;}
    .employee_class {margin-left: 4% !important;margin-right: 4% !important;}
    .panel-footer {padding: 5px;}
    .panel {margin-bottom: 10px !important;}
	a:hover{cursor:pointer;}
</style>


