<?php 
//echo "<pre>";print_r( $this->weightage);die;
?>
<style>
    input { 
    text-align: center; 
}

input:focus{
    border:2px solid #00ed22;
    
}
    </style>
<div style="overflow-x:scroll">
<div class="padding-md clearfix">
    <div class="col-sm-0" style="float:right;">
        <a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a>
    </div>
<table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable-grade" id="dataTable">
						
    <thead>
        <tr>
            <th rowspan="2">S.No.</th>
            <th rowspan="2">Participants Name</th>
            <th rowspan="2">Father Name</th>
            <th rowspan="2">Batch</th>
            <th rowspan="2"> UID</th>
            <th rowspan="2"> Reg. No.</th>
            <th rowspan="2">Exam Roll. No.</th>
            <th>Component</th>
            <?php foreach($this->weightage as $k => $val) { 
                
                ?>
            <th><?php $Component_model = new Application_Model_Component(); 
            
            
            echo $Component_model->getRecord($val['component_id'])['component']; 
            ?>
            </th>
                <input type="text" style="display:none" name="grade[component_id][]" id="grade" value="<?php echo $val['eci_id'];?>"/>
            <?php } ?>
            <!--<th rowspan="2">Penalties For Absence</th>-->
        </tr>
        <tr>
            <th>Weightage</th>
            <?php foreach($this->weightage as $k => $val) {
                 if($val["weightage"]==250)
                    $this->min_pass_percent = 50;
                else if($val["weightage"]==25)
                    $this->min_pass_percent = 50;
                
                ?>
            <?php  $passmarks = ((int)$this->min_pass_percent/100)*(int)$val["weightage"];?>
                <th style="display:none;"><span style="display:none"><?=$Component_model->getRecord($val['component_id'])['component'].' - ';?></span><?php echo $val["weightage"]; ?> / <?=$passmarks;?></th>
                <th id='total_<?=$k;?>' class="no_print"><?php echo $val["weightage"]; ?> / <?=$passmarks;?></th >
            <?php } ?>
        </tr>
    </thead>
    <tbody>
        <?php if(!empty($this->result))	 {  $i = 1;  

        foreach($this->result as $k => $result) { 
        ?>
        <tr>
            <td><?php echo $i;
                $i++; ?>
            </td>
		<td><?php echo $result['student_name'];?></td> 
                <input type="hidden" name="grade[student_id][]" id="student_id" value="<?php echo $result['student_id']; ?>" />
                 <input type="hidden" name="grade[academic_id_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" id="term_id1" value="<?php echo $result['academic_id']; ?>" />
            <input type="hidden" name="grade[term_id_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" id="academic_id1" value="<?php echo $result['term_id']; ?>" />
            <td><?php echo $result['father_name'];?></td> 		
            <td><?php echo $result['short_code'];?></td>
            <td><?php echo $result['stu_id'];?></td>
            <td><?php echo $result['reg_no'];?></td>
            <td><?php echo $result['exam_roll'];?></td>
		<td></td>	
                <?php
		$grade_value=explode(",",$result['grade_value']);
		$number_value=explode(",",$result['number_value']);
                $td = 1;
		foreach ($grade_value as $g_k => $val){	?>
                 <td style="display:none;"><?=strlen($number_value[$g_k])==0?empty($val)?0:$val:$number_value[$g_k];?></td> 
                <td>
                    <table>
                        <tr>
                            <td class="no_print"> <select name="grade[grade_value_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" <?php if($val=='F'){echo 'style="border:2px solid #ff0000;"'; } ?> >
                                     <option value="">-Select-</option>
                                     <?php
                                     foreach($this->ref_grades as $row){
                                         //echo "<pre>";print_r($row);exit;
                                         $selected = '';
                                         if($row['letter_grade'] == $val){
                                             $selected = 'selected="selected"';
                                         }
                                         echo '<option '.$selected.' value="'.$row['letter_grade'].'">'.$row['letter_grade'].'</option>';
                                     }
                                     ?> </select></td>
                                <td>
                                    <?php 
                                    //===logic for tab index
                                    ${"tabindex_$g_k"} = (($g_k + 1) * count($this->result)) + $k  ?>
                                <input type="text" autocomplete="off" data-id='#total_<?=$g_k;?>' style="height:1.5em;" tabindex="<?=${"tabindex_$g_k"};?>" value="<?php echo $number_value[$g_k];?>" name="grade[number_value_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]"  size='3' maxlength="5"/>
                            </td>
                        </tr>
                    </table>
                </td> 
                <!--<td><input type="text" name="grade[grade_value_<?php echo $result['student_id']; ?>][]"  value="<?php                     echo $val;?>" />
                </td>-->
                
		<?php $td++; }
                
               
                
            
                
                    $penalty_value = 0;
                    if(!empty($this->penalty_all_items)){
                        foreach($this->penalty_all_items as $key => $penalty){
                            if($penalty['student_id'] == $result['student_id']){
                                $penalty_courses = explode(',',$penalty['academic_courses']);
                                $penalty_absences = explode(',',$penalty['absence']);
                            if(in_array($this->course_id,$penalty_courses)){//If course id exists, fetch index position
                                $course_id_pos = array_search($this->course_id, $penalty_courses);//Find the index position of course id

                                $penalty_value = $penalty_absences[$course_id_pos];
                                if(empty($penalty_value)){
                                    $penalty_value = 0;
                                }
                            }
                            break;
                        }}
                    }
                ?>  
                <!---<td><input type="text" name="student_penalties_<?php echo $result['student_id']; ?>"  value="<?php echo $penalty_value                      ; ?>" />
                </td>-->
        </tr>
	<?php }  } else { ?>
        <?php
          $i = 1;
        ?>
        <?php foreach($this->category_data as $key=>$val){ ?>
        <tr>
            <td><?php echo $i;
                 $i++; ?>
            </td>
            <td><?php echo $val['students'];?></td> 
            <input type="hidden" name="grade[student_id][]" id="student_id" value="<?php echo $val['student_id']; ?>" />
            <input type="hidden" name="grade[academic_id_<?php echo $val['student_id']; ?>][]" id="term_id1" value="<?php echo $val['academic_id']; ?>" />
            <input type="hidden" name="grade[term_id_<?php echo $val['student_id']; ?>][]" id="academic_id1" value="<?php echo $val['term_id']; ?>" />
            <td><?php echo $val['father_name'];?></td> 		
            <td><?php echo $val['short_code'];?></td>
            <td><?php echo $val['stu_id'];?></td>
            <td><?php echo $val['reg_no'];?></td>
            <td><?php echo $val['exam_roll'];?></td>
            <td></td>
            <?php foreach($this->weightage as $k => $val1) { ?>
            <td style="display:none;">--</td>
            <td class="text-center">
                
                <table>
                    <tr>
                        <td>  <select name="grade[grade_value_<?php echo $val['student_id']; ?>][]" >
                            <option value="">-Select-</option>
                                <?php
                                foreach($this->ref_grades as $row){
                                      //echo "<pre>";print_r($this->ref_grades);
                                    echo '<option value="'.$row['letter_grade'].'">'.$row['letter_grade'].'</option>';
                                }
                                ?>
                           </select>
                        </td>
                        
                        <td>
                            
                            
                            <?php 
                                    //===logic for tab index
                                    ${"tabindex_$k"} = (($k + 1) * count($this->category_data)) + $key  ?>
                            <input type="text" value="" autocomplete="off" style="height:1.5em;"  data-id='#total_<?=$k;?>' tabindex="<?=${"tabindex_$k"};?>" name="grade[number_value_<?php echo $val['student_id']; ?>][]"  size='3' maxlength="5"/>
                            
                        </td>
                    </tr>
                    
                </table>
                
                
                
                
            </td>
            <!--<td><input type="text" name="grade[grade_value_<?php echo $val['student_id']; ?>][]" id="grade" /></td>-->
            <?php }  ?>

            <!--<td><input type="text" name="student_penalties_<?php echo $val['student_id']; ?>"  value="0" /></td>-->
        </tr>
        <?php } } ?>
    </tbody>
</table>
</div>
</div>
<script>
    //modifiedDataTable();
    //modifiedDataTable(true);
    $(document).ready(function() {
    
   
        
    });
    $('#print').click(function(){
        window.print();
    });
    
   // $('div.dt-buttons').hide();
</script>


<script>	
<?php
//$GlobalSettings_model = new Application_Model_GlobalSettings();
//$settings1 = $GlobalSettings_model->getDetailBySystemName('PERCENTCONTENT_FOR_REFRENCE_GRADE');
//echo 'var percent_arr = '.$settings1['gs_content'].";\n";
?>


$('input[type="text"]').bind('keyup blur',function(){
    var node = $(this);
    node.val(node.val().replace(/[^0-9]/g,'') );
});


    $('body').on('blur','input[type="text"]',function(){
      //  alert('hello');
      //  
   //  percent_arr  = JSON.parse(percent_arr);
                $('input[name^="grade[number_value_"]').each(function(){
                    if($(this).attr('style') != 'border:2px solid #ff0000' ){
                    $(this).removeAttr('style');
                 $(this).parent('td').prev().children('select').removeAttr('style');}
                });
                
                var session_id = $('#session').val();
                
                var total = String($($(this).data('id')).text());
                var tot_str = total.split('/');
                total = parseFloat(tot_str[0]);
                var num  = $(this).val()
                var input = $(this);
                
                
                
                
                 $(this).attr('style','border:2px solid #00ed22;');
                if(num > total){
                    
                    alert(num + " should not be greater than your respective component !")
                    $(this).val('');
                    input.parent('td').prev().children('select').val('');
                    //$(this).attr('placeholder',num);
                    $(this).attr('style','border:2px solid #ff0000');
                    $(this).focus();
                    return false;
                }
                
               num = Math.round((parseFloat(num)/total)*100);
                var deg = $('#degree_id').val();
        if(num){ 
         
                    $.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-Refgrade';?>',
			data: {num: num,deg:deg,session:session_id}
		}).done(function( data ) {
			var result = data;
                        if(result){
                            input.parent('td').prev().children('select').val(result);
                           
                            if( result.toUpperCase()== 'F')
                            input.parent('td').prev().children('select').attr('style','border:2px solid #ff0000');
                        else{
                            input.parent('td').prev().children('select').attr('style','border:2px solid #00ed22');
                        }
                    }
                    else{
                     input.parent('td').prev().children('select').val("");
                 }
                           
                }); 
        
        }
        if(input.val() == '' && input.parent('td').prev().children('select').val() !='NA' && input.parent('td').prev().children('select').val() !='Ab')
        input.parent('td').prev().children('select').val("");
    });   
         setDatatables();


</script>