
<style>
    @media print {
                    table td:nth-child(6)
                     {
                         display:none;
                     }
                     table th:nth-child(6)
                     {
                         display:none;
                     }
                      *{
                        visibility:hidden;
                     }
                     table,th,td 
                     {
                         visibility:visible;                    
                     } 
                     .title1
                     {
                        visibility:visible; 
                     }
                }
</style>

<div class="right_col">
    <?php if ($this->type) { ?>
        <div class="padding-md ">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Review and Publish - Grade Allocations</i></div>
                    </h3>
                    <div class="panel panel-default">
                        
                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
                            

                            <div class="panel-body">
                                <div class="row">
                                        <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Session</label>
                                            <?php echo $this->form->session; ?>
                                        </div>
                                    </div>	
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Semester<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cmn_terms; ?>
                                        </div>
                                    </div>	
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Department<span class="asterisk">*</span></label>
                                            <?php echo $this->form->department_id; ?>
                                        </div>
                                    </div>
                                    
                                     <div class=" col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Degree</label>
                                            <?php echo $this->form->degree_id; ?>
                                        </div>
                                    </div>
                                    
                                    
                                   	
                                </div>
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly /></div>
                                    </div>
                                    
                                </div>
                                <div class="row">
                                    
                                     <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Faculty<span class="asterisk">*</span></label>
                                            <?php echo $this->form->employee_id; ?>
                                        </div>
                                    </div>
                                    
                                     <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Course Category<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cc_id; ?>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Course Group<span class="asterisk">*</span></label>
                                            <?php echo $this->form->ge; ?>
                                        </div>
                                    </div>
                                    <div id="course_ids"></div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-12 text-center">
                                        <h4 class="text-danger"><strong>**Published Grade Cannot be Modified.<br>
                                                <small class='text-danger'><b>(Note:</b>&nbsp Course Listed only with Created Evaluation Components.<b>)</b></small></strong></h4>
                                    </div>
                                </div>

                                <div class="">
                                    <div id="grade_details"></div>
                                </div>
                            </div>
                            <div class="panel-footer">									
                                <div class="row">
                                    <div class="col-sm-7 col-sm-offset-5">
                                        <?php if ($this->type == 'add') { ?> 
                                            <div style="float:left;margin-right:2px;">
                                                <button class="btn btn-danger submit">Publish</button>
                                            </div>
                                            <div style="float:left;padding:0px 10px;">

                                            </div>
                                        <?php } else { ?>
                                            <div >
                                                <button class="btn btn-primary submit">Update</button>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                    </div>
                    </form>
                </div><!-- /panel -->
            </div><!-- /.col-->				
        </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

    <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Review and Publish - Grade Allocations </i>

                    </h3>
                </div>
                <?php
                //  if(in_array($this->role_id, $this->administrator_role)){
                ?>		
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>grade-allocation/grade-allocation-report/type/add">Add </a>
                </div>
                <?php
                //}
                ?>
            </div>

            <div class="x_panel">

                <div class="x_title">
                    <h2 class="title1">Review & Publish - Grade Allocations</h2>
                    
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="col-sm-0" style="float:right;">
                                   <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host']; ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id; ?>">Print</a>--><a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a></div>
                        
                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
                            <thead>
                                <tr>
                                    <th>S.  No.</th>
                                    <th>Batch</th>
                                    <th>Term</th>
                                    <th>Course</th>
                                    <th>Faculty</th>
                                    <th>Action</th>

                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    
                                    foreach ($this->paginator as $results) {
                                        
                                        ?>
                                        <tr class="orderid<?php echo $results['grade_report_id']; ?>">
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['academic_year']; ?></td>
                                            <td><?php echo $results['term_name']; ?></td>
                                            <td><?= $results['course_id']; ?></td>
                                            <?php $HRMModel_model = new Application_Model_HRMModel();
                                            $emp = $HRMModel_model->getEmployeeData($results['employee_id']);
                                            ?>
                                            <td><?php echo $emp['empl_firstname']; ?></td>
            <?php /* 	
              <td><a href="<?php echo $this->mainconfig['host']; ?>grade-allocation/grade-allocation-report/type/edit/id/<?php echo $results['grade_report_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>grade-allocation/grade-allocation-report/type/delete/id/<?php echo $results['grade_report_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td> */ ?>
                                            <td><a  class="order_view" data-id="<?= $results['course_id']; ?>" orderid="<?php echo $results['grade_report_id']; ?>" > View </a></td>

                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>
    $(document).ready(function () {
        $('#batch').hide();
    });
    $('body').on('change', '#department_id', function () {
        var department_id = $('#department_id').val();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-employee'; ?>',
            data: {department_id: department_id}
        }).done(function (data) {

            $('#employee_id').empty('');
            $('#employee_id').html(data);

        })
    })
    $('body').on('change', '#cc_id,#ge', function () {
        var employee_id = $('#employee_id').val();
        var department_id = $('#department_id').val();
        var session_id = $('#session').val();
        var grade_allocate_id = '';
        var term_id = $('#cmn_terms').val();
        var cc_id = $('#cc_id').val();
        var ge = $('#ge').val();

        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-courses-edit-new'; ?>',
            data: {employee_id: employee_id, department_id: department_id, session_id: session_id, term_id: term_id, grade_allocate_id: grade_allocate_id,ct_id: cc_id,ge_id : ge,session:session_id }
        }).done(function (data) {

            $('#course_ids').empty('');
            $('#course_ids').html(data);
            $('#grade_details').empty();
            

        });

    });


    $('body').on('change', '#course_id', function () {
        var employee_id = $('#employee_id').val();
        var department_id = $('#department_id').val();
        var academic_year_id = $('#session').val();
        var term_id = $('#cmn_terms').val();
        var course_id = $('#course_id').val();
            var cc_id = $('#cc_id').val();
            var ge = $('#ge').val();
            
//                    $.ajax({
//            type: "POST",
//            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-employee-validation-new'; ?>',
//            data: {session_id: academic_year_id, department_id: department_id, employee_id: employee_id, cmn_term: term_id, ge: cc_id}
//        }).done(function (data) {
//            var result = $.parseJSON(data);
//            if (result != 0) {
//                alert('Selected Faculty is already Existed');
//                $('#employee_id option:selected').remove();
//           		  
//            } else {
if(course_id){
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-grade-details-new'; ?>',
                    data: {department_id: department_id, employee_id: employee_id, session_id: academic_year_id, cmn_term: term_id, course_id: course_id,cc_id :cc_id,ge:ge}

                }).done(function (data) {

                    $('#grade_details').empty('');
                    $('#grade_details').html(data);
                });
                }
//                }
//                });
           
    });
    
    
    

    $(".order_view").click(function () {

        var id = $(this).attr("orderid");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-grade-details-print-new'; ?>",
            data: {id: id}
        }).done(function (data) {
            $(".sub").hide();
            $(data).insertAfter("tr.orderid" + id);
        });
    });

  
    $('body').on('change','#cc_id',function(){
       var term_id = $('#cmn_terms').val();
       var cc_id = $('#cc_id').val();
       var session = $('#session').val();
        if (term_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group'; ?>',
                data: { term_id: term_id, cc_id:cc_id ,session:session}
            }).done(function (data) {
                $('#ge').empty();
                $('#ge').html(data);
            });
        }
        });
    
     $('body').on('change', '#degree_id', function () {
        var degree_id = $('#degree_id').val();
        if (degree_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-course-cat'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                    $('#cc_id').empty();
                    $('#cc_id').html(data);
                
            });
        }

    });

    $('#dataTable').DataTable();
</script>