<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<div class="right_col">
<div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div> 
    <?php if ($this->type) { ?>
        <div class="padding-md ">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-title txt-color-blueDark" >
                        <div class="pull-left"><i class="fa fa-eye">Addon Grade Allocation </i></div>
                                        <div class="row">
                <div class="pull-right col-xs-4 col-sm-4 col-md-4 col-lg-4"><div class="pull-right"><span class="pull-left"><small><b>Payment</b></small></span><input type="checkbox" id="examType" value="1"  checked data-toggle="toggle" data-size="sm"></div>
                
                  <div class="pull-right"><span class="pull-left" ><small><b>Attendance</b></small></span><input type="checkbox" id="attend" value="1"  checked data-toggle="toggle" data-size="sm"></div></div>
            </div>
                        
                    </h3>
                   
                    <div class="panel panel-default" style="margin-top:1.3em" >

                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                            <div class="panel-body">
                                
                                <?php
                                $hide_filter_block = '"';
                                if (in_array($this->role_id, $this->administrator_role)) {
                                    $hide_filter_block = '';
                                }
                                ?>
                                <div class="row" <?php echo $hide_filter_block; ?> >



                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Academic Year</label>
                                            <?php echo $this->form->academic_year; ?>
                                        </div>
                                    </div>
                                    <?php //echo $this->form->csrftoken; ?> 
                                    <input type="hidden" name="csrftoken" value="<?=$this->csrftokn?>" class="form-control" required="required" id="csrftoken" autocomplete="off">
                                   <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Addon Course Type<span class="asterisk">*</span></label>
                                            <?php echo $this->form->addon_course_list; ?>
                                        </div>
                                    </div>
                                     <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Addon Course/Paper <span class="asterisk">*</span></label>
                                            <?php echo $this->form->course_id; ?>
                                        </div>
                                    </div> 
                                    

                                </div>    
                                <div class="row">
                                 <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Department<span class="asterisk">*</span></label>
                                            <?php echo $this->form->department_id; ?>
                                        </div>
                                    </div>
                                <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Exam Coordinator<span class="asterisk">*</span></label>
                                            <?php echo $this->form->employee_id; ?>
                                        </div>

                                </div>	
                                <div class="col-sm-3">
                                        <div class="form-group">
                                            <label class="control-label">&nbsp;</label>
                                            <b><input type="text" id="course_name" class="form-control" style="background-color: rgb(253, 245, 154); display: block;" disabled autocomplete="off"></b>
                                        </div>
                                    </div>
                                </div>
                                     
                                </div>
                                <div class="row" <?php echo $hide_filter_block; ?>>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            <input type="text" id="batch" class="form-control"  style="background-color:#fdf59a;" readonly /></div>
                                    </div>
                                </div>
                                <div class="row" <?php echo $hide_filter_block; ?>>


                                    <div id="components_ids"></div>
                                </div>
                                <div class="" id="grade_data">
                                </div>
                                <input type="hidden" name="students_name" id="students_name" value="<?php echo $this->students_name; ?>"/> 
                                
                                <input type="hidden" name="grade_allocate_id" id="grade_allocate_id" value="<?php echo $this->grade_allocate_id; ?>" />
                            
                            </div>

                            <div class="panel-footer">									
                                <div class="row">
                                    <div class="col-sm-7 col-sm-offset-5">
                                        <?php if ($this->type == 'add') { ?> 
                                            <div style="float:left;margin-right:2px;">
                                                <button class="btn btn-primary submit" id ="add_bt" onclick="return ConfirmDelete()" data-toggle="tooltip" data-placement="top" title="clear search text before add">Submit</button>
                                            </div>
                                            <div style="float:left;padding:0px 10px;">
                                                <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                            </div>
                                        <?php
                                        } else {
                                            //1. Hide 'Update' button if GradeReport is generated
                                            //2. Show 'Update' button a)to the faculty to whom this course is assigned. and b) only if the faculty has not submitted to DEAN
                                            //3. Show 'Update' button a) if DEAN/Director is logged in b)GradeReport is not generated.
                                            $login_empl_id = $this->login_storage->empl_id;


                                            if (!$this->isGradeReportPublished) {
                                                //  echo "<pre>";print_r($this->administrator_role); exit;
                                                if (in_array($this->role_id, $this->administrator_role)){
                                                    ?>
                                        <div class="pull-left col-xs-2 col-sm-2 col-md-2 col-lg-2"> <input type="text" class="form-control" disabled placeholder="Revaluation date" name="reval_date" id ="reval_date"/></div>
                                        <div class="pull-right col-xs-2 col-sm-2 col-md-2 col-lg-2"><div class="pull-right"><span class="pull-left" style="margin-right:.3em;"><small><b>Reval Status</b></small></span><input name = "reval" type="checkbox" id="reval" value="0"   data-toggle="toggle" data-size="sm"></div></div>
                                                    <div style="float:left;">
                                                        <button class="btn btn-primary submit" data-toggle="tooltip" data-placement="top" title="clear search text before update" onclick="return ConfirmDelete()" id ="update_bt">Update</button>
                                                    </div>
                                                    <?php
                                                }
                                            } else {
                                             if(in_array($this->role_id, $this->administrator_role)){  ?>
                                             <div class="pull-left col-xs-2 col-sm-2 col-md-2 col-lg-2"> <input type="text" class="form-control" disabled placeholder="Revaluation date" name="reval_date" id ="reval_date"/></div>
                                        <div class="pull-right col-xs-2 col-sm-2 col-md-2 col-lg-2"><div class="pull-right"><span class="pull-left" style="margin-right:.3em;"><small><b>Reval Status</b></small></span><input name = "reval" type="checkbox" id="reval" value="0"   data-toggle="toggle" data-size="sm"></div></div>
                                                     <div style="float:left;">
                                                        <button class="btn btn-primary submit" onclick="return ConfirmDelete()" data-toggle="tooltip" data-placement="top" title="clear search text before add">Update</button>
                                                    </div>
                                            <?php    }
                                                else{
                                                ?><div class="pull-right font-weight-bold">Please contact sister to republish !</div>;
                                               <?php }
                                            }
                                            ?>

                                            <div style="float:left;">
                                                <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>grade-allocation/index">Back</a>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                    </div>
                    </form>
                </div><!-- /panel -->
            </div><!-- /.col-->				
        </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

    <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars"> Addon Grade Allocation </i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>		
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>addon-grade-allocation/index/type/add">Add </a>
                </div>
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">

                <div class="x_title">
                    <div class="row">
                        
                        <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <!--<label class="control-label">Session </label>-->
                                <?php echo $this->form->academic_year; ?>
                            </div>
                        </div>
                        <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <!--<label class="control-label">Session </label>-->
                                <?php echo $this->form->addon_course_list; ?>
                            </div>
                        </div>
                        
                        <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                <!--<label class="control-label">Course Group </label>-->
                                <?php echo $this->form->course_id; ?>
                            </div>
                        </div>
                    </div>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">
                    
                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData"> 
                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th>Addon Course Group</th>
                                    <th>Exam Coordinator</th>
                                    <th>Course</th>
                                    <th>Course Code</th>
                                     <th>Academic Year</th>
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {
                                    //echo "<pre>"; print_r($this->paginator);die;
                                    foreach ($this->paginator as $results) {
                                        //print_r($results);die;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['addon_course']; ?></td>
                                            <?php $HRMModel_model = new Application_Model_HRMModel();
                                            $emp = $HRMModel_model->getEmployeeData($results['employee_id']);
                                            ?>
                                            <td><?php echo $emp['empl_firstname']; ?></td>
                                            
                                            <td><?php echo $results['course_name']; ?></td>
                                            <td><?php echo $results['course_code']; ?></td>
                                            <td><?php echo $results['academic_year']; ?></td>
                                            <td><a href="<?php echo $this->mainconfig['host']; ?>addon-grade-allocation/index/type/edit/id/<?php echo $results['grade_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a><?php if (in_array($this->role_id, $this->administrator_role)) { ?><!--&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>grade-allocation/index/type/delete/id/<?php echo $results['grade_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a>--><?php } ?></td>

                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
                        </div>
    <?php echo $pagination_tr; ?>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>
    //modifiedDataTable();
   $(document).ready(function () {
    
        //$("#stu_dob").datepicker({ dateFormat: 'dd-mm-yy' });  
        $('#reval_date').datepicker({format: 'dd-mm-yyyy'});
    });

$('body').on('change','input[type="checkbox"]',function(){
var value = $(this).parent().attr("class");
if(value.includes("off")){
    $(this).removeAttr("checked");
     $(this).val("0");
       $('#reval_date').attr('disabled','disabled');
      $('#reval_date').removeAttr('required');
}
else
{
    $(this).attr("checked","checked");
    $(this).val("1");
 
    $('#reval_date').attr('required','required');
     $('#reval_date').removeAttr('disabled');
}
});

 function ConfirmDelete()
    {
        
        $('[data-toggle="tooltip"]').tooltip();   
        var search_val = $('input[type="search"]').val();
        var x = search_val;
        if (x){
            $('.load-box').css('display','none');
            return false;
        
        }
        else{
            $('.load-box').css('display','block');
            return true;
        }
    }

 $("#academic_year").change(function () {
        var academic_year = $('#academic_year').val();
        if (academic_year) {
  $.ajax({
    type: "POST",
     url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-addon-courses-by-session'; ?>',
     data: {academic_year: academic_year}
            }).done(function (data) {
             $('#addon_course_list').empty('');
             $('#addon_course_list').html(data);
             $('#addon_course_list').trigger("chosen:updated");
             });
                 }
 });
 
  
    $('#addon_course_list').change(function () {
     
        var degree_id = $('#addon_course_list').val(); 
        if (degree_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-addon'; ?>',
                data: {degree_id:degree_id}
            }).done(function (data) {
                $('#course_id').empty();
                $('#course_id').html(data);
                $("#course_id").trigger("chosen:updated");
                
            });
            
        
        
       }
       });
       
       
    var employee_id = $('#employee_id option:selected').val();
    var department_id = $('#department_id option:selected').val();
    var grade_allocate_id = $('#grade_allocate_id').val();
   
    
    //Added by kedar for filter
    $('body').on('change', '#course_id', function () {
      var course_id = $('#course_id').val();
      var academic_year = $('#academic_year').val();
      var addon_course_list = $('#addon_course_list').val();
       
        $.ajax({
        type: "POST",
         url: "<?php echo $this->mainconfig['host'] . 'addon-grade-allocation/ajax-get-student-details-new'; ?>",
         data: {employee_id: employee_id, department_id: department_id, course_id: course_id,academic_year: academic_year,addon_course_list:addon_course_list, grade_allocate_id: grade_allocate_id,limit:100,offset:0}
                }).done(function (data) {
                    //	alert(data);	
                    $("#grade_data").html(data);
        
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'addon-grade-allocation/ajax-get-course-code'; ?>",
            data: {course_id: course_id}
        }).done(function (data) {
            $('#course_name').show();
            $('#course_name').empty('');
            $('#course_name').val(data);
            $('.load-box').hide();
        });  
        
        });
           
    });


  
    var academic_year = $('#academic_year option:selected').val();
    var addon_course_list = $('#addon_course_list').val();
    var course_id = $('#course_id option:selected').val();
    
    if(course_id) {
     $.ajax({
        type: "POST",
        url: "<?php echo $this->mainconfig['host'] . 'addon-grade-allocation/ajax-get-student-details-new'; ?>",
         data: {employee_id: employee_id, department_id: department_id, course_id: course_id,academic_year: academic_year,addon_course_list:addon_course_list, grade_allocate_id: grade_allocate_id,limit:100,offset:0}
                }).done(function (data) {
                    //	alert(data);	
                    $("#grade_data").html(data);
                    
                    
         $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'addon-grade-allocation/ajax-get-course-code'; ?>",
            data: {course_id: course_id}
        }).done(function (data) {
            $('#course_name').show();
            $('#course_name').empty('');
            $('#course_name').val(data);
            $('.load-box').hide();
        });              
                    
                
       });
       };      
//    
    
//    
//    if (term_id) {
//           $('.load-box').css('display','block');
//           $('#examType').parent().hide();
//           $('#attend').parent().hide();
//        $.ajax({
//            type: "POST",
//            url: '<?php //echo $this->mainconfig['host'] . 'grade-allocation/ajax-Get-Courses-Edit-New1'; ?>',
//            data: {Ct_id: ct_id, employee_id: employee_id, department_id: department_id, term_id: term_id, ge_id: ge_id, cc_dept: department, grade_allocate_id: grade_allocate_id,session:session,degree_id:degree_id}
//        }).done(function (data) {
//
//            $('#course_ids').empty('');
//            $('#course_ids').html(data);
//            
//            var ct_id = $('#ge_id').val();
//            var term_id = $('#cmn_terms').val();
//            var course_id = $('#course_id').val();
//            var session = $('#session').val();
//            if (course_id != '') {
//                
//                
//                 
//                
//                
//                var academic_id = $("#academic_id").val();
//                $.ajax({
//                    type: "POST",
//                    url: "<?php //echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-student-details-new'; ?>",
//                    //data: { academic_year_id : academic_id,component_name:component_name,component_id:component_id,grade_allocate_id:grade_allocate_id,course_id:course_id}
//data: {employee_id: employee_id, department_id: department_id, ct_id: ct_id, term_id: term_id, course_id: course_id, honors_id: department, session_id: session, grade_allocate_id: grade_allocate_id,session:session,degree_id:degree_id,limit:100,offset:0}
//                }).done(function (data) {
//                    //	alert(data);	
//                    $("#grade_data").html(data);
//                    
//                      $.ajax({
//            type: "POST",
//            url: "<?php //echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-code'; ?>",
//            data: {course_id: course_id}
//        }).done(function (data) {
//            $('#course_name').show();
//            $('#course_name').empty('');
//            $('#course_name').val(data);
//            $('.load-box').hide();
//        });      
//                });
//            }
//        });
//
//    }



    
    
//End
    $('body').on('change', '#component_id', function () {
        var academic_id = $("#academic_id").val();
        var component_name = $('#component_id option:selected').text();
        //alert(component_name)
        var component_id = $('#component_id option:selected').val();
        //alert(academic_id);
        /* $.ajax({ 
         type: "POST",
         url:"<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-student-details'; ?>",
         data: { academic_year_id : academic_id,component_name:component_name,component_id:component_id}
         }).done( function( data ) { 
         //	alert(data);	
         $("#grade_data").html(data);
         }); */

    });


    
    
$('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
      
        if (year_id) {
          $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
            }
    });
    $('body').on('change', '#degree_id', function () {
        var degree_id = $('#degree_id').val();
        if (degree_id) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-course-cat'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                    $('#cc_id').empty();
                    $('#cc_id').html(data);
                    $('#cc_id').trigger("chosen:updated");
                    
                    $.ajax({
                   type: "POST",
                   url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Dept'; ?>',
                   data: {degree_id: degree_id}
               }).done(function (data) {
                   $('#department').empty('');
                   $('#department').html(data);
               });
            
                
            });
        }

    });

    var academic_id = $('#academic_id option:selected').val();
    if (academic_id) {
        $('#batch').show();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch-code'; ?>',
            data: {academic_id: academic_id}
        }).done(function (data) {
            var result = $.parseJSON(data);
            if ((data != '')) {
                $('#batch').val(result['short_code']);
            }
        });
    } else {
        $('#batch').hide();
    }
    $('#print').click(function () {
        window.print('#grade_data');
    });
    
    

$(function()
{   
    $(".monthPicker").datepicker({
        dateFormat: 'MM yy',
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
       

//        onClose: function(dateText, inst) {
//            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
//            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
//            $(this).val($.datepicker.formatDate('MM yy', new Date(year, month, 1)));
//        }
    });
  

    $(".monthPicker").focus(function () {
        
         $('.table-condensed>tbody').hide();
         $('.table-condensed>thead>tr:nth-child(2)').find('th').remove();
         $('.table-condensed>thead>tr:nth-child(2)').append("<th><button class='btn-primary'>Today</button></th><th></th><th><button id ='ok' class='btn-primary'>Done</button></th>");
         
        
    });
    
    $(".switch").mouseup(function(){
        var str = $(this).text();
                   var str_arr =   str.split(' ');
        alert(JSON.stringify(str_arr));
    });

 $("#ok").click(function(){
    $(".monthPicker").empty();
    alert($('.table-condensed>thead>tr:nth-child(1)>th:nth-child(2)').text());
    //$(".monthPicker").val($('.table-condensed>thead>tr:nth-child(1)>th:nth-child(2)').text());
 });

});

$('button').click(function(){

//$('button').attr('disabled','disabled')
});

$('body').on('click','.sorting_desc,.sorting_asc',function(){
 $('.load-box').css('display','block');
var x = 1;
    $('th[id^="total"]').each(function(col){
        var id = $(this).attr('id');
      
$('input[data-id="#'+id+'"]').each(function(e){
            $(this).attr('tabindex',(x));
            x+=1;
    });
});
$('.load-box').hide();
});



 let type='<?= $this->type ?>';
    if(type == 'edit'){
        //disable the field
        
        $("#session").prop( "disabled", true ); 
        $("#cmn_terms").prop( "disabled", true ); 
        $("#degree_id").prop( "disabled", true ); 
        $("#cc_id").prop( "disabled", true ); 
        $("#ge_id").prop( "disabled", true ); 
        $("#department").prop( "disabled", true ); 
    

        //right before the form submits, we re-enable the fields, to make them submit.
        $( "#formValidate1" ).submit(function( event ) {
        $("#course_id").prop( "disabled", false );
        $("#session").prop( "disabled", false );
        $("#cmn_terms").prop( "disabled", false );
        $("#degree_id").prop( "disabled", false );
        $("#cc_id").prop( "disabled", false );
        $("#ge_id").prop( "disabled", false );
        $("#department").prop( "disabled", false );
});   
    }
</script>
