 <div class="col-md-12">
                   
    <?php 
         if(!empty($this->resultData)) { 
             //echo '<pre>'; print_r($this->resultData);

     ?>
                         <div class="table-responsive" id="studentData"> 
                         <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
                             <thead>
                                 <tr>
                                    <th class="no-sort">S.No.</th>
                                    <th>Applicant Name</th>
                                    <th>Father Name</th>
                                    <th>Form Id</th>
                                    <th>Action</th>

                                 </tr>
                             </thead>
                             <tbody>
                         <tr>

                             <td><?php echo '1'; ?></td>						
                             <td><?php echo $this->resultData['stu_fname']; ?></td>
                             <td><?php echo $this->resultData['father_fname']; ?></td>
                             <td><?php echo $this->resultData['stu_id']; ?></td>
                             
                             <td class="download_tc">
                                  <input type="hidden" value="<?= $this->resultData['stu_id']; ?>" id="form_id">
                             <a class="btn btn-primary pdf"  target="_blank" href="<?php echo $this->mainconfig['host'];?>student/migrationprint/stu_id/<?php echo $this->resultData['stu_id']; ?>">PDF </a>
                             </td>
                         </tr>            

                     <?php

                     }else{?>
                         <td colspan="7"><b style="text-align: center;">Oop's..! Form id not exists. </b></td>
                     <?php }

                 ?>

             </tbody>
         </table>
     </div>
 </div>
    
    
    <script>
   
    
    </script>