 <div class="col-md-12">
                   
    <?php 
         if(!empty($this->resultData)) { 
             //echo '<pre>'; print_r($this->resultData);

     ?>
                         <div class="table-responsive" id="studentData"> 
                         <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  style="height:100%;">
                             <thead>
                                 <tr>
                                     <th class="no-sort">S.No.</th>
                                     <th>Applicant Name</th>
                                     <th>Father Name</th>
                                     <th>Form Id</th>
                                     <th>     Edit        </th>
                                     <th>Action</th>

                                 </tr>
                             </thead>
                             <tbody>
                         <tr>

                             <td><?php echo '1'; ?></td>						
                             <td><?php echo $this->resultData['stu_fname']; ?></td>
                             <td><?php echo $this->resultData['father_fname']; ?></td>
                             <td><?php echo $this->resultData['stu_id']; ?></td>
                             <td class="tc_edit"> 
                                 <input type="hidden" value="<?= $this->resultData['stu_id']; ?>" id="stu_id">
                                  <a class="btn btn-primary pdf"  target="_blank" href="<?php echo $this->mainconfig['host'];?>student/index">Edit Participant Details </a>
                             </td>
                             <td class="download_tc">
                                  <input type="hidden" value="<?= $this->resultData['stu_id']; ?>" id="form_id">
                             <a class="btn btn-primary pdf"  target="_blank" href="<?php echo $this->mainconfig['host'];?>student/tcprint/stu_id/<?php echo $this->resultData['stu_id']; ?>">PDF </a>
                             </td>
                         </tr>            

                     <?php

                     }else{?>
                         <td colspan="7"><b style="text-align: center;">Oop's..! Form id not exists. </b></td>
                     <?php }

                 ?>

             </tbody>
         </table>
     </div>
 </div>
    <!-- Modal -- Pay Mode---->
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">

                <div class="modal-body" id="resultas">

              </div>
              <div class="modal-footer">

                    <button type="button" id="" data-dismiss="modal" class="btn btn-default">Cancel</button>
                    <button type="button" id="cnf_cert" class="btn btn-primary">Save/Update</button>
              </div>
            </div>

          </div>
        </div>
    <!---End Modal--->   
    
    <script>
    $(".tc_edit").click(function() {
    let stu_id = $(this).closest("td").find("#stu_id").val();  
    //salert(stu_id);
    
        
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'student/ajax-get-student-Info-for-mid-tc'; ?>',
            data: {form_id:stu_id}
        }).done(function (data) {
            //alert(data);           
            $('#resultas').html(data);
           });
    //$("#resultas").append(application_no);      
    });
    $(".download_tc").click(function(){
      let form_id = $(this).closest("td").find("#form_id").val();
      if(form_id){
        $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student/ajax-update-tc-status'; ?>',
                data: {form_id: form_id}
            }).done(function (data) {
         });
    }
    });

    
    </script>