
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;">S. No.</th>	
                                        <th style="text-align:center;">Name</th>
                                        <th style="text-align:center;">Form Id</th>
                                        <th style="text-align:center;">Addon Course</th>
                                        <th style="text-align:center;">Exam Id</th>
                                        <th style="text-align:center;">Reg No</th>
                                        <th style="text-align:center;">Roll No</th>
                                        <th style="text-align:center">Department</th>
                                        <th style="text-align:center">Fee</th>

                                    </tr>

                                </thead>

                                <tbody style="text-align:center;">

    <?php
  


    $i = 1;

    $pagination_tr = '';

    if (count($this->paginator) != 0) {



        foreach ($this->paginator as $results) {

            //print_r($results);die;
            ?>

                                            <tr>

                                                <td><?php
                                echo $i;



                                $i++;
            ?>

                                                </td>	
                                                <td><?php echo $results['stu_fname']; ?></td>
                                               <td><?php echo $results['stu_id']; ?></td>
                                               <td><?php echo $results['name']; ?></td>
                                               <td><?php echo $results['exam_roll']; ?></td>
                                               <td><?php echo $results['reg_no']; ?></td>
                                               <td><?php echo $results['roll_no']; ?></td>
                                               <td><?php echo $results['department']; ?></td>
                                               <td><?php echo $results['fee']; ?></td>

                                               
                                            </tr>            

                                    <?php
                                }

                                $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                            }
                            ?>

                                </tbody>

                            </table>
<script>
    setDatatables();
    </script>