<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

    <thead>

        <tr>

            <th style="text-align:center;">S. No.</th>	


            <th style="text-align:center">Course</th>
            <th style="text-align:center">Applied Students</th>
            <th style="text-align:center">Paid Students</th>
            <th class="no_print" style="text-align:center">View</th>

        </tr>

    </thead>

    <tbody style="text-align:center;">

        <?php
            $geinfo = new Application_Model_Ge();
            $deptinfo = new Application_Model_Department();
            $deptType = new Application_Model_DepartmentType();
            $i = 1;

        $pagination_tr = '';

        if (count($this->paginator) != 0) {

            $totpaid = $totapp = 0;

            foreach ($this->paginator as $results) {

                //print_r($results);die;

                ?>

                <tr>

                    <td><?php

                        echo $i;



                        $i++;

                        ?>

                    </td>	


                    <td class='<?php if(!$results['course'])echo "text-danger"; ?>'><?php if($results['course']){echo $deptType->getRecord($results['course'])['department_type'];}else{echo "<b>Warning !</b> students without courses...";} ?></td>
                    <td data-id = '#totapp' class='app' ><?php echo $results['total_applied']; $totapp += $results['total_applied']; ?></td>
                    <td data-id='#totpaid' class='paid' ><?php echo $results['paid']; $totpaid+=$results['paid']; ?></td>




                    <td><a href="<?php echo $this->mainconfig['host']; ?>student/form-student/type/students/id/<?php echo $results['course']; ?>/acad/<?=$this->year_id;?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>
    <!--<td></td>-->
                </tr>            

                <?php

            }

            $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

        }else{?>
                <tr>
                    <td colspan="5">
                        <h2 style="color:red">
                            No Records Available.
                        </h2>
                    </td>
                </tr>
        <?php } ?>

    </tbody>
    <tfoot>
        <tr>
            <th class="bg-primary text-center" colspan = 2 style="letter-spacing:.3em;">TOTAL STUDENTS</th>
             <th class="bg-primary text-center" id="totapp" style="letter-spacing:.3em; font-size:1.3em"><?=$totapp; ?></th>
            <th class="bg-primary text-center" id="totpaid" style="letter-spacing:.3em; font-size:1.3em"><?=$totpaid;?></th>


            <th class="bg-primary text-center" id="np" style="letter-spacing:.2em;"><small>Not Paid Students</small> = <?=$totapp-$totpaid;?></th>
        </tr>
    </tfoot>

</table>
<script>
    setDatatables();
    </script>