<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" width="100%">
				<thead>
					<tr>
					    <th>S.No.</th>
					    <th>Participant ID </th>
						<th>Participant Name</th>
						<th>Pass-Out Cert Number</th>
                       
					</tr>
				</thead>
				<tbody>
				<tbody>

					<?php $result=$this->corecourseresult;
                    if(!empty($result)){
                        $i=1;
                        $lastCertNo=!empty($this->lastPassOutNo)?$this->lastPassOutNo+1:'1';
                        foreach($result as $results) { ?>

                        <tr>
                        <td><?php echo $i; ?> </td>
                        <input type="hidden" name="stu_id[]" id="student_id" value="<?php echo $results['student_id']; ?>" />
                        <input type="hidden" name="pass_out_no[]" id="pass_out_no" value="<?php echo $lastCertNo; ?>" />
                        <td><?php echo $results['stu_id'];?></td>

                        <td><?php echo $results['stu_fname'].'&nbsp;&nbsp;'.$results['stu_lname'];?></td> 
                        <td><?php echo $lastCertNo; ?></td> 


                        </tr>
					<?php 
                        $i++;$lastCertNo++; 
                        }
                    }else{                      ?>
                        <tr>
                            <td colspan="4">
            
       
                                <b style="color: red; text-align: center">
                                <?php 
                                if(!empty($_SESSION['message'])){
                                    echo $_SESSION['message'];
                                    unset($_SESSION['message']) ; 
                                }else{
                                echo 'Invalid type of input given.';
                                } ?> </b>
                            </td>
                        </tr> 
                  <?php  } ?>
                    
				</tbody>
			</table>
			 <?php //echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
<script>
   
</script>