<style>
   
    
    
    
</style>
<div class="right_col">
    <?php if($_SESSION['update_message']) {?>
    
      <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $_SESSION['update_message']; unset($_SESSION['update_message']) ;?>
               
            </div> 
        <?php }?>
    
    <?php if ($this->type == 'publish') { ?>
        
         <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
 </div>  
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			 <i class="fa fa-bars"> Serial Number Generation[Marks-sheet/Provisional Certificates] </i> 
		</h3>
              
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					    
							<div class="row">
                            <div class="col-sm-3 employee_class">
                            <div class="form-group">
                                    <!--<label class="control-label">Academic Year<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->academic_year; ?>
                                </div>
                            </div>     
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Session<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->session; ?>
                                </div>
                            </div>
                            <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <!--<label class="control-label">Stream<span class="asterisk">*</span></label>-->
                                <?php echo $this->form->stream; ?>
                            </div>
							</div> 
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <!--<label class="control-label">Type<span class="asterisk">*</span></label>-->
                                <select class="form-control" name="type" id="type" required="required">
                                    <option value="">Select Type</option>
                                    <option value="1">Collegiate</option>
                                    <option value="2">Non-Collegiate</option>
                                </select>
                            </div>
							</div>
                                
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
                                <?php echo $this->form->academic_year_id; ?>
                            </div>
							</div> 
                                
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <!--<label class="control-label">Semester<span class="asterisk">*</span></label>-->
                                <select class="form-control" name="cmn_terms" id="cmn_terms" required="required">
                                    <option value="">Select Semester</option>
                                    <option value="t1">Sem-1</option>
                                    <option value="t2">Sem-2</option>
                                    <option value="t3">Sem-3</option>
                                    <option value="t4">Sem-4</option>
                                    <option value="t5">Sem-5</option>
                                    <option value="t6">Sem-6</option>
                                </select>
                            </div>
							</div>
                           
                                
							<div class="col-sm-3 employee_class">
                                <div class="form-group">
                                  <!--<label class="control-label">Published Date<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->publish_date; ?>
                                    <?php echo $this->form->csrftoken; ?>
                                </div>
							</div>
							
							<div class=" col-md-3 text-right">
                                <div class="form-group">
                                    <BR>
                                    <button class=" btn btn-success" id="getTrStudent" type ="button"  id="submit">Get Records </button>
                                </div>
							</div>
                                
						
                         <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
						<div id="getstudent" class="col-sm-12">
                            
                        </div>
                         
							<div class="row">
							    <div class="col-md-offset-5 col-md-5"><button class=" btn btn-primary" type ="submit"  id="submit"> Generate Serial No. </button></div>
							    
							</div>
							</div>
						
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
    <?php }else if($this->type == 'download'){ ?>
     <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
 </div>  

	<div class="row">
		<div class="col-md-12">
		
            <h3 class="page-title txt-color-blueDark" >
                <i class="fa fa-bars"> Download Bulk Pass-Out Certificates </i> 
            </h3>

               
              
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					     <div class="row">
                            <div class="col-xs-6 pull-left" style="padding-left : 0 ; margin-left: 0;"> 
                                            <div class="col-xs-3 pull-left" style="padding-left : 0 ; margin-left: 0;"><p>Min Sl No. <span class="asterisk"></span> <input type="number" id="manualmin" autocomplete="off"> </p></div>
                                            <div class="col-xs-3 pull-left" style="padding-left : 0 ; margin-left: 0;"><p>Max Sl No. <span class="asterisk"></span><input type="number" id="manualmax" autocomplete="off"></p></div>
                                            
                                            </div>
                        </div>
							<div class="row">
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                                    <!--<label class="control-label">Academic Year<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->academic_year; ?>
                                </div>
                            </div>     
                            <div class="col-sm-3 employee_class">
                                <div class="form-group">
                                    <!--<label class="control-label">Session<span class="asterisk">*</span></label>-->
                                    <?php echo $this->form->session; ?>
                                </div>
                            </div>
                            <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <!--<label class="control-label">Stream<span class="asterisk">*</span></label>-->
                                <?php echo $this->form->stream; ?>
                            </div>
							</div> 
                            <div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
                                <?php echo $this->form->academic_year_id; ?>
                            </div>
							</div>     
							
							<div class="col-md-offset-6 col-md-6 text-right">
                                <div class="form-group">
                                    <BR>
                                    <button class=" btn btn-success" id="getTrStudent" type ="button"  id="submit">Get Records </button>
                                </div>
							</div>
							
							</div>
                        <hr>
                         <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
						<div id="getstudent" class="col-sm-12">
                            
                        </div>
                         
							<div class="footer-bottom">
							    
							    <div class="col-md-offset-3 col-md-3 text-right"><button class="downloadAll btn btn-primary" type ="button"  id="download_pdf">download <i class="fa fa-download"></i></button></div>
							    <div class=" col-md-3 text-left"><button class="cancel btn btn-primary" type ="button" >Stop <i class="fa fa-close"></i></button></div>
							</div>
							</div>
						
				</form>
			</div><!-- /panel -->
            <div class="panel panel-default"> 
               
            <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Download Duplicate Pass-Out Certificate </i>

                    </h3>
                </div>
            </div>
                <div class="panel-body cont">
                </div>
                <div class="col-md-12">
                   
                    <span id="updatemsg" style="color:green;"></span>
                   <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label" style="float:left;">Enter Your Form Id:<span class="asterisk">*</span></label>-->
                            <input type="text" name="form_id" id="form_id" value="" class="form-control" placeholder="Enter Your Form Id" pattern="\d+" title="xxx.." autocomplete="off">
                        </div>
                   </div>
                <div >
                    <button class="btn btn-primary submit" id="pass_cert">Submit</button>
                </div>
                </div>
                 <div class="col-md-12">
                   <div class="table-responsive" id="studentData"> 
                       
                    </div>
                </div>
                
            </div>    
            </div>
		</div><!-- /.col-->				
	</div><!-- /.row -->

    
    <?php }else {?>
    
    <div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
 </div>  
		
    <div class="panel panel-default">
              <a class="btn btn-primary pull-left" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>student/pass-out-certificate/type/publish">Publish Pass-Out Certificate </a> 
              <a class="btn btn-primary pull-left" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>student/pass-out-certificate/type/download">DownLoad Pass-Out Certificate </a>
             
		
	</div><!-- /.row -->
    
       
        
    <?php 
    
    }
    ?>

<script>
$('.monthYearPicker').datepicker();    
$('body').on('click', '#getTrStudent', function() {
   $('.load-box').css('display','block');
      getstudentDetails();
});

let type='<?= !empty($this->type)?$this->type:'' ?>';
    //alert(type);
if(type==='publish'){
function getstudentDetails() {
    

    var academic_id= $('#academic_year_id').val();
    var stream= $('#stream').val();
    var session= $('#session').val();
    var type= $('#current_batch').val();
       if(!academic_id && !stream && !session && !type){
           alert('Please select the required field.');
           $('.load-box').css('display','none');
       }else{
        $url = '<?php echo $this->mainconfig['host']; ?>student/get-student-pass-out-list';
        $.post($url,
        {
            'academic_id': $('#academic_year_id').val(),
            'stream': $('#stream').val(),
            'session': $('#session').val(),
            'type': $('#type').val(),
            'cmn_terms': $('#cmn_terms').val()

        })
        .done(function(data) {
            $('.load-box').css('display','none');
            $('#getstudent').empty();
            $('#getstudent').html(data);
            //setDatatables();
        });

    }   
}
}
if(type==='download'){
function getstudentDetails() {
    $url = '<?php echo $this->mainconfig['host']; ?>student/get-student-pass-out-card';
    $.post($url,
    {
        'academic_id': $('#academic_year_id').val(),
        'stream': $('#stream').val(),
        'session': $('#session').val()
    })
    .done(function(data) {
        $('.load-box').css('display','none');
        $('#getstudent').empty();
        $('#getstudent').html(data);
        setDatatablesManual();
    });

}   
}

$('body').on('change', '#academic_year_id', function() {		
    var academic_id=$('#academic_year_id').val();
    if(academic_id){
    $('#batch').show();
        $.ajax({ 
                type: "POST",
                url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
                data: {academic_id:academic_id}
            }).done(function( data ) {
                var result = $.parseJSON(data);
                if((data!='')){
                    $('#batch').val(result['short_code']);
                }
        });
    }
	 
 });
 
 //To filter Session
    $('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
     //Get Batch By Session
    /*$('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                //$('#academic_year_id').empty('');
                $('#current_batch').empty('');
                //$('#academic_year_id').html(data);
                $('#current_batch').html(data);
                //$('#academic_year_id').trigger("chosen:updated");
                $('#current_batch').trigger("chosen:updated");
            });
        }
    });*/
    $('body').on('change', '#stream', function () {
        var stream = $('#stream').val();
        var session = $('#session').val();
        if (stream) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-academic-on-stream'; ?>',
                data: {stream: stream,session:session}
            }).done(function (data) {
                $('#academic_year_id').empty('');
                $('#academic_year_id').html(data);
                $('#academic_year_id').trigger("chosen:updated");
            });
        }
    });
    //End  
    $("#pass_cert").click(function(){
    //alert('kk');
    var form_id= $('#form_id').val().trim();
        if (form_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student/ajax-get-student-info-for-pass-out'; ?>',
                data: {form_id: form_id}
            }).done(function (data) {
                $('#studentData').empty('');
                $('#studentData').html(data);
            });
        }
});
   var table = '';
   
    function setDatatablesManual() {
        $.fn.dataTable.ext.search.push(
                function (settings, data, dataIndex) {
                    var min = parseInt($('#manualmin').val(), 10);
                    var max = parseInt($('#manualmax').val(), 10);
                    var age = parseFloat(data[0]) || 0; // use data for the age column

                    if ((isNaN(min) && isNaN(max)) ||
                            (isNaN(min) && age <= max) ||
                            (min <= age && isNaN(max)) ||
                            (min <= age && age <= max))
                    {
                        return true;
                    }
                    return false;
                }
        );

        table = $('#datatable-responsive').DataTable({
            "pageLength": -1,

        });
    }

    // Event listener to the two range filtering inputs to redraw on input
    $('#manualmin, #manualmax').keyup(function () {
        //alert("hello");
        table.draw();
    });

    $('#manualmin, #manualmax').change(function () {
        //alert("hello");
        table.draw();
    });

    //End

</script>
