<div class="right_col bdoypayment">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    
 
 <?php if($this->type == "getStudents") { ?>
       
        
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <h3 class="page-title txt-color-blueDark">
                    <i class="fa fa-bars">Participants Details</i>

                </h3>
            </div>
<!--            <div class="col-sm-3 employee_class">
                <div class="form-group">
                  <label class="control-label">Academic Year<span class="asterisk">*</span></label>
                    <?php echo $this->form->academic_year_list; ?>
                </div>
                </div> 
                <div class="col-sm-3 employee_class">
                <div class="form-group">
                  <label class="control-label">Session<span class="asterisk">*</span></label>
                    <?php echo $this->form->session; ?>
                </div>
                </div> 
                <div class="col-sm-3 employee_class">
                <div class="form-group">
                  <label class="control-label">Batch<span class="asterisk">*</span></label>
                    <?php echo $this->form->academic_id; ?>
                </div>
                </div> -->
        </div>
    <div class="padding-md">
    <div class="panel panel-default">
        <div class="panel-body cont">
           
        
                <div class="x_title  table-responsive">
                    <div id="divTableDataHolder">
   <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>
                                       <?php //echo '<pre>'; print_r($this->degree_id);die; ?>
                                        <th style="text-align:center;" rowspan="2">S. No.</th>
                                        <th style="text-align:center;" rowspan="2">Applicant Name</th>
                                        <th style="text-align:center;" rowspan="2">Form Id</th>
                                        <th style="text-align:center;" rowspan="2"> Roll No.</th>
                                        <th style="text-align:center;" rowspan="2"> D.O.B.</th>
                                        <th style="text-align:center;" rowspan="2"> Payment Mode</th>
                                        <th style="text-align:center;" rowspan="2"> Amount</th>
                                        <th style="text-align:center;" rowspan="2"> TXN Id</th>
                                        <th style="text-align:center;" rowspan="2"> Date </th>
                                        <th style="text-align:center;" rowspan="2">Father Name</th>
                                        <th style="text-align:center;" rowspan="2">Aadhar Number</th>
                                        <th style="text-align:center;" rowspan="2">Blood Group</th>
                                        <th style="text-align:center;" rowspan="2">Relegion</th>
                                        <th style="text-align:center;" rowspan="2">Nationality</th>
                                        <th style="text-align:center;" rowspan="2">	Email Id  </th>
                                        <th style="text-align:center;" rowspan="2">	Student Mobile No  </th>
                                        <th style="text-align:center;" rowspan="2">	Father Contact No  </th>
                                        <th style="text-align:center;" rowspan="2">	Mother's Name </th>
                                        <th style="text-align:center;" rowspan="2">	Guardian Name </th>
                                        <th style="text-align:center;" rowspan="2">	Category </th>
                                        <th style="text-align:center;" rowspan="2">	caste </th>
                                        <th style="text-align:center;" rowspan="2">	Caste Certificate Number </th>
                                        <th style="text-align:center;" rowspan="2">	State </th>
                                        <th style="text-align:center;" rowspan="2">	Home Town </th>
                                        <th style="text-align:center;" rowspan="2">	Appearing Status </th>
                                       
                                        

                                        <th style="text-align:center" rowspan="2">Course</th>
                                        <th style="text-align:center" rowspan="2">Addon Course</th>
                                        <th style="text-align:center" rowspan="2">Value Added 1</th>
                                        <th style="text-align:center" rowspan="2">Value Added 2</th>
                                        <th style="text-align:center" colspan="3">First Preference</th>
                                        <th style="text-align:center"rowspan="2">Permanent Address</th>
                                        <th style="text-align:center"rowspan="2">Local Address</th>
                                        <?php if($this->degree_id == 1){?>
                                        <th style="text-align:center" colspan="9">Intermediate Educational Details</th>
                                        <th style="text-align:center" colspan="4">Last Educational Details</th>
                                        <?php }else{ ?>
                                        <th style="text-align:center" colspan="5">Matric Educational Details</th>
                                        <th style="text-align:center" colspan="5">Intermediate Educational Details</th>
                                        <th style="text-align:center" colspan="5">Graduation Educational Details</th>
                                        <th style="text-align:center" colspan="5">Other Educational Details</th>
                                        
                                        <th style="text-align:center" colspan="5">BCA/B.Sc(CS) Educational Details</th>
                                       <th style="text-align:center" colspan="5">Graduation with Maths Educational Details</th>
                                       <th style="text-align:center" colspan="4">Last Educational Details</th>
                                        <?php }?>
                                        <!--<th class="no_print" style="text-align:center">Edit | Delete</th>-->

        <th rowspan=2>Admission Card</th>
                 <th rowspan=2>Photo</th>
                 <th rowspan=2>Action</th>
                <th style="width: 50px;" rowspan=2>status</th>

                                    </tr>
                                    <tr>
                                        <th>Core Course</th>
                                        <th>Generic</th>
                                        <th>Aecc</th>
                                        
                                        <?php if($this->degree_id == 1){?>
                                        
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Roll No</th>
                                        <th>Obt. Marks</th>
                                        <th>Total Marks</th>
                                        <th> Percent</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>Name Of Institution</th>
                                        <th>Place</th>
                                        <th>Board</th>
                                        <th>Pass Year</th>
                                        <?php }else{ ?>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>School</th>
                                        <th>Board</th>
                                        <th>Division</th>
                                        <th>Subject</th>
                                        <th>Pass Year</th>
                                        
                                        <th>Name Of Institution</th>
                                        <th>Place</th>
                                        <th>Board</th>
                                        <th>Pass Year</th>
                                        <?php }?>
                                         
                                    </tr>
                                    
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                           $valueCourseData = new Application_Model_ValueAddedCourseModel();
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->result2) != 0) {

                                     $student_arr = array_column($this->paginator,"stu_id");
                                        foreach ($this->result2 as $result) {

                                          
                                                if(in_array($result['stu_id'],$student_arr)){
                                                   $index = array_search($result['stu_id'],$student_arr);
                                                   $results = $this->paginator[$index];
                                                   //echo '<pre>'; print_r($results);die;
                                            ?>

                                            <tr>

                                                <td>
                                                    <?php
                                                        echo $i;
                                                        $i++;
                                                    ?>
                                                </td>
                                                <td><?php echo $results['applicant_name'];?></td>
                                                    <?php  $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                                <td><?php echo $results['form_id'];?></td>
                                                <td><?php echo $results['class_roll'];?></td>
                                                <td><?php echo $results['dob_date'];?></td>
                                                <td>
                                                    <?php 
                                                    switch($results['pay_mode1']){
                                                        case  '1':
                                                            echo "ONLINE";
                                                            break;
                                                        case  '2':
                                                            echo "NEFT/RTGS";
                                                            break;
                                                        case  '3':
                                                            echo "NEFT";
                                                            break;
                                                        case  '4':
                                                            echo "RTGS";
                                                            break;
                                                        default:
                                                            break;
                                                    }
                                                    ?>
                                                </td>
                                                <td><?=$results['amount1']; ?></td>
                                                <td><?=$results['unique_id1']; ?></td>
                                                <td><?=$results['date_time1']; ?></td>
                                                <td><?=$results['father_name']; ?></td>
                                                <td><?=$results['aadhar_number']; ?></td>
                                                <td><?=$results['blood_group']; ?></td>
                                                <td><?=$results['religion']; ?></td>
                                                <td><?=$results['nationality']; ?></td>
                                                <td><?=$results['email_id']; ?></td>
                                                <td><?=$results['phone']; ?></td>
                                                <td><?=$results['father_contact']; ?></td>
                                                <td><?=$results['mother_name']; ?></td>
                                                <td><?=$results['guard_name']; ?></td>
                                                <td><?=$results['caste_category']; ?></td>
                                                <td><?=$results['caste']; ?></td>
                                                <td><?=$results['certificate_no']; ?></td>
                                                <td><?=$results['p_state']; ?></td>
                                                <td><?=$results['p_homeTown']; ?></td>
                                                <td>
                                                <?php if($results['appearingStatus'] == 1){
                                                    echo 'Yes';
                                                }else{
                                                    echo 'No';
                                                }
                                                ?>
                                                </td>

                                                 <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                 <td><?=$results['name']; ?></td>
                                                 <?php
                                                 
                                                 $valuecourse = $valueCourseData->getRecordBystuid($results['stu_id']);
                                                  if(count($valuecourse)){
                                           $results['course_name1'] = isset($valuecourse[0]['course_name'])?$valuecourse[0]['course_name']:" ";
                                           $results['course_name2'] = isset($valuecourse[1]['course_name'])?$valuecourse[1]['course_name']:" ";
                    
                    $result[$key]["Semester-I"] = isset($valuecourse[0]['semester'])?$valuecourse[0]['semester']:" ";
                    $result[$key]["Semester-II"] = isset($valuecourse[1]['semester'])?$valuecourse[1]['semester']:" ";
                    }
                                                 ?>
                                                 
                                                 <td><?=$results['course_name1']; ?></td>
                                                 <td><?=$results['course_name2']; ?></td>
                                                 <td><?php if($edu_details['core_course1']){echo $deptinfo->getRecordbyAcademic($edu_details['core_course1'])['dpt_name'];}else{echo '--';}?></td>
                                                       
                                                <td><?php if($edu_details['ge1']){echo $geinfo->getRecord($edu_details['ge1'])['general_elective_name'];}else echo '--'; ?></td>
                                                 <td><?= !empty($edu_details['aecc1'])?$edu_details['aecc1']:'--'?></td>
                                                
                                             
                                              <td>
                                                  <b>Village:</b> <?= $results['p_address'] ?>,<b>Post-Office:</b><?= $results['p_postOffice'] ?>,<b>Police St.</b>:<?= $results['p_policeSt'] ?>,<b>District:</b><?= $results['p_district'] ?>,<b>State</b>:<?= $results['p_state'] ?>,<b>Pin Code:</b><?= $results['p_code_number'] ?>
                                              </td>

                                              <td >
                                                   <b>Village:</b> <?= $results['l_address'] ?>,<b>Post-Office:</b><?= $results['l_postOffice'] ?>,<b>Police St.</b>:<?= $results['l_policeSt'] ?>,<b>District:</b><?= $results['l_district'] ?>,<b>State</b>:<?= $results['l_state'] ?>,<b>Pin Code:</b><?= $results['l_code_number'] ?>
                                              </td>
                                              
                                              
                                              <?php if($this->degree_id == 1){?>
                                              <td>
                                                <?=  !empty($results['school'])?$results['school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_board'])?$results['i_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_roll'])?$results['i_roll']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['obt_marks'])?$results['obt_marks']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['total_marks'])?$results['total_marks']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['percent'])?$results['percent']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_division'])?$results['i_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['subject'])?$results['subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_pass_year'])?$results['i_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['l_institution'])?$results['l_institution']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['l_place'])?$results['l_place']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['last_board'])?$results['last_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['l_p_year'])?$results['l_p_year']:'N/A' ?>
                                              </td>
                                              
                                              <?php }else { ?>
                                              <td>
                                                <?=  !empty($results['mat_school'])?$results['mat_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['mat_board'])?$results['mat_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['mat_division'])?$results['mat_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['mat_subject'])?$results['mat_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['mat_pass_year'])?$results['mat_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['school'])?$results['school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_board'])?$results['i_board']:'N/A' ?>
                                              </td>   
                                              
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_division'])?$results['i_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['subject'])?$results['subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['i_pass_year'])?$results['i_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['grad_school'])?$results['grad_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_board'])?$results['grad_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_division'])?$results['grad_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_subject'])?$results['grad_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_pass_year'])?$results['grad_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['other_school'])?$results['other_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['other_board'])?$results['other_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['other_division'])?$results['other_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['other_subject'])?$results['other_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['other_pass_year'])?$results['other_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['bca_school'])?$results['bca_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['bca_board'])?$results['bca_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['bca_division'])?$results['bca_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['bca_subject'])?$results['bca_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['bca_pass_year'])?$results['bca_pass_year']:'N/A' ?>
                                              </td>
                                              <td>
                                                <?=  !empty($results['grad_math_school'])?$results['grad_math_school']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_math_board'])?$results['grad_math_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_math_division'])?$results['grad_math_division']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_math_subject'])?$results['grad_math_subject']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['grad_math_pass_year'])?$results['grad_math_pass_year']:'N/A' ?>
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['l_institution'])?$results['l_institution']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['l_place'])?$results['l_place']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['last_board'])?$results['last_board']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['l_p_year'])?$results['l_p_year']:'N/A' ?>
                                              </td>
                                              <?php } ?>
                                              
                                              <td> 
                            <a class="btn btn-info"  href="<?php echo $this->mainconfig['host']; ?>student/admission-card/a_id/<?php echo $results['stu_id']; ?> " target="_blank">Admission Card </a>
                        </td>
                         
                         <td><img class="img img-rounded pull-right" src="<?= $this->baseUrl($results['photo']); ?>" width="100px" alt="img" /></td>
                        
                         <td>
                             <a class="pdf" href="<?php echo $this->mainconfig['host']; ?>student/student-details/type/downloads/stu_id/<?php echo $results['stu_id']; ?>" class="Download" title="Download"><button type="button" class="btn btn-download">Download Img</button></a>
                         </td>
                         <td>
                            <?php 
                            switch ($result['stu_status']) {
                                case 1:
                                  echo '<b style="color:green">Active</b>';
                                  break;
                                case 2:
                                  echo '<b style="color:red">Discontinue</b>';
                                  break;
                                case 3:
                                  echo '<b style="color:red">T.C.</b>';
                                  break;
                                case 4:
                                  echo '<b style="color:yellowgreen">Alumni</b>';
                                  break;
                                case 5:
                                  echo '<b style="color:orange">Left</b>';
                                  break;
                                
                                default:
                                  echo "n/a";
                            }
                            ?>
                        </td>
                        </tr>            

                                            <?php

                                        }
                                        else
                                        { ?>
                                        
                                        
                                              <tr>

                                                <td>
                                                    <?php
                                                        echo $i;
                                                        $i++;
                                                        $results = $result;
                                                    ?>
                                                </td>
                                                <td><?php echo $results['stu_fname'];?></td>
                                                <td><?php echo $results['stu_id'];?></td>
                                                <td><?php echo $results['roll_no'];?></td>
                                                <td><?php echo $results['stu_dob'];?></td>
                                                <td>
                                                  <?php 
                                                  $str = substr($this->year,2).'PWC';
                                                  $isReadmission = stripos($results['reg_no'],$str); ?>
                                                 <?=is_numeric($isReadmission)?"ONLINE":"Readmission";?>
                                                </td>
                                                <td><?=$results['amount1']; ?></td>
                                                <td><?=is_numeric($isReadmission)?"NEFT":"Fee Waive";?></td>
                                                <td><?=$results['date_time1']; ?></td>
                                                <td><?=$results['father_fname']; ?></td>
                                                <td><?=$results['stu_aadhar']; ?></td>
                                                <td><?=$results['blood_group']; ?></td>
                                                <td>--</td>
                                                <td><?=$results['stu_nationality']; ?></td>
                                                <td><?=$results['stu_email_id']; ?></td>
                                                <td><?=$results['father_mobileno']; ?></td>
                                                <td><?=$results['mother_fname']; ?></td>
                                                <td>--</td>
                                                <td><?=$results['cast_category']; ?></td>
                                                <td><?=$results['stu_caste']; ?></td>
                                                <td>--</td>
                                                <td>--</td>
                                                <td>--</td>
                                                <td>
                                                --
                                                </td>

                                                 <td><?=$results['department_type']; ?></td>
                                                 <td><?=$results['department']; ?></td>
                                                       
                                                <td>--</td>
                                                 <td>--</td>
                                                
                                             
                                              <td>
                                                  <?= $results['present_addr'] ?>
                                              </td>

                                              <td >
                                                   <?= $results['premanent_addr'] ?>
                                              </td>
                                              
                                              
                                              <?php if($this->degree_id == 1){?>
                                              <td>
                                                --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                                --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                              --
                                              </td>
                                              
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                              --
                                              </td>
                                              
                                              <?php }else { ?>
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                            --
                                              </td>
                                              
                                              <td>
                                            --
                                              </td>  
                                              <td>
                                               --
                                              </td>   
                                              
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                                --
                                              </td>  
                                              <td>
                                                --
                                              </td>
                                              
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                               --
                                              </td>
                                              
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                             --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                             --
                                              </td>
                                              
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                                --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                              --
                                              </td>
                                              <td>
                                               --
                                              </td>  
                                              <td>
                                             --
                                              </td>  
                                              <td>
                                              --
                                              </td>  
                                              <td>
                                             --
                                              </td>  
                                              <td>
                                               --
                                              </td>
                                              
                                              <td>
                                                <?=  !empty($results['institution'])?$results['institution']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['place_of_exam'])?$results['place_of_exam']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['university'])?$results['university']:'N/A' ?>
                                              </td>  
                                              <td>
                                                <?=  !empty($results['last_exam_year_passing'])?$results['last_exam_year_passing']:'N/A' ?>
                                              </td>
                                              <?php } ?>
                                              <td> 
                                                 <?=is_numeric($isReadmission)?"--":"N/A";?>
                                            </td>
                         
                         <td><img class="img img-rounded pull-right" src="<?= $this->baseUrl($results['filename']); ?>" width="100px" alt="img" /></td>
                        
                         <td>
                         </td>
                         <td>
                            <?php 
                            switch ($results['stu_status']) {
                                case 1:
                                  echo '<b style="color:green">Active</b>';
                                  break;
                                case 2:
                                  echo '<b style="color:red">Discontinue</b>';
                                  break;
                                case 3:
                                  echo '<b style="color:red">T.C.</b>';
                                  break;
                                case 4:
                                  echo '<b style="color:yellowgreen">Alumni</b>';
                                  break;
                                case 5:
                                  echo '<b style="color:orange">Left</b>';
                                  break;
                                
                                default:
                                  echo "n/a";
                            }
                            ?>
                        </td>

                                            </tr>            
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        
                                        <?php } ?>
                                        
                                        
                                        
                                        <?php }
                                       

                                    }

                                    ?>

                                </tbody>

                            </table>

                        <div class="row">
                                <div class="col-md-offset-3 col-md-3 text-right"><button class="downloadAll btn btn-primary" type ="button" id="download_pdf">Download <i class="fa fa-download"></i></button></div>
                                <div class=" col-md-3 text-left"><button class="cancel btn btn-primary" type ="button" >Stop <i class="fa fa-close"></i></button></div>
                            </div>
                    </div>
<?php } else { ?>
                    
        <div class="row">
            <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                <h3 class="page-title txt-color-blueDark">
                    <i class="fa fa-bars">Participants Details</i>

                </h3>
            </div>
        </div>
        <div class="panel panel-default">
        <div class="panel-body cont">
           
                <div class="x_title">
                    <div class="row">
                        <div class="col-sm-3 pul-right ">
                            <!--<label class="control-label">Academic Year<span class="asterisk">*</span></label>-->
                            <div class="form-group">
                                <?php echo $this->form->academic_year_list; ?>
                            </div>   
                        </div>
                        <div class="col-sm-3 pul-right ">
                            <!--<label class="control-label">Session <span class="asterisk">*</span></label>-->
                            <div class="form-group">
                                <?php echo $this->form->session; ?>
                            </div>
                           
                        </div>
                        <div class="col-sm-3 ">
                            
                        <button type="button" id="getRecord" class="btn btn-primary" style="float: left" value="0" >Get Record</button>
                        </div>
                       
                        
                    
                </div>
                <div  id="ajaxData"> 
            <table class="table table-striped table-bordered mb30 jambo_table bulk_action " id="dataTable">
        <thead>
            <tr>
                <th>S.No.</th>
                <th style="width: 15em">Department </th>
                <th style="width: 15em">No. Of Active Students</th>
                <th>No. of Left Students</th>
                <th>Total Students</th>
                <th>View Students</th>
                
            </tr>
        </thead>
        <tbody>
        </tbody>
            </table>
                </div>
                </div>
            </div>
    <?php } ?>
        </div>
        </div>  
        </div>
    </div>
    </div>
<script>
    $('body').on('change', '#academic_year_list', function () {
        $('#department').removeAttr('disabled');
        var year_id = $('#academic_year_list').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });

    //Added: By Kedar 13 Nov. 2019
    $(document).on('click','#getRecord',function() { 
        var session_id = $('#session').val();
        if (session_id) {
            $('.load-box').css('display','block');
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student/ajax-get-dept-wise-student-count'; ?>',
                data: {session_id: session_id}
            }).done(function (data) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
            });
        }
    });
    //End
    //Get Batch By Session
    $('body').on('change', '#session', function () {
    //alert('jj');
        var year_id = $('#session').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#academic_id').empty('');
                $('#academic_id').html(data);
                $('#academic_id').trigger("chosen:updated");
            });
        }
    });
    
    
    $(document).ready(function () {
            $('#dataTable').DataTable();
            $("[id$=myButtonControlID]").click(function (e) {
                window.open('data:application/vnd.ms-excel,' + encodeURIComponent($('div[id$=divTableDataHolder]').html()));
                e.preventDefault();
            });
        });


    //End
</script>
