
<div class="right_col">
    <?php if ($_SESSION['update_message']) { ?>

        <div class="alert alert-success ">
            <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $_SESSION['update_message'];
            unset($_SESSION['update_message']); ?>

        </div> 
    <?php } ?>

    <?php if ($this->type) { ?>

<?php } else { ?>

        <div class="load-box">
            <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
        </div>  
        <div class="row">
            <div class="col-md-12">
                <h3 class="page-title txt-color-blueDark" >
                    <i class="fa fa-bars"> Download Bulk T.C. Certificates </i> 
                </h3>
                <div class="panel panel-default">
                    <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                        <div class="panel-body">
                            <div class="row">
                            <div class="col-xs-6 pull-left" style="padding-left : 0 ; margin-left: 0;"> 
                                            <div class="col-xs-3 pull-left" style="padding-left : 0 ; margin-left: 0;"><p>Min Sl No. <span class="asterisk"></span> <input type="number" id="manualmin" autocomplete="off"> </p></div>
                                            <div class="col-xs-3 pull-left" style="padding-left : 0 ; margin-left: 0;"><p>Max Sl No. <span class="asterisk"></span><input type="number" id="manualmax" autocomplete="off"></p></div>
                                            
                                            </div>
                        </div>
                            <div class="row">

                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <!--<label class="control-label">Academic Year<span class="asterisk">*</span></label>-->
    <?php echo $this->form->academic_year; ?>
                                    </div>
                                </div> 
                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <!--<label class="control-label">Session<span class="asterisk">*</span></label>-->
    <?php echo $this->form->session; ?>
                                    </div>
                                </div> 
                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <!--<label class="control-label">Batch<span class="asterisk">*</span></label>-->
    <?php echo $this->form->academic_year_id; ?>
                                    </div>
                                </div> 

                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <!--<label class="control-label">Participant Name</label>-->
    <?php echo $this->form->stu_id; ?>
                                    </div>
                                </div>


                            </div>
                            <div class="row">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        <label class="control-label">&nbsp;</label>
                                        <input type="text" id="batch" class="form-control" style="background-color:#fdf59a;"  readonly />
                                    </div>
                                </div>
                            </div>
                            <div id="getstudent" class="col-sm-12">
                            </div>
                            <div class="row">
                                <div class="col-md-offset-3 col-md-3 text-right"><button class="downloadAll btn btn-primary" type ="button" id="download_pdf">Download <i class="fa fa-download"></i></button></div>
                                <div class=" col-md-3 text-left"><button class="cancel btn btn-primary" type ="button" >Stop <i class="fa fa-close"></i></button></div>
                            </div>
                        </div>

                    </form>
                </div><!-- /panel -->
            </div><!-- /.col-->				
        </div><!-- /.row -->

        <div class="panel panel-default"> 

            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <h3 class="page-title txt-color-blueDark">
                            <i class="fa fa-bars"> Download Individual T.C. Certificate by Form Id </i>

                        </h3>
                    </div>
                </div>
                <div class="panel-body cont">
                </div>
                <div class="col-md-12">

                    <span id="updatemsg" style="color:green;"></span>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label" style="float:left;">Enter Your Form Id:<span class="asterisk">*</span></label>-->
                            <input type="text" name="form_id" id="form_id" value="" class="form-control" placeholder="Enter Your Form Id" pattern="\d+" title="xxx.." autocomplete="off">
                        </div>
                    </div>
                    <div>
                        <button class="btn btn-primary submit" id="otpInfo">Submit</button>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="table-responsive" id="studentData"> 

                    </div>
                </div>

            </div>    


        </div>

    </div></center>


    <?php
}
?>

<script>
    //Ajax to update Offline Roll no  date:23 Jan. 2023
    $("#otpInfo").click(function () {
        //alert('kk');
        var form_id = $('#form_id').val().trim();
        if (form_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student/ajax-get-student-Info'; ?>',
                data: {form_id: form_id}
            }).done(function (data) {
                $('#studentData').empty('');
                $('#studentData').html(data);
            });
        }
    });

    $('body').on('change', '#academic_year_id', function () {
        $('.load-box').css('display', 'block');
        getstudentDetails();
    });
    function getstudentDetails() {
        $url = '<?php echo $this->mainconfig['host']; ?>student/get-student-tc-card';
        $.post($url,
                {
                    'academic_id': $('#academic_year_id').val(),
                    'year_id': $('#year_id').val(),
                    'term_id': $('#term_id').val(),
                    'stu_id': $('#stu_id').val()
                })
                .done(function (data) {

                    //$('#payslipData').html('');
                    $('.load-box').css('display', 'none');
                    $('#getstudent').empty();
                    $('#getstudent').html(data);
                   setDatatablesManual();

                });

    }

    $("#academic_year_id").change(function () {
        var academic_year_id = $("#academic_year_id").val();

        if (academic_year_id != '') {
            $('.load-box').css('display', 'block');
            $.ajax({
                type: "POST",
                url: "<?php echo $this->mainconfig['host'] . 'report/ajax-get-student-details'; ?>",
                data: {academic_year_id: academic_year_id}
            }).done(function (data) {
                //alert(data);	
                $("#stu_id").html(data);

                $('.load-box').css('display', 'none');
            });
        }
    });

    $('body').on('change', '#academic_year_id', function () {
        var academic_id = $('#academic_year_id').val();
        if (academic_id) {
            $('#batch').show();
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch-code'; ?>',
                data: {academic_id: academic_id}
            }).done(function (data) {
                var result = $.parseJSON(data);
                if ((data != '')) {
                    $('#batch').val(result['short_code']);
                }
            });
        }

    });

    //for bulk download action to update stu_status as t.c
    // $("#download_pdf").click(function () {
    //     var academic_id = $('#academic_year_id').val();
    //     if (academic_id) {
    //         $.ajax({
    //             type: "POST",
    //             url: '<?php echo $this->mainconfig['host'] . 'student/ajax-update-tc-status'; ?>',
    //             data: {academic_id: academic_id}
    //         }).done(function (data) {
    //         });
    //     }
    // });
    //To filter Session
    $('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    //Get Batch By Session
    $('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#academic_year_id').empty('');
                $('#academic_year_id').html(data);
                $('#academic_year_id').trigger("chosen:updated");
            });
        }
    });
    //End
    
     var table = '';
   
    function setDatatablesManual() {
        $.fn.dataTable.ext.search.push(
                function (settings, data, dataIndex) {
                    var min = parseInt($('#manualmin').val(), 10);
                    var max = parseInt($('#manualmax').val(), 10);
                    var age = parseFloat(data[0]) || 0; // use data for the age column

                    if ((isNaN(min) && isNaN(max)) ||
                            (isNaN(min) && age <= max) ||
                            (min <= age && isNaN(max)) ||
                            (min <= age && age <= max))
                    {
                        return true;
                    }
                    return false;
                }
        );

        table = $('#datatable-responsive').DataTable({
            "pageLength": -1,

        });
    }

    // Event listener to the two range filtering inputs to redraw on input
    $('#manualmin, #manualmax').keyup(function () {
        //alert("hello");
        table.draw();
    });

    $('#manualmin, #manualmax').change(function () {
        //alert("hello");
        table.draw();
    });

    //End
</script>