<?php if(!empty($this->paginator)){ 
    
    //echo '<pre>'; print_r($this->paginator);exit;
?>
   

                                                 
                                                 
  
<style>
     @page {
        background: url('https://pwcadmissions.in/academic/public/images/Certificate_watermark/TC.jpg') no-repeat 0 0;
        background-image-resize: 6;
   
     }
   
@media print {
  
  button,fieldset{
      position:fixed !important;
      display:none !important;
  }
  
  
    #applicationFormPreview{
        padding-left: 2em;
        padding-right:2em;
        position:absolute !important;
        top:0px !important;
        width:100%;
    }
   
    .table td{
         border:.01em solid #932e90;
         font-size:15px;
    }
  .pagebreak {
       clear: both;
      page-break-after: always; }
  

 @page 
    {
        position:absolute !important;
        size:  auto;   /* auto is the initial value */
        margin: 1mm;
        margin-top:0; 
       /* this affects the margin in the printer settings */
    }   
    
</style>
<div class="right_col">
<div class="appForm" id="applicationFormPreview">
<div class="" id="applicationFormPreview">
       <div style="float:right;padding-bottom: 3em;" id="divbutton">
            <button type="button" id="printAppForm2"  class="btn btn-primary" onclick="window.print()"></button>
        </div>
 
        <div class="row" id="section-to-print">
        
                
            <table id='a' class=" table-striped table-bordered mb30 jambo_table bulk_action " >

                <thead>
                    <tr>
                       
                    </tr>
                </thead>
                <tbody>
                   
                    <tr>
                        <td class="col-sm-2 col-sm-offset-1">
                            <div class="form-group">
                                 <img src="<?php echo $this->mainconfig['publicpath']; ?>img/logo.png" width="120" height="130">          
                            </div>
                        </td>
                       

                        <td class="col-sm-10" style="text-align: center;">
                            <div class = 'sub' style="text-align: center;">
                                <h4> PATNA WOMEN'S COLLEGE</h4>
                                <h5>AUTONOMOUS</p></h5>
                                <h4>PATNA UNIVERSITY</h4>
                                <h5>3rd Cycle NAAC Accredited at A Grade with CGPA 3.58/4</h5>
                                <h5>College with Potential for Excellence(CPE) status accorded by UGC</h5>
                                <h5> BAILEY ROAD,PATNA - 800 001, BIHAR</h5>
                                
                        </div>
                        </td>
                         
                        
           

                    </tr>
                  
                </tbody>
            </table>
                <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action "cellspacing ="0"  width="100%" style="margin-top:50px">

                    
                    <tbody>
                        <tr style="display:none">
                            <td style="text-align: left"> <b>T.C. NO. <?= !empty($this->paginator['tc_number'])?$this->paginator['tc_number']: '--' ; ?>  </b></td>
                            <td style="text-align: right"> <b>Date:  <?= !empty($this->paginator['effective_date'])? date("d/m/Y") : date("d/m/Y") ; ?> </b></td>
                        </tr>
                         <tr >
                            <td style="text-align: center" colspan="2"> <b>COLLEGE LEAVING CERTIFICATE (CLC) </b></td>
                        </tr>
                       
                        <tr>
                           
                             <td style="width:25em;">
                                Candidate's Name 
                            </td>
                            <td >                                                                 
                                <?php echo $this->paginator['stu_fname'];?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Father's Name 
                            </td>
                            <td >                                                                 
                                <?php echo $this->paginator['father_fname'];?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Mother's Name 
                            </td>
                            <td >                                                                 
                                <?php echo $this->paginator['mother_fname'];?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                College Roll No.
                            </td>
                            <td >                                                                 
                                <?php echo $this->paginator['roll_no'];?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Aadhar No.
                            </td>
                            <td >                                                                 
                                <?= !empty($this->paginator['stu_aadhar']) ?$this->paginator['stu_aadhar']:'N/A' ;?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Session
                            </td>
                            <td >                                                                 
                                <?= !empty($this->paginator['session_for_tc']) ?$this->paginator['session_for_tc']:$this->paginator['session'] ;?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                College U_ID
                            </td>
                            <td >                                                                 
                               <?php echo $this->paginator['stu_id'];?>
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Date of Birth (as entered in the admission register) 
                            </td>
                            <td >                                                                 
                                <?php echo $this->paginator['stu_dob'];?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Nationality 
                            </td>
                            <td >                                                                 
                               <?= !empty($this->paginator['stu_nationality']) ?$this->paginator['stu_nationality']:'Indian' ;?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Date of Admission 
                            </td>
                            <td >                                                                 
                                <?= !empty($this->paginator['stu_doA']) ?$this->paginator['stu_doA']:'N/A' ;?>
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Class to which admitted 
                            </td>
                            <td > 
                                <?php 
                                    switch ($this->paginator['adm_sem']) {
                                       case "t1":
                                          echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-1</b>':'N/A' ;
                                          break;
                                        case "t2":
                                          echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-2</b>':'N/A' ;
                                          break;
                                        case "t3":
                                            echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-3</b>':'N/A' ;
                                          break;
                                        case "t4":
                                           echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-4</b>':'N/A' ;
                                          break;
                                        case "t5":
                                           echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-5</b>':'N/A' ;
                                          break;
                                        case "t6":
                                           echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'Mb> Semester-6 </b>':'N/A' ;
                                          break;
                                        default:
                                          echo "n/a";
                                    }
                                ?>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Class in which studied at the time of leaving
                            </td>
                            <td >                                                                 
                               
                                <?php 
                                    switch ($this->paginator['leaving_sem']) {
                                        case "t1":
                                          echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-1</b>':'N/A' ;
                                          break;
                                        case "t2":
                                          echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-2</b>':'N/A' ;
                                          break;
                                        case "t3":
                                            echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-3</b>':'N/A' ;
                                          break;
                                        case "t4":
                                           echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-4</b>':'N/A' ;
                                          break;
                                        case "t5":
                                           echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-5</b>':'N/A' ;
                                          break;
                                        case "t6":
                                           echo !empty($this->paginator['dept_name']) ?$this->paginator['dept_name'].'<b> Semester-6 </b>':'N/A' ;
                                          break;
                                        default:
                                          echo "n/a";
                                    }
                                ?>
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Course Studied
                            </td>
                            <td > 
                                <?php 
                                $deptStack= array('30','31','32','33','35','39');
                                if (in_array($this->paginator['dept_id'], $deptStack, TRUE) ||  $this->paginator['dept_id'] == 15 ){ ?>
                                    <?= !empty($this->paginator['batch']) ?$this->paginator['batch']:'N/A' ;?> 
                                <?php } else if($this->paginator['dept_id']==14){ ?>
                                    <?= !empty($this->paginator['batch']) ? trim($this->paginator['batch']).' in ACCOUNTING':'N/A' ;?>
                                <?php } else {  ?>
                                  <?= !empty($this->paginator['batch']) ?$this->paginator['batch']:'N/A' ;?> in <?= !empty($this->paginator['dept_name']) ?trim($this->paginator['dept_name']):'N/A' ;?>
                                <?php }?>   
                            </td>   
                        </tr>
                        <tr>
                           
                            <td style="width:10em;">
                                Whether qualified for promotion to higher class
                            </td>
                            <td > 
                                <?php
                                /*$cgpa= round($this->paginator['total_grade']/$this->paginator['total_credit']);
                                if($cgpa <  6 || $this->paginator['failed_count'] > 0 ){
                                    echo 'No';
                                }else{
                                    echo 'Yes';
                                }*/
                                switch($this->paginator['is_promoted']){
                                    case 1:
                                        echo 'Yes';
                                        break;
                                    case 2:
                                        echo 'No';
                                        break;
                                    default:
                                        break;
                                } 
                                ?>    
                            </td>   
                        </tr>
                        
                        <tr>
                           
                            <td style="width:10em;">
                                Course Completed
                            </td>
                            <td >                                                                 
                               <?php
                                /*$cgpa= round($this->paginator['total_grade']/$this->paginator['total_credit']);
                                if($cgpa <  6 || $this->paginator['failed_count'] > 0 ){
                                    echo 'No';
                                }else{
                                    echo 'Yes';
                                }*/
                                  switch($this->paginator['is_course_completed']){
                                    case 1:
                                        echo 'Yes';
                                        break;
                                    case 2:
                                        echo 'No';
                                        break;
                                    default:
                                        break;
                                } 
                                ?>
                            </td>   
                        </tr>
                        
                        <tr>
                           
                            <td style="width:10em;">
                                Whether all the dues to the College have been paid
                            </td>
                            <td >                                                                 
                                <?php 
                                 switch($this->paginator['is_fee_paid']){
                                    case 1:
                                        echo 'Yes';
                                        break;
                                    case 2:
                                        echo 'No';
                                        break;
                                    default:
                                        break;
                                } 
                                ?>
                                  
                            </td>   
                        </tr>
                        
                        <tr>
                           
                             <td style="width:10em;">
                                Name of the University Examination for which the Student has been last appeared from the College
                            </td>
                            <td >
                                <?php 
                                
                               $deptStack= array('30','31','32','33','35','39');
                                if (in_array($this->paginator['dept_id'], $deptStack, TRUE) ){ ?>
                                    
                                <?= !empty($this->paginator['name_of_university_exam'])?trim($this->paginator['name_of_university_exam']) : trim($this->paginator['batch']) ?>   
                               <?php }else if($this->paginator['dept_id']== 14){ ?>
                                   <?= !empty($this->paginator['name_of_university_exam'])?trim($this->paginator['name_of_university_exam']) : trim($this->paginator['batch']).' in ACCOUNTING'; ?>
                               <?php } else {  ?>
                               <?= !empty($this->paginator['name_of_university_exam'])?trim($this->paginator['name_of_university_exam']) : $this->paginator['batch'].' in '. trim($this->paginator['dept_name']) ?>   
                                <?php } ?>  
                            </td>   
                        </tr>
                        <tr>
                           
                             <td style="width:10em;">
                               Registration No. 
                            </td>
                            <td >                                                                 
                                <?= !empty($this->paginator['reg_no']) ?$this->paginator['reg_no']:'N/A' ;?>  
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                             <td style="width:10em;">
                                Examination Roll No.
                            </td>
                            <td >                                                                 
                                <?= !empty($this->paginator['exam_roll']) ?$this->paginator['exam_roll']:'N/A' ;?>  
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                             <td style="width:10em;">
                                Year of Examination 
                            </td>
                            <td >                                                                 
                                <p>
                                    <?= !empty($this->paginator['name_of_exam']) ?$this->paginator['name_of_exam']:'N/A' ;?> 
                                    <?php //!empty($this->paginator['last_exam_date'])? $this->paginator['last_exam_date']:'N/A' ;?>  
                                </p>
                                  
                            </td>   
                        </tr>
                        <tr>
                           
                             <td style="width:10em;">
                                Result of the Examination Grade with CGPA
                            </td>
                            <td>  
                            <?php  
                      //    echo "<pre>"; print_r($this->paginator);exit;
                         echo $this->paginator['result_of_exam'];
                           // echo $letter_grade['letter_grade'].' with CGPA: '.number_format($Actualcgpa,2); 
                           ///echo number_format($this->paginator['cgpa'],2); 
                         ?> 
                               <?php
                            //     $cgpa= number_format($this->paginator['total_grade']/$this->paginator['total_credit'],2);
                            //      if($cgpa <  6 || $this->paginator['failed_count'] > 0 ){
                            //       echo 'Pending';
                            //     }else{
                                    
                            //          switch ($cgpa) {
                            //             case "10":
                            //               $grad= "Grade (O)";
                            //               break;
                            //             case "9":
                            //               $grad= "Grade (A+)";
                            //              break;
                            //             case "8":
                            //               $grad= "Grade (A)";
                            //               break;
                            //             case "7":
                            //              $grad= "Grade (B)";
                            //               break;
                            //             case "6":
                            //              $grad= "Grade (C)";
                            //              break;
                            //             case "5":
                            //              $grad= "Grade (C)";
                            //              break;
                            //           default:
                            //               $grad= " ";
                            //         }
                            //       echo $grad.' with CGPA: '.$cgpa;
                            //   }
                                
                               ?>
                                  
                            </td>   
                        </tr>
                        <tr>
                       
                            
            </tr>
             
           <tr>
                <th class="sub" colspan="1"></th>
                <th class="sub"><img src="<?php echo $this->mainconfig['publicpath']; ?>images/principal.jpg" alt="..."  height ="40" width="200"></th>
            </tr>
            <tr>
               <th class="sub" colspan="1"></th>
               <th class="sub">(Dr. Sister M. Rashmi A.C.)</th> 
            </tr>   
            <tr>
               <th class="sub" colspan="1"></th>
               <th class="sub">Principal</th> 
            </tr>   
            </tbody>
           </table>
            
        </div>
     
</div>
</div>
</div>
<?php }else{ ?>   

<div class="right_col">
    <label id="alert_msg" style="color:red; ">
       Class Roll Number is not generated!   
    </label> 
    
</div>
<?php  } ?>                                         