<?php
//echo "<pre>";print_r($this->category_data);die;
?>
<style>
    input { 
        text-align: center; 
    }

    input:focus{
        border:2px solid #00ed22;

    }
</style>
<?php
$attendanceCheck = array(
    '0' => 'Allowed',
    '1' => 'Not Allowed'
);
//echo "<pre>"; print_r($attendanceCheck);
?>
<div style="overflow-x:scroll">
    <div class="padding-md clearfix">

        <div class="col-sm-0" style="float:right;">
            <a class="btn btn-link" role="button" href="#" id="print"><span class='glyphicon glyphicon-print'></span></a>
        </div>
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="dataTable" style="height:100%;">

            <thead>
                <tr>
                    <th style="width:2%">S.No.</th>
                    <th style="width:5%">Participants Name</th>
                    <th style="width:2%">Roll No.</th>
                    <th style="width:2%">Exam Roll</th>
                    <th style="width:2%">Batch </th>
                    
                    <th style="width:5%"> UID</th>



                    <th style="width:5%" >Present</th>
                    <th style="width:5%"> Absent</th>  
                </tr>
            </thead>
            <tbody>
                <?php
                if (!empty($this->result)){
                    $i = 1;
                
                    foreach ($this->result as $k => $result) {
                        //echo "<pre>";print_r($result);exit;
                        ?>
                        <tr>
                            <td><?php echo $i;
                        $i++;
                        ?>
                            </td>
                            <td><?php echo $result['student_name']; ?></td> 
                    <input type="hidden" name="stu_id[]" id="student_id" value="<?php echo $result['student_id']; ?>" /> 
                    <input type="hidden" name="grade[academic_id_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" id="term_id1" value="<?php echo $result['academic_id']; ?>" />
                    <input type="hidden" name="grade[term_id_<?php echo $result['student_id']; ?>_<?php echo $result['grade_id']; ?>][]" id="academic_id1" value="<?php echo $result['term_id']; ?>" />
                    <input type="hidden" name="u_id[]" id="student_id" value="<?php echo $result['stu_id']; ?>" />
                    <td><?php echo $result['roll_no']; ?></td> 	
                   	
                    <td><?php echo $result['stu_id']; ?></td> 
                    <td style="text-align:center; "><input style="zoom:1.5" name="class<?=$dcl;?><?=$i;?>"  <?=${"class_".$dcl."_P"} ;?> type="radio" value="<?=$item_result[count($item_result)-1]['course_id'];?>"/></td>
                                                    <td style="text-align:center; "><input style="zoom:1.5" <?=${"class_".$dcl."_A"} ;?> name="class<?=$dcl;?><?=$i;?>" type="radio" value="Absent"/></td>
                    <!--[Ashutosh]-->
                <?php } } ?>
        <?php if (isset($this->category_data) ){
         $i = 1;
              $attendInc=0;
        foreach ($this->category_data as $key => $val) { 
                     //echo "<pre>";print_r($val);exit; ?>
                        <tr>
                            <td><?php echo $i; ?></td>
                            
                            <td><?php echo $val['students']; ?></td> 
                        <input type="hidden" name="stu_id[]" id="student_id" value="<?php echo $val['student_id']; ?>" /> 
                        <input type="hidden" name="grade[student_id][]" id="student_id" value="<?php echo $val['student_id']; ?>" />
                        <input type="hidden" name="grade[academic_id_<?php echo $val['student_id']; ?>][]" id="term_id1" value="<?php echo $val['academic_id']; ?>" />
                        <input type="hidden" name="grade[term_id_<?php echo $val['student_id']; ?>][]" id="academic_id1" value="<?php echo $val['term_id']; ?>" />
                        <input type="hidden" name="u_id[]" id="student_id" value="<?php echo $val['stu_id']; ?>" />
                        <td><?php echo $val['roll_no']; ?></td> 	
                        <td><?php echo $val['exam_roll']; ?></td> 	
                         <input type="hidden" name="batch_code[]" id="batch_code" value="<?php echo $val['short_code']?$val['short_code']:$val['batch']; ?>" />
                        <td><?php echo $val['short_code']?$val['short_code']:$val['batch']; ?></td> 		

                        <td><?php echo $val['stu_id']; ?></td>
                       
                        <td style="text-align:center; " id="present" ><input style="zoom:1.5" name="attendStatus[<?=$attendInc;?>]"  type="radio" value="1" <?= $val['attend_status']==1?'checked':'checked'?> /></td>
                        <td style="text-align:center; " id="absent"><input style="zoom:1.5"  name="attendStatus[<?=$attendInc;?>]" type="radio" value="2"  <?= $val['attend_status']== 2?'checked':'' ?>/> </td>
                        </tr>
        <?php  $i++; $attendInc++;}
        
    }
    
?>
                     
                        
            </tbody>
            <tfoot>
            <tr>
                <td colspan="6"></td>
                <td  id="present_count" style="text-align:center;font-size: 2em;"></td>
                <td id="absent_count" style="text-align:center;font-size: 2em;" > </td>
            </tr> 
            </tfoot>
        </table>
    </div>
</div>

<script>
    // dt._datatablesSettings._range = 2
    // setDatatables();
    var presentCount = [];
    
const min =    $('#min').val();
const max =     $('#max').val();

const totcount = parseInt(max) - parseInt(min);
    
    var absentCount = [];
    $('.dataTable tr').each(function(){
        $('#present', this).each(function(index, val){
         var check = $(this).find(':radio:checked').length;
        if(!presentCount[index]) presentCount[index] = 0;
              presentCount[index] += parseInt(check);

        
        });
          
    }); 
    
    $('.dataTable tr').each(function(){
        $('#absent', this).each(function(index, val){
          
         var check = $(this).find(':radio:checked').length;
        if(!absentCount[index]) absentCount[index] = 0;
              absentCount[index] += parseInt(check);
      
        });
     
    });
    $('#present_count').html(presentCount);
    
    $('#absent_count').html(absentCount);
    
    
    
if(totcount > 0){
    $('#present_count').text(totcount);
}
    
    $('.dataTable tr input[type="radio').change(function(){
   
        var $checkboxesAbsent = $('.dataTable tr #absent input[type="radio"]');
       
            var countCheckedCheckboxesAbsent = $checkboxesAbsent.filter(':checked').length;
            $('#absent_count').text(countCheckedCheckboxesAbsent);
        
 
        var $checkboxesPresent= $('.dataTable tr #present input[type="radio"]');
       
            var countCheckedCheckboxesPresent = $checkboxesPresent.filter(':checked').length;
            $('#present_count').text(countCheckedCheckboxesPresent);
       
    });
    
    
    
    $("#max,#min").keyup(()=>{
      columnCount();
    });
    
    
    
    function columnCount(){
      
         var $checkboxesAbsent = $('.dataTable tr #absent input[type="radio"]');
       
            var countCheckedCheckboxesAbsent = $checkboxesAbsent.filter(':checked').length;
            $('#absent_count').text(countCheckedCheckboxesAbsent);
        
 
        var $checkboxesPresent= $('.dataTable tr #present input[type="radio"]');
       
            var countCheckedCheckboxesPresent = $checkboxesPresent.filter(':checked').length;
            $('#present_count').text(countCheckedCheckboxesPresent);
        
    }
    
    //To claer search box before submit
    $('#dataTable').on('search.dt', function() {
        var value = $('.dataTables_filter input').val();
        if(value){
            $('#updatebtn').prop('disabled', true);
               $('#updatebtn').attr('title','Please clear text before submit.');
            $('#submitbtn').prop('disabled', true);
               $('#submitbtn').attr('title','Please clear text before submit.');

        }else{
            $('#updatebtn').prop('disabled', false);
            $('#updatebtn').removeAttr('title','Please clear text before submit.');
            $('#submitbtn').prop('disabled', false);
            $('#submitbtn').removeAttr('title','Please clear text before submit.');
      }
    }); 

</script> 


