<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  >
                            <thead>
                                <tr>
                                    <th class="no-sort">S.No.</th>
                                    <th> Semester </th> 
                                    <th>course Category</th>
                                    <th> Course </th> 
                                    <th>Student Name</th>
                                    <th>UID</th>
                                    <th>Class Roll No</th>
                                    <th>Batch</th>
                                    <th>Total class conducted</th>
                                    <th>Total class Attended</th>
                                    <th>Total Percent</th>
                                    <th>Attendance Status</th>
                                    <th>Remarks</th>
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $acd_details = new Application_Model_Academic();
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                       //echo"<pre>";print_r($results);die;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['term_name']; ?></td>
                                            <td><?php echo $results['cc_name']; ?></td>
                                            <td><?php  if(empty($results['department'])){ echo $results['course_name'];}else{ echo $results['department'];
                                            }?></td>
                                            
                                           
                                            
                                            <td><?php echo $results['studentName']; ?></td>
                                            <td><?php echo $results['u_id']; ?></td>
                                            <td><?php echo $results['roll_no']; ?></td>
                                             <td><?php echo  $d_id = $acd_details->getRecord($results['academic_id'])['short_code']; ?></td>
                                            <td style="text-align:center"><?php echo $results['conducted_class']; ?></td>
                                            <td style="text-align:center"><?php echo $results['attended_class']; ?></td>
                                            
                                            
                                           <td style="text-align:center" class="total_percent">
                                                <?php  
                                              
                                                $total_percent = round($results['overall_percent']);
                                                if($total_percent >= 75){
                                                   echo "<b style='color:green;'>$total_percent</b>";
                                                }else{
                                                   echo "<b style='color:red;'>$total_percent</b>"; 
                                                }
                                                
                                                ?>
                                            </td>
                                            
                                            
                                            
                                            <td id='attend_status-<?= $results['id']; ?>'>
                                                
                                                <?php if($results['attend_status'] == 0){
                                                echo "Allowed ";}else{
                                                echo "<b style='color:red;'>Not Allowed</b>";}?>
                                            </td>
                                            <td style="width:10em;"> 
                                                <input type="text" class="form-control" value="<?= $results['stu_status'] == 3?'T.C.':$results['attend_remarks'];?>" id="attend_remarks-<?= $results['id']; ?>">
                                              
                                            </td>
                                           
                                            
                                            
                                            <td class="allowed_btn">
                                                   <input type="hidden" value="<?= $results['id']; ?>" id="update_id">
                                                   <button type="button" id="allowedBtn" class="btn btn-primary allowedBtn" value="0" >Allowed</button>
                                                   <button type="button" id="notallowedBtn" class="btn btn-info notallowedBtn" value="1" >Not Allowed</button>
                                                 
                                              </td>
                                            
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
<script>

 setDatatables();
    $(".allowedBtn").click(function() {
    let id = $(this).closest("td").find("#update_id").val();
    let buttonValue=$(this).closest("td").find('#allowedBtn').val();
    let remarks= $("#attend_remarks-"+id).val();
    //alert(remarks);
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-update-attend-status'; ?>',
        data: {id:id,buttonValue:buttonValue,remarks:remarks}
    }).done(function (data) {
        $("#attend_status-"+id).text('Allowed'); 
        //alert("The Application Form this "+update_id+' is approved');
    });     
});
$(".notallowedBtn").click(function() {

    let id = $(this).closest("td").find("#update_id").val();
    let buttonValue=$(this).closest("td").find('#notallowedBtn').val();
    let remarks= $("#attend_remarks-"+id).val();
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-update-attend-status'; ?>',
        data: {id:id,buttonValue:buttonValue,remarks:remarks}
    }).done(function (data) {
        $("#attend_status-"+id).text('Not Allowed'); 
        //alert("The Application Form this "+update_id+' is rejected');

    });   
});
    </script>