<style>
    .ui-datepicker-calendar {
    display: none;
    }
    .dataTable  tbody {
    width: 100%;
    
}

#component_paper_chosen{
    display:none;
}

    .ui-datepicker-calendar {
    display: none;
    }

</style>

<div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
<div class="right_col">

    <?php if ($this->type) { ?>
   
        <div class="padding-md ">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Calculate Monthly Attendance</i></div>
                    </h3>
                    <div class="panel panel-default">

                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                            <div class="panel-body">
                                <?php
                                $hide_filter_block = '"';
                                if (in_array($this->role_id, $this->administrator_role)) {
                                    $hide_filter_block = '';
                                }
                                ?>
                                <div class="row" <?php echo $hide_filter_block; ?> >



                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Session </label>
                                            <?php echo $this->form->session; ?>
                                        </div>
                                    </div>	
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Semester<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cmn_terms; ?>
                                        </div>
                                    </div>
                                    
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Degree<span class="asterisk">*</span></label>
                                            <?php echo $this->form->degree_id; ?>
                                        </div>
                                    </div>

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Course Category<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cc_id; ?>
                                        </div>
                                    </div>
                                    
                                </div>    
                                <div class="row">
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Course Group<span class="asterisk">*</span></label>
                                            <?php echo $this->form->ge_id; ?>
                                        </div>
                                    </div>
                                     <!---<div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Teacher's Department<span class="asterisk">*</span></label>
                                           <select class="form-control" name ="teacher_dept" id = "teacher_dept" required="true">
                                            <option value="">--select--</option>
                                            
                                            <?php 
                                                $dailyAttendanceMaster = new Application_Model_DailyAttendanceModel();
                                                $empl_id=$this->login_storage->empl_id;
                                                $empl_dept = $dailyAttendanceMaster->getEmplDeptById($empl_id); 
                                                foreach ($empl_dept as $key => $value) {?>
                                                  <option value="<?=$value['id'];?> " <?php if($this->result[0]['teacher_dept'] == $value['id'] ){ echo 'selected'; }?>  ><?=$value['department'] ?> </option>
                                               <?php  } ?>
                                            
                                           
                                        </select>
                                        </div>
                                    </div>--->
                                    <div id="course_ids"></div>
                                    
                                    <div class="col-sm-3 employee_class employee_id">
                                        <div class="form-group">
                                            <label class="control-label">Hon's Course<span class="asterisk">*</span></label>
                                            <?php echo $this->form->department; ?>
                                        </div>

                                    </div>	
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Month </label>
                                            <?php echo $this->form->effective_date; ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Total Class Conducted<span class="asterisk">*</span></label>
                                             <?php echo $this->form->conducted_class; ?>
                                        </div>
                                    </div> 
                                    <button type="button" id="getDailyAttendance" class="btn btn-primary" style="float: right" value="0" >Get Attendance</button>
                                   
                                   
                                </div>
                              
                                <div class="row" <?php echo $hide_filter_block; ?>>


                                    <div id="components_ids"></div>
                                </div>
                                <div class="" id="studentData">
                                </div>
                                <input type="hidden" name="students_name" id="students_name" value="<?php echo $this->students_name; ?>"/> 
                                
                                <input type="hidden" name="grade_allocate_id" id="grade_allocate_id" value="<?php echo $this->grade_allocate_id; ?>" />
                            
                            </div>

                            <div class="panel-footer">									
                                <div class="row">
                                    <div class="col-sm-7 col-sm-offset-5">
                                        <?php if ($this->type == 'add') { ?> 
                                            <div style="float:left;margin-right:2px;">
                                                <button class="btn btn-primary submit" id="restirct">Submit</button>
                                            </div>
                                            <div style="float:left;padding:0px 10px;">
                                                <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                            </div>
                                        <?php } else { ?>
                                         <div style="float:left;">
                                                        <button class="btn btn-primary submit">Update</button>
                                                    </div>



                                            <div style="float:left;">
                                                <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>batch-attendance/semester">Back</a>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                    </div>
                    </form>
                </div><!-- /panel -->
            </div><!-- /.col-->				
        </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

   
<?php } ?>
</div>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
//Date Function and calculate monthly attendance
 
 

 $('#getDailyAttendance').on('click',function () {
    $('#studentData').empty('');
    var cc_id = $('#cc_id').val();
    var ge_id = $('#ge_id').val();
    var department = $('#department').val();
    var course_id= $('#course_id').val();
    var session = $("#session").val();
    var term_id = $('#cmn_terms').val();
    var degree_id= $("#degree_id").val();
    var effective_date = $('#effective_date').val();
    if(session && term_id && degree_id && effective_date){
        $('.load-box').css('display','block');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-calculate-monthly-attendance'; ?>',
            data: {session:session,term_id:term_id,degree_id:degree_id,cc_id:cc_id,ge_id:ge_id,department:department,course_id:course_id,effective_date:effective_date}
        }).done(function( data ) {
            $('.load-box').css('display','none');
            $('#studentData').empty('');
            $('#studentData').html(data);

        });
        
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-calculate-total-conducted'; ?>',
            data: {session:session,term_id:term_id,degree_id:degree_id,cc_id:cc_id,ge_id:ge_id,department:department,course_id:course_id,effective_date:effective_date}
        }).done(function( data ) {
            $('#conducted_class').empty('');
            $('#conducted_class').val(data);

        });
    }else{
        alert('Please select the required field.');
    }

});
   
  
$(function() {
    $('.monthYearPicker').datepicker( {
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true,
        dateFormat: 'mm-yy',
        onClose: function(dateText, inst) { 
            var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
            var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
            $(this).datepicker('setDate', new Date(year, month, 1));
        }
    });
});

//End
   
    
    $('body').on('change', '#cmn_terms,session', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
    });
  //Disable some field on change course Category(1)
    $('body').on('change', '#cc_id,#department', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
        var cc_id = $('#cc_id').val();
		let degree_id= $('#degree_id').val();
        var cc_id_InArray = ["1", "7", "11","16","17","18"];
		if(degree_id == 1){
			if(jQuery.inArray(cc_id, cc_id_InArray)!='-1'){
            //alert(cc_id);
            $("#ge_id,#course_id").empty();
            $("#department").removeAttr('disabled').trigger("chosen:updated");
            $("#ge_id,#course_id").attr('disabled','disabled').trigger("chosen:updated");   
            $("#ge_id,#course_id").removeAttr('required').trigger("chosen:updated"); 
           
			}else{
				$("#department").empty();
				$("#department").attr('disabled','disabled').trigger("chosen:updated");
				$("#ge_id,#course_id").removeAttr('disabled').trigger("chosen:updated"); 
				$("#ge_id,#course_id").attr('required',true).trigger("chosen:updated"); 
				
			} 
			$("#course_id").removeAttr('disabled').trigger("chosen:updated");
		}else{
			$("#course_id").attr('disabled','disabled').trigger("chosen:updated");
		}
          
    });
    //End
		let degree_id= $('#degree_id').val();
        var cc_id = $('#cc_id').val();
        var cc_id_InArray = ["1", "7", "11","16","17","18"];
		if(degree_id == 1){
			if(jQuery.inArray(cc_id, cc_id_InArray)){
            //alert(cc_id);
            $("#ge_id,#course_id").attr('disabled','disabled').trigger("chosen:updated");  
            $("#ge_id,#course_id").removeAttr('required').trigger("chosen:updated"); 
			}else{
				$("#ge_id,#course_id").removeAttr('disabled').trigger("chosen:updated");  
				$("#ge_id,#course_id").attr('required','required').trigger("chosen:updated");
			}
			$("#course_id").removeAttr('disabled').trigger("chosen:updated");
		}else{
			$("#course_id").attr('disabled','disabled').trigger("chosen:updated");
		}
        

    


    $('body').on('change', '#ge_id', function () {
     
        $('#grade_data').empty('');
        $('#studentData').empty('');
        $('#course_ids').empty('');
        $('.load-box').css('display','block');
        var employee_id = '';
        var department_id = '';
        var department = '';
        var ct_id = $('#cc_id').val();
        var ge_id = $('#ge_id').val();
        var term_id = $('#cmn_terms').val();
        //alert('ge');
       
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-base-of-course'; ?>',
            data: {Ct_id: ct_id, employee_id: employee_id, department_id: department_id, term_id: term_id, ge_id: ge_id, cc_dept: department}
        }).done(function (data) {

            
            $('#course_ids').html(data);
            $(".chosen-select").chosen();
            $('.load-box').css('display','none');
        });
    });

    $('body').on('change','#course_id,#academic_id', function () {
      
        var course_id = $('#course_id').val();
       
        
            $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-code'; ?>",
            data: {course_id: course_id}
        }).done(function (data) {
            $("<div id='course_container' class='col-md-12 text-center'><h2>"+data+"</h2></div>").insertBefore("#dataTable_length");
            
        });
   
    });
//End
 
   
        
//Department on change degree id
    $('body').on('change', '#degree_id', function () {
       $('#grade_data').empty('');
        $('#studentData').empty('');
        var degree_id = $('#degree_id').val();
         $('.load-box').css('display','block');
        $('#cc_id').empty();
        if (degree_id) {
            
            /*$.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Dept'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data);
                $('.load-box').css('display','none');
            }); */
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-course-cat'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                  // alert(data);
                    $('#cc_id').html(data).trigger("chosen:updated");
                   $('.load-box').css('display','none');
                
            });
        }
    });

//Data on Employee Id : date: 12 Nov 2020: Kedar
    $('body').on('change', '#cc_id', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
        let cc_id = $('#cc_id').val();
        let degree_id = $('#degree_id').val();
        let term_id = $('#cmn_terms').val();
        let employee_id= '<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>'; 
        
        if(degree_id){
        //alert(degree_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-dept-with-empl'; ?>',
                data: {degree_id: degree_id,employee_id : employee_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data).trigger("chosen:updated");
                $('.load-box').css('display','none');
            });
        }
        
        if (cc_id == 2) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group-with-empl-for-daily'; ?>',
                data: {cc_id: cc_id,degree_id:degree_id,employee_id :employee_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }else{
             $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group'; ?>',
                data: {cc_id: cc_id, term_id: term_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }
        
    });


</script>
