<style>
    .dailogBtn{
        background-color: lightcoral;
    }

    .ui-dialog-titlebar { display: none; }
    .ui-dialog{
        width: 400px !important;
    }
    ui-widget-content {
        border: 2px solid #c31616;
    }  
</style>

<?php if (empty($this->type)) { ?>
    <style>
        .ui-datepicker-calendar {
            display: none;
        }
    </style>

<?php } ?>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<div class="right_col">

    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <?php if ($this->type) { ?>
        <div class="padding-md ">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-sm-12">
                        <div class="col-sm-6">
                            <h3 class="page-title txt-color-blueDark" >
                                <div><i class="fa fa-eye">Daily Batch Attendance</i>
                                </div>

                            </h3> 
                        </div>
                        <div class="col-sm-6">

                            <div class="row">
                               <div class="pull-right"><span class="pull-left" style="margin-right:.3em;"><b>PREVIOUS FORM</b></span>
                                    <input type="checkbox" id="payment" value="1"  checked data-toggle="toggle" data-size="sm"></div>
                            </div>
                            <div class="row">
                                <<div class="pull-right"><span class="pull-left" style="margin-right:.3em; margin-top: .5em; "><b>TR SWITCH</b></span>
                                    <input type="checkbox" id="trVal" value="1"  checked data-toggle="toggle" data-size="sm">                                       </div>
                            </div>    
 
                        </div>
                    </div>



                <div class="panel panel-default">

                    <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                        <div class="panel-body">
                            <?php
                            $hide_filter_block = '"';
                            if (in_array($this->role_id, $this->administrator_role)) {
                                $hide_filter_block = '';
                            }
                            ?>
                            <div class="row" <?php echo $hide_filter_block; ?> >
                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Academic Year</label>
                                        <?php echo $this->form->academic_year; ?>
                                    </div>
                                </div>
                                <?php echo $this->form->csrftoken; ?>
                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Session </label>
                                        <?php echo $this->form->session; ?>
                                    </div>
                                </div>	

                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Semester<span class="asterisk">*</span></label>
                                        <?php echo $this->form->cmn_terms; ?>
                                    </div>
                                </div>	

                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Degree<span class="asterisk">*</span></label>
                                        <?php echo $this->form->degree_id; ?>
                                    </div>
                                </div>	



                            </div>    
                            <div class="row">
                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Course Category<span class="asterisk">*</span></label>
                                        <?php echo $this->form->cc_id; ?>
                                    </div>
                                </div>
                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Teacher's Department<span class="asterisk">*</span></label>
                                        <select class="form-control" name ="teacher_dept" id = "teacher_dept" required="true">
                                            <option value="">--select--</option>

                                            <?php
                                            $dailyAttendanceMaster = new Application_Model_DailyAttendanceModel();
                                            $empl_id = $this->login_storage->empl_id;
                                            $empl_dept = $dailyAttendanceMaster->getEmplDeptById($empl_id);
                                            foreach ($empl_dept as $key => $value) {
                                                ?>
                                                <option value="<?= $value['id']; ?> " <?php
                                                if ($this->result[0]['teacher_dept'] == $value['id']) {
                                                    echo 'selected';
                                                }
                                                ?>  ><?= $value['department'] ?> </option>
    <?php } ?>


                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Attendance Date<span class="asterisk">*</span></label>
    <?php echo $this->form->effective_date; ?>
                                    </div>
                                </div>


                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Course Group<span class="asterisk">*</span></label>
    <?php echo $this->form->ge_id; ?>
                                    </div>
                                </div>

                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Hon's Course<span class="asterisk"></span></label>
    <?php echo $this->form->department; ?>
                                    </div>
                                </div>


                                <div id="course_ids">

                                </div>
                                <div id="section_list">

                                </div>
                                <div class="col-sm-3 employee_class">
                                    <div class="form-group">
                                        <label class="control-label">Period<span class="asterisk">*</span></label>
                                        <select class="form-control" name="period" id="period" required="true">
                                            <option value="">--Select--</option>
                                            <option value="p1" <?php
    if ($this->result[0]['period'] == 'p1') {
        echo 'selected';
    }
    ?> >1st Period</option>
                                            <option value="p2" <?php
                                                    if ($this->result[0]['period'] == 'p2') {
                                                        echo 'selected';
                                                    }
                                                    ?> >2nd Period</option>
                                            <option value="p3" <?php
                                            if ($this->result[0]['period'] == 'p3') {
                                                echo 'selected';
                                            }
                                            ?> >3rd Period</option>
                                            <option value="p4" <?php
                                            if ($this->result[0]['period'] == 'p4') {
                                                echo 'selected';
                                            }
                                            ?> >4th Period</option>
                                            <option value="p5" <?php
                                            if ($this->result[0]['period'] == 'p5') {
                                                echo 'selected';
                                            }
                                            ?> >5th Period</option>
                                            <option value="p6" <?php
                                            if ($this->result[0]['period'] == 'p6') {
                                                echo 'selected';
                                            }
                                            ?> >6th Period</option>
                                        </select>
                                    </div>
                                </div>

    <?php if ($this->type == 'add') { ?> 
                                    <button type="button" id="getStudentsRecord" class="btn btn-primary" style="float: right" value="0" >Get Student List</button>
    <?php } ?>
                            </div>

                            <div class="row" <?php echo $hide_filter_block; ?>>


                                <div id="components_ids"></div>
                                <!--                                    <div class="col-xs-6 pull-left" style="padding-left : 0 ; margin-left: 0;"> 
                                            <div class="col-xs-3 pull-left" style="padding-left : 0 ; margin-left: 0;"><p>Min Roll No. <span class="asterisk">*(for B.Com Dept.)</span> <input type="number" id="min" autocomplete="off"> </p></div>
                                            <div class="col-xs-3 pull-left" style="padding-left : 0 ; margin-left: 0;"><p>Max Roll No. <span class="asterisk">*(for B.Com Dept.)</span><input type="number" id="max" autocomplete="off"></p></div>
                                            
                                            </div>-->
                            </div>
                            <div class="" id="grade_data">
                            </div>
                            <input type="hidden" name="students_name" id="students_name" value="<?php echo $this->students_name; ?>"/> 

                            <input type="hidden" name="grade_allocate_id" id="grade_allocate_id" value="<?php echo $this->grade_allocate_id; ?>" />

                        </div>

                        <div class="panel-footer">									
                            <div class="row">
                                <div class="col-sm-7 col-sm-offset-5">
    <?php if ($this->type == 'add') { ?> 
                                        <div style="float:left;margin-right:2px;">
                                            <button data-toggle="tooltip" data-placement="top" id="submitbtn" class="btn btn-primary submit">Submit</button>
                                        </div>
                                        <div style="float:left;padding:0px 10px;">
                                            <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                        </div>
    <?php } else {
        ?>

                                        <div style="float:left;">
                                            <button data-toggle="tooltip" data-placement="top" id="updatebtn" class="btn btn-primary submit">Update</button>
                                        </div>
                                        <div style="float:left;">
                                            <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>batch-attendance/daily-attendance">Back</a>
                                        </div>
    <?php } ?>
                                </div>
                            </div>
                        </div>
                </div>
                </form>
            </div><!-- /panel -->
        </div><!-- /.col-->				
    </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

    <?php
    if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert <?php echo $_SESSION['message_class']; ?> ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
                <strong>  <?php echo $this->escape($message); ?></strong>
            </div>

                        <?php
                        unset($_SESSION['message_class']);
                    }
                }
                ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">

                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Daily Batch Attendance</i>

                    </h3>
                </div>
    <?php
    //    if(in_array($this->role_id, $this->administrator_role)){
    ?>		
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>batch-attendance/daily-attendance/type/add">Add </a>
                </div>
    <?php
    //  }
    ?>
            </div>

            <div class="x_panel">

                <div class="x_title">
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label">Academic Year</label>-->
    <?php echo $this->form->academic_year; ?>
                        </div>
                    </div>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                         <!--   <label class="control-label">Session </label>-->
    <?php echo $this->form->session; ?>
                        </div>
                    </div>	
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <!--<label class="control-label">Semester </label>-->
    <?php echo $this->form->cmn_terms; ?>
                        </div>
                    </div>	

                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">Degree </label>-->
    <?php echo $this->form->degree_id; ?>
                        </div>
                    </div>	

                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                           <!-- <label class="control-label">Attendance Month </label>-->
    <?php echo $this->form->effective_month; ?>
                        </div>
                    </div>
                    
                        <div class="form-group pull-right">
                    <button type="button" id="getDailyAttendance" class="btn btn-primary" style="float: right" value="0" >Get Attendance</button>

  </div>
                
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData"> 
                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                                <thead>
                                    <tr>
                                        <th>S.No.</th>
                                        <th> Batch-Name</th>
                                        <th>Semester</th>  
                                        <th>course Category</th>  
                                        <th>Course</th>   
                                        <th>Section</th>   
                                        <th>Period </th>   
                                        <th>Faculty Name</th>   
                                        <th>Attendance Date</th>
                                        <th class="no_print">Action</th>
                                        <th class="no_print">Delete Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                            <?php
                                            $i = 1;
                                            $pagination_tr = '';
                                            if (count($this->paginator) != 0) {

                                         foreach ($this->paginator as $results) {
                                                    //echo '<pre>'; print_r($results);
                                                    $emplyeeData = new Application_Model_HRMModel();

                                                    $data = $emplyeeData->getEmployeeData($results['employee_id']);
                                                    //echo '<pre>'; print_r($data);exit;
                                                    ?>
                                            <tr>
                                                <td><?php
                                        echo $i;

                                        $i++;
                                                    ?>
                                                </td>						

                                                <td><?php echo $results['batch']; ?></td>
                                                <td><?php echo $results['term_name']; ?></td>
                                                <td><?php echo $results['cc_name']; ?></td>
                                                <td><?php
                                                    if (empty($results['department'])) {
                                                        echo $results['course_name'];
                                                    } else {
                                                        echo $results['department'];
                                                    }
                                                    ?></td>
                                                <td><?php echo $results['sectionName']; ?></td>

                                                <td>
                                                    <?php
                                                    switch ($results['period']) {
                                                        case "p1":
                                                            echo "1st Period";
                                                            break;
                                                        case "p2":
                                                            echo "2nd Period";
                                                            break;
                                                        case "p3":
                                                            echo "3rd Period";
                                                            break;
                                                        case "p4":
                                                            echo "4th Period";
                                                            break;
                                                        case "p5":
                                                            echo "5th Period";
                                                            break;
                                                        case "p6":
                                                            echo "6th Period";
                                                            break;
                                                        default:
                                                            echo "n/a";
                                                    }
                                                    ?>
                                                </td>


                                                <td><?php echo $data['empl_firstname']; ?></td>

                                                <td style="text-align:center">
                                            <?php
                                            $start_date = date_create($results['effective_date']);
                                            $result['effective_date'] = date_format($start_date, "d/m/Y");
                                            echo $result['effective_date'];
                                            ?>
                                                </td>
                                                <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>batch-attendance/daily-attendance/type/edit/id/<?php echo md5($results['id']); ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></td>

                                                <td style="text-align:center">
                                                    <input type="hidden" value="<?= md5($results['id']); ?>" id="delete_id">
                                                    <button type="button" id="dailogBtn" class="btn btn-primary dailogBtn" value="0" >Delete</button>

                                                </td>
                                            </tr>            

            <?php
        }
        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
    }
    ?>

                                </tbody>
                            </table>
    <?php echo $pagination_tr; ?>
                        </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
    <div id="wrapper">
        <h2 style="color:solid black; font-size: 1.5em;">Are you sure to delete this record?</h2>
        <input type="hidden" value="<?= md5($results['id']); ?>" id="delMasterId">
        <br>
        <button type="button" id="deleteBtn" class="btn btn-primary dailogBtn" style="float: right" value="0" >Yes</button>
        <button type="button" id="noDeletebtn" class="btn btn-success" style="float: right" value="0" >No</button>
    </div>
<?php } ?>
</div>

<!------------------------------For Custom DatePicker Script----------------------------------------->
<script>
    $('body').on('change', "#trVal", function () {
        var value = $(this).parent().attr("class");
        //alert(value);
        if (value.includes("off")) {
            $(this).removeAttr("checked");
            $(this).val("0");
        } else
        {
            $(this).attr("checked", "checked");
            $(this).val("1");
        }
    });
    $('body').on('change', "#payment", function () {
        var value = $(this).parent().attr("class");
        //alert(value);
        if (value.includes("off")) {
            $(this).removeAttr("checked");
            $(this).val("0");
        } else
        {
            $(this).attr("checked", "checked");
            $(this).val("1");
        }
    });
</script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" crossorigin="anonymous"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<!----------------------------------- Script Area ---------------------------->
<script>
    //To filter Session
    $('body').on('change', '#academic_year', function () {
        $('#department').removeAttr('disabled');
        var year_id = $('#academic_year').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    //End
    $('body').on('change', '#course_id', function () {

        let course_id = this.value;
        let session = $('#session').val();
        let term_id = $('#cmn_terms').val();
        let ge_id = $('#ge_id').val();
        //alert(course_id);

        if (ge_id == 24 || ge_id == 27 || ge_id == 26) {
            if (course_id != 14) {
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-section'; ?>',
                    data: {course_id: course_id, session: session, term_id: term_id}
                }).done(function (data) {
                    $('#section_list').empty('');
                    $('#section_list').html(data).trigger("chosen:updated");

                });
            }
        }


    });
    //To delete daily Attendance: 11 Aug 2020
    $('#wrapper').dialog({
        autoOpen: false,
        //title: 'Basic Dialog'
    });
    $('#noDeletebtn').click(function () {
        $('#wrapper').dialog('close');
        return false;
    });
    $('.dailogBtn').click(function () {

        let delete_id = $(this).closest("td").find("#delete_id").val();
        $('#wrapper').dialog('open');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-daily-attend'; ?>',
            data: {delete_id: delete_id}
        }).done(function (data) {
            $('#delMasterId').empty();
            $('#delMasterId').val(data);
            //alert(data);

        });

        return false;
    });

    $("#deleteBtn").click(function () {
        let delMasterId = $('#delMasterId').val();
        if (delMasterId) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-delete-daily-attend'; ?>',
                data: {delete_id: delMasterId}
            }).done(function (data) {
                alert('Record is deleted');
                window.location.reload();
            });
        }
    });
    //End


    $('body').on('change', '#cmn_terms,#session,#section,#degree_id', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
    });



    $(window).on('load', function () {
        setDatatablesManual();
        //alert('hello'); 
        let degree_id = $('#degree_id').val();
        var cc_id = $('#cc_id').val();
        var cc_id_InArray = ["1", "7", "11", "16", "17", "18"];



        if (degree_id == 1) {

            if (jQuery.inArray(cc_id, cc_id_InArray) != '-1') {
                //alert(cc_id);
                $("#ge_id,#course_id").attr('disabled', 'disabled').trigger("chosen:updated");
            } else {
                $("#ge_id,#course_id").removeAttr('disabled').trigger("chosen:updated");
            }
            $("#course_id").removeAttr('disabled').trigger("chosen:updated");
        } else {
            $("#course_id").attr('disabled', 'disabled').trigger("chosen:updated");
        }

        var id = '<?= !empty($this->id) ? $this->id : ''; ?>';
        if (id) {
            var totalConductedClass = $('#conducted_class').val();
            var totalAttendClass = $('#attended_class').val();
            var percent = Math.round((totalAttendClass / totalConductedClass) * 100);
            $('#percent_sum').val(percent);
            $("#course_id").removeAttr('required').trigger("chosen:updated");
            $("#conducted_class,#percent_sum,#course_id").prop('readonly', true);
            $('.percent_sum').css("background-color", "#eee");
            $('.load-box').css('display', 'none');
        }

        //alert(percent);
    });


    $('body').on('change', '#department_id', function () {
        $("#course_id").removeAttr('required').trigger("chosen:updated");
        $("#course_id").attr('disabled', 'disabled').trigger("chosen:updated");
        var department_id = $('#department_id').val();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-employee'; ?>',
            data: {department_id: department_id}
        }).done(function (data) {

            $('#employee_id').empty('');
            $('#employee_id').html(data);

        });
    });
    // To check existed result


    //for daily new 
    var employee_id = '<?= !empty($this->login_storage->empl_id) ? $this->login_storage->empl_id : ''; ?>';
    var department_id = $('#department_id option:selected').val();
    var academic_year_id = $('#academic_id option:selected').val();
    var grade_allocate_id = $('#grade_allocate_id').val();
    var department = $('#department').val();
    var session = $('#session').val();
    var ct_id = $('#cc_id option:selected').val();
    var ge_id = $('#ge_id option:selected').val();
    var term_id = $('#cmn_terms option:selected').val();
    var section = $('#section option:selected').val();

    var id = '<?= !empty($this->id) ? $this->id : ''; ?>';
    var courseIdSelected = '<?= $this->course_id; ?>';

    if (ge_id != 0) {
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-base-of-course'; ?>',
            data: {Ct_id: ct_id, employee_id: '', department_id: '', term_id: term_id, ge_id: ge_id, cc_dept: department}
        }).done(function (data) {

            $('#course_ids').empty('');
            $('#course_ids').html(data);
            $('#course_id').val(<?= $this->course_id; ?>).trigger("chosen:updated");
          getstudents();
            
            
        });
    }
    
    
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-section'; ?>',
        data: {teacher_dept: department, session: session, term_id: term_id, course_id: courseIdSelected}
    }).done(function (data) {

        $('#section_list').empty('');
        $('#section_list').html(data);
        $('#section').val(<?= $this->section; ?>).trigger("chosen:updated");



       

        
            getstudents();


    });
 function getstudents(){
      //var ge_id = $('#ge_id').val();
        var term_id = $('#cmn_terms').val();

        var session_id = $('#session').val();
        var degree_id = $('#degree_id').val();
        let tab_offset = $('#trVal').val();
        let pay = $('#payment').val();
        let section = $('#section').val();
        if (department != 0) {
            $('#course_id').attr('disabled', 'disabled');
            $('#course_id').removeAttr('required');
        }
 $('.load-box').css('display', 'block');
        //alert(department);
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-students-details-for-daily-attend'; ?>",

            data: {employee_id: employee_id, department_id: department_id, ct_id: ct_id, term_id: term_id, course_id: courseIdSelected, honors_id: department, session_id: session_id, grade_allocate_id: grade_allocate_id, id: id, degree_id: degree_id, tab_offset: tab_offset, pay: pay, section: section}
        }).done(function (data) {
            $('#grade_data').empty('');
            $("#grade_data").html(data);
            $('.load-box').css('display', 'none');

        });

    }

    //End


    $('body').on('change', '#cc_id', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
        let cc_id = $('#cc_id').val();
        let degree_id = $('#degree_id').val();
        let term_id = $('#cmn_terms').val();
        let employee_id = '<?= !empty($this->login_storage->empl_id) ? $this->login_storage->empl_id : ''; ?>';
        if (cc_id == 2) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group-with-empl-for-daily'; ?>',
                data: {cc_id: cc_id, degree_id: degree_id, employee_id: employee_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        } else {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group'; ?>',
                data: {cc_id: cc_id, term_id: term_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }
        if (degree_id) {
            //alert(degree_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-dept-with-empl'; ?>',
                data: {degree_id: degree_id, employee_id: employee_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data).trigger("chosen:updated");
                $('.load-box').css('display', 'none');
            });
        }
    });


//Disable some field on change course Category(1)
    $('body').on('change', '#cc_id,#department', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
        let degree_id = $('#degree_id').val();
        var cc_id = $('#cc_id').val();
        var cc_id_InArray = ["1", "5", "7", "11", "16", "17", "18"];
        //alert(degree_id);
        if (degree_id == 1) {

            if (jQuery.inArray(cc_id, cc_id_InArray) != '-1') {
                //alert(cc_id);
                $("#ge_id,#course_id").empty();
                $("#department").removeAttr('disabled').trigger("chosen:updated");
                $("#ge_id,#course_id").attr('disabled', 'disabled').trigger("chosen:updated");
                $("#ge_id,#course_id").removeAttr('required').trigger("chosen:updated");


            } else {
                $("#department").empty();
                $("#department").attr('disabled', 'disabled').trigger("chosen:updated");
                $("#ge_id,#course_id").removeAttr('disabled').trigger("chosen:updated");
                $("#ge_id,#course_id").attr('required', true).trigger("chosen:updated");

            }
            $("#course_id").removeAttr('disabled').trigger("chosen:updated");
        } else {
            $("#course_id").attr('disabled', 'disabled').trigger("chosen:updated");
        }
    });

//End
//to get course on basis of  ge id
    $('body').on('change', '#ge_id', function () {

        $('#grade_data').empty('');
        $('#studentData').empty('');
        $('#course_ids').empty('');
        $('.load-box').css('display', 'block');
        var employee_id = '';
        var department_id = '';
        var department = '';
        var ct_id = $('#cc_id').val();
        var ge_id = $('#ge_id').val();
        var term_id = $('#cmn_terms').val();
        //alert('ge');
        if (ge_id == 25) {
            $("#department").removeAttr('disabled').trigger("chosen:updated");
            $('.load-box').css('display', 'none');
        } else {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-base-of-course'; ?>',
                data: {Ct_id: ct_id, employee_id: employee_id, department_id: department_id, term_id: term_id, ge_id: ge_id, cc_dept: department}
            }).done(function (data) {

                $('#course_ids').html(data);
                $(".chosen-select").chosen();
                var exists = $('#course_ids option[value]').length;
                //alert(exists);
                $('.load-box').css('display', 'none');
                if (exists > 1) {
                    $("#department").empty();
                    $("#department").attr('disabled', 'disabled').trigger("chosen:updated");
                } else {
                    $("#department").removeAttr('disabled').trigger("chosen:updated");
                }
            });
        }
    });
//To get  course category and department on degree change

    $('body').on('change', '#degree_id', function () {
        $('#studentData').empty('');
        var degree_id = $('#degree_id').val();
        var employee_id = '<?= !empty($this->login_storage->empl_id) ? $this->login_storage->empl_id : ''; ?>';
        $('.load-box').css('display', 'block');
        $('#cc_id').empty();


        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-course-cat'; ?>',
            data: {degree_id: degree_id}
        }).done(function (data) {
            // alert(data);
            $('#cc_id').html(data).trigger("chosen:updated");
            $('.load-box').css('display', 'none');

        });
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-dept-with-empl'; ?>',
            data: {degree_id: degree_id, employee_id: employee_id}
        }).done(function (data) {
            $('#department').empty('');
            $('#department').html(data);
            $('.load-box').css('display', 'none');
        });


    });



//Semester end Attendance Filter code : Date: 26 March 2020 :Kedar
    var default_type = '<?= $this->type ?>';


    if (!default_type) {
        $('#getDailyAttendance').on('click', function () {
            $('#studentData').empty('');

            var session = $("#session").val();
            var term_id = $('#cmn_terms').val();
            var degree_id = $("#degree_id").val();
            var effective_date = $('#effective_month').val();
            let employee_id = '<?= !empty($this->login_storage->empl_id) ? $this->login_storage->empl_id : ''; ?>';
            if (session && term_id && degree_id && effective_date) {
                $('.load-box').css('display', 'block');
                $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-daily-wise-Student'; ?>',
                    data: {session: session, term_id: term_id, degree_id: degree_id, effective_month: effective_date, employee_id: employee_id}
                }).done(function (data) {
                    $('.load-box').css('display', 'none');
                    $('#studentData').empty('');
                    //alert(data);
                    $('#studentData').html(data);

                });
            } else {
                alert('Please select the required field.');
            }

        });
    } else {
        //to get monthly attendace

        $('body').on('click', '#getStudentsRecord', function () {
            var employee_id = $('#employee_id').val();
            var department_id = $('#department_id').val();
            var honors_id = $('#department').val();
            var ct_id = $('#ge_id').val();
            var term_id = $('#cmn_terms').val();
            var degree_id = $('#degree_id').val();
            var course_id = $('#course_id').val();
            var session = $("#session").val();
            var section = $("#section").val();
            var tabId = $("#trVal").val();
            let pay = $('#payment').val();
            //alert(tabId);
            //alert(default_type);
            if (term_id) {
                $('.load-box').css('display', 'block');
                $.ajax({
                    type: "POST",
                    url: "<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-students-details-for-daily-attend'; ?>",
                    data: {employee_id: employee_id, department_id: department_id, ct_id: ct_id, term_id: term_id, course_id: course_id, session_id: session, degree_id: degree_id, honors_id: honors_id, pay: pay, tabId: tabId, section: section}
                }).done(function (data) {

                    $('.load-box').css('display', 'none');
                    $('#grade_data').empty('');

                    $("#grade_data").html(data);
                    setDatatablesManual();
                });
                if (course_id) {
                    $.ajax({
                        type: "POST",
                        url: "<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-code'; ?>",
                        data: {course_id: course_id}
                    }).done(function (data) {
                        if (data) {

                            $("<div id='course_container'style='background-color: rgb(253, 245, 154); display: block;' class='col-md-3 text-center'><h2>" + data + "</h2></div>").insertAfter("#dataTable_length");
                        } else {
                            $("<div id='course_container'style=' display: none;' class='col-md-3 text-center'>");
                        }
                    });
                }
            }
        });
//End
    }

//Department on teacher department validation
    $('#teacher_dept').on('change', function () {

        $('#department option[value]').show().trigger("chosen", "updated");
        $('#department').val('').trigger("chosen", "updated");
        let teacher_dept = $('#teacher_dept').val();

        if (teacher_dept) {
            $('#department option[value!=' + teacher_dept + ']').hide();
        }
    });

    $('#department').on('change', function () {
        $('.load-box').css('display','block');
        let teacher_dept = this.value;
        let session = $('#session').val();
        let term_id = $('#cmn_terms').val();
        //alert('x');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-section'; ?>',
            data: {teacher_dept: teacher_dept, session: session, term_id: term_id}
        }).done(function (data) {
            $('#section_list').empty('');
            $('#section_list').html(data).trigger("chosen:updated");
            $('.load-box').css('display','none');
        });


    });


    $('#period').on('change', function () {

        let teacher_dept = $('#teacher_dept').val();
        let employee_id = $('#employee_id').val();
        let session = $('#session').val();
        let term_id = $('#cmn_terms').val();
        let degree_id = $('#degree_id').val();
        let effective_date = $('#effective_date').val();
        let section = $('#section').val();
        let period = this.value;




        if (!effective_date) {
            alert('Please select the date field.');
            $("#period option:selected").prop("selected", false);
        } else {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-check-existed-daily-attendance'; ?>',
                data: {session: session, term_id: term_id, degree_id: degree_id, effective_date: effective_date, period: period, teacher_dept: teacher_dept, employee_id: employee_id, section: section}
            }).done(function (data) {
                if ((data != '')) {
                    //alert(data);
                    alert("Daily Attendance for this period is already made!");
                    $('#period').val('');


                }


            });
        }
    });
</script>

<script>
    //After daily attendance implementation
    if (default_type == 'add') {
        var today = new Date();
        $('.monthYearPicker').datepicker({
            dateFormat: 'dd/mm/yy',
            autoclose: true,
            endDate: "today",
            maxDate: today,
            minDate: new Date('-2020-07-06')
        }).on('changeDate', function (ev) {
            $(this).datepicker('hide');

        });


        $('.monthYearPicker').keyup(function () {
            if (this.value.match(/[^0-9]/g)) {
                this.value = this.value.replace(/[^0-9^-]/g, '');
            }
        });
        $(".monthYearPicker").datepicker("setDate", new Date());
    } else {
        $(function () {
            $('.monthYearPicker').datepicker({
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                dateFormat: 'mm-yy',
                onClose: function (dateText, inst) {
                    var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
                    var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
                    $(this).datepicker('setDate', new Date(year, month, 1));
                }
            });
        });
    }
    var table = '';
    setDatatablesManual();
    function setDatatablesManual() {
        $.fn.dataTable.ext.search.push(
                function (settings, data, dataIndex) {
                    var min = parseInt($('#manualmin').val(), 10);
                    var max = parseInt($('#manualmax').val(), 10);
                    var age = parseFloat(data[2]) || 0; // use data for the age column

                    if ((isNaN(min) && isNaN(max)) ||
                            (isNaN(min) && age <= max) ||
                            (min <= age && isNaN(max)) ||
                            (min <= age && age <= max))
                    {
                        return true;
                    }
                    return false;
                }
        );

        table = $('#dataTable').DataTable({
            "pageLength": -1,

        });
    }

    // Event listener to the two range filtering inputs to redraw on input
    $('#manualmin, #manualmax').keyup(function () {
        //alert("hello");
        table.draw();
    });

    $('#manualmin, #manualmax').change(function () {
        //alert("hello");
        table.draw();
    });

    //End
    
    //Dsiable Editing In Core Course Learning Date : 25 Oct 2021
    let type='<?= $this->type ?>';
    if(type == 'edit'){
        //disable the field
        
        $("#academic_year").prop( "disabled", true ); 
        $("#session").prop( "disabled", true ); 
        $("#cmn_terms").prop( "disabled", true ); 
        $("#degree_id").prop( "disabled", true ); 
        $("#cc_id").prop( "disabled", true ); 
        $("#effective_date").prop( "disabled", true ); 
        
    

        //right before the form submits, we re-enable the fields, to make them submit.
        $( "#formValidate1" ).submit(function( event ) {
        $("#academic_year").prop( "disabled", false );
        $("#session").prop( "disabled", false );
        $("#cmn_terms").prop( "disabled", false );
        $("#degree_id").prop( "disabled", false );
        $("#cc_id").prop( "disabled", false );
        $("#effective_date").prop( "disabled", false );
 
    });   
    }
//End
</script>
