
<?php 
    //echo '<pre>'; print_r($this->result);exit;
 ?>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<div class="right_col">
    
<div class="load-box">
    <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
</div>
    <?php if ($this->type) { ?>
        <div class="padding-md ">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="page-title txt-color-blueDark" >
                        <div><i class="fa fa-eye">Daily Batch Attendance</i></div>
                    </h3>
                    <div class="panel panel-default">

                        <form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >

                            <div class="panel-body">
                                <?php
                                
                                $hide_filter_block = '"';
                                if (in_array($this->role_id, $this->administrator_role)) {
                                    $hide_filter_block = '';
                                }
                                ?>
                                <div class="row" <?php echo $hide_filter_block; ?> >



                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Session </label>
                                            <?php echo $this->form->session; ?>
                                        </div>
                                    </div>	
                                    
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Semester<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cmn_terms; ?>
                                        </div>
                                    </div>	
                                    
                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Degree<span class="asterisk">*</span></label>
                                            <?php echo $this->form->degree_id; ?>
                                        </div>
                                    </div>	

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Course Category<span class="asterisk">*</span></label>
                                            <?php echo $this->form->cc_id; ?>
                                        </div>
                                    </div>
                                    
                                </div>    
                                <div class="row">
                                  

                                   <!--- <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Department<span class="asterisk">*</span></label>
                                            <?php echo $this->form->department_id; ?>
                                        </div>
                                    </div>
                                   
                                    <div class="col-sm-3 employee_class employee_id">
                                        <div class="form-group">
                                            <label class="control-label">Faculty<span class="asterisk">*</span></label>
                                        <?php    if($this->login_storage->role_id != 2) {  ?>
                                            <select class="form-control" name ="employee_id" id = "employee_id" required="true">
                                           <!--- <option value="">--select--</option>--
                                            <option value="<?=$this->login_storage->empl_id;?> " <?php if(!empty($this->result[0]['employee_id'])){ echo 'selected'; }?>  ><?=$this->login_storage->real_name;?> </option>
                                        </select>
                                        
                                        <?php } else { ?>
                                         <?php echo $this->form->employee_id; ?>
                                        <?php }  ?>
                                           
                                        </div>

                                    </div>	----->

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Teacher's Department<span class="asterisk">*</span></label>
                                           <select class="form-control" name ="teacher_dept" id = "teacher_dept" required="true">
                                            <option value="">--select--</option>
                                            
                                            <?php 
                                                $dailyAttendanceMaster = new Application_Model_DailyAttendanceModel();
                                                $empl_id=$this->login_storage->empl_id;
                                                $empl_dept = $dailyAttendanceMaster->getEmplDeptById($empl_id); 
                                                foreach ($empl_dept as $key => $value) {?>
                                                  <option value="<?=$value['id'];?> " <?php if($this->result[0]['teacher_dept'] == $value['id'] ){ echo 'selected'; }?>  ><?=$value['department'] ?> </option>
                                               <?php  } ?>
                                            
                                           
                                        </select>
                                        </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                      <div class="form-group">
                                          <label class="control-label">Date<span class="asterisk">*</span></label>
                                          <?php echo $this->form->effective_date; ?>
                                      </div>
                                    </div>
                                    <div class="col-sm-3 employee_class">
                                      <div class="form-group">
                                          <label class="control-label">Period<span class="asterisk">*</span></label>
                                          <select class="form-control" name="period" id="period" required="true">
                                              <option value="">--Select--</option>
                                              <option value="p1" <?php if($this->result[0]['period']=='p1'){ echo 'selected'; }?> >1st Period</option>
                                              <option value="p2" <?php if($this->result[0]['period']=='p2'){ echo 'selected'; }?> >2nd Period</option>
                                              <option value="p3" <?php if($this->result[0]['period']=='p3'){ echo 'selected'; }?> >3rd Period</option>
                                              <option value="p4" <?php if($this->result[0]['period']=='p4'){ echo 'selected'; }?> >4th Period</option>
                                              <option value="p5" <?php if($this->result[0]['period']=='p5'){ echo 'selected'; }?> >5th Period</option>
                                          </select>
                                      </div>
                                    </div>

                                    <div class="col-sm-3 employee_class">
                                        <div class="form-group">
                                            <label class="control-label">Course Group<span class="asterisk">*</span></label>
                                            <?php echo $this->form->ge_id; ?>
                                        </div>
                                    </div>
                                    
                                    <div class="col-sm-3 employee_class">
                                      <div class="form-group">
                                          <label class="control-label">Hon's Course<span class="asterisk"></span></label>
                                          <?php echo $this->form->department; ?>
                                      </div>
                                    </div>
                                  
                                    
                                    <div id="course_ids">
                                        
                                    </div>
                                    
                                     
                                    
                                   
                                </div>
                              
                                <div class="row" <?php echo $hide_filter_block; ?>>


                                    <div id="components_ids"></div>
                                    <div class="col-md-6 pull-left" style="padding-left : 0 ; margin-left: 0;"> 
		    <div class="col-md-3 pull-left" style="padding-left : 0 ; margin-left: 0;"><p>Min. S.No. <input type="number" id="min" autocomplete="off"> </p></div>
		    <div class="col-md-3"><p>Max S.No.<input type="number" id="max" autocomplete="off"></p></div>
		    </div>
                                </div>
                                <div class="" id="grade_data">
                                </div>
                                <input type="hidden" name="students_name" id="students_name" value="<?php echo $this->students_name; ?>"/> 
                                
                                <input type="hidden" name="grade_allocate_id" id="grade_allocate_id" value="<?php echo $this->grade_allocate_id; ?>" />
                            
                            </div>

                            <div class="panel-footer">									
                                <div class="row">
                                    <div class="col-sm-7 col-sm-offset-5">
                                        <?php if ($this->type == 'add') { ?> 
                                            <div style="float:left;margin-right:2px;">
                                                <button class="btn btn-primary submit">Submit</button>
                                            </div>
                                            <div style="float:left;padding:0px 10px;">
                                                <button type="reset" class="btn btn-danger btn-default">Reset</button>
                                            </div>
                                        <?php
                                        } else {
                                          

                                            if (!$this->isGradeReportPublished) {
                                                //  echo "<pre>";print_r($this->administrator_role); exit;
                                                if (($login_empl_id == $this->grade_detail['employee_id']) || in_array($this->role_id, $this->administrator_role)) {
                                                    ?>
                                                        
                                                    
                                                   
                                                    <?php
                                                }
                                            } else {
                                                echo '<div class="pull-right font-weight-bold">Grade is already published. You can\'t edit it</div>';
                                            }
                                            ?>
											<div style="float:left;">
												<button class="btn btn-primary submit">Update</button>
											</div>
                                            <div style="float:left;">
                                                <a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>batch-attendance/daily-attendance">Back</a>
                                            </div>
                                        <?php } ?>
                                    </div>
                                </div>
                            </div>
                    </div>
                    </form>
                </div><!-- /panel -->
            </div><!-- /.col-->				
        </div><!-- /.row -->

    </div><!-- /.padding-md -->	
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
                
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Daily Batch Attendance</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>		
                <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                    <a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>batch-attendance/daily-attendance/type/add">Add </a>
                </div>
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
                
                <div class="x_title">
                    
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label">Session </label>
                            <?php echo $this->form->session_filter; ?>
                        </div>
                    </div>	
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label">Semester </label>
                            <?php echo $this->form->cmn_terms; ?>
                        </div>
                    </div>	
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label">Date </label>
                            <?php echo $this->form->effective_date; ?>
                        </div>
                    </div>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label">Degree </label>
                            <?php echo $this->form->degree_id; ?>
                        </div>
                    </div>	
                   
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label">Course Category<span class="asterisk">*</span></label>
                            <?php echo $this->form->cc_id; ?>
                        </div>
                    </div>
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <label class="control-label">Course Group<span class="asterisk">*</span></label>
                            <?php echo $this->form->ge_id; ?>
                        </div>
                    </div>
                    
                    <div id="course_ids"></div>
                    
                    <div class="col-sm-3 employee_class">
                       <div class="form-group">
                           <label class="control-label">Hon's Course<span class="asterisk"></span></label>
                           <?php echo $this->form->department; ?>
                       </div>
                    </div>

                    <ul class="nav navbar-right panel_toolbox">
                        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        </li>
                        <li><a class=""><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    
                    <div class="clearfix"></div>
                </div>

                <div class="x_content">

                    <div class="padding-md clearfix">
                        <div class="table-responsive" id="studentData"> 
                             <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Batch-Name</th>
                                    <th>Semester</th>  
                                    <th>course Category</th>  
                                    <th>Course</th>   
                                    <th>Period </th>   
                                    <th>Faculty Name</th>   
                                    <th>Effective Date</th>
                                    <th class="no_print">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                      //echo '<pre>'; print_r($results);
                                      $emplyeeData = new Application_Model_HRMModel();
                                      
                                      $data= $emplyeeData->getEmployeeData($results['employee_id']);
                                      //echo '<pre>'; print_r($data);exit;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                            </td>						

                                            <td><?php echo $results['batch']; ?></td>
                                            <td><?php echo $results['term_name']; ?></td>
                                            <td><?php echo $results['cc_name']; ?></td>
                                            <td><?php  if(empty($results['department'])){ echo $results['course_name'];}else{ echo $results['department'];
                                            }?></td>
                                            
                                            
                                            <td>
                                                <?php 
                                                switch ($results['period']) {
                                                    case "p1":
                                                      echo "1st Period";
                                                      break;
                                                    case "p2":
                                                      echo "2nd Period";
                                                      break;
                                                    case "p3":
                                                      echo "3rd Period";
                                                      break;
                                                    case "p4":
                                                      echo "4th Period";
                                                      break;
                                                    case "p5":
                                                      echo "5th Period";
                                                      break;
                                                    default:
                                                      echo "n/a";
                                                }
                                                ?>
                                            </td>
                                            
                                          
                                             <td><?php echo $data['empl_firstname']; ?></td>
                                            
                                            <td style="text-align:center">
                                                <?php
                                                  $start_date = date_create($results['effective_date']);
                                                  $result['effective_date'] = date_format($start_date,"d/m/Y"); 
                                                    echo $result['effective_date']; 
                                                ?>
                                            </td>
                                            <td style="text-align:center"><a href="<?php echo $this->mainconfig['host']; ?>batch-attendance/daily-attendance/type/edit/id/<?php echo md5($results['id']); ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></td>
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
    <?php echo $pagination_tr; ?>
                         </div>
                    </div><!-- /.padding-md -->
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->		
<?php } ?>
</div>

<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.7/chosen.jquery.min.js" crossorigin="anonymous"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script>
  
    $('body').on('change', '#cmn_terms,session', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
    });
 
    
        
    $(window).on('load', function() {
         setDatatables();
       //alert('hello'); 
		let degree_id= $('#degree_id').val();
        var cc_id = $('#cc_id').val();
        var cc_id_InArray = ["1", "7", "11","16","17","18"];
        
    
        
		if(degree_id == 1){
			
			if(jQuery.inArray(cc_id, cc_id_InArray)!='-1'){
            //alert(cc_id);
            $("#ge_id,#course_id").attr('disabled','disabled').trigger("chosen:updated");      
			}else{
				$("#ge_id,#course_id").removeAttr('disabled').trigger("chosen:updated");    
			}
			$("#course_id").removeAttr('disabled').trigger("chosen:updated");
		}else{
			$("#course_id").attr('disabled','disabled').trigger("chosen:updated");
		}
        
        var id  = '<?=!empty($this->id)?$this->id:'';?>';
        if(id){
            var totalConductedClass= $('#conducted_class').val();
            var totalAttendClass= $('#attended_class').val();
            var percent= Math.round((totalAttendClass/totalConductedClass)*100);
            $('#percent_sum').val(percent);
            $("#course_id").removeAttr('required').trigger("chosen:updated"); 
            $("#conducted_class,#percent_sum,#course_id").prop('readonly', true); 
            $('.percent_sum').css("background-color", "#eee");
			$('.load-box').css('display','none');
        }
        
        //alert(percent);
    });
    

    $('body').on('change', '#department_id', function () {
        $("#course_id").removeAttr('required').trigger("chosen:updated"); 
        $("#course_id").attr('disabled','disabled').trigger("chosen:updated"); 
        var department_id = $('#department_id').val();
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-employee'; ?>',
            data: {department_id: department_id}
        }).done(function (data) {

            $('#employee_id').empty('');
            $('#employee_id').html(data);

        });
    });
    // To check existed result
    
       
     //for daily new 
    var employee_id = '<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>'; 
    var department_id = $('#department_id option:selected').val();
    var academic_year_id = $('#academic_id option:selected').val();
    var grade_allocate_id = $('#grade_allocate_id').val();
    var department = $('#department').val();
    var ct_id = $('#cc_id option:selected').val();
    var ge_id = $('#ge_id option:selected').val();
    var term_id = $('#cmn_terms option:selected').val();
    var id  = '<?=!empty($this->id)?$this->id:'';?>';
   
    if(ge_id != 0){
        $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-base-of-course'; ?>',
            data: {Ct_id: ct_id, employee_id: '', department_id: '', term_id: term_id, ge_id: ge_id, cc_dept: department}
            }).done(function (data) {

                $('#course_ids').empty('');
                $('#course_ids').html(data);
                $('#course_id').val(<?=$this->course_id;?>).trigger("chosen:updated");
        });
    }
    
    if (term_id) {
          $('.load-box').css('display','block');
        
            
            //var ge_id = $('#ge_id').val();
            var term_id = $('#cmn_terms').val();
            var course_id = $('#course_id').val();
            var session_id = $('#session').val();
            var degree_id = $('#degree_id').val();
            if(department != 0){
                        $('#course_id').attr('disabled','disabled');
                        $('#course_id').removeAttr('required');
                    }
            if (course_id != '' || department) {
                
                $.ajax({
                    type: "POST",
                     url: "<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-students-details-for-daily-attend'; ?>",
                    
data: {employee_id: employee_id, department_id: department_id, ct_id: ct_id, term_id: term_id, course_id: course_id, honors_id: department, session_id: session_id, grade_allocate_id: grade_allocate_id,id:id,degree_id:degree_id}
                }).done(function (data) {
                    $('#grade_data').empty('');	
                    $("#grade_data").html(data);
                    $('.load-box').css('display','none');
                    $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-code'; ?>",
            data: {course_id: course_id}
        }).done(function (data) {
            if(data){
                
          $("<div id='course_container'style='background-color: rgb(253, 245, 154); display: block;' class='col-md-3 text-center'><h2>"+data+"</h2></div>").insertAfter("#dataTable_length");
            }else{
                $("<div id='course_container'style=' display: none;' class='col-md-3 text-center'>");
            }
            
        });       
                });
                
            }
    }
    
     //End
       
   
    $('body').on('change', '#cc_id', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
        let cc_id = $('#cc_id').val();
        let degree_id = $('#degree_id').val();
        let term_id = $('#cmn_terms').val();
        let employee_id= '<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>'; 
        if (cc_id == 2) {
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group-with-empl-for-daily'; ?>',
                data: {cc_id: cc_id,degree_id:degree_id,employee_id :employee_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }else{
             $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-group'; ?>',
                data: {cc_id: cc_id, term_id: term_id}
            }).done(function (data) {
                $('#ge_id').empty('');
                $('#ge_id').html(data).trigger("chosen:updated");
            });
        }
        if(degree_id){
        //alert(degree_id);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-dept-with-empl'; ?>',
                data: {degree_id: degree_id,employee_id : employee_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data);
                $('.load-box').css('display','none');
            });
        }
    });

    
//Disable some field on change course Category(1)
    $('body').on('change', '#cc_id,#department', function () {
        $('#grade_data').empty('');
        $('#studentData').empty('');
		let degree_id= $('#degree_id').val();
        var cc_id = $('#cc_id').val();
        var cc_id_InArray = ["1", "7", "11","16","17","18"];
		//alert(degree_id);
		if(degree_id == 1){
			
			if(jQuery.inArray(cc_id, cc_id_InArray)!='-1'){
				//alert(cc_id);
				$("#ge_id,#course_id").empty();
				$("#department").removeAttr('disabled').trigger("chosen:updated");
				$("#ge_id,#course_id").attr('disabled','disabled').trigger("chosen:updated");   
				$("#ge_id,#course_id").removeAttr('required').trigger("chosen:updated"); 
				
				
			}else{
				$("#department").empty();
				$("#department").attr('disabled','disabled').trigger("chosen:updated");
				$("#ge_id,#course_id").removeAttr('disabled').trigger("chosen:updated"); 
				$("#ge_id,#course_id").attr('required',true).trigger("chosen:updated"); 
					
			}
			$("#course_id").removeAttr('disabled').trigger("chosen:updated");
		}else{
			$("#course_id").attr('disabled','disabled').trigger("chosen:updated");
		}			
    });

//End
//to get course on basis of  ge id
    $('body').on('change', '#ge_id', function () {
     
        $('#grade_data').empty('');
        $('#studentData').empty('');
        $('#course_ids').empty('');
        $('.load-box').css('display','block');
        var employee_id = '';
        var department_id = '';
        var department = '';
        var ct_id = $('#cc_id').val();
        var ge_id = $('#ge_id').val();
        var term_id = $('#cmn_terms').val();
        //alert('ge');
       
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-base-of-course'; ?>',
            data: {Ct_id: ct_id, employee_id: employee_id, department_id: department_id, term_id: term_id, ge_id: ge_id, cc_dept: department}
        }).done(function (data) {
            
            $('#course_ids').html(data).trigger("chosen:updated");
            $(".chosen-select").chosen();
            $('.load-box').css('display','none');
        });
    });
//To get  course category and department on degree change

    $('body').on('change', '#degree_id', function () {
        $('#studentData').empty('');
        var degree_id = $('#degree_id').val();
        var employee_id=  '<?=!empty($this->login_storage->empl_id)?$this->login_storage->empl_id:'';?>'; 
         $('.load-box').css('display','block');
        $('#cc_id').empty();

            
             $.ajax({
                type: "POST",
               url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-course-cat'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                  // alert(data);
                    $('#cc_id').html(data).trigger("chosen:updated");
                   $('.load-box').css('display','none');
                
                });
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-dept-with-empl'; ?>',
                data: {degree_id: degree_id,employee_id:employee_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data);
                $('.load-box').css('display','none');
            });
            
        
    });
    
   
    
       
   

//Semester end Attendance Filter code : Date: 26 March 2020 :Kedar
var default_type  = '<?= $this->type ?>';


if(!default_type){
    $('body').on('change', '#course_id,#department', function () {
        $('#studentData').empty('');
        var term_id = $('#cmn_terms').val();
        var course_id = $('#course_id').val();
        var cc_id = $('#cc_id').val();
        var ge_id= $('#ge_id').val();
        var hons_id = $('#department').val();
        var session = $("#session_filter").val();
        var degree_id= $("#degree_id").val();
        var effective_date = $('#effective_date').val();
        //alert(session);
        $('.load-box').css('display','block');
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-daily-wise-Student'; ?>',
            data: {session:session,term_id:term_id,degree_id:degree_id,effective_date:effective_date,cc_id:cc_id,ge_id:ge_id,hons_id:hons_id,course_id:course_id}
        }).done(function( data ) {
			$('.load-box').css('display','none');
            $('#studentData').empty('');
            //alert(data);
            
            $('#studentData').html(data);
            
             
        });
      
    });
}else{
	//to get monthly attendace
	
    $('body').on('change','#course_id,#department', function () {
        var employee_id = $('#employee_id').val();
        var department_id = $('#department_id').val();
        var honors_id = $('#department').val();
        var ct_id = $('#ge_id').val();
        var term_id = $('#cmn_terms').val();
        var degree_id = $('#degree_id').val();
        var course_id = $('#course_id').val();
        var session = $("#session").val();
        //alert(academic_id);
        //alert(default_type);
        
        $('.load-box').css('display','block');
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-get-students-details-for-daily-attend'; ?>",
            data: {employee_id: employee_id, department_id: department_id, ct_id: ct_id, term_id: term_id, course_id: course_id,session_id: session,degree_id:degree_id,honors_id:honors_id}
        }).done(function (data) {
           
            $('.load-box').css('display','none');
            $('#grade_data').empty('');
            
            $("#grade_data").html(data);
             setDatatables();
        });
        
        $.ajax({
            type: "POST",
            url: "<?php echo $this->mainconfig['host'] . 'grade-allocation/ajax-get-course-code'; ?>",
            data: {course_id: course_id}
        }).done(function (data) {
            if(data){
                
            $("<div id='course_container'style='background-color: rgb(253, 245, 154); display: block;' class='col-md-3 text-center'><h2>"+data+"</h2></div>").insertAfter("#dataTable_length");
            }else{
                $("<div id='course_container'style=' display: none;' class='col-md-3 text-center'>");
            }
        });
    });
//End
}
//After daily attendance implementation
var today = new Date();
$('.monthYearPicker').datepicker({
    dateFormat: 'dd/mm/yy',
    autoclose:true,
    endDate: "today",
    maxDate: today,
    minDate: -40
}).on('changeDate', function (ev) {
        $(this).datepicker('hide');
});


$('.monthYearPicker').keyup(function () {
    if (this.value.match(/[^0-9]/g)) {
        this.value = this.value.replace(/[^0-9^-]/g, '');
    }
});
if(default_type == 'add'){
     $(".monthYearPicker").datepicker("setDate", new Date());
     
}
//Department on teacher department validation
$('#teacher_dept').on('change', function(){
    
    $('#department option[value]').show().trigger("chosen","updated");
    $('#department').val('').trigger("chosen","updated");
    let teacher_dept= $('#teacher_dept').val();

    if(teacher_dept){
        $('#department option[value!='+teacher_dept+']').hide();
    }
});

$('#period').on('change', function() {
    
    let teacher_dept= $('#teacher_dept').val();
    let employee_id= $('#employee_id').val();
    let session= $('#session').val();
    let term_id= $('#cmn_terms').val();
    let degree_id=$('#degree_id').val();
    let effective_date= $('#effective_date').val();
    let period= this.value;
    
   
    
    
    if(!effective_date){
        alert('Please select the date field.');
       $("#period option:selected").prop("selected", false);
    }else{
        $.ajax({
            type: "POST",
            url: '<?php echo $this->mainconfig['host'] . 'batch-attendance/ajax-check-existed-daily-attendance'; ?>',
            data: {session:session,term_id:term_id,degree_id:degree_id,effective_date:effective_date,period:period,teacher_dept:teacher_dept,employee_id:employee_id}
        }).done(function( data ) {
			if((data!='')){
                //alert(data);
                alert("Daily Attendance for this period is already made!");
                $('#period').val('');
                

            } 
            
             
        });
    }
});
</script>
