<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md ">
	<div class="row">
		<div class="col-md-12">
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Faculty Allotment For Courses & Electives</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
					
					<div class="row">
															
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                              <label class="control-label">Batch<span class="asterisk">*</span></label>
                                <?php echo $this->form->academic_year_id; ?>
                            </div>
							</div>
							<div class="col-sm-3">
							<div class="form-group">
                              <label class="control-label">&nbsp;</label>
							<input type="text" id="batch" class="form-control"  style="background-color:#fdf59a;" readonly />
							</div>
							</div>							
							<input type="hidden" name="alloted_id" id="alloted_id" value="<?php echo $this->alloted_id; ?>" />
							<div id="employeedata" class="col-sm-12">
									</div>
							</div>
					
						
						
					</div>
					<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>electives-allotment/index">Back</a>
										</div>
									<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-8">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Faculty Allotment For Courses & Electives</i>
				
		</h3>
	</div>
			<?php
                                            if(in_array($this->role_id, $this->administrator_role)){
                                            ?>	
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-4">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>electives-allotment/index/type/add">Add </a>
		</div>
                    <?php
                                            }
                                            ?>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2> Faculty Allotment For Courses & Electives</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th>S.  No.</th>												
						<th>Batch</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						//print_r($results);die;

					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>						
								
								
								<td><?php echo $results['from_date'] .'&nbsp;&nbsp;-&nbsp;&nbsp;'. $results['to_date']; ?></td>
                                                                <td><a href="<?php echo $this->mainconfig['host']; ?>electives-allotment/index/type/edit/id/<?php echo $results['faculty_allotment_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a><?php if(in_array($this->role_id,$this->administrator_role)){?>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>electives-allotment/index/type/delete/id/<?php echo $results['faculty_allotment_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a><?php } ?></td>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>	
 
	
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}
	
	/*
$("#cc_name").change(function(){
	
	var course_name=$('#cc_name').val();
	//alert(coursename);
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/get-course-category';?>',
			data: {course_name:course_name}
		}).done(function( data ) {
			
			if((data!='')){
				alert("This Course Name Exists");
				$("#cc_name").val("");
			}
		 });
});

*/
$("#elc_name").change(function(){
	$elc_name=$("#elc_name").val();
	if(!isNaN($elc_name))
	{
		alert("Component Name Should be Characters Only");
		$("#elc_name").val("");
	}
});


 	
//check the same name validation	
$("#elc_name").change(function(){
	
	var componentname=$('#elc_name').val();
	
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/get-component-same';?>',
			data: {componentname:componentname}
		}).done(function( data ) {
			
			if((data!='')){
				alert("This Component name Exists");
				  $("#elc_name" ).val("");
			}
		
			
		 });
});




$("#desig_name").change(function(){
	
	
	var desig_name=$('#desig_name').val();
	//alert(desig_name);
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-designation';?>',
			data: {desig_name:desig_name}
			
		}).done(function( data ) {
			
				
			$('#designation_name').empty('');
			$('#designation_name').append(data);
			
		
			
		 });
});


$("#department_name").change(function(){
	
	
	var department_name=$('#department_name').val();
	alert(department_name);
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-department-name';?>',
			data: {department_name:department_name}
			
		}).done(function( data ) {
			
				
			$('#desig_name').empty('');
			$('#desig_name').append(data);
			
		
			
		 });
});


	
$("#academic_year_id").change(function(){
	
	
	var academic_year_id=$('#academic_year_id').val();
	
	
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'electives-allotment/ajax-get-second-year-terms-data';?>',
			data: {academic_year_id:academic_year_id}
			
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if(result !=0){
				 alert('This Batch is already Existed');
				$("#academic_year_id").find('option').attr("selected",false) ;
		 //	alert(data);
		 $('#batch').hide();
              $('#batch').val('');		 
			$("#employeedata").empty('');
			}
			else{
				$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'electives-allotment/ajax-get-second-year-terms';?>',
			data: {academic_year_id:academic_year_id}
			
		}).done(function( data ) {
					$('#employeedata').empty('');
					$('#employeedata').append(data);
		});
			}

			
		
			
		 });
			

});
 var academic_year_id=$('#academic_year_id option:selected').val();
 var alloted_id=$('#alloted_id').val();
	//alert(academic_year_id);
	//alert(emp_allotment);
	if(alloted_id){
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'electives-allotment/ajax-get-second-year-terms';?>',
			data: {academic_year_id:academic_year_id,alloted_id: alloted_id}
			
		}).done(function( data ) {
		
			$('#employeedata').append(data);
			
		
			
		 });
	}	  

$('body').on('change', '#academic_year_id', function() {		
var academic_id=$('#academic_year_id').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	 
 }); 
 
var academic_id=$('#academic_year_id option:selected').val();
   if(academic_id){
   $('#batch').show();
	$.ajax({ 
			type: "POST",
			url:'<?php echo $this->mainconfig['host'].'master/ajax-get-batch-code';?>',
			data: {academic_id:academic_id}
		}).done(function( data ) {
			var result = $.parseJSON(data);
			if((data!='')){
				$('#batch').val(result['short_code']);
			}
	  });
	 }
	else{
$('#batch').hide();
}
</script>
