<style>

</style>
<div class="right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
    <?php if($this->type == "getStudents") {  ?>

        <?php

        if (count($this->messages)) {

            foreach ($this->messages as $message) {

                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

            <?php

            }

        }

        ?>

        <!-- widget grid -->

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> Addon Course Selection </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">



                    </div>

                </div>



                <div class="x_panel">




                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">

                           

                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;" >S. No.</th>
                                        <th style="text-align:center;" >Applicant Name</th>
                                        <th style="text-align:center;" >Form Id</th>
                                        <th style="text-align:center;" >Roll No.</th>
                                        <th style="text-align:center;">Exam Roll No</th>
                                        <th style="text-align:center;">Email Id</th>
                                        <th style="text-align:center;">Addon Course</th>
                                        <th style="text-align:center"rowspan="2">Save AddOn's</th>

                                    </tr>
                                   
                                </thead>

                                <tbody style="text-align:center;">

                                    <?php 
                                            $geinfo = new Application_Model_Ge();
                                            $deptinfo = new Application_Model_Department();
                                            $deptType = new Application_Model_DepartmentType();
                                            $educdet = new Application_Model_ApplicantCourseDetailModel();
                                         
                                            $addoncourse =  new Application_Model_AddonCourseModel();
                                            $addons = new Application_Model_AddonCourseAssignmentModel();
                                         
                                         
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {



                                        foreach ($this->paginator as $results) {
                                              $studentAddon = $addons->getStudentRecords($results['stu_id']);
                                                    $courseDetails = $addoncourse->getDropDownListByYearID($this->session);
                                        // echo '<pre>';print_r($studentAddon);die;

                                            ?>

                                            <tr>

                                                <td>
                                                    <?php
                                                        echo $i;
                                                        $i++;
                                                    ?>
                                                </td>
                                                <td><?php echo $results['students'];?></td>
                                                  <td><?php echo $results['stu_id'];?></td>
                                                
                                                <td><?=$results['roll_no']; ?></td>
                                                <td><?=$results['exam_roll']; ?></td>
                                                <td><?=$results['stu_email_id']; ?></td>
                                                 <td><select class="form-control selected_courses select2" name='selected_courses[]' id="select_<?=$results['stu_id'];?>" required="required"  multiple="multiple">
                                                    
                                                    <?php 
                                                     
                                                  // echo '<pre>'; print_r($courseDetails);exit;
                                                            foreach($courseDetails as $courseIndex => $Coursevalue){
                                                                $chk = 0;
                                                                foreach($studentAddon as $addonIndex => $addCourse){
                                                                    if($addCourse['addon_course_id'] == $courseIndex){
                                                                
                                                    ?>
                                                    <option value="<?=$courseIndex;?>" selected ><?=$Coursevalue;?></option>
                                                    
                                                    
                                                    <?php $chk=1;} //======[end if]=========//?>
                                                    
                                                   <?php 
                                                    
                                                    }//==end inner foreach==//
                                                    if($chk==0 ){
                                                       
                                                    ?>
                                                    <option value="<?=$courseIndex;?>" ><?=$Coursevalue;?></option>
                                                      <?php }} //==end outer Foreach==//
                                                   ?>
                                                    </select>
                                                 </td>
                                               <td><input type="checkbox" style="height: 25px; width: 25px;" name="check[]"  id="check_<?=$results['stu_id'];?>"></td>
                                               
                                            </tr>            

                                            <?php

                                        }

                                        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');

                                    }

                                    ?>

                                </tbody>

                            </table>

    <?php// echo $pagination_tr; ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->
        
 
</div>
<?php  } else if($this->type == "download-icard") { ?>
       
<?php } else { ?>

   <?php if (count($this->messages)) {
        foreach ($this->messages as $message) {
            ?>
            <div class="alert alert-success ">
                <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
            <?php echo $this->escape($message); ?>
            </div>
        <?php }
    } ?>
    <!-- widget grid -->
    <div class="">
        <div class="">
            <div class="row">
               
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Addon Course Selection</i>

                    </h3>
                </div>
                <?php
                //    if(in_array($this->role_id, $this->administrator_role)){
                ?>
               
                <?php
                //  }
                ?>
            </div>

            <div class="x_panel">
               
                <div class="x_title">
                    <div class="row">
                        <div class="col-sm-3 pul-right ">
                            <!--<label class="control-label">Academic Year<span class="asterisk">*</span></label>-->
                            <div class="form-group">
                                <?php echo $this->form->academic_year_list; ?>
                            </div>   
                        </div>
                        <div class="col-sm-3 pul-right ">
                            <!--<label class="control-label">Session <span class="asterisk">*</span></label>-->
                            <div class="form-group">
                                <?php echo $this->form->session; ?>
                            </div>
                           
                        </div>
                        <div class="col-sm-3 ">
                            
                        <button type="button" id="getRecord" class="btn btn-primary" style="float: left" value="0" >Get Record</button>
                        </div>
                       
                    </div>     
                    
                </div>
                <div  id="ajaxData"> 
            <table class="table table-striped table-bordered mb30 jambo_table bulk_action " id="dataTable">
        <thead>
            <tr>
                <th>S.No.</th>
                <th style="width: 15em">Department </th>
                <th style="width: 15em">No. Of Active Students</th>
                <th>No. of Left Students</th>
                <th>Total Students</th>
                <th>View Students</th>
                
            </tr>
        </thead>
        <tbody>
        </tbody>
            </table>
                </div>
                      
               
                </div><!-- /panel -->
            </div>
        </div>
    </div><!-- /.padding-md -->
<?php } ?>
</div>
<script>
    $(document).ready(function() {	
    $('.selected_courses').select2();
    
});


$('input[type="checkbox"]').click(function() {
   // alert('kl0');
    var checkbox = $(this);
 var patt = /F-\d{4}-\d{1,}/i;
 
       var str =  $(this).attr('id');
       //alert(str);
       var form_id = str.match(patt);
       var selectId = 'select_'+form_id;
       var select = $('#'+selectId + '>option');
       var course_id = [];
       
       if(checkbox.is(":checked")){
      select.each(function(){
          if($(this).prop("selected") ){
               course_id.push($(this).val());
                        
              
          }
      });
      if(course_id){
          $.ajax({
                    type: "POST",
                    url: '<?php echo $this->mainconfig['host'] . 'entrance-report/ajax-insert-addons'; ?>',
                    data: {form_id:form_id[0],course_id:course_id}
                }).done(function (data) {
                    alert('Credit course has been assigned.');
                  });
      }
       }
  
});
$('body').on('change', '#academic_year_list', function () {
        $('#department').removeAttr('disabled');
        var year_id = $('#academic_year_list').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
 //Added: By Kedar 13 Nov. 2019
    $(document).on('click','#getRecord',function() { 
        var session_id = $('#session').val();
        if (session_id) {
            $('.load-box').css('display','block');
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student/ajax-get-dept-wise-student-for-addon-course'; ?>',
                data: {session_id: session_id}
            }).done(function (data) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display','none');
            });
        }
    });
    //End
</script>