<style>

    #refresh{
        cursor:pointer;
    }
#search_cl>div{
    padding:.1em;
}
.input-group {
     margin-bottom: 0px; 
}
.input-group[class*=col-] {
    float: none;
   display:inline-table
}
/*span.total{*/
/*    display:none;*/
/*}*/
</style>
<?php $atominput = $_SESSION['atominput']; 
unset($_SESSION['atominput']);
?>
<div class="right_col bdoypayment">
    <div class="load-box" style="z-index:998">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div>
      <?php  if($this->type == "add") { ?>
     <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-8">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Import Addon's Marks</i>

                    </h3>
                </div>
                 <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                    <h3 class="page-title txt-color-blueDark">
                        <a href="<?php echo $this->mainconfig['host']?>student/fees-updation/" class="btn btn-primary pull-right">Back</a>

                    </h3>
                </div>
            </div>
            <div class="col-md-12">
                <form action="add"  method="post" enctype="multipart/form-data">
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                 <label class="control-label">Import CSV File<span class="asterisk">*</span></label>
                     <input type="file" name="file" />
                     
                    </div>
                </div>
              
                    <div class="col-sm-3 employee_class">
                        <div class="form-group">
                            <input type="submit" name="submit" value="Import" class="btn btn-primary pull-right" style="margin-top:1.5em;z-index:999;">
                           </div>
                    </div>
               
                </form>
                <div style="float:left;padding-left:10%;">
                </div>
            </div>
        
        </div>    


    </div>
    
    <?php } else {?>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-12 col-sm-7 col-md-7 col-lg-8">
                    <h3 class="page-title txt-color-blueDark">
                        <i class="fa fa-bars">Addon's Marks import</i>

                    </h3>
                </div>
                <!-- <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">-->
                <!--    <h3 class="page-title txt-color-blueDark">-->
                <!--        <a href="<?php echo $this->mainconfig['host']?>student/fees-updation/type/add" class="btn btn-primary pull-right">Add</a>-->

                <!--    </h3>-->
                <!--</div>-->
            </div>
            <div class="col-md-12">
                
                
         
             
                <!--<div class="col-sm-3 employee_class exam_date" style="display:none;">-->
                <!--    <div class="form-group">-->
                <!--        <select name="batch_id" class="form-control" id="batch_id">-->
                            
                <!--        </select>-->
                        <!--<label class="control-label">Semester<span class="asterisk">*</span></label>-->
                        <?php ///echo $this->form->term_id; ?>
                <!--    </div>-->
                <!--</div>-->
<!--                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Batch<span class="asterisk">*</span></label>
                        <?php //echo $this->form->academic_id; ?>
                    </div>
                </div>
                <div class="col-sm-3 employee_class">
                    <div class="form-group">
                        <label class="control-label">Semester<span class="asterisk">*</span></label>
                        <?php //echo $this->form->term_id; ?>
                    </div>
                </div>-->
                 
                <div class="col-sm-2 employee_class">
                    <div class="input-group">
                    <input type="file" class="form-control" id="customFile" accept=".csv"  />
                    </div>
                  </div> 
                <div class="col-md-12">
                    <div class="col-sm-3 col-sm-offset-3 employee_class">
                        <div class="form-group">

                        </div>
                    </div>

                    <div class="col-sm-3 employee_class">


                    </div>
                    <div class="col-sm-12">
                        <ul class="nav nav-pills pull-right">
                            
                          <li id="getRecords"><a href="#">Open&nbsp;<i class="fa fa-folder-open-o" ></i></a></li>
                        </ul>
                    </div>
                    
                </div>

                <div style="float:left;padding-left:10%;">
                </div>
            </div>
            <div class="col-md-12">
                <div class="table-responsive" id="ajaxData"> 
                    <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive" style="height:100%">
                        <thead>
                            <tr>
                                <th class="no-sort">S.No.</th>
                                <th>Student Name</th>
                                <th>UID</th>
                                <th>Transaction Id</th>
                                <th>Status</th>
                                <th>Pay Mode</th>
                                <th>Amount</th>
                                <th>Batch</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="9">
                                    <h2 style="color:red">
                                        No Records Available.
                                    </h2>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="col-md-12 text-center"><button class="btn btn-primary" id = "update">Add</button></div>
            </div>
        </div>    
    </div>
<?php } ?>

<button type="button" class="btn btn-info btn-lg" data-toggle="modal" id="modal" style="display:none;" data-target="#myModal">Open Modal</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
        <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>
</div>


<script src="https://cdn.jsdelivr.net/npm/papaparse@5.3.2/papaparse.min.js"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/puppeteer@18.2.1/lib/cjs/puppeteer/puppeteer.min.js"></script>-->
<script>
$(".nav-pills li").click(function(){
    $(".nav-pills li").removeAttr("class");
    $(this).attr("class","active");
})

    $('.datepicker').datepicker();
var headers = []
         var atomjson = '<?php if(isset($atominput))echo $atominput; ?>';
         console.log(atomjson);
         if(atomjson){
            jsonarr = JSON.parse(atomjson);
            if(jsonarr.value.length>0){
                var arr = Papa.unparse(jsonarr.value, {
                    header:true
                });
        
                var arr = Papa.parse(arr, {
                    header:false
                });
                 headers = arr.data[0];
                             var table = createTable(arr.data);
                                $('#ajaxData').empty('');
                                $('#ajaxData').html(table);
                                setDatatablesDasboard();
                                $('.load-box').css('display', 'none');
            }
 
            }




// // api url
// const api_url = 
//       "http://localhost:3000/12-10-2022_12-10-2022";
  
// // Defining async function
// async function getapi(url) {
    
//     // Storing response
//     const response = await fetch(url);
    
//     // Storing data in form of JSON
//     var data = await response.json();
//     console.log(data);
//     if (response) {
//         hideloader();
//     }
//     show(data);
// }








//Author: Kedar: 22 Oct 2020 : To get record by filter crieteria
var headers = [];
    $('body').on('click', '#getRecords', function () {
        //  var imported_files = $('#imported_files').val();
         $('.load-box').css('display', 'block');
         var imported_files = $('#customFile')[0].files[0];
                     Papa.parse(imported_files, {
            	download: true,
            	header:false,
            	skipEmptyLines:true,
            	complete:function(results){
            	    var parseddata = results.data;
            	    headers=parseddata[0];
            	        var table = createTable(parseddata);
                        $('#ajaxData').empty('');
                        $('#ajaxData').html(table);
                        setDatatablesDasboard();
                        $('.load-box').css('display', 'none');
            	    
            	}
            });
      
    });
     

    
    $('body').on('click','#update',function(){
        let sem = $('#cmn_terms').val();
             //  $('.load-box').css('display', 'block'); 
                var fees_type = $('#fees_type').val();
                var filteredRows = table.rows( {order:'index', search:'applied'} ).data();
                var savingdata = [];
                headers = headers.map(headers => headers.trim().replace(/\./g,"").replace(/\s+/g, ' ').replace(/\s/g,"_").toLowerCase());
              
                savingdata.push(headers);
                
                for (var i=0; i<filteredRows.length; i++) {
                        savingdata.push(filteredRows[i]);
                    }
                savingdata = Papa.unparse(savingdata);
                savingdata = Papa.parse(savingdata,{header:true});
                    
                    
             $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'report/ajax-insert-addon-records'; ?>',
                data: {savingdata,headers}
            }).done(function (data) {
                if(data > 0){
                    alert("Record Inserted..");
                    location.reload();
                }
                else{
                     alert("Record Not Inserted..")
                }
              //   $('.load-box').css('display', 'none');
            });
        
    });
    
     $('body').on('click','#delete',function(){
         var file_name = $('#imported_files').val();
         var r = confirm("Are you sure you want to delete this Image?")
    if(r == true)
    {
         $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'report/ajax-delete-csv-records'; ?>',
                data: {file_name}
            }).done(function (data) {
                if(data){
                    alert("Deleted..");
                    location.reload();
                }
                else{
                     alert("error..");
                     location.reload();
                }
            });
    }
         
     });

    //To filter Session
    $('body').on('change', '#academic_year', function () {
        var year_id = $('#academic_year').val();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    //Get Batch By Session
    $('body').on('change', '#session', function () {
        var year_id = $('#session').val();
        //$('#batch_id').hide();
        if (year_id) {

            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch1'; ?>',
                data: {session: year_id}
            }).done(function (data) {
               // $('#academic_id').empty('');
                $('#academic_id').val(data);
               // $('#academic_id').trigger("chosen:updated");
            });
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-batch'; ?>',
                data: {session: year_id}
            }).done(function (data) {
                $('#batch_id').empty('');
                $('#batch_id').html(data);
                $('#batch_id').trigger("chosen:updated");
            });
        }
    });


     $('body').on('change', '#cmn_terms', function () {
        var session_id = $('#session').val();
        var cmnterms = $('#cmn_terms').val();
        if (session_id) {
///alert(cmnterms);
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-term-session'; ?>',
                data: {session_id: session_id,cmnterms:cmnterms}
            }).done(function (data) {
              //  alert(data);
                //$('#term_id').empty('');
                $('#terms_id').val(data);
                
            });
        }
    });

    
function getCells(data, type) {
  return data.map(cell => `<${type}>${cell}</${type}>`).join('');
}

function getInputcells(data, type){
    return data.map(cell => `<${type} class="col-md-1">${cell}</${type}>`).join('');
}

function createBody(data) {
  return data.map(row => `<tr>${getCells(row, 'td')}</tr>`).join('');
}

function createTable(data) {

  // Destructure the headings (first row) from
  // all the rows
  const [headings, ...rows] = data;

  // Return some HTML that uses `getCells` to create
  // some headings, but also to create the rows
  // in the tbody.
  return `
    <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive">
      <thead>${getCells(headings, 'th')}</thead>
      <tbody>${createBody(rows)}</tbody>
    </table>
  `;
}



    
function getCells(data, type) {
  return data.map(cell => `<${type}>${cell}</${type}>`).join('');
}

function getInputcells(data, type){
    return data.map(cell => `<${type} class="col-md-2 form-group-sm input-group">${cell}</${type}>`).join('');
}

function createBody(data) {
  return data.map(row => `<tr>${getCells(row, 'td')}</tr>`).join('');
}

function createTable(data) {

  // Destructure the headings (first row) from
  // all the rows
  const [headings, ...rows] = data;

  // Return some HTML that uses `getCells` to create
  // some headings, but also to create the rows
  // in the tbody.
  return `
    <table class="table table-striped table-bordered mb30 jambo_table bulk_action dataTable" id="datatable-responsive">
      <thead>${getCells(headings, 'th')}</thead>
      <tbody>${createBody(rows)}</tbody>
      
    </table>
  `;
}



 // DataTable
  
          function destroyDtable(){
                 if ($.fn.DataTable.isDataTable("#datatable-responsive")) {
        $('#datatable-responsive').DataTable().clear().destroy();
    } 
          }
    function setDatatablesDasboard(){
    
       // Setup - add a text input to each footer cell
  
    // ======[in above span code ]&nbsp;<input type="checkbox" data-id = "'+i+'"/>
    var cols = [];
    $('[type="checkbox"]').click(function(){
        var index = $(this).data('id');
        
        table.columns(index).visible(!$(this).is(':checked'));
        cols.push(index);
         $('[data-id="'+index+'"]').parents("div.input-group").hide(300);
        localStorage.setItem("columns", cols);
        
    });
    
$("#restore").click(function(){
       if ("columns" in localStorage) {
            	        var col = localStorage.getItem("columns");
            	        refresh(col,true);
        }
    localStorage.clear();
});
    
    
  
   table = $('#datatable-responsive').DataTable({
    //   dom: 'Bfltip',
        initComplete: function () {
 $('span.total').hide();
                
$( '#search_cl>div>input').on( 'keyup change clear', function () {
                    var columnno = $(this).parents('div').index();
                        table.column(columnno).search(this.value, true,true).draw();
                        if(this.value){
                        var amount=(item)=>{return !isNaN(item)?parseInt(item):1};
                        var sum = (prev, next) =>{return prev + next};
                        var number = table.column(columnno, {filter:'applied'}).data();
                        var total = number.map(amount).reduce(sum,0);
                        $('span.total').eq(columnno).show();
                        }
                        else
                        {
                            $('span.total').eq(columnno).hide();
                            total = 0;
                        }
                        $('span.total').eq(columnno).text(total);
                        console.log(total);
                        
                });
        }
       
    });
    
    if ("columns" in localStorage) {
            	        var col = localStorage.getItem("columns");
            	        refresh(col);
                        }
}

function refresh(col,bool=false){
     var cols = col.split(',');
     console.log(table);
    if(cols.length > 0){
        table.columns(cols).visible(bool);
     for(i in cols){
         if(!bool)
        $('[data-id="'+cols[i]+'"]').parents("div.input-group").hide();
        else
         $('[data-id="'+cols[i]+'"]').parents("div.input-group").show();
     }
    }
}
</script>

