 <?php if(!empty($this->result)){ 
    
    $student = $this->result;
  // echo "<pre>";print_r($student);exit;
$StudentPortal_model = new Application_Model_StudentPortal();
$details = $StudentPortal_model->getStudenInfo($student['form_id']);

?>
   

                                                 
                                                 
  
<style>
    @page {
        background: url('https://pwcadmissions.in/academic/public/images/Certificate_watermark/passout.jpg') no-repeat 0 0;
        background-image-resize: 6;
    }

@font-face {
  font-family: charcoal;
  src: url(../../../fonts/lci.ttf);
}
 h4 {
    font-family:charcoal;
        font-weight:bolder;
        font-size:1.5em;
 }
  button,fieldset{
      position:fixed !important;
      display:none !important;
  }
   p{
        font-size: 18px;
        line-height: 2em;
        text-align: justify;
        /*margin:20px 20PX;*/
    }
   b{
        font-size: 15px;
    }
    .pull-right{
        text-align: right;
        
    }
    .sup {
        text-align: center;
        font-size:.8em;
}
    /*table{*/
    /*    margin:20PX 20PX;*/
    /*}*/
    .sub{
        border:.01em solid #932e90;
        text-align: center;
        font-size:.8em;
    }
    #applicationFormPreview{
        padding:3em;
        padding-bottom:5em;
        padding-top:0;
        border:3px solid #000;
    }
  
 
</style>

    <?php //echo '<pre>'; print_r($this->duplicate);exit; ?>
<div class="appForm" id="applicationFormPreview">

       <div style="float:right;padding-bottom: 3em;" id="divbutton">
            <button type="button" id="printAppForm2"  class="btn btn-primary" onclick="window.print()"></button>
        </div>
   <table class="tablestyle1" width="100%" cellspacing ="0" style="margin-bottom:20px" >
                    <tr>
                      
                 <td ><p style="font-family: serif;">  Sl.No.: <?= $student['slno'] ?></p></td>
                 <td style="text-align:right;"><p style="font-family: serif;">Registration No.: <?= $student['registration_no'] ?></p></td>     
                        
                      
            </tr>
            </table>
        <div class="row" id="section-to-print">  
        <table class="tablestyle1" width="100%" cellspacing ="0" >
                    <tr>
                        <td>
                             <div class = 'sub' style="text-align: center;">
                    
                    <img src="<?php echo $this->mainconfig['publicpath']; ?>img/logo.png" width="80" height="100">               
                </div>
                        </td>
                
               <td style="text-align: center;"> 
            
                 <div class = 'sub' style="text-align: center; font-size: 28px; font-weight:bold; ">
                     PATNA WOMEN'S COLLEGE 
                 </div>
                 <div class = 'sub' style="text-align: center; font-size: 20px ">
                     Autonomous
                 </div>
                <div class = 'sub' style="text-align: center; font-size: 20px ">
                        Patna University             
                </div>
        <p style="text-align: center;line-height:0em;margin:0px;"><span style ="font-size:0.8em;">3rd Cycle NAAC Accredited <span style="text-transform: lowercase;">at</span> A Grade <span style="text-transform: lowercase;">with</span>&nbsp;CGPA 3.58/4</span><br/>
    <span style ="font-size:0.8em;">"College<span style="text-transform: lowercase;"> with</span> Potential <span style="text-transform: lowercase;">for</span> Excellence" (CPE) <span style="text-transform: lowercase;">&nbsp;status accorded by </span>UGC</span>
                </p>
                <br>
               
            
            </td>
            <td style="text-align:center; font-weight:bold">
            <img src="<?=$this->baseUrl($details['filename']);?>" width="70" height="100"> <br/>
            <?=$student['Form_Id'];?>
                </td>
                </tr>
            </table> 
            <div class="col-xs-12" style="margin-top:40px">
                <?php  //echo '<pre>'; print_r($this->mainconfig['publicpath']); exit;?>
               
                    <div class="col-xs-12" >
                        <h2 style="text-align: center; font-size: 1.2em;">CREDIT BASED ADD-ON CERTIFICATE COURSE</h2>
                        <h3 style="text-align: center; font-size: 1em;margin:0"><?=strtoupper($student['course_name']);?></h3>
                        <?php  if(!is_numeric(stripos($student['ref'],'Default'))){ ?>
                        <h3 style="text-align: center; font-size: 1em;margin:0">(DEPARTMENT OF <?=strtoupper($student['conducted_by_department']);?>)</h3>
                        <?php } ?>
                    </div>
                     <p style="font-family: lucida;">
                            This is to certify that <b><?=strtoupper($student['name']);?>
                            </b> Department of <b><?=ucfirst($student['department_of_student']);?></b> Session <span style="font-family: serif;"><b><?=$student['session'];?></b></span> Examination Roll No. <span style="font-family: serif;"><b><?=$student['examination_roll_no'];?></b></span>
                            has successfully completed the <b>Certificate Course in <?=ucfirst($student['course_name']);?> </b>of<b> <?=$student['total_credits'];?> credits*</b> 
                            and has obtained <b><?=$student['grade'];?></b> Grade in the examination held in the month of April 2022.
                    </p>
                    <div class="col-xs-12" style="text-align: center; font-size: 1em;">
                        <strong><H3 style="font-size: 1.2em;">MARKSHEET</h3></strong>
                    </div>
                    <table class="tablestyle1" width="100%" cellspacing ="0" >
                    <thead>
                    <tr>
                        <th class="sub">Paper</th>
                        <th class="sub">Paper Name</th>
                        <th class="sub">Paper Code</th>
                        <th class="sub">Credits</th>
                        <th class ="sub">Full Marks</th>
                        <th class="sub">Obtained Marks</th>
                    </tr>
                </thead>
                <tbody>
                    <?php 
                    $roman_container = array("i","ii","iii","iv");
                    $str = implode(" ",array_keys($student));
                    $papercount = substr_count($str,"paper_code");
                    $credit= 0;
                    $fullmarks = 0;
                    $obt_marks = 0;
                    $cunt = 0;
                    for($i=0;$i<$papercount;$i++){
                      if(!preg_match('/[a-zA-Z]+/', $student['paper_'.$roman_container[$i]]))
                      continue;
                        $cunt++;
                    ?>
                    <tr>
                    <td class="sub" style="text-align:left;"><?=$student['paper_'.$roman_container[$i]]?></td>
                    <td class="sub" style="text-align:left;"><?=$student['paper_name_'.$roman_container[$i]]?></td>
                    <td class="sub"><?=$student['paper_code_'.$roman_container[$i]]?></td>
                    <td class="sub"><?=$student['credits_'.$roman_container[$i]]?></td>
                    <td class="sub"><?=$student['full_marks_'.$roman_container[$i]]?></td>
                    <td class="sub"><?=$student['obtained_marks_'.$roman_container[$i]]?></td>
                    
                    </tr>
                    <?php $credit+=$student['credits_'.$roman_container[$i]];
                           $fullmarks+= $student['full_marks_'.$roman_container[$i]];
                         $obt_marks+=  $student['obtained_marks_'.$roman_container[$i]];
                    
                    }  ?>
                </tbody>
                <tfoot>
                    <tr>
                    <th class="sub" style="text-align:left;" > Grand Total</th>
                    <th class="sub" colspan="2"></th>
                    <th class="sub"><?=$credit;?></th>
                    <th class="sub"><?=$fullmarks;?></th>
                    <th class="sub" ><?=$obt_marks;?></th>
                    </tr>
                </tfoot>
                </table>
                 <table class="tablestyle1" width="100%" <?php if($cunt > 3){ echo 'style="margin-top:20px"';}else if($cunt < 3){echo 'style="margin-top:50px"';}else{echo 'style="margin-top:40px"';} ?> cellspacing ="0" cellpadding="0" >
                    <thead>
                        <tr>
                            <?php 
                                $grades = $this->grades;
                                
                            foreach($grades[0] as $value){ 
                            ?>
                            <th class="sub"><?=$value;?></th>
                            <?php } ?>
                            
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                            $i = 1;
                            while($i<count($grades)){
                        ?>
                        <tr>
                         
                            <td class="sub">
                                <table style="width:100%;margin:0" cellspacing = 0 cellpadding="0">
                                    <tr><td class="sub" style="height:10px; width:15px"><span style='font-family:helvetica; <?php if($student['grade']==$grades[$i][1]) echo "color:blue;";else echo "color:white;"; ?>'>&#10004;</SPAN></td>
                                    <td style="text-align:left;" class="sup" >&nbsp;<?=$grades[$i][0];?></td></tr></table></td>
                            <td class="sub"><?=$grades[$i][1];?></td>
                            <td class="sub"><?=$grades[$i][2];?></td>
                         
                        </tr>
                        <?php 
                               $i++; }
                        ?>
                    </tbody>
                </table>
                
                
                
                
              
</div>
</div>
<table class="tablestyle1" width="100%" cellspacing ="0" style="margin-top:120px;" >
                    <tr>
                        <td  style="font-family: lucida; font-weight:700; text-align:center; font-size:.7em;vertical-align:bottom;">Date:<br/><?=$student['date_of_result'];?><br/>*(1 credit - 15 hrs.)</td>
                        <td  style="font-family: lucida; font-weight:700; text-align:center; font-size:.7em;vertical-align:bottom;width:150px">Coordinator</td>
                        <td  style="font-family: lucida; font-weight:700; text-align:center; font-size:.7em;vertical-align:bottom;"><img  src="<?php echo $this->mainconfig['publicpath']; ?>images/controler.jpg" alt="..." height="40" width="190px"><br/>Controller of Examinations</td>
                        <td  style="font-family: lucida; font-weight:700; text-align:center; font-size:.7em ;vertical-align:bottom;"><img  src="<?php echo $this->mainconfig['publicpath']; ?>images/principal.jpg" alt="..." height="40" width="190px"><br/>Principal</td>
                    </tr>
                </table>
                <div  <?php if($cunt > 3){ echo 'style="margin-top:10px"';}else if($cunt < 3){echo 'style="margin-top:60px"';}else{echo 'style="margin-top:40px"';} ?>>
                    
                </div>
</div>

<?php }else{ ?>   

<div class="right_col">
    <label id="alert_msg" style="color:red; ">
       Result not found.....!Oop's:) 
    </label> 
    
</div>
<?php  }  ?>                                         