<?php if(!empty($this->paginator)){ ?>
<?php

    $geinfo = new Application_Model_Ge();
    $deptinfo = new Application_Model_Department();
    $deptType = new Application_Model_DepartmentType();
    $educdet = new Application_Model_ApplicantCourseDetailModel();
    
    //echo '<pre>'; print_r($this->paginator);exit;
?>
   

                                                 
                                                 
  
<style>
@media print {
  
  button,fieldset{
      position:fixed !important;
      display:none !important;
  }
  
  
    #applicationFormPreview{
        padding-left: 2em;
        padding-right:2em;
        position:absolute !important;
        top:0px !important;
        width:100%;
    }
  
  
  .pagebreak {
       clear: both;
      page-break-after: always; }
}
 @page 
    {
        position:absolute !important;
        size:  auto;   /* auto is the initial value */
        margin: 1mm;
        margin-top:0; 
       /* this affects the margin in the printer settings */
    }   
    
</style>
<div class="right_col">
<div class="appForm" id="applicationFormPreview">
<div class="" id="applicationFormPreview">
       <div style="float:right;padding-bottom: 3em;" id="divbutton">
            <button type="button" id="printAppForm2"  class="btn btn-primary" onclick="window.print()">Print</button>
        </div>
 
        <div class="row" id="section-to-print">
        
                
            <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">

                <thead>
                    <tr>
                       
                    </tr>
                </thead>
                <tbody>
                   
                    <tr>
                        <td class="col-sm-2 col-sm-offset-1">
                            <div class="form-group" style="padding-top: 1em;">
                                 <img src="<?php echo $this->baseUrl($this->paginator['filename']);?>" alt="img" height="160" width="190">
                                  <h4 style="text-align: center"> <?= $this->paginator['stu_id'] ?> </h4><br>
                            </div>
                        </td>
                       

                        <td class="col-sm-8">
                            <div class = 'sub' style="text-align: center;">
                                <h4> PATNA WOMEN'S COLLEGE</h4>
                                <h5>AUTONOMOUS</p></h5>
                                <h4>PATNA UNIVERSITY</h4>
                                <h5>3rd Cycle NAAC Accredited at A Grade with CGPA 3.58/4</h5>
                                <h5>College with Potential for Excellence(CPE) status accorded by UGC</h5>
                                <h5> BAILEY ROAD,PATNA - 800 001, BIHAR</h5>
                                <h5>Admission Card</h5>
                                 </div>
                        </td>
                         <td class="col-sm-2 col-sm-offset-1">
                           
                            <div class="form-group">
                                <img src="<?php echo $this->mainconfig['publicpath']; ?>img/logo.png" width="120" height="130">          
                            </div>
                        </td>
                        
           

                    </tr>
                  
                </tbody>
            </table>
                <table id='a' class="table table-striped table-bordered mb30 jambo_table bulk_action " border="1">

                    
                    <tbody>
                       
                        <tr>
                           
                            <td class="">
                             Degree Name
                            </td>
                           
                            <td class="">
                               <?php if($this->paginator['degree_id'] == 1){
                                    echo 'Graduation';
                               }else{
                                   echo 'Post Graduation';
                               } ?>
                            </td>
                            
                           
                        </tr>
                        <tr>
                           
                            <td class="">
                                Batch
                            </td>
                           
                            <td class="">
                                <?php echo $this->paginator['short_code']; ?>
                            </td>
                            
                           
                        </tr>
                        
                        <tr>
                           
                            <td class="">
                                <div class="col-xs-12">
                                    <p>Name:</p>
                                    <p>Father's Name:</p>
                                    <p>Caste</p>
                                    <p>Roll No.</p>
                                    <p>Reg. No.</p>
                                    <p>Session:</p>
                                    <p>Date Of Admission</p>
                                </div>
                            </td>
                            <td class=""> 
                                <p><?php echo $this->paginator['stu_fname'];?></p>
                                <p><?php echo $this->paginator['father_fname'];?></p>
                                <p><?php echo $this->paginator['stu_caste'];?></p>
                                <p><?php echo $this->paginator['roll_no'];?></p>
                                <p><?php echo $this->paginator['stu_id'];?></p>
                                <p><?php echo  $this->paginator['session']; ?></p>
                                <p><?php echo date('d-m-Y') ?></p>
                            
                            </td>   
                        </tr>
                        <tr>
                             <?php if($this->paginator['degree_id'] == 1){?>
                            <td class="">
                                Subjects
                            </td>
                           
                            <td class="">
                               <div class="col-xs-6">
                                    <p>Core Course Honours:</p>
                                    <p>Generic Elective Course(Subsidiary):</p>
                                    <p>Ability Enhancement Compulsory Course:</p>
                                    <p>Compulsory:</p>
                                </div>
                               <div class="col-xs-6">
                                    <p><?php echo  $this->paginator['short_code']; ?></p>
                                    <p><?php echo  $this->ge; ?></p>
                                    <p>
                                     
                                    <?= $this->aecc == 5?'English':'Hindi'?></p>
                                    <p>Environmental Science</p>
                                </div>
                                
                            </td>
                             <?php } ?>
                           
                        </tr>
                        
                         <tr>
                            <td class="">
                              Date: <?php echo date('d-m-Y'); ?>
                            </td>
                           
                            <td class="">
                                <div class="col-xs-12" style="padding-top: 7em;"> 
                                    <p style="text-align: center">College Signature & Seal</p>
                                </div>
                            </td>
                            
                        </tr>
                        <tr>
                            <td style="text-align: center" colspan="2"></td>
                        </tr>
                        <tr>
                            <td style="text-align: center" colspan="2"> <b>I-Card Details </b></td>
                        </tr>
                         <tr>
                           
                            <td class="">
                                <div class="col-xs-12">
                                    <p>Name:</p>
                                    <p>Hons:</p>
                                    <p>Roll No.</p>
                                    <p>Father's Name:</p>
                                    <p >Address:</p>
                                    <p>Phone:</p>
                                    <p>Session:</p>
                                    <p>Blood Group:</p>
                                </div>
                            </td>
                            <td class=""> 
                                <div class="col-xs-8">
                                <p><?php echo $this->paginator['stu_fname'];?></p>
                                <p><?php echo  $this->paginator['short_code']; ?></p>
                                 <p><?php echo $this->paginator['roll_no'];?></p>
                                <p><?php echo $this->paginator['father_fname'];?></p>
                                <p>
                                    <?php echo $this->paginator['premanent_addr'];?>
                                </p>
                                <p><?php echo $this->paginator['father_mobileno'];?> 
                               
                                </p>
                                <p><?php echo $this->paginator['session'];//echo $deptType->getRecord($this->paginator['course'])['session']; ?></p>
                                <p><?= !empty($this->paginator['blood_group'])?$this->paginator['blood_group']:'N/A';?></p>
                                </div>
                                <div class="col-xs-4">
                                   <div class="form-group" style="padding-top: 1em;">
                                 <img src="<?php echo $this->baseUrl($this->paginator['filename']);?>" alt="img" height="160" width="190">
                                  <h4 style="text-align: center"> <?= $this->paginator['stu_id'] ?> </h4><br>
                            </div> 
                                </div>
                            </td>   
                        </tr>
                        
                    </tbody>
                </table>
                
            
       
       
        </div>
</div>
</div>
</div>
<?php }else{ ?>   

<div class="right_col">
    <label id="alert_msg" style="color:red; ">
       Class Roll Number is not generated!   
    </label> 
    
</div>
<?php  } ?>                                         