<style>
    table.dataTable.fixedHeader-floating {
    position: relative !important;
  
}
</style>

<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  >
                            <thead >
                                <tr >
                                    <th>S.No.</th>
                                    <th> Students Name</th>
                                    <th>Roll No</th>  
                                    <th>Semester </th>  
                                    <th>Form Id</th>  
                                    <th>Exam Roll No</th>  
                                    <th>Section</th>  
                                </tr>
                                   
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                        //echo '<pre>'; print_r($results);exit;
                                        $reqModel=new Application_Model_Section();
                                        $sections= $reqModel->getSectionId($results['term_id']);
                                        
                                        //echo '<pre>'; print_r($sections);exit;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                        </td>						
                                        
                                            <td><?php echo $results['studentName']; ?></td>
                                            <td><?php echo $results['roll_no']; ?></td>
                                            <td><?php echo $results['term_description']; ?></td>
                                            <td><?php echo $results['form_id']; ?></td>
                                            <td> <?php echo $results['exam_roll']; ?></td>
                                            <td>  
                                            <input type="hidden" name="stu_id" id="student_id" value="<?php echo $results['stu_id']; ?>" /> 
                                        <div class="form-group">
                                            <select class="form-control" name ="selectedSection" id = "selectedSection" disabled="disabled" required="true">
                                            <option value="">--select--</option>
                                                <?php foreach ($sections as $key => $value) {?>
                                                  <option value="<?= $value['id'];?> " <?php if($results['section'] == $value['id'] ){ echo 'selected'; }?>  ><?=$value['sectionName'] ?> </option>
                                            <?php } ?>
                                           </select>
                                        </div>
                                            </td>
                                           
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
 <?php echo $pagination_tr; ?>
<script>
  setDatatablesManual();
     $('body').on('change', '#selectedSection', function () {

    let academic_id = $('#academic_id').val();
    let session = $('#session').val();
    let termId = $('#term_id').val();
    let SectionId = $(this).closest("td").find("#selectedSection").val();
    let student_id = $(this).closest("td").find("#student_id").val();
    //alert(termId);
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'student/ajax-update-student-section'; ?>',
        data: {SectionId:SectionId,student_id:student_id,termId:termId,academic_id:academic_id,session:session}
    }).done(function (data) {
        
        alert("Section changed successfully.");

    });   
});
    </script>