

<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable" >
                            <thead>
                                <tr>
                                    <th>S.No.</th>
                                    <th> Students Name</th>
                                    <th>Roll No</th>  
                                    <th>Form Id</th>  
                                    <th>Exam Roll No</th>  
                                </tr>
                         
                            </thead>
                            <tbody>
                                <?php
                                $i = 1;
                                $pagination_tr = '';
                                if (count($this->paginator) != 0) {

                                    foreach ($this->paginator as $results) {
                                        //echo '<pre>'; print_r($results);exit;
                                        ?>
                                        <tr>
                                            <td><?php echo $i;

                                        $i++;
                                        ?>
                                        </td>						
                                        <input type="hidden" name="stu_id[]" id="student_id" value="<?php echo $results['student_id']; ?>" /> 
                                            <td><?php echo $results['stu_fname']; ?></td>
                                            <td><?php echo $results['roll_no']; ?></td>
                                            <td><?php echo $results['stu_id']; ?></td>
                                            <td> <?php echo $results['exam_roll']; ?></td>
                                           
                                        </tr>            

                                    <?php
                                    }
                                    $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                                }
                                ?>

                            </tbody>
                        </table>
 <?php echo $pagination_tr; ?>
<script>
   setDatatablesManual();
   
 
   
    </script>