
<style type="text/css">

    .bold-checkbox{
        position: absolute; top: 12px; font-weight:bold;
    }

</style>
<div class="right_col">

    <div class="">
        <div class="row">

            <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
                <h3 class="page-title txt-color-blueDark">
                    <i class="fa fa-bars">Earned Credit Allocation</i>

                </h3>
            </div>

          
        </div>

        <div class="x_panel">
            <div class="load-box">
                <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
            </div>
            <div class="x_title">
                <div class="row">

                    <div class="col-sm-3 pul-right ">
                        <div class="form-group">
                            <?php echo $this->form->academic_year_list; ?>
                        </div>   
                    </div>    
                    <div class="col-sm-3 pul-right ">
                        <div class="form-group">
                            <?php echo $this->form->session; ?>
                        </div>   
                    </div>

                    <div class="col-sm-3 pul-right ">
                        <div class="form-group">
                            <?php echo $this->form->degree_id; ?>
                        </div>

                    </div>
                    <div class="col-sm-3 pul-right ">
                        <div class="form-group">
                            <?php echo $this->form->department; ?>
                        </div>

                    </div>

                    <button type="button" id="getRecord" class="btn btn-primary" style="float: right" value="0" >Get Record</button>

                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="x_content">

                <div class="padding-md clearfix">
                    <div class="col-sm-0" style="float:right;">
                       <!-- <a class="btn btn-primary" target="_blank" href="#<?php //echo $this->mainconfig['host'];                               ?>fee-structure/structure-pdf/id/<?php //echo $this->structure_id;    ?>">Print</a>-->
                        <a class="btn btn-link" role="button" href="#" id="print">
                            <span class='glyphicon glyphicon-print'></span></a>
                    </div>
                    <div class="table-responsive" id="studentData"> 

                        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive" style="height: 100%" >
                            <thead>
                                <tr>
                                    <th >S.  No.</th>
                                    <th>Student Name</th>
                                    <th>Father Name</th>
                                    <th>Batch</th>
                                    <th>UID</th>
                                    <th >REG NO.</th>
                                    <th>Exam Roll No.</th>
                                    <th >Earned Credit</th>
                                   
                                </tr>
                            </thead>

                            <tfoot>
                                <tr>
                                    <td colspan="7">Save All</td>
                                    <td ><button type='buttom' class='btn btn-primary' type = "button" >Save All</button></td> 
                                    
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <?php echo $pagination_tr; ?>
                </div><!-- /.padding-md -->
            </div><!-- /panel -->
        </div>
    </div>
</div><!-- /.padding-md -->

<script>
//    setDatatablesManual();

    $('body').on('change', '#academic_year_list', function () {
        $('#department').removeAttr('disabled');
        var year_id = $('#academic_year_list').val();
        if (year_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Session'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#session').empty('');
                $('#session').html(data);
                $('#session').trigger("chosen:updated");
            });
        }
    });
    
    $('body').on('change', '#degree_id', function () {
        $('#department').removeAttr('disabled');
        var degree_id = $('#degree_id').val();
        if (degree_id) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-Get-Dept'; ?>',
                data: {degree_id: degree_id}
            }).done(function (data) {
                $('#department').empty('');
                $('#department').html(data);
                $('#department').trigger("chosen:updated");
            });
        }
    });
    $("#degree_id option").each(function() {
        if($(this).val() == 1 )  
            $(this).show();
        else
            $(this).hide();
    }); 
    $(document).on('click','#getRecord',function() { 
    var session_id = $('#session').val();
    var department_id = $('#department').val();
    var degree_id = $('#degree_id').val();
    //alert(session_id);
    $('.load-box').css('display','block');
    $.ajax({
        type: "POST",
        url: '<?php echo $this->mainconfig['host'] . 'student/ajax-get-student-by-session-for-credits'; ?>',
        
        data: {session_id : session_id,department_id:department_id,degree_id:degree_id}
    }).done(function( data ) {
        $('#studentData').empty('');
        $('.load-box').css('display','none');
        $('#studentData').html(data);
        
    });   
});

//Method used to update checkbox!
    $(document).on('click','input[type="checkbox"]',function () {
         var earned_credit = 0;
        var total_credit=0;
        var id = $(this).data('id');
        var tr_no = $(this).parent('td').parent('tr').index();
        var td_no = $(this).parent('td').index();
            earned_credit = $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').children("table").find("tbody>tr>td>input").val();
            
            
        if ($(this).prop('checked')) {
            
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'master/ajax-get-saved-result'; ?>',
                data: {earned_credit:earned_credit, id: id}
            }).done(function (data) {
              //  if (data = 1){
              
                
                  
            });
        } else  {

           earned_credit = $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').children("table").find("tbody>tr>td>label").text();
         
            


           
            $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + td_no + ')').children('label').remove();
            
        
            $('table>tbody>tr:nth-child(' + (tr_no + 1) + ')').children('td:nth-child(' + (td_no) + ')').children("table").find("tbody>tr>td:nth-child(1)").empty().append("<input type='text'  size='2' data-credit = '"+id+"' class='changebox form-control' name='earned_credit' value='" + (earned_credit?earned_credit:0) + "'/>");
            
   

        }

    });
    
//=========================[END]=================================================================// 

    </script>