<style>

    @media print {

        table td:nth-child(5)

        {

            display:none;

        }

        table th:nth-child(5)

        {

            display:none;

        }

        *{

            visibility:hidden;

        }

        table,th,td 

        {

            visibility:visible;                    

        } 

        .title1

        {

            visibility:visible; 

        }

    }


    .ui-datepicker-calendar {
        display: none;
    }
    .dataTable  tbody {
        width: 100%;

    }

    .bg-primary{
        background-color: #932e90;
    }

    #component_paper_chosen{
        display:none;
    }

</style>

<div class="right_col">
    <div class="load-box">
        <img src="<?php echo $this->mainconfig['publicpath']; ?>/images/loader.gif" width='200px'  class="loder_img1" />
    </div> 
    <?php
    if ($this->type == 'students') {

        if (count($this->messages)) {

            foreach ($this->messages as $message) {
                ?>

                <div class="alert alert-success ">

                    <a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>

                    <?php echo $this->escape($message); ?>

                </div>

                <?php
            }
        }
        ?>

        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> New Applicants </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 

                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <h2 class="title1">New Admission  Records</h2>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive">



                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;">S. No.</th>	
                                        <th style="text-align:center;">Applicant Name</th>
                                        <th style="text-align:center;">Father's Name</th>
                                       
                                        <th style="text-align:center;">Form Id</th>

                                        <th style="text-align:center">Course</th>

                                        
                                        <th style="text-align:center">Pay Status</th>
                                        <th style="text-align:center">Photo</th>
                                        <th style="text-align:center">Admit Card</th>

                                            <!--<th class="no_print" style="text-align:center">Edit | Delete</th>-->



                                    </tr>

                                </thead>

                                <tbody style="text-align:center;">

    <?php
    $geinfo = new Application_Model_Ge();
    $deptinfo = new Application_Model_Department();
    $deptType = new Application_Model_DepartmentType();
    $educdet = new Application_Model_ApplicantCourseDetailModel();


    $i = 1;

    $pagination_tr = '';

    if (count($this->paginator) != 0) {



        foreach ($this->paginator as $results) {

            //print_r($results);die;
            ?>

                                            <tr>

                                                <td><?php
                                echo $i;



                                $i++;
            ?>

                                                </td>	
                                                <td><?php echo $results['applicant_name']; ?></td>
                                                <td><?php echo $results['father_name']; ?></td>
                                                    <?php $edu_details = $educdet->getApplicationCourseDetails($results['form_id']); ?>
                                               

                                                <td><?php echo $results['form_id']; ?></td>

                                                <td><?php echo $deptType->getRecord($results['course'])['department_type']; ?></td>
                                                
                                                <td class='<?php if ($results['payment_status1'] == 1) {
                                            echo 'text-success';
                                        } else {
                                            echo "text-danger";
                                        }; ?>'><?php if ($results['payment_status1'] == 1) {
                                    echo "Paid";
                                } else {
                                    echo "NA";
                                } ?></td>
                                    <td><img src = "/academic/<?= $results['photo']; ?>" width ="70em" alt ='NA'/></td>
									<!--  <td><a class="btn btn-primary" target='_blank' href ='/academic/multi-step-form/document-dashboard/a_id/<?= md5($results['application_no']); ?>'>click here</a></td>-->

                                         <td><a href="<?php echo $this->mainconfig['host']; ?>multi-step-form/index/type/step4/a_id/<?php echo md5($results['application_no']); ?>/role/admin/"target="_blank" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>
           
                                            </tr>            

                                    <?php
                                }

                                $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
                            }
                            ?>

                                </tbody>

                            </table>

    <?php // echo $pagination_tr;  ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->		



<?php } else { ?>
        <div class="">

            <div class="">

                <div class="row">



                    <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">

                        <h3 class="page-title txt-color-blueDark">

                            <i class="fa fa-bars"> New Enroll Applicants </i>



                        </h3>

                    </div>



                    <div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 


                    </div>

                </div>



                <div class="x_panel">



                    <div class="x_title">

                        <div class="col-sm-3 employee_class">
                            <div class="form-group disabled" >
                                <!--<label class="control-label">Academic Year<span class="asterisk">*</span></label>-->
    <?php echo $this->form->academic_year_list; ?>
                            </div>
                        </div>

                        <ul class="nav navbar-right panel_toolbox">

                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>

                            </li>

                            <li class="dropdown">

                                <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>

                            </li>

                            <li><a class=""><i class="fa fa-close"></i></a>

                            </li>

                        </ul>

                        <div class="clearfix"></div>

                    </div>

                    <div class="x_content">



                        <div class="padding-md clearfix table-responsive" id="ajaxData">



                            <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="datatable-responsive">

                                <thead>

                                    <tr>

                                        <th style="text-align:center;">S. No.</th>	


                                        <th style="text-align:center">Course</th>
                                        <th style="text-align:center">Applied Students</th>
                                        <th style="text-align:center">Paid Students</th>


    <!--                                        <th style="text-align:center">Degree</th>-->


                                        <th class="no_print" style="text-align:center">View</th>



                                    </tr>

                                </thead>

                                <tbody style="text-align:center;">

                                    <?php
                                    $geinfo = new Application_Model_Ge();
                                    $deptinfo = new Application_Model_Department();
                                    $deptType = new Application_Model_DepartmentType();
                                    $i = 1;

                                    $pagination_tr = '';

                                    if (count($this->paginator) != 0) {

                                        $totpaid = $totapp = 0;

                                        foreach ($this->paginator as $results) {

                                            //print_r($results);die;
                                            ?>

                                            <tr>

                                                <td><?php
                                        echo $i;



                                        $i++;
                                        ?>

                                                </td>	


                                                <td class='<?php if (!$results['course']) echo "text-danger"; ?>'><?php if ($results['course']) {
                                            echo $deptType->getRecord($results['course'])['department_type'];
                                        } else {
                                            echo "<b>Warning !</b> students without courses...";
                                        } ?></td>
                                                <td data-id = '#totapp' class='app' ><?php echo $results['total_applied'];
                                $totapp += $results['total_applied']; ?></td>
                                                <td data-id='#totpaid' class='paid' ><?php echo $results['paid'];
                                $totpaid += $results['paid']; ?></td>




                                                <td><a href="<?php echo $this->mainconfig['host']; ?>student/form-student/type/students/id/<?php echo $results['course']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a></td>

                                            </tr>            

            <?php
        }

        $pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
    } else {
        ?>
                                        <tr>
                                            <td colspan="5">
                                                <h2 style="color:red">
                                                    No Records Available.
                                                </h2>
                                            </td>
                                        </tr>
    <?php } ?>

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th class="bg-primary text-center" colspan = 2 style="letter-spacing:.3em;">TOTAL STUDENTS</th>
                                        <th class="bg-primary text-center" id="totapp" style="letter-spacing:.3em; font-size:1.3em"><?= $totapp; ?></th>
                                        <th class="bg-primary text-center" id="totpaid" style="letter-spacing:.3em; font-size:1.3em"><?= $totpaid; ?></th>


                                        <th class="bg-primary text-center" id="np" style="letter-spacing:.2em;"><small>Not Paid Students</small> = <?= $totapp - $totpaid; ?></th>
                                    </tr>
                                </tfoot>

                            </table>

    <?php // echo $pagination_tr;  ?>

                        </div><!-- /.padding-md -->

                    </div><!-- /panel -->

                </div>

            </div>

        </div><!-- /.padding-md -->		

<?php } ?>

</div>

<script>

//Added By Kedar:07 Oct 2020

    $('body').on('change', '#academic_year_list', function () {
        let year_id = $('#academic_year_list').val();

        if (year_id) {
            $('.load-box').css('display', 'block');
            $.ajax({
                type: "POST",
                url: '<?php echo $this->mainconfig['host'] . 'student/ajax-get-record-by-year-id'; ?>',
                data: {year_id: year_id}
            }).done(function (data) {
                $('#ajaxData').empty('');
                $('#ajaxData').html(data);
                $('.load-box').css('display', 'none');
            });
        }
    });

</script>

