<div id="content">
<div class="row">
	<div class="col-xs-12">
		<form id="basicForm" action="<?php echo $this->ErpFinanceJournalLedger_form->getAction() ?>" method="post" class="form">		
		   <div class="panel">
				<div class="row" style="margin:0px;">
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">Start Date<span class="asterisk">*</span></label>
							<?php echo $this->ErpFinanceJournalLedger_form->start_date; ?>
							<!-- <input class="form-control start_date" type="text" name="start_date" value="" required="required"> -->
						</div>
					</div>
					 <div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">End Date <span class="asterisk">*</span></label>
							<?php echo $this->ErpFinanceJournalLedger_form->end_date; ?>
							<!-- <input class="form-control end_date" type="text" name="end_date" value="" required="required"> -->
						</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group">
							<div style="float:left">
								<br />							
								<input type="submit" style="margin-top:5px;" class="btn btn-primary" name="submit" value="Submit" onclick="submits();">
							</div>											
						</div>
					</div>					
				</div>
			</div>
		</form>
	</div>
</div>

<?php 
//if ( ( !empty($postvalue['start_date']) ) && ( !empty($postvalue['end_date']) ) ) { ?>
<!-- widget grid -->
<section id="widget-grid" class="">

	<!-- row -->
	<div class="row">

		<!-- NEW WIDGET START -->
		<article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
				<header>
					<span class="widget-icon"> <i class="fa fa-table"></i> </span>
					<h2></h2>

				</header>

				<!-- widget div-->
				<div>		
					<!-- widget content -->
						<div class="widget-body">
							<div class="table-responsive">
								<table style="margin-bottom:0px !important;" class="table table-bordered ">
									<thead>
										<tr>											
											<th colspan="4"></th>
											<th colspan="2" style="text-align:center;">Balance</th>
										</tr>
										<tr>
											<th style="text-align:center;">Date</th>
											<th style="text-align:center;">Particulars</th>
											<th style="text-align:center;">Debit</th>
											<th style="text-align:center;">Credit</th>	
											<th style="text-align:center;">Debit</th>
											<th style="text-align:center;">Credit<?php //echo CURRENCY_TH_SYMBOL;?></th>											
										</tr>
									</thead>
									<tbody>
									<?php	
										$total_items = 0;
										$total_credit = 0;
										$total_debit = 0;
										$total_credit_balance = 0;
										$total_debit_balance = 0;
										$i = 0;
										$account_statement = $this->account_statement;
										if ( count($account_statement) > 0 ) {
											?>											  
											<?php
											$total_items = count($account_statement);
											$k = 0;
											foreach ($account_statement as $val) {	
												$i++;												
												?>
												<tr>
												
													<td style="width:10%;"><?php echo date("d-m-Y ", strtotime($val['date'])); ?></td>
													<td style="width:30%;">
														<?php														
															echo $val['payment_by'];															
														?>														
													</td>
													<td style="text-align:right;width:15%;"><?php
														if( $val['payment_status'] == 5){
															echo $val['paid_amount'];
															$total_debit += $val['paid_amount'];
														}
														?></td>
													<td style="text-align:right;width:15%;">
													<?php
														if( $val['payment_status'] == 4){
															echo $val['paid_amount'];
															$total_credit += $val['paid_amount'];
														}
														?>
													</td>
													<td style="text-align:right;width:15%;">
														<?php 
														if( $total_debit > $total_credit){
															//$total_debit_balance += $total_debit - $total_credit;
															echo $total_debit - $total_credit;
														}														
													  ?>
													</td>
													<td style="text-align:right;width:15%;">
														<?php 
														if( $total_credit > $total_debit){															
															//$total_credit_balance += $total_credit - $total_debit;
															echo $total_credit - $total_debit;
														}														
													  ?>
													</td>
												</tr>
												<?php
												
											}																							
											/*
											 * Vendor Pyments end
											 */
											?>
											<?php
											}
											
											
											if( $total_debit > $total_credit){
												$total_debit_balance = $total_debit - $total_credit;
											}														
										
											if( $total_credit > $total_debit){															
												$total_credit_balance = $total_credit - $total_debit;
											}	 
											
											?>
										<tr>
											<td colspan="" style=" border-right:0px !important;"><b>Total Transactions<b/></td>
											<td style="text-align:right; border-left:0px !important;"><b><?php echo $total_items; ?><b/></td>
											<td style="text-align:right; border-left:0px !important;"><b><?php echo number_format($total_debit, 2); ?><b/></td>
											<td style="text-align:right; border-left:0px !important;"><b><?php echo number_format($total_credit, 2); ?><b/></td>
											<td style="text-align:right; border-left:0px !important;"><b><?php if(!empty($total_debit_balance)) echo number_format($total_debit_balance, 2); ?><b/></td>
											<td style="text-align:right; border-left:0px !important;"><b><?php if(!empty($total_credit_balance)) echo number_format($total_credit_balance, 2); ?><b/></td>

										</tr>

									</tbody>
								</table>
							</div>
						</div>
					<!-- end widget content -->
				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->
		</article>
		<!-- WIDGET END -->
	</div>

	<!-- end row -->
</section>
<!-- end widget grid --> 
</div>
<?php //} ?>
<script type="text/javascript"> 
$(document).ready(function() {  
	$("#start_date").datepicker({ dateFormat: 'yy-mm-dd' });
	$("#end_date").datepicker({ dateFormat: 'yy-mm-dd' });
	//$(".end_date").datepicker({ dateFormat: 'yy-mm-dd' });
	
    /* $(".payment_view").click(function() {			
            var id=$(this).attr("paymentid");            
            $("tr.paymentsitemsdiv").remove();
            $.ajax({
              type: "POST",
               url:"<?php echo SITE_URL.'ajax/pvoucherview';?>",
              data: { name: id }
            }).done(function(data) {
				$( ".purchase-quatation-items-close" ).hide();
                $(data).insertAfter("tr.paymentid"+id);
            });
     });
	 
	  $(".cp_view").click(function() {
            var id=$(this).attr("cpid");            
            $("tr.cpitemsdiv").remove();
            $.ajax({
              type: "POST",
               url:"<?php echo SITE_URL.'ajax/rvoucherview';?>",
              data: { name: id }
            }).done(function(data) {
				$( ".purchase-quatation-items-close" ).hide();
                $(data).insertAfter("tr.cpid"+id);
            });
     });
	 
	 $(".petty_cash_view").click(function() {
            var id=$(this).attr("pettycashid");            
            $("tr.pettycashiddiv").remove();
            $.ajax({
              type: "POST",
               url:"<?php echo SITE_URL.'ajax/pettycashview';?>",
              data: { name: id }
            }).done(function(data) {
				$( ".purchase-quatation-items-close" ).hide();
                $(data).insertAfter("tr.pettycashid"+id);
            });
     }); */

}); 

</script>
<?php 

function no_to_words($no)
{   
 $words = array('0'=> '' ,'1'=> 'one' ,'2'=> 'two' ,'3' => 'three','4' => 'four','5' => 'five','6' => 'six','7' => 'seven','8' => 'eight','9' => 'nine','10' => 'ten','11' => 'eleven','12' => 'twelve','13' => 'thirteen','14' => 'fouteen','15' => 'fifteen','16' => 'sixteen','17' => 'seventeen','18' => 'eighteen','19' => 'nineteen','20' => 'twenty','30' => 'thirty','40' => 'fourty','50' => 'fifty','60' => 'sixty','70' => 'seventy','80' => 'eighty','90' => 'ninty','100' => 'hundred &','1000' => 'thousand','100000' => 'lakh','10000000' => 'crore');
    if($no == 0)
        return ' ';
    else {
	$novalue='';
	$highno=$no;
	$remainno=0;
	$value=100;
	$value1=1000;       
            while($no>=100)    {
                if(($value <= $no) &&($no  < $value1))    {
                $novalue=$words["$value"];
                $highno = (int)($no/$value);
                $remainno = $no % $value;
                break;
                }
                $value= $value1;
                $value1 = $value * 100;
            }       
          if(array_key_exists("$highno",$words))
              return $words["$highno"]." ".$novalue." ".no_to_words($remainno);
          else {
             $unit=$highno%10;
             $ten =(int)($highno/10)*10;            
             return $words["$ten"]." ".$words["$unit"]." ".$novalue." ".no_to_words($remainno);
           }
    }
}

function convert_number($number)
{
if (($number < 0) || ($number > 999999999))
{
throw new Exception("Number is out of range");
}
 
$Gn = floor($number / 100000);  /* Millions (giga) */
$number -= $Gn * 100000;
$kn = floor($number / 1000);     /* Thousands (kilo) */
$number -= $kn * 1000;
$Hn = floor($number / 100);      /* Hundreds (hecto) */
$number -= $Hn * 100;
$Dn = floor($number / 10);       /* Tens (deca) */
$n = $number % 10;               /* Ones */
 
$res = "";
 
if ($Gn)
{
$res .= convert_number($Gn) . " Lacs";
}
 
if ($kn)
{
$res .= (empty($res) ? "" : " ") .
convert_number($kn) . " Thousand";
}
 
if ($Hn)
{
$res .= (empty($res) ? "" : " ") .
convert_number($Hn) . " Hundred";
}
 
$ones = array("", "One", "Two", "Three", "Four", "Five", "Six",
"Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen",
"Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eightteen",
"Nineteen");
$tens = array("", "", "Twenty", "Thirty", "Fourty", "Fifty", "Sixty",
"Seventy", "Eigthy", "Ninety");
 
if ($Dn || $n)
{
if (!empty($res))
{
$res .= " and ";
}
 
if ($Dn < 2)
{
$res .= $ones[$Dn * 10 + $n];
}
else
{
$res .= $tens[$Dn];
 
if ($n)
{
$res .= "-" . $ones[$n];
}
}
}
 
if (empty($res))
{
$res = "zero";
}
 
return $res;
}

?>