<div class="right_col">
<?php if ($this->type) { ?>
<div class="padding-md">
	<div class="row">
		<div class="col-md-12 " >
		<h3 class="page-title txt-color-blueDark" >
			<div><i class="fa fa-eye"> Fee Heads</i></div>
		</h3>
			<div class="panel panel-default">
				<form class="no-margin" id="formValidate1" action="<?php echo $this->form->getAction() ?>" method="post" data-validate="parsley" >
					
					<div class="panel-body">
						  <div class="row">

							<div class="col-sm-3 employee_class">
                            <div class="form-group" >
                            <label  class="control-label" >Fee Category<span class="asterisk">*</span></label>
                            <?php echo $this->form->feecategory_id; ?>
                            </div>
							</div>
						
							<div class="col-sm-3 employee_class">
                            <div class="form-group">
                            <label class="control-label">Fee Heads Name<span class="asterisk">*</span></label>
                            <?php echo $this->form->feehead_name; ?>
                            </div>
							</div>
							
							</div>
							
					<!--	 <?php /* if(count($this->item_result)>0){
							//		print_r($this->item_result);die;
							$i=0;
						   foreach($this->item_result as $val){ 
						$i++; */
					?>
					<div class="row" id="" style="">
					
							<div class="col-sm-3">
							<label>Fee Head Name<span class="asterisk">*</span></label>
							<input type="text"  label="feehead_name_<?php // echo $i;?>"  class="form-control feehead_name" name="Fee[feehead_name][]" placeholder="" value="<?php echo $val['feehead_name'];?>"/> 
							</div>				  
													
						<a href="#" class="removeclass btn btn-primary remove_class" style="padding:7px 15px;margin:24px 15px; ">-</a>
						</div>   
					<?php // } ?>
					 <div class="col-sm-3"></div>    
					<input type="button" value="+" id="AddButton" class="btn btn-primary adjust-size" style="padding:7px 15px;margin-left:9px;">
					
					<?php  // }  else {    ?>
					 
		<input type="hidden" name="count_val" id="count_val" value="1" class="count_val" />  
		<div class="row" style="">
	
		<div class="col-sm-3"><label> Fee Head Name <span class="asterisk">*</span></label> <input type="text"  label="feehead_name_0"  class="form-control" name="Fee[feehead_name][]" style="" placeholder="Name" value="" /> 
		</div>
            <input type="button" value="+" id="AddButton" class="btn btn-primary adjust-size" style="padding:7px 15px;margin:24px 15px;"> 
       	
		
	</div>
	<?php // } ?>
       <div id="fields">
         <div class="padding-top"></div>
        </div>   -->
					</div>
					<div>
						<div class="panel-footer">									
							<div class="row">
								<div class="col-sm-7 col-sm-offset-5">
									<?php if ($this->type == 'add') { ?> 
										<div style="float:left;margin-right:2px;">
										<button class="btn btn-primary submit">Submit</button>
										</div>
										<div style="float:left;padding:0px 10px;">
										<button type="reset" class="btn btn-danger btn-default">Reset</button>
										</div>
									<?php } else { ?>
										<div style="float:left;">
										<button class="btn btn-primary submit">Update</button>
										</div>
										<div style="float:left;">
										<a class="btn btn-primary" href="<?php echo $this->mainconfig['host']; ?>fee-heads/index/">Back</a>
										</div>
										<?php }		?>
								</div>
							</div>
						</div>
					</div>
				</form>
			</div><!-- /panel -->
		</div><!-- /.col-->				
	</div><!-- /.row -->
	
</div><!-- /.padding-md -->	
<?php } else { ?>
  
<?php if (count($this->messages))   { 
    foreach ($this->messages as $message) {?>
     <div class="alert alert-success ">
<a type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</a>
<?php echo $this->escape($message); ?>
</div>
 <?php } } ?>
 <!-- widget grid -->
<div class="">
	<div class="">
		<div class="row">
			
			<div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
		<h3 class="page-title txt-color-blueDark">
			<i class="fa fa-bars"> Fee Heads</i>
				
		</h3>
	</div>
			
		<div class="col-xs-12 col-sm-5 col-md-5 col-lg-8">	 
			
			<a class="btn btn-primary pull-right" style="margin-top: 25px;" href="<?php echo $this->mainconfig['host']; ?>fee-heads/index/type/add">Add </a>
		</div>
		</div>
		
		<div class="x_panel">
               
                    <div class="x_title">
                    <h2>Fee Heads</h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                       </li>
                      <li><a class=""><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
<div class="x_content">
		
		<div class="padding-md clearfix">
			<table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable">
				<thead>
					<tr>
						<th style="text-align:center;">S. No.</th>	
						<th style="text-align:center;">Fee Category</th>
						<th style="text-align:center;">Fee Heads Name</th>
						<th style="text-align:center;">Action</th>
					</tr>
				</thead>
				<tbody style="text-align:center;">
					<?php

						$i = 1;
						$pagination_tr = '';
						if (count($this->paginator) != 0) {

						foreach ($this->paginator as $results) {
						//print_r($results);die;

					?>
							<tr>
								<td><?php echo $i;

									$i++; ?>
								</td>						
								
								
								<td><?php echo $results['category_name']; ?></td>
								
								<td><?php echo $results['feehead_name']; ?></td>
								
								<td><a href="<?php echo $this->mainconfig['host']; ?>fee-heads/index/type/edit/id/<?php echo $results['feehead_id']; ?>" class="edit" title="Edit"><span class="fa fa-edit fa-lg"></span></a>&nbsp; | &nbsp;  <a href="<?php echo $this->mainconfig['host']; ?>fee-heads/index/type/delete/id/<?php echo $results['feehead_id']; ?>" onclick="return ConfirmDelete();" title="Delete" class="delete"> <span class="fa fa-trash-o fa-lg"></span> </a></td>

							</tr>            

						<?php }
						$pagination_tr = $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml');
						} ?>

				</tbody>
			</table>
			 <?php echo $pagination_tr; ?>
		</div><!-- /.padding-md -->
	</div><!-- /panel -->
	</div>
	</div>
</div><!-- /.padding-md -->		
<?php } ?>
</div>
<script>	
 
	
	function ConfirmDelete()
	{
	var x = confirm("Are you sure you want to delete?");
	if(x)
		return true;
	else
		return false;
	}


/*
var count = $('#count_val').val(); //Addmore script code

$("body").on("click","#AddButton",function(event){
		var count_value = count++;
		//alert(count_value);
		append_html = '<div class="row">';
		
		append_html += '<div class="col-sm-3 employee_class" style=""><label class="control-label "></label><input type="text"  class="form-control ec"  name="Fee[feehead_name][]"  style=" background:#FFFFFF;" label="feehead_name_'+count_value+'"   /></div>';
		append_html += '<a href="#" class="removeclass6 btn btn-primary remove_class6 " style="padding:7px 15px;margin:20px 15px;">-</a>';
		append_html += '</div>';	
        $('#count_val').append(count_value);		
		$('#fields').append(append_html);
		
		});
		$("body").on("click",".removeclass6", function(e){
		//alert('sdsd');

                $(this).parent('div').remove(); 				
				
        return false;

    });  */
	

</script>
