<div class="col-md-12">
<?php //echo '<pre>'; print_r($this->paginator);exit; ?>
    <div class="table-responsive" id="studentData"> 
        <table class="table table-striped table-bordered mb30 jambo_table bulk_action" id="dataTable"  >
            <thead>
                <tr>
                    <th>S.No.</th>
                    <th> Fee heads Name </th>
                    

                </tr>
            </thead>
           
            <tbody>
                <?php 
                $i=1;
                foreach ($this->paginator as $key => $value) { 
                    
                    ?>
                   
                <tr>	
                    <td><?php echo $i; ?></td>
                    <td><?php echo $value['feehead_name']; ?></td>
                    <input type="hidden" name="feehead_name[]" value="<?= $value['feehead_name'] ?>" />
                    <input type="hidden" name="feecategory_id[]" value="<?= $value['feecategory_id'] ?>" />
                    
                <tr>
                <?php  $i++; }?>

            </tbody>
            
        </table>
    </div>
</div>
<script>
    setDataTables();
</script>